### ISSUE TITLE
Add Local Attention

### ISSUE THREAD

**Issue by renzhe0009** [OpenNMT/OpenNMT-py#100]
Are there plans to add a PyTorch implementation of "Local Attention" from？
I saw the implementation of "Local Attention" was in [OpenNMT](https://github.com/OpenNMT/OpenNMT/pull/329) .

Thanks in advance.

**Comment by srush** [comment]
Yup, we can do this. Any interest in working on it?

**Comment by renzhe0009** [comment]
I am so sorry that I am a beginner in pytorch.
I'm just trying to do NMT from Luong‘s [matlab](https://github.com/lmthang/nmt.matlab) to python.Still learning.
 (;´༎ຶД༎ຶ`)

**Comment by JianyuZhan** [comment]
I would like to undertake this work, while at it, I so plan to refactor with `GlobalAttention.py` with it to create a uniform attention module exposed to the `*Encoder`/`*Decoder` models.

**Comment by srush** [comment]
Let's do this one later.

**Comment by JianyuZhan** [comment]
Okay, I will finish the most urgent works first.

**Comment by vince62s** [comment]
unless someone is highly motivated to do this feature, closing for now this old request.
feel free to reopen.

**Comment by t1war1** [comment]
Any plans to implement this feature?
