### ISSUE TITLE
[Help wanted] preprocessing shuffling

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT-py#1006]
I just commited a change to raise an error when using the -shuffle flag in preprocess.py
Doc was not in line with code. (never implemented)

The point is as follow:
We could use the torchtext shuffling capability as long as we do not shard.
However since torchtext does not support data streaming we had to implement sharding to avoid memory overflow.
Hence data need to shuffled before sharding.
This can be done in bash but if someone is interested to do this n preprocess.py, welcome.
Cheers.

**Comment by JoostvDoorn** [comment]
I have implemented shuffling inside `build_save_in_shards_using_shards_size`, I can make a pull request for this later.

**Comment by vince62s** [comment]
@JoostvDoorn code base has changed but do you intend to submit a PR soon ?
thanks.

**Comment by JoostvDoorn** [comment]
I created a pull request for the solution which I used, this made more sense when `build_save_in_shards_using_shards_size` was still part of the codebase, but this works as long as you have enough memory.

**Comment by 1-800-BAD-CODE** [comment]
I see the PR to solve this is still in limbo.

Would there be any interest if I wrote an external Python library to handle stuff like this? It could be useful for other NMT preprocessing tasks as well, I will expand the discussion on the forum if there seems to be initial interest. 

E.g., an interface like
```
from bitext_tools import BitextShuffler as Shuffler

Shuffler shuffler(path_to_src_file, path_to_tgt_file)

# Yields random bitext pairs without loading entire files into memory
for src, tgt in shuffler.random_yield():
    # create example
```
