### ISSUE TITLE
coverage loss and copy mechanism

### ISSUE THREAD

**Issue by falcondai** [OpenNMT/OpenNMT-py#101]
Per Abigail See et al's paper https://arxiv.org/abs/1704.04368, the coverage loss should be *independent* of whether to use the copy mechanism or not. Currently, they are not independent: https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Loss.py#L178

- [ ] find a better and consistent name for `copy_loss`: copy
- [ ] change the associated CLI arguments
- [x] fix the train/val (approximate) accuracy calculation
- [ ] move UNK mask computation to preprocessing
- [ ] test

**Comment by srush** [comment]
I don't think I understand the issue here. They are implemented as independent. 

Also can you make this in Projects and not an issue?

**Comment by srush** [comment]
Think these are basically working now?
