### ISSUE TITLE
Does this project support multiple encoders?

### ISSUE THREAD

**Issue by Runingtime** [OpenNMT/OpenNMT-py#1014]
Hi,
I want to know how I can train a seq2seq model with multiple encoders  e.g. two RNNs instead of one. Do I need to write from the scratch or just modify some configurations? Thanks!

**Comment by Runingtime** [comment]
> same as #744 ?

Yes.  Has it been implemented?

**Comment by vince62s** [comment]
no, the other issue is still open ... but onmt-tf has it already if you really want to test it.
