### ISSUE TITLE
Ensemble translate does not support copy_attn

### ISSUE THREAD

**Issue by Runingtime** [OpenNMT/OpenNMT-py#1018]
Hi,
I tried to average two checkpoints but got the following error:

> Traceback (most recent call last):
  File "../OpenNMT-py/translate.py", line 36, in <module>
    main(opt)
  File "../OpenNMT-py/translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/data/comp/OpenNMT-py/onmt/translate/translator.py", line 222, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/data/comp/OpenNMT-py/onmt/translate/translator.py", line 326, in translate_batch
    return self._translate_batch(batch, data)
  File "/data/comp/OpenNMT-py/onmt/translate/translator.py", line 619, in _translate_batch
    src_map)
TypeError: forward() takes 2 positional arguments but 4 were given

The command option is -model models/baseline_step_140000.pt models/baseline_step_160000.pt 
How to solve this problem?

**Comment by vince62s** [comment]
Not sure what you're trying to accomplish.
Ensemble.py: will ensemble 2 checkpoints from 2 runs (or N)
averaging (seems what you're trying to do) will average checkpoints in time of a run.
But you need to average before translationg.
you trace seems to show you're running a translation directly. won't work.

**Comment by Runingtime** [comment]
Sorry. 
I just want to use multiple checkpoints for translation by following this FAQ  [http://opennmt.net/OpenNMT-py/FAQ.html#how-can-i-ensemble-models-at-inference](url). 
Is this the correct way to average checkpoints at inference?

**Comment by vince62s** [comment]
Give your full command line

**Comment by Runingtime** [comment]
Here is the full command line:
```
python ../OpenNMT-py/translate.py \
-batch_size 20 \
-beam_size 5 \
-model models/cnndm_step_140000.pt models/cnndm_step_160000.pt \
-src data/cnndm/val.txt.src \
-output testout/cnndm.out \
-min_length 9 \
-max_length 25 \
-stepwise_penalty \
-coverage_penalty summary \
-beta 5 \
-length_penalty wu \
-alpha 0.9 \
-block_ngram_repeat 3 \
-ignore_when_blocking "." "</t>" "<t>" \
-replace_unk
```

**Comment by vince62s** [comment]
okay, is the same command line with only one model working fine ?

**Comment by Runingtime** [comment]
> okay, is the same command line with only one model working fine ?

yes

**Comment by vince62s** [comment]
@Waino was your code supposed to support copy_attn ?

**Comment by vince62s** [comment]
can you please pull and run it again, I don't understand the error.
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translator.py#L654-L656
it takes 3 arguments so I don't get why the error says 2 vs 4
thanks.

**Comment by vince62s** [comment]
did you modify the code ?

**Comment by Runingtime** [comment]
The error is still the same  at inference after I run the git pull command. You can try the example of text summarization in the document if possible, in  case I missed something.

**Comment by vince62s** [comment]
please repost the error trace lines have changed.

**Comment by Runingtime** [comment]
> Traceback (most recent call last):
  File "../OpenNMT-py/translate.py", line 36, in <module>
    main(opt)
  File "../OpenNMT-py/translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/data/comp/OpenNMT-py/onmt/translate/translator.py", line 223, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/data/comp/OpenNMT-py/onmt/translate/translator.py", line 327, in translate_batch
    return self._translate_batch(batch, data)
  File "/data/comp/OpenNMT-py/onmt/translate/translator.py", line 656, in _translate_batch
    src_map)
TypeError: forward() takes 2 positional arguments but 4 were given

**Comment by vince62s** [comment]
yes that can't work as is.
if you can try the following patch, in here:
https://github.com/OpenNMT/OpenNMT-py/blob/49185121e46c4f65d68101590bad231a8dd73e4f/onmt/decoders/ensemble.py#L92-L101

def forward(self, hidden, attn, src_map):
        """
        Compute a distribution over the target dictionary
        by averaging distributions from models in the ensemble.
        All models in the ensemble must share a target vocabulary.
        """
        distributions = [model_generator(hidden[i], attn[i], src_map[i])
                         for i, model_generator
                         in enumerate(self.model_generators)]
        return torch.stack(distributions).mean(0)

let me know if it works
but it won't in the non copy mode

**Comment by Runingtime** [comment]
It raised another error:

> Traceback (most recent call last):
  File "../OpenNMT-py/translate.py", line 36, in <module>
    main(opt)
  File "../OpenNMT-py/translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/data/comp/OpenNMT-py/onmt/translate/translator.py", line 223, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/data/comp/OpenNMT-py/onmt/translate/translator.py", line 327, in translate_batch
    return self._translate_batch(batch, data)
  File "/data/comp/OpenNMT-py/onmt/translate/translator.py", line 656, in _translate_batch
    src_map)
  File "/data/comp/OpenNMT-py/onmt/decoders/ensemble.py", line 98, in forward
    distributions = [model_generator(hidden[i], attn[i], src_map[i]) for i, model_generator in enumerate(self.model_generators)]
  File "/data/comp/OpenNMT-py/onmt/decoders/ensemble.py", line 98, in <listcomp>
    distributions = [model_generator(hidden[i], attn[i], src_map[i]) for i, model_generator in enumerate(self.model_generators)]
  File "/home/server3/.conda/envs/master/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/comp/OpenNMT-py/onmt/modules/copy_generator.py", line 86, in forward
    batch_by_tlen_, slen = attn.size()
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by vince62s** [comment]
can you make sure your pull was after this fix:
https://github.com/OpenNMT/OpenNMT-py/commit/513c06899d9cbc95c827083ba8e2b2ed52461f42

**Comment by Runingtime** [comment]
> can you make sure your pull was after this fix:
> [513c068](https://github.com/OpenNMT/OpenNMT-py/commit/513c06899d9cbc95c827083ba8e2b2ed52461f42)

Yes. I just pulled the latest version yesterday. Manual inspection also confirms it. And I think the above ValueError is not related to this file.

**Comment by vince62s** [comment]
I will have to dig then.
what model did you train ? transformer or RNN ?

**Comment by Runingtime** [comment]
The model is a pointer-generator(i.e., RNN) and the commands are described in [the example](http://opennmt.net/OpenNMT-py/Summarization.html).

**Comment by vince62s** [comment]
in my patch, change 
distributions = [model_generator(hidden[i], attn[i], src_map[i])
to
distributions = [model_generator(hidden[i], attn, src_map)

it should work.

**Comment by Runingtime** [comment]
It really works.
Thank you for your time and effort in fixing this issue!
