### ISSUE TITLE
Translate.py runs faster on CPU than GPU

### ISSUE THREAD

**Issue by tanaka-jp** [OpenNMT/OpenNMT-py#1027]
I found that the translate.py runs faster on CPU than GPU. (OpenNMT ver 0.2)
On GPU, It needs 20seconds for one batch which on CPU is just 17.3seconds.
  (-share_vocab -max_length 50 -block_ngram_repeat 5 -beam_size 5)

It means that I can use one PC to train my model and use another to run translate.
It sounds good.

**Comment by tanaka-jp** [comment]
Now, I am running them on one PC.
And they are working well.

Train works as usual and translation works faster than usual.
And I don't need to worry about the OutOfGpuMemory.

I will test it for this weekend.

**Comment by vince62s** [comment]
not sure about what your command lines are (batch_size for inference, ...) but translate is much faster on GPU  than CPU in most cases.
Please use the forum for this discussion as you are not reporting a bug.
Thanks
