### ISSUE TITLE
help ,which code did you split the dataset for multi gpu training?

### ISSUE THREAD

**Issue by mjc14** [OpenNMT/OpenNMT-py#1028]
hi,
    i want to understand your code clearly, i can't find which code  that  you split the dataset for multi gpu training . could you give me some idea?

             thx

**Comment by vince62s** [comment]
please read the doc or this:
https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md

**Comment by mjc14** [comment]
sorry,i can run it  with multi gpus, but  i mean i can't find any codes in  OpenNMT-py/onmt/inputters/inputter.py , which is to split dataset for multi gpus.  or any where? did you use the same data for different gpus?

**Comment by vince62s** [comment]
it happens here:
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/trainer.py#L149

the dataset is iterated sequentially but each worker takes a modulo N of batches

**Comment by mjc14** [comment]
thx
