### ISSUE TITLE
do you have a plan to implement BERT in your model?

### ISSUE THREAD

**Issue by mjc14** [OpenNMT/OpenNMT-py#1040]
@vince62s

**Comment by vince62s** [comment]
contribution welcome but not in the short term.

**Comment by anupamsingh610** [comment]
is BERT applicable to Translation task? It is not apparent from the paper itself. I'm eager to contribute if it can be used.

**Comment by arijitx** [comment]
A BERT encoder can be very helpful with this library, anyone willing to contribute?

**Comment by vince62s** [comment]
Guys, BERT fine-tuning is there !
can someone test it on a specific task ?

**Comment by francoishernandez** [comment]
@Zenglinxiao made [a nice guide / tutorial available on the forum](http://forum.opennmt.net/t/opennmt-py-bert-tutorial/3015).
(Will be in the FAQ of the docs when it's merged.)
