### ISSUE TITLE
mask is set to None in the TransformerDecoderLayer

### ISSUE THREAD

**Issue by BigKaiju** [OpenNMT/OpenNMT-py#1044]
Hi guys,

In the TransformerDecoderLayer (in [onmt/decoders/transformer.py](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/transformer.py)), we can read at lines 69-72:
`dec_mask = torch.gt(tgt_pad_mask +
                            self.mask[:, :tgt_pad_mask.size(1),
                                      :tgt_pad_mask.size(1)], 0)
dec_mask = None`

I get the first operation (set the mask's size to the target's size and set ones for pad&future tokens), but I'm confused by the immediate voiding of the operation by `dec_mask = None`.

Can someone tell me what's happing here ?

Cheers,

**Comment by vince62s** [comment]
Sorry my mistake. I'll fix it.

**Comment by vince62s** [comment]
fixed in #1045
