### ISSUE TITLE
How to build model parallelism ?

### ISSUE THREAD

**Issue by KelleyYin** [OpenNMT/OpenNMT-py#1047]
In this program , we already built data parallelism for multi-gpu training. However, I need to build two model in my program , but the cuda memory overflowed . 
Therefore, I want to use model  parallelism, two model can be distributed trained in different GPUs. 
The final loss consists of two parts, one part is independent and an other is joint.
Could anybody give suggestions ?

**Comment by vince62s** [comment]
I am not sure what you are trying to accomplish but please use the forum since it's not really an issue of the code.

**Comment by KelleyYin** [comment]
@vince62s 
Could you please post OpenNMT forum ?
Thank you !
