### ISSUE TITLE
Dialog System based pretrained model

### ISSUE THREAD

**Issue by abaheti95** [OpenNMT/OpenNMT-py#1053]
Hi,
I recently found that you have uploaded a pre-trained model of Opensubtitles based dialog system ([here](http://opennmt.net/Models-py/)). Thank you so much for that contribution. However, I have many doubts regarding that.

I downloaded the training dataset and it downloaded all the compressed subtitles files from various movies. This raises a lot of questions:
- Could you specify how it was preprocessed for this data? 
- What tokenizer was used? 
- How many previous turns in the context?
- How many total training and validation instances? What was the train/test split?

Eagerly waiting for the clarifications!

**Comment by vince62s** [comment]
I am not sure but I think this is the equivalent of what was described here:
http://forum.opennmt.net/t/english-chatbot-model-with-opennmt/184/3
Anyway, better place to discuss is the forum. Thanks.
