### ISSUE TITLE
No saved .pt file after training job

### ISSUE THREAD

**Issue by floris1946** [OpenNMT/OpenNMT-py#1059]
Hi all,

I'm having a little issue. I'm trying OpenNMT on a small Ge'ez script corpus. To verify if OpenNMT handles the data well, I'm adding 10 Ge'ez lines to the test and train datasets and running a training job of 300 train steps. The goal fow now is not to create a great translation engine, but testing if a job can be finished using the Ge'ez script.
Preprocessing goes well, but after a training job, no model file is saved anywhere. I'm using the exact same commands as the readme provides. The only difference is that I have added Ge'ez lines (and their English translations) to the src and tgt datasets, and changing the number of train steps (adding "-train_steps=300" to the training command)

Is this the result of a training not going well?

**Comment by sebastianGehrmann** [comment]
There is a command `save_checkpoint_steps` that is by default set to 5000. Try decreasing this to <300 and it should work.

**Comment by eduamf** [comment]
I set the `save_checkpoint_steps` parameter and didn't save anything.

**Comment by vince62s** [comment]
post your full command line.
