### ISSUE TITLE
When will OPEN-NMT update itself following Pytorch 1.0 ?

### ISSUE THREAD

**Issue by ColainCYY** [OpenNMT/OpenNMT-py#1068]
Hi，Pytorch 1.0 help a lot for deploying a NMT system. I wonder whether Pytorch 0.4.0 can get satisfactory performance, for delpoying rather than research.

Will OPENNMT transfer to Pytorch 1.0 in the future?
Thanks!

**Comment by vince62s** [comment]
It does work already with Pytorch 1.0rc
The only thing is, some unittest are failing, we need to dig, but you can train and translate.
