### ISSUE TITLE
Translate.py for summarization returning error

### ISSUE THREAD

**Issue by krishnateja614** [OpenNMT/OpenNMT-py#1070]
(base) C:\Users\Murali\Downloads\OpenNMT-py-master\OpenNMT-py-master>python translate.py -gpu 1 -batch_size 10 -beam_size 2 -model demo_model_step_15000.pt -src test.txt.src -output test.out -max_len

Traceback (most recent call last):
  File "translate.py", line 33, in <module>
    main(opt)
  File "translate.py", line 19, in main
    attn_debug=opt.attn_debug)
  File "C:\Users\Murali\Downloads\OpenNMT-py-master\OpenNMT-py-master\onmt\translate\translator.py", line 191, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "C:\Users\Murali\Downloads\OpenNMT-py-master\OpenNMT-py-master\onmt\translate\translator.py", line 295, in translate_batch
    return self._translate_batch(batch, data)
  File "C:\Users\Murali\Downloads\OpenNMT-py-master\OpenNMT-py-master\onmt\translate\translator.py", line 595, in _translate_batch
    batch, data_type)
  File "C:\Users\Murali\Downloads\OpenNMT-py-master\OpenNMT-py-master\onmt\translate\translator.py", line 305, in _run_encoder
    src, src_lengths)
  File "C:\Users\Murali\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Murali\Downloads\OpenNMT-py-master\OpenNMT-py-master\onmt\encoders\transformer.py", line 102, in forward
    emb = self.embeddings(src)
  File "C:\Users\Murali\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Murali\Downloads\OpenNMT-py-master\OpenNMT-py-master\onmt\modules\embeddings.py", line 203, in forward
    source = module(source, step=step)
  File "C:\Users\Murali\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Murali\Downloads\OpenNMT-py-master\OpenNMT-py-master\onmt\modules\embeddings.py", line 41, in forward
    emb = emb + self.pe[:emb.size(0)]
RuntimeError: The size of tensor a (17382) must match the size of tensor b (5000) at non-singleton dimension 0

Using the latest version of OpenNMT-py, and pytorch version 0. 41 .Am I missing anything?

**Comment by vince62s** [comment]
I don't get this error when I translate a transformer trained summarization model.

can you post your training command line ?

**Comment by krishnateja614** [comment]
This is my command line for training 
python train.py -save_model demo_model -data E:\data_dir\ -gpu_ranks 0 1 -encoder_type transformer -decoder_type transformer -position_encoding -layers 2 -rnn_size 512 -word_vec_size 512 -transformer_ff 2048 -heads 8

I used the model after the third checkpoint. The dataset is not the same one given in the summarization example code. I am using another dataset but I ran the preprocessing code on them before training and it worked fine

python preprocess.py -train_src train.txt.src -train_tgt train.txt.tgt.tagged -valid_src val.txt.src -valid_tgt val.txt.tgt.tagged -save_data E:\data_dir\ -src_seq_length 10000 -tgt_seq_length 10000 -src_seq_length_trunc 400 -tgt_seq_length_trunc 100 -dynamic_dict -share_vocab -shard_size 524288000

**Comment by krishnateja614** [comment]
yes the vocab size is 17382 but the 5000 is coming from the default max_len parameter in PositionalEncoding function. I added the print statements to the same i.e

class PositionalEncoding(nn.Module):
    """
    Implements the sinusoidal positional encoding for
    non-recurrent neural networks.

    Implementation based on "Attention Is All You Need"
    :cite:`DBLP:journals/corr/VaswaniSPUJGKP17`

    Args:
       dropout (float): dropout parameter
       dim (int): embedding size
    """

    def __init__(self, dropout, dim, max_len=5000):
        pe = torch.zeros(max_len, dim)
        position = torch.arange(0, max_len).unsqueeze(1)
        div_term = torch.exp((torch.arange(0, dim, 2, dtype=torch.float) *
                             -(math.log(10000.0) / dim)))
        pe[:, 0::2] = torch.sin(position.float() * div_term)
        pe[:, 1::2] = torch.cos(position.float() * div_term)
        pe = pe.unsqueeze(1)
        super(PositionalEncoding, self).__init__()
        self.register_buffer('pe', pe)
        self.dropout = nn.Dropout(p=dropout)
        self.dim = dim

    def forward(self, emb, step=None):
        emb = emb * math.sqrt(self.dim)
        if step is None:
            print(emb.size(0))#prints 17382
            print(emb.size(1))#prints 10
            print(self.pe.size(0))#prints 5000
            emb = emb + self.pe[:emb.size(0)]
        else:
            emb = emb + self.pe[step]
        emb = self.dropout(emb)
        return emb

**Comment by vince62s** [comment]
anyway where you have your "prints"
print emb.size() and self.pe.size()
they should be [src_len x batch x hidden]
for self.pe src_len = max_len = 5000
otherwise something is wrong.

**Comment by krishnateja614** [comment]
I am training a new model closer to the one given in the summarization link, I will try your suggestion and post the results for the old model once the first checkpoint is saved. Thanks for your help.

**Comment by krishnateja614** [comment]
The new model is trained and I tested the translate.py on valid.txt.src and it is giving the summarizations but when ran with exact same parameters on test.txt.src, fails with the same error "RuntimeError: The size of tensor a (5793) must match the size of tensor b (5000) at non-singleton dimension 0"

emb.size() = [5793,5,512]
self.pe.size() == [5000,1,512]

**Comment by vince62s** [comment]
what is the max sequence length you used at preprocessing time ?

**Comment by vince62s** [comment]
closing, reopen if needed.
