### ISSUE TITLE
Pruning options during preprocessing

### ISSUE THREAD

**Issue by monsieurzhang** [OpenNMT/OpenNMT-py#1075]
HI,

Could anyone help to clarify these 4 options used during preprocessing?

-src_seq_length [50] Maximum source sequence length
-src_seq_length_trunc [] Truncate source sequence length.
-tgt_seq_length [50] Maximum target sequence length to keep.
-tgt_seq_length_trunc [] Truncate target sequence length.

It seams by default, the source sentences which are longer than 50 tokens will not be used for further training.
Then, what does the option src_seq_length_trunc do?
If I set e.g. "-src_seq_length 50 -src_seq_length_truc 100",  whether the second option does not take effect? or it is related with features?

Thank you.

**Comment by vince62s** [comment]
If I recall properly, it will first truncate to 100, and then retain only segments of 50 max.
So in this case, useless.

**Comment by monsieurzhang** [comment]
Thanks, Vincent,

The reason I looked into these options is that during my training, the system met an unexpected "OUT OF MEMORY" problem.
I checked but found no any suspecious configurations.
And when I relaunch the training, it works smoothly.

**Comment by vince62s** [comment]
Did you shard ? onmt-py uses torchtext which is not so good at memory optimization. If you don't shard and if you handle more than 1M segments you may have OOM issues.
I use shard_size 1000000 most of the time.

**Comment by monsieurzhang** [comment]
I suppose yes, because by default the shard_size is 1000000.
https://github.com/OpenNMT/OpenNMT-py/blob/22b30ee890805534594d7b048722d8a292f87b24/onmt/opts.py#L192
Thanks.
