### ISSUE TITLE
Question about Truncated Decoder

### ISSUE THREAD

**Issue by swiseman** [OpenNMT/OpenNMT-py#1076]
Hi all,

From the relevant lines in [trainer.py](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/trainer.py#L282), [model.py](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/models/model.py#L44), and [decoder.py](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/decoder.py#L119) it looks to me like the truncated decoder RNN's state is always initialized with a function of the encoder, even _after_ the first truncation block, and I was wondering whether this was intentional. 

In particular, when I played around with truncating decoders for [data-to-document generation](https://arxiv.org/pdf/1707.08052.pdf), it seemed helpful to initialize the truncated decoder's hidden state at truncation block i with the final state of the decoder in truncation block i-1. It also looks like the current code would actually do this by itself if not for the call to [init_state()](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/models/model.py#L44) each time we call forward() on the model (and so a simple fix would be to pass a flag indicating whether to init_state() again). If this sounds reasonable, would you be interested in a PR with this change?

Thanks!

**Comment by vince62s** [comment]
a PR is always welcome, but it could be even better if you could test and make the point showing it gives you better results.

**Comment by swiseman** [comment]
Sounds good, thanks!

**Comment by vince62s** [comment]
closing, reopen if needed or when ready.
