### ISSUE TITLE
bug in tally_parameters

### ISSUE THREAD

**Issue by kellymarchisio** [OpenNMT/OpenNMT-py#1080]
Hi - there's a bug in _tally_parameters because `elif 'decoder' or 'generator' in name:` will always evaluate to True, since a string is True.  I'd submit the fix, but I've already got a fork with some unrelated changes on the file I don't want to submit :)

**Comment by bpopeters** [comment]
Good catch, but this code should still return correct parameter counts. Anything that isn't counted for the encoder should be counted for the decoder anyway so the current code is just an obfuscated if/else. The parameter counts will only be off iof you have an `NMTModel` that contains a submodule which is not called `encoder`, `decoder`, or `generator`, and which should not be counted toward the decoder parameters displayed in the log file.
