### ISSUE TITLE
Fixing number of output words individually for each input

### ISSUE THREAD

**Issue by ShivaliGoel** [OpenNMT/OpenNMT-py#1082]
I am experimenting with OpenNMT-py. I wanted to know if there is any way I can restrict the no. of words in the output (different number for each input).

I have very small training dataset. So, I think dividing into separate files to do this on a file level can’t be an option in this case. I know for each input sentence the no. of words I need in output.

**Comment by vince62s** [comment]
Please move your question to forum, but you will need to be much more specific regarding your use case, type of data, is this to happen at training and inference. Anyway, you'll see if someone can help.
