### ISSUE TITLE
RuntimeError: invalid argument 2: k not in range for dimension at ... 

### ISSUE THREAD

**Issue by eduamf** [OpenNMT/OpenNMT-py#1085]
```

Traceback (most recent call last):
  File "translate.py", line 36, in <module>
    main(opt)
  File "translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "OpenNMT-py/onmt/translate/translator.py", line 191, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "OpenNMT-py/onmt/translate/translator.py", line 295, in translate_batch
    return self._translate_batch(batch, data)
  File "OpenNMT-py/onmt/translate/translator.py", line 650, in _translate_batch
    beam_attn.data[j, :, :memory_lengths[j]])
  File "OpenNMT-py/onmt/translate/beam.py", line 128, in advance    True, True)
RuntimeError: invalid argument 2: k not in range for dimension at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/TH/generic/THTensorMath.cpp:3466

```
I have used a shared_vocabulary,

Command:
```

**(pytorch) $ python translate.py -model models/Modelo_2018_12_01-08_49__step_45000.pt \
>  -src test/valid-src-2017-1-2000.pt.atok -tgt test/valid-trg-2017-1-2000.en.atok \
>  -output test/pred-2017-1-2000.en.atok \
>  -report_bleu -report_rouge \
>  -log_file logs/translate.log \
>  -dynamic_dict -share_vocab** 

```

I used, previously, preprocess.py with
-src_vocab_size 0                                                     (not prune)
-tgt_vocab_size 0                                                     (not prune)
-dynamic_dict -share_vocab

**Comment by vince62s** [comment]
you don't seem to be on master. git pull and also remove dynamic_dict share_vocab from the translate.py command line they are not supposed to be there.

**Comment by eduamf** [comment]
My last update from the Master was on November 20th. But to avoid doubts, I will update again.

**Comment by eduamf** [comment]
Fixed.
I am new to using github. The fixed file is [inputter.py](https://github.com/eduamf/OpenNMT-py/blob/master/onmt/inputters/inputter.py).

The problem was not counting the number of terms in the vocabulary, target, and font when a size limit is not set, so that the two values remain zero.

The error does not arise in training. However, at the time of translation, there is an error in processing values 4 and 2 (tgt_vocab_size + 4 and src_vocab_size + 2) as vocabulary size.
