### ISSUE TITLE
Transformer Model

### ISSUE THREAD

**Issue by smukh93** [OpenNMT/OpenNMT-py#1095]
We are using the transformer model for our work and we are planning to use pre-trained word embeddings(Glove300). is there any reasonable way to decide beforehand if we will get some good performance keeping most of the hyperparameters intact as given in the FAQ section? If anyone got good results with pre-trained word embeddings in Transformer model please let me know.

**Comment by vince62s** [comment]
Please raise the question on the forum.
Also read this: http://forum.opennmt.net/t/how-to-use-glove-pre-trained-embeddings-in-opennmt-py/1011
FAQ params should be a good start.
