### ISSUE TITLE
main differences between OpenNMT-tf and OpenNMT-py

### ISSUE THREAD

**Issue by alphadl** [OpenNMT/OpenNMT-py#1111]
I found that the key features of OpenNMT-py are not consistent with the OpenNMT-tf , so if there any comparisons between them so that we can quickly determine which version to choose?

**Comment by vince62s** [comment]
I think it's the other way around. Depending on your need and your goal we could advise you to pick one or the other.

**Comment by vince62s** [comment]
clsoing this, feel free to raise the question on the Forum.
