### ISSUE TITLE
Bug introduced by #1114

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT-py#1116]
@bpopeters 
Last PR #1114 introduced a bug in the vocab preprocess.
I did not dig but it leads to an issue where when you translate, each generated sentence ends with a <unk>

I think there might be a mismatch wih EOS.

Can you look into it please ?
Thanks.

**Comment by bpopeters** [comment]
What does each generated sentence end with? I just preprocessed, trained, and translated with a small model and the output looks normal.

**Comment by vince62s** [comment]
sorry github deleted it: < unk >

**Comment by vince62s** [comment]
Here is the issue (in vocab.pt files) :
before your PR:
[
  "< unk >",
  "< blank >",
  "< s >",
  "< /s >",
...]
after your PR:
[
  "< unk >",
  "< blank >",
  null,
  null,
...]

**Comment by bpopeters** [comment]
I haven't been able to reproduce this bug. What options are you using? Is that the source vocabulary or target vocabulary? What's your command line?

**Comment by vince62s** [comment]
python3 preprocess.py -shard_size 1000000 \
	-train_src $TRAIN_SRC \
	-train_tgt $TRAIN_TGT \
	-valid_src $VALID_SRC \
	-valid_tgt $VALID_TGT \
        -src_seq_length $seq_len \
        -tgt_seq_length $seq_len \
        -share_vocab \
	-save_data exp/dataset.$sl-$tl

**Comment by bpopeters** [comment]
It's the `-share_vocab` that causes it. I'll have a fix soon.

**Comment by bpopeters** [comment]
#1117
