### ISSUE TITLE
ImportError for get_rank function

### ISSUE THREAD

**Issue by sahiljajodia01** [OpenNMT/OpenNMT-py#1129]
While running the **preprocess.py** I am getting an ImportError of get_rank function from Pytorch. What I have found on the internet that it is now deprecated and is inside the deprecated module. I can send a pull request for a fix of that?

**Comment by arnav1993k** [comment]
Hi, I am getting the same error. Using Pytorch version 1.0.0 and python version 3.6.

**Comment by sahiljajodia01** [comment]
Python: 3.6.4
Pytorch: 1.0
I am on master.
This is the screenshot of my command line.
![screenshot 2018-12-24 at 1 03 11 pm](https://user-images.githubusercontent.com/25135893/50393503-a8bfec00-077c-11e9-97d9-91ea059e8a38.png)

**Comment by vince62s** [comment]
can you post
pip list | grep torch

**Comment by sahiljajodia01** [comment]
@vince62s Here is my screenshot
![screenshot 2018-12-24 at 4 54 00 pm](https://user-images.githubusercontent.com/25135893/50398485-f436c200-079d-11e9-804b-311270acddfe.png)

**Comment by vince62s** [comment]
I would uninstall and reinstall it and check in the distribution if "distributed" is properly installed.
it should work.

**Comment by yangyaofei** [comment]
I solve this problem, because get_rank function in pytorch 1.0 is deprecated.

i just change the requirements.txt `torch<=0.9` and run `pip3 install -r requirements.txt` again.

another solution is change the code   ` from torch.distributed import get_rank` to ` from torch.distributed.deprecated import get_rank` and  then  we can use pytorch 1.0.

**Comment by vince62s** [comment]
I don’t think this is right.
There is a new get_rank search it in the doc of Pytorch
Something must be wrong with your install

**Comment by yangyaofei** [comment]
@vince62s yea, I can see the get_rank in pytorch 1.0's source ,and still get this error.

I'm pretty sure i install a pytorch 1.0 

I just use ipython3 to import get_rank with pytorch 1.0 , OS : macOS .10.14 brew python3 pip3 installed. I think maybe it's a bug in this whl package.

**Comment by vince62s** [comment]
2 ideas:
try to uninstall and remove manually all the torch related dist-package things and reinstall it.
if not working
make your point in the Pytorch forum with a minimal example showing the import get_rank not working.
Good luck
cheers.

**Comment by erip** [comment]
I can confirm this with the `pip install`d version: 

```
$ pip freeze
atomicwrites==1.2.1
attrs==18.2.0
certifi==2018.11.29
chardet==3.0.4
ConfigArgParse==0.14.0
future==0.17.1
idna==2.8
more-itertools==5.0.0
numpy==1.16.0
pluggy==0.8.1
py==1.7.0
pytest==4.1.1
requests==2.21.0
six==1.12.0
torch==1.0.0
torchtext==0.4.0
tqdm==4.29.1
urllib3==1.24.1
(opennmt)
~/Code/OpenNMT-py/onmt on  master ⌚ 7:58:03
$ python3 -c "from torch.distribution import get_rank"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch.distribution'
```

**Comment by erip** [comment]
@vince62s Updated -- sorry. :-) I ran into the same error and tried to minify. I fixed the above comment.

**Comment by vince62s** [comment]
so you need to understand why the is_available returns false.

**Comment by erip** [comment]
Presumably this is an issue with a missing CUDA toolkit. It would be nice if it were documented that CUDA 10.x is required to even run tests.

**Comment by vince62s** [comment]
can you try this:
here https://github.com/OpenNMT/OpenNMT-py/blob/e084cf3ff717c1edea080f1046eaeb97cb5391bb/onmt/utils/statistics.py#L7-L8
these two lines, move them in line 57 in the def function where they are used.
let me know if it fixes the issue

**Comment by erip** [comment]
I can confirm that after moving those imports and issuing a `pip install pyrouge` allows tests to run (at least via `pytest`).

**Comment by vince62s** [comment]
do you have time to send a PR? that would be great, thanks.

**Comment by erip** [comment]
I'm happy to. It looks like `pyrouge` is only required for tests. Should I include it in the `requirements.txt`? I can create a separate `requirements.test.txt` or similar.
