### ISSUE TITLE
The comment in onmt.modules.average_attn may be wrong

### ISSUE THREAD

**Issue by Michaelvll** [OpenNMT/OpenNMT-py#1134]
The comment in onmt.modules.average_attn.AverageAttention.forward says that it gets a input of size `[batch_size x input_len x model_dim]`, and outputs a gating_outputs and a average_outputs both with size `[batch_size x 1 x model_dim]`. However, in my test the two outputs are both with size [batch_size x input_len x model_dim].
```python
import torch
import onmt.modules.average_attn as Att
model = Att.AverageAttention(3)
a = torch.arange(24).reshape(2,4,3).float()
print("intput size:", a.size())
o1, o2 = model(a)
print("o1 size:", o1.size())
print("o2.size:", o2.size())
```
intput size: torch.Size([2, 4, 3])
o1 size: torch.Size([2, 4, 3])
o2 size: torch.Size([2, 4, 3])

**Comment by vince62s** [comment]
@francoishernandez  when you have time if you can have a look.

**Comment by Michaelvll** [comment]
Thank you!
