### ISSUE TITLE
 Is the lower parameter actually being used?

### ISSUE THREAD

**Issue by eduamf** [OpenNMT/OpenNMT-py#1135]
Is the **-lower** parameter, in preprocess.py, actually being used? It looks like it's not being used anywhere. 

I'm using this parameter with another one that I created in order to have only words and punctuation marks in vocabulary.

Another thing is about src_size_vocab and tgt_size_vocab when, in the same file inputter.py. If you set to be zero, no prune, the final size is not updated.

In inputter.py, I`m using:

```
def build_vocab(train_dataset_files, fields, data_type, share_vocab,
                src_vocab_path, src_vocab_size, src_words_min_frequency,
                tgt_vocab_path, tgt_vocab_size, tgt_words_min_frequency,
                lower, only_words):
    """
    Args:
        train_dataset_files: a list of train dataset pt file.
        fields (dict): fields to build vocab for.
        data_type: "text", "img" or "audio"?
        share_vocab(bool): share source and target vocabulary?
        src_vocab_path(string): Path to src vocabulary file.
        src_vocab_size(int): size of the source vocabulary.
        src_words_min_frequency(int): the minimum frequency needed to
                include a source word in the vocabulary.
        tgt_vocab_path(string): Path to tgt vocabulary file.
        tgt_vocab_size(int): size of the target vocabulary.
        tgt_words_min_frequency(int): the minimum frequency needed to
                include a target word in the vocabulary.
        lower(bool): lower case vocab.
        only_words(int): 1 = accept only words with letters,
                2 - accept words and punctuation marks.

```
after update counters I set:

```
    if tgt_vocab_size == 0:
        tgt_vocab_size = len(counters["tgt"])
    if src_vocab_size == 0:
        src_vocab_size = len(counters["src"])

```

**Comment by bpopeters** [comment]
You appear to be using an old version of the code because the `build_vocab` does not have a `lower` parameter anymore. There isn't currently a straightforward way to get OpenNMT's preprocessing to do things like lowercase the data right now. I'm working to change this, but in the meantime the best solution is just to lowercase your data beforehand.

As to the other problem, let me know if it's fixed after you pull the current code.

**Comment by bpopeters** [comment]
In that case, I'm not sure what you're asking. Have you attempted to add a new features which lowercases your training data and you are not certain why it doesn't work?

**Comment by eduamf** [comment]
I`m trying to reduce the dictionary size, and what I was thinking to do already exists in [OpenNMT.net] (http://opennmt.net/OpenNMT/tools/tokenization/), similar to the "segment_case" parameter. As you said, new features. I`ll try to use them, thank you.

But another thing is the vocabulary size, when:

```
if tgt_vocab_size == 0:
        tgt_vocab_size = len(counters["tgt"])
if src_vocab_size == 0:
        src_vocab_size = len(counters["src"])
```

**Comment by bpopeters** [comment]
That's actually the documentation for the Lua version of the code, which has a completely different implementation and different options. I would still recommend lowercasing your data before you give it to preprocess.py.

**Comment by eduamf** [comment]
Thank you
