### ISSUE TITLE
Performance is declining when using large beam size ?

### ISSUE THREAD

**Issue by tramphero** [OpenNMT/OpenNMT-py#1137]
I have trained a transformer based translator to translate the deformed sentences （by inserting, deleting or substituting some tokens）into the original sentences.
During inference, the performance is declining when enlarge the beam size. 
**Beam=1：**
WER 5.61 [ 5806 / 103551, 580 ins, 898 del, 4328 sub ]
BLEU = 89.23, 95.4/91.3/87.6/84.1 (BP=0.997, ratio=0.997, hyp_len=103233, ref_len=103551)
**Beam=2：**
WER 6.04 [ 6255 / 103551, 560 ins, 1450 del, 4245 sub ]
BLEU = 88.86, 95.4/91.4/87.7/84.3 (BP=0.991, ratio=0.991, hyp_len=102661, ref_len=103551)
**Beam=4**：
%WER 7.14 [ 7394 / 103551, 546 ins, 2688 del, 4160 sub ]
BLEU = 87.80, 95.5/91.5/87.8/84.3 (BP=0.979, ratio=0.979, hyp_len=101409, ref_len=103551)

Is this phenomenon reasonable?

**Comment by vince62s** [comment]
difficult to say, depends on the task.
For a "standard" translation problem, what we observe is an increase in performance (BLEU) with the beam silze to an extend and then a decrease in performance if the beam is too high.
If the task is very "easy" I guess it could make sense that you see what you described.
