### ISSUE TITLE
Errors in speech to text conversion example

### ISSUE THREAD

**Issue by archomt** [OpenNMT/OpenNMT-py#1138]
When I try to train the speech to text conversion model using "**python train.py -model_type audio -enc_rnn_size 512 -dec_rnn_size 512 -audio_enc_pooling 1,1,2,2 -dropout 0 -enc_layers 4 -dec_layers 1 -rnn_type LSTM -data data/speech/demo -save_model demo-model -global_attention mlp -gpu_ranks 0 -batch_size 8 -optim adam -max_grad_norm 100 -learning_rate 0.0003 -learning_rate_decay 0.8 -train_steps 100000**", I get the "**RuntimeError: Length of all samples has to be greater than 0, but found an element in 'lengths' that is <= 0**" error. I follow every step given in [http://opennmt.net/OpenNMT-py/speech2text.html](url)
I'm not sure what else I'm missing

**Comment by vince62s** [comment]
please post python, pytorch versions, make sure you're on master.

**Comment by vince62s** [comment]
then a recent commit may have change the behavior with empty target sequence, can you double check ?
I am not having the error with another dataset.

**Comment by vince62s** [comment]
I did not get the error while running it with Python 3.5 pytorch 1.0 and master, torchtext 0.4.0
What torchtext version do you have ?

**Comment by vince62s** [comment]
Ben the only thing that has changed is torch audio 3 days ago. I don't see any other reason for the failing build.

**Comment by archomt** [comment]
I ran it with python 3.6 and pytorch 1.0.

**Comment by vince62s** [comment]
can you update torchaudio (pip3 install --upgrade git+git://github.com/pytorch/audio)
git pull onmt-py
and try again ?
thanks.

**Comment by archomt** [comment]
@vince62s Updated the OpenNMT-py  worked for me. Thank you very much for your reply and help
