### ISSUE TITLE
torch.multiprocessing.get_context

### ISSUE THREAD

**Issue by lianrzh** [OpenNMT/OpenNMT-py#1139]
Can i use the `fork` mode when using torch.multiprocessing.get_context?
I need to run code by using the command `/opt/compiler/gcc-4.8.2/lib/ld-linux-x86-64.so.2 --library-path /opt/compiler/gcc-4.8.2/lib:/lib64:$LD_LIBRARY_PATH python train.py`, and the `spawn` mode starts a fresh python interpreter process which does not inherit the environment variable of the parent node, so problem(`ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found`) appear.

**Comment by vince62s** [comment]
Without context, very difficult to understand what you are trying to accomplish.
maybe you can try using train_single.py, just an idea because I don't really knwo what you are trying to do.

**Comment by lianrzh** [comment]
@vince62s The problem (ImportError: /lib64/libc.so.6: version GLIBC_2.14' not found`) will occur when i run pytorch1.0, so i need to add the prefix before python like `/opt/compiler/gcc-4.8.2/lib/ld-linux-x86-64.so.2 --library-path /opt/compiler/gcc-4.8.2/lib /opt/python2.7/bin/python` . It is succes to run opennmt in 1GPU . Now i want to run 4GPU, the GLIB problem occur again, because the code use `spawn` to new python interpreter which not include the prefix `/opt/compiler/gcc-4.8.2/lib/ld-linux-x86-64.so.2 --library-path /opt/compiler/gcc-4.8.2/lib`.If i change the code in train.py(line35) to `mp = torch.multiprocessing.get_context('fork')` , `fork` mode seems work,  but is fork mode not used for cuda in python3. Is there any solution to this problem？

**Comment by vince62s** [comment]
Are you trying to use OpenNMT-py in multi-gpu mode as is or are you trying your own code ?
if as is, then solve the error first.
You may have installed it incorrectly.
post your python version, pytorch version and make sure you installed all requirements.txt
Thanks.
