### ISSUE TITLE
How to calculate a the gradient of of score w.r.t parameters?

### ISSUE THREAD

**Issue by wuhaixutab** [OpenNMT/OpenNMT-py#114]
Our team are implementing a dual learning [algorithm,](https://papers.nips.cc/paper/6469-dual-learning-for-machine-translation.pdf) where we need to calculate the gradient of a decoder score w.r.t the model parameters. However, the score is a Tensor, we can not just call grad().

**Comment by srush** [comment]
Yes, you cannot call grad on a tensor, so you have to decide what your loss is. Typically people use a sum. Perhaps I misunderstand though?

**Comment by wuhaixutab** [comment]
`#  (2) if a target is specified, compute the 'goldScore'
        #  (i.e. log likelihood) of the target under the model
        goldScores = context.data.new(batchSize).zero_()
        if batch.tgt is not None:
            decStates = encStates
            mask(padMask)
            decOut, decStates, attn = decoder(batch.tgt[:-1],
                                              context, decStates)
            for dec_t, tgt_t in zip(decOut, batch.tgt[1:].data):
                gen_t = self.model.generator.forward(dec_t)
                tgt_t = tgt_t.unsqueeze(1)
                scores = gen_t.data.gather(1, tgt_t)
                scores.masked_fill_(tgt_t.eq(onmt.Constants.PAD), 0)
                goldScores += scores

        #  (3) run the decoder to generate sentences, usin`
In this block, I want to calculate the gradient of scores w.r.t model parameters as during the training stage. However, I can just call scores.backward(), how to solve this problem?
