### ISSUE TITLE
Question about -max_grad_norm 0

### ISSUE THREAD

**Issue by sys1874** [OpenNMT/OpenNMT-py#1140]
I check the function about `def clip_grad_norm_(parameters, max_norm, norm_type=2)`
https://pytorch.org/docs/stable/_modules/torch/nn/utils/clip_grad.html

the grads of parameters will be zero when set the -max_grad_norm 0   ?? 

what happen to grad when setting -max_grad_norm 0 ?

**Comment by vince62s** [comment]
just no clipping:
https://github.com/OpenNMT/OpenNMT-py/blob/be888f40d7ecfe34169077a9746303e4a7a987f9/onmt/utils/optimizers.py#L245
