### ISSUE TITLE
torch.no_grad() in validate ? 

### ISSUE THREAD

**Issue by tanaka-jp** [OpenNMT/OpenNMT-py#1141]
"torch.no_grad()" is not used in validate().
I think it should be used ...

https://github.com/OpenNMT/OpenNMT-py/blob/94cc2b62990b7eeb382a6b74a7268230e2a572b5/onmt/trainer.py#L213-L220

**Comment by vince62s** [comment]
I think you are correct, we forgot to include this during the 0.4 to 1.0 migration.
Can you please send PR and show:
- differences in results (if any)
- reduction in memory footprint at validation time.
thanks.
