### ISSUE TITLE
Run OpenNMT-py on Google Colaboratory

### ISSUE THREAD

**Issue by molhaMaleh** [OpenNMT/OpenNMT-py#1147]
Hi, I am trying to run OpenNMT-py on a cloud service
Is there anyway to run openNMT-py on Google Colaboratory?
If there, could you please provide guideline steps?

**Comment by vince62s** [comment]
unfortunately we did not maintain properly the exiting notebook here:
https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/Library.ipynb
and the doc:
https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/Library.md

This is still a good starting point and if you can send a PR to update it, it would be great.
