### ISSUE TITLE
Query regarding detach behavior in truncated bptt

### ISSUE THREAD

**Issue by ratishsp** [OpenNMT/OpenNMT-py#1148]
Hi,
I was going through the 0.1 release code of OpenNMT-py https://github.com/OpenNMT/OpenNMT-py/tree/v0.1
In bptt, after the first iteration through the ```trunc_size``` the detach on decoder_state is called to prevent backprop fully to the start of the sequence and to the encoder. 
https://github.com/OpenNMT/OpenNMT-py/blob/0ecec8b4c16fdec7d8ce2646a0ea47ab6535d308/onmt/Trainer.py#L321

This inturn invokes detach_ on individual variable in ```_all``` https://github.com/OpenNMT/OpenNMT-py/blob/0ecec8b4c16fdec7d8ce2646a0ea47ab6535d308/onmt/Models.py#L611

The ```detach_``` sets ```required_grad``` to ```False``` for the variable. 
In the present case, ```self.hidden``` will have ```required_grad``` ```True``` during the first truncation pass and then ```False``` from the second pass onwards. 
I am confused if this is desired behavior.
As per my understanding, ```required_grad``` should be set to ```True``` for ```self.hidden``` throughout all the trunc bptt.

Thanks.

**Comment by vince62s** [comment]
code is bit old, can you have a look at master ?
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/trainer.py

**Comment by ratishsp** [comment]
Thanks @vince62s 
I went through the code again and it seems to be fine. 
```required_grad``` will be ```False``` only at the beginning of the first time step for each ```trunc_size```. It will be set to ```True``` during the remaining time steps as gradients flow if any one of the variable in subgraph requires gradients.
