### ISSUE TITLE
How to apply image pre-trained model in Image encoder

### ISSUE THREAD

**Issue by SoonmoKwon** [OpenNMT/OpenNMT-py#1152]
Is there anyone who apply pretrained image models such as VGG or ResNet?

In onmt.encoders.image_encoders.py, there is a function, load_pretrained_vectors but I don't have any idea implement it using the existing models on torchvision or pretrainedmodels.

Help me please,

**Comment by vince62s** [comment]
This is not the good place.
Read the Pytorch Tutorials instead.
https://pytorch.org/tutorials/
