### ISSUE TITLE
using embedding_to_torch is resulting an error

### ISSUE THREAD

**Issue by MiladAlshomary** [OpenNMT/OpenNMT-py#1172]
Hi,

Following the instructions [here](http://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-pretrained-embeddings-e-g-glove) is resulting the following assertion error error:
`"assert enc_vocab is not None and dec_vocab is not None"`

I tried to print the vocabs variable that is loaded in get_vocabs function and it shows the following:
`{'src': [('src', <torchtext.data.field.Field object at 0x7f1822831908>)], 'tgt': [('tgt', <torchtext.data.field.Field object at 0x7f18226b2518>)], 'indices': [('indices', <torchtext.data.field.Field object at 0x7f1821d79f98>)]}
`
Hence, the following statments to load the enc_vocab and dec_vocab are failing. Maybe there is a change on the structure of the vocabs that is not accounted to in the embedding code?

Thanks for your help on this!

**Comment by MiladAlshomary** [comment]
Yes, this release works fine!

Thanks

**Comment by vince62s** [comment]
@bpopeters another one in your basket, thanks.
