### ISSUE TITLE
Should bias be enabled in transformer?

### ISSUE THREAD

**Issue by anoidgit** [OpenNMT/OpenNMT-py#1173]
The bias in `nn.Linear` is enabled by default, and according to [Sockeye](https://github.com/awslabs/sockeye/blob/master/sockeye/layers.py), seems bias in [MultiHeadAttention](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/multi_headed_attn.py#L59-L64) and also [here](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/multi_headed_attn.py#L67) should be disabled.

But I am not sure, since I have difficulty in find related code in tensor2tensor.

**Comment by guillaumekln** [comment]
Bias is indeed not used in the paper, but I don't think this makes an interesting difference. For example, I remember that the reference implementation (tensor2tensor) did use a bias at some point.

**Comment by anoidgit** [comment]
@guillaumekln got it. Thank you for your reply.
