### ISSUE TITLE
Transformer show no logs respond during training start

### ISSUE THREAD

**Issue by weizhenzhao** [OpenNMT/OpenNMT-py#1176]
Hi Dear

when I try to use the transformer to train the translation from English to Chinese,
the console shown no respond when the training started ,
Can you give me some advice?
Thank you very much
weizhen
![image](https://user-images.githubusercontent.com/13706689/51105198-4dd16000-1823-11e9-861a-3c219eb757af.png)

`python3  train.py -data ./data/demo -save_model demo_model_transformer -layers 6 -rnn_size 512 -word_vec_size 512 -transformer_ff 2048 -heads 8          -encoder_type transformer -decoder_type transformer -position_encoding         -train_steps 200000  -max_generator_batches 2 -dropout 0.1         -batch_size 4096 -batch_type tokens -normalization tokens  -accum_count 2         -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 2         -max_grad_norm 0 -param_init 0  -param_init_glorot         -label_smoothing 0.1 -valid_steps 10000 -save_checkpoint_steps 10000 -world_size 4 -gpu_ranks 0
`

**Comment by vtrokhymenko** [comment]
hm, in your screen u can see `Start training...` and it means that the training started

**Comment by weizhenzhao** [comment]
@vtrokhymenko 
but I've waited for nearly 30 minutes , it shows no logs next.
Is there some problem happen?
Thanks
weizhen

**Comment by vtrokhymenko** [comment]
at this time I understand what u mean
yes, it's ok
I waiting also a long time, like 30 min, but all depends on your architecture machine and what is the weight of your data u training

**Comment by weizhenzhao** [comment]
here is my training data
src-train-new.txt
![image](https://user-images.githubusercontent.com/13706689/51106079-c0dbd600-1825-11e9-80ea-b7b6add464db.png)
src-tgt-new.txt
![image](https://user-images.githubusercontent.com/13706689/51106102-ccc79800-1825-11e9-84f6-9a7f2e74d057.png)
and I use the following command to generate the data


python3 preprocess.py -train_src data/src-train-new.txt -train_tgt data/tgt-train-new.txt -valid_src data/src-val-new.txt -valid_tgt data/tgt-val-new.txt -save_data data/demo


Thanks
weizhen

**Comment by vtrokhymenko** [comment]
I want to tell, what the size your data, ex. 1gb or 100gb 
and its effects on training

**Comment by vince62s** [comment]
-world_size 4 -gpu_ranks 0
this is wrong unless you have other nodes
if you have only 1 gpu, use -world_size 1 -gpu_ranks 0
if you have 4 gpu, use -world_size 4 -gpu_ranks 0 1 2 3

**Comment by weizhenzhao** [comment]
@vtrokhymenko 
the size is 94.12MB

Thanks
weizhen

**Comment by vtrokhymenko** [comment]
it so interesting, that u have such small data and waiting nearly 30 minutes

**Comment by weizhenzhao** [comment]
@vtrokhymenko 
you said right after I changed the --world_size  to 1 , it didn't wait,
but it showed the following error
![image](https://user-images.githubusercontent.com/13706689/51106860-04374400-1828-11e9-8c5e-63bc6f600e89.png)

I will try to train it in the azure with k80 gpu

Thanks
weizhen

**Comment by vtrokhymenko** [comment]
before train.py u run `CUDA_VISIBLE_DEVICES=0`?

**Comment by weizhenzhao** [comment]
![image](https://user-images.githubusercontent.com/13706689/51107088-c71f8180-1828-11e9-84e7-138b42558cf0.png)
yes I ran the CUDA_VISIBLE_DEVICES=0 in my local ,but it still went out of memory

**Comment by vtrokhymenko** [comment]
I suggest you either restart your machine or free memory from gpu
maybe this influence

**Comment by vince62s** [comment]
with 6GB of GPU ram you need to divide by 2 the batch size try 2048

**Comment by weizhenzhao** [comment]
![image](https://user-images.githubusercontent.com/13706689/51120975-39a45780-1851-11e9-9513-4d938f98ebbb.png)
![image](https://user-images.githubusercontent.com/13706689/51121194-cbac6000-1851-11e9-86aa-589d868135f0.png)

Hi dear

I've tried trainning it on the azure cloud with k80m gpu ,
but I find the trainning process is too slow, it took 152 seconds for 50 iterations.
I think with 2 k80m gpu 16GB GPU ram should it be that slow?

thanks
weizhen

**Comment by vtrokhymenko** [comment]
it all depends what u say in an arguments

**Comment by weizhenzhao** [comment]
should I divide the batch_size by 2 to 2048? and speed up the training cost for one iteration?
thanks
weizhen

**Comment by vtrokhymenko** [comment]
of course, u can do this & it will affect your result and speed

**Comment by vince62s** [comment]
K80 are old, you won't get faster training speed.

you need to get a GTX1080ti or if on aws / azure a P100 or better.

**Comment by 520jefferson** [comment]
@vince62s 
i trian like this. and torch version is 1.0.0, but i get this error:

Traceback (most recent call last):
  File "train.py", line 120, in <module>
    main(opt)
  File "train.py", line 35, in main
    mp = torch.multiprocessing.get_context('spawn')
AttributeError: 'module' object has no attribute 'get_context'

**Comment by vince62s** [comment]
yes it is in the prerequisite.
