### ISSUE TITLE
empty prediction by ada6_bridge_oldcopy_tagged_larger_acc_54.84_ppl_10.58_e17.pt

### ISSUE THREAD

**Issue by vtrokhymenko** [OpenNMT/OpenNMT-py#1177]
I take one of pre-trained model like `ada6_bridge_oldcopy_tagged_larger_acc_54.84_ppl_10.58_e17.pt` and received a many empty prediction on cnndm.

for example:
![image](https://user-images.githubusercontent.com/8581044/51114162-27a0c580-180d-11e9-83eb-c6186b8e0ca8.png)

can u tell, who trained him? because after this I can't trust another pre-trained model.

**Comment by vtrokhymenko** [comment]
from 690 predictions I received 635 empty!

**Comment by vtrokhymenko** [comment]
@vince62s 
sorry, maybe u can help?

**Comment by vince62s** [comment]
Can you post your command line as well as the pytorch and onmt-py version ?

**Comment by vince62s** [comment]
reopen if needed
