### ISSUE TITLE
call to Decoder.forward() has wrong number of arguments

### ISSUE THREAD

**Issue by eriche2016** [OpenNMT/OpenNMT-py#118]
[here](https://github.com/OpenNMT/OpenNMT-py/blob/8a93bdf2aa3c9e5c5bcad21423d53d686f29375b/onmt/Translator.py#L132), should this be fed in to 4 variables instead of 3?

**Comment by eriche2016** [comment]
cause error message: ```forward() missing 1 required positional argument: 'state'```

**Comment by falcondai** [comment]
yes, it does seem like a mistake. Could you provide a minimal example that can reproduce this issue?

**Comment by eriche2016** [comment]
just run translate.py on test data  and gives error:
"""
forward() missing 1 required positional argument: 'state'
"""

**Comment by srush** [comment]
This is addressed in https://github.com/OpenNMT/OpenNMT-py/pull/99 . merging soon.

**Comment by srush** [comment]
Should be fixed.
