### ISSUE TITLE
Opennmt-py demo training failed from time to time 

### ISSUE THREAD

**Issue by lmatt-bit** [OpenNMT/OpenNMT-py#1181]
I used below command to train a demo model.
`python train.py -data data/demo -save_model demo-model -gpu_ranks 0 -tensorboard`

But the training failed from time to time(see below tensorboard, there are two runs. One is success with high accuracy, the other one is not. ). Is the result expected?

![image](http://forum.opennmt.net/uploads/default/optimized/1X/4c5fe85c20bd9f301db70dc4eb6e75ad70373d81_2_1035x598.png)

**Comment by vince62s** [comment]
The toy set is way too smal to give good results anyway.
