### ISSUE TITLE
Repeated tokens in translation

### ISSUE THREAD

**Issue by stefanziv** [OpenNMT/OpenNMT-py#1185]
Hi, I was wondering if someone can help me with my issue. Translating "Lebron James is tall" with a trained model results in the following output.

python translate.py -model my_model.pt -src data/src-test.txt -replace_unk -verbose

SENT 1: ('Lebron', 'James', 'is', 'tall')
PRED 1: <arg1> Lebron James </arg1> <rel> is </rel> <arg2> tall Lebron </arg2>
PRED SCORE: -2.1360

This seems to happen pretty frequently with full names and I was wondering if anyone has encountered something similar/what the solution may be

Thanks!!

**Comment by stefanziv** [comment]
Upon further analysis, this seems to be caused by a < unk > token at the end of the sentence, probably resulting from the eos character

**Comment by eduamf** [comment]
What`s your target language?

**Comment by stefanziv** [comment]
Yes, the issue has since been solved. Adding a space and a period after the sentence removed the < unk > token
