### ISSUE TITLE
Support additional non UTF-8 codecs.

### ISSUE THREAD

**Issue by djKooks** [OpenNMT/OpenNMT-py#119]
Hello.
One question is, is codec fixed to 'utf-8'? 
Surely most of data is being encode/decode to utf-8, but maybe there could be a user who wants to do with other type(In my case, because I'm korean, just wondered if It could be set as 'euc-kr' or else).

Thanks.

**Comment by gladuo** [comment]
@djKooks In my experience with Chinese, utf-8 is the most compatible solution to the encoding/decoding problem. Other coding is fine and I believe use `codecs` to open files and always keep your string as Unicode will solve most of the problem.

**Comment by djKooks** [comment]
@gladuo Yes, I know utf-8 is most compatible, and it mostly causes no issues. But maybe there could be a problem in other languages, and make codec as an API parameter to make it selectable by user could be one of options.

Or as you say, make a guide to keep string as unicode can be an answer.

**Comment by srush** [comment]
Yes, I think in the near term we will use UTF-8 unless someone really wants to own this issue. We are trying to support python2 and python3, and this is a simple solution for us now.

**Comment by djKooks** [comment]
@srush Okay. I'll try work on this.

**Comment by djKooks** [comment]
I added process about this in #130 . Please look on.
