### ISSUE TITLE
Concat with downstream model

### ISSUE THREAD

**Issue by gongzhitaao** [OpenNMT/OpenNMT-py#1193]
Are there any easy ways to concatenate a downstream task model?

For example, for the following architecture, **M** could be a text classification model.  Running the model **M** on the output of the whole OpenNMT model is not an option for me since I need an end-to-end model to back-prop the gradients.

![ae-clf](https://user-images.githubusercontent.com/704995/51496750-870b5200-1d86-11e9-91da-706c88ef45ab.png)

I looked into the `translator.py` code, it seems to me that I might need to reuse parts of `Translation` class.  Any suggestions would be appreciated.

**Comment by vince62s** [comment]
not plug and play, you have to modify the code base quite heavily.
opennmt-tf might be more flexible to accomplish what you want.
