### ISSUE TITLE
[feature request - Document level context]

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT-py#1212]
Hi guys,
If someone is interested, there are some papers that we could implement.
Research is definitely going that way and it is part of the WMT19 task.

This paper: http://aclweb.org/anthology/D18-1049
We could implement it. One aspect is that it requires 2 steps training.
Maybe we can avoid that by turning off context attention when not applicable (we need to separate the 2 soources: sentence level, document level).

There is another interesting paper here: https://publications.idiap.ch/downloads/papers/2018/Miculicich_EMNLP_2018.pdf
There is an implementation based on an old version of onmt-py.
We could implement it too but it also require 2 or 3 step training.

if anyone is interested, let me know.

**Comment by LauraYu** [comment]
I've been playing the code of the HAN model (https://publications.idiap.ch/downloads/papers/2018/Miculicich_EMNLP_2018.pdf). As you said, it's based on an old version of onmt-py and pytorch 0.3, which makes it very difficult to adapt it.
It'll be really helpful to have it implemented in onmt.

**Comment by vince62s** [comment]
closing this while expecting more convincing papers.

**Comment by ling-pan** [comment]
Hi, 

I wonder whether there are implementations for these two papers in current OpenNMT?

Thanks!

**Comment by vince62s** [comment]
No, I am waiting for papers submitted at WMT19

**Comment by JOHW85** [comment]
Any interest in this: https://aclanthology.org/2021.acl-long.267/
