### ISSUE TITLE
AttributeError: 'TextMultiField' object has no attribute 'is_target'

### ISSUE THREAD

**Issue by tangxiangru** [OpenNMT/OpenNMT-py#1224]
Traceback (most recent call last):
  File "translate.py", line 42, in module
    main(opt)
  File "translate.py", line 27, in main
    attn_debug=opt.attn_debug
  File "/home/txr/OpenNMT-py-ende/onmt/translate/translator.py", line 208, in translate
    for batch in data_iter:
  File "/home/txr/anaconda3/envs/python3/lib/python3.5/site-packages/torchtext/data/iterator.py", line 157, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "/home/txr/anaconda3/envs/python3/lib/python3.5/site-packages/torchtext/data/batch.py", line 26, in __init__
    self.input_fields = [k for k, v in dataset.fields.items() if
  File "/home/txr/anaconda3/envs/python3/lib/python3.5/site-packages/torchtext/data/batch.py", line 27, in listcomp
    v is not None and not v.is_target]
AttributeError: 'TextMultiField' object has no attribute 'is_target'

**Comment by vince62s** [comment]
Please post your command line.
@flauted can you have a look please.

**Comment by tangxiangru** [comment]
`python translate.py -model ./transformer-ende-wmt-pyOnmt/averaged-10-epoch.pt -src ../ig-more-turn/data/multi30k/test.en -output pred.txt -replace_unk -verbose`
with http://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-the-transformer-model

**Comment by flauted** [comment]
Let me see if I can reproduce this.

**Comment by vince62s** [comment]
so you used the checkpoint in the pretrained section of the website ?

**Comment by tangxiangru** [comment]
> so you used the checkpoint in the pretrained section of the website ?

yes，and I modify opt.py to -data /tmp/de2/data -save_model /tmp/extra \
        -layers 6 -rnn_size 512 -word_vec_size 512 -transformer_ff 2048 -heads 8  \
        -encoder_type transformer -decoder_type transformer -position_encoding \
        -train_steps 200000  -max_generator_batches 2 -dropout 0.1 \
        -batch_size 4096 -batch_type tokens -normalization tokens  -accum_count 2 \
        -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 2 \
        -max_grad_norm 0 -param_init 0  -param_init_glorot \
        -label_smoothing 0.1 -valid_steps 10000 -save_checkpoint_steps 10000 \
        -world_size 4 -gpu_ranks 0 1 2 3

**Comment by tangxiangru** [comment]
> Let me see if I can reproduce this.

My torchtext is the latest version, https://github.com/pytorch/text

**Comment by flauted** [comment]
Could you post the commit hash you're using? You can do ``git log -n 1``.

**Comment by tangxiangru** [comment]
> Could you post the commit hash you're using? You can do `git log -n 1`.
I just download the zip several hours ago instead of using git clone(because my server is unable to connect GITHUB)

**Comment by tangxiangru** [comment]
> Could you post the commit hash you're using? You can do `git log -n 1`.

I think it is the torchtext's problem

**Comment by tangxiangru** [comment]
I solve it, thanks so much
