### ISSUE TITLE
Different performance with different GPUs

### ISSUE THREAD

**Issue by Felix0805** [OpenNMT/OpenNMT-py#1226]
I use opennmt-py to train a transformer-NMT baseline with LDC dataset, and I use nist02.en as the test set. However, I got a bleu of 44 in a P100 GPU and got a bleu of 41 in a 1080ti GPU. I wonder if this is a common phenomenon.

**Comment by vince62s** [comment]
Beside the seed, is everything fully comparable ? (token batch size, accum acount, ...)
How big is the dataset ?

**Comment by Felix0805** [comment]
Everything is the same, about 1.25M parallel sentences

**Comment by vince62s** [comment]
looks strange, but you can test with another seed value on one of them to see of the deviation is high.
can't tell more.
