### ISSUE TITLE
What is the difference between averaged-10-epoch.pt and sentencepiece.model（pretrained model)）

### ISSUE THREAD

**Issue by tangxiangru** [OpenNMT/OpenNMT-py#1229]
And anything else I need to do? before run translate.py

This is my ugly result:
SENT 170: ['A', 'woman', 'and', 'a', 'child', 'embrace', 'while', 'the', 'child', 'tastes', 'what', 'they', 'have', 'been', 'making.']
PRED 170: ▁Herr ▁Kolleg e !
PRED SCORE: -6.5181

SENT 171: ['Two', 'men', 'and', 'a', 'lady', 'are', 'standing', 'outside.']
PRED 171: ▁Nein .
PRED SCORE: -6.6718

SENT 172: ['A', 'group', 'of', 'men', 'using', 'logs', 'to', 'push', 'a', 'boat', 'out', 'of', 'the', 'water.']
PRED 172: ▁Am ▁lieb sten ▁ist ▁es , ▁wenn ▁man ▁einfach ▁nur ▁ redet .
PRED SCORE: -19.3394

SENT 173: ['A', 'man', 'drinks', 'from', 'a', 'wineglass', 'while', 'reading', 'the', 'paper.']
PRED 173: ▁Ganz ▁einfach .
PRED SCORE: -6.1896

SENT 174: ['A', 'man', 'wearing', 'a', 'all', 'black', 'and', 'playing', 'a', 'piano.']
PRED 174: ▁Herr ▁Kolleg e !
PRED SCORE: -5.7212

SENT 175: ['A', 'young', 'boy', 'wearing', 'a', 'blue', 'jersey', 'and', 'yellow', 'shorts', 'is', 'playing', 'soccer.']
PRED 175: ▁Ganz ▁einfach !
PRED SCORE: -6.6967

**Comment by tangxiangru** [comment]
My cmd: 
python translate.py -model ./transformer-ende-wmt-pyOnmt/averaged-10-epoch.pt -data data/demo -src ../ig-more-turn/data/multi30k/test.en -output pred.txt -replace_unk -verbose  --report_bleu

**Comment by francoishernandez** [comment]
Sentencepiece is the tokenization model.
The `.pt` file is the actual translation model.

You need to tokenize your data before running it into `translate.py`, for instance with this [Tokenizer](https://github.com/OpenNMT/Tokenizer).

**Comment by tangxiangru** [comment]
> Sentencepiece is the tokenization model.
> The `.pt` file is the actual translation model. The vocabulary is stored inside it. (You can have a look by opening a python shell and torch.load() your pt file.)
> 
> You need to tokenize your data before running it into `translate.py`, for instance with this [Tokenizer](https://github.com/OpenNMT/Tokenizer).

just need to tokenize the test-src data?

**Comment by francoishernandez** [comment]
Yes.
Not sure why it's in your command, the `-data` option is for training. Have a look at https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/opts.py .
