### ISSUE TITLE
Document "Attention is all you need"

### ISSUE THREAD

**Issue by srush** [OpenNMT/OpenNMT-py#123]
@srush you need to document the options that work for attention is all you need.

**Comment by ijauregiCMCRC** [comment]
Any documentation available for the transformer option yet? I have select my -encoder_layer and -decoder_layer as "transformer", and I get an error.
```
File "/data/ijauregi/Desktop/CMCRC/OpenNMT/OpenNMT-py/onmt/modules/Util.py", line 9, in aeq
    assert a == base, str(args)
AssertionError: (4, 0)
```

**Comment by davidecaroselli** [comment]
Hi all!

Is the Transformer model actually available? I see in train.py that the classic Encoder/Decoder schema is kind of hard-coded, and it seems the only available model right now.

Am I wrong? If yes, how can I train and use a Transformer model?

Thanks!
