### ISSUE TITLE
What does train_step mean?

### ISSUE THREAD

**Issue by Huijun-Cui** [OpenNMT/OpenNMT-py#1232]
I am confused what the train_step mean?  the number of iteration depend on the size of dataset . why should we specialize trian_step?   For example, if batch size is 2 , my data size is 10 then in one epoch there will be 5 training steps(10 / 2) ,   but if I set the training step to 4 ,  obviously it will drop some data, it dons`t make sense, could you help me , thanks so much

**Comment by vince62s** [comment]
http://forum.opennmt.net/t/how-to-estimate-number-of-iterations/1897
