### ISSUE TITLE
Why translate.py only predict the head 1160 lines ? 

### ISSUE THREAD

**Issue by Huijun-Cui** [OpenNMT/OpenNMT-py#1236]
My task is text summarization . I have finished training the model .  In the  inference step strange error occur . It only predict the head  1160 lines . I ran it twice , it happened twice . My command is 

python translate.py -gpu 0 \
                    -batch_size 20 \
                    -beam_size 10 \
                    -model models/Byte_step_110000.pt \
                    -src datasets/bytecup2018/valid.article.txt \
                    -output testout/ByteCup.out \
                    -min_length 5 \
                    -verbose \
                    -stepwise_penalty \
                    -coverage_penalty summary \
                    -beta 5 \
                    -length_penalty wu \
                    -alpha 0.9 \
                    -verbose \
                    -block_ngram_repeat 3 \
                    -ignore_when_blocking "." "</t>" "<t>"

Is it a bug or is there something I may make a mistake ?

**Comment by vince62s** [comment]
is it the first 1160 or just random.
if random, just try to increase the beam_size to 15 or more. You may have to reduce the batch_size if you go OOM.

**Comment by vince62s** [comment]
try to remove the line where it break to identify if this is a data issue or a code issue.

**Comment by Huijun-Cui** [comment]
@vince62s  make sense , thanks so much for your patience

**Comment by vince62s** [comment]
We fixed something that may be related. please git pull, it may help.
