### ISSUE TITLE
I have some questions when I use pretrained model 

### ISSUE THREAD

**Issue by Huijun-Cui** [OpenNMT/OpenNMT-py#1255]
I try using the pretrained model in this link   []( http://opennmt.net/Models-py/)

In English Summarization section I notice that the model Parameters is that

2 layers, LSTM 500, WE 500, input feed
20 epochs

I notice that it didn`t mention Attention mechanism  , so I am curious does this implement Attention mechanism ?

**Comment by bpopeters** [comment]
Yes, there is an attention mechanism. The codebase does not currently support RNN-based models without an attention mechanism.

**Comment by Huijun-Cui** [comment]
cool !! thank you ,
