### ISSUE TITLE
[feature request: Publish on Pip]

### ISSUE THREAD

**Issue by andreaferretti** [OpenNMT/OpenNMT-py#1261]
Hi, is there a reason why OpenNMT-py is not published on Pip? I think it would be worthwhile, in order to make it easier to depend on it, and I see that OpenNMT-tf is already published there.

**Comment by vince62s** [comment]
yes we'll try to have this, good point.

**Comment by ruohoruotsi** [comment]
+1 that this would be very useful indeed.  I currently use opennmt-py as a dependency for my diacritic restoration work and this would simplify packaging my lib (and pre-trained models) significantly.

**Comment by andreaferretti** [comment]
Are there any updates on this point? Or possibly any other suggestions on how to depend on OpenNMT?

**Comment by TMiguelT** [comment]
Also, it would be nice for the dependencies to be defined in the `setup.py` rather than the `requirements.txt`, so that they get pulled in as part of the install process.

**Comment by pltrdy** [comment]
Hi guys, we've been working on it and finally published OpenNMT-py on pip as release candidates (rc) for v1.0.0.

We introduce commands to call OpenNMT-py without pointing to `*.py` files : use instead `onmt_train`, `onmt_preprocess`, `onmt_server`, `onmt_translate`. 

Command line options remains unchanged and we kept preprocess/train/translate/server.py in root for compatibility.

Feel free to use it and give us feedback about that !

https://pypi.org/project/OpenNMT-py/
