### ISSUE TITLE
Number of examples in training dataset got changed after preprocessing

### ISSUE THREAD

**Issue by deepak1357** [OpenNMT/OpenNMT-py#1263]
Hey @vince62s , @srush, @bpopeters , @JianyuZhan 
I am getting different number of training samples before and after preprocessing.py.
The input to the preprocessing is 86635 number of source and target pairs. When I am going to load the "data.train.0.pt"  for  training the network using train.py then I am getting only 76718 number of pairs. I am using dynamic dictionary option.

[2019-02-03 07:04:27,815 INFO] Loading dataset from  data/data.train.0.pt, number of examples: 76718.

Any kind of help is highly appreciated. Thanks.

**Comment by vince62s** [comment]
Post your command line but most likely you use default values that filter sequences longer than 50 words/tokens.

**Comment by bpopeters** [comment]
The default is to filter sentence pairs where either the source or the target is longer than 50 words. You can set higher limits with the `-src_seq_length` and `-tgt_seq_length` command line options.

**Comment by deepak1357** [comment]
Thank you, @vince62s, @bpopeters. I was misreading -src_seq_length and -tgt_seq_length.
