### ISSUE TITLE
With pre-trained model , so hight score in text summarization 

### ISSUE THREAD

**Issue by Huijun-Cui** [OpenNMT/OpenNMT-py#1271]
I download the pre-trained model from the link [http://opennmt.net/Models-py/]() 

I choose the English Summarization => the second model (2 layers, LSTM 500, WE 500, input feed, 

copy_attn, reuse_copy_attn

20 epochs)   

I also download the corpus you used . 

But I found that my Rouge score is quite high in the inference result . Your model result is R1 : 35.51 R2 : 

17.35 RL : 33.17 

 But my result is R1 : 0.42  R2 : 0.21  RL:  0.38   

I wanna figure out which data you use , so your dataset path is this right ? 

sumdata/train/train.article.txt and  sumdata/train/train.title.txt

**Comment by vince62s** [comment]
please search the forum here: http://forum.opennmt.net/search?q=summarization
and ask your questions there, also make sure you follow: https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/Summarization.md
