### ISSUE TITLE
Scores for random sampling appear to be arbitrary

### ISSUE THREAD

**Issue by flauted** [OpenNMT/OpenNMT-py#1284]
When doing random sampling translation, the scores don't have much meaning. Once all the batches are finished, each batch gets the final log-prob from the decoder. That's not even guaranteed to be the prob of EOS since there's no stopping a batch if EOS is produced. With beam search, the score is the sum of all the log-probs from first word to EOS.

I left a comment in random_sampling.py on #1281 to this effect.

So my question is, should the random sampling scores be something more thoughtful?

**Comment by guillaumekln** [comment]
For consistency, I think random sampling should also return the score of EOS which means it should track sentences that are finished.

In practice, it's not clear if these scores will actually be useful. I guess they can still be used in a back translation process to filter out some outputs with too low probability.
