### ISSUE TITLE
Creating chat response interface 

### ISSUE THREAD

**Issue by nikhiljaiswal** [OpenNMT/OpenNMT-py#1288]
Hi,
I have trained OpenNMT for conversational agent.
For translating as per the available options, we need to pass a file and consequently obtain a prediction file.
But, is it possible that I can pass a sentence by sentence to model and get the output as a general chatter. Anyone please provide yours suggestions.

**Comment by pltrdy** [comment]
I guess the easiest would be to use OpenNMT-py translation server described here: http://forum.opennmt.net/t/simple-opennmt-py-rest-server/1392 (may not be 100% up to date)

**Comment by nikhiljaiswal** [comment]
thanks a lot. It was helpful.

**Comment by nikhiljaiswal** [comment]
hey @pltrdy , I was using your provided rest server. 
One of the shortcomings which I encountered is that the method fails when src sentence contains a ' symbol. For e.g. it's, don't.
This is bcz it is conflicting with the ' symbol provided here: d \'[{
Can you specify the some ways to solve this?

**Comment by pltrdy** [comment]
Yep for sure, you need to escape those special characters (single `'` and double `"` quotes) with a blackslash `\` e.g. 

`curl -i -X POST -H "Content-Type: application/json" -d '[{"src": "it\'s raining", "id": 100}]' http://$HOST:$PORT$URL_ROOT/translate`

**Comment by nikhiljaiswal** [comment]
i tried that earlier, but that's not working. plz have a look at the attached screnshot.
![error](https://user-images.githubusercontent.com/21051117/52783053-a8561a00-3076-11e9-96f7-fa5d51dada43.png)

**Comment by nikhiljaiswal** [comment]
Also, I had one more doubt. Is there a way to replace <unk> word from the target?
![image](https://user-images.githubusercontent.com/21051117/52783297-7e512780-3077-11e9-85e0-a92340d2a225.png)

**Comment by pltrdy** [comment]
1) indeed, it's not that straightforward, google has an answer tho https://stackoverflow.com/a/39802572
2) don't understand the point. Your src is probably out of vocabulary, therefore, there's not much the model can do.

**Comment by nikhiljaiswal** [comment]
1. It was of great help. thanks a lot.
2. yes, the src is out of vocabulary. So, for such OOV or UNK words, there is no method to handle ?

**Comment by nikhiljaiswal** [comment]
Is BPE available here?

**Comment by pltrdy** [comment]
2. Hmm, I'm not sure what kind of method could handle it. I mean, what would you expect as an output for an unknown input word? 

3. You can define tokenizing related options, [see example conf](https://github.com/OpenNMT/OpenNMT-py/blob/master/available_models/example.conf.json#L14), you can set `type` to `sentencepiece` or `pyonmttok` ([src](https://github.com/OpenNMT/OpenNMT-py/blob/master/available_models/example.conf.json#L14))

**Comment by nikhiljaiswal** [comment]
Hi @pltrdy @vince62s 
I was able to create chat response interface using translation server as suggested by you.
I have to put the code in the production. 
Can we not load a model once and translate different sentences one by one instead of using a server to do so.
I am not much experienced in PyTorch, so am unable to come out with it.
My question is simple. Just load model once and get responses of query in a loop.
Can't we do that here?

**Comment by pltrdy** [comment]
How is it different from using `https://github.com/OpenNMT/OpenNMT-py/blob/master/translate.py` directly?

**Comment by nikhiljaiswal** [comment]
That takes as input as a file. If we think of passing an input sentence through file and retrieving the predicted response from output file, that can be done. But the problem will be that, for each query we will be have to load the model again and again.

**Comment by pltrdy** [comment]
And that's precisely why we wrote the translation server: load once, translate anything. Just set `"timeout": -1` in your server config file if you want it to be kept loaded.

**Comment by nikhiljaiswal** [comment]
Yes, I understand that translation server will help us achieve that. But my problem is that will I be able to use that type of server for production use. 
Since, we have to define IP, Port etc. to use the server, I feel that the process might get complicated when utilizing the model for production and deploying it further on cloud.

I was just eager to understand that, can't we achieve something similar to what being displayed in attached screenshot Keras code where I have loaded a model and utilized it to query several sentences. Although the code is not for NMT, but for a similar task.

![image](https://user-images.githubusercontent.com/21051117/54676718-539b3880-4b27-11e9-8000-547776d82807.png)

Even if OpenNMT wasn't being prepared to achieve this, can you refer me some code where I can train my model to achieve the same. The Transformer model performed very good on my dataset.
