### ISSUE TITLE
mermaid in annotation

### ISSUE THREAD

**Issue by hwijeen** [OpenNMT/OpenNMT-py#1289]
Hi, 
I see annotations starting with '.. mermaid:: ' in source code.
I learned that mermaid is a script language that generates diagrams from text.

How is this mermaid annotation supposed to be turned into graph?
Does it assume that people use some kind of vim/pycharm plugin to generate graph from source code?
What should I do to make a graph out of it in vim/pycharm?

Thanks,
Hwijeen

**Comment by vince62s** [comment]
enjoy: https://github.com/knsv/mermaid

**Comment by hwijeen** [comment]
Yep! So copying and pasting the mermaid code into the web editor is the only suggested way?
