### ISSUE TITLE
Library Example-issue

### ISSUE THREAD

**Issue by mahdavis** [OpenNMT/OpenNMT-py#1291]
Hi,

I need to run the example library mentioned in http://opennmt.net/OpenNMT-py/Library.html. In the first step,  I got errors, please see the code and related errors

code lines:
vocab = dict(torch.load("../../data/data.vocab.pt"))
src_padding = vocab["src"].stoi[onmt.inputters.PAD_WORD]
tgt_padding = vocab["tgt"].stoi[onmt.inputters.PAD_WORD]

Error:
AttributeError: 'list' object has no attribute 'stoi'

AttributeError: module 'onmt.inputters' has no attribute 'PAD_WORD'

I looked at onmt.inputters and it does not have PAD_WORD. Could you please tell me how I can run this example or fix this errors.  thanks,

**Comment by vince62s** [comment]
We have made a deep refactoring and the doc is not up to date.
We'll try to do so, in the meantime reading the code is your best option....

**Comment by vince62s** [comment]
#1292
