### ISSUE TITLE
fast flag throwing unexpected error

### ISSUE THREAD

**Issue by deepak1357** [OpenNMT/OpenNMT-py#1293]
Hi @vince62s , @bpopeters ,
I am getting the following error when enabling the 'fast' fag in translate.py:
![image](https://user-images.githubusercontent.com/14105096/52724306-1cd87c80-2fd5-11e9-94ea-ddc2f453d603.png)

Although, it is working fine w/o 'fast' flag. 
Please help

**Comment by vince62s** [comment]
please read the release notes / changelog. cheers.
