### ISSUE TITLE
assert self.global_scorer.beta == 0 

### ISSUE THREAD

**Issue by Huijun-Cui** [OpenNMT/OpenNMT-py#1295]
It really make me crazy , I am doing research with open-nmt ,  I will modify the code based on the open-nmt , but open-nmt keep changing the version and new bug is keep occurring ,
when I run this code ,the error happend , I can run this command before ,but today error happend ,gigaword_copy_acc_51.78.pt  is the pre-trained model dowloaded from your official website

 python translate.py -gpu 0 \
                    -batch_size 20 \
                    -beam_size 10 \
                    -model models/gigaword_copy_acc_51.78.pt \
                    -src datasets/gigaword/sumdata/Giga/input.txt \
                    -output testout/giga.out \
                    -min_length 35 \
                    -verbose \
                    -stepwise_penalty \
                    -coverage_penalty summary \
                    -beta 5 \
                    -length_penalty wu \
                    -alpha 0.9 \
                    -verbose \
                    -block_ngram_repeat 3 \
                    -ignore_when_blocking "." "</t>" "<t>"

**Comment by vince62s** [comment]
If you want some help; you need to post your error trace and the version (or master) you use.
If you're not happy with master, feel free to stay on an older tag.
