### ISSUE TITLE
Serve OpenNMT as REST API

### ISSUE THREAD

**Issue by dyngts** [OpenNMT/OpenNMT-py#1297]
Dear @vince62s and others,

Any pointer to any docs that can guide me how to deploy the OpenNMT model as REST API (I'm expecting for Pytorch 1.0 Serving). I can't find it in the official docs. Thanks!

**Comment by nikhiljaiswal** [comment]
Hi,
Please have a look at the following link. It might be of your help.

http://forum.opennmt.net/t/simple-opennmt-py-rest-server/1392

**Comment by dyngts** [comment]
Thanks @nikhiljaiswal for the answer. It seems that article more showing how to load the model as REST API.

What i'm really looking for is tutorial that can guide me how to convert this OpenNMT model as graph through JIT script or convert it as C++ code to achieve high performant model as introduced in Pytorch 1.0. Just wondering if there are people who already done this, thus i can just reuse it. Thanks

**Comment by flauted** [comment]
@dyngts actually the most recent conversation on Gitter is related to that.

![screenshot from 2019-02-16 19-36-34](https://user-images.githubusercontent.com/29395172/52906805-37ebfc00-3222-11e9-8685-87eaa332f847.png)

Not totally conclusive, but I take it the answer is that no one is aware of a solution, but contributions are welcome!

**Comment by dyngts** [comment]
ok thanks @flauted for the info!
