### ISSUE TITLE
[feature request] Better handling of vocab reuse

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT-py#1304]
At the moment we have:
preprocess.py that will take text files and output 1) preprocessed .pt dataset 2) .pt vocab files

preprocess.py can take as arguments src_vocab / tgt_vocab that need to be text files "one word per line".

create_vocabulary.py will create text files from either text dataset files or .pt preprocessed dataset files.

This is not very covenient when it comes to train a new dataset (or added data to a dataset) with an existing vocabulary.

New feature 1: possibility to load directly .pt vocab at preprocessing to force the use of an existing vocab.

New feature 2: same as 1, but add new words in the .pt vocab, without losing the indexing of course.

**Comment by lordeddard** [comment]
I need some clarification regarding the first feature. If we choose to use the existing vocabulary, then we should pass the paths given in `-src_vocab` , `-tgt_vocab` to `train.py` and load the vocab since we are not building the vocabulary again. Am I right? Thanks!

**Comment by vince62s** [comment]
well, not exactly.
It looks weird because your first PR was a bit close enough to the need but the point is as follow:
We need to be able to pass an existing .pt vocab that may have a different "name" than the standard one.
But in fact the preprocess will just read it and dump it with the standard name.
everything will be at preprocess. It's just that -src_vocab will accept either a text file or a pickle file.
clearer?

**Comment by vince62s** [comment]
New Feature 1 is done.

New Feature 2 later, closing for now.
