### ISSUE TITLE
Transformer overfitting

### ISSUE THREAD

**Issue by circlePi** [OpenNMT/OpenNMT-py#1315]
I performed transformer training on my datasets of 200k sentence pairs(translation from English to Chinese) using the parameters as recommended in the opennmt document. But over-fitting happened at 1000 valid steps, and this situation become heavier as the training goes.
Could you give me some suggestions to overcome this problem?

**Comment by circlePi** [comment]
One more thing, when performed brnn training on the same datasets, all things is right.

**Comment by circlePi** [comment]
One more thing, When performed brnn training on the same datasets, all things get right.

**Comment by vince62s** [comment]
The network might be too big for such a small dataset.
try to reduce the number of layers and / or the size of each.
