### ISSUE TITLE
Please make sure you have pytorch >=1.0 AND torchtext 0.40 from the github master repo.

### ISSUE THREAD

**Issue by prigioni** [OpenNMT/OpenNMT-py#1316]
Please make sure you have pytorch >=1.0 AND torchtext 0.40 from the github master repo.
but  Could not find a version that satisfies the requirement torchtext==0.4.0 (from versions: 0.1.1, 0.2.0, 0.2.1, 0.2.3, 0.3.1)
No matching distribution found for torchtext==0.4.0
_Originally posted by @vince62s in https://github.com/OpenNMT/OpenNMT-py/issues/1313#issuecomment-464684550_

**Comment by vince62s** [comment]
If you just read the home page you will see how to install requirements
and if you dig abit you will see it installs torchtext with git+https://github.com/pytorch/text
which will give you 0.4
