### ISSUE TITLE
-save_checkpoint_steps doesn't work!!

### ISSUE THREAD

**Issue by cdj0311** [OpenNMT/OpenNMT-py#1322]
hi, all:
I'm doubt -save_checkpoint_steps doesn't work, **nothing to save**, the command as fellows:

python train.py -data data/demo -save_model demo_model -train_steps 10000 -save_checkpoint_steps 1000 -valid_steps 1000 -world_size   -gpu_ranks 1 -batch_size 128 -optim adam learning_rate 0.001

What's the problem for this?

**Comment by guillaumekln** [comment]
Hi,

If you have a single GPU you should use `-gpu_ranks 0`.

**Comment by cdj0311** [comment]
@guillaumekln I have 4 GPUs

**Comment by guillaumekln** [comment]
See here: http://forum.opennmt.net/t/unable-to-use-save-checkpoint-steps-with-gpu-enabled/2451
