### ISSUE TITLE
ZeroDivisionError for summarization

### ISSUE THREAD

**Issue by shantipriyap** [OpenNMT/OpenNMT-py#1324]
Train.py is failing during training with the below error when for the Giga word dataset. Preprocess runs fine.

UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  align_vectors = self.sm(align.view(batch*targetL, sourceL))

torch/nn/modules/container.py:67: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
Traceback (most recent call last):
  File "train.py", line 340, in <module>
    main()
  File "train.py", line 336, in main
    train_model(model, train, valid, fields, optim)
  File "train.py", line 182, in train_model
    print('Validation perplexity: %g' % valid_stats.ppl())
  File "/XXX/Abstractive-summarization-OpenNMT/onmt/Trainer.py", line 48, in ppl
    return math.exp(min(self.loss / self.n_words, 100))
ZeroDivisionError: division by zero

**Comment by vince62s** [comment]
You seem to be using a very old version. Please use the latest with pytorch 1.0.1 and Torchtext 0.4

**Comment by shantipriyap** [comment]
Thanks for your response.  although able to install pytorch 1.0.1 getting below error that there is no matching version available for torchtext 0.4. My pythorn verson is 3.6

 Could not find a version that satisfies the requirement torchtext==0.4 (from versions: 0.1.1, 0.2.0, 0.2.1, 0.2.3, 0.3.1)

Any suggestion ?.

**Comment by shantipriyap** [comment]
After installed the below suggested version, also getting the same error. Another thing to mention that my cuda version is: Cuda compilation tools, release 9.2, V9.2.148

torch                    1.0.1      
torchtext                0.4.0

**Comment by vince62s** [comment]
"/XXX/Abstractive-summarization-OpenNMT/onmt/Trainer.py"
Trainer.py with an uppercase T is an old version
are you on master ?
