### ISSUE TITLE
Question about position embedding

### ISSUE THREAD

**Issue by yangyaofei** [OpenNMT/OpenNMT-py#1328]
why multiply a sqrt of x.dim ? it's some trick or something? I can't find it in tensot2tensor and paper "Attention is All you need".
please, tell me, thx
https://github.com/OpenNMT/OpenNMT-py/blob/d6870f907d77ec90bab482b356dd4599b803b477/onmt/modules/embeddings.py#L48

**Comment by guillaumekln** [comment]
In the paper, last sentence of the section 3.4.

**Comment by yangyaofei** [comment]
@guillaumekln oh, I was thinking that is part of position encoding.😂 thank you
