### ISSUE TITLE
rnn_size in Transformer

### ISSUE THREAD

**Issue by gitlost-murali** [OpenNMT/OpenNMT-py#1330]
I've seen your recommended training command for Transformer [here](https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md). A Vaswani et.al 's Transformer paper doesn't have RNNs. From where did you include this. Is there any reference paper. Can you give specifics on where RNNs are included.

**Comment by vince62s** [comment]
the argument naming is wrong, it's just the dmodel size.
