### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGUSR1'

### ISSUE THREAD

**Issue by robeld** [OpenNMT/OpenNMT-py#1333]
Downloaded the pre-trained English-German Transformer from http://opennmt.net/Models-py/, and when I unzipped it got a .pt and a .model file. Then, I fed the path of the .pt file into the command given http://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-the-transformer-model (with the --train_from flag) and got the error in the title. From some searching, this seems to be a Windows problem, but I'm not sure how to resolve it. I would like to load the pre-trained model using the state_dict given in .pt, but I'm not sure how to make sure that it fits the same parameters of the original model without using the train.py script.

**Comment by vince62s** [comment]
Please use the forum for this type of general question. Also read more previous post, and give exact command lines you used + trace of your errors.
However not sure about the windows problem.
