### ISSUE TITLE
ensemble models

### ISSUE THREAD

**Issue by LeonCrashCode** [OpenNMT/OpenNMT-py#1334]
I encounter two problems on ensembles.

1) I used scripts preprocess.py to prepare the data 
```
program="../OpenNMT-py/preprocess.py"
python $program --train_src data/silver_gold.src \
	--train_tgt data/silver_gold.tgt \
	--valid_src data/gold_dev.src \
	--valid_tgt data/gold_dev.tgt \
	--src_words_min_frequency 3 \
	--tgt_words_min_frequency 3 \
	--src_seq_length 4000 \
	--tgt_seq_length 4000 \
	--dynamic_dict \
	-save_data data-bin/data
```

and then I train the several models with different random seed.
```
program="../../OpenNMT-py/train.py"
for idx in 1 2 3 4
do
save_model="checkpoints"${idx}"/checkpoints"
log_file="log"${idx}
random_seed=$RANDOM
echo random_seed $random_seed
python $program -data data-bin/data \
	-src_word_vec_size $src_word_vec_size \
	-tgt_word_vec_size $tgt_word_vec_size \
	-layers $layers \
	-rnn_size $rnn_size \
	-transformer_ff $transformer_ff \
	-heads $heads \
	-save_model $save_model \
	-log_file $log_file \
	-dropout $dropout \
	$bridge \
	-encoder_type $encoder_type \
	-decoder_type $decoder_type \
	$position_encoding \
	$copy_attn -copy_attn_type $copy_attn_type \
	-max_relative_positions $max_relative_positions \
	-global_attention $global_attention \
	-report_every $report_every \
	-train_steps $train_steps \
	-batch_size $batch_size \
	-batch_type $batch_type \
	-optim $optim \
	-learning_rate $learning_rate \
	-learning_rate_decay $learning_rate_decay \
	-max_grad_norm $max_grad_norm \
	-adam_beta2 $adam_beta2 \
	-start_decay_steps $start_decay_steps \
	-decay_steps $decay_steps \
	-pre_word_vecs_enc $pre_word_vecs_enc \
	-pre_word_vecs_dec $pre_word_vecs_dec \
	-save_checkpoint_steps $save_checkpoint_steps \
	-valid_steps $valid_steps \
	-param_init $param_init \
	$param_init_glorot \
	-normalization $normalization \
	-accum_count $accum_count \
	-seed $random_seed \
	-world_size 4 -gpu_ranks 0 1 2 3  
done
```
When I do ensemble inference with the four trained models, it raised a error "AssertionError: Ensemble models must use the same preprocessed data". 
```
program="../../OpenNMT-py/translate.py"
python $program -src ${1} \
        -output ${2} \
        -model checkpoints1/checkpoints_step_40000.pt checkpoints2/checkpoints_step_40000.pt checkpoints3/checkpoints_step_40000.pt checkpoints4/checkpoints_step_40000.pt\
        -beam_size $beam_size \
        -max_length $max_length \
        $replace_unk \
        -n_best $n_best \
        -length_penalty $length_penalty \
        -coverage_penalty $coverage_penalty \
        -log_file_level $log_file_level \
        -log_file $log_file \
```
As you seen, For each models, I still use the same input "-data data-bin/data". How to solve this problem.

2) The other problem is that I try to ensemble models with two latest updates.
```
program="../../OpenNMT-py/translate.py"
python $program -src ${1} \
        -output ${2} \
        -model checkpoints1/checkpoints_step_38000.pt checkpoints2/checkpoints_step_40000.pt\
        -beam_size $beam_size \
        -max_length $max_length \
        $replace_unk \
        -n_best $n_best \
        -length_penalty $length_penalty \
        -coverage_penalty $coverage_penalty \
        -log_file_level $log_file_level \
        -log_file $log_file \
```
it raised the error "AttributeError: 'EnsembleDecoder' object has no attribute 'attentional'". But in my training setting encoder and decoder are transformer and global attentions and copy attentions are set. How did it happen? Thanks

**Comment by flauted** [comment]
Point 2 is related to #1314. As a short term workaround you might be able to check out a version before that commit. I'll try to fix that soon. Ensemble translation is tested in Travis so also need to figure out why it didn't fail.

**Comment by vince62s** [comment]
I am using ensembling without any issue. Are yo using coverage_penalty ?

**Comment by LeonCrashCode** [comment]
> I am using ensembling without any issue. Are yo using coverage_penalty ?

@vince62s I did not use the coverage_penalty and set coverage_penalty with none. Does it cause errors?

**Comment by vince62s** [comment]
no. but it is impossible to figure out what kid of model you trained and what options you used because you posted with variables instead of actual parameters.

**Comment by LeonCrashCode** [comment]
@vince62s Thanks and sorry for fuzzy post. below is the completed scripts I used.

```
program="../../OpenNMT-py/train.py"
for idx in 1 2 3 4
do
save_model="checkpoints"${idx}"/checkpoints"
log_file="log"${idx}
random_seed=$RANDOM
echo random_seed $random_seed
python $program -data data-bin/data \
	-src_word_vec_size 300\
	-tgt_word_vec_size 300\
	-layers 6 \
	-rnn_size 300\
	-transformer_ff 2048\
	-heads 6\
	-save_model checkpoints1/checkpoints\
	-log_file log \
	-dropout 0.2\
	-bridge \
	-encoder_type transformer \
	-decoder_type transformer \
	-position_encoding \
	-copy_attn -copy_attn_type dot\
	-max_relative_positions 1000\
	-global_attention general\
	-report_every 100\
	-train_steps 40000\
	-batch_size 512\
	-batch_type tokens\
	-optim adam\
	-learning_rate 0.001\
	-learning_rate_decay 0.7\
	-max_grad_norm 0\
	-adam_beta2 0.998\
	-start_decay_steps 5000\
	-decay_steps 1000\
	-pre_word_vecs_enc ../../data/data-bin/embeddings-300.enc.pt\
	-pre_word_vecs_dec ../../data/data-bin/embeddings-300.dec.pt\
	-save_checkpoint_steps 2000 \
	-valid_steps 2000\
	-param_init 0\
	-param_init_glorot \
	-normalization tokens\
	-accum_count 2\
	-seed $random_seed \
	-world_size 4 -gpu_ranks 0 1 2 3  
done 
```

And the ensemble script is
```
program="../../OpenNMT-py/translate.py"
python $program -src ${1} \
        -output ${2} \
        -model checkpoints1/checkpoints_step_38000.pt checkpoints2/checkpoints_step_40000.pt\
        -beam_size 10\
        -max_length 1000\
        -replace_unk \
        -n_best 1\
        -length_penalty avg \
        -coverage_penalty none\
        -log_file_level WARNING\
        -log_file log_ens\
```

if I ensemble the two latest checkpoint model, it raised error "AttributeError: 'EnsembleDecoder' object has no attribute 'attentional'". If I ensemble the models trained on same dataset in the same setting but in different random seed, it raises the errors "AssertionError: Ensemble models must use the same preprocessed data". 

I am not sure if the preprocessing script is based on random seed. If you have any idea about it, it will be helpful.

**Comment by LeonCrashCode** [comment]
@flauted Thanks for your suggestions, I checkout 518a19d, it raised a new error "'EnsembleDecoderOutput' object has no attribute 'view'". so which commit I should checkout.

**Comment by vince62s** [comment]
For this one you need to wait for a fix, or take a much older tag.

My concern is more about the vocab thing.

**Comment by vince62s** [comment]
@flauted  did you get a chance to fix the above ?

**Comment by flauted** [comment]
No, it slipped my mind. I'll take a look tonight or tomorrow.

**Comment by flauted** [comment]
I've gotten busy and haven't had a chance to test this, but I think the fix is something like this:

In translate/translator.py, [line 149](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translator.py#L149) change
```
if self.replace_unk and not self.model.decoder.attentional:
    raise ValueError("replace_unk requires an attentional decoder.")
```
to
```
try:
    attentional = self.model.decoder.attention
except AttributeError:
    # must be an ensemble
    attentionals = [dec.attentional for dec in self.model.decoder.model_decoders]
    assert all(attentionals) or not any(attentionals), \
        "Use all attentional models or no attentional models."
    attentional = all(attentionals)
if self.replace_unk and not attentional:
    raise ValueError("replace_unk requires an attentional decoder.")
```

and then change [line 161](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translator.py#L161) from
```
if self.global_scorer.has_cov_pen and \
    not self.model.decoder.attentional:
```
to
```
if self.global_scorer.has_cov_pen and not attentional:
```
I'm guessing this didn't show up in Travis because it doesn't test ``replace_unk`` or coverage penalty. Since Python uses short-circuit logic the second part of these two if statements wouldn't have ran so the attribute lookup never would have failed.

**Comment by nikhiljaiswal** [comment]
hi @flauted ,

I tried to incorporate the changes suggested by you and run the ensemble models. I was able to run the code successfully. However, when I tried to run the model without ensemble, i.e with a single checkpoint file, I was encountered with an error. Please have a look at the attached error and provide yours valuable suggestions.

![image](https://user-images.githubusercontent.com/21051117/54586217-5ec86880-4a42-11e9-8808-5312a2583894.png)

**Comment by flauted** [comment]
Is there anything above it about error occurred while handling an AttributeError? I don't really understand why it's failing out of the ``try: attentional = self.model.decoder.attention`` block. @nikhiljaiswal

**Comment by nikhiljaiswal** [comment]
no this is the only error. basically, it is unable to recognize model_decoders

**Comment by flauted** [comment]
Okay, then, I'm wondering did you copy the whole thing:
```
try:
    attentional = self.model.decoder.attention
except AttributeError:
    # must be an ensemble
    attentionals = [dec.attentional for dec in self.model.decoder.model_decoders]
    assert all(attentionals) or not any(attentionals), \
        "Use all attentional models or no attentional models."
    attentional = all(attentionals)
if self.replace_unk and not attentional:
    raise ValueError("replace_unk requires an attentional decoder.")
```
The ``try`` is important, too. The except stuff handles the ensemble but it won't work for not-ensembled decoders.

**Comment by flauted** [comment]
Oh nevermind it's my fault. Should be
```
try:
    attentional = self.model.decoder.attentional

**Comment by nikhiljaiswal** [comment]
@flauted it's working now. thanks!

**Comment by vince62s** [comment]
@nikhiljaiswal can you please submit a PR ?
thanks.

**Comment by vince62s** [comment]
can someone submit a PR please ?

**Comment by flauted** [comment]
Yes I will later today.
