### ISSUE TITLE
Codec Error When feeding sentence to Translation Server

### ISSUE THREAD

**Issue by fmobrj** [OpenNMT/OpenNMT-py#1339]
Hi @pltrdy . I am feeding simple sentences or terms to the server, but I am allways receiving a codec error response from it. (I just cloned the repo and am using the latest commits)

Post data:
$ curl -i -X POST -H "Content-Type: application/json" -d '[{"src": "this contract is still valid", "id": 0}]' http://$HOST:$PORT$URL_ROOT/translate

Server Response:
![image](https://user-images.githubusercontent.com/22793365/53760707-6d3f4d80-3ea2-11e9-9de4-4e51dde9185b.png)

Thanks,
Fabio.

**Comment by pltrdy** [comment]
@fmobrj thanks for the issue. see the PR where I reference this issue (right above this comment). 

Could you confirm (i) that it fixes the problem (haven't reproduced), (ii) that you are running python2?

**Comment by fmobrj** [comment]
Thanks. @pltrdty! Yes. I am using python2. I will test it and confirm if it is working. 

Thank you very much.

**Comment by fmobrj** [comment]
@pltrdy It worked fine. Thanks.
