### ISSUE TITLE
Using uwsgi with server

### ISSUE THREAD

**Issue by fmobrj** [OpenNMT/OpenNMT-py#1343]
Hello, @pltrdy . I am bothering you again. I am trying to use uwsgi with the server, but I am facing some difficulties. uwsgi is complaining about not being able to find a callable application in server. Any hints?

Thank you very much.

**Comment by pltrdy** [comment]
The server is based on `flask` without having `uwsgi` in mind.

I guess you can look flask's doc about it, <http://flask.pocoo.org/docs/1.0/deploying/uwsgi/>.
There's no plan in supporting it, so you probably better just edit it locally. Unless a fix can make the code seamlessly `uwsgi` compatible (i.e. should not add requirement or much complexity), we would probably not merge it.

**Comment by fmobrj** [comment]
Ok. Thanks.
