### ISSUE TITLE
Beam search bug: returns no predictions

### ISSUE THREAD

**Issue by memray** [OpenNMT/OpenNMT-py#1345]
Hi,

I found that when I run beam search with a large n_best, it sometimes returns no results.
I think the problem may be due to the logic in beam_search.py: 
if the outer loop terminates ([the step reaching  the max_length](https://github.com/OpenNMT/OpenNMT-py/blob/5f0880920c3114d458a4266006e774b63cbf2271/onmt/translate/translator.py#L447)) but it hasn't collected enough finished sequences (self.hypotheses[b] is shorter than self.n_best at [line 223](https://github.com/OpenNMT/OpenNMT-py/blob/5f0880920c3114d458a4266006e774b63cbf2271/onmt/translate/beam_search.py#L223) in beam_search.py), it will return empty arrays (predictions, scores and attention).

Thanks,
Rui

**Comment by vince62s** [comment]
please read #1320 thanks

**Comment by vince62s** [comment]
reopen if needed.
