### ISSUE TITLE
pointer generator model starts overfitting 

### ISSUE THREAD

**Issue by priyanks179** [OpenNMT/OpenNMT-py#1348]
I am trying to train pointer generator network . After training for 10k iterations it starts overfitting.
Any suggestions on why this might be happening.
Note- 1==50 iterations
![adagrad 90k](https://user-images.githubusercontent.com/40527782/54075020-cbfc3100-42bf-11e9-8b48-657967edc989.png)

**Comment by vince62s** [comment]
Please post your question on the forum with the full context and command line.
with such few info, we can't help you.
