### ISSUE TITLE
beam.py log probs and not probs

### ISSUE THREAD

**Issue by ixlan** [OpenNMT/OpenNMT-py#1356]
As far as I understand the https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/beam.py advance operates on log-probabilities, as we add up log probs of histories and the next words. However, in the documentation of the method it says that word probabilities are expected, which I suspect to be a mistake.

**Comment by pltrdy** [comment]
You're correct, beam.py is outdated for sure, I think it only present for some kind of legacy reason (compatibility or very specific use-cases).

You should focus on <https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/beam_search.py>.
