### ISSUE TITLE
nn.DataParallel  AssertionError: Not all arguments have the same value: (16, 8) 

### ISSUE THREAD

**Issue by lipingbj** [OpenNMT/OpenNMT-py#1358]
I changed the multiprocessing to nn.DataParallel,but there is  a problem (AssertionError: Not all arguments have the same value: (16, 8) ).I use two GPU.
It seems that the src of the batch does not split to two but the lengths of the src split to two.

**Comment by vince62s** [comment]
Well, either you submit a PR with your code and we can discuss but the way you open this issue is nonsense, sorry.
