### ISSUE TITLE
ensemble not working as mentioned in faq

### ISSUE THREAD

**Issue by nikhiljaiswal** [OpenNMT/OpenNMT-py#1359]
Hi,
I am trying to use the ensemble approach during inference time as mentioned in the FAQ.
![image](https://user-images.githubusercontent.com/27516315/54524914-12751e00-4999-11e9-8b70-33ab6546227f.png)

But, I am getting error.
AttributeError: 'EnsembleDecoder' object has no attribute 'attentional'

Please help me with this.
Also, what ensembling technique is used here. I cannot find any documentation for this.

**Comment by vince62s** [comment]
duplicate #1334
