### ISSUE TITLE
Recognition fails on images outside the dataset (image to text)

### ISSUE THREAD

**Issue by wzlxjtu** [OpenNMT/OpenNMT-py#1360]
Hi, I'm having troubles converting math images to LaTex. Seems like the pre-trained model would fail on images that are outside the dataset. I tried to crop images from scientific papers, which has a similar size to the images in the dataset. However, the output would fail totally even for simple formulas. For debugging, I also took a screenshot of the images from the dataset, but the output for the screenshot would fail, even though the original images succeeded. The screenshot and the original image are almost the same, which really confuses me. Am I missing some preprocessing steps, or do I need to re-train the model with different image sizes? Hope this question doesn't sound too naive, but I really need some help. Thank you very much!

**Comment by Anmoldeep5056** [comment]
did you get it?
