### ISSUE TITLE
training and build batchs 

### ISSUE THREAD

**Issue by mahdavis** [OpenNMT/OpenNMT-py#1361]
Hi 

I used onmt.inputters.inputter.DatasetLazyIter to create batches and after that do train.

train_iter = onmt.inputters.inputter.DatasetLazyIter(         dataset_paths=[train_data_file],         fields=dataset_fields,         batch_size=50,         batch_size_multiple=1,         batch_size_fn=None,
        device=dev,         is_train=True,         repeat=False)

 The number of batches is 1000 and I need to train this model for  the number of epoch 100 so I set train_steps to 1000 *100.

trainer.train(train_iter=train_iter,    train_steps=100*1000,   valid_iter=valid_iter,
                  valid_steps=2)

But training finished sooner than train_steps, I think because I set repeat=False in .inputter.DatasetLazyIter which makes only 1000 batches. If I set repeat=true, it takes for ever to finish. Please help me how I can solve this problem? 

Thanks,

**Comment by vince62s** [comment]
if you're making your own code, difficult to provide help with so little info. Sorry.
are you following this ? https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/Library.md

**Comment by vince62s** [comment]
reopen if needed.
