### ISSUE TITLE
<Unk> symbol in summarization output

### ISSUE THREAD

**Issue by shantipriyap** [OpenNMT/OpenNMT-py#1363]
Now I am using OpnNMT-Py for summarization. I have trained the model using "Transformer model" using 80K training and 20k validation data. When I ran the translation for summarization using my validation data, the output is coming proper but with many <unk> symbols, How to deal with it ?. Do I have to train for more ?. Now I am running evaluation after 95k checkpoint. My training and validation dataset (german) not contain any "<unk>" symbols.

**Comment by vince62s** [comment]
too small a dataset.
