### ISSUE TITLE
Domain adaptation support for text summarization

### ISSUE THREAD

**Issue by shantipriyap** [OpenNMT/OpenNMT-py#1365]
As my dataset size is small, want to use other domain data. Does OpenNMT support it ?. If so, how to create the voab and training and learning parameter transferring ?.

**Comment by vince62s** [comment]
There are very very few public dataset for summarization. CNN/Daily mail is one of them and still, not very big.
If you are working on English, try mixing your data with theirs.

**Comment by shantipriyap** [comment]
Sorry, but now I am working on german data, so want to know how to use other domain data for performance improvement. Or if any big german dataset I can use ?.

**Comment by vince62s** [comment]
Not that I know.
