### ISSUE TITLE
torchtext 0.4.0 not available

### ISSUE THREAD

**Issue by Americanwallace0** [OpenNMT/OpenNMT-py#1368]
$ pip install torchtext==0.4.0
Collecting torchtext==0.4.0
Could not find a version that satisfies the requirement torchtext==0.4.0 (from versions: 0.1.1, 0.2.0, 0.2.1, 0.2.3, 0.3.1)
No matching distribution found for torchtext==0.4.0

**Comment by vince62s** [comment]
read the requirements.txt and / or setup procedure.
