### ISSUE TITLE
Solution to 2 problems running Speech to Text demo on Windows

### ISSUE THREAD

**Issue by catskillsresearch** [OpenNMT/OpenNMT-py#1378]
These are problems running Speech to Text demo:

1. TorchAudio is not supported on Windows.  I resolved this by rewriting the line of code that needed it, in onmt/inputters/audio_dataset.py:

```
        # sound, sample_rate_ = torchaudio.legacy.load(audio_path)
        import scipy.io.wavfile
        sample_rate_, sound = scipy.io.wavfile.read(audio_path)
        sound=np.array(sound,dtype=float)
        sound = torch.from_numpy(sound)
```
2. Vocab not pickling, see for example [this bug report](https://discuss.pytorch.org/t/attribute-lookup-field-lambda-on-torchtext-data-field-failed/35844).  For this it is necesssary to pip uninstall torchtext and then python setup.py install the GitHub, per solution in the comments of [this bug report](https://github.com/OpenNMT/OpenNMT-py/issues/1165).

**Comment by vince62s** [comment]
For 1. not sure what to do with this, maybe a quick note in the FAQ.md 
For 2; it's already said in the README.

**Comment by catskillsresearch** [comment]
If there is no other reason to use torchaudio, why not just permanently switch those lines to scipy?

**Comment by vince62s** [comment]
well not sure why @da03 used torchaudio instead.

**Comment by catskillsresearch** [comment]
Probably because it's a Torch application and TorchAudio is Torch branded.  But that limits the scope of the repo for speech to Linux users.  Using SciPy in this case will make it platform independent for speech.

**Comment by da03** [comment]
Does scipy support other formats other than wav? I used torchaudio cause it's based on libsox which supports many formats.

**Comment by catskillsresearch** [comment]
In this patch I used SciPy.audo.wavfile which I guess will only read wavfile.  Libsox has no Windows build because of some FLAC code that won't go through MSVC.  You could structure the code so that it goes to sox if you have sox and scipy if you dont.  I am working with Sphere files which are weird and for that I use a Windows tool outside of Python to convert to WAV and then I stay in WAV.

**Comment by da03** [comment]
Yeah, that makes sense. It'd be nice to support Windows through scipy as long as we don't break supports for other formats when torchaudio is installed.

**Comment by catskillsresearch** [comment]
FYI to go from Sphere to WAV on Windows I use [sph2pipe_v2.5](http://www.openslr.org/3/).  It's basically the only game in town for Windows.  My Sphere files use something called "alaw" recording.   [This is not supported out of the box in sox,](http://asrman.blogspot.com/2016/10/sox-cannot-play-files-with-law-encoding.html) so in the end I just care about WAV files once I've gotten to WAV.  There's no reason to care about anything else.  In the end it's just a vector of floats between -1 and 1.

Here is more info on the problem in libsox in Windows that keeps torchaudio off of Windows:

- https://github.com/pytorch/audio/issues/50
- https://sourceforge.net/p/sox/mailman/message/32638200/
- https://stackoverflow.com/questions/54872876/how-to-install-torch-audio-on-windows-10-conda

**Comment by vince62s** [comment]
okay, this is good to recall, but maybe what you can do is a PR on the FAQ.md file to report your findings so that windows users could find out this solution.

**Comment by catskillsresearch** [comment]
@vince62s , telling Windows users that they need to reach into a line of a code file in a subfolder and replace it with some other lines doesn't seem like the cleanest solution.  It's not something I'd put in a README.  I figure that people that are trying to make the OpenNMT speech example work on Windows will  run into the problems I had, start Googling it and looking at the issues, will find the lines I posted above, and then apply them to their copy.

**Comment by vince62s** [comment]
Fine. closing, then.
