### ISSUE TITLE
Copy models don't work with word features

### ISSUE THREAD

**Issue by AmitMY** [OpenNMT/OpenNMT-py#1379]
I don't know why, but I'm experiencing a very buggy behavior using:
- feat_vec_size 300,
- feat_merge sum

With 
-  copy_attn

For a test, I want my NMT system to repeat the input sentence.
I have a closed set of lowercase letters, and open set of uppercase letters, like:

> ABC a BBC b CDE c XYZ

If I do not use word features, it manages to copy everything it ever seen, and sometimes a bit more, but if the entire capital letters are unseen, it will have trouble:

> VCA a SDAS b SDAS c DSSDS

I thought that adding features like (O to mean Open, C to mean Closed): 
> ABC|O a|C BBC|O b|C CDE|O c|C XYZ|O

would help, I tried both feat merge = concat and sum.

Now the model never copies, even if it is something it already seen....

(Just by adding the features, I'm dropping from 55 BLEU to 27)

**Comment by AmitMY** [comment]
Note: the target sequence does not have word features, so:
> **Input**: ABC|O a|C BBC|O b|C CDE|O c|C XYZ|O
> **Output**: ABC a BBC b CDE c XYZ

**Comment by vince62s** [comment]
Please rephrase completely your issue / task because it is very unclear.
Also be more specific, explain the tokenization you used, the dataset size, vocab size, .....
Post this on the forum: http://forum.opennmt.net/

**Comment by AmitMY** [comment]
I think the phrasing was OK, the issue was my stupidity though, I used the pipe character instead of the correct Unicode character.
