### ISSUE TITLE
-report_every option works inconsistently with bptt

### ISSUE THREAD

**Issue by ratishsp** [OpenNMT/OpenNMT-py#1394]
Hi,
```optim.step()``` occurs in each loop of bptt size. 
https://github.com/OpenNMT/OpenNMT-py/blob/f7fc40e319c03b90addc7e3364635e0fc7625b95/onmt/trainer.py#L382

This results in inconsistent step count in
https://github.com/OpenNMT/OpenNMT-py/blob/f7fc40e319c03b90addc7e3364635e0fc7625b95/onmt/trainer.py#L238
The step count gets incremented by various values depending on target output length.

**Comment by ratishsp** [comment]
Just realized that the value of ```step % valid_steps == 0``` will be incorrect here in case bptt is applied:
https://github.com/OpenNMT/OpenNMT-py/blob/f7fc40e319c03b90addc7e3364635e0fc7625b95/onmt/trainer.py#L243
The PR doesn't fix this.

**Comment by ratishsp** [comment]
Hi @vince62s, any ideas on this issue?

**Comment by pltrdy** [comment]
You could try adding, after line 382:
```
                    self.optim.step()
                    if j > 0:
                        # not incrementing training step in case of bptt
                        self.optim._training_step -= 1
```

Note that `bptt > 0` is equivelent to `bptt=True`

**Comment by ratishsp** [comment]
That should work, thanks!
One question: this will make optimizer step and training steps to be different. The optimizer will update for each bptt whereas training step will increment once for each batch in a single gpu setup. Do you think this could create issue elsewhere?

**Comment by ratishsp** [comment]
Updated the PR https://github.com/OpenNMT/OpenNMT-py/pull/1395
