### ISSUE TITLE
[Feature Request] Training ETA / Remaining Time

### ISSUE THREAD

**Issue by DNGros** [OpenNMT/OpenNMT-py#1397]
While training from train.py the utils/statistic.py will periodically log info like loss, toks/s, and elapsed time. It would also be nice it printed an ETA as well so you know when your model will be done training.

I just greped to find where the logging message was coming from, and am not really familiar with the whole codepath to it or the training flow. With that caveat in mind, quickest way I see to do that might be is in utils.statistic.Statistic.output() to store the time from the last time it was called, and calculate a sec/step and then an ETA based off that. Does it seem reasonable to add that extra state to that object, or should it be tracked elsewhere in the training code?

**Comment by vince62s** [comment]
closing the issue since there is apending PR (which requires some validation though)
