### ISSUE TITLE
Cannot reproduce iwslt2018 MT results

### ISSUE THREAD

**Issue by mhn226** [OpenNMT/OpenNMT-py#1402]
Hi guys,

I'm wondering if any of you have tried to reproduce the MT baseline of iwslt2018: 
https://github.com/isl-mt/SLT.KIT/blob/master/systems/smallTED/Summary.en-de.md

They definitely used a very old version of OpenNMT to train the model that yielded these results (https://github.com/quanpn90/OpenNMT-py).

I'm struggling to reproduce this with the current version of OpenNMT, getting no luck so far. It was always behind what they reported. 

I haven't figured out the main differences between the two OpenNMT versions yet. If any of you happened to do the same thing and found out the reason, please let me know!

Thank you for your concerning!

**Comment by vince62s** [comment]
I doubt someone did it recently. the dataset is a bit small.
