### ISSUE TITLE
Seems to be redundant code in train_single.py

### ISSUE THREAD

**Issue by ratishsp** [OpenNMT/OpenNMT-py#1405]
Why do we need this line https://github.com/OpenNMT/OpenNMT-py/blob/dcaeb2347b5e3bab0dcf3c1c1e1136e29ae65ebf/onmt/train_single.py#L38
It is invoked by https://github.com/OpenNMT/OpenNMT-py/blob/dcaeb2347b5e3bab0dcf3c1c1e1136e29ae65ebf/train.py#L39

**Comment by vince62s** [comment]
not sure to understand your question.

**Comment by ratishsp** [comment]
I was wondering if need this code:
https://github.com/OpenNMT/OpenNMT-py/blob/dcaeb2347b5e3bab0dcf3c1c1e1136e29ae65ebf/onmt/train_single.py#L38

If I comment this code and only set CUDA_VISIBLE_DEVICES it works well enough.

https://pytorch.org/docs/stable/cuda.html?highlight=torch%20cuda%20set_device#torch.cuda.set_device

**Comment by vince62s** [comment]
this is needed for multi process.
