### ISSUE TITLE
error "CUDA out of memory" when training

### ISSUE THREAD

**Issue by jiahaosuda** [OpenNMT/OpenNMT-py#1406]
Hi.

when I put in the parameters of training, it outputs the error "### RuntimeError: CUDA out of memory. Tried to allocate 73.50 MiB (GPU 0; 11.17 GiB total capacity; 732.35 MiB already allocated; 60.12 MiB free; 4.90 MiB cached)". 
![微信图片_20190422235443](https://user-images.githubusercontent.com/40142236/56509610-09f4a200-655a-11e9-9d7a-61002714e3d8.png)

But I have input the parameter "-world_size 1 -gpu_ranks 6" and the output is the picuter below.
![微信图片_20190422235127](https://user-images.githubusercontent.com/40142236/56509444-93f03b00-6559-11e9-9682-d2d2e0fa11e3.png)

It means training on GPU [6]. But why it shows the error that GPU[0] doesn't have enough memory? And how can I solve the problem? Thanks.

**Comment by jiahaosuda** [comment]
And my full command is like below.

python train.py -data data/amrtest.low -save_model amrtest_model -world_size 1 -gpu_ranks 6 -layers 6 -rnn_size 512 -word_vec_size 512 -transformer_ff 2048 -heads 8 -encoder_type transformer -decoder_type transformer -position_encoding -train_steps 100000  -max_generator_batches 2 -dropout 0.1 -batch_size 10000 -batch_type tokens -normalization tokens  -accum_count 2 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 2 -max_grad_norm 0 -param_init 0  -param_init_glorot -label_smoothing 0.1 -valid_steps 5000 -save_checkpoint_steps 5000

**Comment by vince62s** [comment]
This has been discussed already.
Please use CUDA_VISIBLE_DEVICE=6
and then
world_size 1 gpu_ranks 0
