### ISSUE TITLE
Using the pointer generator architecture/ Transformer with Copy attention

### ISSUE THREAD

**Issue by Shashi456** [OpenNMT/OpenNMT-py#1408]
So the current summarization tutorial is present to replicate the bottom up abstractive summarization model. 
I wanted to know if and how i could train the pointer generator or the transformer with copy attention on a different kind of dataset, or how i could go about adopting the model here to those requirements.

Thank You.

**Comment by vince62s** [comment]
not sure to follow what you mean.
Summarization is not an easy task with many available datasets.
So if you have a large amount of data on your own, feel free to give it a try.
Also the tuto os not really the original "pointer generator" architecture.
please use the forum for further questions.

**Comment by Shashi456** [comment]
@vince62s Newsroom dataset is available so is gigaword, DUC2000, and NYT btw. just saying.
