### ISSUE TITLE
Im2Text - Unexpected prediction output

### ISSUE THREAD

**Issue by vndee** [OpenNMT/OpenNMT-py#1417]
Hi,
I've used pre-trained model trained with im2latex-100k-dataset and run `translate.py` on CPU for demo expression given by OpenNMT-py document:
![](http://lstm.seas.harvard.edu/latex/results/website/images/119b93a445-orig.png)
But I've got an irrelevant output:
```
SENT 1: None
PRED 1: { \cal D } { \bf S } \, \prod _ { \bf p } \ \Longleftrightarrow \ { \bf D } { \bf A } ^ { \bullet } { \bf P }
PRED SCORE: -10.8810
PRED AVG SCORE: -0.3200, PRED PPL: 1.3772
```
I don't know what I am wrong here, please help me. Thanks.

**Comment by da03** [comment]
Hmm where does the test image come from? Is that also from im2latex-100k-dataset?

**Comment by vndee** [comment]
> Hmm where does the test image come from? Is that also from im2latex-100k-dataset?

The test images come from OpenNMT-py document: http://opennmt.net/OpenNMT-py/im2text.html
It's output should be 
```
 d s _ { 1 1 } ^ { 2 } = d x ^ { + } d x ^ { - } + l _ { p } ^ { 9 } \frac { p _ { - } } { r ^ { 7 } } \delta ( x ^ { - } ) d x ^ { - } d x ^ { - } + d x _ { 1 } ^ { 2 } + \; \cdots \; + d x _ { 9 } ^ { 2 } 
```

**Comment by HongChow** [comment]
> Hi,
> I've used pre-trained model trained with im2latex-100k-dataset and run `translate.py` on CPU for demo expression given by OpenNMT-py document:
> ![](https://camo.githubusercontent.com/8516e379e6ed493de3deba42d66c4a4d620336af/687474703a2f2f6c73746d2e736561732e686172766172642e6564752f6c617465782f726573756c74732f776562736974652f696d616765732f313139623933613434352d6f7269672e706e67)
> But I've got an irrelevant output:
> 
> ```
> SENT 1: None
> PRED 1: { \cal D } { \bf S } \, \prod _ { \bf p } \ \Longleftrightarrow \ { \bf D } { \bf A } ^ { \bullet } { \bf P }
> PRED SCORE: -10.8810
> PRED AVG SCORE: -0.3200, PRED PPL: 1.3772
> ```
> 
> I don't know what I am wrong here, please help me. Thanks.
Have you settle this problem?

**Comment by da03** [comment]
oh you need to downsample that image by 2. Because during preprocessing we downsampled every image by 2, and the one given in the document is the original (before downsampling) one for best resolution. Note that neural networks are very domain sensitive, so in order to get it work we need to make sure test domain matches the training domain. I.e. if we want to get a robust model at test time, we need to use all kinds of image (different sizes, different fonts) at training time.

**Comment by vaidhin** [comment]
HIi @da03  even after downsampling the image , I am just getting empty table like below.. any clues ?

[2020-09-07 05:48:38,108 INFO] 
SENT 2: None
PRED 2: <tabular> <tbody> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> </tbody> </tabular>
PRED SCORE: -0.4111 

command used:  !python translate.py --data_type img --model model/model.pt --src_dir input/ --output pred.txt --gpu 0 --verbose --src source/source.txt   

image format :png and jpg
