### ISSUE TITLE
check if is_cuda while setting cudnn deterministic?

### ISSUE THREAD

**Issue by ratishsp** [OpenNMT/OpenNMT-py#1420]
I guess we should check ```is_cuda``` too while setting ```cudnn``` as ```deterministic```
https://github.com/OpenNMT/OpenNMT-py/blob/03fe8d9ce310959094f3063b78fb02cd63067553/onmt/utils/misc.py#L82

**Comment by vince62s** [comment]
probably right, can you PR ?
