### ISSUE TITLE
Copy generator does not work with ensemble decoding

### ISSUE THREAD

**Issue by ratishsp** [OpenNMT/OpenNMT-py#1422]
Hi,
I was trying to do ensemble decoding with a model having copy generator. It fails on the following line with the error: 
https://github.com/OpenNMT/OpenNMT-py/blob/03fe8d9ce310959094f3063b78fb02cd63067553/onmt/translate/translator.py#L575

AttributeError: 'EnsembleDecoderOutput' object has no attribute 'view'

I see that ```squeeze``` method is implemented in ```EnsembleDecoderOutput```. I guess we need to implement ```view``` and ```size``` methods

**Comment by vince62s** [comment]
@flauted not sure if you tested that case.

**Comment by ratishsp** [comment]
Just realized that this issue is duplicate of #1404
