### ISSUE TITLE
Transformer rnn_size doesn't consider word feature dimensions automatically

### ISSUE THREAD

**Issue by fdzzy** [OpenNMT/OpenNMT-py#1425]
It seems if I use word features with mode "concat" with Transformer, I have to specify the enc_rnn_size/dec_rnn_size to be (d_model + feature_dims) by myself:
https://github.com/OpenNMT/OpenNMT-py/blob/c8c2369a921c21e8392566f1f73a643816fae9c1/onmt/encoders/transformer.py#L85-L107

This behavior seems to be different than RNN, which considers the dimensions automatically:
https://github.com/OpenNMT/OpenNMT-py/blob/c8c2369a921c21e8392566f1f73a643816fae9c1/onmt/encoders/rnn_encoder.py#L37-L42

**Comment by vikrant97** [comment]
@fdzzy The source side word features are working with normal RNN encoder-decoder but not with transformer due the issue with model dimensions.
Were you able to find a workaround to this problem?
