### ISSUE TITLE
Pytorch 1.1.0 or 1.0?

### ISSUE THREAD

**Issue by eduamf** [OpenNMT/OpenNMT-py#1427]
Is there any problem in using Pytorch 1.1.0?

The README says: "Note that we currently only support PyTorch 1.0.0"

But, after the command
`pip install -r requirements.txt`

The Pytorch 1.1.0 is installed.

**Comment by vince62s** [comment]
both will work, I will update the readme when I bump a new version.
I just saw a performance boost with 1.1
