### ISSUE TITLE
-report_bleu during inference doesn't work correctly

### ISSUE THREAD

**Issue by ZiweiHe** [OpenNMT/OpenNMT-py#1429]
when activate `-report_bleu` during inference with `translation.py` it gives wrong param `tgt` to _report_bleu()

**Comment by vince62s** [comment]
Can you please be specific and post a command line + error backtrace ?
thanks

**Comment by Parkchanjun** [comment]
me too

command:  python3 ../../../translate.py -model ../model/model_step_80000.pt -src ./test.txt -output ./pred_80000.txt -replace_unk -verbose -report_bleu -report_time

Threre is no BLEU score announce.....

**Comment by chan0park** [comment]
Hi all,

I experienced the same issue (pytorch 1.1.0, python 3.7), and improvised a solution to make it work.
Main problem here was in `translate.py`, the function`translator.translate()` gives the `tgt` argument as a list of tgt lines (tgt_shard) while `_report_bleu()` in `onmt.translate.translator` needed tgt as tgt_path, not the list of lines to execute the BLEU script. 

Therefore, I needed to write given tgt_shard (list of lines) to a temporary file and use the path of the file as the input argument to `_report_bleu()`. Below is my code from [line 391 in translator.py](https://github.com/OpenNMT/OpenNMT-py/blob/b7c2c809544a3e869589f7575d1a0a7fcc35d081/onmt/translate/translator.py#L390-L392):
```
if self.report_bleu:
    fd, tgt_path = tempfile.mkstemp()
    try:
        with os.fdopen(fd, 'wb') as tempfile:
            tempfile(b"".join(tgt))
        msg = self._report_bleu(tgt_path)
        self._log(msg)
    finally:
        os.remove(tgt_path)
```

I believe the same applies to `report_rouge` option although I haven't tested.

But one thing I'm not sure yet is whether users would want to evaluate the BLEU score on each shard. For me, it makes more sense to evaluate BLEU over the entire output. If that's the case, then evaluating & reporting should be done outside of the [for loop](https://github.com/OpenNMT/OpenNMT-py/blob/b7c2c809544a3e869589f7575d1a0a7fcc35d081/translate.py#L25) in `translate.py`

@vince62s let me know if there's anything I can help you with this issue.

**Comment by vince62s** [comment]
@pltrdy @francoishernandez we need to implement a better solution or to remove this.
1) we remove it
2) we implement with a python package
3) we just call an external bash script leaving it to the user.

**Comment by francoishernandez** [comment]
No that trivial I think.
The issue is that if we want to compute the 'proper' corpus bleu, we need the full set / shard. So we'd need to keep it in memory or dump a temp file as @chan0park suggests.
Or, more elegant maybe, we could build some kind of CorpusBleu object inspired by sacrebleu's [corpus_bleu](https://github.com/mjpost/sacreBLEU/blob/fe51f492c045f952049f7caf815161c28fcd79fa/sacrebleu.py#L1271), that we could update at each batch, with limited memory footprint.

**Comment by vince62s** [comment]
@chan0park is your use case to compute Bleu on a set that is longer than 10000 lines ?
I feel it is not really an issue (change the shardsize) unless you really want to compute bleu on tenths of thousands (which does not really make sense IMO)

**Comment by chan0park** [comment]
@vince62s no mine was less than 10k lines, so there was no issue in my case. But that was just one suggestion in logic-wise. I agree on the part where people are not likely want to compute BLEU score on too many lines which will take lots of time and memory.
