### ISSUE TITLE
Pretrained embeddings

### ISSUE THREAD

**Issue by mahdavis** [OpenNMT/OpenNMT-py#1432]
I want to use pretrained embeddings but  running this ./tools/embeddings_to_torch.py -emb_file_both "glove_dir/glove.6B.100d.txt" \ -dict_file "data/data.vocab.pt" \ -output_file "data/embeddings" gives this error "embeddings_to_torch.py: error: the following arguments are required: -emb_file_enc, -emb_file_dec". What are -emb_file_enc, -emb_file_dec? there is nothing in Doc link :http://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-pretrained-embeddings-e-g-glove. I would appreciate for any suggestions, thanks,

**Comment by vince62s** [comment]
use the forum, you will find some tuto on this matter.
