### ISSUE TITLE
Distributed Training in OpenNMT-py Not working

### ISSUE THREAD

**Issue by unknownSK** [OpenNMT/OpenNMT-py#1439]
Hello there,
I am new to OpenNMT-py. I am trying Distributed training on multiple nodes but nothing is coming up.
I have used these codes:-

On Node 1:-
export CUDA_VISIBLE_DEVICES=0
python train.py -data data/demo -save_model demo-model 
-layers 6 -rnn_size 512 -word_vec_size 512 -transformer_ff 2048 -heads 8 
-encoder_type transformer -decoder_type transformer -position_encoding 
-train_steps 200000 -max_generator_batches 2 -dropout 0.1 
-batch_size 4096 -batch_type tokens -normalization tokens -accum_count 2 
-optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 2 
-max_grad_norm 0 -param_init 0 -param_init_glorot 
-label_smoothing 0.1 -valid_steps 10000 -save_checkpoint_steps 10000 -world_size 2 \
-gpu_ranks 0 -master_ip “10.138.0.10” -master_port 1056

On Node 2:-
export CUDA_VISIBLE_DEVICES=0
python train.py -data data/demo -save_model demo-model 
-layers 6 -rnn_size 512 -word_vec_size 512 -transformer_ff 2048 -heads 8 
-encoder_type transformer -decoder_type transformer -position_encoding 
-train_steps 200000 -max_generator_batches 2 -dropout 0.1 
-batch_size 4096 -batch_type tokens -normalization tokens -accum_count 2 
-optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 2 
-max_grad_norm 0 -param_init 0 -param_init_glorot 
-label_smoothing 0.1 -valid_steps 10000 -save_checkpoint_steps 10000 -world_size 2 
-gpu_ranks 0 -master_ip “10.138.0.10” -master_port 1056

When I run these commands on the nodes, nothing comes up and when I give a keyboard interrupt it shows like this:-
^CTraceback (most recent call last):
File “train.py”, line 109, in 
main(opt)
File “train.py”, line 36, in main
p.join()
File “/usr/lib/python3.5/multiprocessing/process.py”, line 121, in join
res = self._popen.wait(timeout)
File “/usr/lib/python3.5/multiprocessing/popen_fork.py”, line 51, in wait
return self.poll(os.WNOHANG if timeout == 0.0 else 0)
File “/usr/lib/python3.5/multiprocessing/popen_fork.py”, line 29, in poll
pid, sts = os.waitpid(self.pid, flag)

Please Help!

Thanks in advance.

**Comment by vince62s** [comment]
it's world_size 2 for both
but
gpu_ranks 0 for node 1
gpu_ranks 1 for node 2

**Comment by vince62s** [comment]
check here: https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md
