### ISSUE TITLE
configuration for dialogue modelling

### ISSUE THREAD

**Issue by Americanwallace0** [OpenNMT/OpenNMT-py#1441]
I use a 2M training set for dialogue modelling. with GRU I trained a model that generates pretty high-quality responses. but with Transfomer, it only generates meaningless responses like "i 'm not sure , but i do n't know what you 're talking about ." , although beam search und nbest are set.
Could somebody give me suggestion about configuration for transformer, or other aspects?

**Comment by vince62s** [comment]
I suggest you use the Forum for this, but don't forget to post the full config you used for your task.
