### ISSUE TITLE
Multiple GPUs issue

### ISSUE THREAD

**Issue by vikrant97** [OpenNMT/OpenNMT-py#1442]
I want to use Multiple GPUs for my experiments. I have a machine with 8 GPUs.
I run one experiment on first two GPUs setting CUDA_VISIBLE_DEVICES=0,1 with world_size=2 and gpu_ranks=0 1 
It works correctly.
Now at the same time I also run an another experiment on the other two GPUs setting  CUDA_VISIBLE_DEVICES=2,3 with world_size=2 and gpu_ranks=0 1 
It doesn't work and shows an error saying "Address already in use".

Can anyone help me out in this situation? I want to run various experiments on multiple GPUs in my machine.
Is there any problem in the parameter world_size & gpu_ranks for the second experiment?

**Comment by noe** [comment]
May be related to https://github.com/OpenNMT/OpenNMT-py/issues/840

**Comment by francoishernandez** [comment]
Hi @vikrant97 ,
This is linked to the `torch.distributed` implementation (#962).
You need to have a different `-master_port` for each distributed process running on the same machine.

**Comment by vikrant97** [comment]
@noe Yes the issue is related, but I don't find any solution over there.
As I can see the available GPUs using nvidia-smi, they are free.
So is there something I am missing?

**Comment by vikrant97** [comment]
Hi @francoishernandez ,
I unable to find a solution to my problem referring to the issue (#962 ).
Can you please help me how do I set master port with an example? Say 2 experiments on a single machine with multiple gpus. It would help me a lot.
Thanks.

**Comment by francoishernandez** [comment]
The default `master_port` is 10000 ([here](https://github.com/OpenNMT/OpenNMT-py/blob/8ff007107bbe9056820982509dce09c99d547435/onmt/opts.py#L344)).
So, just append `-master_port XXXX` to your `train.py` arguments, with XXXX being any port that is not already used on your machine.

**Comment by vikrant97** [comment]
@francoishernandez Thanks a lot. It worked.
I would suggest that there should be a proper documentation about multiple GPU usage in OpenNMT-py.

**Comment by vince62s** [comment]
you are very welcome to update this page http://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-the-transformer-model-do-you-support-multi-gpu
by posting a PR
on this file: 
https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md
