### ISSUE TITLE
All beam blocked by ngram repeat

### ISSUE THREAD

**Issue by fdzzy** [OpenNMT/OpenNMT-py#1445]
In some rare cases, all beam candidates for an input would be blocked by ngram repeat, resulting in all beam setting to -10e20, then torch.topk would just randomly choose a word.

Could it be possible to change this:
https://github.com/OpenNMT/OpenNMT-py/blob/7f1fc81da864c465862f23e048802107ada714a8/onmt/translate/decode_strategy.py#L119
to:
`log_probs[path_idx] += -1e5`

So that the repeated ngrams are given lower prob while the order of log_probs is kept. So once all candidates are blocked, the one with highest probability is still chosen. Not sure if -1e5 is small enough, though. For my case, log_probs seems to be larger than -100 most of the time.

**Comment by vince62s** [comment]
@pltrdy @sebastianGehrmann any comment ?

**Comment by pltrdy** [comment]
In my understanding, this should only block one token in the vocabulary by assigning a `-10e20` score. Therefore, this token should not be a candidate, right? It should no longer be a candidate if it's score is penalized.

**Comment by fdzzy** [comment]
It seems to me that the all vocabulary within the beam has been set to -10e20 instead of just one token, correct?
https://github.com/OpenNMT/OpenNMT-py/blob/7f1fc81da864c465862f23e048802107ada714a8/onmt/translate/decode_strategy.py#L119

Probably change to only block the candidate token that results in ngram repeat?
