### ISSUE TITLE
Transformer as encoder, lstm as decoder

### ISSUE THREAD

**Issue by unbreading** [OpenNMT/OpenNMT-py#1446]
I wanna use OpenNMT to build a transformer encoder and lstm(or gru) decoder model, but I do not know how to config.
Could I simply feed SelfAttentionEncoder and AttentionalRNNDecoder to SequenceToSequence? I've tried many times but always got exception. 
How could I config correctly?  Or any paper / people already done it?

**Comment by vince62s** [comment]
we never took the time to implement it: see https://github.com/OpenNMT/OpenNMT-py/projects/4
if you want something plug and play, look at OpenNMT-TF it's already possible to mix things.

Otherwise feel free to PR. It should not be very complicated but takes time to test.
