### ISSUE TITLE
Unable to use GPU

### ISSUE THREAD

**Issue by rohanpandey** [OpenNMT/OpenNMT-py#1448]
I have installed CUDA on my machine and it is visible in the prompt. I am using OpenNMT for translation purposes using my GPU using the command python train.py -data data/demo -save_model demo-model -gpu_ranks 0 . It is throwing an error and I cannot seem to resolve it. Any help would be great. 
![image](https://user-images.githubusercontent.com/31413869/58379893-5ef75e00-7fc7-11e9-8db0-cb1987f8b0cc.png)

**Comment by vince62s** [comment]
Please post your full config:
CUDA version
Pytorch version
OpenNMT-py: make sure you're on Master.

**Comment by rohanpandey** [comment]
CUDA: 9.0
Pytorch Version : 1.1.0

**Comment by vince62s** [comment]
does nvidia-smi give you the right information ?
I think you need to make sure that CUDA examples run fine on your config first.

**Comment by rohanpandey** [comment]
It gives me this output. I had previously installed CUDA 10 and it didn't work for that as well.
![image](https://user-images.githubusercontent.com/31413869/58380101-80a61480-7fca-11e9-90f6-6256899aa962.png)

**Comment by rohanpandey** [comment]
I'm able to train the model on my CPU however when I try to use the GPU mode, it throws an error.

**Comment by rohanpandey** [comment]
@vince62s any ideas?

**Comment by vince62s** [comment]
I think first you need to make sure it does not come from your config, please use a minimal pytorch example where you load / init cuda to see what happens.

**Comment by rohanpandey** [comment]
I've already checked if CUDA is available and it says true. 
![image](https://user-images.githubusercontent.com/31413869/58413496-8c5f0d00-8096-11e9-9a41-3f1cdbc1c2da.png)
CUDA seems to be working fine.

**Comment by rohanpandey** [comment]
@vince62s However running commands using cuda does throw me an error. Unable to understand why 
![image](https://user-images.githubusercontent.com/31413869/58413882-7f8ee900-8097-11e9-8a2a-0f564d47ab7a.png)

**Comment by vince62s** [comment]
You need to get help from the pytorch forum.
