### ISSUE TITLE
Attention visualization for Image to Latex

### ISSUE THREAD

**Issue by unknownSK** [OpenNMT/OpenNMT-py#1451]
Hello,
I am new to OpenNMT-py.
I was wondering if there is a way to visualize the attention in Image to Latex conversion just like this.
![687474703a2f2f6c73746d2e736561732e686172766172642e6564752f6c617465782f6d61746865782e706e67](https://user-images.githubusercontent.com/37638352/58758242-0deee900-8536-11e9-84a5-262541c456d4.png)

Thanks in Advance for the help!

**Comment by vince62s** [comment]
closing this since you asked the question on the forum.
maybe @da03 has an idea.
