### ISSUE TITLE
Vocabulary size cannot be specified for word features

### ISSUE THREAD

**Issue by noe** [OpenNMT/OpenNMT-py#1452]
When using word features, it is useful to be able to limit the vocabulary size, especially when using lemmas as word features, as the number of different lemmas can be very large.

However, `preprocess.py` does not support providing a list of integers, unlike the [Lua version](http://opennmt.net/OpenNMT/data/word_features/).

~I understand that it should be possible to get the same effect by extracting the feature vocabulary externally (pruning the vocabulary by frequency) and then supplying the vocabulary to `preprocess.py` with the parameter `--features_vocabs_prefix`.~

I just realized that `--features_vocabs_prefix` is completely ignored. Therefore, I understand that there is no way to control the feature vocabulary size; is that correct?

**Comment by vince62s** [comment]
Hi @noe 
yes, this option was inserted in the opts.py file just to mimic the Lua version but it was never implemented.
Honestly, features are not on my priority list and @bpopeters seems to have taken some distance from the project at the moment.
If you feel comfortable to implement, PR are always welcome.

**Comment by eeric** [comment]
make OpenNMT project audio list and sentences text list, as following:
https://github.com/eeric/OpenNMT-py-make-tgt-train.txt/blob/master/openNMT_make_label.py

**Comment by noe** [comment]
Just for reference, issue https://github.com/OpenNMT/OpenNMT-py/issues/1534 (and associated PR https://github.com/OpenNMT/OpenNMT-py/pull/1564) is related to this, as it allows setting the embedding sizes. Nevertheless, it does not handle different vocabulary sizes.

**Comment by vince62s** [comment]
@vikrant97

**Comment by vikrant97** [comment]
@vince62s Can you point me out where does the Vocab pruning happens in the preprocessing script?
I remember earlier, there used to be function called makeVocabulary which contains that part.
Is it now shifted to using torchtext.vocab?  
Can you please some light on this?

**Comment by vince62s** [comment]
is this what you are looking for ?
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/inputters/inputter.py#L317
