### ISSUE TITLE
Add scalars like "hidden state" and "gradient" to the tensorboardX option. 

### ISSUE THREAD

**Issue by Rajashan** [OpenNMT/OpenNMT-py#1459]
Presently in OpenNMT-py, tensorboardX only logs scalars such as accuracy and learning rate. If I wanted to extract things like hidden state, gradient and so on to a tensorboardX writer, does anyone know where in the code to put this? And how would it be added to the options when training?

**Comment by vince62s** [comment]
Well you have to read the code if you want ot do such a thing. it's not just in one place, it all depends on the encoder / decoder choice.
I personally don't see the real use of this so, as usual, PR are Welcome !
