### ISSUE TITLE
Decoder processing one input at a time?

### ISSUE THREAD

**Issue by pltrdy** [OpenNMT/OpenNMT-py#146]
Hi,

I'm currently working on a different decoder. So I'm constantly looking at existing code as inspiration/confirmation.

It turns out I'm not really understanding the decoding process (`.forward`) especially [Models.py l.301](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L301), written by @srush .

There is something like:
```
            # Standard RNN decoder.
            for i, emb_t in enumerate(emb.split(1)):
```
which will, to my mind, iterate over `batch_size * tgt_length` elements `emb_t` that are each target words embedding. Right?

Then, does this process one word at a time? (thus not working with batch?)

In fact I don't get why we split, I would have expected to word with some kind of `1 x batch_size x emb_size` tensors, iterating over `tgt_length`

Could you elaborate or tell me what's wrong in my understanding?

**Comment by wintor12** [comment]
I think your understanding is correct, emb_t has tensor size: 1 x batch_size x emb_size
The process is working with batch. enumerate(emb.split(1)) iterates over tgt_length elements, not batch_size * tgt_length elements. Please check the split function, the input 1 actually means the split size is 1, not the dim is 1

**Comment by sebastianGehrmann** [comment]
@pltrdy Does that answer solve your question?

**Comment by jerryitp** [comment]
I guess this page will answer your question. 
See the graph below: 
"Attention Model"
Different models are available from Luong (2015) "Global Attention Model"

The integrated RNN in the decoder is used as in encoder. RNN is computed iteratively in the backend c code (not the python code).  Under this case, the attention can only be put into between the last decoding layer and the output (different from the general case that attention locates between encoder and decoder).

In the input feed RNN decoder, the computation is iteratively performed as you expected.

**Comment by jerryitp** [comment]
http://opennmt.net/OpenNMT/training/models/
