### ISSUE TITLE
Translation error with a single gpu

### ISSUE THREAD

**Issue by vikrant97** [OpenNMT/OpenNMT-py#1473]
I am trying to translate a single file with 1000 sentences on a single GPU but its throws the following error:
RuntimeError: CUDA out of memory. Tried to allocate 8.76 GiB (GPU 0; 11.91 GiB total capacity; 10.59 GiB already allocated; 505.06 MiB free; 234.02 MiB cached)

I am using the below mentioned command:
python translate.py -model models/baseline_step_150000.pt -src test.en -output test.en.pred -gpu 0

I have already exported the CUDA_VISIBLE_DEVICES=7 and while running the code it do use the GPU 7 but end up eating the entire memory.

Please help me out to solve this issue.

**Comment by vince62s** [comment]
set a lower than default batch_size

**Comment by vikrant97** [comment]
@vince62s I set a batch size of 10 and it works. Now I try to translate a single file of 4M sentences with a batch_size of 10, then it throws some errors like:
File "/home/t-vigoya/intern_project/OpenNMT-py/onmt/modules/embeddings.py", line 50, in forward
    emb = emb + self.pe[:emb.size(0)]
RuntimeError: The size of tensor a (7901) must match the size of tensor b (5000) at non-singleton dimension 0

Can you please specify some details to translate large files on a GPU? Which parameters are required?
Thanks.
