### ISSUE TITLE
Three-way weight tying on Transformer

### ISSUE THREAD

**Issue by alphadl** [OpenNMT/OpenNMT-py#1478]
As mentioned in the paper [Weight Tying](https://arxiv.org/pdf/1608.05859.pdf), weight tying seems a useful trick that could reduce the parameter size and improve the model inference quality. Is there anyone who tried this trick in Opennmt-py?

**Comment by alphadl** [comment]
i.e., Using the option during training ```--share_decoder_embeddings ----share_embeddings```

**Comment by vince62s** [comment]
please don't ask the same question on both repo. Use the forum for this, thanks.
