### ISSUE TITLE
Adding self-made parameter to preprocess.py

### ISSUE THREAD

**Issue by kreeteeekah** [OpenNMT/OpenNMT-py#1480]
I want to tokenize my data by a tokenizer of my choice. For that i tried adding a parameter to for tokenizer in opts.py file. But it does not work.
 `token=opt.token_delim`
`# mix this with partial`
`def _feature_tokenize(
        string, layer=0, tok_delim=token, feat_delim=None, truncate=None):`
code in text_dataset file.

` #change for tokenizer of choice`         
   ` group.add(--token_delim, -token_delim, default=[None],
              help="Set the tokenizer")`
code added in opts.py file for tokenizer

It generates error: opts has no module named token_delim

**Comment by rishibommasani** [comment]
I am not sure why you need to log the tokenizer in the opts.py file/deal with that. I would just preprocess separately; i.e as is done here: http://opennmt.net/OpenNMT-py/extended.html using the Moses tokenizer.
