### ISSUE TITLE
re-training/train out model

### ISSUE THREAD

**Issue by vtrokhymenko** [OpenNMT/OpenNMT-py#1483]
hi

unfortunately, i didn't find how i cant re-training/train out model.
or i missed this information if u have this feature

**Comment by vince62s** [comment]
are you looking for this: https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/opts.py#L372

**Comment by vtrokhymenko** [comment]
i think that this is it

and what about data? i add only new raws to files at path data?

**Comment by vince62s** [comment]
not sure waht you are trying to accomplish.
Maybe browse the forum to check if some people havenot raised the same thing.
