### ISSUE TITLE
UserWarning when trying to train a summarization model

### ISSUE THREAD

**Issue by adabghi** [OpenNMT/OpenNMT-py#1486]
I am trying to train a summarazition model (using the transformer) with the CNN/DM and gigaword data sets. No problem with the pre-processing. However, when launching the training, I have a UserWarning, which probably should not interrupt the training, but surprisingly it did !

This is what I got :

`[2019-07-01 15:33:07,805 INFO] encoder: 38212608
[2019-07-01 15:33:07,805 INFO] decoder: 42469717
[2019-07-01 15:33:07,805 INFO] * number of parameters: 80682325
[2019-07-01 15:33:07,809 INFO] Starting training on GPU: [0, 1]
[2019-07-01 15:33:07,809 INFO] Start training loop and validate every 10000 steps...
[2019-07-01 15:33:36,440 INFO] number of examples: 99886
some_directories/.local/lib/python3.7/site-packages/torchtext/data/field.py:359: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)
`

I tried to replace the `torch.tensor` with `arr.clone().detach()`, but I got another error : 

`AttributeError: 'list' object has no attribute 'clone'`

Any idea what the problem might be ?

**Comment by vince62s** [comment]
please post yuor command line.

**Comment by adabghi** [comment]
`python3 train.py -data data/cnndm/CNNDM -save_model models/cnndm -copy_attn -reuse_copy_attn -train_steps 100000 -report_every 1 -world_size 4 -gpu_ranks 0 1 2 3`

**Comment by adabghi** [comment]
It is no longer a userwarning problem, I think the problem emerges when I try to use GPUs for training because it works fine when running on CPU !

**Comment by vince62s** [comment]
make sure you install requirements properly. (eg torchtext with the master version)

**Comment by adabghi** [comment]
Still nothing ..
The strange thing is that the training begins on CPU but when I try to use GPUs, I have the following :

`[2019-07-03 12:14:33,458 INFO] encoder: 38212608
[2019-07-03 12:14:33,458 INFO] decoder: 42469717
[2019-07-03 12:14:33,458 INFO] * number of parameters: 80682325
[2019-07-03 12:14:33,461 INFO] Starting training on GPU: [0, 1, 2, 3]
[2019-07-03 12:14:33,461 INFO] Start training loop and validate every 10000 steps...
[2019-07-03 12:15:01,095 INFO] number of examples: 99886`

And nothing else ..

I even added the `-report_every 1` option to check and nothing.
I checked the usage of GPUs and it is 0%.

**Comment by vince62s** [comment]
you should try with one GPU only and on the demo set just to make sure everything is properly configured.

**Comment by vince62s** [comment]
see #1487 make sure you have pytorch 1.1

**Comment by adabghi** [comment]
![image](https://user-images.githubusercontent.com/47088354/60597907-1001cd00-9dac-11e9-8969-ba04a7aba27b.png)

It worked on a single gpu, thank you very much @vince62s ! Is there a possible explanation for this ?

**Comment by vince62s** [comment]
Are you saying it works on 1 GPU "only" ? did you try 2? 3 ? what worked ? demo or cnndm ?

**Comment by adabghi** [comment]
I'm saying I'm able to train the summarization model, on both data sets (CNN-DM and gigaword), but only using CPU or **only** one GPU. I tried with 2, 3 and 4 GPUs but it got stuck and there is no progress after printing : 
`[2019-07-04 10:40:00,726 INFO] number of examples: 100000`

Thank you @vince62s, I really appreciate your help !

**Comment by vince62s** [comment]
try to set -gpu_verbose_level 2 in the training command line

**Comment by JasonCopper** [comment]
I think there is a deadlock issue in summarization code, I have tried to train a model in multi-gpu setting. No progress made, no checkpoint saved.
My command line:
nohup python -u train.py -data data/google/title/processed/ -save_model model/google/v1 -layers 4 -rnn_size 512 -word_vec_size 512 -max_grad_norm 0 -optim adam -encoder_type transformer -decoder_type transformer -position_encoding -dropout 0\.2 -param_init 0 -warmup_steps 8000 -learning_rate 2 -decay_method noam -label_smoothing 0.1 -adam_beta2 0.998 -batch_size 4096 -batch_type tokens -max_generator_batches 2 -train_steps 400000 -accum_count 4 -share_embeddings -copy_attn -param_init_glorot -world_size 4 -gpu_ranks 0 1 2 3 -gpu_verbose_level 2 -report_every 100 > google.log

**Comment by vince62s** [comment]
There is no "summarization code", the only thing that varies between translation and summarization is the -copy_attn flag. You may try to see if this does the same thing without it.
Also try to set max_generator_batches 0
We use the code daily with the same settings.
post the log output here, and check nvidia-smi / top

**Comment by vince62s** [comment]
reopen if needed.

**Comment by Simons2017** [comment]
> ![image](https://user-images.githubusercontent.com/47088354/60597907-1001cd00-9dac-11e9-8969-ba04a7aba27b.png)
> 
> It worked on a single gpu, thank you very much @vince62s ! Is there a possible explanation for this ?

I meet the same problem with you even on a single gpu, would you like to post your command line here and give me some advice.
