### ISSUE TITLE
FileExistsError when creating model/ folder with multiple GPUs

### ISSUE THREAD

**Issue by memray** [OpenNMT/OpenNMT-py#1495]
Hi,

I often ran into the following error when starting a multi-gpu training. I think this is because multiple `train_single` processes are trying to create a model folder at the same time [here](https://github.com/OpenNMT/OpenNMT-py/blob/3499f92634f2fe85e3198dc442fcde3fb4537ab8/onmt/train_single.py#L18). Should we move this _check_save_model_path() logic to `train.py` instead of  `train_single.py`? A similar issue happens with _tensorboard_log_dir_ as well.

`Traceback (most recent call last):
  File "/export/home/OpenNMT-summary/train.py", line 147, in run
    single_main(opt, device_id, batch_queue, semaphore)
  File "/export/home/OpenNMT-summary/onmt/train_single.py", line 96, in main
    _check_save_model_path(opt)
  File "/export/home/OpenNMT-summary/onmt/train_single.py", line 23, in _check_save_model_path
    os.makedirs(model_dirname)
  File "/export/home/anaconda/envs/py37/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/export/share/exp_dir/models'
`

Thanks,
Rui

**Comment by vince62s** [comment]
I don't think thsi is the reason because only GPU 0 process should do this.
@pltrdy can you have a look ?  thanks

**Comment by francoishernandez** [comment]
@memray is this still happening? on master?
The trace seems to link to line 23 something that is currently line 22.

**Comment by memray** [comment]
I added another path check to avoid the problem. I still don't know what causes this. But I think it might be related to this issue where I turned on logging of other GPUs: https://github.com/OpenNMT/OpenNMT-py/issues/1476

**Comment by francoishernandez** [comment]
Ok so I reckon you're not on master and this is related to your specific codebase.
Re-open the issue if you reproduce on master.
