### ISSUE TITLE
with RTX 2080Ti, RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by VictorLi2017** [OpenNMT/OpenNMT-py#1497]
Basic info of my machine:
**Ubuntu 18.04
single RTX 2080Ti
CUDA Version 10.0.130
cudnn version 7.6.1
Python 3.6.5 |Anaconda
pytorch version 1.1.0
Driver Version: 410.48**

Following the official doc, I ran the demo training command:
`CUDA_VISIBLE_DEVICES=0 python train.py -data data/demo -save_model demo-model -world_size 1 -gpu_ranks 0`
but got the error:
`Traceback (most recent call last):
  File "train.py", line 200, in <module>
    main(opt)
  File "train.py", line 86, in main
    single_main(opt, 0)
  File "/data/work/OpenNMT-py/onmt/train_single.py", line 84, in main
    model = build_model(model_opt, opt, fields, checkpoint)
  File "/data/work/OpenNMT-py/onmt/model_builder.py", line 233, in build_model
    model = build_base_model(model_opt, fields, use_gpu(opt), checkpoint)
  File "/data/work/OpenNMT-py/onmt/model_builder.py", line 226, in build_base_model
    model.to(device)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 127, in _apply
    self.flatten_parameters()
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 123, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED`

I google for long time, and tried several different version of cudnn and python, but it always failed. I'm almost exhausted. Can somebody help me solve the problems? Thanks very much!

**Comment by vince62s** [comment]
Please post also:
Driver version
Pytorch version
are you on master on this repo ?

**Comment by VictorLi2017** [comment]
@vince62s Thank you. I update the info as you mentioned. I installed the OpenNMT follow the doc, that is:
`git clone https://github.com/OpenNMT/OpenNMT-py
 cd OpenNMT-py
pip install -r requirements.txt`

**Comment by vince62s** [comment]
unfortunately I doubt this is an OpenNMT issue.
I would suggest to unsintall and clean up any Pytorch / Cuda install and restart from scratch.

**Comment by PierreSp** [comment]
I had the same issue and could fix by installing the CUDA 10 version of pytorch from their [website](https://pytorch.org/get-started/locally/) as conda seems to install version 8 by default.

**Comment by VictorLi2017** [comment]
Hello, thanks for your advice. But I have installed the proper version of
pytorch following OpenNMT’s official instruction and still had the same
problem.

**Comment by VictorLi2017** [comment]
> unfortunately I doubt this is an OpenNMT issue.
> I would suggest to unsintall and clean up any Pytorch / Cuda install and restart from scratch.

@vince62s I tried your suggestions several times, I uninstalled the cuda driver, cuda toolkit, Anaconda, pytorch, and deleted the OpenNMT repo, and reinstall them one by one, and git clone OpenNMT, but it always failed as  RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED. I tried install pytorch before downloaded the OpenNMT repo, also tried installed pytorch by `pip install -r requirements.txt`, but never successful. I'm almost crazy.

**Comment by vince62s** [comment]
can you try without Anaconda ?
also did you try to run the Cuda toolkit examples ?

**Comment by VictorLi2017** [comment]
> can you try without Anaconda ?
> also did you try to run the Cuda toolkit examples ?
@vince62s Actually I tried both cuda toolkit examples and cudnn examples every time I reinstalled cuda, all successfully ran, and I tried other codes, they can be suitable with GPU. I even tried OpenNMT in the new environment created by conda, failed again and again, with the same CUDNN error. So I totally have no idea about it, the last way may be reinstalling the Ubuntu system? :(

**Comment by eduamf** [comment]
Try the command: $ nvidia-smi

Probrably you wil receive something like this:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.72       Driver Version: 410.72       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:02:00.0  On |                  N/A |
| 24%   28C    P8    14W / 180W |    189MiB /  8118MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```
The board, driver version and CUDA version are ok?

**Comment by VictorLi2017** [comment]
@eduamf Thanks for your comments. I tried nvidia-smi many times every day, I think everything goes well. I reinstalled the cuda driversion and CUDA days ago, as shown in the following:
`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
| 28%   49C    P8    33W / 250W |    378MiB / 10986MiB |     11%      Default |
+-------------------------------+----------------------+----------------------+
`
Ubuntu 18.04
single RTX 2080Ti
CUDA Version 10.0.130
cudnn version 7.6.1
Python 3.6.5 |Anaconda
pytorch version 1.1.0
Driver Version: 410.78
Everything is OK, right?

**Comment by SahilDhull** [comment]
Hi @lihongzheng-nlp I am facing the same error!
I tried changing the CUDA and pytorch versions, even that is not working.
I'm using Jupyter Notebook and moving the model to CUDA causes this error.
However, running the same cell for the second time, I don't see any error!

Have you found any solution for the problem?
