### ISSUE TITLE
Train with cpu error?

### ISSUE THREAD

**Issue by trangtv57** [OpenNMT/OpenNMT-py#1498]
I just use command preprocess a sample data like:
`python preprocess.py -save_config demo.cf -train_src data/src-train.txt -train_tgt data/tgt-train.txt -shard_size 2000 -save_data data/demo`
and then i run command for generate data .pt :
`python preprocess.py -config demo.cf `
my data has name: demo.train_None.0.pt , demo.train_None.1.pt, demo.train_None.2.pt, demo.train_None.3.pt, demo.train_None.4.pt, demo.vocab.pt
and so when i run command for train model:
`python train.py -data data/demo -save_model model_dm/test`    
(with model_dm is folder i have created before)
this command make error: 
> Traceback (most recent call last):
>   File "train.py", line 199, in <module>
>     main(opt)
>   File "train.py", line 53, in main
>     train_iter = build_dataset_iter(shard_base, fields, opt)
>   File "/home/trangtv/Documents/project/OpenNMT-py/onmt/inputters/inputter.py", line 784, in build_dataset_iter
>     raise ValueError('Training data %s not found' % opt.data)
> ValueError: Training data data/demo not found

And when i check a code,  i see a difference between code component handle data_ids in file train_single.py (line 101) with component handle data_ids in file train (line 49). And code handle (when the data_ids not define) is has a problem. I don't sure its bug. Can you tell me what's my wrong in this case. 
Thank you

**Comment by francoishernandez** [comment]
Hi @trangtv57 
#1499 should fix this 'inconsistency' issue though there is another issue.
For whatever reason, dumping a config file and then reading it converts the default `-data_ids` which is `[None]` to `["None"]`, hence dumping the shards as "train_None" instead of the default "train".

**Comment by trangtv57** [comment]
yeah, I already get its fixed. 
Thank you
