### ISSUE TITLE
Alignment between source and target

### ISSUE THREAD

**Issue by atsb1372** [OpenNMT/OpenNMT-py#150]
Sorry if this is a noob question but can anyone tell me the benefit of using alignment in Dataset class? I know it shows an overlap between src and tgt but I don't understand [#Create a copying alignment](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Dataset.py#L117). Is there any paper that I can read regarding this? Thanks.

**Comment by wintor12** [comment]
The copying alignment is for copying mechanism ([one related paper](https://arxiv.org/pdf/1603.06393.pdf)): copying words from source sequence to target sequence based on copy attention. It needs alignment since the source dictionary and the target dictionary have different word indices.

**Comment by sebastianGehrmann** [comment]
Another recent paper using copy mechanism is [this one](https://arxiv.org/abs/1704.04368).
