### ISSUE TITLE
Vocab being shared in translation despite not using relevant options

### ISSUE THREAD

**Issue by raghavnauhria** [OpenNMT/OpenNMT-py#1506]
I'm using OpenNMT-py (PyTorch) for machine translation. I'm translating language A to B (for example) using a corpus of parallel sentences.
The vocabulary of both languages is distinct (i.e. there are no words from language A in the dataset of B and vice-versa).

I'm running:
1.  _preprocess.py_ without the options _--share_vocab_ and _--dynamic_dict_ 
2. _train.py_ without the options _--share_embeddings_ and _--share_decoder_embeddings_
3. _translate.py_ without the option _--share_vocab_

Despite this, the final translated files generated for B contain words from A as well.

**Comment by Damcy** [comment]
Maybe you used `--replace_unk` option in `translate.py`?
