### ISSUE TITLE
Loading lua trained models in translate.py 

### ISSUE THREAD

**Issue by ayushidalmia** [OpenNMT/OpenNMT-py#151]
how to load torch trained models in pytorch. I can use `load_lua` method but then I am not sure how to make it device agnostic. `load_lua` does not allow any similar parameters like `map_location=lambda storage, loc: storage`

**Comment by guillaumekln** [comment]
This is not supported unfortunately. You'll need to retrain your model using the PyTorch version.

**Comment by srush** [comment]
Sorry about this.
