### ISSUE TITLE
AttributeError: Can't get attribute '_split_tokenizer' 

### ISSUE THREAD

**Issue by hackerxiaobai** [OpenNMT/OpenNMT-py#1511]
```
import torch
import torch.nn as nn

import onmt
import onmt.inputters
import onmt.modules
import onmt.utils

vocab_fields = torch.load("data/data.vocab.pt")

src_text_field = vocab_fields["src"].base_field
print(src_text_field)
src_vocab = src_text_field.vocab

src_padding = src_vocab.stoi[src_text_field.pad_token]

tgt_text_field = vocab_fields['tgt'].base_field
tgt_vocab = tgt_text_field.vocab
tgt_padding = tgt_vocab.stoi[tgt_text_field.pad_token]
```

AttributeError: Can't get attribute '_split_tokenizer' on <module 'torchtext.data.utils' from '/opt/anaconda/anaconda3/envs/wangleiEnv/lib/python3.6/site-packages/torchtext/data/utils.py'>

**Comment by vince62s** [comment]
unless you give some explanation of what you re trying to do, I'll have to close this.

**Comment by ZhongRuiqi1997** [comment]
I encountered the same problem before and found the reason to be torchtext version - torchtext 0.3.1 does not have '_split_tokenizer'. So you will need to install the newest version (0.4.0) by following the instruction on https://github.com/OpenNMT/OpenNMT-py, with command pip install -r requirements.txt . (it seems that it cannot be installed by pip3 or conda).
