### ISSUE TITLE
limit vocab on summarization task.

### ISSUE THREAD

**Issue by zeeqy** [OpenNMT/OpenNMT-py#1515]
Is it possible to limit the summarization output to words only from related input document?

For example, I have data like
(document1, summary1)
(document2, summary2)

Now I noticed that my model pick words from document2 to generate summary1. And those words do not even exist in document1. How can I config my model only pick words from document1 to summarize document1?

(Or maybe it is a training issue that the model didn't converge?)

**Comment by vince62s** [comment]
no you can't do this. You'll to train more or get more data.

**Comment by zeeqy** [comment]
Thanks. you are right. Confirmed after checking the training accuracy. Model needs more data.
