### ISSUE TITLE
Best way to performing batching?

### ISSUE THREAD

**Issue by mrpega** [OpenNMT/OpenNMT-py#1520]
I couldn't find anything in the documentation. What's the best way to do batching when the input text is already on memory (from another model outputs). The easiest but probably slow way is to write it to text and then re-read it again like the translator.py approach.

Is there anywhere in the docs that talks about data input and batching?

Thanks!

**Comment by francoishernandez** [comment]
Hi @mrpega
Document might be lacking a bit here but about everything is in `onmt.inputters.inputter`.
It is heavily based on torchtext structures like `torchtext.data.Batch`.

**Comment by vince62s** [comment]
It is not ery easy but achievable.
look here https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/trainer.py#L193
this is the trainer and you will see a train_iter parameter.
you need to track down how it is built and use inputter / torchtext.
you may be able to short circuit all of this if you can rebuild the same structure.

**Comment by mrpega** [comment]
Hey @francoishernandez thanks for the help. document might be lacking but support here is definitely not lacking! ;)

@vince62s thanks the help again. will look in that area.
