### ISSUE TITLE
What exactly does dynamic_dict mean？

### ISSUE THREAD

**Issue by 5118Python** [OpenNMT/OpenNMT-py#1523]
What exactly does dynamic_dict mean

**Comment by pltrdy** [comment]
Long story short, it's an option to make extra fields during preprocessing that are necessary for the copy mecanism (i.e. `-copy_attn`).

You need `dynamic_dict` if, and only if, you use `-copy_attn` during training.

**Comment by 520jefferson** [comment]
> Long story short, it's an option to make extra fields during preprocessing that are necessary for the copy mecanism (i.e. `-copy_attn`).
> 
> You need `dynamic_dict` if, and only if, you use `-copy_attn` during training.

if  i use the shared_vocab in preprocess.py, then is the -dynamic_dict still a must option?

**Comment by pltrdy** [comment]
(sorry for late reply) 
> > Long story short, it's an option to make extra fields during preprocessing that are necessary for the copy mecanism (i.e. `-copy_attn`).
> > You need `dynamic_dict` if, and only if, you use `-copy_attn` during training.
> 
> if i use the shared_vocab in preprocess.py, then is the -dynamic_dict still a must option?

Yes it is. I mean, in some case one might want to only use `shared_vocab` (without `dynamic_dict`) for example for translation. If you need both, set both.
