### ISSUE TITLE
Gold score for perfect match should be 0

### ISSUE THREAD

**Issue by catskillsresearch** [OpenNMT/OpenNMT-py#1529]
When the output exactly matches the target output, shouldn't the GOLD SCORE be 0?  For example:

SENT 1748: None
PRED 1748: <hes> <space> <no-speech> <space> ښ ه
PRED SCORE: -0.7886
GOLD 1748: <hes> <space> <no-speech> <space> ښ ه
GOLD SCORE: -0.7886

**Comment by guillaumekln** [comment]
No, GOLD SCORE is the log likelihood of the true target. It is 0 when the model is absolutely sure about its prediction which is almost never the case.

In your example, we should just expect that PRED SCORE == GOLD SCORE.
