### ISSUE TITLE
after setup.py install, translate.py cannot use -report_rouge and -report_bleu

### ISSUE THREAD

**Issue by lan2720** [OpenNMT/OpenNMT-py#1530]
the error is like 
```
python: can't open file '.../lib/python3.7/site-packages/OpenNMT_py-0.9.1-py3.7.egg/onmt/translate/tools/test_rouge.py': [Errno 2] No such file or directory
```
Maybe the error is caused by setup.py, where didn't have `tools` in packages. But if I modified the setup.py, it still cannot work.

**Comment by vince62s** [comment]
what command line did you use?

**Comment by lan2720** [comment]
python translate.py -config [config_file]

**Comment by vince62s** [comment]
this not helping if you don't post your config ....

**Comment by lan2720** [comment]
gpu: 0
batch_size: 20
beam_size: 10

src: src.test
tgt: tgt.test

dynamic_dict: 'true'
share_vocab: 'true'

report_bleu: 'true'
report_rouge: 'true'

min_length: 5
max_length: 50
stepwise_penalty: 'true'
length_penalty: wu
coverage_penalty: summary
alpha: 0.9
beta: 5
block_ngram_repeat: 2
replace_unk: 'false'
verbose: 'true'

**Comment by lan2720** [comment]
@vince62s this is the config file. Thank you.

**Comment by francoishernandez** [comment]
I think this codepath is broken. The command is looking for `onmt/translate/tools/test_rouge.py` which does not exist. The proper path is `tools/test_rouge.py`.
Path is retrieved [here](https://github.com/OpenNMT/OpenNMT-py/blob/b7c2c809544a3e869589f7575d1a0a7fcc35d081/onmt/translate/translator.py#L839).
@vince62s @pltrdy not sure when this changed.

**Comment by vince62s** [comment]
right, longtime ago....
@nikhilweee fixed belu here https://github.com/OpenNMT/OpenNMT-py/commit/8bae2f95f5d6da9e770d85b75d74e2343db5ea29
but rouge was not fixed.

**Comment by lan2720** [comment]
@vince62s @francoishernandez [Here](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translator.py#L391) the input of _report_bleu or _report_rouge should be tgt file path. But now tgt is a generator `tgt_shard`. How to fix this?

**Comment by vince62s** [comment]
look at the code here https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translator.py#L839
that needs to be changed by the similar found here:
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translator.py#L824

ok?
if it works then, you can submit a PR

**Comment by francoishernandez** [comment]
I think the issue he's mentioning is the same as #1429. @lan2720 there is a patch proposed there. Not extra clean but it should do the trick if you want a quick fix.

**Comment by vince62s** [comment]
oh right I overlooked. so same question, are you really scoring a set that is longer than 10k sentences?

**Comment by lan2720** [comment]
@francoishernandez @vince62s  Yes I have fixed it in another way which is different from #1429 . Check [here](https://github.com/lan2720/OpenNMT-py-BDA/commit/16f3f2b59996ec5095ae2218589f32c99bf7d13b). If you think it is ok, I will submit a PR.

**Comment by lan2720** [comment]
@vince62s No, it is less than 10k, so it will not be split.
