### ISSUE TITLE
[Feature Request]skip unk when beam search

### ISSUE THREAD

**Issue by lan2720** [OpenNMT/OpenNMT-py#1531]
Hi, could you add an arg like `skip_unk` (which is bool) when initializing BeamSearch object. So its advance() function can skip unk in each step of decoding. This method was used in [DSTC6](https://github.com/dialogtekgeek/DSTC6-End-to-End-Conversation-Modeling/blob/master/ChatbotBaseline/tools/seq2seq_model.py#L96).

**Comment by vince62s** [comment]
PR welcome.
