### ISSUE TITLE
[Help Wanted] Training the german model with keywords and sentences

### ISSUE THREAD

**Issue by prabalbansal** [OpenNMT/OpenNMT-py#1532]
Hi , I try to train a parallel german dataset having sentence keywords and complete sentence and predict the complete sentence using keywords. Model is not predicting as expected. Could you suggest some specific parameters while training ?

**Comment by francoishernandez** [comment]
Hi @prabalbansal,
You might want to take this to the [forum](http://forum.opennmt.net/), which is more suited to such research related discussions. Also, to maximize useful answers, you might add some details about your task: corpus size, exemples, context, what you've already tried, etc.
