### ISSUE TITLE
Predicted result contain only one word for grammar error correction task.

### ISSUE THREAD

**Issue by MichaelZhouwang** [OpenNMT/OpenNMT-py#1536]
Hi, I have trained a grammar error correction model with transformer model with copy and coverage attention. Training seems ok by when translating it results in generating only the first word in the input sentence. I am confused and wonder if there may be some mistake in my decoding or training setting. Thanks!

**Comment by vince62s** [comment]
raise this on the forum,but give much more information otherwise nobody will be able to help you.
