### ISSUE TITLE
Error while running the server.py

### ISSUE THREAD

**Issue by daviewan** [OpenNMT/OpenNMT-py#1542]
@pltrdy 
 python server.py --ip $IP --port $PORT --url_root $URL_ROOT --config $CONFIG
Traceback (most recent call last):
  File "server.py", line 4, in <module>
    from flask import Flask, jsonify, request
ImportError: No module named flask

**Comment by francoishernandez** [comment]
You need to install the proper dependencies.
e.g. `pip install flask`

**Comment by daviewan** [comment]
> You need to install the proper dependencies.
> e.g. `pip install flask`

I have flask installed:
flask --version
Python 3.6.7
Flask 1.1.1
Werkzeug 0.15.5

**Comment by daviewan** [comment]
Error: No module named flask is now solved.

Now i get the error:

python server.py --ip $IP --port $PORT --url_root $URL_ROOT --config $CONFIG
Traceback (most recent call last):
  File "server.py", line 129, in <module>
    debug=args.debug)
  File "server.py", line 24, in start
    translation_server.start(config_file)
  File "/home/ng/open/OpenNMT-py-master/onmt/translate/translation_server.py", line 80, in start
    with open(self.config_file) as f:
IOError: [Errno 2] No such file or directory: './available_models/conf.json'

**Comment by daviewan** [comment]
This is my conf.json file located in OpenNMT-py-master/available_models:
{
    "models_root": "./available_models",
    "models": [
        {
            "id": 100,
            "model": "model_0.pt",
            "timeout": 600,
            "on_timeout": "to_cpu",
            "load": true,
            "opt": {
                "gpu": 0,
                "beam_size": 5
            },
            "tokenizer": {
                "type": "sentencepiece",
                "model": "wmtenfr.model"
            }
        },{
            "model": "model_0.light.pt",
            "timeout": -1,
            "on_timeout": "unload",
            "model_root": "../other_models",
            "opt": {
                "batch_size": 1,
                "beam_size": 10
            }
        }
    ]
}

**Comment by vince62s** [comment]
closing, this is all on the forum tutos.
