### ISSUE TITLE
using glove with transformer

### ISSUE THREAD

**Issue by rajarsheem** [OpenNMT/OpenNMT-py#1548]
I try to [add glove embeddings](http://opennmt.net/OpenNMT-py/FAQ.html?highlight=glove) to the transformer model.

```
python -u train.py  \
        -data $DATA_DIR/preprocessed \
        -save_model $DATA_DIR/saves/model \
        -layers 6 \
        -rnn_size 512 \
        -transformer_ff 2048 \
        -heads 8 \
        -encoder_type transformer \
        -decoder_type transformer \
        -position_encoding \
        -train_steps 10000 \
        -max_generator_batches 2 \
        -dropout 0.1 \
        -batch_size 6144 \
        -batch_type tokens \
        -accum_count 2 \
        -optim adam \
        -adam_beta2 0.998 \
        -decay_method noam \
        -warmup_steps 8000 \
        -learning_rate 2.0 \
        -normalization tokens \
        -max_grad_norm 0.0 \
        -param_init 0.0 \
        -param_init_glorot \
        -label_smoothing 0.1 \
        -valid_steps 2000 \
        -save_checkpoint_steps 2000 \
        -world_size 5 \
        -share_embeddings \
        -gpu_ranks 0 1 2 3 4 \
        -word_vec_size 100 \
        -pre_word_vecs_enc $DATA_DIR/embeddings.enc.pt \
        -pre_word_vecs_dec $DATA_DIR/embeddings.dec.pt
```

Since the embedding size is now 100 and the layer_norm excepts the input to be of size ```d_model``` which is 512, I get the following error. 

```
RuntimeError: Given normalized_shape=[512], expected input with shape [, 512], but got input of size[99, 39, 100].
```

Even though I have a workaround by adding a projection layer between embedding and layer norm which projects the embedding to ```d_model```, I would still want to know if there was something that I could have done in the first place.

This issue is very similar to http://forum.opennmt.net/t/error-in-training-using-embeddings/2675

**Comment by francoishernandez** [comment]
In the [Transformer](https://arxiv.org/abs/1706.03762) architecture embeddings are supposed to have the same dimension as the model.
You may try to add a projection layer but I'm not sure how that would behave. Also, you may want to have a look at #1477 .

**Comment by rajarsheem** [comment]
That's exactly what I did, worked like a charm. Should it be a PR?

**Comment by vince62s** [comment]
If you show some results were there is an improvement in pre-training, yes why not.
