### ISSUE TITLE
what is the requirement for  the input image size?

### ISSUE THREAD

**Issue by HongChow** [OpenNMT/OpenNMT-py#1549]
image2latex:  some error arise when the image set to an arbitrary  size (eg. (38,386,3)) 
the error :
RuntimeError: Given groups=1, weight of size 64 3 3 3, expected input[1, 4, 38, 363] to have 3 channels, but got 1 channels instead

**Comment by HongChow** [comment]
> image2latex: some error arise when the image set to an arbitrary size (eg. (38,386,3))
> the error :
> RuntimeError: Given groups=1, weight of size 64 3 3 3, expected input[1, 4, 38, 363] to have 3 channels, but got 4 channels instead

it seems not the problem of image size.
but: 
the dataset image shows:ex_dict['src'].shape
torch.Size([3, 64, 128])
and mine:
torch.size([1,....])
when i use opencv to read the image , it seems no problem with its channel.
I am so puzzled...

**Comment by HongChow** [comment]
> image2latex: some error arise when the image set to an arbitrary size (eg. (38,386,3))
> the error :
> RuntimeError: Given groups=1, weight of size 64 3 3 3, expected input[1, 4, 38, 363] to have 3 channels, but got 1 channels instead
I find a similar problem on #1121 
and try to add :
(1) "-image_channel_size 1 " and (2) "-image_channel_size 3"
at the end of the translate.py command line
(1) outputs: expected input[1, 1, 97, 500] to have 3 channels, but got 1 channels instead
(2) outputs: expected input[1, 4, 97, 500] to have 3 channels, but got 4 channels instead
I am still not know why ....
Would someone please do me a favor?

**Comment by HongChow** [comment]
I find a similar problem on #1121
and try to add :
(1) "-image_channel_size 1 " and (2) "-image_channel_size 3"
at the end of the translate.py command line
(1) outputs: expected input[1, 1, 97, 500] to have 3 channels, but got 1 channels instead
(2) outputs: expected input[1, 4, 97, 500] to have 3 channels, but got 4 channels instead
I am still not know why ....
Would someone please do me a favor?

**Comment by vince62s** [comment]
@da03

**Comment by wnma3mz** [comment]
@HongChow Maybe you should preprocess the input image, such as converting a four-channel image into a three-channel image.

**Comment by HongChow** [comment]
> @HongChow Maybe you should preprocess the input image, such as converting a four-channel image into a three-channel image.

Thanks, sorry for the late reply

**Comment by HongChow** [comment]
> @HongChow Maybe you should preprocess the input image, such as converting a four-channel image into a three-channel image.

Thanks and sorry for the late reply

**Comment by dishan14** [comment]
> > @HongChow Maybe you should preprocess the input image, such as converting a four-channel image into a three-channel image.
> 
> Thanks and sorry for the late reply

@HongChow hi,so did solved this problem ?, if did then please can you post the solution here
