### ISSUE TITLE
Incorrect scores when using translate.py

### ISSUE THREAD

**Issue by bpopeters** [OpenNMT/OpenNMT-py#155]
I've noticed that I get a lot of results that look like this when I run translate.py:

PRED 397: β i s̪ j o̞ n̪
PRED SCORE: -3.0023
GOLD 397: β i s̪ j o̞ n̪
GOLD SCORE: -0.4212

In cases where the prediction is exactly correct, the scores for gold and predicted are almost always different.

**Comment by srush** [comment]
Looking into this.

**Comment by srush** [comment]
This is now fixed and is included in the continuous integration.
