### ISSUE TITLE
OpenNMT-py/data/ dataset is trash? acc:  88.38; ppl:  1.52; xent: 0.42; -- translation is full random.

### ISSUE THREAD

**Issue by 4n70w4** [OpenNMT/OpenNMT-py#1561]
Hi! I decided to try OpenNMT-py.
I cloned the repository and run commands from the quickstart instructions.
As a result, the translation is terrible.
I spent a few days to get the trash. Thanks.

Is it possible to achieve a good translation on this data?
Why does the quick start guide give a useless result?
If it is so terrible, then why is it in the repository?
What are the next steps to take?

For example one of best checkpoints:

```
[2019-09-13 01:33:21,311 INFO] Step 29850/100000; acc:  86.50; ppl:  1.63; xent: 0.49; lr: 1.00000; 7946/7860 tok/s;   5277 sec
[2019-09-13 01:33:29,509 INFO] Step 29900/100000; acc:  87.38; ppl:  1.59; xent: 0.47; lr: 1.00000; 8487/8383 tok/s;   5285 sec
[2019-09-13 01:33:38,730 INFO] Step 29950/100000; acc:  86.01; ppl:  1.67; xent: 0.51; lr: 1.00000; 7822/7797 tok/s;   5294 sec
[2019-09-13 01:33:46,442 INFO] Loading dataset from data\demo.train.0.pt
[2019-09-13 01:33:46,511 INFO] number of examples: 10000
[2019-09-13 01:33:48,652 INFO] Step 30000/100000; acc:  85.90; ppl:  1.68; xent: 0.52; lr: 1.00000; 7420/7463 tok/s;   5304 sec
[2019-09-13 01:33:48,653 INFO] Loading dataset from data\demo.valid.0.pt
[2019-09-13 01:33:48,720 INFO] number of examples: 3000
[2019-09-13 01:33:59,396 INFO] Validation perplexity: 88401.7
[2019-09-13 01:33:59,396 INFO] Validation accuracy: 15.8091
[2019-09-13 01:33:59,569 INFO] Saving checkpoint demo-model_step_30000.pt
```

and after 30 000 steps acc and ppl get worse and worse.

For all checkpoints translate are random.

`python translate.py --model demo-model_step_30000.pt --src data\src-test.txt --output test.txt --verbose`

```
[2019-09-13 02:20:24,376 INFO] Translating shard 0.

SENT 1: ['Orlando', 'Bloom', 'and', 'Miranda', 'Kerr', 'still', 'love', 'each', 'other']
PRED 1: Finden Sie den M├╢rder im Bonusspiel !
PRED SCORE: -4.6939

SENT 2: ['Actors', 'Orlando', 'Bloom', 'and', 'Model', 'Miranda', 'Kerr', 'want', 'to', 'go', 'their', 'separate', 'ways', '.']
PRED 2: Der U-Bahnhof Knightsbridge bietet die Beta-Test-Phase der h├дuslichen Enterprise und die Konzentrierung der foreach .
PRED SCORE: -7.8273

SENT 3: ['However', ',', 'in', 'an', 'interview', ',', 'Bloom', 'has', 'said', 'that', 'he', 'and', 'Kerr', 'still', 'love', 'each', 'other', '.']
PRED 3: In einer Arbeit , wer in der Lage ist , dass er und in einem anderen Weg .
PRED SCORE: -9.3243

SENT 4: ['Miranda', 'Kerr', 'and', 'Orlando', 'Bloom', 'are', 'parents', 'to', 'two-year-old', 'Flynn', '.']
PRED 4: Scrollen Sie die Produktvariante im Bonusspiel und wechseln .
PRED SCORE: -6.5437

SENT 5: ['Actor', 'Orlando', 'Bloom', 'announced', 'his', 'separation', 'from', 'his', 'wife', ',', 'supermodel', 'Miranda', 'Kerr', '.']
PRED 5: Scrollen Sie die Maus auf kitten , dass 1994 in der Sprachausbildung ist .
PRED SCORE: -8.7006

SENT 6: ['In', 'an', 'interview', 'with', 'US', 'journalist', 'Katie', 'Couric', ',', 'which', 'is', 'to', 'be', 'broadcast', 'on', 'Friday', '(local', 'time),', 'Bloom', 'said', ',', '&quot;', 'sometimes', 'life', 'doesn', '&apos;t', 'go', 'exactly', 'as', 'we', 'plan', 'or', 'hope', 'for', '&quot;', '.']
PRED 6: In der Unternehmenslandschaft sehen sich Beutez├╝ge der Agenda eines Anrufs von einem Plan , in dem die Entwicklungsl├дnder stecken , ist ein wichtiger Sicherheitsaspekt , der nicht als , was wir ├╝ber 30% besch├дftigen k├╢nnen .
PRED SCORE: -19.1376
```

**Comment by 4n70w4** [comment]
@francoishernandez why did you close the issue?

**Comment by francoishernandez** [comment]
Because this is not an issue.
This dataset is not intended to give good translation performance.
> This is just a toy set to get started with the basic scripts and commands.

**Comment by 4n70w4** [comment]
In Quickstart step 2 the number of steps for training is not specified and the default is 100 000 steps. On a GPU this takes about 5 hours, and on a CPU it takes a week. The instruction is trolling and does not respect the time of users! So why for the Quickstart step 2 command, do not specify a step limit of 1000-10000? Further training this dataset is useless.

**Comment by francoishernandez** [comment]
Please read the Note at the end of the Quickstart.
You may also think about respecting the time of the maintainers and read a bit more about the task you're trying to achieve before trolling yourself.

**Comment by 4n70w4** [comment]
I doing the quickstart in order and saw this note only after I received a shitty translation that I spent a lot of time on.

This note is at the end of a quick start. In the very last paragraph. Need it be read from the end of quickstart? Since training is the longest step - I would like to see such things in the context of training step, and not at the end of the quickstart. As a result, my quickstart lasted for several days.

Have you heard about the userfriendly?

**Comment by francoishernandez** [comment]
Feel free to PR an updated quickstart.
