### ISSUE TITLE
'pretrainedmodels' not found in 'tools/vid_feature_extractor.py'

### ISSUE THREAD

**Issue by CaesarPan** [OpenNMT/OpenNMT-py#1562]
Hi, for the `tools/vid_feature_extractor.py` for video feature extraction a module `pretrainedmodels` it's importing cannot be found. Thanks.

**Comment by francoishernandez** [comment]
@flauted is this something that should have been added in #1409 ?

**Comment by flauted** [comment]
I actually think the import might be unused but:
https://github.com/Cadene/pretrained-models.pytorch
You can pip install pretrainedmodels

**Comment by CaesarPan** [comment]
thanks. it's actually used as `pretrainedmodels.resnet152` is used as feature extractor in your script.

**Comment by CaesarPan** [comment]
Hi @flauted, thanks for contributing to the captioning! I also raised a new issue regarding this, but I'm wondering what kind of input file (also file format) should I provide to `translate.py` if I wanna use it for beam search decoding for my customized video captioning model (the captioning module of which is a transformer)? Thanks!

**Comment by flauted** [comment]
I believe the full question is on #1565.

You can leave this open because pretrainedmodels should be listed in the requirements opt file. I'm short on time right now, so if you have free time it would be awesome if you could contribute a PR adding that line to the requirements file.

**Comment by CaesarPan** [comment]
Sure. added and PR submitted. I'm closing this issue. Thanks.
