### ISSUE TITLE
What input should I provide if I want to use the translator for a customized captioning model?

### ISSUE THREAD

**Issue by CaesarPan** [OpenNMT/OpenNMT-py#1565]
Hi there,

Thanks for providing this wonderful codebase. So I'm using a customized video captioning model (it's end-to-end trained together with the feature extractor so I cannot use the OpenNMT codebase for modeling). The captioning part of it is a transformer. Now if I'd like to use OpenNMT's translator for beam search decoding, what kind of file (like format etc) should I provide to `translate.py`? Thanks!

**Comment by flauted** [comment]
This isn't supported out of the box. You say you're training the system end-to-end, which has required modifications to what's provided. You'll have to make similar modifications for eval. I hope it works well and you contribute it!

**Comment by CaesarPan** [comment]
Thanks for your reply. So for training I'm not using OpenNMT, and now I just want to use it for beam search and to generate candidate captions which are then used to compute scores. So I'm not quite clear about what modifications should I make for eval. It'd be highly appreciated if you can provide some pointing / reference!

**Comment by flauted** [comment]
Oh okay I misunderstood. I can maybe put together a more detailed reply later, but to get you on your feet:

For the data input, you can follow the tutorial under ``docs/source/vid2text.rst`` and inspect the files. IIRC the input will need to be a folder of .npy feature vector sequences ``(* x feat_dim)``.

I think you'll need to take whatever model ckpt you have and split it in two. You'll have to figure out how to use your feature extractor to get to that directory of vector seqs. Then you'll need to make sure the seq2seq transformer part is saved out in the same format and ONMT ckpt would look like (again, tutorial should help here). And then with any luck it'll load in and work.

So:
* Split up your checkpoint into a feature extractor and a seq2seq part.
* Run your feature extractor to create feature vec seqs. This will take some coding probably.
* Use the translate script to do inference on the feature vector seqs with the seq2seq part of your checkpoint.
