### ISSUE TITLE
Applying subword regularization in training my NMT model?

### ISSUE THREAD

**Issue by minstar** [OpenNMT/OpenNMT-py#1567]
Hi, thank you for great library.

I'm currently trying to apply subword regularization method to training my NMT model. I noticed that texts get tokenized before building dictionary and then gets trained with fixed segmented outputs. However, I would like to sample from raw text into segmented outputs every epoch(applying this method would improve 1~2 bleu score according to "subword regularization"). Any suggestion? I can use sentencepiece library to sample segmented candidates. But this sampling procedure must be done every epoch during training. 

Thank you.

**Comment by francoishernandez** [comment]
Hi,
There is [a similar discussion on the forum](http://forum.opennmt.net/t/how-to-train-nmt-model-with-subword-regularization-sampling-segmentation-every-epoch/3052).

**Comment by minstar** [comment]
Thank you!! @francoishernandez
