### ISSUE TITLE
Reproduced results vary much

### ISSUE THREAD

**Issue by haorannlp** [OpenNMT/OpenNMT-py#1572]
I tried to reproduce the results with transformer on your website: http://opennmt.net/Models-py/#translation
"newstest2014 = 26.89    newstest2017 = 28.09"
- preprocess
    I followed the instructions on http://opennmt.net/OpenNMT-py/quickstart.html
    python preprocess.py -train_src data/wmt_ende_sp/train.en -train_tgt data/wmt_ende_sp/train.de -valid_src data/wmt_ende_sp/valid.en -valid_tgt data/wmt_ende_sp/valid.de -save_data data/wmtende
- train 
     with the recommended transformer settings on http://opennmt.net/OpenNMT-py/FAQ.html 
- translate
      following the instructions on http://opennmt.net/OpenNMT-py/extended.html
       python translate.py -gpu 0 -model my_transformer_step_200000.pt -src data/wmt-ende-sp/test.en -tgt data/wmt-ende-sp/test.de -replace_unk -verbose -output test_pred
- evaluate
    perl tools/multi-bleu.perl data/wmt-ende-sp/test.de < test_pred

I evaluated transformer on "test.en""test.de" in "wmt-ende-sp" file, got 26.15 BLEU. Then I modified the source code of transformer, only on the attention layer. I run the transformer again with the same settings. Then I evaluated new transformer on "test.en""test.de"got roughly the same score. 
But when I tried to run my first transformer model, I got only 0.5 BLEU score.  The first transformer model was not overwritten. I also tried the "averaged-10-epoch.py" on "test.en""test.de", got 0.23 BLEU.
Why can't I reproduce the results with same model, same dataset?

It took me 3 days to train these models. So pls help me on this. Thanks.

**Comment by francoishernandez** [comment]
> Then I modified the source code of transformer, only on the attention layer. I run the transformer again with the same settings.

> But when I tried to run my first transformer model, I got only 0.5 BLEU score.

I think you're trying to infer with a model built with the 'original' architecture by running some code with your 'custom' architecture.

**Comment by haorannlp** [comment]
That's right...I realized this as soon as I finished this issue. haha.
