### ISSUE TITLE
Question about the Transformer

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [OpenNMT/OpenNMT-py#1578]
As we all know, the transformer architecture uses the ReLU for the feedforward layer.

I noticed that [same utterances issue](https://github.com/OpenNMT/OpenNMT-py/issues/1017) in this package. And I think this may caused by the ReLU activative function.

If ReLU returns all the zero results for the the next decoder or encoder multi-head attention block, the zero will propagate to the final prediction layer (softmax) which will create the same utterance based on the different contexts.

So I think if we can change the activation function ReLU to some other function such as tanh which will alleviate this issue.

**Comment by guillaumekln** [comment]
> If ReLU returns all the zero results for the the next decoder or encoder multi-head attention block, the zero will propagate to the final prediction layer (softmax)

This is not true for the OpenNMT-py implementation. The last ReLU layer is followed by a linear layer, a layer norm, and the final linear layer, all of which have a bias vector.

**Comment by gmftbyGMFTBY** [comment]
Thanks for your response, I will check my usage. Close it.
