### ISSUE TITLE
RuntimeError: sim_vml_cpu not implemented for 'Long'

### ISSUE THREAD

**Issue by hadiaskari1981** [OpenNMT/OpenNMT-py#1579]
By running translator.py, I got this error RuntimeError: sim_vml_cpu not implemented for 'Long', I tried to find some solutions, but I could not. Can you please give me some hints on how to solve the issue.
 The problem happens in computing the embeddings in /onmt/modules/Embedding.py line 16, in __init__ pe[:, 0::2] = torch.sim(pe[:, 0::2])
I am using Python 3.6 and ubuntu 16.04.
Thank you in advance.
Hadi

**Comment by viethoangtranduong** [comment]
@hadiaskari1981 How did you fix it? I faced the same problem. 
Thank you so much
