### ISSUE TITLE
What length does src_seq_length refer to for audio preprocessing?

### ISSUE THREAD

**Issue by khanh111** [OpenNMT/OpenNMT-py#1582]
The documentation says it is the "maximum source sequence length." For audio, does this refer to the frames? If preprocessing converts the source audio to 100Hz (for example), would that mean that the default `src_seq_length` of 50 would only use 0.5 seconds of data from each audio file?

This seems a bit unclear in the documentation, so I would appreciate any clarity.

**Comment by francoishernandez** [comment]
Hi,
Yes, `src_seq_length` will be your number of frames.
If you don't pass any additional opt when preprocessing, it means you're using the default ones: https://github.com/OpenNMT/OpenNMT-py/blob/7675770620fa1f34e8869d0918a260a3b7a2b8bb/onmt/opts.py#L298-L307

**Comment by fdalvi** [comment]
Hi,

Apologies for resurrecting a closed issue, but according to https://github.com/OpenNMT/OpenNMT-py/blob/d9f993ee4d0307bff170611bd573e0ec12ad48a1/onmt/bin/preprocess.py#L174-L178
it seems like the `src_seq_length` is only used when the data type is `text`. If this is true, are all of the audio frames then taken into account regardless of the `src_seq_length`?
