### ISSUE TITLE
Where to modify the padding for the encoder decoder input in Transformer

### ISSUE THREAD

**Issue by haorannlp** [OpenNMT/OpenNMT-py#1583]
I’m working on a NMT task and try to make source and target language inputs to the encoder and decoder have the same length (usually they do not have the same length). Do anybody know where to modify the source code so that source and target language sentences can have the same length after padding?

**Comment by francoishernandez** [comment]
Conversation happening [on the forum](http://forum.opennmt.net/t/where-to-modify-the-padding-for-the-encoder-decoder-input-in-transformer/3075/2?u=francoishernandez).
