### ISSUE TITLE
Target side features 

### ISSUE THREAD

**Issue by XinnuoXu** [OpenNMT/OpenNMT-py#1587]
I know that the target side features haven't been implemented yet. 

Just a quick double check, if I feed the model target side features, based on the current code, during the training process, the model will take the combination of the feature embeddings and the word embeddings as the input, but these features will not be predicted by the network, right? I mean the loss is calculated only on the words.

**Comment by pltrdy** [comment]
That's correct.

**Comment by XinnuoXu** [comment]
That's great! Many thanks : )
