### ISSUE TITLE
Close to state of the art model

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [OpenNMT/OpenNMT-py#160]
Following the example in readme for WMT'16 yields very low BLEU score (6.93). Is it expected?

**Comment by guillaumekln** [comment]
No this is not expected. Which version are you using?

**Comment by dmitriy-serdyuk** [comment]
I'm using the master branch, commit 0eba7895c1fa6d9a6aa0bb0e3339e8d9415e63df. Pytorch version 0.1.12_2.

**Comment by dmitriy-serdyuk** [comment]
Sorry, my fault. The groundtruth wasn't in the lower case. Now it shows ~34 BLEU.
