### ISSUE TITLE
Alpha channel and grayscale in image-to-text with -image_channel_size=3

### ISSUE THREAD

**Issue by DimitriF** [OpenNMT/OpenNMT-py#1601]
For training image to text, the argument `-image_channel_size=3` imply that the images already have the good number of channel. However, some of my images are black and white and saved with only one channel or saved in RGB but with the alpha channel.
I could fix it with a change in `onmt/inputters/image_dataset.py` [here](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/inputters/image_dataset.py#L78):

from this:
```
            if self.channel_size == 1:
                img = transforms.ToTensor()(
                    Image.fromarray(cv2.imread(img_path, 0)))
            else:
                img = transforms.ToTensor()(Image.open(img_path))
```
to this:
```
            if self.channel_size == 1:
                img = transforms.ToTensor()(
                    Image.fromarray(cv2.imread(img_path, 0)))
            else:
                img = transforms.ToTensor()(
                    Image.fromarray(cv2.imread(img_path, 1)))
```
The flag in `cv2.imread` with value of 1 tell cv2 to convert to RGB no matter what the original image is.

Should I do a PR ?

**Comment by vince62s** [comment]
sure feel free to send a PR

**Comment by lamhoangtung** [comment]
Since every one kinda forget this issue and I have encountered some problem because of this myself. I have sent a PR for this. Hope you take a look @vince62s
