### ISSUE TITLE
MC Dropout at inference

### ISSUE THREAD

**Issue by ssp573** [OpenNMT/OpenNMT-py#1602]
Is there a way to use Monte Carlo dropouts at inference and do multiple passes for a given input sequence as given in https://arxiv.org/pdf/1709.01907.pdf ? If not, how do we add dropout to the model in the translation code?

**Comment by vince62s** [comment]
Since we use the pytorch nn.dropout maybe you can try this solution:
https://discuss.pytorch.org/t/dropout-at-test-time-in-densenet/6738
