### ISSUE TITLE
does the preprocessing command in the quickstart include BPE?

### ISSUE THREAD

**Issue by moyid** [OpenNMT/OpenNMT-py#1603]
Hi, I'm new to openNMT, and this question clearly reflects it -- in the README under quick start, we can preprocess tokenized data using the onmt_preprocess command. Does the preprocessing learn and apply BPE codes? If not, how can I incorporate it? 

Because after applying BPE the tokens are no longer separated by spaces, so it doesn't fit the spec of the input that preprocessing needs? 

Thank you!

**Comment by moyid** [comment]
Specifically, I'd like to run the transformers model, and I'd like to prepare my data with BPE. In the [FAQs here](http://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-the-transformer-model-do-you-support-multi-gpu), there is a question about how to use transformer model. The train script is given but I'm basically trying to understand how to prepare the data for training, if I'd like to use subword-nmt in my preprocessing.

**Comment by francoishernandez** [comment]
Hi,
You might want to read [this thread](http://forum.opennmt.net/t/using-sentencepiece-byte-pair-encoding-on-model/3027).

**Comment by moyid** [comment]
Thank you @francoishernandez ! This is exactly what I'm looking for.
