### ISSUE TITLE
Reflen, testlen, guess greatly differs on the same dataset (video captioning)

### ISSUE THREAD

**Issue by leobxpan** [OpenNMT/OpenNMT-py#1604]
Hi there,

My `reflen`, `testlen` and `guess` values for MSVD test split are very different from what you showed here (http://opennmt.net/OpenNMT-py/vid2text.html). My values for one epoch are like `'testlen': 4154, 'reflen': 4137, 'guess': [4154, 3484, 2814, 2144]`. They vary a bit from epoch to epoch but the variance is smaller than 100. Do you possible know the cause of this issue? Thanks!

**Comment by francoishernandez** [comment]
@flauted any insight on this?

**Comment by flauted** [comment]
I can look into it. Could you share the exact commands for preprocessing, training, testing, etc.?
