### ISSUE TITLE
Any successful experience on multi-node?

### ISSUE THREAD

**Issue by memray** [OpenNMT/OpenNMT-py#1606]
Hi,

I started a training job on two GCP nodes, each has 8 GPUs. The initialization takes very long (>20min) and I see the GPU memory usage keeps going up. But after it the program just hangs (1 hour already). I turned on the flag NCCL_DEBUG=INFO and the latest log is as follow:
```
sfr-pod-rmeng:437:785 [2] NCCL INFO Trees [0] 9->10->11/-1/-1
sfr-pod-rmeng:438:786 [3] NCCL INFO comm 0x7f6594002560 rank 11 nranks 16 cudaDev 3 nvmlDev 3 - Init COMPLETE
sfr-pod-rmeng:439:787 [4] NCCL INFO comm 0x7f5500002560 rank 12 nranks 16 cudaDev 4 nvmlDev 4 - Init COMPLETE
sfr-pod-rmeng:441:789 [6] NCCL INFO comm 0x7fed38002560 rank 14 nranks 16 cudaDev 6 nvmlDev 6 - Init COMPLETE
sfr-pod-rmeng:440:788 [5] NCCL INFO comm 0x7fba5c002560 rank 13 nranks 16 cudaDev 5 nvmlDev 5 - Init COMPLETE
sfr-pod-rmeng:436:784 [1] NCCL INFO comm 0x7f1a40002560 rank 9 nranks 16 cudaDev 1 nvmlDev 1 - Init COMPLETE
sfr-pod-rmeng:437:785 [2] NCCL INFO comm 0x7fc66c002560 rank 10 nranks 16 cudaDev 2 nvmlDev 2 - Init COMPLETE
sfr-pod-rmeng:435:783 [0] NCCL INFO Could not find real path of /sys/class/net/eth0/device
sfr-pod-rmeng:435:783 [0] NCCL INFO include/net.h:19 -> 2
sfr-pod-rmeng:435:783 [0] NCCL INFO Ring 00 : 0 -> 8 [receive] via NET/Socket/0
sfr-pod-rmeng:435:783 [0] NCCL INFO NET/Socket: Using 1 threads and 1 sockets per thread
sfr-pod-rmeng:435:783 [0] NCCL INFO Trees [0] 0->8->9/-1/-1
sfr-pod-rmeng:435:783 [0] NCCL INFO comm 0x7fa940002560 rank 8 nranks 16 cudaDev 0 nvmlDev 0 - Init COMPLETE
[2019-10-14 21:03:52,635 INFO] Loading dataset from data.train.5.pt
[2019-10-14 21:05:01,849 INFO] number of examples: 100000
```

Any insight into this?

Thanks,
Rui

**Comment by francoishernandez** [comment]
Hey,
Could you post your command line please?

**Comment by memray** [comment]
This is only the part about GPU setting. The others are just a normal transformer. The two nodes are connected for sure (`telnet 10.35.253.217 8888` works).
Does multi-node distributed training ever work on your end? If so please let me know how you set it up.
 
1st node (Master):
```
master_ip: 10.35.253.217
master_port: 8888
world_size: 16
gpu_ranks:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
```

2nd node:
```
master_ip: 10.35.253.217
master_port: 8888
world_size: 16
gpu_ranks:
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
```

**Comment by francoishernandez** [comment]
Hmmm.
It worked fine last time I checked (few weeks ago, two Ubuntu 18.04 nodes, 2/4 gpus, torch 1.1 or 1.2 not sure). I'll try and test it again on soon. Which version of pytorch are you using?
I'm not too used to these NCCL traces but this "NCCL INFO Could not find real path of /sys/class/net/eth0/device" looks strange. (Maybe have a look [here](https://github.com/horovod/horovod/issues/584)?)

**Comment by vince62s** [comment]
reopen if needed.
