### ISSUE TITLE
copy_att mode in translator._decode_and_generate might be wrong?

### ISSUE THREAD

**Issue by sx349995780** [OpenNMT/OpenNMT-py#1607]
I think there might be some bugs in translator._decode_and_generate's copy_att mode involving 'dimension transformation'.
onmt/translate/translator.py:
the line 596-598:
`scores = self.model.generator(dec_out.view(-1, dec_out.size(2)),
                                          attn.view(-1, attn.size(2)),
                                          src_map)`
the scores has the size of [tgt_len\*batch, vocab+extend] or [beam\*batch, vocab+extend]

the line 600-603:
`if batch_offset is None:
                scores = scores.view(batch.batch_size, -1, scores.size(-1))
            else:
                scores = scores.view(-1, self.beam_size, scores.size(-1))`
which should be:
scores = scores.view(-1, batch.batch_size, scores.size(-1)) and (self.beam_size, -1, scores.size(-1))

Assume the line 600-603 is right, the scores's size is [batch, tgt_len, vocab+extend]
the line 612:
`scores = scores.view(decoder_in.size(0), -1, scores.size(-1))`
[batch, tgt_len, vocab+extend] -> [tgt_len, batch, vocab+extend] 
or [batch, beam, vocab+extend] -> [beam, batch, vocab+extend]
is impossible

there might be many transpose missing. Thanks.

**Comment by pltrdy** [comment]
You're right, in that the code and the doc/comments does not fit. However, the code is right, the documentation is wrong.

In particular, `hidden` and `attn` comes in [CopyGenerator.forward()](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/copy_generator.py#L95) `tgt_len` first (i.e. dimensions are `[tlen*bsize, input_size]`) which is confirmed by transposition [at line 128](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/copy_generator.py#L128).

The `bmm` operation returns `batch_size` first.

**Comment by sx349995780** [comment]
The size of the `scores` returned by CopyGenerator is `[tgt*batch, vocab+extend]`.
It can be confirmed by [line 130 in onmt/modules/copy_generator.py](https://github.com/OpenNMT/OpenNMT-py/blob/2c4501cad86e7bc1ad11e21a06d23faec1be0d21/onmt/modules/copy_generator.py#L130)
(`bmm` returns `batch_size` first.`transpose` turns `tgt_len` first)

[line 600-603 in onmt/translate/translator.py](https://github.com/OpenNMT/OpenNMT-py/blob/2c4501cad86e7bc1ad11e21a06d23faec1be0d21/onmt/translate/translator.py#L600-L603)
transform `[tgt*batch, vocab+extend]` to `[batch, tgt, vocab+extend]` without transpose.
I think the code is also wrong. 
Thanks!

**Comment by pltrdy** [comment]
I think it works just because here, `tgt_len=1`, therefore `[tgt*batch] = [tgt x batch].view(-1) = [batch x tgt].view(-1)`

**Comment by sx349995780** [comment]
at least when function [_score_target](https://github.com/OpenNMT/OpenNMT-py/blob/2c4501cad86e7bc1ad11e21a06d23faec1be0d21/onmt/translate/translator.py#L820) call the  the _decode_and_generate, `tgt_len != 1`

**Comment by pltrdy** [comment]
True.

I tried some fixes, --following your suggestions -- that resulted in crashes in the code. Did you tried stuff?

**Comment by sx349995780** [comment]
Sorry. I haven't modified the code.
I just thought I'd better confirm it on issue first...

**Comment by pltrdy** [comment]
I do understand your point, it definitely make sense. We still need to investigate it experimentally now.

**Comment by sx349995780** [comment]
Thanks！
