### ISSUE TITLE
Vocab Size

### ISSUE THREAD

**Issue by aastha19** [OpenNMT/OpenNMT-py#1612]
I wanted to ask if there is a limit to the vocab size.
I have a training data of 25 million and the target and source vocab generated only have a size of around 50000. How is it possible?

Is there something I can do to change it or check it?

**Comment by Zenglinxiao** [comment]
There is an option called --src_vocab_size / --tgt_vocab_size control the max_size of resulting vocabulary which is default to 50000. Try to increase this to a large number.
