### ISSUE TITLE
Why doesn't the translation server support n_best > 1?

### ISSUE THREAD

**Issue by johnjago** [OpenNMT/OpenNMT-py#1614]
The translation server only supports 1 for the value of `n_best`. (see https://github.com/OpenNMT/OpenNMT-py/commit/acb4e0dbca6f997ea406f667bcb0f25f9245f15c)

n_best works as expected using `translate.py`, so I was looking for some additional insight as to why the server does not support this option.

**Comment by pltrdy** [comment]
It's not a hard constraint, i.e. we could make it available without a lot of work. Just that currently, using `n_best` could lead to unwanted sides effects (see [line 443](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translation_server.py#L443))

**Comment by vince62s** [comment]
Also this would be a breaking chage in the JSON response I guess. To handle carefully because of some production systems in place.

**Comment by pltrdy** [comment]
@vince62s I think we can keep the same format and just return a longer "flattened" list, i.e. for a query with `k` inputs, return `k x n_best` translations, instead of just `k`.

**Comment by autodataming** [comment]
if n_best >1, what are sides effects?  I prepare to comment these codes
```py
  if self.opt.n_best > 1:
            raise ValueError("Values of n_best > 1 are not supported")
```

**Comment by pltrdy** [comment]
@autodataming We keep tracks of whitespaces in lines https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translation_server.py#L389 to 412, then put it back into the resulting translations in https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translation_server.py#L456 to 462.

`n_best` > 1 would lead to a list that is `n_best` times bigger than expected, resulting in the inconsistensy of the indices.

To fix it we probably just need to consider `n_best` in the indexing, and to duplicate structures
```
        # build back results with empty texts
        for i in empty_indices:
            j = i * n_best
            results = results[:j] + [""] * n_best + results[j:]
            scores = scores[:j] + [0] * n_best + scores[j:]
        head_spaces = [h for h in head_spaces for i in range(n_best)]
        tail_spaces = [h for h in tail_spaces for i in range(n_best)]
        results = ["".join(items)
                   for items in zip(head_spaces, results, tail_spaces)]
```

All this process ensure that empty inputs are returned (empty as well then), and that preceding/following whitespaces are kept in the translation

**Comment by johnjago** [comment]
Thanks for adding the support! It now works in my application as expected. However, I have one question about the format of the JSON response from the server. Why is each object inside its own array? The response for n_best = 2 has  the following format `[[{}],[{}]]`. Why not `[{},{}]`?

Note that this change did not introduce this. With n_best = 1 the result has the format `[[{}]]`.

**Comment by pltrdy** [comment]
@johnjago indeed, it does not really make sense. The truth is that we made it for compatibility reasons with the previous lua based server. I do not really like it, but it made the transition seamless at the time, which was valuable.
