### ISSUE TITLE
How to translate complete document.

### ISSUE THREAD

**Issue by Navaneeth-Ewall** [OpenNMT/OpenNMT-py#1628]
i have trained 1M sentence pair . i'can't even translate a complete text document . application will be translate single line only, until full stop . 
kindly help me to fix this issues . how can i translate complete document .
Thanks in advance

**Comment by francoishernandez** [comment]
What's your command line?
Do you have an error? If so, please post the full trace.

**Comment by eledhwen** [comment]
> i have trained 1M sentence pair . i'can't even translate a complete text document . application will be translate single line only, until full stop .
> kindly help me to fix this issues . how can i translate complete document .

You could split your document into sentences, tokenize them, and submit those for translation in batch.
