### ISSUE TITLE
Keyerror [unk_idx] + [src_ex_vocab.stoi[w] for w in tgt] + [unk_idx])

### ISSUE THREAD

**Issue by zhu-y11** [OpenNMT/OpenNMT-py#1636]
Hi,

I got a key error in this line:

https://github.com/OpenNMT/OpenNMT-py/blob/b731e04f3a8a842d18b0e475270c98b74c2198e3/onmt/inputters/dataset_base.py#L58

it seems that src_ex_vocab is only on the source side, not on the target side, and when it numericalizes the target text, the error is thrown when some token is not on the source side. Could anyone explain to me what the code means?

Is
`[unk_idx] + [src_ex_vocab.stoi[w] if w in src_ex_vocab.stoi else unk_idx for w in tgt] + [unk_idx])`
safe?

I am modifying the library code and using my own vocabulary, so there might be also other bugs in my code.

Thank you in advance! :)

**Comment by pltrdy** [comment]
You probably just have to update `torchtext`. KeyError should not happen anymore since it will map it to the unkown token seamlessly.

Long story short this code is preparing the `alignment` that is used to determine which tokens of the target are also present in the source.

**Comment by zhu-y11** [comment]
Thank you very much! :)
