### ISSUE TITLE
Train transformer model for Sequence labeling

### ISSUE THREAD

**Issue by sebastian-nehrdich** [OpenNMT/OpenNMT-py#1644]
Hey there! 

I was wondering how to proceed if one wants to train the transformer model for a multi-class sequence labeling task. Is this possible in OpenNMT-py?

**Comment by guillaumekln** [comment]
Hi, this is not possible with OpenNMT-py without code changes. However, you can check out OpenNMT-tf which supports [sequence labeling with arbitrary encoder architecture](http://opennmt.net/OpenNMT-tf/package/opennmt.models.SequenceClassifier.html).
