### ISSUE TITLE
Translate raw input

### ISSUE THREAD

**Issue by aastha19** [OpenNMT/OpenNMT-py#1646]
Hi

While training my input I had applied Tokenization and BPE using pyonmttok.
Now while translation is it necessary to input the data the same way because if done otherwise, the results are pretty different and poor.

Is there any other way to deal with it

**Comment by francoishernandez** [comment]
Not sure to understand your point. If you trained your model on tokenized data, you need to infer on tokenized data. Maybe have a look [here](http://forum.opennmt.net/t/using-sentencepiece-byte-pair-encoding-on-model/3027/4?u=francoishernandez).

**Comment by aastha19** [comment]
@francoishernandez thanks I got the point. 
Could you please help to remove the BPE from the output results while translating. The black square boxes are required to be removed. Any help on it.

![image](https://user-images.githubusercontent.com/14852345/69136433-d8888880-0ae0-11ea-8a54-caeeea8fc92f.png)

**Comment by francoishernandez** [comment]
Since it seems you're using pyonmttok, look for the `detokenize` method [here](https://github.com/OpenNMT/Tokenizer/tree/master/bindings/python).
