### ISSUE TITLE
Training will deadlock when world_size is set to 2 and gpu_ranks only contain one value.

### ISSUE THREAD

**Issue by zhoujunpei** [OpenNMT/OpenNMT-py#1647]
I have tested it in Python 3.6 and 3.7 with Pytorch 1.2.0, finding the training will deadlock (GPU utilization will always be 0%) if we set `-world_size 2` and `-gpu_ranks 0`.
After changing -world_size back to 1, the problem is solved.

Actually I am not sure why the world_size is specified by the user, because it seems could be derived by len(gpu_ranks).

It is related with this code snippet: https://github.com/OpenNMT/OpenNMT-py/blob/8e3910235fe72fe8b511420b7445c1853667578a/onmt/bin/train.py#L58

**Comment by vince62s** [comment]
read the multi-gpu section of this https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md
