### ISSUE TITLE
-bash onmt_preprocess: command not found

### ISSUE THREAD

**Issue by bodekjan** [OpenNMT/OpenNMT-py#1649]
how to use this stuff?

**Comment by francoishernandez** [comment]
Did you install via pip or just git clone?

**Comment by bodekjan** [comment]
> Did you install via pip or just git clone?
By using pip

**Comment by bodekjan** [comment]
> This looks like a pip issue, those [entry points.](https://github.com/OpenNMT/OpenNMT-py/blob/8e3910235fe72fe8b511420b7445c1853667578a/setup.py#L33-L39) should be added as executables in your path.
> Maybe have a look [here](https://stackoverflow.com/questions/42182707/pip-not-installing-entry-points-as-executables) or [here](https://stackoverflow.com/questions/19427486/pip-importerror-entry-point-console-scripts-pip-not-found?noredirect=1).

Problem solved, It is my python environment problem

**Comment by dishan14** [comment]
hi @bodekjan and @francoishernandez  ,i am experiencing the same error but i installed using git clone , can you share what was wrong with your python environment @bodekjan

**Comment by devdudejohn** [comment]
I'm also experiencing this issue.... What fixed it for you?

**Comment by francoishernandez** [comment]
@devdudejohn if you cloned or installed a recent version `onmt_preprocess` does not exist anymore. You can check the [docs](https://opennmt.net/OpenNMT-py/quickstart.html) for details.

**Comment by meghajain-1711** [comment]
It is showing me this error for onmt_train when I am trying to run it on the colab, after installing from :
pip3 install git+https://github.com/OpenNMT/OpenNMT-py.git

**Comment by francoishernandez** [comment]
@meghajain-1711 
There is a dedicated thread on the forum for using OpenNMT-py with colab, you might want to check it out:
https://forum.opennmt.net/t/tutorial-for-opennmt-py-using-colab/2895
