### ISSUE TITLE
How to build my own model using OpenNMT-py?

### ISSUE THREAD

**Issue by entslscheia** [OpenNMT/OpenNMT-py#1652]
For now, OpenNMT looks to me like sort of an off-the-shelf command-line based tool for machine translation, however, I didn't find a concrete tutorial for using it as a library to support more flexible further development, i.e., I don't know how exactly should I use it as a high-level framework (for example, just like allennlp) to build my own model and my own training procedure. To be specific, what should I do if I want to implement my own decoder? Do I just define a new decoder inherits from `onmt.decoders.DecoderBase`, and then pass it to `onmt.models.model.NMTModel`? Also, what should I do if I want to add my own metrics for evaluation and do early stop based on the new metrics? Where should I find the answer to those questions? Any suggestions would be greatly appreciated!

**Comment by francoishernandez** [comment]
Hey @entslscheia 
I just replied on [your forum post](https://github.com/OpenNMT/OpenNMT-py/blob/f7fc40e319c03b90addc7e3364635e0fc7625b95/onmt/decoders/transformer.py#L92).
