### ISSUE TITLE
Seeking suggestions for implementing a special type of copy mechanism using OpenNMT

### ISSUE THREAD

**Issue by entslscheia** [OpenNMT/OpenNMT-py#1656]
Hi. OpenNMT has already provided the typical type of copy mechanism, i.e., copy tokens from the source based on the copy attention. Now, I want to implement another copy mechanism, in which the model doesn't directly copy from the source, instead, it copies from a knowledge base based on the copy attention over the source tokens and the matching score between source tokens and terms from the knowledge base. Then the probability of copying a term is calculated by the mapping score weighted by the copy attention. 

It seems to me that there is not enough tutorial on using OpenNMT as a library. Or maybe it's just not the purpose of OpenNMT. Do you think it's appropriate for me to implement the above-mentioned model using OpenNMT? If it's too costly to do that with OpenNMT, maybe I will switch to another framework. Many thanks!

**Comment by vince62s** [comment]
What is your task? translation or something else?

**Comment by entslscheia** [comment]
> What is your task? translation or something else?

Semantic parsing. it's in a sense similar to translation, but with a backend knowledge base.

**Comment by vince62s** [comment]
I think what you are looking for is closer to the recently merged PR #1615  rather than a copy attention mechanism.

**Comment by vince62s** [comment]
What exactly do you call your "knowledge base" ? what is it made of?

**Comment by entslscheia** [comment]
> What exactly do you call your "knowledge base" ? what is it made of?

Examples are Freebase, DBpedia, e.t.c. A knowledge base contains entities, relations, types and their interplays.
