### ISSUE TITLE
Using OpenNMT for low resource languages

### ISSUE THREAD

**Issue by shreyapandit** [OpenNMT/OpenNMT-py#1657]
Hi,

Can I follow the [NMT tutorial](http://opennmt.net/OpenNMT-py/quickstart.html#step-1-preprocess-the-data) but for low resource languages, such as Latin? 

Should the source and target files follow a specific format?

Thanks for the help and your work! I am new to the field and using OpenNMT for the first time.

**Comment by francoishernandez** [comment]
There is an [ongoing discussion on the forum](http://forum.opennmt.net/t/experiment-with-limited-data-set-how-small-is-too-small/3215/2) about low resource.
As for the quickstart, yes you may follow it with your own datasets. The options are to strict minimum though. You may for instance have a look at the [Transformer FAQ](http://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-the-transformer-model) to go further.
Finally, the data will be whitespace tokenized when preprocessing, so you might want to apply any useful tokenization to your dataset before hand. You might also want to shuffle your data if it's not already.
