### ISSUE TITLE
translate long sentences

### ISSUE THREAD

**Issue by lllyyyqqq** [OpenNMT/OpenNMT-py#1658]
When I put several long sentences in a single line,  and run translation.py, I can only get the translation of the first sentence. How can I get the complete translation of the line?

**Comment by francoishernandez** [comment]
You might want to have a look at [this option](https://github.com/OpenNMT/OpenNMT-py/blob/b98fb3d7cb96cd0677a95ca524b280351bf283c4/onmt/opts.py#L660).

**Comment by lllyyyqqq** [comment]
> You might want to have a look at [this option](https://github.com/OpenNMT/OpenNMT-py/blob/b98fb3d7cb96cd0677a95ca524b280351bf283c4/onmt/opts.py#L660).

I set -max_length a larger number, however, the result doesn't change.

**Comment by francoishernandez** [comment]
You'll need to be more specific as to how you trained your model (data, architecture, parameters) and the data you're trying to infer on. Also, this is probably more a topic for the forum.
There are already a few topics on similar matters, for instance:
- http://forum.opennmt.net/t/options-to-translate-long-sentences-or-paragraphs/3009
- http://forum.opennmt.net/t/words-are-lost-when-transforme-long-sentences/3147/2
