### ISSUE TITLE
list index out of range when translating with transformer

### ISSUE THREAD

**Issue by jiaorunnju** [OpenNMT/OpenNMT-py#1659]
Hi, I have a problem when translating with the pretrained transformer. The model and data used are:
https://s3.amazonaws.com/opennmt-models/transformer-ende-wmt-pyOnmt.tar.gz
https://s3.amazonaws.com/opennmt-trainingdata/wmt_ende_sp.tar.gz
The command I ran is as follows:
`python translate.py -model model/averaged-10-epoch.pt -src /data1/WMT2014/wmt_ende_sp/test.en -replace_unk -alpha 0.6 -beta 0.0 -beam_size 5 -length_penalty wu -coverage_penalty wu -gpu 0`
The results are:
```
Traceback (most recent call last):
  File "translate.py", line 6, in <module>
    main()
  File "/home/xxx/workspace/OpenNMT-py-master/onmt/bin/translate.py", line 49, in main
    translate(opt)
  File "/home/xxx/workspace/OpenNMT-py-master/onmt/bin/translate.py", line 33, in translate
    attn_debug=opt.attn_debug
  File "/home/xxx/workspace/OpenNMT-py-master/onmt/translate/translator.py", line 353, in translate
    translations = xlation_builder.from_batch(batch_data)
  File "/home/xxx/workspace/OpenNMT-py-master/onmt/translate/translation.py", line 95, in from_batch
    for n in range(self.n_best)]
  File "/home/xxx/workspace/OpenNMT-py-master/onmt/translate/translation.py", line 95, in <listcomp>
    for n in range(self.n_best)]
IndexError: list index out of range
```
The file to translate is test.en, which should have been encoded by sentencepiece.
```
▁28 - Y ear - O ld ▁Chef ▁Found ▁Dead ▁at ▁San ▁Francisco ▁Mal l
▁A ▁28 - year - old ▁chef ▁who ▁had ▁recently ▁moved ▁to ▁San ▁Francisco ▁was ▁found ▁dead ▁in ▁the ▁sta ir well ▁of ▁a ▁local ▁mall ▁this ▁week .
▁But ▁the ▁victim ' s ▁brother ▁says ▁he ▁can ' t ▁think ▁of ▁anyone ▁who ▁would ▁want ▁to ▁hurt ▁him , ▁saying , ▁" Th ing s ▁were ▁finally ▁going ▁well ▁for ▁him . "
```
I am using pytorch 1.3.0
It seems that the translate program does not generate a word for some inputs, since `n_best` is 1 when using transformer. When I choose a larger beam_size, e.g. 30, It may work correctly, but the BLEU would be much lower than that of a smaller beam_size and the speed is slower. I may also fail with the same error.
I am wondering whether the beam search used here will terminate with a final output, or is there any mistake I made when translating? Anyone can help with this? Thanks!

**Comment by francoishernandez** [comment]
This probably happens because pytorch 1.3.0 is broken.
Could you try downgrading to pytorch 1.2.0 or upgrading to 1.3.1?

**Comment by jiaorunnju** [comment]
Thanks for your reply! I tried pytorch 1.2.0, and it works fine.
