### ISSUE TITLE
data_type=vec, High dimensional time series data

### ISSUE THREAD

**Issue by issac-wolf** [OpenNMT/OpenNMT-py#1660]
I want to input a sequence of feature vectors which is High dimensional time series data orgnized as (batch_size, seq_len, input_size). How can I save the data into file and use preprocess.py?
Thanks!

**Comment by francoishernandez** [comment]
@flauted isn't it roughly what you introduced a few months ago?

**Comment by flauted** [comment]
Yeah. [This guide](https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/vid2text.rst) might be of help. Guessing all the functionality you need is already there. Might take a little scripting to get the data into the format, but it should be fairly clear what format is expected from the guide.
