### ISSUE TITLE
Example-based Reweighting

### ISSUE THREAD

**Issue by siddk** [OpenNMT/OpenNMT-py#1664]
Is there a way to reweight individual examples (sentence pairs) by some value? E.g. scale the loss for a given example by 0.5 (arbitrary scalars).

**Comment by vince62s** [comment]
the operation of reweighting is quite straight forward, the question is more what you want to reweight and based on what criterion.
maybe the best is to have a look at #1438 which was never merged but very interesting.

**Comment by francoishernandez** [comment]
@siddk let us know if you have some interesting results with #1438!
There are some conflicts with current master because it was done a while ago but we might fix them and merge if it appears useful.
