### ISSUE TITLE
Why encode the image to 3 dimensions instead of 4 while doing img2latex

### ISSUE THREAD

**Issue by hengyeliu** [OpenNMT/OpenNMT-py#1665]
hello, I wonder why you encode the image to 3 dimensions instead of 4 in image_encoder.py?
`for row in range(src.size(2)):
    inp = src[:, :, row, :].transpose(0, 2).transpose(1, 2)
    row_vec = torch.Tensor(batch_size).type_as(inp.data).long().fill_(row)
    pos_emb = self.pos_lut(row_vec)
    with_pos = torch.cat((pos_emb.view(1, pos_emb.size(0), pos_emb.size(1)), inp), 0)
    outputs, hidden_t = self.rnn(with_pos)
    all_outputs.append(outputs)
 out = torch.cat(all_outputs, 0)`
The input size is [batch_size, channels,H,W],The output size is [H*W,batch_size,channels]

**Comment by francoishernandez** [comment]
@da03 might have some comments here
