### ISSUE TITLE
Provide pretrained models for more languages

### ISSUE THREAD

**Issue by filips123** [OpenNMT/OpenNMT-py#1667]
Can you please provide pretrained models for more languages? As currently only pretrained models are for English and Germany, and creating custom models yourself is quite hard, this would be very useful.

For data, European Commission [provides](https://ec.europa.eu/jrc/en/language-technologies/dgt-translation-memory) DGT-Translation Memory which contains sentences in 24 languages. There is also [ParaCrawl Corpus](https://paracrawl.eu) which provides 23 languages paired with English.

It would be great if you could use them to create pretrained models.

**Comment by vince62s** [comment]
nice try, but might not happen soon.

**Comment by filips123** [comment]
@vince62s I may try to provide some models based on that data sources. Can you provide few more details how to process that data and create models?

**Comment by vince62s** [comment]
read more info (documentation) and tutos (forums) if you want to follow this path.
