### ISSUE TITLE
Generated Translation Text are one word only

### ISSUE THREAD

**Issue by Kaushalgithub94** [OpenNMT/OpenNMT-py#1668]
Hi,  I am recently started working with OpenNMT.  I am using OpenNMT for sentence generation, not for Translation. I modified the code appropriately. At this stage, I am not sure what is wrong going on i.e., the model always generates a one-word target sentence irrespective of source sentence length. If anyone encountered similar situation or can suggest possible solutions that will be a great help. Thank you!

**Comment by vince62s** [comment]
unless you submit a PR with comments and use case, it's impossible to help you based on this info.
