### ISSUE TITLE
Training takes too long

### ISSUE THREAD

**Issue by prabalbansal** [OpenNMT/OpenNMT-py#1669]
I am using OpenNMT on CPU for generating sentences from context. For testing purpose I train on  500 sentences , and it takes approx 15 minutes for 50 steps.
Below is my training command:

python3 train.py -save_model models/cnndm -data data/d/cnndm -train_steps 5000 -copy_attn -encoder_type transformer -decoder_type transformer -label_smoothing 0.1 -layers 4 -rnn_size 512 -word_vec_size 512 -transformer_ff 2048 -heads 8 -save_checkpoint_steps 1000 -batch_size 4096 -batch_type tokens -normalization tokens -max_generator_batches 2 -accum_count 4 -param_init_glorot -position_encoding

Output is: 
[2019-12-09 17:54:47,997 INFO] Step 50/ 5000; acc:   5.35; ppl: 1497.24; xent: 7.31; lr: 1.00000;  84/336 tok/s;    890 sec

**Comment by francoishernandez** [comment]
You'll need a GPU if you want to train faster.
