### ISSUE TITLE
Are there some research papers about text-to-set generation?

### ISSUE THREAD

**Issue by guotong1988** [OpenNMT/OpenNMT-py#1670]
I know this question is a little out of topic. But it is helpful to me. Thank you.

Text-to-(word)set generation or sequence-to-(token)set generation.

For example, input a text and then output the tags for this text:

`'Peter is studying English'` --> `{'good behavior','person','doing something'}`

Thank you!

**Comment by francoishernandez** [comment]
You may look for "semantic parsing", e.g. https://paperswithcode.com/task/semantic-parsing/latest
It seems some other OpenNMT users are interested in such tasks (#1656), it might be good to start some discussion on the [forum](http://forum.opennmt.net/) instead of opening different issues.

**Comment by guotong1988** [comment]
Thank you. Sorry to trouble you.

**Comment by guotong1988** [comment]
Multi-label Classification
