### ISSUE TITLE
Setting --seed for GPU has not working.  

### ISSUE THREAD

**Issue by phuongnm-bkhn** [OpenNMT/OpenNMT-py#1682]
Please check this line: 
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/bin/train.py#L25 

I think this line needs to change to 
```python 
set_random_seed(opt.seed, torch.cuda.is_available())
``` 
or check setting opt using gpuid or not.

**Comment by vince62s** [comment]
no this one is just to keep the same examples order of the datasets.
waht you are looking ofr is here:
https://github.com/OpenNMT/OpenNMT-py/blob/09f40dc575af72a60467f591a133b8123ee4b5b7/onmt/train_single.py#L39
