### ISSUE TITLE
Chinese->English Translation Preprocess

### ISSUE THREAD

**Issue by ARDUJS** [OpenNMT/OpenNMT-py#1683]
How to preprocess the Chinese training corpus?
this is my command:
python train.py -data ./data/ch-en-morph  -save_model ch-en -world_size 2 -gpu_rank 0 1 -encoder_type transformer -decoder_type transformer -rnn_size 360 -word_vec_size 360
but poor effect.
![image](https://user-images.githubusercontent.com/20811685/70881124-874bb600-2006-11ea-9a4d-388dc3207616.png)
why?
What modifications can I try?

**Comment by vince62s** [comment]
read some WMT19 papers, like this one: https://www.aclweb.org/anthology/W19-5341/
