### ISSUE TITLE
Could I use NestedField with TextMultiField?

### ISSUE THREAD

**Issue by kugwzk** [OpenNMT/OpenNMT-py#1684]
Hi. I want to use a hierarchy input like: [sentence_list_1[], sentence_list_2[],....]. So if I need to use Nestedfield to hold the hierarchy structure of the input? And if I use the Nestedfield instead of the Field in official code, what should I pay more attention about it and could I use it with TextMultiField?

**Comment by vince62s** [comment]
not sure what you are trying to accomplish, but why not using features instead ?
