### ISSUE TITLE
raise value assertionerror how to fix this error. 

### ISSUE THREAD

**Issue by zeeshan649** [OpenNMT/OpenNMT-py#1687]
how to fix this error i already use save my dataset with utf8 type.
![test](https://user-images.githubusercontent.com/58245332/71310234-8cbe4d00-23c6-11ea-9e44-30410cf1f4b3.jpg)

**Comment by vince62s** [comment]
source and target don't have the same number of lines.
might come fro a special character if wc -l gives you the same number.

**Comment by zeeshan649** [comment]
i use english is source script and target script is arabic lines are also same please help me what i can do

**Comment by zeeshan649** [comment]
how to fix this error
