### ISSUE TITLE
Transformer layers (encoder and decoder) implementation

### ISSUE THREAD

**Issue by antoniovilarinholopes** [OpenNMT/OpenNMT-py#1689]
Hi,

While I was trying to extend the transformer decoder layer, I noticed something odd in the implementation -- which I traced back to this [commit](https://github.com/OpenNMT/OpenNMT-py/commit/b4fb1ddf3a2963514db80a49da70a4173e963b85) trying to mimic the onmt-tf implementation. Before this change, the implementation was actually what should be expected (in my opinion).

Correct me if I'm wrong but here is what I found (I don't know know how much impact it has):

- Residual connection of encoder-decoder attention is not actually `X+Sublayer(X)`,  starting at line [132](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/transformer.py#L132). In addition, there's also layer norm missing in line [139](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/transformer.py#L139), the same place where the residual is created.
``` 
        query = self.drop(query) + inputs
        query_norm = self.layer_norm_2(query)
        mid, attns = self.context_attn(memory_bank, memory_bank, query_norm,
                                       mask=src_pad_mask,
                                       layer_cache=layer_cache,
                                       attn_type="context")
        output = self.feed_forward(self.drop(mid) + query)
```
- Also, for the self-attention, again the residual connection is with the non-normalized query, line [132](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/transformer.py#L132). The same applies for the transformer encoder.

From a quick inspection of other frameworks (fairseq, marian, tensor2tensor), even the pytorch nn.Transformer, I noticed they are more faithful to the original paper. So now I'm wondering, why does onmt (also, onmt-tf) use a different implementation? Is there any motivation for this choice (can you point me the literature)?

**Comment by vince62s** [comment]
check this if it answers part of your questions.
https://github.com/OpenNMT/OpenNMT-py/issues/770

**Comment by antoniovilarinholopes** [comment]
Thank you for your quick answer! It does answer my questions, thank you. I'm closing this issue

**Comment by mathematicsofpaul** [comment]
So to summarize, the authors found that the swapping of the ordering of the layernorm and etc. was better experimentally?

**Comment by francoishernandez** [comment]
IIRC [this paper](https://arxiv.org/abs/1906.01787) goes deeper in the analysis of pre-norm vs post-norm.
