### ISSUE TITLE
give same translation 

### ISSUE THREAD

**Issue by zeeshan649** [OpenNMT/OpenNMT-py#1690]
i train more then 1 million sentences dataset but they will give me only one small sentences and repeat that sentence for every translation .when i test for some sentences it give me only one sentence translation but that  translation sentence used for every target sentence
![test](https://user-images.githubusercontent.com/58245332/71555838-02d53c00-29e5-11ea-9504-d3125fd31f4a.jpg)

**Comment by vince62s** [comment]
you don't give enough info, please sue the forum for this type of questions.
