### ISSUE TITLE
demo-model_acc_XX.XX_ppl_XXX.XX_eX.pt

### ISSUE THREAD

**Issue by zeeshan649** [OpenNMT/OpenNMT-py#1694]
Hello

I’m new in using openNMT-py and I’d like to know which model should I pick up for translation out of all the models I get from the training process. In the tutorial I see that the models should be this form

demo-model_acc_XX.XX_ppl_XXX.XX_eX.pt

however my models name are like this:

model_step_45000.pt

Can you please let me know how can I obtain the model that looks like the demo example or how can I know which model is the best for translation?

Thanks in advance

**Comment by francoishernandez** [comment]
The model name structure changed a while back, now it only shows which training step it is.
You'll have to look at your logs if you want acc/ppl metrics.
To choose which model fits best for your translation task you might want to have a look at metrics like BLEU or TER.

**Comment by zeeshan649** [comment]
you means i try from every step model which is created

**Comment by francoishernandez** [comment]
Basically yes.
http://forum.opennmt.net/t/model-stats-opennmt-py/2476
