### ISSUE TITLE
Using Multiple GPUs for different MT models

### ISSUE THREAD

**Issue by mayank408** [OpenNMT/OpenNMT-py#1695]
I have a machine with 2 GPU's, I want to train to different MT models in each of them for the first GPU, I am using simply gpu_ranks 0 and world_size 1 and it's running fine, But when I try on to run my other model on different GPU by using gpu_ranks 1 and world_size 2, it doesn't work and show TCP connect() error.

**Comment by francoishernandez** [comment]
You need to have world_size 1 gpu_ranks 0 for both runs. You can chose which GPU to use with the environment variable 'CUDA_VISIBLE_DEVICES'.
You'll also have to change the master_port option for the second one you'll launch.

**Comment by mayank408** [comment]
Thanks, @francoishernandez it worked like a charm :')
