### ISSUE TITLE
why set bos and eos always be None in the src filed in the translation preprocess?

### ISSUE THREAD

**Issue by labixiaoK** [OpenNMT/OpenNMT-py#1697]
As what I say in the title, and the relevant code is on **line 152** of **inputter.py**：
```
    src_field_kwargs = {"n_feats": n_src_feats,
                        "include_lengths": True,
                        "pad": pad, "bos": None, "eos": None,
                        "truncate": src_truncate,
                        "base_name": "src"}
    fields["src"] = fields_getters[src_data_type](**src_field_kwargs)
```
Is this an intentional setup or an error？

**Comment by francoishernandez** [comment]
It's because these kwargs are also valid for other type of inputs (image, audio, etc.).
They're still defaulting to <s> </s> in the `text_fields` function.
See #1210.

**Comment by labixiaoK** [comment]
> It's because these kwargs are also valid for other type of inputs (image, audio, etc.).
> They're still defaulting to in the `text_fields` function.
> See #1210.

okay, agree with the first point.
But they are always be None in the `text_fields ` function, because u have explicitly set them to `None `and passed them to the `text_fields `.

**Comment by francoishernandez** [comment]
I think it was always the case in fact for source fields, eos/bos were not set before (and they [default to None in torchtext definition](https://torchtext.readthedocs.io/en/latest/data.html#field)), if you look here:
https://github.com/OpenNMT/OpenNMT-py/pull/1210/files#diff-55eec480db97bda4ea4ea8fc498bfad6L124
