### ISSUE TITLE
BPE using BPEmb

### ISSUE THREAD

**Issue by mayank408** [OpenNMT/OpenNMT-py#1698]
I am trying out Byte Pair Encoding (BPE) using the word embeddings from BPEmb. I am trying to understand the pipeline to be used. If I am not wrong this should be the process:-
1. Construct BPE vocab of say 25k for source and target language.
2. Preprocess the Source Train, Source Test and Target Train leaving Target Test.
3. (doubt) I should replace "@@" with "" in the training test.
4. Train the model with word embeddings as BPEmb.
5. (doubt)Do the same process at the time of translating.

**Comment by francoishernandez** [comment]
Some links that might help you:
- http://forum.opennmt.net/t/using-sentencepiece-byte-pair-encoding-on-model/3027/4?u=francoishernandez
- http://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-pretrained-embeddings-e-g-glove
