### ISSUE TITLE
Where to find word embedding lookup table

### ISSUE THREAD

**Issue by Americanwallace0** [OpenNMT/OpenNMT-py#1699]
Hello,

I trained word embedding while training, not using pre-trained embedding
Now I want to extract the parameters of word embedding (look-up table). where can I find it?

**Comment by Americanwallace0** [comment]
Sorry, perhaps I didn’t ask a question.
I know extract_embeddings.py can extract look-up table from saved models.

Now I want to read the input word embedding at each iteration and Then manipulate the word embedding by adding a tensor. Can I do that?

**Comment by francoishernandez** [comment]
You can have a look inside the encoder of the model you're using, in `onmt.encoders`.
For instance for transformer: https://github.com/OpenNMT/OpenNMT-py/blob/f44d1d2550c04cf7c8f8e190d1ddc3443439f7f4/onmt/encoders/transformer.py#L121
