### ISSUE TITLE
Could we know the id of a source-target pair while training 

### ISSUE THREAD

**Issue by Mingyu-academic** [OpenNMT/OpenNMT-py#1701]
Hello,
Sorry if this is a noob question, now I want to know which pair or which source sequence is being process while training. I remembered it was a id number. Can we now still do that?

**Comment by francoishernandez** [comment]
Examples are processed in batches. Batches are produced by an iterator (`onmt.inputters.inputter.DatasetLazyIter` or `onmt.inputters.inputter.MultipleDatasetIterator` depending on your setup).
For performance reasons, these iterators both apply some 'pooling' mechanism: retrieve `pool_factor` * `batch_size` examples, sort them by length, split in batches, yield them in a random way (with set random seed).
Not sure the id is carried all the way through that process. If not, you might want to add a custom field.

**Comment by Americanwallace0** [comment]
> Examples are processed in batches. Batches are produced by an iterator (`onmt.inputters.inputter.DatasetLazyIter` or `onmt.inputters.inputter.MultipleDatasetIterator` depending on your setup).
> For performance reasons, these iterators both apply some 'pooling' mechanism: retrieve `pool_factor` * `batch_size` examples, sort them by length, split in batches, yield them in a random way (with set random seed).
> Not sure the id is carried all the way through that process. If not, you might want to add a custom field.

Excuse me, if I want to add a custom field, how can I do that?

**Comment by francoishernandez** [comment]
You can have a look at #1418 where we add a "weight" fields. You can do quite the same with your IDs.
