### ISSUE TITLE
Installation Error in while running command: pip install -r requirements.opt.txt --no-cache-dir

### ISSUE THREAD

**Issue by RavneetDTU** [OpenNMT/OpenNMT-py#1704]
Installing collected packages: pycparser, cffi, Pillow, numpy, torch, six, torchvision, joblib, audioread, scipy, scikit-learn, decorator, setuptools, llvmlite, numba, resampy, soundfile, librosa, pyrouge, opencv-python, munch, tqdm, pretrainedmodels, torchaudio, apex
  Running setup.py install for pycparser ... done
  Running setup.py install for audioread ... done
  Running setup.py install for resampy ... done
  Running setup.py install for librosa ... done
  Running setup.py install for pyrouge ... done
  Running setup.py install for pretrainedmodels ... done
  Running setup.py install for torchaudio ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-ev_133q9-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bp_e2aup-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/torchaudio
    copying torchaudio/legacy.py -> build/lib.linux-x86_64-3.6/torchaudio
    copying torchaudio/transforms.py -> build/lib.linux-x86_64-3.6/torchaudio
    copying torchaudio/common_utils.py -> build/lib.linux-x86_64-3.6/torchaudio
    copying torchaudio/functional.py -> build/lib.linux-x86_64-3.6/torchaudio
    copying torchaudio/kaldi_io.py -> build/lib.linux-x86_64-3.6/torchaudio
    copying torchaudio/__init__.py -> build/lib.linux-x86_64-3.6/torchaudio
    copying torchaudio/sox_effects.py -> build/lib.linux-x86_64-3.6/torchaudio
    creating build/lib.linux-x86_64-3.6/test
    copying test/test.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_kaldi_io.py -> build/lib.linux-x86_64-3.6/test
    copying test/common_utils.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_dataloader.py -> build/lib.linux-x86_64-3.6/test
    copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_legacy.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_sox_effects.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_transforms.py -> build/lib.linux-x86_64-3.6/test
    creating build/lib.linux-x86_64-3.6/torchaudio/datasets
    copying torchaudio/datasets/vctk.py -> build/lib.linux-x86_64-3.6/torchaudio/datasets
    copying torchaudio/datasets/yesno.py -> build/lib.linux-x86_64-3.6/torchaudio/datasets
    copying torchaudio/datasets/__init__.py -> build/lib.linux-x86_64-3.6/torchaudio/datasets
    running build_ext
    building '_torch_sox' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/torchaudio
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/rlabs/.local/lib/python3.6/site-packages/torch/include -I/home/rlabs/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/rlabs/.local/lib/python3.6/site-packages/torch/include/TH -I/home/rlabs/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/include/python3.6m -c torchaudio/torch_sox.cpp -o build/temp.linux-x86_64-3.6/torchaudio/torch_sox.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_torch_sox -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    torchaudio/torch_sox.cpp:3:10: fatal error: sox.h: No such file or directory
     #include <sox.h>
              ^~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-ev_133q9-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bp_e2aup-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-ev_133q9-build/

**Comment by francoishernandez** [comment]
You need to install sox libraries.
Or remove the torchaudio requirement if you don't need it.

**Comment by steve3p0** [comment]
Hello.  Can you be more specific about the sox libraries?

I followed these instructions here.  Is this the right sox library?

https://at.projects.genivi.org/wiki/display/PROJ/Installation+of+SoX+on+different+Platforms
`sudo apt-get install sox`

After installing sox, I still get the same exact error as RavneetDTU.

I tried both the following commands with the same error result as above:

```
pip3 install -r requirements.opt.txt  --no-cache-dir
pip3 install -r requirements.opt.txt
```

**Comment by RavneetDTU** [comment]
@steve3p0, if you are not working with sound/music files, just comment the Sox requirement. In past few months, sox changed much and pip package is not update.

If your project need Sox, still comment Sox from requirements and use other resources to install it. It will work fine with OpenNMT. Conda can be helpful for installation.
