### ISSUE TITLE
How to train on GPU 1, while leaving GPU 0? 

### ISSUE THREAD

**Issue by RavneetDTU** [OpenNMT/OpenNMT-py#1707]
Mine 1st GPU is Old Quadro, doesn’t support new PyTorch Version. Another one is new Tesla K40.
Just wants to start on GPU 1, instead 0.
I can’t remove old one as Tesla don’t have display port.

So how to train on only GPU 1, while leaving GPU 0 ?

**Comment by francoishernandez** [comment]
Use the CUDA_VISIBLE_DEVICES environment variable.
--> `export CUDA_VISIBLE_DEVICES=1` in your shell before running OpenNMT training.
