### ISSUE TITLE
Using SentencePiece & onmt_preprocess?

### ISSUE THREAD

**Issue by paulkp** [OpenNMT/OpenNMT-py#1721]
Hi @guillaumekln et al
I successfully got SentencePiece working and measured the BLEU of the Transformer OpenNMT-py pre-trained model. 
Q1. To reproduce the TRAINING of the Transformer itself, how do I use SentencePiece & onmt_preprocess? Do I run SentencePiece first and then pass those files (with underscores etc) into onmt_preprocess? Or?
Q2. I got a BLEU of 33.1 for the pre-trained Transformer model on the test.en/test.de data. That's higher than the 2014 & 2017 news tests (26-28). Why? What is the test.de/test.en data anyway? Is it either of the 2014 or 2017 news tests or something else again?

**Comment by paulkp** [comment]
@guillaumekln ?

**Comment by vince62s** [comment]
Search the forum but in essence:
You have to tokenize a sentence with sentence piece, translate it, detokenize the output and score the detokenized output.
Your score is on the tokenized output hence higher Bleu.

**Comment by francoishernandez** [comment]
This post might help: https://forum.opennmt.net/t/using-sentencepiece-byte-pair-encoding-on-model/3027/4?u=francoishernandez
