### ISSUE TITLE
Arguments outdated in `LossComputeBase`?

### ISSUE THREAD

**Issue by chrisrytting** [OpenNMT/OpenNMT-py#1723]
Why are `tgt_vocab` and `normalization` specified here as arguments when the constructor doesn't take them, but rather an unspecified argument `criterion`? 

https://github.com/OpenNMT/OpenNMT-py/blob/5ea9cb2fa0d12e1f8b3b835ecf51a4b949fc0a14/onmt/utils/loss.py#L67-L89 # #

**Comment by francoishernandez** [comment]
Good question. Looks like it dates back to #1057 .
We'll need to make this clearer.
