### ISSUE TITLE
Usage of pretrained embedding and Transformers

### ISSUE THREAD

**Issue by rajeshsahu09** [OpenNMT/OpenNMT-py#1725]
Thanks for sharing your work. I am wondering if **OpenNMT-Py** supports **pretrained embedding** or not and does this **has Transformer** implemetation or not?

I want to feed source embedding to encoder side and target embedding to decoding side. Can I do this?

If these are supported then how can I use them? Please help...

**Comment by francoishernandez** [comment]
Look at the first two questions of the [FAQ](https://opennmt.net/OpenNMT-py/FAQ.html#faq).

**Comment by rajeshsahu09** [comment]
thank you
