### ISSUE TITLE
Vocabulary size and best model configuration for Transformer on WMT data WITHOUT sentence-piece vocabulary

### ISSUE THREAD

**Issue by abhirut** [OpenNMT/OpenNMT-py#1726]
Hi,

Has anyone figured out the optimal vocabulary sizes for src and tgt, and model parameters for training the Transformer model on en-de WMT data, without using sentencepieces? 

(I am trying to work on extensions to the translation model where I'd rather not have sentence-pieces at the moment.)

**Comment by vince62s** [comment]
when it comes to german, it will ne difficult to get good results without bpe/sentencepiece.
you still can try about 40K
the thing is the bigger the vocab the smaller your batch size will be without going OOM.
good luck.
