### ISSUE TITLE
Pretrained German2English translation model getting bad results

### ISSUE THREAD

**Issue by deepseek** [OpenNMT/OpenNMT-py#1727]
@srush @bpopeters @vince62s @pltrdy @sebastianGehrmann @bmccann @da03 @falcondai 
Thank you for your hard work, you are appreciated.

When testing the [german2english](https://s3.amazonaws.com/opennmt-models/iwslt-brnn2.s131_acc_62.71_ppl_7.74_e20.pt) translation pretrained model, the results seem bad, example:
input: `Mein Name ist Tom, wie geht es dir?`
pred: `Mein Name : how goes to dir?`
The translation should be: `My name is Tom, how are you?`

```
onmt_translate -model iwslt-brnn2.s131_acc_62.71_ppl_7.74_e20.pt -src input.txt -output pred.txt -replace_unk -verbose
```

**Comment by francoishernandez** [comment]
You need to tokenize your input.
Have a look at this post: https://forum.opennmt.net/t/preprocessing-for-running-german-english-bilstm-pretrained-model/3339
