### ISSUE TITLE
Confusion about testing the model and BLEU scores

### ISSUE THREAD

**Issue by lihongzheng-nlp** [OpenNMT/OpenNMT-py#1733]
I'm conducting word_based Chinese-Vitenamese (zh-vi ) NMT with OpenNMT-py. The data are all  word segmented and preprocessed with fastBPE,  and produce train-bpe.txt, valid-bpe.txt and test-bpe.txt respectively.  

My first question is,  **when translating the model to give outputs, which test file I should use? the original test.txt or the BPE-processed test-bpe.txt?**  I translated the original and the processed respectively, and found the two testout files ( named testout.original.vi  and  testout.bpe.vi ) have the BPE '@@' symbols.

When calculating BLEU with multi-bleu.perl, I tested the two testout files with the two ref files (original and BPE-processed ), found that :

testout.original.vi V.S.  test.original.vi  is 9.86;
testout.original.vi V.S.  test.bpe.vi is 8.91;
testout.bpe.vi V.S. test.original.vi  is 9.56
testout.bpe.vi V.S. test.bpe.vi is 8.93

My second question is, which score above should be the final score? And should I detokenize the output before calculating BLEU?  @vince62s  would you please solve my confusion ? Thank you very much!

**Comment by francoishernandez** [comment]
You can read [this post](https://forum.opennmt.net/t/using-sentencepiece-byte-pair-encoding-on-model/3027/4?u=francoishernandez) to better understand the tokenization workflow.

BLEU scores are usually reported on **detokenized** outputs, but it might depend on the language. I think for some asian languages for instance there is necessarily some tokenization applied to be able to compute BLEU.

**Comment by lihongzheng-nlp** [comment]
@francoishernandez Thank you for your comments. I've read the post, I understand the pipeline before translating. But I'm not sure which test file to be translated with the trained sub-word model, because if without BPE, there's only one test file, but now there are two,  I guess the BPE-processed file should be translated?

**Comment by francoishernandez** [comment]
As said in the post : 
>As for inference, in step 3 you need to use the same model than the one you used on your training data.
And in the end, you need indeed to detokenize to have your text in the proper format.

When inferring, the model is doing the task it has learned. If it learned subword input / subword output, then you need to give a subword input to get a subword output.
Afterwards, you may need to manipulate this output to get the proper score.

**Comment by lihongzheng-nlp** [comment]
@francoishernandez thanks for your comments.  At the beginning, I was confused with the translation outputs with the '@@' symbols, but today I have solved the problem by using `'sed -r 's/(@@ )|(@@ ?$)//g''` to convert the outputs to normal tokenenized texts without the symbols first. And I can calculate BLEU with **the original reference file**, further, as you said, I should detokenize the outputs before the BLEU score.  Thank you once again!
