### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by tonytu16** [OpenNMT/OpenNMT-py#1734]
I was trying to create glove embeddings using the following command
./tools/embeddings_to_torch.py -emb_file_both /OpenNMT-py/glove_dir/glove.6B.100d.txt -dict_file "data/data.vocab.pt" -output_file "data/embeddings"

but I'm getting:
Saving embedding as:
	* enc: data/embeddings.enc.pt
	* dec: data/embeddings.dec.pt
Traceback (most recent call last):
  File "./tools/embeddings_to_torch.py", line 160, in <module>
    main()
  File "./tools/embeddings_to_torch.py", line 148, in main
    convert_to_torch_tensor(src_vectors, enc_vocab),
  File "./tools/embeddings_to_torch.py", line 57, in convert_to_torch_tensor
    dim = len(six.next(six.itervalues(word_to_float_list_dict)))
StopIteration

Can someone help?

**Comment by francoishernandez** [comment]
This `StopIteration` means that it [reached the end of the iterator](https://six.readthedocs.io/#six.advance_iterator).
This means your `src_vectors` is empty or in the wrong format.

**Comment by tonytu16** [comment]
Thanks for the reply! What could be causing this error? I am using the same format as src-train-case.txt except that I am using two features.
