### ISSUE TITLE
Same Issue :( with speech to text 

### ISSUE THREAD

**Issue by Nouraaaawwad** [OpenNMT/OpenNMT-py#1737]
First of all i want to thank you for the fast reply.

second, I already triend to install the torchaudio with this command:
"!pip install git+git://github.com/pytorch/audio.git@d92de5b97fc6204db4b1e3ed20c03ac06f5d53f0"
but got this error:
Collecting git+git://github.com/pytorch/audio.git@d92de5b97fc6204db4b1e3ed20c03ac06f5d53f0
  Cloning git://github.com/pytorch/audio.git (to revision d92de5b97fc6204db4b1e3ed20c03ac06f5d53f0) to /tmp/pip-req-build-ltc3xil8
  Running command git clone -q git://github.com/pytorch/audio.git /tmp/pip-req-build-ltc3xil8
  Running command git checkout -q d92de5b97fc6204db4b1e3ed20c03ac06f5d53f0
Requirement already satisfied: torch in /usr/local/lib/python3.6/dist-packages (from torchaudio==0.2) (1.4.0)
Building wheels for collected packages: torchaudio
  Building wheel for torchaudio (setup.py) ... error
  ERROR: Failed building wheel for torchaudio
  Running setup.py clean for torchaudio
Failed to build torchaudio
Installing collected packages: torchaudio
  Found existing installation: torchaudio 0.4.0
    Uninstalling torchaudio-0.4.0:
      Successfully uninstalled torchaudio-0.4.0
    Running setup.py install for torchaudio ... error
  Rolling back uninstall of torchaudio
  Moving to /usr/local/lib/python3.6/dist-packages/_torch_sox.cpython-36m-x86_64-linux-gnu.so
   from /tmp/pip-uninstall-_oeqhe2q/_torch_sox.cpython-36m-x86_64-linux-gnu.so
  Moving to /usr/local/lib/python3.6/dist-packages/torchaudio-0.4.0.dist-info/
   from /usr/local/lib/python3.6/dist-packages/~orchaudio-0.4.0.dist-info
  Moving to /usr/local/lib/python3.6/dist-packages/torchaudio/
   from /usr/local/lib/python3.6/dist-packages/~orchaudio
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ltc3xil8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ltc3xil8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6s6k53ha/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

thats why i used this command to install the toarchaudio earlier :
"!pip install torchaudio"

and it successfully installed but when i run the command:
I try the speech to text example in openNMT
→ python preprocess.py -data_type audio -src_dir data/speech/an4_dataset -train_src data/speech/src-train.txt -train_tgt data/speech/tgt-train.txt -valid_src data/speech/src-val.txt -valid_tgt data/speech/tgt-val.txt -shard_size 300 -save_data data/speech/demo

the error is :
**[2020-03-02 20:21:17,427 INFO] Extracting features...
[2020-03-02 20:21:17,427 INFO] * number of source features: 0.
[2020-03-02 20:21:17,427 INFO] * number of target features: 0.
[2020-03-02 20:21:17,427 INFO] Building Fields object...
[2020-03-02 20:21:17,428 INFO] Building & saving training data...
[2020-03-02 20:21:17,436 INFO] Building shard 0.
0% 0/276 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
result = (True, func(*args, **kwds))
File "/content/OpenNMT-py/onmt/bin/preprocess.py", line 64, in process_one_shard
filter_pred=filter_pred
File "/content/OpenNMT-py/onmt/inputters/dataset_base.py", line 121, in init
for ex_dict in starmap(join_dicts, zip(*read_iters)):
File "/content/OpenNMT-py/onmt/inputters/audio_dataset.py", line 127, in read
spect = self.extract_features(audio_path)
File "/content/OpenNMT-py/onmt/inputters/audio_dataset.py", line 64, in extract_features
sound, sample_rate = torchaudio.legacy.load(audio_path)
AttributeError: module 'torchaudio' has no attribute 'legacy'
-------------------------

The answer was:
It was probably not a url for a webpage but for the commit in question. This needs to be installed via pip.
`pip install -r requirements.opt.txt`
or
`pip install git+git://github.com/pytorch/audio.git@d92de5b97fc6204db4b1e3ed20c03ac06f5d53f0`

_Originally posted by @francoishernandez in https://github.com/OpenNMT/OpenNMT-py/issues/1736#issuecomment-593610624_

**Comment by francoishernandez** [comment]
Please do not open a duplicate issue when discussion is already happening in another one.
This error is the very reason you need to install the right torchaudio version.
I just ran it again on an ubuntu 18.04 machine and it went smoothly. You must have something wrong with your setup. As mentioned in the error message: check the logs to see what might have gone wrong when trying to install.
