### ISSUE TITLE
The code of copy mechanism seems that it can't copy unknown word in target dict?

### ISSUE THREAD

**Issue by wjbianjason** [OpenNMT/OpenNMT-py#174]
The code of combination of copy prob and output prob:
```
out, c_attn_t = self.model.generator.forward(
                        decOut, attn_copy.view(-1, batch_src.    size(0)))
for b in range(out.size(0)):
    for c in range(c_attn_t.size(1)):
        v = self.align[words[0, c].data[0]]
        if v != onmt.Constants.PAD:
            out[b, v] += c_attn_t[b, c]
out = out.log()
```
self.align corresponding code as follow:
```
def align(self, other):
    alignment = [onmt.Constants.PAD] * self.size()
    for idx, label in self.idxToLabel.items():
        if label in other.labelToIdx:
            alignment[idx] = other.labelToIdx[label]
    return alignment
```
as you can see, when the source word is unknown in target dict, its copy prob will can't be calculated.
anyone explain why implementation of  copy mechanism this way?

**Comment by srush** [comment]
Yes, we are changing the implementation of this. It is mostly working in the `torchtext` branch.

**Comment by srush** [comment]
Fixed now. You need to call preprocess.py with `-dynamic_dict`

**Comment by wjbianjason** [comment]
Ok, Thanks!

**Comment by eeric** [comment]
make OpenNMT project audio list and sentences text list, as following:
https://github.com/eeric/OpenNMT-py-make-tgt-train.txt/blob/master/openNMT_make_label.py
