### ISSUE TITLE
Why features are calculated after splitting based on pipe, what if the data does not contain "|"

### ISSUE THREAD

**Issue by sahinurlaskar** [OpenNMT/OpenNMT-py#1744]
https://github.com/OpenNMT/OpenNMT-py/blob/e442f3f8b114c36397cd2ada41af0edeeb3b20af/onmt/bin/preprocess.py#L237

**Comment by vince62s** [comment]
be more specific, I don't understand your question.

**Comment by francoishernandez** [comment]
@sahinurlaskar 'features' are actually additional 'word features'
Words/tokens have embeddings on their own. Word features are not necessary for training.
