### ISSUE TITLE
Pretrained Embeddings for Word Features Only

### ISSUE THREAD

**Issue by sawsanq** [OpenNMT/OpenNMT-py#1750]
Hello, 

Would it be possible that we have only word features in the source side initialized with pre-trained embeddings? But the words themselves in the source and target side initialized randomly during training? 

For example, 
word_source  | feat1 ---> word_target 
word_source and word_target are initialized randomly but feat1 uses pretrained embeddings. 

Thank you!

**Comment by eduamf** [comment]
The embeddings with features?

A line in a word embedded file is like: 
word 0.9, 0.3, ..., 1.2

A vocabulary (or "dictionary") file line is like: 
word | feat1

Supposing a pretrained embeddings where the first dimension of each word represents the POS (part-of-speech) and the target don`t need that information. Then you can set it to zero.
