### ISSUE TITLE
Example code to load pretrained NMT models

### ISSUE THREAD

**Issue by elyase** [OpenNMT/OpenNMT-py#1758]
I am unable to load and use the en-de transformer pretrained model. This is the code I am using:

```
import onmt
import onmt.inputters
import onmt.translate
import onmt.model_builder
from collections import named tuple

Opt = namedtuple('Opt', ['model', 'data_type', 'reuse_copy_attn', "gpu"])
opt = Opt("transformer-ende-wmt-pyOnmt.tar.gz", "text",False, 0)
fields, model, model_opt =  onmt.model_builder.load_test_model(opt,{"reuse_copy_attn":False})
```

which fails with:

`AttributeError: 'dict' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.`

I haven't been able to find documentation on how to load the pretrained models in python. Can someone help?

**Comment by francoishernandez** [comment]
You need to decompress the tarball. The model is the `.pt` file inside it.

**Comment by elyase** [comment]
@francoishernandez  Thanks for your reply. I should have mentioned that I tried that but got the same error. This is the code I am using:

```
import onmt
import onmt.inputters
import onmt.translate
import onmt.model_builder
from collections import namedtuple

# Load the model.
Opt = namedtuple('Opt', ['model', 'data_type', 'reuse_copy_attn', "gpu"])
opt = Opt("opennmt/averaged-10-epoch.pt", "text",False, 0)
fields, model, model_opt =  onmt.model_builder.load_test_model(opt,{"reuse_copy_attn":False})

# Test data
data = onmt.inputters.build_dataset(fields, "text", None, use_filter_pred=False, src_path='/Users/esalesky/projects/data/fisher/test.es')
data_iter = onmt.inputters.OrderedIterator(
        dataset=data, device='cuda',
        batch_size=1, train=False, sort=False,
        sort_within_batch=True, shuffle=False)

# Translator
translator = onmt.translate.Translator(model, fields,
                                           beam_size=5,
                                           n_best=1,
                                           global_scorer=onmt.translate.GNMTGlobalScorer(0, 0, "none", "none"),
                                           gpu=True)

builder = onmt.translate.TranslationBuilder(
        data, translator.fields,
        1, False, None)

for j, batch in enumerate(data_iter):
        batch_data = translator.translate_batch(batch, data)
        translations = builder.from_batch(batch_data)
        print("src:", " ".join(translations[0].src_raw))
        print("tgt:", " ".join(translations[0].pred_sents[0]))
        print("idx:",str(j))
        print("-----")

```

and this is the error I am getting:

```
python test.py
Traceback (most recent call last):
  File "/home/elyase/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 289, in _check_seekable
    f.seek(f.tell())
AttributeError: 'dict' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    fields, model, model_opt =  onmt.model_builder.load_test_model(opt,{"reuse_copy_attn":False})
  File "/home/elyase/miniconda3/lib/python3.6/site-packages/onmt/model_builder.py", line 95, in load_test_model
    map_location=lambda storage, loc: storage)
  File "/home/elyase/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/elyase/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 217, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/home/elyase/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 202, in __init__
    _check_seekable(buffer)
  File "/home/elyase/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 292, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/home/elyase/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 285, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'dict' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
```

**Comment by francoishernandez** [comment]
You're not passing the right arguments to the function.
It takes your dict `{"reuse_copy_attn":False}` as a model_path.

https://github.com/OpenNMT/OpenNMT-py/blob/a4b800d1fa12d23651902df9c3d537944b2e7f75/onmt/model_builder.py#L91-L114

**Comment by elyase** [comment]
Thanks. I was finally able to run a minimum example of how to translate using a pretrained model:
```
from onmt.translate.translator import build_translator
from argparse import Namespace

path = 'averaged-10-epoch.pt'
opt = Namespace(alpha=0.0, batch_type='sents', beam_size=5, beta=-0.0, block_ngram_repeat=0, coverage_penalty='none', data_type='text', dump_beam='', fp32=False, gpu=-1, ignore_when_blocking=[], length_penalty='none', max_length=100, max_sent_length=None, min_length=0, models=['openmnt/averaged-10-epoch.pt'], n_best=1, output='/dev/null', phrase_table='', random_sampling_temp=1.0, random_sampling_topk=1, ratio=-0.0, replace_unk=False, report_align=False, report_time=False, seed=829, stepwise_penalty=False, tgt=None, verbose=False)
translator = build_translator(opt, report_score=False)
translator.translate(['it kinda works'], batch_size=1)
```

**Comment by RobinRojowiec** [comment]
I looks wrong because you need to use the provided sentence piece model to translate, e.g.: `import sentencepiece as spm
sp = spm.SentencePieceProcessor()
sp.Load("pretrained_models/sentencepiece.model")
pieces = sp.EncodeAsPieces('it kinda works')
text = " ".join(pieces)
# ▁It ▁kind a ▁works`

**Comment by elyase** [comment]
Correct, took me a while but was able to figure it out here:
https://github.com/OpenNMT/OpenNMT-py/issues/1760

**Comment by abdullahkhilji** [comment]
> Thanks. I was finally able to run a minimum example of how to translate using a pretrained model:
> 
> ```
> from onmt.translate.translator import build_translator
> from argparse import Namespace
> 
> path = 'averaged-10-epoch.pt'
> opt = Namespace(alpha=0.0, batch_type='sents', beam_size=5, beta=-0.0, block_ngram_repeat=0, coverage_penalty='none', data_type='text', dump_beam='', fp32=False, gpu=-1, ignore_when_blocking=[], length_penalty='none', max_length=100, max_sent_length=None, min_length=0, models=['openmnt/averaged-10-epoch.pt'], n_best=1, output='/dev/null', phrase_table='', random_sampling_temp=1.0, random_sampling_topk=1, ratio=-0.0, replace_unk=False, report_align=False, report_time=False, seed=829, stepwise_penalty=False, tgt=None, verbose=False)
> translator = build_translator(opt, report_score=False)
> translator.translate(['it kinda works'], batch_size=1)
> # ['▁Herr ▁Präsident !']
> ```
> 
> The problem is that the translation looks wrong but I will open another issue for that.


Running the code, results in the error `AttributeError: 'Namespace' object has no attribute 'tgt_prefix'`

**Comment by cucbui57** [comment]
> > ```
> > from onmt.translate.translator import build_translator
> > from argparse import Namespace
> > 
> > path = 'averaged-10-epoch.pt'
> > opt = Namespace(alpha=0.0, batch_type='sents', beam_size=5, beta=-0.0, block_ngram_repeat=0, coverage_penalty='none', data_type='text', dump_beam='', fp32=False, gpu=-1, ignore_when_blocking=[], length_penalty='none', max_length=100, max_sent_length=None, min_length=0, models=['openmnt/averaged-10-epoch.pt'], n_best=1, output='/dev/null', phrase_table='', random_sampling_temp=1.0, random_sampling_topk=1, ratio=-0.0, replace_unk=False, report_align=False, report_time=False, seed=829, stepwise_penalty=False, tgt=None, verbose=False)
> > translator = build_translator(opt, report_score=False)
> > translator.translate(['it kinda works'], batch_size=1)
> > # ['▁Herr ▁Präsident !']
> > ```
> > 
> > 
> > The problem is that the translation looks wrong but I will open another issue for that.
> 
> Running the code, results in the error `AttributeError: 'Namespace' object has no attribute 'tgt_prefix'`

You should add 'tgt_prefix=False' in your opt variable

**Comment by abdullahkhilji** [comment]
Thanks @cucbui57, it worked!

**Comment by GurjotTatras** [comment]
> You're not passing the right arguments to the function. It takes your dict `{"reuse_copy_attn":False}` as a model_path.
> 
> https://github.com/OpenNMT/OpenNMT-py/blob/a4b800d1fa12d23651902df9c3d537944b2e7f75/onmt/model_builder.py#L91-L114

I'm getting Attribute error when I'm loading my own trained model using this code-

AttributeError: 'Namespace' object has no attribute 'int8'
