### ISSUE TITLE
Pretrained english->german model giving wrong predictions

### ISSUE THREAD

**Issue by elyase** [OpenNMT/OpenNMT-py#1760]
When I try the English German transformer model from [here](https://opennmt.net/Models-py/):

```
from onmt.translate.translator import build_translator
from argparse import Namespace


opt = Namespace(models=['averaged-10-epoch.pt'], n_best=1, alpha=0.0, batch_type='sents', beam_size=5, beta=-0.0, block_ngram_repeat=0, coverage_penalty='none', data_type='text', dump_beam='', fp32=False, gpu=-1, ignore_when_blocking=[], length_penalty='none', max_length=100, max_sent_length=None, min_length=0, output='/dev/null', phrase_table='', random_sampling_temp=1.0, random_sampling_topk=1, ratio=-0.0, replace_unk=False, report_align=False, report_time=False, seed=829, stepwise_penalty=False, tgt=None, verbose=False)
translator = build_translator(opt, report_score=False)
translator.translate(['it doesnt work', 'and I dont know why', "so please help me"], batch_size=1)
```

I get meaningless output like:

`[['▁Herr ▁Kolleg e !'], ['▁Und ▁ich ▁bin ▁nicht ▁ganz ▁sicher .'], ['▁Herr ▁Kolleg e !']]
`
What am I doing wrong?

**Comment by elyase** [comment]
it looks like I need to sentencepiece the sentence before passing it to the translator. Working code:
```
from onmt.translate.translator import build_translator
from argparse import Namespace
import sentencepiece as spm

tokenizer = spm.SentencePieceProcessor()
tokenizer.Load('openmnt/sentencepiece.model')
opt = Namespace(models=['openmnt/averaged-10-epoch.pt'], n_best=1, alpha=0.0, batch_type='sents', beam_size=5, beta=-0.0, block_ngram_repeat=0, coverage_penalty='none', data_type='text', dump_beam='', fp32=False, gpu=-1, ignore_when_blocking=[], length_penalty='none', max_length=100, max_sent_length=None, min_length=0, output='/dev/null', phrase_table='', random_sampling_temp=1.0, random_sampling_topk=1, ratio=-0.0, replace_unk=False, report_align=False, report_time=False, seed=829, stepwise_penalty=False, tgt=None, verbose=False)
translator = build_translator(opt, report_score=False)

sentence = 'it works!'
tokens = tokenizer.EncodeAsPieces(sentence)
sentence = " ".join(tokens)
translated = translator.translate([sentence], batch_size=1)
detokenized = translated[1][0][0].replace('▁', '')
print(detokenized)
#es funktioniert !
```

Detokenization can probably be improved. It would be great to add this to the docs somewhere.

**Comment by kgarg8** [comment]
I had to update opt to :

`opt = Namespace(models=['transformer-ende-wmt-pyOnmt/averaged-10-epoch.pt'], n_best=1, alpha=0.0, batch_type='sents', beam_size=5, beta=-0.0, block_ngram_repeat=0, coverage_penalty='none', data_type='text', dump_beam='', fp32=False, gpu=-1, ignore_when_blocking=[], length_penalty='none', max_length=100, max_sent_length=None, min_length=0, output='/dev/null', phrase_table='', random_sampling_temp=1.0, random_sampling_topk=1, ratio=-0.0, replace_unk=False, report_align=False, report_time=False, seed=829, stepwise_penalty=False, tgt=None, verbose=False, int8=False, random_sampling_topp=0, ban_unk_token=False, tgt_prefix=False)`
