### ISSUE TITLE
configuration for pre-trained model

### ISSUE THREAD

**Issue by ziyanyang** [OpenNMT/OpenNMT-py#1765]
Hi,

I found the pre-trained model German-English - 2-layer BiLSTM here https://opennmt.net/Models-py/. Could you provide the specific training options for this model? 

Thanks!

**Comment by francoishernandez** [comment]
Hi,
You can access all the options of the model by loading it with
```python
import torch
model = torch.load(<model_path.pt>)
```
There you will have a dict, of which one of the keys should be `'opt'`.
