### ISSUE TITLE
-withAttn 

### ISSUE THREAD

**Issue by sdlmw** [OpenNMT/OpenNMT-py#1766]
Hi guys,

 Does OpenNMT-py also support attention tables? It's like the inside of the lua version - withattn parameter.

thanks

**Comment by francoishernandez** [comment]
Hey,
Would you mind elaborating a bit on what you mean?
Maybe linked to [this](https://forum.opennmt.net/t/how-can-i-get-some-hidden-states-of-model-such-as-self-attention-matrix-during-translation/3553/3)?

**Comment by sdlmw** [comment]
Hi  @francoishernandez 
It's like a set of numbers in the picture below. In the opennmt-lua version, it can get it with -withAttn
![image](https://user-images.githubusercontent.com/13164077/78318301-f853b100-7596-11ea-87b6-9ae48d5fc9c9.png)

**Comment by francoishernandez** [comment]
There is no flag available for that. Attention matrices are fairly accessible via the API though. 
Feel free to PR if you want.
