### ISSUE TITLE
Issue with Example Preprocessing

### ISSUE THREAD

**Issue by JustCunn** [OpenNMT/OpenNMT-py#1771]
I've recently just installed OpenNMT-py on Linux Ubuntu in a virtual environment. It installed smoothly and went to try out the first example given at https://opennmt.net/OpenNMT-py/quickstart.html . It's about preprocessing the data. So I type in what it tells me to:

`onmt_preprocess -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo`

But I get this error returned:

`Traceback (most recent call last):
  File "/home/justin/open-nmt-test/bin/onmt_preprocess", line 11, in <module>
    sys.exit(main())
  File "/home/justin/open-nmt-test/lib/python3.6/site-packages/onmt/bin/preprocess.py", line 298, in main
    preprocess(opt)
  File "/home/justin/open-nmt-test/lib/python3.6/site-packages/onmt/bin/preprocess.py", line 246, in preprocess
    ArgumentParser.validate_preprocess_args(opt)
  File "/home/justin/open-nmt-test/lib/python3.6/site-packages/onmt/utils/parse.py", line 144, in validate_preprocess_args
    assert os.path.isfile(file), "Please check path of %s" % file
AssertionError: Please check path of data/src-train.txt`

I have no idea why this happens. Do I need to installing the data beforehand? Was it not installed when I initially installed OpenNMT-py?

For reference:
OS: Linux-Ubuntu 18.04
OpenNMT-py updated to latest
PyTorch: 1.4.0+cpu

**Comment by francoishernandez** [comment]
The paths are relative to the git repo. You need to clone it if you want to try out the commands with the toy data.

**Comment by JustCunn** [comment]
Thank you very much! Working perfectly now.
