### ISSUE TITLE
vocabulary size mismatching 

### ISSUE THREAD

**Issue by ziyanyang** [OpenNMT/OpenNMT-py#1772]
Hi,

Currently I'm checking again the German-English pre-trained model in https://opennmt.net/Models-py/, and feel confused about the tokenization method. Before preprocessing the tokenized data, https://forum.opennmt.net/t/preprocessing-for-running-german-english-bilstm-pretrained-model/3339 this thread mentioned to use https://github.com/pytorch/fairseq/blob/e734b0fa58fcf02ded15c236289b3bd61c4cffdf/data/prepare-iwslt14.sh this script to get the data. I run this script and then run preprocess method(python preprocess.py -train_src data/iwslt14.tokenized.de-en/train.de -train_tgt data/iwslt14.tokenized.de-en/train.en -valid_src data/iwslt14.tokenized.de-en/valid.de -valid_tgt data/iwslt14.tokenized.de-en/valid.en -save_data data/iwslt14.tokenized.de-en/iwslt14.atok), and the English vocabulary size is >50000(because of the max limit). However, in the pre-trained model's vocabulary, the English's vocab size is 24725. 

I actually check the pre-trained model's vocab by printing
len(vocab['tgt'].fields[0][1].vocab)
len(vocab['tgt'].fields[0][1].vocab.stoi)
len(vocab['tgt'].fields[0][1].vocab.itos)
and get 24725, 53284 and 54188. Thus, how could I re-produce the vocabulary=24725? Actually I found another script from fairseq(https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-iwslt14.sh) applying BPE preprocessing, and does the pre-trained model actually use similar pre-processing method?

Thanks!

**Comment by francoishernandez** [comment]
I think that's linked to #1453.
IIRC there are some situations where OOV tokens are mapped to the "<unk>" id, hence polluting the vocab.

**Comment by ziyanyang** [comment]
> I think that's linked to #1453.
> IIRC there are some situations where OOV tokens are mapped to the "" id, hence polluting the vocab.

I see. This explains why len(vocab['tgt'].fields[0][1].vocab) and len(vocab['tgt'].fields[0][1].vocab.stoi) have different length because when the pre-trained model is created, such issue is not solved. 

However, I still don't know how to reproduce pre-trained model's vocab with 24725 words. As I mentioned, if I preprocess the iwslt14 data now, I will get vocabulary with more than 50000 words.

**Comment by vince62s** [comment]
it's because using sentence piece you can set the vocab size
look here: https://github.com/OpenNMT/OpenNMT-tf/blob/master/scripts/wmt/prepare_data.sh
