### ISSUE TITLE
Error not showing in log_file

### ISSUE THREAD

**Issue by Binteislam** [OpenNMT/OpenNMT-py#1773]
I am using OpenNMT-py to built NMT systems but checkpoints beyond 500 are not being saved for some experiments. Training runs till 1000 but checkpoints are not being saved. Whereas for some other experiments checkpoints gets saved with the same experimental setup. Kindly help to resolve this problem.

**Comment by francoishernandez** [comment]
Hey @Binteislam 
You'll probably need to give a bit more details. What are the commands you execute in each case?

**Comment by Binteislam** [comment]
The following command for each case. 

python train.py -data $svdir/$name -batch_size=128 -train_steps 15000 -save_checkpoint_steps 5000 -save_model  $mdir/$name --global_attention mlp -optim adam  -world_size=1 -gpu_ranks=0 -log_file $bdir/log.$name -learning_rate 0.001  -tensorboard -tensorboard_log_dir $tnsrdir

**Comment by francoishernandez** [comment]
`-save_checkpoint_steps 5000` --> this means you save every 5000 steps

**Comment by Binteislam** [comment]
Yes, and sorry for the typo in the question. The first checkpoint after 5000 steps is saved. The job runs further till 10000 but doesn't save the checkpoint and exits after this.

**Comment by francoishernandez** [comment]
Oh

**Comment by Binteislam** [comment]
Yes, this is a strange behavior, I rechecked data issues, tried different machines but am not able to figure out what is specifically causing this.

These are the last lines in the log file:

[2020-03-30 12:01:01,103 INFO] Step 9950/15000; acc:  64.85; ppl:  7.85; xent: 2.06; lr: 0.00100; 34445/23464 tok/s;    441 sec
[2020-03-30 12:01:05,081 INFO] Step 10000/15000; acc:  62.62; ppl:  8.72; xent: 2.17; lr: 0.00100; 33080/22958 tok/s;    445 sec
[2020-03-30 12:01:05,083 INFO] Loading dataset from /home/mt-jobs/jobs-en/nw-wi-os_en-128/savedata_dir/nw-wi-os_en-128.valid.0.pt
[2020-03-30 12:01:09,611 INFO] number of examples: 118739

**Comment by francoishernandez** [comment]
I'm wondering whether there may be some errors that are not properly written to the log file. Would you mind running this again without writing to log file and see if there are more info in the shell?

**Comment by Binteislam** [comment]
Thank you. It was empty line in the corpus.

Would have been helpful if the log file had the error log too.
