### ISSUE TITLE
Copy Mechanism Visualization

### ISSUE THREAD

**Issue by mahimanzum** [OpenNMT/OpenNMT-py#1777]
Is there any way to identify the tokens that were generated from copy mechanism during ONMT translate? i am currently using -attn_debug flag but that just gives me the attention weights not any information relevant to copy mechanism.

**Comment by francoishernandez** [comment]
@pltrdy might have an idea here.

**Comment by mahimanzum** [comment]
anything related to this is helpful. please share.

**Comment by pltrdy** [comment]
@mahimanzum sorry, didnt checked github notifs for a while.

There's no option to do it directly in OpenNMT-py, it would require a bit of tweaks.

First, the attention weights are relevant to understand the copy mechanism as it define, **what** is going to be copied.
Then, the model calculate a copy weight, that is a soft-switch between copy/generation mode. You can find it at <https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/copy_generator.py#L123>.

In particular, a model with a high `p_copy` would be mostly extractive, thus, the final word probability distribution would be ~= the attention.

Hope it helps. Do not hesitate to ask for any other concern.
