### ISSUE TITLE
Translate by giving a sentence as input

### ISSUE THREAD

**Issue by aastha19** [OpenNMT/OpenNMT-py#1780]
Hi

The basic translate command is as follows:
python translate.py -model demo-model_XYZ.pt -src data/src-test.txt -output pred.txt -replace_unk -verbose
where src-test.txt has the sentences to translate and pred.txt stores them

Is it possible that rather than having sentences written in a file, we give a sentence on runtime and display the generated output.

**Comment by francoishernandez** [comment]
This is not implemented yet, but should not be too hard. If you want to make a PR for such an addition we'd gladly merge it.
