### ISSUE TITLE
Training two models on 8 GPUs, 4 each

### ISSUE THREAD

**Issue by ymoslem** [OpenNMT/OpenNMT-py#1781]
Hello!

I have a machine with 8 GPUs. I am using 4 GPUs to train the first model. I cannot start the training of the second model on the remaining GPUs.

Here are the settings I tried to run the second model (note the first model is running on another "screen" on GPUs 0,1,2,3). I tried four changes:

### 1st Change:

CUDA_VISIBLE_DEVICES=4,5,6,7
-world_size 4
-gpu_ranks 0 1 2 3

Will not start
RuntimeError: Address already in use

--------------------------------------

### 2nd Change:

CUDA_VISIBLE_DEVICES=4,5,6,7
-world_size 4
-gpu_ranks 4 5 6 7

Will not start
AssertionError: -gpu_ranks should have master(=0) rank unless -world_size is greater than len(gpu_ranks).

--------------------------------------

### 3rd Change:

CUDA_VISIBLE_DEVICES=4,5,6,7 (note the first 4 GPUs are already visible)
-world_size 8
-gpu_ranks 4 5 6 7

Will start “Loading dataset…” with an error.

```
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/work/OpenNMT-py/train.py", line 148, in run
    error_queue.put((opt.gpu_ranks[device_id], traceback.format_exc()))
KeyboardInterrupt
Traceback (most recent call last):
  File "../../OpenNMT-py/train.py", line 200, in <module>
    main(opt)
  File "../../OpenNMT-py/train.py", line 82, in main
    p.join()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 121, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "../../OpenNMT-py/train.py", line 184, in signal_handler
    raise Exception(msg)
Exception: 

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/home/ubuntu/work/OpenNMT-py/train.py", line 142, in run
    single_main(opt, device_id, batch_queue, semaphore)
  File "/home/ubuntu/work/OpenNMT-py/onmt/train_single.py", line 139, in main
    valid_steps=opt.valid_steps)
  File "/home/ubuntu/work/OpenNMT-py/onmt/trainer.py", line 239, in train
    (normalization))
  File "/home/ubuntu/work/OpenNMT-py/onmt/utils/distributed.py", line 112, in all_gather_list
    torch.distributed.all_gather(out_buffers, in_buffer.cuda())
  File "/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py", line 1098, in all_gather
    work = _default_pg.allgather([tensor_list], [tensor])
```

--------------------------------------

### 4th Change:

In train.py I changed `if x[0] % opt.world_size  == rank` which is 8 here to `nb_gpu` which is 4 here in the following code:

```
def batch_producer(generator_to_serve, queues, semaphore, opt):
    init_logger(opt.log_file)
    set_random_seed(opt.seed, False)   
    # generator_to_serve = iter(generator_to_serve)

    def pred(x):
        """
        Filters batches that belong only
        to gpu_ranks of current node
        """
        nb_gpu = len(opt.gpu_ranks)

        for rank in opt.gpu_ranks:
            if x[0] % nb_gpu == rank:
                return True
```

This makes the training start; however, it keeps "loading dataset *.0" and then "loading dataset *.1", etc.

So I am not sure what to do to be able to run the training of the second model on the unused 4 GPUs.

Thanks for your help!

**Comment by vince62s** [comment]
Yasmine,
what did you do for the first training ?
it shouldbe
1st: cuda_visible_devices=0,1,2,3 (and not 1 2 3 4 as in your post)
world_size 4
gpu_ranks 0 1 2 3

2nd: cuda_visible_devices=4,5,6,7
world_size=4
gpu_ranks 0 1 2 3

**Comment by ymoslem** [comment]
Hi Vincent!

Thanks for your reply.

My post was wrong. I am now copying what I have from my command. For the first training, I have:

CUDA_VISIBLE_DEVICES=0,1,2,3
-world_size 4
-gpu_ranks 0 1 2 3


If for the 2nd model, if I have this:
CUDA_VISIBLE_DEVICES=4,5,6,7
world_size=4
gpu_ranks 0 1 2 3

I get an error message "RuntimeError: Address already in use" and this makes sense because now all the 8 GPUs are visible: 4 for the first training and 4 for the second training, are not they?

Many thanks!

**Comment by francoishernandez** [comment]
You need to change the `-master_port`. This is link to torch.distributed stuff to run on multiple nodes.

**Comment by ymoslem** [comment]
Many thanks, François!

Now the second training works as follows:
CUDA_VISIBLE_DEVICES=4,5,6,7
-world_size 4
-gpu_ranks 0 1 2 3
-master_port 3000
