### ISSUE TITLE
how to add new data to a trained model in image to latex

### ISSUE THREAD

**Issue by dishan14** [OpenNMT/OpenNMT-py#1782]
how to train a model on a data and just add it to the previously trained model in im2text (image to latex conversion)

**Comment by francoishernandez** [comment]
You're probably looking for the `-train_from` flag.
Training on only the new data not might be the best though, as it may cause catastrophic forgetting and other negative side effects.

**Comment by dishan14** [comment]
thanks for the reply, i am not suggesting to train only on new data but how to train the model on new data including the old data without starting training from scratch

**Comment by francoishernandez** [comment]
Then you need to preprocess your new data with the same vocab as your existing data (pass your existing `<your_dataset_name>.vocab.pt` to `-src_vocab`). And use the `-train_from` flag to start from the existing checkpoint.

**Comment by dishan14** [comment]
should i use train_from  flag in the training command and could the example value be 'demo-model_step_40000.pt' ?

**Comment by francoishernandez** [comment]
Yes.

**Comment by dishan14** [comment]
> Then you need to preprocess your new data with the same vocab as your existing data (pass your existing `<your_dataset_name>.vocab.pt` to `-src_vocab`). And use the `-train_from` flag to start from the existing checkpoint.

it is asking for overwrite option  in preprocessing step ,should i overwrite it?

**Comment by francoishernandez** [comment]
Depends if you want to overwrite the existing shards or not. Can't really know without knowing your exact setup and what you're trying to achieve.
Also, you may want to have a look at the `-data_ids` (and later `-train_ids`) flag(s) if you want to handle data from different sources.
