### ISSUE TITLE
what type of preprocessing should be applied on camera captured images

### ISSUE THREAD

**Issue by dishan14** [OpenNMT/OpenNMT-py#1783]
what type of preprocessing should be applied on camera captured images for image to latex translation .
Model is able to translate images from CROHME dataset (which were not present in the training data) but when i test it with camera captured images it produces <unk> tag or wrong result

**Comment by francoishernandez** [comment]
You may start from [there](https://opennmt.net/OpenNMT-py/im2text.html).
Some comments in #1417 may be useful as well.

**Comment by dishan14** [comment]
i am testing the images captured from camera then also will the procedure be the [https://opennmt.net/OpenNMT-py/im2text.html](same) as mentioned

**Comment by dishan14** [comment]
[this](https://opennmt.net/OpenNMT-py/im2text.html)

**Comment by dishan14** [comment]
thanks for the help
