### ISSUE TITLE
Transformers link not working.

### ISSUE THREAD

**Issue by arshadshk** [OpenNMT/OpenNMT-py#1789]
http://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-the-transformer-model

The above link present on https://github.com/OpenNMT/OpenNMT-py  in Feature section as "Transformer models" is not working.

**Comment by francoishernandez** [comment]
Indeed it looks like the docs are broken. Having a look into it.

**Comment by francoishernandez** [comment]
Should be better now. Thanks for reporting!
