### ISSUE TITLE
Coverage in Global attention

### ISSUE THREAD

**Issue by atsb1372** [OpenNMT/OpenNMT-py#179]
When using the Global attention without transformer RNN,  we have :
https://github.com/OpenNMT/OpenNMT-py/blob/3f6c9a2a6d9751a1c5000df9d2497084974d6c25/onmt/Models.py#L357

You are not passing the coverage to the global attention so it is always None. Does the -coverage_attn option work?

**Comment by srush** [comment]
We have yet to replicate the results with`coverage_attn` . Consider that feature off at the moment (we are actively working on it).
