### ISSUE TITLE
ModuleNotFoundError: No module named 'onmt.inputters'

### ISSUE THREAD

**Issue by Roweida-Mohammed** [OpenNMT/OpenNMT-py#1802]
hello :)
When I use the python train_mm.py it gave me this error

Traceback (most recent call last):
File "train_mm.py", line 448, in
main()
File "train_mm.py", line 423, in main
first_dataset = next(lazily_load_dataset("train"))
File "train_mm.py", line 314, in lazily_load_dataset
yield lazy_dataset_loader(pt, corpus_type)
File "train_mm.py", line 305, in lazy_dataset_loader
dataset = torch.load(pt_file)
File "C:\Users\user\Anaconda3\envs\thesis1\lib\site-packages\torch\serialization.py", line 358, in load
return _load(f, map_location, pickle_module)
File "C:\Users\user\Anaconda3\envs\thesis1\lib\site-packages\torch\serialization.py", line 542, in _load
result = unpickler.load()
ModuleNotFoundError: No module named 'onmt.inputters'

**Comment by francoishernandez** [comment]
Not sure what you're talking about, there is no such `train_mm.py` in this repository, only `train.py`.

Anyways, it's probably just a PYTHONPATH issue. Make sure you have the folder containing `onmt` in your path when executing your script.

**Comment by Roweida-Mohammed** [comment]
I used the MultimodalNMT, before 3 months it worked fine and when today to used it again it gave me the above error I don't know why

[https://github.com/iacercalixto/MultimodalNMT](url)

**Comment by francoishernandez** [comment]
This fork looks like it's based on a very old version. Can't be of much more help here.
Did you check your path is properly set?

**Comment by Roweida-Mohammed** [comment]
yes the path is properly set

**Comment by francoishernandez** [comment]
This seems totally off. It's trying to load `onmt.inputters` which does not exist (`onmt.io` in the old version this fork is based).

If it worked fine a few months back, you can probably go back to an old commit.

Closing this issue as it belongs on the fork, not here. This fork is not part of the OpenNMT project.
