### ISSUE TITLE
Logger is not passed to translator

### ISSUE THREAD

**Issue by marcelgwerder** [OpenNMT/OpenNMT-py#1804]
When building the translator, there is a logger created but not passed to the translator:
https://github.com/OpenNMT/OpenNMT-py/blob/35cf4f0ae774a4aa500318879a1a4d53408ac129/onmt/bin/translate.py#L18
This results in a log file that only contains a single entry:
https://github.com/OpenNMT/OpenNMT-py/blob/35cf4f0ae774a4aa500318879a1a4d53408ac129/onmt/bin/translate.py#L24

**Comment by francoishernandez** [comment]
Indeed. You can PR a fix if you want.

**Comment by marcelgwerder** [comment]
> Indeed. You can PR a fix if you want.

Yeah, I just submitted one
