### ISSUE TITLE
Retrieve NMT Encoder's output 

### ISSUE THREAD

**Issue by brash6** [OpenNMT/OpenNMT-py#1811]
Hi, 

Assuming that I've trained a NMT with OpenNMT, how coud I retrieve the representation vector of new sequences ? 

More precisely, If I trained a NMT to translate from French to English, if I want to predict the output sequence for a new French sentence, how could I also retrieve the output vector of the encoder ? 

Thank you !

**Comment by francoishernandez** [comment]
Hi there,
This is quite similar to this [post](https://forum.opennmt.net/t/how-can-i-get-some-hidden-states-of-model-such-as-self-attention-matrix-during-translation/3553).
It is not handled "as is" but it should not be too difficult to add it if you're willing to dive a bit in the code.

**Comment by brash6** [comment]
Thank you for your answer, I'll post here If I manage to do it !

**Comment by Marvinmw** [comment]
hi, do you manage to do it? @brash6

**Comment by brash6** [comment]
Hello, not really, If you have any idea how to do it, I am interested !

**Comment by shashankg7** [comment]
Hi, 

Did anybody had any success in getting the encoder representation from the trained model?

**Comment by francoishernandez** [comment]
This should not be very difficult guys, if you're willing to dive a bit in the code.
You can start by printing / torch.save what's happening here, after the encoder forward:
https://github.com/OpenNMT/OpenNMT-py/blob/8b073fb2a047509ff590839b1194a155ec1a50bf/onmt/models/model.py#L45

Then, it's just plumbing to retrieve this at the translator level.

**Comment by shashankg7** [comment]
Thanks for your reply.

I have mainly used it's command line tool only. Have not used the torch
api. Any reference to building a transformer translation model with its
pytorch api?

Pardon if I am missing anything obvious here.

**Comment by francoishernandez** [comment]
You don't need to rebuild everything just to retrieve some representations.
You can just edit the code and run the scripts.

**Comment by shashankg7** [comment]
Thank you for your prompt response. 

I have one more doubt. Please pardon me if my doubts appear naive. 

The installed scripts will invoke the code from the installed location, right? 

How do I ensure that the scripts call the changes I make in the onmt codebases' model?

**Comment by francoishernandez** [comment]
Easiest is probably to `git clone`the repo in the location you'd like and work from there.

**Comment by shashankg7** [comment]
Thanks. I started with the codebase, and was able to run the model with train.py and translate.py files. 

However, given a raw src text file, I am not sure how to get the encoder representations aligned with the ordering of src sentences.

**Comment by Shikhar-S** [comment]
Hi @francoishernandez! Is anyone working on this issue? I want to contribute.
