### ISSUE TITLE
Rest server pre-processing

### ISSUE THREAD

**Issue by IchoKatsarski** [OpenNMT/OpenNMT-py#1813]
Hi, 

Can you please update the documentation for the REST server. In my configuration I use a simple script for pre-processing. It used to receive a string and return a string. I updated to the latest version opennmt-py and now It seems to me that I have to wrap my sentences in a dictionary. Maybe I'm not using it in the correct way anymore. Whats the right way to use pre-processing?
Hope you can shed light on this.

**Comment by francoishernandez** [comment]
Hi there,
You are probably referring to the change introduced in #1745 .
Basically if you don't want to make any change to your existing function, you should be able to use a wrapper like the one in `onmt.translate.process_zh`:

https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/process_zh.py#L6-L13
