### ISSUE TITLE
the parameters of the machine translation experiment,especially the word vector,have not been compared in different dimensions please how to compared anybody help me to give answer of this question

### ISSUE THREAD

**Issue by zeeshan649** [OpenNMT/OpenNMT-py#1814]
i compare LSTM MODEL and TRANSFORMER MODEL.for LSTM i use default setting while for transformer i change parameters ?the reviewer ask this question but i am confuse how to give answer.

**Comment by francoishernandez** [comment]
Hi there,
I am not sure to understand what you are asking. Also, it seems this kind of discussion would rather belong on the [forum](https://forum.opennmt.net) than in the github issues.
