### ISSUE TITLE
translate.py bugs

### ISSUE THREAD

**Issue by StevenLOL** [OpenNMT/OpenNMT-py#182]
## AttributeError: 'module' object has no attribute 'Markdown'
python translate.py -gpu 0 -model ./demo-model_acc_xxxx_e11.pt -src data/src-val.txt -output pred.txt -replace_unk -verbose
```
Traceback (most recent call last):
  File "translate.py", line 14, in <module>
    onmt.Markdown.add_md_help_argument(parser)
AttributeError: 'module' object has no attribute 'Markdown'
python: can't open file 'score_it.py': [Errno 2] No such file or directory
```

## 'ascii' codec can't encode character u'\xe4' in position 5: ordinal not in range(128)

python translate.py -gpu 0 -model ./demo-model_acc_xxxx_e11.pt -src data/src-val.txt -output pred.txt -replace_unk -verbose

```
SENT 1: Parliament Does Not Support Amendment <unk> <unk>
33

 PRED 1: Die Kommission ist nicht wichtig . ist es nicht . ist es nicht . ist es nicht . ist es nicht . ist es nicht . ist es nicht . ist es nicht
PRED SCORE: -60.3104
Traceback (most recent call last):
  File "translate.py", line 165, in <module>
    main()
  File "translate.py", line 108, in main
    for i in predBatch[b][0]]) + '\n')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 5: ordinal not in range(128)

```

## bug 3: translate.py fail to reproduce val score on val data.

Python 2.7 , tested on the latest code base. ubuntu 16.04

**Comment by srush** [comment]
First is fixed. Looking into the second two. 

For bug 3, what do you mean precisely?

**Comment by StevenLOL** [comment]
### More info for  'ascii' codec can't encode character u'\xe4' in position 5: ordinal not in range(128)


Loading model
predBatch[b][0]] [u'Die', u'Kommission', u'ist', u'nicht', u'wichtig', u'.', u'ist', u'es', u'nicht', u'.', u'ist', u'es', u'nicht', u'.', u'ist', u'es', u'nicht', u'.', u'ist', u'es', u'nicht', u'.', u'ist', u'es', u'nicht', u'.', u'ist', u'es', u'nicht', u'.', u'ist', u'es', u'nicht']

SENT 1: Parliament Does Not Support Amendment <unk> <unk>

PRED 1: Die Kommission ist nicht wichtig . ist es nicht . ist es nicht . ist es nicht . ist es nicht . ist es nicht . ist es nicht . ist es nicht

PRED SCORE: -60.3104

predBatch[b][0]] [u'Die', u'Kommission', u'hat', u'sich', u'in', u'der', u'Lage', u',', u'dass', u'die', u'Europ\xe4ische', u'Union', u'in', u'der', u'Europ\xe4ischen', u'Union', u',', u'die', u'im', u'Rahmen', u'der', u'Europ\xe4ischen', u'Union', u',', u'die', u'im', u'Rahmen', u'der', **u'Europ\xe4ischen'**, u'Union', u',', u'die', u'in', u'der', u'Lage', u',', u'die', u'in', u'der', u'Lage']

Traceback (most recent call last):
  File "translate.py", line 166, in <module>
    main()
  File "translate.py", line 109, in main
    for i in predBatch[b][0]]) + '\n')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 5: ordinal not in range(128)
```

**Comment by StevenLOL** [comment]
For the third problem :

The validation acc is 22.88 , but if I generate the output via translate.py , I can't  get an acc of 22.88.

Some output samples:
```
Val index= 2991
ref:		In Anbetracht des Hinspiels (0-0) am Freitag in der Hölle von Zenica scheint es offenkundig , dass die Würfel noch nicht gefallen sind .
predict:	Im Rahmen der Europäischen Union hat die Möglichkeit , dass die Europäische Union in der Europäischen Union in der Europäischen Union in der Europäischen Union in der Europäischen Union in der Europäischen Union . gibt es die Möglichkeit . gibt es die Möglichkeit . gibt es die Möglichkeit . gibt es
Val index= 2992
ref:		Portugal dominierte über mehr als eine Stunde klar die Partie , aber die Mannschaft war nicht imstande , der Sache den so wichtigen Stempel aufzudrücken , der den Druck von ihr genommen hätte .
predict:	Wir haben die Frage , dass die Europäische Union nicht mehr als auch in der Lage ist , und es wird nicht auf die Zukunft . ist es nicht . ist es . ist es nicht . ist es nicht . ist es . ist es nicht .
Val index= 2993
ref:		&quot; Das ist ein gutes Ergebnis , das jedoch ein gewisses Risiko birgt , da wir kein Auswärtstor erzielt haben &quot; .
predict:	Es ist nicht einfach , dass es sich in der Lage ist . ist es nicht einfach . ist es nicht einfach . ist es nicht einfach . ist es nicht einfach . ist es nicht einfach . ist es nicht einfach . ist es nicht einfach
Val index= 2994
ref:		Zuhause jedoch , in ihrem hell erstrahlenden Stade de la Luz in Lissabon , sind die Portugiesen davon überzeugt , sich vor einem Publikum , das ebenso heiβ auf das Spiel sein dürfte , durchzuschlagen , selbst wenn die Partie natürlich als &quot; sehr knapp &quot; angekündigt wurde , sagte der optimistische , jedoch klarsichtige Bento .
predict:	Doch wenn es sich in den letzten zehn Jahren nicht mehr als auch in der Ukraine , die im Hinblick auf die Zukunft , die sich in der Lage , die im Rahmen der Europäischen Union , die im Rahmen der Europäischen Union , die in der Lage , die sich in der Ukraine
Val index= 2995
ref:		&quot; Wir erwarten ein sehr knappes Match , sind jedoch vollkommen davon überzeugt , die Oberhand gewinnen zu können &quot; , erklärte der 42-jährige portugiesische Trainer .
predict:	Wir haben uns nicht , dass wir uns in der Lage , und wir haben uns nicht , dass wir uns in diesem Bereich nicht akzeptieren können . ist es nicht . werden wir uns nicht . werden wir uns nicht . sind wir nicht . sind wir nicht
Val index= 2996
ref:		&quot; Wir haben weiterhin eine 50% -ige Chance bei der Europameisterschaft 2012 dabei zu sein &quot; , relativierte jedoch der Nachfolger von Carlos Queiroz .
predict:	Wir haben auch die Möglichkeit , dass die Kommission die Möglichkeit , die sich in der Lage in der Ukraine , die im Rahmen der Europäischen Union . gibt es auch nicht . ... ... ... ... ... ... ... ... ... ...
Val index= 2997
ref:		Das Unentschieden am Freitag in Bosnien zwingt die Portugiesen dazu , ein Tor zu erzielen und zu gewinnen .
predict:	Die Kommission ist ein sehr sehr gut . ist ein Teil der Stadt . ist es . ist eine sehr gute Partnerschaft . ist das Ergebnis der Stadt . ist das Ergebnis der Stadt . ist das Ergebnis der Stadt . ist das Ergebnis der Stadt .
Val index= 2998
ref:		Ein Unentschieden kann den Bosniern , die ebenfalls ein Tor nötig haben , bereits genügen .
predict:	Ein Beispiel in der Lage wird nicht einfach . gibt es eine Kreditkarte . gibt es eine Kreditkarte . gibt es eine Kreditkarte . gibt es eine Kreditkarte . gibt es eine Kreditkarte . gibt es eine Kreditkarte . gibt es eine Kreditkarte . gibt es auch
Val index= 2999
ref:		&quot; Das ist ein gutes Ergebnis , das jedoch ein gewisses Risiko birgt , da wir kein Auswärtstor erzielt haben &quot; , bedauert Bento .
predict:	Es ist nicht einfach , dass es sich in der Ukraine , die in der Lage ist . ist es nicht einfach . ist es nicht . ... ... ... ... ... ... ... ... ... ... ... ...

```

**Comment by srush** [comment]
Thanks! I will fix the first ascii issue today. 

For the second, I think there is some confusion. Validation accuracy of 22, means it has a 22% chance of predicting the next word correctly *when seeing the correct prefix* . This is very different than predicting a translation with 22% accuracy.

**Comment by StevenLOL** [comment]
En, I got a novice question, can the accuracy of the first word in the predicted sentences reach 22% ?

**Comment by srush** [comment]
Um, yeah in theory that might be true. However the first word tends to have a different distribution. In general it is quite hard to extrapolate from PPL final accuracy, although they are correlated. 

The other issues should now all be fixed.

**Comment by StevenLOL** [comment]
Thanks
