### ISSUE TITLE
Gated Graph Neural Network

### ISSUE THREAD

**Issue by Anurag-Swarnim-Yadav** [OpenNMT/OpenNMT-py#1820]
Hi, 

How I can pre-process input for gated graph neural network? If I have a file with the source code. How can I convert into the required input?

Thanks

**Comment by francoishernandez** [comment]
Hi there,
Did you see the example in the docs ? https://opennmt.net/OpenNMT-py/ggnn.html
Else, maybe @SteveKommrusch can be of some help.

**Comment by SteveKommrusch** [comment]
I'm working with Anurag by email; one way to create tree structures from code is to use ANTLR: https://www.antlr.org/. I will update the docs with more details after working directly with Anurag.

**Comment by Anurag-Swarnim-Yadav** [comment]
Hi @francoishernandez 

Thanks for replying and yes @SteveKommrusch is helping me a lot.

Thanks 
Anurag

**Comment by SteveKommrusch** [comment]
Working with Anurag I have created a more extensive example use case, including processing textual code tree output from ANTLR. I've added the details to the example GIT already linked mentioned in the ggnn.md document: https://github.com/SteveKommrusch/OpenNMT-py-ggnn-example .
