### ISSUE TITLE
Model with their working and use.

### ISSUE THREAD

**Issue by Kamesh-Mishra** [OpenNMT/OpenNMT-py#1821]
How to know which model is for image to text generation ,, actually i'm working with handwritten mathematical text expression recognization and want help from community. my email is kamesh.mishra20@gmail.com   
thanks in advance.

**Comment by francoishernandez** [comment]
You may want to start there : https://opennmt.net/OpenNMT-py/im2text.html
Also, if you have more general questions regarding the task rather than specific issues in the code, you should probably head to [the forum](https://forum.opennmt.net).
