### ISSUE TITLE
Why process killed and no one kills the process

### ISSUE THREAD

**Issue by xxyliuyang** [OpenNMT/OpenNMT-py#1824]
run with ：nohup sh run.sh&, and I am sure no one kills the process, This situation happens repeatedly。
`
run.sh: line 66: 777016 Killed                  CUDA_VISIBLE_DEVICES=$gpu python train.py`

**Comment by xxyliuyang** [comment]
I confirm that the program can be executed normally and 80,000 steps have been executed。

`[2020-07-04 15:41:57,821 INFO] Step 85700/300000; acc:  69.58; loss: 141.93; lr: 0.00100; 503 tok/s;  69798 sec
run.sh: line 66: 777016 Killed`

**Comment by francoishernandez** [comment]
Hey @xxyliuyang 
Not sure to understand this issue and whether you found a solution or not.
Please close the issue if it's no longer of use.
