### ISSUE TITLE
I have an error in preprocessing module 'OSError: [Errno 5] Input/output error' 

### ISSUE THREAD

**Issue by asha2785** [OpenNMT/OpenNMT-py#1833]

**Comment by francoishernandez** [comment]
You'll have to give more details if you want some help.
- command line
- full error trace

**Comment by asha2785** [comment]
@francoishernandez  thank you for the response.  I uploaded opennmt folder in google drive and trying do translation using opennmt in colab. when I execute "!onmt_preprocess -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo" this command it is showing above error.

**Comment by francoishernandez** [comment]
This is probably more of a colab issue than an OpenNMT one.
You can probably refer to this post on the forum: https://forum.opennmt.net/t/tutorial-for-opennmt-py-using-colab/2895

**Comment by rituparnakhaund** [comment]
same issue , can't solve
