### ISSUE TITLE
How to do Hyperparameter Optimization using OpenNMT. 

### ISSUE THREAD

**Issue by thilakshiK** [OpenNMT/OpenNMT-py#1840]
Hi, 

I want to know whether there are built-in methods in OpenNMT to optimize hyperparameters. Unfortunately, I didn't find any. 
 Ex: **Grid search, Random Search**.

**Comment by francoishernandez** [comment]
Indeed there are none. As most of the tasks performed with OpenNMT are quite compute intensive, you probably would not want to perform such extensive searches anyway.
There might be some new methods that would be more optimized and might be worth a look though. Feel free to PR if you want to implement something in that matter.

**Comment by thilakshiK** [comment]
Hi @francoishernandez  thank you for the reply. I would like to know how you tune your models when using OpenNMT. Do you tune manually or is there any other method?

**Comment by nashid** [comment]
@thilakshiK have you found a solution? For me, it looks like we need to do a manual hyperparameter search with a limited number of combinations. I would be interested to know what option you chose eventually. 

@francoishernandez, what do you recommend?
