### ISSUE TITLE
is there any reason that default=-3 for the alignment layer?

### ISSUE THREAD

**Issue by Sanghyuk-Choi** [OpenNMT/OpenNMT-py#1843]
https://github.com/OpenNMT/OpenNMT-py/blob/95aeefb4377617b94f94090d375eb8ae03dbd6c4/onmt/opts.py#L186

Original paper(https://arxiv.org/abs/1909.02074) says "penultimate layer naturally tend to learn
alignments and provide significantly better results compared to naively averaging across all layers"

but in this code, default value is -3 for the alignment layer.
is there any special reason?

**Comment by Zenglinxiao** [comment]
Hello,
Yes, indeed in the paper, the suggest layer is "penultimate layer". We should probably default the `-alignment_layer` to -2.
But in our preliminary experiment, we got the best performance with `-alignment_layer -3` using exactly the same procedure as described in the paper.
The difference comes from the architecture itself actually. In the paper, they do all the experiments with the original Transformer, but in OpenNMT-py and many other open-source libraries, the Transformer implementation is a so-called Pre-Norm style Transformer. This minor change improves training efficiency and model capacity. For more detail, you can refer to [Transformer Details Not Described in The Paper](https://tunz.kr/post/4) & [Deep Transformer](https://arxiv.org/abs/1906.01787).
