### ISSUE TITLE
Possible inaccuracies during beam search

### ISSUE THREAD

**Issue by pltrdy** [OpenNMT/OpenNMT-py#1844]
While working on unittest for https://github.com/OpenNMT/OpenNMT-py/pull/1829 I encountered weird behavior from the beam search which are unrelated to block ngram repeat.

I made a simple script quite similar to unittest to demonstrate it https://github.com/pltrdy/OpenNMT-py/blob/master/investigating_beam_search.py (you can just download the script and run it on master)

The idea is to only work with two tokens with:

At each timestep `i`:
            - token `repeat_idx`(default `47`) get a logprob of `repeat_logprob`(default `-0.2`)
            - token `repeat_idx+i` get `no_repeat_logprob`(default `-0.1`)
            - other tokens get `base_logprob`(default `-inf`)

At the first step there's only two choices: 47 and 48 so it make sense that only 2 beams has logprobs > -inf.
```
# 1rst step
Iteration (0): logprobs tensor([[-0.1000, -0.2000,    -inf,    -inf,    -inf]])
Iteration (0): seq tensor([[ 1, 48],
        [ 1, 47],
        [ 1,  3],
        [ 1,  1],
        [ 1,  4]])

```
In the second iteration, the first beam is following the optimal path, no problem. The second one is the second optimal, right. But then, we find tokens associated with `-inf` when the beam search should have found that `[1, 47, 49]` is better (actually same score than `[1, 48, 47]`
```
# 2nd step
Iteration (1): logprobs tensor([[-0.2000, -0.3000,    -inf,    -inf,    -inf]])
Iteration (1): seq tensor([[ 1, 48, 49],
        [ 1, 48, 47],
        [ 1, 48,  3],
        [ 1, 48,  1],
        [ 1, 48,  4]])
```

In fact, following iterations won't manage to create more diversity, and keep the 3 last beams with `-inf` probabilities which I don't really understand (and don't think that's how beam search should behave -- maybe am I wrong here).
```
# 6-th step
Iteration (6): logprobs tensor([[-0.7000, -0.8000,    -inf,    -inf,    -inf]])
Iteration (6): seq tensor([[ 1, 48, 49, 50, 51, 52, 53, 54],
        [ 1, 48, 49, 50, 51, 52, 53, 47],
        [ 1, 48, 49, 50, 51, 52, 53,  3],
        [ 1, 48, 49, 50, 51, 52, 53,  1],
        [ 1, 48, 49, 50, 51, 52, 53,  4]])
Iteration (6): indices tensor([[54, 47,  3,  1,  4]])
```

I'm not sure how much it interfere in real situations to be honest but it's probably not good.

**Comment by guillaumekln** [comment]
In your example, the top k predictions are all coming from the first beam, which makes it the only one being explored. So the observed behavior seems expected. Am I missing something else?

**Comment by pltrdy** [comment]
I may not understand beam search well, but in my understanding, the top-k predictions should *not* come from the first beam only, e.g. at step 2 the first beam is optimal with the two first results `[ 1, 48, 49]` and `[ 1, 48, 47]` but I would expect `[ 1, 47, 49]` to come third (ex aequo with the second actually) from the second beam of step 1. Then `[1, 47, 47]` as the top-4, from the second beam as well. The last isn't really relevant since it would lead to `-inf`.

**Comment by guillaumekln** [comment]
In the example there are comments which mention "beam 0" and "beam 1" but then you only set finite log probs to beam 0. Is this expected?

https://github.com/pltrdy/OpenNMT-py/blob/master/investigating_beam_search.py#L55-L66

If only beam 0 is making valid predictions (i.e. all elements in `topk(log_probs)` come from beam 0) then the other beams are not explored and it becomes the same as running greedy search.

**Comment by pltrdy** [comment]
Oh you're right my bad. No problem then, the beam search --and my understanding of beam search-- are ok. Only the reproduction isn't relevant. I've been used to this `0::beam_sz` while writing test but it's not relevant here.

Thanks for feedbacks anyway!
