### ISSUE TITLE
-replace_unk and -phrase_table not working to replace <unk> token

### ISSUE THREAD

**Issue by SoYoungCho** [OpenNMT/OpenNMT-py#1846]
Hello, I am using this source to translate Korean into English and built ```model.pt``` model to translate sentences.

We made ```phrase_table.txt``` file that looks like ```source_unk_example|||target_replacement_example``` .
and gave ```-replace_unk``` and ```-phrase_table txt_path``` as arguments when running ```translate.py```,

but the unknown source token we made in ```phrase_table.txt``` does not change into the corresponding target token.

How can I use these two arguments ```-replace_unk``` and ```-phrase_table``` to make unk token not appear?
Is this format below correct when trying to replace multiple unknown tokens?
Any help would be so thankful.

```
unk1|||tgt1
unk2|||tgt2
unk3|||tgt3
```

**Comment by Zenglinxiao** [comment]
Hello @SoYoungCho ,
I haven't used that feature, but it should work after briefly read the code.
As it runs in silence without logging, I recommend you to print the `phrase_table_dict` after the [line](https://github.com/OpenNMT/OpenNMT-py/blob/592a2f62f098c69beeb5487f93d6c74321363630/onmt/translate/translation.py#L39) to see if the file is loaded and handled correctly.
