### ISSUE TITLE
PRED No words predicted

### ISSUE THREAD

**Issue by ValkyriaLenneth** [OpenNMT/OpenNMT-py#1851]
Hi
I face this problem while training the model with conversational dataset. I split the question and response in the conversational dataset as the src and target files for ONMT_train.
Then I got the trained model to predict my test words, however, there is no predict, just "PRED No words predicted".
I noticed that when training the model,  the ppx and cent is so small that become "nan". Is this the reason for my issue?

This is the configuration for onmt_train
```
data: ./save/preprocessedData
src_word_vec_size: 300
tgt_word_vec_size: 300
optim: adam
learning_rate: 0.15
batch_size: 16
gpu_ranks: 0
save_model: ./save/test_model
train_steps: 100000
```

And this is the configuration for onmt_translate
```
src: ./super/test.txt
output: ./save/output.txt
model: ./save/test_model_step_5000.pt
replace_unk: True
verbose: True
```

**Comment by CAOyj1010** [comment]
I have the same problem，Have you solved it?

**Comment by hanqi-qi** [comment]
Have you solved it? 
The original transformer model can output successfully, but with some modifications, it fails to translate anything, although my training process seems quite normal....

**Comment by DaisyTung** [comment]
Is there any solution?
I got same problem on my summarization task with transformer, I can predict most of inputs, but few of inputs are predicted as empty line, I have no idea why and how to solve it.

**Comment by hanqi-qi** [comment]
Yes, I remember that I modified some details in the decoding process, then it works.

**Comment by DaisyTung** [comment]
@hanqi-qi Did you remember what you modified? Thank you for help.

**Comment by hanqi-qi** [comment]
> @hanqi-qi Did you remember what you modified? Thank you for help.

I think it varies from datasets and tasks. I think I debugged step by step to monitor the decoder output and fixed some uncommon issues. Try it.
