### ISSUE TITLE
Training model with Constituency Tree/supertag input

### ISSUE THREAD

**Issue by JustCunn** [OpenNMT/OpenNMT-py#1853]
I'm trying to train a model that uses data that's parsed to a constituency tree or tagged with Supertags. I tried feeding it through as it looks (both are linearised) but of course, it just hurt performance greatly.

If I wanted to train a model that uses the tags and labels as information instead, what would be the best way to go about it? I have a feeling `gated graph neural networks` would be the way to do it but any advice is welcome!

Thanks

**Comment by francoishernandez** [comment]
@SteveKommrusch might have some ideas here.
Probably have a look at #1820 as well.

**Comment by SteveKommrusch** [comment]
JustCunn,

Yes, the GGNN could support your use case. The input, as documented at https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/ggnn.md , has 3 sections: The first section is the token sequence, much like the standard sequence-to-sequence models; the 2nd section allows for feature flags to be set per node (so a given node with the language token 'if' might also be labeled as a control node for example); the 3rd section is edge information which allows for a variety of edges to interconnect the nodes - different edge types have different learnable weights in the GGNN model.

I have created a more extensive example use case, including processing textual code tree output from ANTLR. I've added the details to the example GIT already mentioned in the ggnn.md document: https://github.com/SteveKommrusch/OpenNMT-py-ggnn-example . Refer to the 'end-to-end' example section in the README.md for a description of files; the files have hopefully useful comments about setup. I'm happy to schedule a web call to help get you going with the model.

Regards,
Steve

**Comment by JustCunn** [comment]
@SteveKommrusch Thanks very much for your detailed reply. May I ask, just to clarify, that if I have English text that is parsed that looks like this:
```
(ROOT (NP (NP (DT the) (JJ electoral) (NN register)) (CC and) (NP (JJ direct) (NN marketing)) (. .)))
```
It must be formatted into a sequence that looks like this?:
```
- - - 0 a a b b <EOT> 0 1 2 3 4 4 2 3 12 <EOT> 0 2 1 3 2 4 , 0 6 1 7 2 5 , 0 4 , 0 5 , , , , 8 0 , 8 1
```

Also, if we could speak about it that would be great!

Justin

**Comment by SteveKommrusch** [comment]
Correct, your 2nd sequence shows the format for src-*.txt files used by OpenNMT. In my example, this PERL script translates a format like your parenthesis text into the necessary GGNN input: https://github.com/SteveKommrusch/OpenNMT-py-ggnn-example/blob/master/src/raw2graph.pl .

Send me email at steve.kommrusch@gmail.com and we can set up a live discussion.
