### ISSUE TITLE
REST Server: Inconsistent I/O for preprocessors and postprocessors

### ISSUE THREAD

**Issue by cordawyn** [OpenNMT/OpenNMT-py#1855]
Hello!

I had to develop several preprocessors and postprocessors for the server, and so I came across one inconsistency:
While *preproceessors* are expected to get a dict object (with segments) and output a dict object of the same kind, *postprocessors* are expected to get that dict object, but output the string.

It was deliberately introduced in #1745 (https://github.com/OpenNMT/OpenNMT-py/blob/37e53e628294e5e40cda7258c551d228c19452dd/onmt/translate/translation_server.py#L700), but I wonder if that effect was indeed intended. Because of it, several postprocessors cannot be "chained" in a pipeline, similar to preprocessors (for now I'm forced to bundle them in a single big postprocessor function).

Looks like a bug?

**Comment by francoishernandez** [comment]
This code is executed only when no postprocessing function is defined in the configuration.
If you have several functions, you can chain them as you like, as long as their corresponding i/o match, and the final one outputs a string as expected.
https://github.com/OpenNMT/OpenNMT-py/blob/37e53e628294e5e40cda7258c551d228c19452dd/onmt/translate/translation_server.py#L713-L714

Might not be the cleanest way to do this I agree. The idea behind this was to allow more flexibility without breaking/rewriting the whole codebase.

**Comment by cordawyn** [comment]
I see. Thank you for the explanation!
