### ISSUE TITLE
How to let the script only save the best checkpoint?

### ISSUE THREAD

**Issue by JiyangZhang** [OpenNMT/OpenNMT-py#1856]
Hi,

Thanks for developing such a nice tool for all researchers. I am new to this tool, so correct me if there is something wrong.

I assume that if keep_checkpoint is set to 1, the script will only save one checkpoint which is the best one during validation. But it seems that it only saves the latest checkpoint. Is there option to let the script only save the best checkpoint? Or I misunderstand something here?

Thank you.

**Comment by francoishernandez** [comment]
`-keep_checkpoint` indeed allows to keep the last N checkpoints, hence from a 'chronological' standpoint:
https://github.com/OpenNMT/OpenNMT-py/blob/60125c807d1cb18099a69dbfba699bcdf30560b1/onmt/opts.py#L393-L394

If you'd like to implement something smarter, metric-based, PR welcome.
Most of the model saving logic is here:
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/models/model_saver.py

**Comment by JiyangZhang** [comment]
Thanks for reply. 
I would suggest change from "Keep X checkpoints" to "Keep last X checkpoints" to be more clear.
Actually I have no idea why we can early stop the training but can not save the checkpoint at the "best" time. 
I am happy to submit PR when I have the chance to implement something new.

**Comment by francoishernandez** [comment]
>  Actually I have no idea why we can early stop the training but can not save the checkpoint at the "best" time.

Good point. The early stopping mechanism should probably override this `keep_checkpoint` parameter.

**Comment by vince62s** [comment]
follow up on this in #1946
