### ISSUE TITLE
issues with loading existing dictionary and pre-trained word vectors

### ISSUE THREAD

**Issue by shuoyangd** [OpenNMT/OpenNMT-py#186]
Hi All,

It seems like in `preprocess.py`, the options to load existing dictionaries (`src_vocab` `tgt_vocab` `features_vocabs_prefix`) are currently not implemented. These options are actually pretty important if one is loading pre-trained word vectors, because one would want the string-to-index mapping of the dictionary to be consistent with that of the pre-trained word vectors. Right now the code does not seem to provide guarantee for that.

Instead of waiting on these options to be implemented, I would like to propose changing the implementation of `Embeddings.load_pretrained_vectors(self, emb_file)` such that during loading, the pre-trained word embedding will be re-arranged to match the dictionary of encoder/decoder.

Does it sound reasonable?

Shuoyang

**Comment by StevenLOL** [comment]
Yes , you can just go ahead. 

By the way do you know how to set a value of torch.cuda.FloatTensor

**Comment by shuoyangd** [comment]
@StevenLOL I thought one would just use `operator=` to set a reference and `copy_` function to set a real copy of the value. Is there any other special aspects I should bear in mind?

**Comment by StevenLOL** [comment]
Thanks
I have a workable one:

https://github.com/StevenLOL/OpenNMT-py/blob/master/onmt/Models.py

Now , gensim is required to load standard word2vec file, anyway one can get ride of gensim, by coding his own data loader (read key-value pairs from pain text), that is as easy as abc.

**Comment by shuoyangd** [comment]
@StevenLOL thanks. I'm working on [this branch](https://github.com/shuoyangd/OpenNMT-py/tree/new_mono_emb) -- seems to be getting similar trend as yours but I'd withhold any conclusion before finishing a full experiment.

**Comment by shuoyangd** [comment]
I finished implementing my [branch](https://github.com/shuoyangd/OpenNMT-py/tree/new_mono_emb). #166 seems to be already working on the very similar problem so I don't think there is a need to merge it, hence closing this issue.
