### ISSUE TITLE
Seq2seq model using Convolutional Neural Network

### ISSUE THREAD

**Issue by nashid** [OpenNMT/OpenNMT-py#1861]
Seq2seq model is typically implemented as RNN. However, recent works have shown the applications of Convolutional Neural Network (CNN) for seq2seq learning.

Does OpenNMT-py provide a model using CNN for seq2seq?

I have looked into the documentation https://opennmt.net/OpenNMT-py/quickstart.html

However, it does not look like OpenNMT supports seq2seq using CNN.

In case it supports CNN for seq2seq, can you please point me to the necessary resources?

**Comment by francoishernandez** [comment]
There indeed are [`CNNEncoder`](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/encoders/cnn_encoder.py) and [`CNNDecoder`](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/cnn_decoder.py), though in full transparency I have never tested it myself so I wouldn't know how it would behave.
Let us know if you get some results!
