### ISSUE TITLE
What version of GCC do I need?

### ISSUE THREAD

**Issue by JustCunn** [OpenNMT/OpenNMT-py#1863]
Just a quick question, what version(s) of `gcc` does OpenNMT-py accept and use? I'm having trouble with v8.2.0.

**Comment by francoishernandez** [comment]
Not sure this is an `OpenNMT-py` issue per se.
You probably have some issues with your python or `torch` setup.

**Comment by JustCunn** [comment]
@francoishernandez Oh sorry, I wasn't too sure about what was causing it or familiar with `gcc`/the error message I got `libgcc_s.so.1 must be installed for pthread_cancel`. I have a StackOverflow question [here](https://stackoverflow.com/questions/63749000/libgcc-s-so-1-must-be-installed-for-pthread-cancel-to-work-on-ubuntu) about it with more detail if you think you could help in any way, it would be much appreciated. Thanks for letting me know though.

**Comment by francoishernandez** [comment]
There might be an issue with the last version(s) of pytorch, or with your setup.
What you're mentioning very much looks like this issue: https://github.com/pytorch/pytorch/issues/41661

Maybe you could try with an OpenNMT-py version < 1.2.0 and a torch==1.4.0 for instance.
Doesn't solve the issue but probably fine as a temporary workaround.
