### ISSUE TITLE
how to pass live stream audio for translate.py

### ISSUE THREAD

**Issue by Nouraaaawwad** [OpenNMT/OpenNMT-py#1865]
Hello 

thank you for your good work 

My plan is to make a mobile application for correcting the speech of the user.

i already did the ML speech2text, but i am wondering if i could pass a live stream audio from microphone to translate.py ?
i tried but it gave me an error that the src should be array or something.
i want the translation to be dynamic, is there a better way to pass it ?

appreciate your help..,
thank you

**Comment by francoishernandez** [comment]
This is quite beyond the scope of this project. You would need to look for 'online' speech recognition and toolkits that support it (not many out there).
Also I'm curious: do you get any satisfying result in an offline setup? What kind of utterances are you handling?
Out of the experiments I did on speech with onmt, I found it way less appropriate than dedicated speech toolkits.

**Comment by Nouraaaawwad** [comment]
> This is quite beyond the scope of this project. You would need to look for 'online' speech recognition and toolkits that support it (not many out there).

i tried to do the simple REST server tutorial .. doesn't it work for speech also ? My plan was after training the ML i would set up the REST server then doing a GUI. but i am stuck with the audio streaming now :/ .. i am sorry if My question are silly but it is my first ASR app 🙈

> Also I'm curious: do you get any satisfying result in an offline setup? What kind of utterances are you handling?
> Out of the experiments I did on speech with onmt, I found it way less appropriate than dedicated speech toolkits.

actually i did get good result although the ML is pretty small but still satisfying accuracy for testing over 80%. the ML only about 300 word.
