### ISSUE TITLE
Confusing `fix_word_vecs_*` option

### ISSUE THREAD

**Issue by ygorg** [OpenNMT/OpenNMT-py#1866]
As a new OpenNMT user (coming from allennlp) I wondered for a while what [`fix_word_vecs`](https://github.com/OpenNMT/OpenNMT-py/blob/a5401acfea0b013743bc36c4179af76ddf34251f/onmt/opts.py#L446) meant, I initially thought 'fix' as if the word embeddings would somehow be broken.
By looking at [the code](https://github.com/OpenNMT/OpenNMT-py/blob/8453ab79dcf822d16e2e907bcb7cc26b04c63a86/onmt/tests/test_embeddings.py#L109) I understood it meant to not train the weights of the word embeddings.

So I wonder whether changing the `help` string to "Do not train word embeddings weights on the * side." (or "Freeze word embedding on the * side.") would make it clearer?
But maybe it would alter the doc's consistency.

(btw this library makes it so easy to train seq2seq models, thanks a lot !)

**Comment by pltrdy** [comment]
Agree on this. Replacing each "fix" occurence (in this context) with "freeze" would be a lot clearer. 

Would you mind opening a PR for this @ygorg ?

**Comment by ygorg** [comment]
Hi, yes i'll do that. (I didn't see your message until now sorry)
