### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by yellowbirdwithme** [OpenNMT/OpenNMT-py#1867]
Cannot pip install on neither python 3.7 nor python 3.5. 

>  ERROR: Could not find a version that satisfies the requirement torch>=1.6.0 (from OpenNMT-py) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
> ERROR: No matching distribution found for torch>=1.6.0 (from OpenNMT-py)

**Comment by francoishernandez** [comment]
This means your pip can't install pytorch 1.6.0, which is required.
Please see the pytorch docs/help to get this installed first.

**Comment by yellowbirdwithme** [comment]
Thank you. Installing pyTorch separately solves the problem.
