### ISSUE TITLE
Following quick start steps but get onmt_train: error: the following arguments are required: -data/--data

### ISSUE THREAD

**Issue by SoniciSika** [OpenNMT/OpenNMT-py#1871]
here is my yaml files
build_vocab:
save_data: context_demo
overwrite: True
data:
    corpus_1:
        path_src: train_in
        path_tgt: train_out
    valid:
        path_src: val_in
        path_tgt: val_out
src_seq_length: 2050
tgt_seg_length: 2050
train:
src_vocab: context_demo.vocab.src
tgt_vocab: context_demo.vocab.tgt
world_size: 1
gpu_ranks: [0]
save_model: context
save_checkpoint_steps: 5000
train_steps: 100000
valid_steps: 3000
batch_size: 128

**Comment by francoishernandez** [comment]
You need to set the data configuration as shown in quickstart, instead of leaving it empty.

**Comment by XIEBBS** [comment]
I got the same exception when I followed the guild document.

**Comment by XIEBBS** [comment]
It seems that the author did't update the document.

**Comment by francoishernandez** [comment]
Read the doc and my comment. Everything is there.

The configuration passed to train is actually the concatenation of the two configs shown in the Quickstart doc -- as shown by the `...` in the yaml sections, as well as explicitly mentioned [in the first sentence of Step 2](https://opennmt.net/OpenNMT-py/quickstart.html#step-2-train-the-model):
`add the following to the YAML configuration file`

Feel free to PR some changes if you feel like it's not enough.
