### ISSUE TITLE
Can't perform preprocessing of the source and target files

### ISSUE THREAD

**Issue by GalleonChestnut** [OpenNMT/OpenNMT-py#1876]
I implement my model in Google colab and it worked fine until recently when I got the following error message when I tried to perform preprocessing.

**python3: can't open file 'OpenNMT-py/preprocess.py': [Errno 2] No such file or directory**

Then, I checked the onmt/bin directory and found that the preprocess.py file is not available as it was before. Please let me know how to fix this issue.

**Comment by francoishernandez** [comment]
The preprocessing step has been removed. See the [announcement about release 2.0](https://github.com/OpenNMT/OpenNMT-py#announcement---opennmt-py-20).

**Comment by GalleonChestnut** [comment]
Thank you for your response. It was my mistake that I didn't check the announcement.
