### ISSUE TITLE
How to run onmt_build_vocab

### ISSUE THREAD

**Issue by yellowbirdwithme** [OpenNMT/OpenNMT-py#1877]
Hi, 
I'm having a problem running the command onmt_build_vocab on Google Colab

> /bin/bash: onmt_build_vocab: command not found

Any ideas how to overcome the issue?

**Comment by francoishernandez** [comment]
There probably is an issue with your setup.
How did you install OpenNMT-py?

**Comment by yellowbirdwithme** [comment]
pip install OpenNMT-py

**Comment by yellowbirdwithme** [comment]
onmt_train works fine

**Comment by yellowbirdwithme** [comment]
pip install OpenNMT-py installs version 1.2.0

**Comment by yellowbirdwithme** [comment]
I tried to install from the sources, but the followin error appeared:


>  Traceback (most recent call last):
>   File "/usr/local/bin/onmt_build_vocab", line 33, in <module>
>     sys.exit(load_entry_point('OpenNMT-py==2.0.0rc1', 'console_scripts', 'onmt_build_vocab')())
>   File "/usr/local/bin/onmt_build_vocab", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 105, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'onmt'

When I try to run onmt/bin/build_vocab.py the following error occurs:

> Traceback (most recent call last):
>   File "OpenNMT-py/onmt/bin/build_vocab.py", line 3, in <module>
>     from onmt.utils.logging import init_logger
> ModuleNotFoundError: No module named 'onmt'

**Comment by francoishernandez** [comment]
> pip install OpenNMT-py installs version 1.2.0

The `build_vocab` entry point was added in 2.0.0rc1. See the [announcement about the 2.0 release](https://github.com/OpenNMT/OpenNMT-py#announcement---opennmt-py-20).

>  ModuleNotFoundError: No module named 'onmt'

This is because you need to have it in your `PYTHONPATH`.
