### ISSUE TITLE
Does new version run on Windows?

### ISSUE THREAD

**Issue by yellowbirdwithme** [OpenNMT/OpenNMT-py#1879]
Hi,
The previous version of OpenNMT-py ran on Windows without any problems. Were the new version and the quickstart instructions tested on Windows?
I've tried to run it on my computer, but different errors keep coming up.

**Comment by francoishernandez** [comment]
No test were performed on windows.
I think it should be able to, but some transforms may require some incompatible modules.
The best thing to do here is probably to open a topic on the [forum](https://forum.opennmt.net/) to track what you've tried to do and get help from others.
