### ISSUE TITLE
Number of examples while training

### ISSUE THREAD

**Issue by Anurag-Swarnim-Yadav** [OpenNMT/OpenNMT-py#1883]
Hello,

I have 1230 examples in my training dataset but while training the model it says the number of examples as 6. I am not sure what is going on?

**Comment by francoishernandez** [comment]
Hi there,
You might have to give a bit more info here:
- are you using the legacy version or the 2.0.0 pre-release?
- what is your task // what are your command lines?

Note: this is probably just an issue with some examples that are discarded because they're too long. (`src_seq_length`/`tgt_seq_length` flags)

**Comment by Anurag-Swarnim-Yadav** [comment]
Hello francoishernandez,

Yes I am using the legacy version.

I am training on source code. Both my source and target file are source code. 

I am using the following commands.
To pre-process

onmt_preprocess -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo

to Train 

onmt_train -data data/demo -save_model demo-model



So when I training with default configuration. It is loading number of exampels as 6. What does that mean ?

**Comment by francoishernandez** [comment]
This is probably what I put in the note above: the default configuration sets the `src_seq_length` and `tgt_seq_length`to `50`.
https://github.com/OpenNMT/OpenNMT-py/blob/585499a4509b1c2dac7683b7588f3f544f89119e/onmt/opts.py#L310-L319
What's the length of your training examples? Most of them are probably longer than 50, hence they're ignored.
Side note, 1230 examples is very (very) small of a dataset to train a seq2seq model anyways.

**Comment by Anurag-Swarnim-Yadav** [comment]
Thanks but in the documentation its mentioned  --src_seq_length as 200 by default.

https://opennmt.net/OpenNMT-py/options/train.html

**Comment by francoishernandez** [comment]
This documentation was updated for the 2.0 update.
You can see here the `src_seq_length`and `tgt_seq_length`are actually opts of the `filtertoolong`transform.
That's why I linked you to the legacy opts.

**Comment by Anurag-Swarnim-Yadav** [comment]
could you please guide where I can make changs ? I can not find src_seq_length and tgt_seq_length in opts.py

**Comment by francoishernandez** [comment]
Add `-src_seq_length 1234` to your command line to set the value to 1234.

**Comment by Anurag-Swarnim-Yadav** [comment]
Is source sequence lenght Is equal to total training example ?

**Comment by francoishernandez** [comment]
If you're still using the legacy version of course. But since you're saying you can't find it, it's quite unclear to me what you're doing... If you switched to 2.0 you can have a look at the examples in the docs.

**Comment by francoishernandez** [comment]
Please read carefully.
These arguments are used to **filter examples by their length**.
If an example is longer than that, il will be discarded.
Can't be more explicit.

**Comment by Anurag-Swarnim-Yadav** [comment]
Yeah I am switching to 2.0 now. Thanks . 

Yeah thats what I thought about source sequence but thanks

**Comment by francoishernandez** [comment]
I'll close the issue then. Reopen if anything else arises using 2.0.

**Comment by Anurag-Swarnim-Yadav** [comment]
How do I know if my model is using all the traning examples? I just changed the source sequence length and target sequence length to 20000. Once I start training it still says 

[2020-10-08 18:35:11,759 INFO] Loading dataset from data/demo.train.0.pt
[2020-10-08 18:35:11,760 INFO] number of examples: 6

**Comment by francoishernandez** [comment]
Mate, you just said you were switching to 2.0.

With legacy you have to preprocess again. Did you?

**Comment by Anurag-Swarnim-Yadav** [comment]
I am confused with legacy and 2.0.0 pre-release. I just installed OpenNMT again . How do I know what verison is it?

**Comment by francoishernandez** [comment]
`pip list` will tell you the version you have installed.

**Comment by Anurag-Swarnim-Yadav** [comment]
Thanks François Hernandez.
