### ISSUE TITLE
Can't import some files from onmt.inputters

### ISSUE THREAD

**Issue by GalleonChestnut** [OpenNMT/OpenNMT-py#1885]
I was trying to run the jupyter notebook example available in  "OpenNMT-py/docs/source/examples/Library.ipynb" in google colab. and when I tried to run, 

**import onmt
from onmt.inputters.inputter import _load_vocab, _build_fields_vocab, get_fields, IterOnDevice
from onmt.inputters.dynamic_iterator import DynamicDatasetIter
from onmt.translate import GNMTGlobalScorer, Translator, TranslationBuilder
from onmt.utils.misc import set_random_seed**

it imported fine for first two modules but raised an error as below.

**ModuleNotFoundError: No module named 'onmt.inputters.dynamic_iterator'**

but the said file in available in the folder. Why is this happenning?

**Comment by francoishernandez** [comment]
There probably is an issue with your `PYTHONPATH`.
Maybe you have a previous version of `onmt` (in which `dynamic_iterator` does not exist yet) installed?

**Comment by GalleonChestnut** [comment]
Yes, I added the `onmt` folder to the `PYTHONPATH` as follows and then I could import all the modules without any error.

```
import sys
sys.path.insert(1, "/content/OpenNMT-py/onmt")
```
