### ISSUE TITLE
train.py: error: Couldn't parse config file: expected '<document start>', but found '<block mapping start>'

### ISSUE THREAD

**Issue by 27182812** [OpenNMT/OpenNMT-py#1886]
when I run "onmt_train -config toy_en_de.yaml", it will be as follow:
![image](https://user-images.githubusercontent.com/33630730/95742269-4e31b000-0cc2-11eb-8d28-0babcbcbabe5.png)
and my steps just like quickstart, and my toy_en_de.yaml is this:

![image](https://user-images.githubusercontent.com/33630730/95742526-bc767280-0cc2-11eb-8c95-ab0dec9e3f66.png)

![image](https://user-images.githubusercontent.com/33630730/95742545-c304ea00-0cc2-11eb-8c16-f771a8de4631.png)

the line 30 is "save_model: toy-ende/run/model"

please help me, thank you !

**Comment by francoishernandez** [comment]
You probably need to remove the `...` from line 19. It was supposed to mean that the config was appended to the previous config.
Sorry if unclear, the docs might still need a bit of work.
