### ISSUE TITLE
onmt_build_vocab is missing

### ISSUE THREAD

**Issue by texttheater** [OpenNMT/OpenNMT-py#1890]
The quickstart instructions reference the onmt_build_vocab script. However, it does not appear to be present in this repository or installed with OpenNTM-py.

**Comment by francoishernandez** [comment]
You probably have installed the legacy version (< 2). The build_vocab entry point was introduced in the 2.0.0rc1 pre-release.
You can force pip to install this pre-release by setting the version to 2.0.0rc1 in your pip install.
