### ISSUE TITLE
What does the 'src' tensor (in a models forward call) represent?

### ISSUE THREAD

**Issue by JustCunn** [OpenNMT/OpenNMT-py#1891]
I'm trying to add an embedding layer to an encoder I'm using. During a forward call of any encoder (except the GGNN) it runs src through an `embedding` layer. I notice `src` is a 3 Dimensional tensor, but I'm unsure as to what it represents (except of course that it is the src side sentences).

For example, if I have a `src` tensor of size `[20,32,1]`, what does each dimension represent? Apologies if this is a trivial question, just I haven't delved into the specifics of OpenNMT too much before. 

Thanks in advance,
Justin

**Comment by francoishernandez** [comment]
See the definition of `EncoderBase.forward`:
https://github.com/OpenNMT/OpenNMT-py/blob/fab4518bfb8799d077fddfd485429106a4e1831c/onmt/encoders/encoder.py#L46-L47

**Comment by JustCunn** [comment]
@francoishernandez Thanks
