### ISSUE TITLE
Word embedding in seq2seq network

### ISSUE THREAD

**Issue by Bessem11** [OpenNMT/OpenNMT-py#1892]
My question is related to the seq2seq model provided here : 
https://opennmt.net/OpenNMT-py/options/train.html#model-encoder-decoder

When I specify the word_vec_size option [--word_vec_size WORD_VEC_SIZE], what is the technique used by the network to create the word embedding (word2vec CBOW, word2vec CBOW Skip-gram, one hot encoding ..)? I tried to find if this is specified somewhere in the documentation; but unfortunately, I didn't find an answer.

Thank you in advance

**Comment by francoishernandez** [comment]
The embeddings here are just a [`torch.nn.Embeddings`](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html) module which is trained along with the model.
You can use pretrained embeddings if needed: https://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-pretrained-embeddings-e-g-glove
