### ISSUE TITLE
different batch_size generates different result

### ISSUE THREAD

**Issue by AbelCui** [OpenNMT/OpenNMT-py#1909]
hi, when I use translate.py to inference same testset, different batch_size generates different result, but other parameters are same.
Could you help me to fix this bug? THX

**Comment by francoishernandez** [comment]
Hi,
This is a known behaviour. You can read this for further details:
- https://forum.opennmt.net/t/a-slightly-different-result-in-translation-with-various-batch-sizes/3273/7
- https://github.com/OpenNMT/OpenNMT-py/issues/1320
