### ISSUE TITLE
Model evaluation/summary

### ISSUE THREAD

**Issue by Bessem11** [OpenNMT/OpenNMT-py#1917]
Hey,

I trained a model (seq2seq) using the train.py file. Is there a possibility to get the different evaluation metrics (accuracy, cross-entropy ...) after completing the training of the model? 
The mode I obtained has a .pt extension, Is there a method to obtain the model summary ( layers, weights..) like methods in Keras? In fact, I used the method .eval but I got an error <AttributeError: 'dict' object has no attribute 'eval'>

Thank you for your time

**Comment by francoishernandez** [comment]
All the information you're looking for should be in your training logs.
Details of the layers and parameters is output at the beginning of the training, and then metrics are printed periodically (depending on the opts you passed).
