### ISSUE TITLE
Using amp(fp16) cause "returned nan values in its 0th output." in backward

### ISSUE THREAD

**Issue by Sanghyuk-Choi** [OpenNMT/OpenNMT-py#1918]
when training with fp16 (using amp),
`RuntimeError: Function 'BmmBackward0' returned nan values in its 0th output.`
on Copy Generator module.

https://github.com/OpenNMT/OpenNMT-py/blob/dfdd4554cf1c9327c2c249ab11a978efe72a93d9/onmt/modules/copy_generator.py#L127-L130

It works fine with fp32 settings.

**Comment by francoishernandez** [comment]
Sorry for the late reply.
Does this happen at the beginning of your training or later? Randomly or always around the same step?

**Comment by Sanghyuk-Choi** [comment]
> 
Hi, I just noticed you had the same problem.
Actually, I couldn't solve it, so I just did not used amp.
