### ISSUE TITLE
Option to freeze the embedding layer

### ISSUE THREAD

**Issue by StevenLOL** [OpenNMT/OpenNMT-py#192]
After load pre-trained embedding, I would like freeze this layer, how could I do that ?

I knew there is "param.requires_grad = False", but haven't figure where to put it .

**Comment by shuoyangd** [comment]
As you have pointed out, the following line would mark the word embedding as fixed:

```
self.embeddings.weight.data.requires_grad = False # fix this embedding
```

But in order to make the optimizer to follow the marking, you need to find the following line in `train.py`

```
optim.set_parameters(model.parameters())
```

and replace it with:

```
optim.set_parameters(filter(lambda p: p.requires_grad, model.parameters()))
```

That should do it.

**Comment by srush** [comment]
If you look at this PR it implements this: https://github.com/OpenNMT/OpenNMT-py/pull/166/files You should be able to just use it as is.
