### ISSUE TITLE
How to inference on multiple GPU?

### ISSUE THREAD

**Issue by charlenellll** [OpenNMT/OpenNMT-py#1921]
Hi,
Do you support translation on multiple gpus? I tried CUDA_VISIBLE_DEVICES but it does not work, and it seems that using option --gpu only allow one gpu to be used. 
Since I have a really large dataset to predict, is it possible to use multiple gpus during inference time? If so, how to setup the configs correctly? By the way, the version of OpenNMT-Py==2.0.0.rc1.

**Comment by vince62s** [comment]
You'll need to run several processes in parallel.

**Comment by charlenellll** [comment]
Thanks! I'll give it a try.
