### ISSUE TITLE
Infinite loop Loading ParallelCorpus in version bump-2.0.0-rc2

### ISSUE THREAD

**Issue by cucbui57** [OpenNMT/OpenNMT-py#1927]
I have an issue when trying BART to my machine translation task. 
The log: [2020-11-11 17:08:16,251 INFO] Loading ParallelCorpus(..) have infinite loop on 30 mins despite I've tried only with 10k sentences.

**Comment by cucbui57** [comment]
I have some trouble understanding how the framework work. Sorry

**Comment by francoishernandez** [comment]
The dataset is supposed to be continuously loaded. This loading will happen even more frequently that your dataset is small.
If you think there is another issue, please give more details such as your full config and logs.

**Comment by cucbui57** [comment]
I have some trouble understanding how the framework work. Sorry
