### ISSUE TITLE
bus error (core dumped)

### ISSUE THREAD

**Issue by cucbui57** [OpenNMT/OpenNMT-py#1928]
Hi,

I got a bus error (core dumped) when using option train from with 2 GPUs. This work with 1 GPU not faced this error. The following error below:

![c84e450391b16fef36a0](https://user-images.githubusercontent.com/30381401/98907200-0c7a6c00-24f1-11eb-8255-34d78a0a6134.jpg)

**Comment by francoishernandez** [comment]
Do you happen to run this in a docker container?

**Comment by cucbui57** [comment]
Yes, I've run in docker. But in the previous version 1.0.0, I did not face this error.
P.s: I'm currently using version bump 2.0.0rc2

**Comment by francoishernandez** [comment]
You could try something like this maybe: https://github.com/pytorch/pytorch/issues/2244#issuecomment-318864552

**Comment by cucbui57** [comment]
It's useful for me. Thank you
