### ISSUE TITLE
Vocab size incorrect when use features for encoder

### ISSUE THREAD

**Issue by XinyuHua** [OpenNMT/OpenNMT-py#193]
I encountered this problem when I'm trying to label each src token with 1 or 0, e.g. "The|1 word|0". But this causes the preprocessed .pt file to have only 2 words in vocabulary, \<unk\> and \<blank\>. Also for tgt the vocabulary contains \<unk\>, \<blank\>, \<s\>, \</s\> only as well.  (I've tried the same document without adding features and it worked fine.)

**Comment by srush** [comment]
Just to confirm. Are you using the latest code? How many features does it say you have when you run `train.py`

**Comment by XinyuHua** [comment]
Thanks for the reply. I cloned the repo just now so I'm assuming it's up-to-date. I included one bit as feature. If I run `train.py` it says:

* vocabulary size. source = 2; target = 4
 * src feature 0 size = 2
 * number of training sentences. 0
 * maximum batch size. 32


If I add `print('numFeatures:', numFeatures)` at the end of extractFeatures method in onmt/IO.py it prints this:

Preparing training ...
('numFeatures:', 1)
Building Training...
('numFeatures:', 1)
('numFeatures:', 0)

**Comment by XinyuHua** [comment]
I found the problem, the input sequence was too long so it's removed...sorry about the trouble

**Comment by eduamf** [comment]
I'm using one feature that can be in {'N', 'U', 'C', 'L'}.

Why the vocab size is diferent?

```
[2019-05-02 03:28:49,162 INFO]  * src vocab size = 154622
[2019-05-02 03:28:49,163 INFO]  * src_feat_0 vocab size = 2
[2019-05-02 03:28:49,163 INFO]  * tgt vocab size = 131749
[2019-05-02 03:28:49,163 INFO]  * tgt_feat_0 vocab size = 4
[2019-05-02 03:28:49,163 INFO] Building model...
[2019-05-02 03:28:54,630 INFO] NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(154622, 600, padding_idx=1)
          (1): Embedding(2, 2, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(602, 400, num_layers=2, dropout=0.2, bidirectional=True)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(131749, 600, padding_idx=1)
          (1): Embedding(4, 4, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.2)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.2)
      (layers): ModuleList(
        (0): LSTMCell(1404, 800)
        (1): LSTMCell(800, 800)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=800, out_features=800, bias=False)
      (linear_out): Linear(in_features=1600, out_features=800, bias=False)
      (linear_cover): Linear(in_features=1, out_features=800, bias=False)
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=800, out_features=131749, bias=True)
    (1): LogSoftmax()
  )
)

```
