### ISSUE TITLE
Some empty lines in translation output

### ISSUE THREAD

**Issue by fenimi** [OpenNMT/OpenNMT-py#1934]
I'm using OpenNMT-py but i'm getting empty lines in the translation output file for both lstm and transformer models. Please what may be going on?

Thank you

**Comment by francoishernandez** [comment]
You probably have empty lines in your training data. Maybe you can try and find some pattern in the sources that producer empty predictions.

**Comment by fenimi** [comment]
> You probably have empty lines in your training data. Maybe you can try and find some pattern in the sources that producer empty predictions.

ok, thank you. I will check and get back to you.

**Comment by fenimi** [comment]
I have checked my training data again, there are no empty lines. Although some lines have only 2 words. I'm not sure why there are empty lines
