### ISSUE TITLE
MRR and Recall

### ISSUE THREAD

**Issue by mayaKaplansky** [OpenNMT/OpenNMT-py#1936]
(Duplicate of forum post: https://forum.opennmt.net/t/calculate-mrr-and-recall/4033)
Hi
I would like to calculate MRR and Recall of the performance of my model.
To calculate those, I need not only 1 prediction per input, but multiple predictions, sorted by score.
Should I use n_best>1 to get those?
Is there anyway to export those to a file I can use to calculate?
Thanks!

**Comment by francoishernandez** [comment]
Yes, you can use the `n_best` flag to generate this many predictions. Do not forget to set `beam_size` >= `n_best` as well.
This will dump the results in a single file, with `n_best` lines per input example.

**Comment by mayaKaplansky** [comment]
Thank you very much!
When I use train, how do I know for which checkpoint step I have the best
results so I can use it on translate?
Thanks Maya

**Comment by francoishernandez** [comment]
Basic idea is to do the inference with several checkpoints along the way and see which model will perform the best, according to your metrics.
Training metrics are often not enough to select the best model for your task.

**Comment by mayaKaplansky** [comment]
Gotcha
Thank you very much!
