### ISSUE TITLE
How is Accuracy calculated ?

### ISSUE THREAD

**Issue by arshadshk** [OpenNMT/OpenNMT-py#1944]
I manually calculated the accuracy and it didn't match the validation printed accuracy while training.
In which way is the accuracy calculated -

eg.  ground_truth - a b c d e f
      predicted_seq - z b c z f z

1. Comparing ground truth tokens to the predicted tokens position wise. ( The standard way )
      n_correct- 2
       total - 6
      Accuracy  = 100 * (2/6) = 33.33

2. Considering the token as correct if it is present in the prediction irrelative to the position in the predicted sequence.
      n_correct- 3
      total - 6
      Accuracy = 100 * (3/6) = 50

( If possible please tag the code where the n_correct is calculated)

**Comment by vince62s** [comment]
it starts around here: https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/utils/loss.py#L181-L185

can you give your real world example that does not match?

**Comment by arshadshk** [comment]
Thanks for the reply.
So it is computing the accuracy token to token while ignoring the pad index.
I have a practical example but the tensor is pretty large for comparing printed acc and manually computed acc. @vince62s 
Closing the issue.
