### ISSUE TITLE
Get output in variable

### ISSUE THREAD

**Issue by Krak91** [OpenNMT/OpenNMT-py#1945]
Hello, how can I get the output/predictions from the Translator in a variable that I can use in code? Thanks.

**Comment by francoishernandez** [comment]
The easiest is probably to use the REST server: https://forum.opennmt.net/t/simple-opennmt-py-rest-server/1392

Else, you can have a look at the ["How to use onmt library example"](https://opennmt.net/OpenNMT-py/examples/Library.html#translate).

**Comment by Krak91** [comment]
Thanks! For my use case I've found this to be useful:
- Defining the ArgumentParser in my main script. (similar to translate._get_parser) -> parser
- Parsing a string of the arguments to the parser to get a Namespace object. (parser.parse_args(<args_sting>)) -> Namespace
- Modifying the translate function in the translate.py script to return the predictions. (by default it will only write them in the output file)
- Passing the Namespace object to the translate function.
