### ISSUE TITLE
Passing variable to translator

### ISSUE THREAD

**Issue by Krak91** [OpenNMT/OpenNMT-py#1947]
Is there a way to pass the data (src) to the translator as variables rather than a file path from which it reads it from?

**Comment by francoishernandez** [comment]
You can have a look at the `onmt.translate.translation_server` code, where `texts_to_translate` is actually a list of strings.
https://github.com/OpenNMT/OpenNMT-py/blob/bc95e03875aabf4363161aac70830ecbdb762d91/onmt/translate/translation_server.py#L484-L489

**Comment by Krak91** [comment]
Awesome! Thanks a lot.
