### ISSUE TITLE
RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by sjchasel** [OpenNMT/OpenNMT-py#1950]
To produce prediction output using pretrained model, I am using following command but I am getting given below error. There seems to be model-loading issue. Could you please help on this?

Thanks!

Error:

```
Extracting features...
 * number of source features: 0.
 * number of target features: 0.
Building `Fields` object...
Building & saving training data...
 * divide corpus into shards and build dataset separately(shard_size = 52428800 bytes).
Traceback (most recent call last):
  File "/home/yons/PycharmProjects/TG-Net-master/onmt/io/TextDataset.py", line 662, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 206, in <module>
    main()
  File "preprocess.py", line 196, in main
    train_dataset_files = build_save_dataset('train', fields, opt)
  File "preprocess.py", line 141, in build_save_dataset
    corpus_type, opt)
  File "preprocess.py", line 107, in build_save_text_dataset_in_shards
    dynamic_dict=opt.dynamic_dict)
  File "/home/yons/PycharmProjects/TG-Net-master/onmt/io/TextDataset.py", line 85, in __init__
    for ex_values in example_values:
  File "/home/yons/PycharmProjects/TG-Net-master/onmt/io/TextDataset.py", line 77, in <genexpr>
    example_values = ([ex[k] for k in keys] for ex in examples_iter)
  File "/home/yons/PycharmProjects/TG-Net-master/onmt/io/TextDataset.py", line 293, in _dynamic_dict
    for example in examples_iter:
  File "/home/yons/PycharmProjects/TG-Net-master/onmt/io/TextDataset.py", line 61, in <genexpr>
    examples_iter = (self._join_dicts(src, query, tgt) for src, query, tgt in
RuntimeError: generator raised StopIteration
```

**Comment by francoishernandez** [comment]
Looks like your project is based on a very (very) old version.
Is this something you've been working on or maybe a public fork? If the latter you might want to ask for help there.

**Comment by sjchasel** [comment]
I am reproducing a paper from which these codes are derived.
Should I download an older version of OpenNMT-py if I want to run it?
Or what should I change?

**Comment by francoishernandez** [comment]
I'm not sure to understand. Are you implementing yourself the paper from scratch ? Or did you retrieve a codebase somewhere?
If implementing yourself, you might want to start from a more recent version of OpenNMT-py if you want some decent support.

**Comment by sjchasel** [comment]
Sorry, I didn't make myself clear. The code comes from the author of a paper.
He doesn't seem to have the code on GitHub, so I can't tell you where the repository is.
I wonder if there is any way to execute these older versions of the code?

**Comment by francoishernandez** [comment]
Ok, understood.
I think your best bet is to ask them for details about the environment they ran the code in. Python version, torch, torchtext versions etc.
You may also ask them for a toy example that runs on their side, and check you can execute it properly.
Else you can dive in the code, follow the traces or maybe find old issues tackling the topics to debug it yourself.

**Comment by sjchasel** [comment]
Thank you very much! It was very helpful.
