### ISSUE TITLE
Transformer encoder layer differs from original paper

### ISSUE THREAD

**Issue by anderleich** [OpenNMT/OpenNMT-py#1952]
Hi,

I've been analyzing the code for the Transformer architecture and I found some minor differences when comparing it with the original paper "Attention is all you need".

The forward pass of one of the encoder's layer is defined as follows:
```
def forward(self, inputs, mask):
        """
        Args:
            inputs (FloatTensor): ``(batch_size, src_len, model_dim)``
            mask (LongTensor): ``(batch_size, 1, src_len)``
        Returns:
            (FloatTensor):
            * outputs ``(batch_size, src_len, model_dim)``
        """
        input_norm = self.layer_norm(inputs)
        context, _ = self.self_attn(input_norm, input_norm, input_norm,
                                    mask=mask, attn_type="self")
        out = self.dropout(context) + inputs
        return self.feed_forward(out)
```
Then, the encoder's forfard pass is defined as follows:
```
def forward(self, src, lengths=None):
        """See :func:`EncoderBase.forward()`"""
        self._check_args(src, lengths)

        emb = self.embeddings(src)

        out = emb.transpose(0, 1).contiguous()
        mask = ~sequence_mask(lengths).unsqueeze(1)
        # Run the forward pass of every layer of the tranformer.
        for layer in self.transformer:
            out = layer(out, mask)
        out = self.layer_norm(out)

        return emb, out.transpose(0, 1).contiguous(), lengths
```

This results in:
_____________________________________
Embeddings (input)
1st layer:
- Normalization(embbedings)
- Self-attention
- Dropout
- Concat with inputs (residual connection)
- Feed-forward

2nd layer
- Normalization(feed forward)
- Self-attention
- Dropout
- Concat with inputs (residual connection)
- Feed-forward

More layers..
Normalization (last feed-forward)
_______________________________________

However, according to the original paper this is what I understood as the behaviour of the encoder. Please correct me if I misunderstood something.

____________________________________
Embeddings (input)
1st layer:
- Self-attention
- Dropout
- Concat (residual connection)
- Normalization
- Feed-forward
- Dropout
- Concat (residual connection)
- Normalization

More layers..
____________________________

I would appreciate some comments on this, as I guess it is not behaving as expected

Thanks

**Comment by francoishernandez** [comment]
This is what is called 'Pre-Norm'.
https://github.com/OpenNMT/OpenNMT-py/blob/fa7f888de1607618d4ee04a3f5e9150021937410/onmt/decoders/transformer.py#L15-L19

(Not sure why we have a comment on the decoder but not encoder though.)

Section 2 of [this paper](https://arxiv.org/abs/1906.01787) details the rationale a bit. You can probably find more searching for 'pre-norm transformer'.

**Comment by anderleich** [comment]
Thanks for the clarification. Is dropout also discarded after the FF net?

**Comment by francoishernandez** [comment]
See the definition of `PositionalFeedForward`, dropout and concat happen there.

https://github.com/OpenNMT/OpenNMT-py/blob/fa7f888de1607618d4ee04a3f5e9150021937410/onmt/modules/position_ffn.py#L6-L37

**Comment by anderleich** [comment]
Thanks! That was the answer
