### ISSUE TITLE
Error in decoding Gujarati Subwords

### ISSUE THREAD

**Issue by Vedant-06** [OpenNMT/OpenNMT-py#1954]
Hi, I was using OpenNMT for English to Gujarati Translation. I used sentence piece transform for Gujarati Corpus. I trained the model for 70k sentences. But when I use `translate.py` for the output and printed out the verbose, I found that most of the subwords were being mapped to the `<unk>` tag. 

Eg.

```
[2020-11-30 12:07:40,417 INFO]
SENT 1: ['but', 'some', 'really', 'good', 'work', 'is', 'being', 'done', 'around', 'us', ',', 'in', 'our', 'society', '.', 'and', 'all', 'this', 'has', 'been', 'possible', 'through', 'the', 'collective', 'efforts', 'of', 'a', '130', 'crore', 'countrymen', '.']
PRED 1: ▁છત <unk> <unk> ▁કરવા . . . . ▁સમગ્ર ▁ચ વ ર્ક ી સુર ક્ષ િત ▁અને ▁સમગ્ર ત ▁વધાર ો ▁છે ▁.
PRED SCORE: -30.2231
GOLD 1: <unk> <unk> <unk> <unk> <unk> <unk> <unk> આપણી <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> તે <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> .
GOLD SCORE: -674.3291

[2020-11-30 12:07:40,417 INFO]
SENT 2: ['this', 'can', 'pave', 'a', 'new', 'way', 'to', 'serve', 'the', 'purpose', 'of', 'ek', 'bharat', 'shresht', 'bharat', 'abhiyan', ',', 'ultimately', 'providing', 'a', 'great', 'boost', 'to', 'india’s', 'tourism', 'development', '.']
PRED 2: ▁સરપંચ ▁છું ▁ , ▁વિમુદ્રીકરણ ▁ <unk> ▁ , ▁ડેરી ▁ઉદ્યોગ નું ▁ઉદ્ઘાટન ▁કરવું ▁ , ▁ડેરી ઓ ▁ ,
PRED SCORE: -21.4394
GOLD 2: <unk> એક ભારત , શ્રેષ્ઠ ભારત <unk> <unk> પૂર્ણ <unk> <unk> માર્ગ <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> .
GOLD SCORE: -431.0326

```

So is there any specific format, the input has to be given? Please guide me with this issue.
Thanks in advance.

Here GOLD Sentences are target ground truth sentences.

**Comment by francoishernandez** [comment]
You probably have an issue in your vocabulary. Which version are you using?

**Comment by Vedant-06** [comment]
I am using version 2. And I have attached the target vocab file for your reference.
[tgt.vocab.txt](https://github.com/OpenNMT/OpenNMT-py/files/5622452/tgt.vocab.txt)

**Comment by francoishernandez** [comment]
What's your training config? How many steps did you train before performing inference?
What are your training metrics? accuracy and loss/ppl ?
Do you have a valid set ? What are the validation metrics ?

**Comment by Vedant-06** [comment]
Training Config: [config.yaml.txt](https://github.com/OpenNMT/OpenNMT-py/files/5623663/config.yaml.txt)
Total Training Steps: 200000
I am using ppl as performance metrics both for training and Validation Set.
Logging File: [logging.txt](https://github.com/OpenNMT/OpenNMT-py/files/5623695/logging.txt)

**Comment by francoishernandez** [comment]
Oh, it seems there is an error that is not properly raised (should stop the whole process normally):
```
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    main()
  File "/home/irlab/Documents/Share/Vedant/Indic-Neural-Machine-Translation/OpenNMT/onmt/bin/train.py", line 169, in main
    train(opt)
  File "/home/irlab/Documents/Share/Vedant/Indic-Neural-Machine-Translation/OpenNMT/onmt/bin/train.py", line 154, in train
    train_process(opt, device_id=0)
  File "/home/irlab/Documents/Share/Vedant/Indic-Neural-Machine-Translation/OpenNMT/onmt/train_single.py", line 73, in main
    _train_iter = _build_train_iter(opt, fields, transforms_cls)
  File "/home/irlab/Documents/Share/Vedant/Indic-Neural-Machine-Translation/OpenNMT/onmt/train_single.py", line 45, in _build_train_iter
    stride=stride, offset=offset)
  File "/home/irlab/Documents/Share/Vedant/Indic-Neural-Machine-Translation/OpenNMT/onmt/inputters/dynamic_iterator.py", line 195, in build_dynamic_dataset_iter
    transforms = make_transforms(opts, transforms_cls, fields)
  File "/home/irlab/Documents/Share/Vedant/Indic-Neural-Machine-Translation/OpenNMT/onmt/transforms/transform.py", line 221, in make_transforms
    transform_obj.warm_up(vocabs)
  File "/home/irlab/Documents/Share/Vedant/Indic-Neural-Machine-Translation/OpenNMT/onmt/transforms/tokenize.py", line 210, in warm_up
    from subword_nmt.apply_bpe import BPE, read_vocabulary
ModuleNotFoundError: No module named 'subword_nmt'
```
--> you might want to install [subword-nmt](https://github.com/rsennrich/subword-nmt) or switch to the `onmt_tokenize` transform if you're using `pyonmttok`.

In your current training I think the error is just ignored, hence your source is not properly tokenized. It's overfitting very quickly, most probably because it learns to produce only `<unk>` tokens.

@Zenglinxiao we should probably check the transforms codepaths to see if we could raise such errors properly.

**Comment by Vedant-06** [comment]
Thank for your suggestions, I will try that .
