### ISSUE TITLE
Upgrade torchtext to more recent releases

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/OpenNMT-py#1956]
This warning is raised when using torchtext 0.8.0:
```
warnings.warn('Example class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.', UserWarning)
/usr/local/lib/python3.6/dist-packages/torchtext/data/iterator.py:48: UserWarning: OrderedIterator class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
```

We should investigate the changes needed to make a more up to date usage of torchtext classes.

**Comment by francoishernandez** [comment]
Else, we can always freeze to some version in the mean time.

**Comment by guillaumekln** [comment]
In the short term, can the package be upgraded to at least 0.5.0? This will prevent an error when releasing models to CTranslate2 (cf. https://github.com/OpenNMT/CTranslate2/issues/109).

**Comment by francoishernandez** [comment]
I think 0.5.0 should be safe. I upgraded the version in #1980.
I'll let this issue open though, as it would still probably be a good idea to investigate further more recent versions of torchtext at some point.

**Comment by vince62s** [comment]
https://github.com/pytorch/text/issues/969
In fact I think we need to get rid of torchtext completely.
Even if we keep it, there are some major changes to implement because Fields are deprecated.
My suggestion is to switch completely to Dataloader from pytorch. SHoud be way easier to support.

@anderleich @Zenglinxiao @francoishernandez any better idea ?

**Comment by Zenglinxiao** [comment]
> Even if we keep it, there are some major changes to implement because Fields are deprecated.
> My suggestion is to switch completely to Dataloader from pytorch. SHoud be way easier to support.

Yes, I agree. There are not many benefits left to continue using deprecated torchtext except the back-compatibility issue. It would be much better to directly rely on torch.utils.data for data loading as in many other major NLP frameworks.

**Comment by vince62s** [comment]
Goodbye Torchtext with OpenNMT-py v3.0
