### ISSUE TITLE
Changing input for Transformer

### ISSUE THREAD

**Issue by anderleich** [OpenNMT/OpenNMT-py#1957]
Hi,

I'm interested in adding some extra information to the embeddings to train a Transformer. Which are the key files I need to change? I found where batches are passed to the encoder and the decoder, and where the embeddings are computed. However, I can't find the exact location corpus files are parsed and iterated through.

I guess `train_iterator` is key here

The idea is:

1. Have the information stored in the corpus file along with the sentences.
2. Create information embeddings
3. Sum these embedding with word embeddings (no change in dimension)
4. Train

Thanks

**Comment by francoishernandez** [comment]
The data loading part mostly happens here:
https://github.com/OpenNMT/OpenNMT-py/blob/fa7f888de1607618d4ee04a3f5e9150021937410/onmt/inputters/corpus.py#L107

You can take the example of the optional `align` field, which requires an additional file, and then we check if the value exists:
https://github.com/OpenNMT/OpenNMT-py/blob/fa7f888de1607618d4ee04a3f5e9150021937410/onmt/inputters/corpus.py#L75-L76

Then you will indeed retrieve these examples/batches in your train_iter, and can do what you want of it in the model parts.

**Comment by anderleich** [comment]
Thanks!!

**Comment by anderleich** [comment]
One more thing. Where are source features separated from tokens and stored?

**Comment by francoishernandez** [comment]
I already hinted to that here: https://forum.opennmt.net/t/opennmt-py-2-0-release/3962/5?u=francoishernandez

The _feature_tokenize function is still there, but there needs to be some adaptations:
https://github.com/OpenNMT/OpenNMT-py/blob/1b1e6c1ce5b29d09e87881797dce786148f51090/onmt/inputters/text_dataset.py#L179

It should not be very difficult, but requires a bit of time and testing, the main topic being the building of the vocab for the feature fields. If you wish to contribute to add back support for such source features, we would gladly accept a PR.

**Comment by anderleich** [comment]
I was asking that because I need to store some information about each token but not as a source feature appended to word embedding but added to the word embedding. Same thing it is done with positional encoding, adding word embeddings with another embedding. This information would be on the corpus file.

**Comment by francoishernandez** [comment]
These are two different things:
- how to retrieve the feature stuff from the corpus file;
- what to do with it.

Basically you would need the following:
1. build a vocab of your features ["A", "B", "C"]
2. build the corresponding embeddings
3. merge the main embeddings and your feature embeddings with a chosen strategy.

--> 1. is the main missing part that we did not implement yet in OpenNMT-py 2.0
--> 2. and 3. are handled in the `Embeddings` class here:
https://github.com/OpenNMT/OpenNMT-py/blob/bdc245b15aeeee405bc54d89f8cbbaffbfe6b329/onmt/modules/embeddings.py#L59

E.g. `feat_merge` flag.

**Comment by anderleich** [comment]
Thanks for taking your time! That should help me implementing it.

**Comment by anderleich** [comment]
Hi @francoishernandez,

I've managed to:
1. build vocabulary of the extra information
2. build the corresponding embeddings from vocab
3. merge word embeddings after the positional encoding with my information embeddings

I've tried to run the system on the CPU and it works. However, when sending it to the GPU I got the following error:
`RuntimeError: Input, output and indices must be on the current device`
This happens when generating the embeddings from input information on the decoder. Where should I set the device for those embeddings? I mean, where are the embeddings for src and tgt moved to GPU?

Thanks

**Comment by anderleich** [comment]
I've managed to train the system. Now I want to traslate some sentences using onmt_translate.
I have a question regarding this line:
https://github.com/OpenNMT/OpenNMT-py/blob/f46a4da48efd3df5f7abd7ef7bc2b8860a6f7025/onmt/translate/translator.py#L822

My batch is as follows:
```
[torchtext.data.batch.Batch of size 2]
	[.src]:('[torch.LongTensor of size 10x2x1]', '[torch.LongTensor of size 2]')
	[.indices]:[torch.LongTensor of size 2]
	[.info]:[torch.LongTensor of size 1x2]
```
And the line result is:
`torch.Size([1, 10, 1])`

What does the 10 mean? Is it generating a 10 tokens long sequence? Shouldn't it be 2, one token for each sentence at the beginning of the beam search?

Thanks

**Comment by anderleich** [comment]
I found each example in a batch is multiplied by beam_size.
When training info consists of a single token and its embedding is added to each target word.
With the beam search strategy, I first need to augment batch examples by copying each example beam_size times. However, beam_size seems to decrease when some hypotheses are finished, so this is not the variable I'm looking for, isn't it?
