### ISSUE TITLE
Test Perplexity with or without Teacher Forcing?

### ISSUE THREAD

**Issue by zhongpeixiang** [OpenNMT/OpenNMT-py#1959]
In (conditional) language modelling, the perplexity measures the probability of groundtruth sentences. I'm wondering whether the test perplexity should be computed with or without teacher forcing? 

In [current implementation](https://github.com/OpenNMT/OpenNMT-py/blob/7cbfbb38190baa0a7b98260435c47fa6beb13461/onmt/translate/translator.py#L874), the test perplexity is computed with teacher forcing. In this case, the test perplexity is independent of the decoding algorithm, e.g., beam search with various widths.

However, there are many other sources ([here](https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html#evaluation) and [here](https://github.com/bentrevett/pytorch-seq2seq/blob/master/1%20-%20Sequence%20to%20Sequence%20Learning%20with%20Neural%20Networks.ipynb)) where the test perplexity is computed without teacher forcing. In this case, the test perplexity depends on the decoding algorithm.

Which way is more appropriate? and which way is used in academic papers in langauge modelling and machine translation?

**Comment by Zenglinxiao** [comment]
Hello @zhongpeixiang,
The lines you're referring are actually computing the gold score (summed log probability for a given target sentence using the model). As it's for a provided target sentence, it has nothing to do with the decoding algorithm, and will only be computed when you provide one(by option `--tgt`).

As you are mentioning teacher forcing in the two sources, I've only found the referred term and code in the second one:
```markdown
we will sometimes use the actual, ground truth next word in the sequence, $y_t$ and sometimes use the word predicted by our decoder, $\hat{y}_{t-1}$. This is called teacher forcing
```
```python
class Seq2Seq(nn.Module):
...
    def forward(self, src, trg, teacher_forcing_ratio = 0.5):
        ...
        #teacher_forcing_ratio is probability to use teacher forcing
        for t in range(1, trg_len):
           ...
            #decide if we are going to use teacher forcing or not
            teacher_force = random.random() < teacher_forcing_ratio
            
            #get the highest predicted token from our predictions
            top1 = output.argmax(1) 
            
            #if teacher forcing, use actual next token as next input
            #if not, use predicted token
            input = trg[t] if teacher_force else top1
            ...
```
```python
def evaluate():
   ...
   output = model(src, trg, 0) #turn off teacher forcing
```
But if you look carefully in our code, what we're doing is actually always feed the golden target when training/evaluate, in the inference time, we feed always current predicted words to the next step. If we use the term teacher forcing that will be teacher forcing during training and no teacher forcing during inference. We'll use teacher forcing to get the gold score before doing real inference if provide a golden target by `--tgt` but that's not "test perplexity".

**Comment by zhongpeixiang** [comment]
Thank you for the detailed reply. 

If the gold score is not the test perplexity, how could I calculate the test perplexity like those done in language modelling? With or without teacher forcing?

**Comment by zhongpeixiang** [comment]
It seem that teacher forcing is used in evaluating test perplexity: https://github.com/pytorch/examples/blob/a3f28a26851867b314f4471ec6ca1c2c048217f1/word_language_model/main.py#L138

**Comment by Zenglinxiao** [comment]
In machine translation, we evaluate model performance with BLEU score rather than perplexity. As OpenNMT is more oriented as a toolkit for machine translation (language model is only added recently, so some stuff may not be so complete.)
Usually in NMT, we generate the translation(say hypothesis) and then use that translation to calculate BLEU score using sacrebleu or script from Moses, when computing the BLEU score, it's computed w.r.t provided reference translation(say target).
That's why in inference(translate.py), there is no teacher forcing.
Since you want to get the perplexity for language modeling, then you can do this. But you may need some extra effort, like writing some code and may attention to the ppl calculated(reduced by sum in inference while mean in training).

**Comment by zhongpeixiang** [comment]
Thank you for the explanation.
