### ISSUE TITLE
Refactor code to pass needed options into each class explicitly.

### ISSUE THREAD

**Issue by JianyuZhan** [OpenNMT/OpenNMT-py#196]
This is not a bug.

Currently each class takes the global `opt `argument, which is not a good practice. Because we need a more clean-cut interface of each class to de-entangle the code and thus facilitate future unittest. 

The goal is to expose each class's needed options in its constructor, thus making the interface less entangled, and also expose more opportunities for further re-factorization and/or optimization.

This issue is thus open for this re-factorization work.

**Comment by JianyuZhan** [comment]
The first part is done in this pull request: https://github.com/OpenNMT/OpenNMT-py/pull/197

**Comment by srush** [comment]
Cool, checking it out. Note that @bpopeters was also working on this for Embedding, so maybe sync with him.

**Comment by JianyuZhan** [comment]
The second part is done in this PR: https://github.com/OpenNMT/OpenNMT-py/pull/219

Refactored class: `ImageEncoder`

Later series will be on `Decoder` and related classes.

**Comment by JianyuZhan** [comment]
The third part is done in this PR: https://github.com/OpenNMT/OpenNMT-py/pull/228

Refactored class `Decoder`.
