### ISSUE TITLE
Difference in final BLEU score

### ISSUE THREAD

**Issue by aloka-fernando** [OpenNMT/OpenNMT-py#1962]
The BLEU score obtained from OpenNMT  and the BLEU score obtained by directly calculating from the multi-bleu.perl script seems to be different.
with OpenNMT I get BLEU = 21.91 and from the script the its BLEU = 24.83.
What would be the reason for the diviation?

**Comment by Zenglinxiao** [comment]
What do you mean by BLEU score obtained from OpenNMT?
OpenNMT does not calculate BLEU score in its source code, you need to use a script for this after getting the translation. We usually use sacrebleu or script from Moses.

**Comment by aloka-fernando** [comment]
I have used the same scripts mentioned. What I wanted to confirm is whether the BLEU calculation (sacrebleu or script from moses) in OpenNMT is calculated at the mini batch level and aggregated? and there by causing any difference.

**Comment by francoishernandez** [comment]
@aloka-fernando you need to be more explicit. There is no BLEU "calculated in OpenNMT".
Post command lines if needed.

**Comment by aloka-fernando** [comment]
It's clear now. @francoishernandez Thanks.
