### ISSUE TITLE
ONMT sever behind Apache

### ISSUE THREAD

**Issue by anderleich** [OpenNMT/OpenNMT-py#1964]
Hi,

I'm trying to run the server behind Apache2. I've created the following WSGI file:

```
import sys
sys.path.insert(0, '/working_dir/OpenNMT-py/onmt/bin/')
from server import start
application=start("/working_dir/server.config", url_root="/translator", port=6578)
```

Executing this file loads the server on the GPU without problems.

And this is the Apache2 configuration file:
```
<VirtualHost *:80>
     ServerName localhost

     WSGIDaemonProcess transformers python-path=/working_dir:/working_dir/OpenNMT-py python-home=/working_dir/venv 
     WSGIProcessGroup transformers                                                             
     WSGIScriptAlias / /working_dir/kk.wsgi

     <Directory /working_dir>
                <Files kk.wsgi>
                        Require all granted
                </Files>
     </Directory>

     ErrorLog /working_dir/logs/error.log
     LogLevel warn      
     CustomLog /working_dir/logs/access.log combined
</VirtualHost>
```

When executing `service apache2 start` it does not throw any error.

Then when calling the server:
 `curl -d '[{"src":"Test", "id":100}]' -X POST -H "Content-Type: application/json" http://localhost:80/translator/translate`

It seems it starts loading the server:
```
[Thu Dec 10 16:23:57.051009 2020] [wsgi:error] [pid 39474:tid 140016499951360] Pre-loading model 100
[Thu Dec 10 16:23:57.053677 2020] [wsgi:error] [pid 39474:tid 140016499951360] [2020-12-10 16:23:57,053 INFO] Loading tokenizer
[Thu Dec 10 16:23:57.080117 2020] [wsgi:error] [pid 39474:tid 140016499951360] [2020-12-10 16:23:57,080 INFO] Loading model 100
```

But it never loads the server on the GPU. Furthermore it seems it loads the server after the first request...

Any clues on this?

Thanks

**Comment by francoishernandez** [comment]
First step: does the server run properly when executing it as standalone script?

**Comment by anderleich** [comment]
Yes, it does. It loads the model on the GPU and performs translations. Even with the WSGI file

**Comment by anderleich** [comment]
Just for the record. When using mod_wsgi Python package to host the server it works correctly:

`mod_wsgi-express start-server /working_dir/wsgi.py --port 8080
`

**Comment by guillaumekln** [comment]
This is possibly related to https://forum.opennmt.net/t/docker-flask-server-timeout-when-calling-ctranslate-python-module/4112.

Can you look to disable multiprocessing? https://modwsgi.readthedocs.io/en/develop/user-guides/processes-and-threading.html

**Comment by anderleich** [comment]
I guess I should then set the number of processes to, say, 15 and the threads to 1. Is it correct?

**Comment by guillaumekln** [comment]
I think it would be the opposite to disable multiprocessing. But you should check the Apache/WSGI documentation, this is not related to OpenNMT-py.

**Comment by anderleich** [comment]
According to WSGIDaemonProcess, if not set, process is 1 and threads 15. So it seems it is not multiprocessing...

> processes=num
> Defines the number of daemon processes that should be started in this process group. If not defined then only one process will be run in this process group.

> threads=num
> Defines the number of threads to be created to handle requests in each daemon process within the process group.
> 
> If this option is not defined then the default will be to create 15 threads in each daemon process within the process group.

**Comment by anderleich** [comment]
I've seen OpenNMT-py server is running on Waitress. Is it really necessary to use apache mod_wsgi to host the server in a production environment?

**Comment by francoishernandez** [comment]
From `waitress` docs:
> Waitress is meant to be a production-quality pure-Python WSGI server with very acceptable performance.

Also, it's multi-threaded so it should be able to handle multiple concurrent requests.

Anyways, I think this is more an environment specific decision you have to make on your end, and not really an issue with the project. For further discussion, you might want to open a thread on the forum.
