### ISSUE TITLE
adding checkpoints to the GPUs.

### ISSUE THREAD

**Issue by hozayfarifai** [OpenNMT/OpenNMT-py#1967]
I am having a dataset of size 11G. Below, I am only sharing the important pre-processing attributes along with the training parameters:

1- pre-processing

```
    onmt_preprocess --train_src src.txt  --train_tgt tgt.txt \
    --valid_src src_dev.txt --valid_tgt tgt_dev.txt \
    --overwrite --src_vocab_size -1 --tgt_vocab_size -1 \
    --num_threads 4 --shard_size 10000
```

2- training 

```
    CUDA_VISIBLE_DEVICES=$visible_gpus onmt_train --model_type text --encoder_type transformer --decoder_type transformer \
    --accum_count 2 --learning_rate 2.0  \
    --save_checkpoint_steps 10000 --keep_checkpoint -1 \
    --train_steps 200000 --valid_steps 10000 --warmup_steps 800
```

I am training on 4 GPUs, each has a size of 12G. when I checked the folder that has all the dataset checkpoints, its size was 15G. The issue i am currently having is that each checkpoint is being loaded on the GPU. After couple of checkpoints loads, the memory in each GPU is full and i get this error: 

    RuntimeError: CUDA out of memory. Tried to allocate 2.04 GiB (GPU 0; 10.92 GiB total capacity; 5.54 GiB already allocated; 1.75 GiB free; 8.44 GiB reserved in total by PyTorch).

I was looking for a way to save only the model on the gpu and not adding the datasets on the GPU. any idea how this can be achieved. ?

**Comment by francoishernandez** [comment]
You might want to try to reduce the batch_size, and use batch_type tokens. You can follow the example transformer configuration in the docs.

**Comment by hozayfarifai** [comment]
I have already tried setting the batch_size to 1 and I am already using batch_type tokens. I wanted to ask if there is a way of putting the pressure on the ram and not the gpu.

**Comment by francoishernandez** [comment]
Something else must be wrong. You should not have any issue fitting a basic transformer model on 12G GPUs.
For transformer you need to explicitly add specific values for some hyperparams. You may try a config like the one here: https://opennmt.net/OpenNMT-py/examples/Translation.html#step-2-train-the-model

**Comment by francoishernandez** [comment]
Also, does this error happen at validation? Sometimes it is necessary to reduce the valid_batch_size to prevent such errors.

**Comment by hozayfarifai** [comment]
the error occurs exactly at step 10k. when reaching step number 10k. it loads the checkpoints and then i get this error:
<img width="775" alt="Screen Shot 2020-12-23 at 12 10 35 PM" src="https://user-images.githubusercontent.com/68183403/102974602-3d9a8300-4518-11eb-9e2f-eb640fc24ab3.png">

if i scroll down, here is the main error: 
<img width="1085" alt="Screen Shot 2020-12-23 at 12 14 42 PM" src="https://user-images.githubusercontent.com/68183403/102974746-7c303d80-4518-11eb-9303-7136d7d70cc8.png">

**Comment by funboarder13920** [comment]
Your validation and your model checkpoint are both set to 10K steps. In this case, validation scores are computed before checkpointing the model. In your logs, the validation scores do not appear before the error. As @francoishernandez suggested you should have a look at valid_batch_size and consider cutting long sequences in your validation set if you are not using the latest version of the code. In #1919 , we made a change so that batch_type is the same for training and validation.
