### ISSUE TITLE
A problem in computing ppl while validating

### ISSUE THREAD

**Issue by YQ-11** [OpenNMT/OpenNMT-py#1968]
I use the defalut wmt14_en_de.yaml to train a nmt model, carefully following Translation.md.
But I meet a problem in computing ppl while validating.
![image](https://user-images.githubusercontent.com/64119995/103145517-1d1c3400-4777-11eb-9b2f-a320751db05c.png)
How to solve this problem?

**Comment by francoishernandez** [comment]
Can you post your full configuration? Also, are your validation files ok? This error seems to indicate that there might be some empty lines or no content at all in your validation set.

**Comment by YQ-11** [comment]
> Can you post your full configuration? Also, are your validation files ok? This error seems to indicate that there might be some empty lines or no content at all in your validation set.

![image](https://user-images.githubusercontent.com/64119995/103534235-7861cb00-4ec9-11eb-8fb3-8aa2e139513c.png)
THANK YOU!!!! Indeed validation files are empty.
