### ISSUE TITLE
Version installed with pip is different than that from the source

### ISSUE THREAD

**Issue by ymoslem** [OpenNMT/OpenNMT-py#1977]
When I download OpenNMT-py using git and install it from the source, it installs version 2; however, when I install it using pip, it installs version 1. Is this (temporarily) intentional? If not, I think it might cause confusion. Thanks!

```
$ pip3 install opennmt-py

Collecting opennmt-py
  Downloading OpenNMT_py-1.2.0-py3-none-any.whl (195 kB)
```
```
$ pip3 freeze | grep -i "opennmt"

OpenNMT-py==1.2.0
```

---
```
$ git clone https://github.com/OpenNMT/OpenNMT-py.git
$ cd OpenNMT-py
$ python3 setup.py install

...
Finished processing dependencies for OpenNMT-py==2.0.0rc2
```
```
$ pip3 freeze | grep -i "opennmt"

OpenNMT-py==2.0.0rc2
```

**Comment by francoishernandez** [comment]
This is because it's still rc and not properly released. We should do the 2.0 release soon.
You can still install 2.0 rc with pip though, by specifying the explicit version. (https://pypi.org/project/OpenNMT-py/2.0.0rc2/)
