### ISSUE TITLE
Training Stuck at start: Training on 2 GPUs

### ISSUE THREAD

**Issue by i55code** [OpenNMT/OpenNMT-py#1981]
Hi all, I have a machine with 2 GPUs. And I train an experiment using: CUDA_VISIBLE_DEVICES=0,1 \
                    onmt_train \ 
                    ...
                    -world_size 2 \
                    -gpu_ranks 0 1 \

Preveiously, training an experiment on two GPUs works fine. However, starting from today that the training get stuck right at the start of the training: 
[2021-01-04 18:01:31,220 INFO] Starting training on GPU: [0, 1]
[2021-01-04 18:01:31,220 INFO] Start training loop and validate every 10000 steps...
(then there is no updates) 

May you share some insights with how to fix this?

**Comment by francoishernandez** [comment]
I'm not sure what could be happening here. Maybe some strange behavior of NCCL. We had some cases in the past where training would get stuck (not right at beginning though).

**Comment by chijianlei** [comment]
I have the same question, I find that pytorch 1.7 has some strange behaviors of NCCL, which is fixed in 1.8

**Comment by Zhw098** [comment]
Hi, I also have the same question, Do you know why?
pytorch=1.5 OpenNMT=0.4 Python=3.6
Thanks!

**Comment by chijianlei** [comment]
It seems that the version you chose is too old.

**Comment by Zhw098** [comment]
> It seems that the version you chose is too old.

I am very happy to receive your reply. Which version do you use?
I am a new opennmt-er. 
Thanks!

**Comment by SamraMehboob** [comment]
Hi,
Can anyone help to resolve this issue?

**Comment by vince62s** [comment]
reopen if you face the issue again
