### ISSUE TITLE
learn_bpe.py for multiple files as input to generate one bpe model file

### ISSUE THREAD

**Issue by ishaansharma** [OpenNMT/OpenNMT-py#1982]
Respected Fellow Researchers, 
I am trying to generate BPE Model using  [learn_bpe.py](https://github.com/OpenNMT/OpenNMT-py/blob/master/tools/learn_bpe.py). As per my problem statemement I am required to
generate BPE model using multiple file. I am using the following command to perform this task:
`python OpenNMT-py/tools/learn_bpe.py -i data_1.txt -i data_2.txt -i data_3.txt -o bpe_model.code -s 30000`

I want to know if this script can be used to generate BPE model from multiple files (more than 2)or I am doing something wrong here. Or this script can be used to generate BPE model from only one file. 

Secondly I have come across this repository ([fastBPE](https://github.com/glample/fastBPE#learn-codes)) which takes maximum of two files as input to learn BPE and generate BPE model. 
`./fast learnbpe 40000 train.de train.en > codes`

Regards

**Comment by Zenglinxiao** [comment]
The command you gave is not allowed. Every argument can be given only once. But as the `--input` argument of `learn_bpe.py` is stdin, you can concatenate files using `cat` like this:
```
cat data_1.txt ... data_x.txt | python learn_bpe.py -o bpe_model.code -s 30000
```

**Comment by ishaansharma** [comment]
> The command you gave is not allowed. Every argument can be given only once. But as the `--input` argument of `learn_bpe.py` is stdin, you can concatenate files using `cat` like this:
> 
> ```
> cat data_1.txt ... data_x.txt | python learn_bpe.py -o bpe_model.code -s 30000
> ```

Thank you @Zenglinxiao . this solves the issue.
