### ISSUE TITLE
AttributeError: 'Nonetype' object has no attribute 'dynamic_dict'

### ISSUE THREAD

**Issue by xjtu-zeng** [OpenNMT/OpenNMT-py#199]
When I run **translate.py** with **-tgt**， i encountered this problem.

**Comment by srush** [comment]
Yeah, we are in the process of fixing -tgt and improving beam search. Follow this issue https://github.com/OpenNMT/OpenNMT-py/issues/188 and this PR https://github.com/OpenNMT/OpenNMT-py/pull/195

**Comment by srush** [comment]
Should be fixed.

**Comment by xjtu-zeng** [comment]
I met another issue when use **translate.py**, following the three steps in the **Quickstart**.
**_IndexError: list index out of range_**
![image](https://user-images.githubusercontent.com/15373554/29804993-635a5b80-8cb9-11e7-894b-a9461cced1e3.png)
