### ISSUE TITLE
Cross Validation

### ISSUE THREAD

**Issue by mayaKaplansky** [OpenNMT/OpenNMT-py#1992]
Hi
I couldn't find in your website info about cross validation. Can you give me some details on how its been implemented?
Many thanks!

**Comment by francoishernandez** [comment]
It's not. It would not be realistic for most setups, as training a single model is already resource hungry. You may do this 'manually' though, by defining your training and validation sets before hand.

**Comment by mayaKaplansky** [comment]
Understood. So what is being done with the validation file we provide as input? Is it used to calculate the metrics at each step checkpoint?

**Comment by francoishernandez** [comment]
It's used to compute validation metrics, periodically during training (`valid_steps` flag). Just not "cross" validation.
