### ISSUE TITLE
ask for decoding method

### ISSUE THREAD

**Issue by leileilin** [OpenNMT/OpenNMT-py#1993]
I would like to consult which methods the system supports for decoding.
Does it support streaming decoding, forced decoding, or incremental decoding?

**Comment by leileilin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        thank you man. but in this page, i only see some decoding tricks, not the methods that i want.
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1299192319
                            
                    
                        
                            
                                    1299192319@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 1/18/2021 18:38，François Hernandez<notifications@github.com> wrote： 



The various options for inference can be found here in the docs.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by francoishernandez** [comment]
I fear you will have to implement these methods yourself, either in a client using the translation server, or in some custom code using the `onmt.translate` library.
