### ISSUE TITLE
ask for path of data and configuration file

### ISSUE THREAD

**Issue by sjchasel** [OpenNMT/OpenNMT-py#1999]
Hi!
My files are as follows
![image.png](https://i.loli.net/2021/01/27/oniNO6qf2XkWyVb.png)

they are in `home\yons\OpenNMT-kpg-release-new\data\keyphrase\meng17\kp20k`.

My configuration file uses `data:  /home/yons/OpenNMT-kpg-release-new/data/keyphrase/meng17/kp20k` to assign data and it is in `home\yons\OpenNMT-kpg-release-new\config\train`.

Then I use `python train.py -config config/train/config-rnn-keyphrase-one2seq-diverse.yml` under `OpenNMT-kpg-release-new`. It reports an error which is

`Traceback (most recent call last):
  File "train.py", line 6, in <module>
    main()
  File "/home/yons/OpenNMT-kpg-release-new/onmt/bin/train.py", line 274, in main
    train(opt)
  File "/home/yons/OpenNMT-kpg-release-new/onmt/bin/train.py", line 126, in train
    train_iter = build_dataset_iter(shard_base, fields, opt)
  File "/home/yons/OpenNMT-kpg-release-new/onmt/inputters/inputter.py", line 1220, in build_dataset_iter
    raise ValueError('Training data %s not found' % opt.data)
ValueError: Training data /home/yons/OpenNMT-kpg-release-new/data/keyphrase/meng17/kp20k not found`

Is there something wrong with the way I assign the data?

**Comment by francoishernandez** [comment]
Looks like you're using a fork, based on some older version of OpenNMT-py. You might want to ask your question there for more details, but it seems to me your issue is that you just did not preprocess the data.

**Comment by sjchasel** [comment]
> Looks like you're using a fork, based on some older version of OpenNMT-py. You might want to ask your question there for more details, but it seems to me your issue is that you just did not preprocess the data.

you mean if I preprocess my data then I can get pt files and jsonl files?

**Comment by francoishernandez** [comment]
I don't know about "jsonl" files, but in original OpenNMT-py preprocessing was indeed creating .pt files.
You really need to ask the questions on the repo you're using. It is not part of the scope of OpenNMT and we don't know about any specifics of their implementation.

**Comment by sjchasel** [comment]
OK! Thanks a lot. I understand.
