### ISSUE TITLE
How to use either Encoder or Decoder from a trained (saved) Transformer model

### ISSUE THREAD

**Issue by R11Raj** [OpenNMT/OpenNMT-py#2005]
Hello Folks ,
I am doing some implementations for NMT in Indic languages , in one of the implementations I need to use encoder from one of the saved models and decoder from one of the saved ones ,  And combined them together to form a single transformer model. 

Is it possible in OpenNMT-py ? How it can be done ?

**Comment by francoishernandez** [comment]
There is no predefined method to do that, but it should be doable without too much hassle.
You can probably load your models, and then retrieve the parameters from the decoder of one to replace the decoder of the other, something like:
```
import torch
modelA = torch.load("modelA.pt")
modelB = torch.load("modelB.pt")
# I don't remember the exact structure but you will probably find it quickly by looking at the object
modelA.decoder = modelB.decoder
torch.save(modelA, "modelAB.pt")

**Comment by R11Raj** [comment]
Thank You for the answer 

Not the exact answer but the structure was similar to what you have suggested above
