### ISSUE TITLE
SentencePiece Training

### ISSUE THREAD

**Issue by henry8th** [OpenNMT/OpenNMT-py#2007]
Hello! 
Thanks for awesome library.
Just a quick question, when training sentence piece model do I have to train on src or tgt language or perhaps both?
Thank you!

**Comment by francoishernandez** [comment]
It depends on what the sentencepiece model is for... If you want to apply it to your source, you'd better train on the source, and if target then train on target.
If you want to train a model with shared vocab / embeddings, then you might want to train your sentencepiece model on both.
