### ISSUE TITLE
Computation of BLEU score for generated translations

### ISSUE THREAD

**Issue by R11Raj** [OpenNMT/OpenNMT-py#2008]
I am developing some NMT models and I am stuck at computation of BLEU score for generated translations.

I am generating 1000 sentence translations for test data but I read that taking BLEU score for Individual sentences and averaging them will not give the exact BLEU score of model.

I want to know what is the standard process to compute BLEU score for a model and if possible give me some script.

**Comment by francoishernandez** [comment]
[sacrebleu](https://github.com/mjpost/sacreBLEU) is what you're looking for.
