### ISSUE TITLE
Character-based Neural Machine Translation

### ISSUE THREAD

**Issue by wuhaixutab** [OpenNMT/OpenNMT-py#201]
Where did you implement Character-based Neural Machine Translation? Or, how to set the parameters if I want to train a character-based model?

**Comment by srush** [comment]
You shouldn't need to do anything differently. Just give your input as characters (and make a special <space> token), when you feed it to preprocess.py.

**Comment by wuhaixutab** [comment]
Thank you！I tried character-based translation and it works well. In details, where did you implement this ?

**Comment by srush** [comment]
We don't do anything different. It just treats the characters as words.

**Comment by wuhaixutab** [comment]
But in your homepage you said you implement [Character-based Neural Machine Translation](https://aclweb.org/anthology/P/P16/P16-2058.pdf), where they use CNN and start with character-based embedding to compute word representation. Since you said you implement this paper, you should do something different.

**Comment by srush** [comment]
Oh sorry, we don't implement that in this version. Where does it say that?

**Comment by wuhaixutab** [comment]
http://opennmt.net/about/ , in the Research section:

There are a lot of additional options on top of the baseline model. Specifically, there are functionalities which implement:

Effective Approaches to Attention-based Neural Machine Translation. Luong et al., EMNLP 2015.
Character-based Neural Machine Translation. Costa-Jussa and Fonollosa, ACL 2016.
