### ISSUE TITLE
Where are toy-ende/run/example.vocab.tgt and toy-ende/run/example.vocab.src located?

### ISSUE THREAD

**Issue by betanglao** [OpenNMT/OpenNMT-py#2010]
Nowhere to be found in the toy-ende folder

**Comment by francoishernandez** [comment]
Did you execute the `onmt_build_vocab` command as stated [here](https://opennmt.net/OpenNMT-py/quickstart.html#step-1-prepare-the-data)?

**Comment by betanglao** [comment]
I tried and it worked! Thank you
