### ISSUE TITLE
FAQ Dead link in README

### ISSUE THREAD

**Issue by brettfazio** [OpenNMT/OpenNMT-py#2015]
`For more advanded models and parameters, see other example configurations or the FAQ.` line in the readme contains a link to https://github.com/OpenNMT/OpenNMT-py/blob/master/FAQ which does not exist.

Is there an FAQ on the GitHub? Or should the link re-direct somewhere else?

**Comment by brettfazio** [comment]
I was specifically trying to read into how to use different types of models on training if there is a live link for that

**Comment by francoishernandez** [comment]
Indeed, there is no FAQ directly in the README anymore.
Please check the docs: https://opennmt.net/OpenNMT-py/FAQ.html
