### ISSUE TITLE
module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by betanglao** [OpenNMT/OpenNMT-py#2016]
i tried running `onmt_train -config toy_en_de.yaml`, but I got this error because Mac doesn't have CUDA. I tried everything here https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/67 , but none of it worked. Do you know how I can use CPU only?

**Comment by naghm3h** [comment]
Comment out the gpu_ranks line in the yaml file to train it on CPU.

**Comment by RealHinome** [comment]
Hey @naghm3h,

Maybe I'm idiot. Maybe I don't know how to read but, what we need to change on the "gpu_ranks"?
Can I have an example of the yaml file?

Thanks

**Comment by naghm3h** [comment]
Hope this help:

`# toy_en_de.yaml

## Where the samples will be written
save_data: toy-ende/run/example

# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: toy-ende/src-train.txt
        path_tgt: toy-ende/tgt-train.txt
    valid:
        path_src: toy-ende/src-val.txt
        path_tgt: toy-ende/tgt-val.txt

# Vocabulary files that were just created
src_vocab: toy-ende/run/example.vocab.src
tgt_vocab: toy-ende/run/example.vocab.tgt

# Train on a single GPU
world_size: 1
#gpu_ranks: [-1]

# Where to save the checkpoints
save_model: toy-ende/run/model
save_checkpoint_steps: 100
train_steps: 200
valid_steps: 100`

**Comment by RealHinome** [comment]
Thanks all for you help.
Have a nice day! 👋
