### ISSUE TITLE
Merging too many trained models into one.

### ISSUE THREAD

**Issue by 1BM18CS403** [OpenNMT/OpenNMT-py#2017]
After training, OpenNMT created .pt files for every 5000 steps. How to merge all those trained models into one. Or can we use last trained model for final model.

**Comment by francoishernandez** [comment]
You have to decide yourself, based on the metric of your choice, which checkpoint best fit your usage.
If you want to merge several checkpoints, you can use the `onmt_average_models` tool.

**Comment by 1BM18CS403** [comment]
Hello,

Thank you for your response But I'm new to OpenNMT Platform. I don't know
how to decide which model to consider. For better results. And would please
tell how many steps should I add before training for better results.

Thank you

**Comment by francoishernandez** [comment]
All this depends on your task and what you're trying to achieve.
You can find quite a lot of resources on the forum: https://forum.opennmt.net/
Also, in previous issues, such as https://github.com/OpenNMT/OpenNMT-py/issues/1637#issuecomment-553310037
