### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by aykutfirat** [OpenNMT/OpenNMT-py#202]
I am getting the following error when trying to load the pretrained en-fr model. <br> Can't get attribute 'StackedLSTM' on <module 'onmt.Models' from 'Github/OpenNMT-py/onmt/Models.py'> 
<br>
When do you think we can get pretrained models that work with the current codebase?

Thank you.

**Comment by srush** [comment]
Oh yes, we have been slow on this as pytorch has been changing. We will work on this right away.

**Comment by srush** [comment]
Okay, uploaded a 200k model, other models are training and will be up soon.

**Comment by prasadkawthekar** [comment]
Hi! I am wondering if there is a plan to upload checkpoints for the new code any time soon? Thanks!
