### ISSUE TITLE
errors when using multiple gpus

### ISSUE THREAD

**Issue by chijianlei** [OpenNMT/OpenNMT-py#2024]
I have tried to use three GTX 3090 to train my model. However, I received the exception like this:

Traceback (most recent call last):
  File "/root/OpenNMT-py/onmt/utils/distributed.py", line 200, in consumer
    gpu_rank = multi_init(opt, device_id)
  File "/root/OpenNMT-py/onmt/utils/distributed.py", line 25, in multi_init
    torch.distributed.init_process_group(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 442, in init_process_group
    barrier()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1947, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8

I have searched for that, [https://github.com/PyTorchLightning/pytorch-lightning/issues/5264](url) tells me this occurres only in pytorch 1.7, pytorch 1.8 has fixed this issue. 
However, the package named torchtext which is used in openNMT only supports less than 0.8 (supported for pytorch 1.7), one Class named torchtext.data.Field has been deprecated in 0.9 version (supported for pytorch 1.8).

In general, I'm facing a problem with support for 30 series NVIDIA graphics cards, does anyone have a solution?

**Comment by francoishernandez** [comment]
I don't have access to 30 series gpus unfortunately. 
A few things you could try:
- is torchtext 0.8 actually not working with torch 1.8?
- patch all the instances of `torchtext.data.Field` with `torchtext.legacy.data.Field` as mentioned in the [torchtext v.0.9 release notes](https://github.com/pytorch/text/releases/tag/v0.9.0-rc5).

Linked to #1956

**Comment by phuongnm-bkhn** [comment]
> 'm facing a problem with support for 30 series NVIDIA graphics cards, does anyone have a solution?

I have a workaround solution for the RTX 3090 card: 

pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchtext==0.8.0 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html 
(from: https://github.com/pytorch/pytorch/issues/47109#issuecomment-728131637 )

I tried and OpenNMT worked with torch 1.7 and torch text 0.8.0.

**Comment by chijianlei** [comment]
Now I have successfully run OpenNMT with torch 1.7.0 and torch text 0.8.0.
I have three GTX 3090s, a strange problem is that I can successfully run with GPU rank 0 and 1, but cannot run with 3 GPUs or with 0 and 2.
The exception is also a NCCL error, I guess the reason may be a hardware problem, I think I will use two graphics cards to complete my program.
Thank you for your reply.

**Comment by VarunnnxCode** [comment]
Which OpenNMT version did you use that's compatible with Torch, torchtext and torchvision?
