### ISSUE TITLE
Terminology Clarifications

### ISSUE THREAD

**Issue by kyledampier** [OpenNMT/OpenNMT-py#2025]
While training my model in OpenNMT, I had some questions on some of the terminologies for the parameters.

I was wondering what `effective_batch_size` means since we are already required to define a batch size in `training`. What effect does this have on the training of the model?

EDIT: Sorry, I submitted this request to the wrong GitHub repo

**Comment by guillaumekln** [comment]
https://github.com/OpenNMT/OpenNMT-tf/issues/813
