### ISSUE TITLE
UserWarning: Non-default `alpha` with no length penalty. `alpha` has no effect.   warnings.warn("Non-default `alpha` with no length penalty. "

### ISSUE THREAD

**Issue by Wangpeiyi9979** [OpenNMT/OpenNMT-py#2028]
Is alpha useless? How can we make the model produce longer output

**Comment by francoishernandez** [comment]
You need to enable `length_penalty`:
https://github.com/OpenNMT/OpenNMT-py/blob/2212db9ac2b913826764950cfdacdf8f7bee29a0/onmt/opts.py#L671-L672
