### ISSUE TITLE
when apply BPE  in translation_server.py, Invoked with: None

### ISSUE THREAD

**Issue by gdxie1** [OpenNMT/OpenNMT-py#2031]
When add bpe configuration in the conf.json as follows:
"tokenizer":{         
                "src":{
                    "type": "pyonmttok",
                    "mode": null,
                    "params":{
                        "bpe_model_path": "bpe/en.model"
                    }
                },
                 "tgt":{
                    "type": "pyonmttok",
                    "mode": null,
                    "params":{
                        "bpe_model_path": "bpe/ga.model"
                    }
                }
            }
Error happens at line of 688 of translation_server.py as:
Invoked with: None; kwargs: bpe_model_path='en.model'
![image](https://user-images.githubusercontent.com/52421565/113118879-c73ca980-9207-11eb-9d13-3357eb8fc7e6.png)
The solution should be like this: 
mode = None should be changed into mode = 'none'

**Comment by gdxie1** [comment]
I just realized that in the conf.json, I should use the "mode": 'none", rather than the "mode": null, then the error would not happen.

**Comment by francoishernandez** [comment]
Yes, this could be made a bit cleaner. Feel free to PR.
