### ISSUE TITLE
May I ask how to load a pretrained model and fine tuning by training on another dataset

### ISSUE THREAD

**Issue by itaowei** [OpenNMT/OpenNMT-py#2045]
This pretrained model is saved as a '.pt' file
Using yaml file? I cannot find how to do that...
Thanks in advance

**Comment by Zenglinxiao** [comment]
Hello @itaowei,
There is the `--train_from` option to load a saved checkpoint.
And to finetune it on another dataset, you just need to change the data config in your previous training YAML config file.

**Comment by itaowei** [comment]
> Hello @itaowei,
> There is the `--train_from` option to load a saved checkpoint.
> And to finetune it on another dataset, you just need to change the data config in your previous training YAML config file.

Thanks for your kind help!
