### ISSUE TITLE
how can I use -model_type img ?

### ISSUE THREAD

**Issue by StephenKyung** [OpenNMT/OpenNMT-py#2051]
I am following 'Image to Text' task(https://opennmt.net/OpenNMT-py/legacy/im2text.html)
but I got following error :
onmt_train: error: argument --model_type/-model_type: invalid choice: 'img' (choose from 'text')

my version:
OpenNMT-py v2.1.0

my command : 
onmt_train -config im2text.yaml

im2text.yaml file :

save_data: data/im2text/
src_vocab: data/im2text/example.vocab.src
tgt_vocab: data/im2text/example.vocab.tgt
overwrite: False

data:
    corpus_1:
        path_src: data/im2text/src-train.txt
        path_tgt: data/im2text/tgt-train.txt
    valid:
        path_src: data/im2text/src-val.txt
        path_tgt: data/im2text/tgt-val.txt

src_vocab: data/im2text/example.vocab.src
tgt_vocab: data/im2text/example.vocab.tgt

world_size: 1
gpu_ranks: [0]

save_model: model/im2text/
save_checkpoint_steps: 500
train_steps: 1000
valid_steps: 500

batch_size: 20
max_grad_norm: 20
learning_rate: 0.1
word_vec_size: 80
encoder_type: brnn
model_type: img
image_channel_size: 1

**Comment by francoishernandez** [comment]
These models are not supported from v2.
https://github.com/OpenNMT/OpenNMT-py#breaking-changes

You can try with the legacy / v1.2 version.

**Comment by StephenKyung** [comment]
thank you very much!!

**Comment by StephenKyung** [comment]
Thank you very much!
