### ISSUE TITLE
how to apply sru to decoder

### ISSUE THREAD

**Issue by LittleRooki** [OpenNMT/OpenNMT-py#2061]
Hi ! 
If I want to apply SRU to decoder, how should I set the parameters ？
Can you show me the configuration? I need some help

**Comment by francoishernandez** [comment]
#1935

**Comment by hangcao1004** [comment]
Thanks, I got it.
Do you have a trained model of transformer as encoder and SRU as decoder?
Or which version of OpenNMT I can train myself?
