### ISSUE TITLE
why is preprocess.py is removed? from the list

### ISSUE THREAD

**Issue by tarekegn2020** [OpenNMT/OpenNMT-py#2063]

**Comment by francoishernandez** [comment]
https://github.com/OpenNMT/OpenNMT-py#announcement---opennmt-py-20

https://forum.opennmt.net/t/opennmt-py-2-0-release/3962

**Comment by tarekegn2020** [comment]
thanks a lot ..but i am still struggling how to use this in google colab

**Comment by francoishernandez** [comment]
https://forum.opennmt.net/t/notebook-for-opennmt-py-2-x-quickstart/4143
