### ISSUE TITLE
Unable to run this command in google colab

### ISSUE THREAD

**Issue by IshanBorkar10038** [OpenNMT/OpenNMT-py#2069]
Dear author, I am running installation and model training steps for OpenNMT model inside google colab.
I have reached at step 1 prepare the data
But I am unable to run this command inside Google Colab: **head -n 5 src-train.txt**

Please suggest me some method to resolve this issue

**Comment by francoishernandez** [comment]
This is a basic colab question, in no way related to OpenNMT-py.
This might help you though: https://stackoverflow.com/a/52345902
