### ISSUE TITLE
role of the argument max_generator_batches

### ISSUE THREAD

**Issue by rkoystart** [OpenNMT/OpenNMT-py#2072]
Hi , I am new to the opennmt-py library. Can anyone explain what is the use of the argument max_generator_batches.
Thanks in advance.!!!!!!!!!

**Comment by BrightXiaoHan** [comment]
There is explanation in the document
```
Maximum batches of words in a sequence to run the generator on in parallel. Higher is faster, but uses more memory. Set to 0 to disable.
```

In the training phase, the decoder side can only generate one word at one time. It's impossible to generate all target sequences. So this parameter specifies the max generator batches. The bigger the number is, the more memory is needed.
