### ISSUE TITLE
Preprocess data and generate pt files

### ISSUE THREAD

**Issue by Tinarights** [OpenNMT/OpenNMT-py#2074]
Hello,

Where can I find preprocess.py ? 
and what are the steps to generate pt files of my custom data?
I have a multi documents as an input and a summary as an output.

Would anyone please let me know the steps of generating pt files?

**Comment by Zenglinxiao** [comment]
Hello @Tinarights,
The preprocess step has been removed from the v2.0 release, you can check #2063 for some useful links.

To train models, you only need raw text files if you're working on the master branch(v2.\*). Checkout [QuickStart](https://opennmt.net/OpenNMT-py/quickstart.html).
If you're working on the legacy branch(v1.\*), you do need to preprocess the data into binary files, QuickStart can be found in the [README of legacy branch](https://github.com/OpenNMT/OpenNMT-py/tree/legacy#quickstart).

Multi documents can be joint into a single corpus on you own and pass that resulting file as training corpus, or providing corpus configuration (path/weight/etc...) as detailed in the [doc](https://opennmt.net/OpenNMT-py/FAQ.html#how-can-i-weight-different-corpora-at-training).

**Comment by Tinarights** [comment]
Thank you very much @Zenglinxiao  for your reply. I will use legacy branch and I want to preprocess the data into pt files.

The details of my dataset:
The size of the data is around 1000,
input: several abstracts of scientific papers.
output: a summary of these papers.

for each examples, there are around 10 abstracts as an input, and one paragraph (summary) as an output.

Following your last link, should I process each example as a corpus? So in total I will have around 1000 training/val files?
Each src file contains the input abstracts of one example.

However, I did not understand the (weight: 3) which means 3 examples from this corpus.

Could you please help in this.

**Comment by Zenglinxiao** [comment]
Hello.
First of all, I suggest you follow some tutorials to get familiar with that task before working on your own data.
For the seq2seq task, each example is a line pair, a corpus is a collection of examples.
You should prepare your data as aligned parallel file **train_corpus.src** and **train_corpus.tgt** as:
```
**train_corpus.src** 
One line of text as model input to encoder.
Another line of text as model input to encoder.
```

```
**train_corpus.tgt**
One line of text as model input to decoder.
Another line of text as model input to decoder.
```
Then call `preprocess.py` on this file if you use the legacy branch. Forget about the weight if you could not understand, you can preprocess a single pair of src/tgt files without the need for weight.
But anyway, 1000 examples for (abstractive) summarization is far from enough to build any meaningful stuff. In seq2seq tasks such as translation, we use millions of examples.

**Comment by Tinarights** [comment]
@Zenglinxiao 
Thank you very much. Actually, this is a small sample of my dataset, I want to make sure that it works.

I have created these files: demo.train.0.pt, demo.valid.0.pt, demo.vocab.pt
<img width="240" alt="image" src="https://user-images.githubusercontent.com/33947520/123586146-f786ea80-d7ec-11eb-82df-b37e47945393.png">

How to generate a test set? I need another file named test.pt

Many thanks,

**Comment by francoishernandez** [comment]
You don't need a ".pt" prepared dataset for your test set. `translate.py` takes a plain text file as input.
Prepared datasets are not dicts but torchtext.data objects. You can check attributes of such objects with `.__dict__` for instance. For more details, check torchtext docs.
