### ISSUE TITLE
--reset_optim doesn't appear to be working

### ISSUE THREAD

**Issue by BeaLove** [OpenNMT/OpenNMT-py#2075]
when restarting training from a checkpoint, it ignores the --reset_optim: states flag, and lr is still set to the original, what am I doing wrong? should it be 'states'? as in string?

**Comment by Zenglinxiao** [comment]
This is expected, `reset_optim=states` is defined to removing the state_dict of the `torch.optim.Optimizer` while retaining all other stuff from optimizer checkpoint such as training_step, decay_step etc.

see code:
https://github.com/OpenNMT/OpenNMT-py/blob/54c777a12c6942e34fbb156d84f448ff063d1b55/onmt/utils/optimizers.py#L257-L277
