### ISSUE TITLE
VecEmbedding import error

### ISSUE THREAD

**Issue by HamidShojanazeri** [OpenNMT/OpenNMT-py#2085]
I am using the [code](https://github.com/NVIDIA/FasterTransformer/blob/main/sample/pytorch/utils/translation_model.py) from Nvidia for translation model, where it is importing VecEmbedding from onmt.modules, where it seems it has been deprecated, was wondering if has been moved to other place/replaced.

Thank for your help.

**Comment by francoishernandez** [comment]
As stated in their README, they expect OpenNMT-py==1.1.1.
This task has not been ported yet to v2.
