### ISSUE TITLE
Is on-the-fly data processing slower than pre-processing?

### ISSUE THREAD

**Issue by SefaZeng** [OpenNMT/OpenNMT-py#2092]
I wanna update the opennmt code to the latest stable version, and I find the main feature of version 2.0 is on-the-fly data processing. Is this method slower than the previous one like process the data before?
In my opinion, the on-the-fly method should process the batch every time even after the first epoch, it should spend more time on the data processing.
And another question is do I need to update the code to version 2.0 if I do not need the on-the-fly method?

**Comment by francoishernandez** [comment]
This depends on a lot of factors such as your hardware configuration, the kind of processing you're applying, etc.
The easiest is probably just to test this out on a setup you're familiar with, and you'll see.
Note that you can still apply some processing before-hand, and just read the pre-processed text data on the fly if you don't need transforms with random components such as sentencepiece regularization, BPE dropout or BART noise for instance.

>  And another question is do I need to update the code to version 2.0 if I do not need the on-the-fly method?

The legacy branch is fixed and no longer worked on, so some bugs might not be fixed and some new features might not be added. (For now there is not much difference between 1.2 and 2.0 apart from the data pipeline though.)
