### ISSUE TITLE
Loading OpenNMT model gives ModuleNotFoundError

### ISSUE THREAD

**Issue by debparth** [OpenNMT/OpenNMT-py#2093]
## ❓ Questions and Help
I'm trying to load an OpenNMT model [Link](https://buaaeducn-my.sharepoint.com/personal/liminghao1630_buaa_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fliminghao1630%5Fbuaa%5Fedu%5Fcn%2FDocuments%2FTableBank%5Fv1%2E1%5FMODELZOO%2FRecognition&originalPath=aHR0cHM6Ly9idWFhZWR1Y24tbXkuc2hhcmVwb2ludC5jb20vOmY6L2cvcGVyc29uYWwvbGltaW5naGFvMTYzMF9idWFhX2VkdV9jbi9FcjNlMzl3d1VQeExzRW9vTVlVMXlsc0JXcXI3SEhtOXcybXlXaThaeEZnYUVRP3J0aW1lPXVrNWlVTmh0MlVn) (First one named `Recognition_All.pt`) which gives me `ModuleNotFoundError`. I even tried to install `OpenNMT-py`; yet it didn't resolve the error.

I filed an issue over `pytorch` but they said that it's not their issue for now ([link to issue](https://github.com/pytorch/pytorch/issues/64417)).

## Command I use:
```
import torch

torch.load("/content/Recognition_All.pt")
```

## Error I got:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-ce769809aef1> in <module>()
      1 import torch
      2 
----> 3 torch.load("/content/drive/MyDrive/Recognition_All.pt")

/usr/local/lib/python3.7/dist-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    605                     opened_file.seek(orig_position)
    606                     return torch.jit.load(opened_file)
--> 607                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    608         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    609 

/usr/local/lib/python3.7/dist-packages/torch/serialization.py in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
    880     unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
    881     unpickler.persistent_load = persistent_load
--> 882     result = unpickler.load()
    883 
    884     torch._utils._validate_loaded_sparse_tensors()

/usr/local/lib/python3.7/dist-packages/torch/serialization.py in find_class(self, mod_name, name)
    873         def find_class(self, mod_name, name):
    874             mod_name = load_module_mapping.get(mod_name, mod_name)
--> 875             return super().find_class(mod_name, name)
    876 
    877     # Load the data (which may in turn use `persistent_load` to load tensors)

ModuleNotFoundError: No module named 'onmt.inputters.image_dataset'
```

## Envirnment: 
- Google Colab

**Comment by Zenglinxiao** [comment]
Hi @debparth,
As the prompt message suggests, the model you are trying to load needs image modules that are dropped in the v2.0 release.
you may need to check out the [legacy branch](https://github.com/OpenNMT/OpenNMT-py/tree/legacy) or install via pip by `pip install OpenNMT-py==1.2.0`.

**Comment by debparth** [comment]
@Zenglinxiao Oh... Thank you for your reply. I did install `OpenNMT-py==1.2.0` and it worked. 

One more question @Zenglinxiao, Is there a way that I can export my model to `v2.1.2`?

**Comment by Zenglinxiao** [comment]
As been said, the image module has been dropped since the release of v2.0.
It's not supported without modifying the code.

**Comment by debparth** [comment]
@Zenglinxiao Ok.
