### ISSUE TITLE
[docs] onmt_server instead of server.py

### ISSUE THREAD

**Issue by sih4sing5hong5** [OpenNMT/OpenNMT-py#2094]
In [docs](https://opennmt.net/OpenNMT-py/options/server.html), 
![onmt](https://user-images.githubusercontent.com/5996555/132822754-519c5755-7a17-4d5b-bc57-46126f8ec391.png)
should be 
```
usage: onmt_server [-h] [--ip IP] [--port PORT] [--url_root URL_ROOT] [--debug]
                 [--config CONFIG]
```

**Comment by Zenglinxiao** [comment]
You can actually use the two.
For `server.py`, you need to be at the root path of OpenNMT-py to launch this way. It's good for development as all changes made will be reflected.
For the case of `onmt_server`, it's an entry point created by `setup.py` or when you use `pip`. This doesn't restrict the path, but you may need to reinstall it if you want any modification to take effect.

For more detail, you can check [setuptools](https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html) and the following code: https://github.com/OpenNMT/OpenNMT-py/blob/7e8c7c2a6ac1d28265f27c861fc63ef72c1f0fae/setup.py#L33-L41

**Comment by sih4sing5hong5** [comment]
Thank you for reply :) The `server.py` way is good for development, and `onmt_server` is for user.
Because `Quickstart` pages are latter, so I was confused.
Keeping `server.py` for consistency like other `Scripts` pages is good.

**Comment by sih4sing5hong5** [comment]
Another question, `python -m onmt.bin.server` worked without `/server.py` in reposity root and all changes made will be reflected. Is it better than maintaining a `/server.py` file in reposity root?

Thanks :)

**Comment by Zenglinxiao** [comment]
I think it's just a historical reason that we keep these scripts in the repository root.
We have moved all these scripts into `onmt/bin` for ease of distribution when preparing for pip.
You can directly use these `onmt/bin/*.py`

**Comment by sih4sing5hong5** [comment]
Thanks for quick reply :)
