### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [OpenNMT/OpenNMT-py#2102]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by francoishernandez** [comment]
Hi there,
Thanks for pointing that out. We'll try and add this soon.
What is the security issue you're mentioning? You can reach me via PM [through gitter](https://gitter.im/OpenNMT/OpenNMT-py) if needed.

**Comment by JamieSlome** [comment]
@francoishernandez - https://huntr.dev/bounties/46acaaa4-2559-4c26-94d3-3efe3ef22530/

**Comment by francoishernandez** [comment]
Thanks!
The tools in question are actually not used by the main codebase and not part of the project itself, we'll remove these soon.
