### ISSUE TITLE
KeyError: 'features' while translating with library

### ISSUE THREAD

**Issue by Amplil** [OpenNMT/OpenNMT-py#2110]
I came across the following error while translating with library.  I am running [Library.ipynb](https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/examples/Library.ipynb) on Google Colaboratory.

```
KeyError                                  Traceback (most recent call last)
<ipython-input-34-a0fe180feb36> in <module>()
      2 tgt_data = {"reader": onmt.inputters.str2reader["text"](), "data": tgt_val}
      3 _readers, _data = onmt.inputters.Dataset.config(
----> 4     [('src', src_data), ('tgt', tgt_data)])

/usr/local/lib/python3.7/dist-packages/onmt/inputters/dataset_base.py in config(fields)
    163             if field["data"] is not None:
    164                 readers.append(field["reader"])
--> 165                 data.append((name, field["data"], field["features"]))
    166         return readers, data

KeyError: 'features'
```

This error seems to be due to the lack of `features` column in `src_data` or `tgt_data`. What should I put in `features` column?

**Comment by francoishernandez** [comment]
Hi @Amplil 
This is linked to the recent introduction of source features.
You can probably do something similar to what's done in `onmt.translate.translator` as a workaround:
https://github.com/OpenNMT/OpenNMT-py/blob/4ccf5821b86bd67644c446fb953ae03dd0c463b1/onmt/translate/translator.py#L368-L380


@anderleich couldn't we put some safeguard at a higher level to facilitate such use cases?
Else, we'll probably have to update the Library example.
