### ISSUE TITLE
How could I train a transformer-based BIG model on single machine with mutli GPUs, big batch size is very important for me.

### ISSUE THREAD

**Issue by Ch3nYe** [OpenNMT/OpenNMT-py#2119]
I have RTX 3090*10 GPU on a single machine, I want to trian a model like:
```
decoder_type: transformer
encoder_type: transformer
enc_layers: 1
dec_layers: 1
heads: 6
word_vec_size: 128
rnn_size: 128
transformer_ff: 2048
```
when I set configuration like above, I could only use *batch_size==64*. How could I config onmt, to do something like splitting big batch to different GPU, so I could use more big batch_size.

**Comment by vince62s** [comment]
read this: https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md

**Comment by Ch3nYe** [comment]
> read this: https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md

I already read it, but stilly have no idea how to config it.

**Comment by PJ-Finlay** [comment]
https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md#do-you-support-multi-gpu

> First you need to make sure you export CUDA_VISIBLE_DEVICES=0,1,2,3. 

> If you want to use GPU id 1 and 3 of your OS, you will need to export CUDA_VISIBLE_DEVICES=1,3

> Both -world_size and -gpu_ranks need to be set. E.g. -world_size 4 -gpu_ranks 0 1 2 3 will use 4 GPU on this node only.

**Comment by Ch3nYe** [comment]
> https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md#do-you-support-multi-gpu
> 
> > First you need to make sure you export CUDA_VISIBLE_DEVICES=0,1,2,3.
> 
> > If you want to use GPU id 1 and 3 of your OS, you will need to export CUDA_VISIBLE_DEVICES=1,3
> 
> > Both -world_size and -gpu_ranks need to be set. E.g. -world_size 4 -gpu_ranks 0 1 2 3 will use 4 GPU on this node only.

guys, guys, maybe you misunderstanding my issue, I know how to use multi GPUs on single machine, I want know how to split a batch data to different GPU so I could use a **BIG batch_size**, right now my training always out **of CUDA memory**.

**Comment by vince62s** [comment]
When you set a batch_size (of lines or tokens depending on the chosen mode) it will send one batch of this size to each GPU and then compute gradients on the full size of each of them.
if you want an even bigger true batch_size look at the -accum_count flag which can accumulate several passes.

**Comment by Ch3nYe** [comment]
> When you set a batch_size (of lines or tokens depending on the chosen mode) it will send one batch of this size to each GPU and then compute gradients on the full size of each of them. if you want an even bigger true batch_size look at the -accum_count flag which can accumulate several passes.

Nice! I will try it, Thank a lot, I will close this issue after that.🤤
