### ISSUE TITLE
translate.py; IndexError: list index out of range

### ISSUE THREAD

**Issue by xjtu-zeng** [OpenNMT/OpenNMT-py#212]
I met another issue when use **translate.py**, following the three steps in the **Quickstart**.
![image](https://user-images.githubusercontent.com/15373554/29874234-b82ee6ac-8dc8-11e7-8f93-da61b4fa895e.png)

**Comment by srush** [comment]
Thanks, will fix asap.

**Comment by sriniiyer** [comment]
I think this is because beam.finished is empty because the END token is not reached for any of the beam elements.

**Comment by srush** [comment]
FIxed. merging now.
