### ISSUE TITLE
Question about the "input_feed" feature.

### ISSUE THREAD

**Issue by peiyangL** [OpenNMT/OpenNMT-py#2121]
I notice that the input_feed of RNN decoder is initialized to be zeros in https://github.com/OpenNMT/OpenNMT-py/blob/7c314f41dc1b017ac105144beeb53cb072960a54/onmt/decoders/decoder.py#L179-L180

Is that means the input_feed is forced to be a zero vector instead of the context vector during training, if yes, why?

**Comment by francoishernandez** [comment]
This is just the initialization for the first step, as there is no context vector at this time. (See fig. 4 in [this paper](https://arxiv.org/pdf/1508.04025.pdf).)
`input_feed` is updated at each step in the forward related methods.
