### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by michelleqyhqyh** [OpenNMT/OpenNMT-py#2122]
![training-issue](https://user-images.githubusercontent.com/45490378/142797236-b36289d7-06a3-4970-a284-a6764dd9ea64.png)
When I was training the data, it seems load sentences one by one, and the process is very slow. Is there any problem?

**Comment by Zhw098** [comment]
Hi，I also have the same question，Do you solve the question now?
If you already have this problem, can you share the method？
Thanks
