### ISSUE TITLE
How to test the alignment performance?

### ISSUE THREAD

**Issue by michelleqyhqyh** [OpenNMT/OpenNMT-py#2124]
When I finished the joint alignment translation training, how can I test the  word alignment performance with my final model?

**Comment by Zenglinxiao** [comment]
Ref: section 5 of the original paper for [Jointly Learning to Align and Translate with Transformer Models](https://arxiv.org/abs/1909.02074).

**Comment by michelleqyhqyh** [comment]
> Ref: section 5 of the original paper for [Jointly Learning to Align and Translate with Transformer Models](https://arxiv.org/abs/1909.02074).

I read the paper carefully. But I hope to know whether there are some direct code commands to execute to generate a predicted alingment file and the corresponding ARE with my test data in this git?

**Comment by Zenglinxiao** [comment]
You should be able to find all repo/scripts necessary to replicate their experiment in the paper. Especially the link listed under the Experiments section 5.1.1 for stuff related to alignment conversion, AER computation, etc.
To get the predicted alignment from a trained OpenNMT-py model, please refer to [doc](https://opennmt.net/OpenNMT-py/FAQ.html#raw-alignments-from-averaging-transformer-attention-heads).

**Comment by michelleqyhqyh** [comment]
> You should be able to find all repo/scripts necessary to replicate their experiment in the paper. Especially the link listed under the Experiments section 5.1.1 for stuff related to alignment conversion, AER computation, etc. To get the predicted alignment from a trained OpenNMT-py model, please refer to [doc](https://opennmt.net/OpenNMT-py/FAQ.html#raw-alignments-from-averaging-transformer-attention-heads).

![pred](https://user-images.githubusercontent.com/45490378/143361949-a681b996-88a5-4569-b144-60dbced9ea53.png)
![result](https://user-images.githubusercontent.com/45490378/143361998-8a6c8e8c-da5b-4c43-8038-dec971cd85e9.png)
When I used my model trained with alignment training data to pred the alignment results of my testset, there are some missing sentences. Do you know what's wrong with this?
PS: For output results, what does "PRED PPL" mean? Do higher values of "PRED AVG SCORE" and "PRED PPL" mean better predictions?

**Comment by michelleqyhqyh** [comment]
> > You should be able to find all repo/scripts necessary to replicate their experiment in the paper. Especially the link listed under the Experiments section 5.1.1 for stuff related to alignment conversion, AER computation, etc. To get the predicted alignment from a trained OpenNMT-py model, please refer to [doc](https://opennmt.net/OpenNMT-py/FAQ.html#raw-alignments-from-averaging-transformer-attention-heads).
> 
> ![pred](https://user-images.githubusercontent.com/45490378/143361949-a681b996-88a5-4569-b144-60dbced9ea53.png) ![result](https://user-images.githubusercontent.com/45490378/143361998-8a6c8e8c-da5b-4c43-8038-dec971cd85e9.png) When I used my model trained with alignment training data to pred the alignment results of my testset, there are some missing sentences. Do you know what's wrong with this? PS: For output results, what does "PRED PPL" mean? Do higher values of "PRED AVG SCORE" and "PRED PPL" mean better predictions?

![image](https://user-images.githubusercontent.com/45490378/143365628-2fa4361b-0390-4bcd-830b-eb5378d1c392.png)
This is my config.

**Comment by michelleqyhqyh** [comment]
> > > You should be able to find all repo/scripts necessary to replicate their experiment in the paper. Especially the link listed under the Experiments section 5.1.1 for stuff related to alignment conversion, AER computation, etc. To get the predicted alignment from a trained OpenNMT-py model, please refer to [doc](https://opennmt.net/OpenNMT-py/FAQ.html#raw-alignments-from-averaging-transformer-attention-heads).
> > 
> > 
> > ![pred](https://user-images.githubusercontent.com/45490378/143361949-a681b996-88a5-4569-b144-60dbced9ea53.png) ![result](https://user-images.githubusercontent.com/45490378/143361998-8a6c8e8c-da5b-4c43-8038-dec971cd85e9.png) When I used my model trained with alignment training data to pred the alignment results of my testset, there are some missing sentences. Do you know what's wrong with this? PS: For output results, what does "PRED PPL" mean? Do higher values of "PRED AVG SCORE" and "PRED PPL" mean better predictions?
> 
> ![image](https://user-images.githubusercontent.com/45490378/143365628-2fa4361b-0390-4bcd-830b-eb5378d1c392.png) This is my config.

![image](https://user-images.githubusercontent.com/45490378/143366128-b4f78cd7-dfaf-42c0-a6d1-b19662655a9e.png)
This is my alignment file of the valid set (PS: the the alignment file of the training set is similar.)
