### ISSUE TITLE
Do the on-the-fly processing use more GPU memory?

### ISSUE THREAD

**Issue by SefaZeng** [OpenNMT/OpenNMT-py#2127]
I try to train a transformer model with 20 layers encoders, and it can be run successfully in OpenNMT-py-1.2.0. In the previous version, I use the preprocess scripts to process the data in advance. Now I want to use the on-the-fly process as I want to sample from different datasets, but it will always raise CUDA OOM error. 
Is there some methods to solve this? Maybe move the process to CPU?

**Comment by francoishernandez** [comment]
Already discussed a few times. You probably need to add the `filtertoolong` transform to ignore examples that may be too long and hence trigger CUDA OOM.
