### ISSUE TITLE
I cannot find transforms.py in onmt file

### ISSUE THREAD

**Issue by cassie-cuihua** [OpenNMT/OpenNMT-py#2131]
There is no transforms.py in onmt file, but parse.py needs function in transforms.py.

**Comment by francoishernandez** [comment]
`transforms` is a module/subfolder with several transforms in it, not a single `transforms.py`.
https://github.com/OpenNMT/OpenNMT-py/tree/master/onmt/transforms
Your problem is probably more of a path / install issue. Install via pip if you're not sure.

**Comment by cassie-cuihua** [comment]
Thank you for replying to my email, and I will try again.&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenNMT/OpenNMT-py"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 下午5:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenNMT/OpenNMT-py] I cannot find transforms.py in onmt file (Issue #2131)





 
transforms is a module/subfolder with several transforms in it, not a single transforms.py.
 https://github.com/OpenNMT/OpenNMT-py/tree/master/onmt/transforms
 Your problem is probably more of a path / install issue. Install via pip if you're not sure.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
