### ISSUE TITLE
Why the model behaves differently during training and translation?

### ISSUE THREAD

**Issue by PosoSAgapo** [OpenNMT/OpenNMT-py#2132]
In my own dataset, the accuracy could reach 80% in both the training and validation dataset. However, after training, using the model to translate the validation dataset, the results give repeated tokens, and the performance drops massively, which is far from the result during training.  Is this due to the setting of the translator? What should I do to keep the performance the same?

I know the model performs Beam Search while translating, but this gives a much worse performance.

**Comment by francoishernandez** [comment]
Please do not duplicate posts across here and the forum.
