### ISSUE TITLE
transformer encoder output

### ISSUE THREAD

**Issue by Sunnycheey** [OpenNMT/OpenNMT-py#2133]
Hi, thanks for your contribution.

It seems that the [transformer encoder](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/encoders/transformer.py#L129) doesn't return the same output as EncoderBase (since the first returned argument isn't the final encoder state).

**Comment by francoishernandez** [comment]
Hi,
Yes, we never came to homogenize properly all the encoder/decoder interfaces.
This could be a nice project if you would like to contribute.
