### ISSUE TITLE
 Is it meaningful to use word2vec or glove as hot start to train the MT model with transformer? 

### ISSUE THREAD

**Issue by Andrewlesson** [OpenNMT/OpenNMT-py#2134]
When I use machine translation with OpenNMT-py,  both encoder and decoder use transformers. Is it meaningful if I use word2vec or glove as hot start to train the model? Has the effect improved?  and why if yes ?

**Comment by francoishernandez** [comment]
You might have some better chance for such discussion on the [forum](https://forum.opennmt.net/).
You might also want to check the literature a bit. IIRC most experiments of this kind were not very conclusive, but I may be wrong.
