### ISSUE TITLE
some question about alignments

### ISSUE THREAD

**Issue by Andrewlesson** [OpenNMT/OpenNMT-py#2135]
Is the data of alignments during training the same as that of alignments during inference? If not, how did the inferred alignment corpus come from?   can it be converted from training data?

![image](https://user-images.githubusercontent.com/10346684/146171913-fa88f7bb-3d13-47f5-b969-a9c81f645dff.png)

![image](https://user-images.githubusercontent.com/10346684/146174982-5da79955-32ce-45fd-bbdd-100264902cbc.png)

**Comment by francoishernandez** [comment]
It's not the same thing.
The alignment that can be passed when training are for "guided alignments", see details in #1615 and [the docs](https://opennmt.net/OpenNMT-py/FAQ.html#can-i-get-word-alignments-while-translating).
Then, when inferring you would retrieve the alignments in the form of one of the attention matrices.

The `-phrase_table` flag is to be used at inference only, but it was more meant to be used with an RNN+attention architecture, where the single attention matrix is supposed to carry the alignment information relatively explicitly.
