### ISSUE TITLE
transformer decoder mismatch dimension

### ISSUE THREAD

**Issue by Sunnycheey** [OpenNMT/OpenNMT-py#2136]
Hi, It seems that the returned multi-head attention [*attn*](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/transformer.py#L528) which is used in [here](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/transformer.py#L98) is not of shape (batch_size, head, T, T) but (batch_size, T, T).

**Comment by funboarder13920** [comment]
Hello, are you using AverageAttention ?

**Comment by Sunnycheey** [comment]
Hi, I'm using the *MultiHeadedAttention*.

**Comment by francoishernandez** [comment]
That's strange.
Do you have an error trace?
If so, can you share it, along with the exact config you're running?
A minimal reproducible example would be even better.

**Comment by Sunnycheey** [comment]
Hi, thanks for quickly reply. It's seems that I mistakenly take this version [code](https://github.com/OpenNMT/OpenNMT-py/blame/f122269dc50b76a4656d2542709ffe4837144a24/onmt/modules/multi_headed_attn.py#L153), sorry for the interrupting, close the issue.
