### ISSUE TITLE
Advice on how to get the best possible translations

### ISSUE THREAD

**Issue by RealHinome** [OpenNMT/OpenNMT-py#2138]
Hey,

This is not a real problem and can bring the whole community.

I would like to know what to do to get the best translations, as said in the title.
For example, how many lines in the src-train, how many train steps recommended or even, if possible, explain me the best possible configuration (in the yaml file).

Otherwise, I would like to say that it's a great job and with the little I could test, it made quite good translations!

Thanks in advance,
Hinome

**Comment by francoishernandez** [comment]
You will need to do a bit of research. There is no magical formula.

A potential starting point: [Training Tips for the Transformer Model](https://arxiv.org/abs/1804.00247)

Also, this discussion would be more appropriate on [the forum](forum.opennmt.net). Feel free to open a thread there (or participate in existing ones).

**Comment by RealHinome** [comment]
Thanks for your fast answer.
So I will do my own research, a little bit of challenge 😂

Have a nice day
