### ISSUE TITLE
OpenNMT-py pretrained model output

### ISSUE THREAD

**Issue by bhavitvyamalik** [OpenNMT/OpenNMT-py#2139]
I tried `German-English - 2-layer BiLSTM` available [here](https://opennmt.net/Models-py/#translation) and it was giving really poor performance with many `<UNK>` tokens like I tried this German sentence `Schauspieler Orlando Bloom und Model Miranda Kerr wollen künftig getrennte Wege gehen .` for which the English translation came out like `<unk> <unk> <unk> and <unk> <unk> <unk> wants to <unk> <unk> <unk> .` I added `replace_unk` still the output was `Schauspieler Orlando Bloom and Model Miranda wollen wants to gehen getrennte getrennte .` which wasn't that good for a pretrained model.

I am using this command to get translation: `onmt_translate -model MODEL_PATH -src TXT_FILE_GERMAN -output EMPTY_TXT_FILE -replace_unk` should I add any other parameter to this inorder to improve the outputs?

**Comment by Zenglinxiao** [comment]
It seems you are sending raw texts to the model. An OpenNMT-py model file does not contain preprocess pipeline inside, you need to preprocess the text exactly the same as for training data before sending it to the model for translation. In your case, it's a Moses tokenization + lowercase step, you can check the data section link from where you download the pretrained model.
