### ISSUE TITLE
Does the latest version support MAC M1 chip installation ?

### ISSUE THREAD

**Issue by harishankar-gopalan** [OpenNMT/OpenNMT-py#2154]
Hi wanted to know if version 2.1.2 or higher supports MAC M1. Wanted to check if pinning the version to some higher value will allow me to install it seamlessly on M1 chip machine.

**Comment by francoishernandez** [comment]
This is probably more of a pytorch question than an OpenNMT question.
OpenNMT-py should theoretically be compatible with the latest versions of pytorch. So you'll have to check if pytorch is compatible with M1.

**Comment by harishankar-gopalan** [comment]
Actually I guess not. The specific package that does not install on MAC M1 is the **pyonmttok** package which is a dependency of OpenNMT-Py and due to this the installation of OpenNMT-Py rolls back.

**Comment by harishankar-gopalan** [comment]
Hi @guillaumekln  sure will check that while installing from sources. Will update in couple of days.

**Comment by harishankar-gopalan** [comment]
Hi @guillaumekln  I can confirm that this has worked. But I presume we are excluding the `pyonmttok` dependency for MAC M1 based OS. I would like to know what is the use of this. From the name and the repo it seems like some kind of a tokenization library. So if this is not available is there some other default behavior or alternate tokenization used ?

**Comment by francoishernandez** [comment]
Other tokenizers are supported: https://opennmt.net/OpenNMT-py/FAQ.html#tokenization

For this to be taken into account in PyPi we will need to create a new release.
Though, you will be able to install directly from github with a command such as `pip install git+https://github.com/OpenNMT/OpenNMT-py`

**Comment by guillaumekln** [comment]
`pyonmttok` now includes Python wheels for ARM64 macOS, so the installation should now succeed.
