### ISSUE TITLE
Question with respect to transformer decoder input

### ISSUE THREAD

**Issue by jaes77** [OpenNMT/OpenNMT-py#2156]
I noticed that the transformer decoder input of your model is slightly different from what I've known.

As far as I know, transformer decoder uses the concatenated output from the previous steps results like below.
step1: input shape: (1x1) ~~~ step n, (1 x n)
(when batch size and beam size are 1 respectively)
 
But your model only uses last prediction result.

https://github.com/OpenNMT/OpenNMT-py/blob/7c314f41dc1b017ac105144beeb53cb072960a54/onmt/translate/greedy_search.py#L157-L158

https://github.com/OpenNMT/OpenNMT-py/blob/fc3409ce08785915728dac9e9c9fb49f73027917/onmt/translate/translator.py#L908-L910

I'm curious if there is no accuracy issue when using only last token.
Also, is there any reason that you feed only (batch x last one result) input to the transformer decoder unlike (batch x sequence_length_through_decoding steps)?

**Comment by guillaumekln** [comment]
Forwarding all previous inputs to the decoder is the basic and inefficient implementation. In practice, most Transformer implementations cache previous projections within the decoder and forward the last token only. This optimization has no impact on accuracy.

You can read section 3.4 of this [paper](https://aclanthology.org/2020.ngt-1.25.pdf) to know exactly what is being cached from previous decoding steps.

**Comment by guillaumekln** [comment]
Your understanding is correct.

**Comment by jaes77** [comment]
I appreciate your explanation enormously.
Have a good day :)
