### ISSUE TITLE
Question about skipping elementwise addition after FFN in decoder and encoder layers.

### ISSUE THREAD

**Issue by jaes77** [OpenNMT/OpenNMT-py#2157]
In general, transformer encoder and decoder follow the way below.(whatever post layer norm and pre-layer norm are)
layernorm -> MHA -> addition1(with MHA result and residual input) -> layernorm -> FFN -> addition2
(For decoder, enc-dec attention, layernorm and sum will be added.)

But, it seems your model skips the last addition and I'm curious there is any reason omitting the operation.

**Comment by guillaumekln** [comment]
The addition is done in the FFN module:

https://github.com/OpenNMT/OpenNMT-py/blob/2.2.0/onmt/modules/position_ffn.py#L51
