### ISSUE TITLE
[ASK FOR HELP] How to use a GCN generate token embeddings before input data to seq2seq model

### ISSUE THREAD

**Issue by Ch3nYe** [OpenNMT/OpenNMT-py#2160]
As the title says, Could I use a GCN model generate embeddings of input data from a graph, and then input the sequence sampling from graph to the seq2seq model in ONMT-py?

**Comment by Ch3nYe** [comment]
Base on, I already have a GCN model that could generate node data embeddings from graph.

**Comment by vince62s** [comment]
Not sure what you are trying to achieve but you can always skip the numericalize step and feed with your own vectors.
