### ISSUE TITLE
Support for feature vectors

### ISSUE THREAD

**Issue by n8rob** [OpenNMT/OpenNMT-py#2167]
There doesn't seem to be much support or documentation for using feature vectors, other than a few small notes like the below comment from `onmt/modules/embeddings.py`. How does one incorporate feature vectors into training, and what format do they need to be in? I've found some tips online indicating that the input files take a very different form than the GloVe-style input files for pretrained embedding vectors.

```
feat_vec_size (int): embedding dimension for features when using
            `-feat_merge mlp`
```

**Comment by francoishernandez** [comment]
This might help: https://opennmt.net/OpenNMT-py/FAQ.html#how-can-i-use-source-word-features
