### ISSUE TITLE
The problem of language model generating multi format input

### ISSUE THREAD

**Issue by Andrewlesson** [OpenNMT/OpenNMT-py#2168]
I find that the input format of text generation is very fixed. The data I use now cannot use BPE format. Can I support the input of data in this format? I follow the steps below. In step 1, I can't get the data of various datasets ，such as  train.bpe, test.bpe, valid.bpe 
https://opennmt.net/OpenNMT-py/examples/LanguageModelGeneration.html

**Comment by Andrewlesson** [comment]
The training data I input only generates a subword.bpe , The data in BPE is only numbers
my train data format below:

诺 氟 沙 星 遇 丙 二 酸 及 酸 酐 748 484 849 498 985 854 542 427 273 734 346 468 689 894 942 426 水 浴 加 热 后 显
找 朋 友 要 的 下 雪 的 826 263 636 366 662 622 224 242 426 265 654 546 468 684 842 426 269 694 942 425 他 们 那 边 今 天 下 了
我 爸 说 没 有 368 689 898 983 834 342 426 265 653 533 都 租 掉 了 的
谁 劳 动 去 了 945 454 549 494 942 424 247 478 785 853 自 己 摘 去 了
这 家 伙 这 俩 天 睡 不 醒 926 267 674 742 426 264 645 458 586 863 633 332 328 289 894 946 464 649 492 926 267 674 早 上 困 的 不 行 要 死
我 刚 吃 完 出 来 968 689 894 943 434 348 483 834 348 485 852 有 一 丢 丢 辣
已 经 想 好 本 周 五 深 夜 的 朋 友 圈 文 案 了 942 426 267 674 744 445 454 542 426 264 648 484 842 426 269 699 消 失 两 天
这 个 不 要 紧 969 693 932 328 283 838 386 864 648 484 844 448 482 我 也 不 多 会 画
我 就 是 不 给 你 冲 965 652 526 266 664 646 463 636 364 642 428 286 863 636 364 645 453 537 374 我 看 你 能 不 能 渴 死
大 家 凑 一 凑 了 啊 486 869 694 949 494 942 423 234 342 422 226 269 694 946 466 664 643 434 346 463 636 过 一 下 低 保 兄 弟 们

only generate  subword.bpe below:
#version: 0.2
2 6</w>
2 6
4 2</w>
6 4
9 4</w>
4 3
4 26</w>
2 4</w>
4 8
4 3</w>
6 4</w>
7 4</w>
4 8</w>
4 4</w>
5 4</w>
4 6</w>
6 3
26 4</w>
4 9</w>
6 8
6 8</w>
4 9
3 3
6 3</w>
4 94</w>
26 9</w>

**Comment by francoishernandez** [comment]
I suspect there is an issue in your data / preparation pipeline. `subwords.bpe` is the set of merge operations learned by the BPELeaner. If "numbers" are there, it means that the data you learned on was already "numbers".

**Comment by Andrewlesson** [comment]
Numbers are one kind of data I input, and some are single word data, so BPE splitting and merging cannot be performed. I want to know how to deal with the data that cannot be split by a single word, and whether the language model generation can support the data input of such a single word.

**Comment by francoishernandez** [comment]
I'm really not sure to understand the issue here. Why would bpe not be able to work on numbers? These are bytes like any other.
The model is taking the input//vocab it's given.
You might want to do a bit more reading, e.g. on [the forum](https://forum.opennmt.net/) or ask for help there, describing clearly what you are trying to achieve and the issues (being theoretical or technical) you face.

**Comment by Andrewlesson** [comment]
I don't think you understand what I mean. I'm not talking about numbers at all. I mean about the input of single Chinese characters. The input generated by the language model is the result of BPE, but if my input is a single Chinese character, BPE cannot produce a vocabulary. In this case, how should I deal with the input problem.  i will not get subword.bpe .
For example:
诺 氟 沙 星 遇 丙 二 酸 及 酸 酐 水 浴 加 热 后 显
找 朋 友 要 的 下 雪 的 他 们 那 边 今 天 下 了
我 爸 说 没 有 都 租 掉 了 的
谁 劳 动 去 了 自 己 摘 去 了
这 家 伙 这 俩 天 睡 不 醒 早 上 困 的 不 行 要 死

**Comment by Andrewlesson** [comment]
ok  thanks, i have post my issue on the forum
