### ISSUE TITLE
Support for custom architecture training?

### ISSUE THREAD

**Issue by st-vincent1** [OpenNMT/OpenNMT-py#2169]
Does OpenNMT currently support training custom architectures? I would like to implement a Transformer for NMT with an extra Encoder and a modified beam search objective. If yes, are there any examples or suggestions for how to go about that? Thanks!

**Comment by francoishernandez** [comment]
You would need to write custom code. See `onmt.encoders` / `onmt.model_builder` for the encoder/architecture part, and `onmt.translate.decode_strategy` / `onmt.translate.beam_search` for the beam search part.
