### ISSUE TITLE
Wrong type specified in documentation

### ISSUE THREAD

**Issue by solemn-leader** [OpenNMT/OpenNMT-py#2175]
Here in documentation https://opennmt.net/OpenNMT-py/FAQ.html#how-can-i-create-custom-on-the-fly-data-transforms you say that the type of the `example['src']` and `example['tgt']` in `apply` method is `str` (source and target strings respectfully). Though in reality each out-of-the-box transform is operating on lists of strings like [here](https://github.com/OpenNMT/OpenNMT-py/blob/fc3409ce08785915728dac9e9c9fb49f73027917/onmt/transforms/tokenize.py#L188)

Did I get something wrong or the documentation is really misleading?

**Comment by markovalexander** [comment]
same situation

**Comment by vince62s** [comment]
not sure what you meant but example['src'] is a str
maybe now it's clearer with the combination of apply() and batch_apply()
