### ISSUE TITLE
beam_size in translate doesn't work

### ISSUE THREAD

**Issue by freddieyang** [OpenNMT/OpenNMT-py#2183]
Hi,

When I try to set the beam size to translate using translate.py, it seems that the size of the beam does not affect the final output, so I would like to ask if there is any solution.

**Comment by vince62s** [comment]
please post your command lines here and output

**Comment by freddieyang** [comment]
command line: 
python translate.py -model experiments/models/model_step_400000.pt -src data/src-test.txt -tgt data/tgt-test.txt -gpu 0 -verbose -output experiments/pred/output -beam_size 10

Output is too long to be posted. When i tried several command with different beam_size, the length of the final output will always be the same.

The OpenNMT version is 0.9.1.

**Comment by vince62s** [comment]
we can't support this very old version of OpenNMT. Why don't you upgrade to last ?
did you compare the pred_scores ? are they exactly the same?

**Comment by freddieyang** [comment]
the code of our project is built based on the old version, and the new version of OpenNMT doesn't support the videos, so maybe it is difficult to migrate the project into new version.

the pred_scores is a bit different.

**Comment by vince62s** [comment]
can't help you further then, but f scores are different, then you got your answer, maybe hypotheses are too close.

closing.

**Comment by freddieyang** [comment]
thank you for your help!
