### ISSUE TITLE
sentence translation in python

### ISSUE THREAD

**Issue by himanshudce** [OpenNMT/OpenNMT-py#2184]
Hi,
How can i do the translation sentence by sentence using python API calls?
I have a trained model for machine translation from Sumerian - English and the below code is working perfectly fine -
```
python3 translate.py -model ../Apertium_MT/Data/_step_10000.pt -src ../Apertium_MT/src.txt -output ../Apertium_MT/NNres.txt
```
I want to reproduce the same results, but using onmt python library.  Basically, I want to pass a single sentence and want its translation using the python API interface.

**Comment by francoishernandez** [comment]
You can either use the onmt library directly (not very straightforward though): https://opennmt.net/OpenNMT-py/examples/Library.html

Or you could use/adapt the small REST server included: https://forum.opennmt.net/t/simple-opennmt-py-rest-server/1392
