### ISSUE TITLE
Onmt-train: how to leave vocab untouched (Language ID token filtered off)

### ISSUE THREAD

**Issue by i55code** [OpenNMT/OpenNMT-py#2185]
Hi,  

Onmt-train filters off language tokens that are intended to be very useful in multilingual training. Is there a way to stop omnt-train from filtering it off? 

[2022-08-25 15:54:41,827 INFO] Filtered invalid vocab token ['__es__']

Thanks!

**Comment by francoishernandez** [comment]
It's probably just your vocab file that is not properly formatted. See conditions here:
https://github.com/OpenNMT/OpenNMT-py/blob/7e8c7c2a6ac1d28265f27c861fc63ef72c1f0fae/onmt/inputters/inputter.py#L291-L315

**Comment by i55code** [comment]
Thank you so much, I reformatted the vocab file by including counts and now special tokens are all read in. Thanks!
