### ISSUE TITLE
Incorrect normalization

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT-py#2209]
It does not have an impact on regular training but the math is incorrect.

in _gradient_accumulation we normalize with "normlization" which is calculated on the total number of token in the "global batch" = Accum x "minibatch"
then the loss of each mini batch is normalized by the global batch "nomalization" number of token instead of the number of tokens of each mini-batch.
We can correct this in two ways:
1) the accurate one: we need to calculate the number of tokens in each minibatch inside the gradient_accum loop
2) we can approximate by multiplying the loss by the "accum" number.

Which one shall we do ?

NB: it has an impact when combining the loss with another term (lm_prior_loss for instance).

**Comment by vince62s** [comment]
fixed in v3.0

**Comment by sandyhouse** [comment]
The loss of of each mini batch is calculated on tokens of each mini batch, so why should we normalize the loss of each mini batch by the global batch "normalization"?
