### ISSUE TITLE
invalid literal for int() with base 10

### ISSUE THREAD

**Issue by ArtanisTheOne** [OpenNMT/OpenNMT-py#2210]
I've subworded my corpus, built vocab, and built sentencepiece unigram models just fine with a corpus of around 300,000 and a vocab size of 25,000 but upon attempting to train the model, it runs into an error with the first input in the source.vocab (shown below) and throws an error. Is this an issue that is fixable on my side or is it deeper than that, eg something to do with my corpus or vocab/subwording process.
![image](https://user-images.githubusercontent.com/52015929/193148863-92cb1734-393b-41b6-bc52-2315436b6e55.png)

![image](https://user-images.githubusercontent.com/52015929/193148870-15c7fc0f-2e01-4c3d-9f78-bdd7acf96c40.png)

(config.yml is base transformer config)

**Comment by vince62s** [comment]
Second column is supposed to be counts of tokens.
remove the second column if you don't have counts.

**Comment by ArtanisTheOne** [comment]
So I should remove the second column completely? Or should I add a correct second column with counts. 

Do you know where I can see an example of a correct opennmt-py vocab file, just to compare myself

**Comment by ArtanisTheOne** [comment]
Nevermind, I found the issue. I was confusing my sentencepiece models vocab and the result of onmt_build_vocab, hence the issue. To fix it just had to change the location of src/tgt_vocab to a new dir which was created by onmt_build_vocab
