### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by herochen7372** [OpenNMT/OpenNMT-py#2212]
你好请问为什么翻译出来的所有句子的第一个字都是'他',真实标签不是所有句子开头都是'他',其他的基本都对.

**Comment by vince62s** [comment]
对不起，你需要在这里说英语。

**Comment by herochen7372** [comment]
Excuse me, why does the first word of every sentence in translation begin with ‘he’？

**Comment by vince62s** [comment]
most likely it comes from your dataset. 
what is your task ? chinese to english ? you need to give more info on the task, the data, the processing, ....

**Comment by herochen7372** [comment]
I did a sign language translation task from video to text, using the transformer model. I don't know why the first word of the translated text is "he", so I had to ask for help everywhere. Please forgive me for interruptions!

**Comment by vince62s** [comment]
well then you seem to have used the version 1.0 of Open-NMT-py or something else ? sorry can't help you.

**Comment by herochen7372** [comment]
OK, thank you for your reply
