### ISSUE TITLE
Possible to include metadata in model?

### ISSUE THREAD

**Issue by richardburleigh** [OpenNMT/OpenNMT-py#2249]
Thank you for this amazing project!

Is it possible to include additional information, such as formality into the model when doing a translation task?

I'm mainly thinking about languages that have high variation depending on the formality level, but it would also be interesting to guide the subject matter of a translation.

**Comment by vince62s** [comment]
Hello, you need to go through the forum for this kind of question. It is not really a direct "issue" of the toolkit.
Short answer is "it is possible with some tricks".
