### ISSUE TITLE
Apply custom transform in raw text before any tokenization

### ISSUE THREAD

**Issue by panosk** [OpenNMT/OpenNMT-py#2250]
Hello,

I'd like to apply a custom transform to the raw source segments and I have 2 issues:
- Inside the `apply` method of the transform, the src and tgt text in the `example` is already tokenized even though I don't define any tokenization in the config. Digging a bit I find that in `text_corpus.py`, a plain tokenization is always applied before the `_transform` function. Why is that tokenization applied and how can I get the `example['src']` as raw, untokenized text? The solution so far is to convert the `example` to string and then back to list but I'd like to avoid that if possible.
- Is there a way to apply the transform to all the corpus at once, e.g. get a list with all the raw segments instead of a single `example`?

Thanks!

**Comment by vince62s** [comment]
Maybe @francoishernandez  and @Zenglinxiao can give a good answer for question 1.

For question 2, it would be an issue in terms of memory, but maybe we could envision to do it at the bucket level.
again @francoishernandez may give a better insight.

**Comment by francoishernandez** [comment]
1. I think it was necessary to homogenize inputs to all transform functions, for simplicity. You could probably modify the `ParallelCorpusIterator` code quite easily to bypass this tokenization call.
2. I'm not sure to see the point. Do you basically want to preprocess your data instead of having it processed on the fly? You could probably do that by hijacking the `build_vocab` script, which can dump datasets by enabling the `dump_samples` flag. Else, something like "batching" the transform is not really considered in the current workflow. You might want to move this at the bucket level, but not sure what gains it would bring since a lot of this would still be looping through examples anyways. Do you have an example or a bit of context to better understand the need?

**Comment by panosk** [comment]
Hi @francoishernandez , thanks for the pointer to `ParallelCorpusIterator`, I'll check it.

The point of the batch processing is indeed a special case where I need to apply fuzzy matching with a library which offers a function that takes a list of strings to match against another list. This should have huge speed improvements. Right now matching every single example is a no go as it takes forever to go through the whole dataset. I'll try to find a way around it or else I will do this preprocessing outside the transform.

Another possible use case could be for working with example dependencies for getting context.

**Comment by francoishernandez** [comment]
Interesting use cases. Something might be doable at the bucket level then, but that might need a bit of thinking to embed it cleanly and allow extendability.

**Comment by l-k-11235** [comment]
Hello @vince62s and  @panosk, #2261 seems to be linked with this issue, I hope it can help.

**Comment by panosk** [comment]
Hello @l-k-11235 , thanks for this, looks like a clean and straightforward solution! Have a question about your comment in this line:
https://github.com/OpenNMT/OpenNMT-py/blob/0fff96b673dcf130c738ec6a8ebfd49e55fc90d6/onmt/inputters/text_utils.py#L62
I suppose it is meant to be Transform and not TransformPipe? From a quick look to the rest of your PR, it seems indeed that bucket processing can be applied on a per transform basis with the new `batch_apply` method, which means a TransformPipe can contain both transforms that apply to example level and transforms that apply to bucket level. I'm still getting familiar with the code, so bare with me if I miss sth obvious :)

**Comment by panosk** [comment]
> @panosk maybe you ca test this PR? @l-k-11235 did you actually test it in a real configuration ?
> I have the feeling that for some cases it will slow down if the bucket is too big. Curious to see the overhead while feeding batches.

Sure, will test and report back my findings in the next couple of days.

**Comment by l-k-11235** [comment]
@panosk, there is a default `batch_apply` method which simply iterates through the classic `apply_method` so that you can apply any transforms at the bucket level.
https://github.com/OpenNMT/OpenNMT-py/blob/16bbb978b890eea49add154588685b771af65d6b/onmt/transforms/transform.py#L62-L73

**Comment by vince62s** [comment]
we'll see the tests, but my feeling is that when using a bucket_size of >300K just reading the bucket is slow, so applying a transform at the full bucket might be a little long (wrt the timings to prepare prefetched batches), so I was thinking something at the batch level. But again I might be wrong and tests will tell.

**Comment by francoishernandez** [comment]
This behavior is actually not introduced by the PR in question.
Current implementation already loops over full bucket:
https://github.com/l-k-11235/OpenNMT-py/pull/12/files#diff-40f2c1cd4dd5a3a33b93efef64289debd2ee1423b4f467ed860f61f9c013837aL212-R214

Note: this "reading the bucket is slow" issue was the trigger for the addition of bucket warm up (#2246)

**Comment by vince62s** [comment]
Indeed but I am still confused. If we follow the path bucket_level=True and it enables to both use Transforms with or without a real batch_apply then we don't really need it and just make it the behavior in all cases, no ?

**Comment by panosk** [comment]
I'm still running tests and adapting some transforms I'm working on, but so far bucketing seems to work as expected.

In the meantime, more questions have risen regarding the (batching and non-batching) transforms. I don't quite get how the `_get_specials` work. My understanding is that I should implement this method 

a) when the transform injects special tokens that need to be added to the vocabs
b) when the transform is not applied during `build_vocab` but we need to add any tokens in the vocabs at that time so we can later apply the transform at training and have all required tokens in the vocabs.

Concerning b), the batch transform I'm working on is not applied with `build_vocab` (how can I control this?) so I can't add the required tokens to the vocabs automatically, but my other non-batching transforms are applied with `build_vocab` so the vocab is filled with all required tokens.

So it seems that `_get_specials` is never called. I took a look at the other provided transforms and I don't see explicit calls to it from within the transform, it gets called in the TransformPipe for each transform.

Also, what's the purpose of the `is_train` parameter in the `apply` method and how can it be actually used? The documentation mentions that it defines if we deal with training src/tgt but I would like some more clarifications.

Thanks!

**Comment by panosk** [comment]
> I am not sure what you are trying to achieve during the build_vocab call.

I'm just checking the whole workflow with transforms and trying to figure out when and how things happen. So I have a config with 4 custom transforms, A, B, C ,D and I run build_vocab to build the vocabs before training. After that I check the vocabs and they contain all the custom tokens from transforms B, C, D but not from A (which is the batch transform). When I run the training command, then the `_get_specials` is indeed run and I see the message
```
Get special vocabs from Transforms:
```
with all the tokens from all the transforms. However, the tokens from transform A are still not written to the actual vocab file.

**Comment by panosk** [comment]
I think I figured out the vocab issue – it seems the vocab file is merged with the model's vocab, so these "missing" tokens are actually added in the model's vocab.

**Comment by vince62s** [comment]
merged in v3.0.2
