### ISSUE TITLE
bleu of  Translation demo is too low

### ISSUE THREAD

**Issue by Sarah-Callies** [OpenNMT/OpenNMT-py#2262]
**I want to train a translation demo as by the step in  the 
https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/examples/Translation.md;

**while the bleu is too low 
model-wmt-demo/data//run/model_step_100000.pt
{
 "name": "BLEU",
 "score": 11.7,
 "signature": "nrefs:1|case:mixed|eff:no|tok:13a|smooth:exp|version:2.2.1",
 "verbose_score": "48.9/16.5/7.1/3.3 (BP = 1.000 ratio = 1.020 hyp_len = 62525 ref_len = 61287)",
 "nrefs": "1",
 "case": "mixed",
 "eff": "no",
 "tok": "13a",
 "smooth": "exp",
 "version": "2.2.1"
}**
**when  I set the train step to 400000, the blue is 12.3**
[config-yaml.txt](https://github.com/OpenNMT/OpenNMT-py/files/10128518/config-yaml.txt)

**Comment by vince62s** [comment]
can you share the log file of the training ?

**Comment by Sarah-Callies** [comment]
[model_train.log](https://github.com/OpenNMT/OpenNMT-py/files/10124377/model_train.log)

**Comment by vince62s** [comment]
your accuracy stagnate after a certain point around 50-55, something is wrong with your data, my guess is that parallelism is lost somewhere.

**Comment by Sarah-Callies** [comment]
the data is generated by the scrips：
https://github.com/OpenNMT/OpenNMT-py/blob/master/examples/scripts/prepare_wmt_data.sh
when I change the train_steps to **200000**
the accuracy will be 70+
while bleu is still 12.3

**Comment by vince62s** [comment]
I read 52 for training and 56 for validation, not 70


[2022-11-23 13:34:14,618 INFO] Step 200000/200000; acc:  52.89; ppl:  8.08; xent: 2.09; lr: 0.00020; 22879/24614 tok/s; 146798 sec;
[2022-11-23 13:34:14,707 INFO] * Transform statistics for valid(100.00%):
			* SubwordStats: 104746 -> 150675 tokens

[2022-11-23 13:35:00,410 INFO] Validation perplexity: 8.39741
[2022-11-23 13:35:00,411 INFO] Validation accuracy: 56.2365


try to have a look at the data each one million to see if they are still aligned

**Comment by Sarah-Callies** [comment]
O, My mistake for the acc!
You mean that the train data get from prepare_wmt_data.sh need extra actions that does not show on the Translation.md?

**Comment by vince62s** [comment]
I have never used that script. it should be fine but obviously something went wrong, so just have a look at your data using vi.
check if en and de files are aligned at various line numbers. (eg each 1M or each 100k for smaller ones)

**Comment by Sarah-Callies** [comment]
**[root@dnnl data]$ head commoncrawl.de-en.de**
iron cement ist eine gebrauchs-fertige Paste, die mit einem Spachtel oder den Fingern als Hohlkehle in die Formecken (Winkel) der Stahlguss -Kokille aufgetragen wird.
Nach der Aushärtung schützt iron cement die Kokille gegen den heissen, abrasiven Stahlguss .
feuerfester Reparaturkitt für Feuerungsanlagen, Öfen, offene Feuerstellen etc.
Der Bau und die Reparatur der Autostraßen...
die Mitteilungen sollen den geschäftlichen kommerziellen Charakter tragen.
der Vertrieb Ihrer Waren und Dienstleistungen durch das Postfach-System WIRD NICHT ZUGELASSEN.
die Werbeversande (Spam) und andere unkorrekte Informationen werden gelöscht.
ACDSee 9 Photo Manager Organize your photos. Share your world.
No matter what kind of photos you take - of friends and family or artistic shots as a hobby - you need photo software that organizes your shots AND allows you to view, fix, and share them quickly and easily.
ACDSee 9 makes organizing your photos exactly that: Quick and easy, so you can play with and share the great photos you've got...
**[root@dnnl data]$ head commoncrawl.de-en.en** 
iron cement is a ready for use paste which is laid as a fillet by putty knife or finger in the mould edges (corners) of the steel ingot mould.
iron cement protects the ingot against the hot, abrasive steel casting process.
a fire restant repair cement for fire places, ovens, open fireplaces etc.
Construction and repair of highways and...
An announcement must be commercial character.
Goods and services advancement through the P.O.Box system is NOT ALLOWED.
Deliveries (spam) and other improper information deleted.
Translator Internet is a Toolbar for MS Internet Explorer.
It allows you to translate in real time any web pasge from one language to another.
You only have to select languages and TI does all the work for you! Automatic dictionary updates....
**[root@dnnl data]$ head europarl-v7.de-en.de** 
Wiederaufnahme der Sitzungsperiode
Ich erkläre die am Freitag, dem 17. Dezember unterbrochene Sitzungsperiode des Europäischen Parlaments für wiederaufgenommen, wünsche Ihnen nochmals alles Gute zum Jahreswechsel und hoffe, daß Sie schöne Ferien hatten.
Wie Sie feststellen konnten, ist der gefürchtete "Millenium-Bug " nicht eingetreten. Doch sind Bürger einiger unserer Mitgliedstaaten Opfer von schrecklichen Naturkatastrophen geworden.
Im Parlament besteht der Wunsch nach einer Aussprache im Verlauf dieser Sitzungsperiode in den nächsten Tagen.
Heute möchte ich Sie bitten - das ist auch der Wunsch einiger Kolleginnen und Kollegen -, allen Opfern der Stürme, insbesondere in den verschiedenen Ländern der Europäischen Union, in einer Schweigeminute zu gedenken.
Ich bitte Sie, sich zu einer Schweigeminute zu erheben.
(Das Parlament erhebt sich zu einer Schweigeminute.)
Frau Präsidentin, zur Geschäftsordnung.
Wie Sie sicher aus der Presse und dem Fernsehen wissen, gab es in Sri Lanka mehrere Bombenexplosionen mit zahlreichen Toten.
Zu den Attentatsopfern, die es in jüngster Zeit in Sri Lanka zu beklagen gab, zählt auch Herr Kumar Ponnambalam, der dem Europäischen Parlament erst vor wenigen Monaten einen Besuch abgestattet hatte.
[yandaowei@dnnl data]$ head europarl-v7.de-en.en
Resumption of the session
I declare resumed the session of the European Parliament adjourned on Friday 17 December 1999, and I would like once again to wish you a happy new year in the hope that you enjoyed a pleasant festive period.
Although, as you will have seen, the dreaded 'millennium bug' failed to materialise, still the people in a number of countries suffered a series of natural disasters that truly were dreadful.
You have requested a debate on this subject in the course of the next few days, during this part-session.
In the meantime, I should like to observe a minute' s silence, as a number of Members have requested, on behalf of all the victims concerned, particularly those of the terrible storms, in the various countries of the European Union.
Please rise, then, for this minute' s silence.
(The House rose and observed a minute' s silence)
Madam President, on a point of order.
You will be aware from the press and television that there have been a number of bomb explosions and killings in Sri Lanka.
One of the people assassinated very recently in Sri Lanka was Mr Kumar Ponnambalam, who had visited the European Parliament just a few months ago.
**[root@dnnl data]$ head news-commentary-v11.de-en.de** 
Steigt Gold auf 10.000 Dollar?
SAN FRANCISCO – Es war noch nie leicht, ein rationales Gespräch über den Wert von Gold zu führen.
In letzter Zeit allerdings ist dies schwieriger denn je, ist doch der Goldpreis im letzten Jahrzehnt um über 300 Prozent angestiegen.
Erst letzten Dezember verfassten meine Kollegen Martin Feldstein und Nouriel Roubini Kommentare, in denen sie mutig die vorherrschende optimistische Marktstimmung hinterfragten und sehr überlegt auf die Risiken des Goldes  hinwiesen.
Und es kam, wie es kommen musste.
Seit der Veröffentlichung ihrer Artikel ist der Goldpreis noch weiter gestiegen.
Jüngst erreichte er sogar ein Rekordhoch von 1.300 Dollar.
Im letzten Dezember argumentierten die Goldbugs, dass der Preis zweifellos in Richtung 2.000 Dollar gehen würde.
Beflügelt aufgrund des anhaltenden Aufwärtstrends, meint man nun mancherorts, dass Gold sogar noch höher steigen könnte.
Ein erfolgreicher Gold-Investor erklärte mir vor kurzem, dass die Aktienkurse über ein Jahrzehnt dahingedümpelt waren, bevor der Dow Jones-Index in den frühen 1980er Jahren die Marke von 1.000 Punkten überschritt.
[root@dnnl data]$ **head news-commentary-v11.de-en.en**
$10,000 Gold?
SAN FRANCISCO – It has never been easy to have a rational conversation about the value of gold.
Lately, with gold prices up more than 300% over the last decade, it is harder than ever.
Just last December, fellow economists Martin Feldstein and Nouriel Roubini each penned op-eds bravely questioning bullish market sentiment, sensibly pointing out gold’s risks.
Wouldn’t you know it?
Since their articles appeared, the price of gold has moved up still further.
Gold prices even hit a record-high $1,300 recently.
Last December, many gold bugs were arguing that the price was inevitably headed for $2,000.
Now, emboldened by continuing appreciation, some are suggesting that gold could be headed even higher than that.
One successful gold investor recently explained to me that stock prices languished for a more than a decade before the Dow Jones index crossed the 1,000 mark in the early 1980’s

**Comment by Sarah-Callies** [comment]
I check all these three pairs of en and de file, they both have same line counts, what should I do next ?
thanks

**Comment by vince62s** [comment]
you can see the last 3 of commoncrawl are not aligned

**Comment by Sarah-Callies** [comment]
O my godness！ It takes me above four weeks to find, how to get the right origianl train file?  
Suggests: Maybe most of the newer may occurs the same mistakes, set one tips on the prepare_wmt_data.sh maybe helpful

**Comment by vince62s** [comment]
as I said, I don't think this is the issue because I same files and these alignment errors are there too. Commoncrawl is dirty anyway but it should be your issue.

**Comment by vince62s** [comment]
send me a link with your spm model and vocab files, I'll test it.

**Comment by Sarah-Callies** [comment]
[vocab.txt](https://github.com/OpenNMT/OpenNMT-py/files/10131906/vocab.txt)
[spm-model.txt](https://github.com/OpenNMT/OpenNMT-py/files/10131907/spm-model.txt)

Next
I will check the other two train pairs and then train it again

**Comment by vince62s** [comment]
I found your issue, you need position_encoding: true in the config
it is here: https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md
but for some reason it has been omitted in the guide you referred to in your first post.
Sorry.
