### ISSUE TITLE
sent sentence None

### ISSUE THREAD

**Issue by guoyihonggyh** [OpenNMT/OpenNMT-py#2264]
<img width="863" alt="image" src="https://user-images.githubusercontent.com/54264468/205430811-0c060f6c-5546-417e-932a-e38ca676099d.png">

**Comment by guoyihonggyh** [comment]
All the sent sentence is none

**Comment by vince62s** [comment]
from README:
Note:

The predictions are going to be quite terrible, as the demo dataset is small. Try running on some larger datasets! For example you can download millions of parallel sentences for [translation](http://www.statmt.org/wmt16/translation-task.html) or [summarization](https://github.com/harvardnlp/sent-summary).
