### ISSUE TITLE
TransformerDecoder class layer cache

### ISSUE THREAD

**Issue by MaxThFe** [OpenNMT/OpenNMT-py#2280]
In v3.0 in the TransformerDecoder class, the layer cache is no longer reset. This leads to an error when switiching between training and inference. During inference, in the layer cache the keys, etc. of the last tokens are saved, but they need to be removed when switching back to training.

**Comment by vince62s** [comment]
Hi @MaxThFe ,
Can you please be more specific in what context (training Inference training) you are seeing this ?

**Comment by MaxThFe** [comment]
@vince62s Sorry about being unclear. This happens when inferencing first and then training the model. I believe this is due to the following change:

In version 2.3.0, in onmt.decoders.TransformerDecoder.forward, the forward is implemented with a cache check:
for i, layer in enumerate(self.transformer_layers):
            layer_cache = (
                self.state["cache"]["layer_{}".format(i)]
                if step is not None
                else None
            )
            output, attn, attn_align = layer(
                output,
                src_memory_bank,
                src_pad_mask,
                tgt_pad_mask,
                layer_cache=layer_cache,
                step=step,
                with_align=with_align,
            )

In version 3.0 however this part is changed:
        for layer in self.transformer_layers:
            dec_out, attn, attn_align = layer(
                dec_out,
                enc_out,
                src_pad_mask,
                tgt_pad_mask,
                step=step,
                with_align=with_align,
            )
            if attn_align is not None:
                attn_aligns.append(attn_align)

Thus, when calling the forward function during inference, the cache of each layer of self attention is filled. Afterwards however, when calling the forward function in training, this leads to an error as there is layer cache. This is unwanted behaviour, as denoted in onmt.modules.MultiHeadedAttention.forward as well:
# 1) Project key, value, and query.
        # as a reminder at training layer_cache[0] remains False
        if self.layer_cache[0]:

Hope this is sufficiently clear.

**Comment by vince62s** [comment]
I know but in what context are you experiencing this ?

**Comment by vince62s** [comment]
for instance, when we train with the new scroing stuff at validation time, then we do this:
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/utils/scoring_utils.py#L163-L172

**Comment by MaxThFe** [comment]
@vince62s oh I see what you mean. I used only the decoder model in a custom training framework.

**Comment by vince62s** [comment]
But overall you are correct, there is a slight change in behavior if we consider the API as a library for custom frameworks.
Can you PR ?
I think the easiest would be a test on step == None to reset the cache.
