### ISSUE TITLE
how to use replace_unk in translate

### ISSUE THREAD

**Issue by Sarah-Callies** [OpenNMT/OpenNMT-py#2282]
1、Although I only see the “replace_unk“ parameter in the translation phase
I still configured  “replace_unk“in the training yaml configuration file: True

2、Of course, I also added  “replace_unk“ in the translation phase
But it turns out that this configuration doesn't work to replace the unk by copying the source token using attention scores as doc said

Is there anything wrong? thanks

**Comment by vince62s** [comment]
https://forum.opennmt.net/t/translate-py-with-replace-unk-option-and-the-transformer-model/2646
