### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'label_smoothing

### ISSUE THREAD

**Issue by Phil-521** [OpenNMT/OpenNMT-py#2283]
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?7449f4c8-5935-4acc-94b4-c7adc09c24a1)
/home/admin/wmc/Ph1/OpenNMT-Tutorial-main/nmt
[2022-12-27 17:58:23,268 WARNING] Corpus corpus_1's weight should be given. We default it to 1 for you.
[2022-12-27 17:58:23,269 INFO] Parsed 2 corpora from -data.
[2022-12-27 17:58:23,269 INFO] Get special vocabs from Transforms: {'src': [], 'tgt': []}.
[2022-12-27 17:58:23,349 INFO] Building model...
[2022-12-27 17:58:27,632 INFO] NMTModel(
  (encoder): TransformerEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(14720, 512, padding_idx=1)
        )
        (pe): PositionalEncoding(
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (transformer): ModuleList(
      (0): TransformerEncoderLayer(
        (self_attn): MultiHeadedAttention(
          (linear_keys): Linear(in_features=512, out_features=512, bias=False)
          (linear_values): Linear(in_features=512, out_features=512, bias=False)
          (linear_query): Linear(in_features=512, out_features=512, bias=False)
          (softmax): Softmax(dim=-1)
          (dropout): Dropout(p=0.1, inplace=False)
...
    train_loss = LossCompute.from_opts(opt, model, vocabs['tgt'])
  File "/home/admin/anaconda3/envs/openue/lib/python3.8/site-packages/onmt/utils/loss.py", line 88, in from_opts
    criterion = nn.CrossEntropyLoss(
**TypeError: __init__() got an unexpected keyword argument 'label_smoothing'**

**Comment by Phil-521** [comment]
I guess it‘s the problem of torch version ，but torch==1.9.0 doesn't work

**Comment by vince62s** [comment]
yes you need at least 1.0 but try to use the last version anyway.

**Comment by Phil-521** [comment]
> 

It does work, thank you very much!
