### ISSUE TITLE
Problem of Pretraining BART model from scratch.

### ISSUE THREAD

**Issue by medicine-wave** [OpenNMT/OpenNMT-py#2291]
I find `Transform/BART` in `Build Vocab/Train/Translate `
How can I pretrain the BART model or generating the noisying results in my own data corpus by using these modules? 
Appreciate very much!

**Comment by vince62s** [comment]
this is github issues here. please use the forum for those questions.
https://forum.opennmt.net/latest

**Comment by medicine-wave** [comment]
Thanks for your guidance!
