### ISSUE TITLE
Normalization of loss

### ISSUE THREAD

**Issue by sandyhouse** [OpenNMT/OpenNMT-py#2293]
As stated by the issue #2209 , 

> the loss of each mini batch is normalized by the global batch "normalization" number of token instead of the number of tokens of each mini-batch.

The loss of each mini batch, however, is calculated on tokens of each mini batch, so why should we normalize the loss of each mini batch by the global batch "normalization"?

**Comment by vince62s** [comment]
I reconsidered my position.
The accurate way is to divide the loss by the exact total of token in the global batch.
If you normalize each minibatch by the number of each mini batch tokens, then you cannot just average because each mini batch may have a different number of tokens.
