### ISSUE TITLE
Error with supervised learning of alignments

### ISSUE THREAD

**Issue by anderleich** [OpenNMT/OpenNMT-py#2301]
Hi,

I'm trying to learn alignments during the training phase of the Transformer. I've followed the FAQ: https://opennmt.net/OpenNMT-py/FAQ.html#supervised-learning-on-a-specific-head

This is my config:

```
data:
   train:
       path_src: CORPUS/train/data.train.es
       path_tgt: CORPUS/train/data.train.eu
       path_align: CORPUS/train/data.train.align
       transforms: [filtertoolong]
       weight: 1
   valid:
       path_src: CORPUS/dev/data.dev.es
       path_tgt: CORPUS/dev/data.dev.eu
       path_align: CORPUS/dev/data.dev.align
       transforms: []

# Alignment
lambda_align: 0.05
alignment_heads: 1
alignment_layer: -3
full_context_alignment: true

```

Everything seems to be right until the training phase starts. The model and data are loaded correctly. However, I get this error in backpropagation:

```
Traceback (most recent call last):
  File "OpenNMT-py_v2.0/onmt/trainer.py", line 432, in _gradient_accumulation
    loss, batch_stats = self.train_loss(
  File "OpenNMT-py_v2.0/onmt/utils/loss.py", line 195, in __call__
    for shard in shards(shard_state, shard_size):
  File "OpenNMT-py_v2.0/onmt/utils/loss.py", line 462, in shards
    torch.autograd.backward(inputs, grads)
  File "venv_latest/lib/python3.8/site-packages/torch/autograd/__init__.py", line 166, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_, is_grads_batched=False)
  File "venv_latest/lib/python3.8/site-packages/torch/autograd/__init__.py", line 67, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs
```
The code is at this commit: 173e113b1220b32c1d03a0f8d3f9d44759c071de

Any clues?

Thanks

**Comment by vince62s** [comment]
you must have opt.max_generator_batches > 0
try to set it to 0

**Comment by anderleich** [comment]
Great! That solved the error

What does `opt.max_generator_batches > 0` do?

`alignment_layer: -3` indicates the index of the decoder layer on which we do alignment supervised learning. After the training is complete we ca use `-report_align` to output the translation alignments. According to the documentation:

>  Those alignments are computed from an argmax on the average of the attention heads of the second to last decoder layer.

My question is: if we do supervised training are the alignments still computed from the argmax on the average of the attention heads of the second to last decoder layer, or are they computed from the -3 layer as during the training phase?

Thanks

**Comment by francoishernandez** [comment]
> What does opt.max_generator_batches > 0 do?

https://github.com/OpenNMT/OpenNMT-py/issues/2072#issuecomment-918951588

> My question is: if we do supervised training are the alignments still computed from the argmax on the average of the attention heads of the second to last decoder layer, or are they computed from the -3 layer as during the training phase?

As stated in the same docs:
Note: The *second to last* default behaviour was empirically determined. It is not the same as the paper (they take the *penultimate* layer), probably because of light differences in the architecture.

It's not hardcoded, just a default behaviour specific to the onmt implementation.

You can also check the code, where you see the alignment_layer value is used in the transformer decoder:
https://github.com/OpenNMT/OpenNMT-py/blob/d30366e1eb2d476e26876c632d00a8c07c408638/onmt/decoders/transformer.py#L478
