### ISSUE TITLE
 Error: Output 0 of SplitBackward0 is a view and is being modified inplace.

### ISSUE THREAD

**Issue by safae2023** [OpenNMT/OpenNMT-py#2303]
I tried to run the MMESGN code but found this error : RuntimeError: Output 0 of SplitBackward0 is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one. please if you can help me

**Comment by vince62s** [comment]
did you mean posting this issue somewhere else ?
