### ISSUE TITLE
Alignments between source and gold target not being predicted

### ISSUE THREAD

**Issue by anderleich** [OpenNMT/OpenNMT-py#2310]
Hi,

I'm trying to evaluate the alignments between the source tokens and the gold target tokens. According to the docs:

> Using the -tgt option when calling translate.py, we output alignments between the source and the gold target rather than the inferred target, assuming we’re doing evaluation.

However, in both cases, with and without the `-tgt` option I get the same alignments. I think it is not using the gold target to align...

The code is at this commit: https://github.com/OpenNMT/OpenNMT-py/commit/173e113b1220b32c1d03a0f8d3f9d44759c071de

Any clues?

**Comment by vince62s** [comment]
https://github.com/OpenNMT/OpenNMT-py/pull/1788
@francoishernandez @Zenglinxiao can you confirm the FAQ doc is no longer correct ? -tgt does not trigger golden alignment anymore.

**Comment by francoishernandez** [comment]
I'll let @Zenglinxiao circle back if needed, but my understanding is the same.
We can probably fix the docs, and add some mention similar to the PR comment
> In this PR, we, therefore, remove this implicit handling, if one would like to just verify the alignment quality, they can always add these lines on and set -replace_unk to false to avoid this conflict.

**Comment by Zenglinxiao** [comment]
> #1788 @francoishernandez @Zenglinxiao can you confirm the FAQ doc is no longer correct? -tgt does not trigger golden alignment anymore.

Yes. I can confirm this. `--tgt` to get golden alignment is removed in that PR. We can fix that line in the doc.

**Comment by vince62s** [comment]
@anderleich do you want to fix the doc or implement a flag to re-allow the old code ?
I'm fine with both options if there is a real interest in having this.

**Comment by anderleich** [comment]
I think it is interesting to have this option to evaluate the alignments learnt by supervised learning. Getting the alignments for the gold target is essential to evaluate this task, as reference alignments are manually annotated on the gold target. Otherwise, we are evaluating translation alignments against the reference alignments which do not match.
