### ISSUE TITLE
[feature request] add BPE learning as an optional preamble to build_vocab

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT-py#2312]
Contribution welcome.

Steps are here: https://github.com/OpenNMT/Tokenizer/tree/master/bindings/python#subword-learning

@ymoslem interested to contribute ?

**Comment by ymoslem** [comment]
Thanks, Vincent! Do you mean implementing something like the SentencePiece option available in [build vocab of OpenNMT-tf](https://github.com/OpenNMT/OpenNMT-tf/blob/2b196ff883e983b8d022c697fa56e921de798a6d/opennmt/bin/build_vocab.py) into the [build vocab of OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py/blob/62c96cccdae712a38a66032a7bbdb67e1c2bf762/onmt/bin/build_vocab.py)? Do you suggest adding only `BPELearner` or also `SentencePieceLearner`?

**Comment by vince62s** [comment]
yes I think both would be good add-on features to avoid side scripts that everyone has.
In the same vein, maybe an alignment feature (using fast align) to generate a bilingual terminology might be useful.

**Comment by ymoslem** [comment]
I should start working on these in March (if they are not too urgent). Thanks!

**Comment by vince62s** [comment]
as an extra step, it might be good also to build a bilingual dictionary with fastalign in order to feed some specific transforms like #2321

**Comment by ymoslem** [comment]
> add BPE learning as an optional preamble to build_vocab

I finished this for both BPE and SPM. What should be the value of `opts.vocab_sample_queue_size` if the default is used. The default is 20. For SPM, it must be at least 50 as `required_chars` is 50. However, with this small number, the generated vocab is only characters. Should I set to something higher if the default is used?

**Comment by vince62s** [comment]
@francoishernandez 
no clue why this: https://github.com/OpenNMT/OpenNMT-py/commit/d149e2e961fd19816256b0073f3188f2256a1356

**Comment by francoishernandez** [comment]
I have no specific recollection of this... Probably just followed empirical performance observations.
@ymoslem I'm not sure this flag is relevant here, as it's just used for the processes dumping the samples to disk. The actual vocabulary building relies more on the `n_sample` opt.

**Comment by ymoslem** [comment]
Thanks! @francoishernandez

Here is the function used now. What should be used for `symbols` and `vocab_size`? I do not want to hardcode it as the dataset might be small.

```python
def learn_subword(opts):
    if opts.tokenization_type == "bpe":
        tokenizer = pyonmttok.Tokenizer("aggressive", joiner_annotate=True, segment_numbers=True)
        learner = pyonmttok.BPELearner(tokenizer=tokenizer, symbols=opts.vocab_sample_queue_size)
    elif opts.tokenization_type == "spm":
        if opts.vocab_sample_queue_size < 50:
            opts.vocab_sample_queue_size = 50
        learner = pyonmttok.SentencePieceLearner(vocab_size=opts.vocab_sample_queue_size, character_coverage=0.98)

    return learner
```

---

As you can see above, I added this condition. If I remove it (and vocab_sample_queue_size is not set in the *.yml file):
```python
if opts.vocab_sample_queue_size < 50:
    opts.vocab_sample_queue_size = 50
```

... it shows this error:
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/xxx/Downloads/OpenNMT-py/onmt/bin/build_vocab.py", line 85, in build_sub_vocab
    tokenizer = learner.learn(tok_path)
RuntimeError: SentencePieceTrainer: Internal: /Users/runner/work/Tokenizer/Tokenizer/third_party/sentencepiece/src/trainer_interface.cc(512) [(static_cast<int>(required_chars_.size() + meta_pieces_.size())) <= (trainer_spec_.vocab_size())] Vocabulary size is smaller than required_chars. 20 vs 50. Increase vocab_size or decrease character_coverage with --character_coverage option.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxx/Downloads/OpenNMT-py/build_vocab.py", line 6, in <module>
    main()
  File "/Users/xxx/Downloads/OpenNMT-py/onmt/bin/build_vocab.py", line 238, in main
    build_vocab_main(opts)
  File "/Users/xxx/Downloads/OpenNMT-py/onmt/bin/build_vocab.py", line 202, in build_vocab_main
    src_counter, tgt_counter, src_feats_counter = build_vocab(
  File "/Users/xxx/Downloads/OpenNMT-py/onmt/bin/build_vocab.py", line 168, in build_vocab
    for sub_counter_src, sub_counter_tgt, sub_counter_src_feats in p.imap(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
RuntimeError: SentencePieceTrainer: Internal: /Users/runner/work/Tokenizer/Tokenizer/third_party/sentencepiece/src/trainer_interface.cc(512) [(static_cast<int>(required_chars_.size() + meta_pieces_.size())) <= (trainer_spec_.vocab_size())] Vocabulary size is smaller than required_chars. 20 vs 50. Increase vocab_size or decrease character_coverage with --character_coverage option.
```

So, my question is, do you want me to keep the aforementioned condition or to handle it differently?

Thanks!

**Comment by vince62s** [comment]
@ymoslem this opts.vocab_sample_queue_size is completely unrelated with the vocab size.
the vocab size setting comes from src_vocab_size, tgt_vocab_size and whether share_vocab is true or not.
I think the best is you to submit your PR and then we will review it in context.
many thanks.
