### ISSUE TITLE
Help with feeding in custom data example

### ISSUE THREAD

**Issue by cmosguy** [OpenNMT/OpenNMT-py#2319]
Hello,

I have a toy example of machine data that I want to translate over.  Is there a toy example that can help explain how I can format my data and feed into OpenNMT?

The table below is input-->output
![image](https://user-images.githubusercontent.com/1676382/219883237-56a99e63-e09e-4225-b0e8-52b2d70f47ec.png)

Thanks!

**Comment by vince62s** [comment]
What is your task and why do you think OpenNMT is the right tool to accomplish what you are trying to do ?

**Comment by cmosguy** [comment]
Hello @vince62s, apologies on the slow response.  Is there a way to reopen this issue.  Please let me explain the problem a bit more:

I am trying to solve a very specific domain problem. I have a project where I must take input text that contains domain specific codes in the text and translate it to a specific output.

I am using `ABC` and `FOO` to just convey the basic idea here, because I do not want to distract with problem statement. However, my domain is electrical engineering data. There will be words like: Port, VSS, GND, CHA, etc. 

In this example, I have an input text, and what I am showing you is the output result that I am trying to produce from the model. This example shows input text → output result I want, for example:
! Port[1] = ABCZ4_FOO1 -model-> ABC_c_FOO1
or
! Port[4] = ABC4_FOO1 -model-> ABC_t_FOO1

There are many variations of this input text, where in some cases it would be ABC3 instead of ABCZ4, so in this case the input/output would be:
! Port[1] = ABC3_FOO1 -model-> ABC_c_FOO1

What I am trying to figure out is what would be the best model transformer, base mode model and then training task. Should I use translation, masking, or something else?

You can see that the input has individual character input tokens, and the sequence of characters gives more context. My instincts is that a transformer makes sense here because “attention” is needed on the specific character tokens to be translated to an output.

The snapshot above is an example table of input/output. The goal is to train on the inputs/outputs.  There is a ton of variations of possibilities of the input tokens that could be provided with different text. BTW, I have about 700 training input/output samples. Do you think this would be enough or would I need generate more?  

I am trying to figure out how to potentially use opennmt for my use case.  Do you have any ideas how I could start with this?

**Comment by vince62s** [comment]
Are you saying you have only 700 samples but potentially there could be similar input that you would like to "translate" into an output ?
if so, I think it will be difficult to train anything with 700 samples.
You can try:
to tokenize at the character level in order to have a sequence of something
I would start with a very very small rnn and see the results first before thinking of a transformer.
Again, AI is based on lots of data, so your use case seem a bit outside this scope.
