### ISSUE TITLE
Where does the seq2seq/translation model append special tokens into raw texts?

### ISSUE THREAD

**Issue by JiankunW** [OpenNMT/OpenNMT-py#2320]
Hi, I am a newbie to NMT/seq2seq field and luckily find this wonderful repo to learn a lot from.

After wandering through the code, I am confused about where it appends the special tokens like \<eos> \<bos> \<pad> into the batched sentences. 

I noticed the transform methods `PrefixTransform`, `SuffixTransform` are able to deal with appending the special tokens. However, both the [data configuration](https://github.com/OpenNMT/OpenNMT-py/blob/master/examples/wmt17/wmt17_ende.yaml) for `wmt17` and the [data configuration](https://opennmt.net/OpenNMT-py/examples/Translation.html#step-1-build-the-vocabulary) for `wmt14` do not config these two transforms. So I am wondering where you append special tokens into sentences for translation tasks.

Thanks
Jiankun

**Comment by vince62s** [comment]
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/inputters/text_utils.py#L116

**Comment by JiankunW** [comment]
> https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/inputters/text_utils.py#L116

Thanks.
