### ISSUE TITLE
Remove Optim class, switch to new pytorch rate features.

### ISSUE THREAD

**Issue by srush** [OpenNMT/OpenNMT-py#233]
Pytorch has this nifty LR schedule http://pytorch.org/docs/master/optim.html#how-to-adjust-learning-rate We should move to that instead of our hacks.

**Comment by JianyuZhan** [comment]
I would like to do it.

**Comment by srush** [comment]
Actually we can be even more aggressive here. Let's remove Optim.py
entirely. We shouldn't need our own optimization class, if we have a
function to translate opt to the Optim construction arguments , we can just
use pytorch's defaults.

**Comment by JianyuZhan** [comment]
Ah, aggreed! Staring at the all assortment of Optim features in pytorch, I was wondering it would be too tedious to just add a wrapper.

**Comment by srush** [comment]
Yeah, I don't think we need to wrap everything there. For now though, let's keep the same functionality, but remove all our Optim class. Just like with Dataset, the new pytorch features make our code redundant.

**Comment by JianyuZhan** [comment]
Will do.
