### ISSUE TITLE
Implement Flash Attention

### ISSUE THREAD

**Issue by JOHW85** [OpenNMT/OpenNMT-py#2331]
Now that PyTorch 2.0 is out and supports native Flash Attention, perhaps OpenNMT-py should support it? This can help in creating document-level models with the longer context length instead of sentence-based models.

https://pytorch.org/tutorials/intermediate/scaled_dot_product_attention_tutorial.html

![image](https://user-images.githubusercontent.com/1308761/225953208-f01522a1-b932-4699-b739-a119fdac203d.png)

**Comment by vince62s** [comment]
FYI we just committed a doc level transform. https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md#context--doc-aware-transform

**Comment by JOHW85** [comment]
> 

Yes, I'm aware. But I'm looking more at like >1024 context length, preferably 4k or 8k long. Flash Attention should be helpful in the training efficiency.

**Comment by louisoutin** [comment]
Is this something planned to be implemented still? :)
I'm not sure what's the actual max input length I can finetune some LLM on.

**Comment by vince62s** [comment]
are you interested in sending a PR ? this is not very difficult to implement.
