### ISSUE TITLE
Difference in training results between single GPU and multi-GPU

### ISSUE THREAD

**Issue by githubjixin** [OpenNMT/OpenNMT-py#2335]
For single GPU and multi-GPU training, the single card is 4% higher than the multi-card training. What is the cause?
Here is my configuration：
<img width="150" alt="image" src="https://user-images.githubusercontent.com/109410944/226503405-f70fa165-2fe6-4c23-b1bd-e4d4e7610c32.png">
<img width="207" alt="image" src="https://user-images.githubusercontent.com/109410944/226503453-a0e1ba34-47ff-482e-86ad-13602c338ef1.png">

**Comment by vince62s** [comment]
what do you mean by "is 4% higher" ?

**Comment by githubjixin** [comment]
Forgot to write that BLEU is 4% higher on a single card than on a multi-card

**Comment by vince62s** [comment]
is it just one run each or same obseravtion over several runs ? can you post the end of the logs for each ? (with last steps or train + validation)

**Comment by githubjixin** [comment]
By the way, at the beginning of multi-card training, you did not average batch_size and then distribute data like TORCH.DISTRIBUTED. Each card has the same initial batch_size, right?

**Comment by githubjixin** [comment]
On the left is the final training result of a single card, and on the right is the multi-card：
<img width="623" alt="image" src="https://user-images.githubusercontent.com/109410944/226545929-7f4553ae-6575-4cb4-9a37-4a23a07368d6.png">

**Comment by vince62s** [comment]
what version of OpenNMT-py do you use ?

**Comment by githubjixin** [comment]
master

**Comment by vince62s** [comment]
if you're 100% sure of the process (same data -train - valid) so on, my suggestion would be to test v3.0.4 to see if it comes from a recent commit (I changed striding since 3.0.4).
Another test could be to revert https://github.com/OpenNMT/OpenNMT-py/issues/2295 back to async_op=True
to see if this has a real impact.
If you have time to test these 2 leads, it might be helpful for others.

**Comment by githubjixin** [comment]
Ok, thank you for your reply. I'll have a try

**Comment by githubjixin** [comment]
Can you explain how multi-card data parallelism works in your latest version? thank you

**Comment by githubjixin** [comment]
batch_size is divided into multiple copies and distributed to each GPU model in parallel. How do you do it in the code? I can't find it.
