### ISSUE TITLE
ONMTDataset don't need to set sort_key to be reverse size order

### ISSUE THREAD

**Issue by jingxil** [OpenNMT/OpenNMT-py#234]
As `__iter__ ` function of `Iterator ` class in torchtext would sort the batch reversely by sort_key, we don't need to set the sort_key `-len(ex.src)`. Instead, the sort_key should be `len(ex.src)`. Otherwise, ValueError "lengths array has to be sorted in decreasing order" pops up.

**Comment by srush** [comment]
Yeah, use the torchtext in pip. They just changed behavior in the repo.

**Comment by jingxil** [comment]
That explained why we were required using pip to install dependency packages :)
