### ISSUE TITLE
Incorporating part-of-speech features

### ISSUE THREAD

**Issue by Phil-521** [OpenNMT/OpenNMT-py#2348]
If my corpus size is 37000, the format is like (元祐|t 初|t ，|w 復|d 置|v 簽書|nx 院|nx 事|nx ，|w 仍|c 以|p 樞密|nx 直學士|nx 充|v 。|w),and I'm using OpenNMT V3 for translation research that involves incorporating part-of-speech features, is it reasonable to set my parameters as follows? Although the model runs successfully, the results don't seem to have improved.
dropout: 0.5
n_src_feats: 1
src_feats_defaults: "1"
feat_merge: "concat"
decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
feat_vec_size: 12
hidden_size: 512
batch_size: 512
share_vocab: False
src_vocab_size: 200000
tgt_vocab_size: 200000
or not use transformer:
n_src_feats: 1
src_feats_defaults: "1"
feat_merge: "sum"

**Comment by vince62s** [comment]
last time I tried, did not get better result either.
