### ISSUE TITLE
Only one layer_norm in Encoder? 

### ISSUE THREAD

**Issue by sleepwalker2017** [OpenNMT/OpenNMT-py#2364]
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/encoders/transformer.py#:~:text=def%20forward(self%2C%20layer_in%2C%20mask)%3A

Here I see the encoder only has one layer_norm, but in decoder it has 2 layer_norms, why is this?

**Comment by vince62s** [comment]
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/encoders/transformer.py#L41
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/encoders/transformer.py#L104
