### ISSUE TITLE
Unable to build gcld3 wheels 

### ISSUE THREAD

**Issue by patrickpato** [OpenNMT/OpenNMT-py#2380]
As recently as April 2023, I was able to install and run openNMT-py on Colab without any challenge. However, my attempts to install openNMT-py on Colab recently have been unsuccessful with the process returning this error code: 

Building wheels for collected packages: gcld3
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for gcld3 (setup.py) ... error
  ERROR: Failed building wheel for gcld3
  Running setup.py clean for gcld3
Failed to build gcld3
ERROR: Could not build wheels for gcld3, which is required to install pyproject.toml-based projects

On Kaggle, for instance, the installation works well. I tried downgrading from Python 3.10 to Python 3.9 on Colab but this solution did not work. 
Is this an OpenNMT-py issue or is it related to Colab? 
Thank you for this amazing product by the way!

**Comment by vince62s** [comment]
see #2370 
I will release so that this is taken into account
