### ISSUE TITLE
Install as a library

### ISSUE THREAD

**Issue by srush** [OpenNMT/OpenNMT-py#239]
Users should be able to eventually install and use directly from torch without the command line. Think we are getting closer to that.

**Comment by srush** [comment]
Almost have this one done. We just need to move training to a library and have an example use case.

**Comment by JianyuZhan** [comment]
Train library is implemented in https://github.com/OpenNMT/OpenNMT-py/pull/276.  `onmt/Trainer.py` is the library, `train.py` is the first example use case.

Next step is do the same for the translation part.

**Comment by srush** [comment]
I think we are basically here on this on. Have an example up http://opennmt.net/OpenNMT-py/Library.html

**Comment by paruul** [comment]
How can I run translation without command line, unfortunately I couldn't find it in the documentation. Could anyone please direct me to the documentation if it already exists. Thank you!
