### ISSUE TITLE
 Error with lora_weights.py 

### ISSUE THREAD

**Issue by martinbombin** [OpenNMT/OpenNMT-py#2393]
Got following error when I was trying to merge lora weights with last PR.

File “/home/m.barroso/OpenNMT_nllb/OpenNMT-py/tools/lora_weights.py”, line 45, in
base_checkpoint = load_checkpoint(opt.base_model, map_location=torch.device(“cpu”))
TypeError: load_checkpoint() got an unexpected keyword argument ‘map_location’

I had to comment map_location in the function call.

After that, I had to make changes to 3 lines of code that were trying to access to model generator in lora's checkpoint that is empty.

2 of them in model.saver.py

if  "0.weight" in checkpoint["generator"]:  ->  checkpoint["generator"] and "0.weight" in checkpoint["generator"]:
...
if "0.bias" in checkpoint["generator"]:  -> checkpoint["generator"] and "0.bias" in checkpoint["generator"]:

and 1 of them in model.py

name == "generator" and len(checkpoint["generator"].keys()) > 0  -> name == "generator" and checkpoint["generator"]

**Comment by vince62s** [comment]
can you please confirm it's working fine now ?

**Comment by martinbombin** [comment]
I think it is going to fail again. 

`                    elif (
                       "generator" in checkpoint.keys()
                        and name == "generator"
                        and len(checkpoint["generator"].keys()) > 0
                    ):
`
This elif is going to fail because generator is in checkpoint.keys() but has no values. It is going to pass until it reaches len(checkpoint["generator"].keys()) > 0, where is going to fail because it has no keys.

Anything else seems ok now

**Comment by vince62s** [comment]
oh sorry I misunderstood your point.
