### ISSUE TITLE
Fix merging of lora weights

### ISSUE THREAD

**Issue by JOHW85** [OpenNMT/OpenNMT-py#2404]
Getting the error when trying to merge the lora weights with the base model (Falcon).
```
onmt/models/model_saver.py", line 54, in load_checkpoint
    if "0.weight" in checkpoint["generator"]:
TypeError: argument of type 'NoneType' is not iterable
```
See: https://forum.opennmt.net/t/error-with-lora-weights-py/5357

**Comment by vince62s** [comment]
you are not on master. it was fixed here https://github.com/OpenNMT/OpenNMT-py/pull/2394
