### ISSUE TITLE
Problem in implementing : "Linguistic Input Features Improve Neural Machine Translation"

### ISSUE THREAD

**Issue by yash-srivastava19** [OpenNMT/OpenNMT-py#2408]
As given in the title, I'm trying to implement the paper(with Transformer architecture), but I seem to encounter the following issue while training: 
``` 
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 43, in fetch
    data = next(self.dataset_iter)
  File "/usr/local/lib/python3.10/dist-packages/onmt/inputters/dynamic_iterator.py", line 341, in __iter__
    tensor_batch = tensorify(self.vocabs, minibatch)
  File "/usr/local/lib/python3.10/dist-packages/onmt/inputters/text_utils.py", line 203, in tensorify
    tbatchsrc = torch.stack(tbatchfs, dim=2)
RuntimeError: stack expects each tensor to be equal size, but got [50, 42] at entry 0 and [50, 1] at entry 1
``` 
I have the data for source language in the following format : 
``` A|DET black|ADJ box|NOUN in|ADP your|PRON car|NOUN ?|PUNCT
    The|DET tea|NOUN party|NOUN is|AUX aghast|ADJ .|PUNCT
    This|PRON really|ADV is|AUX a|DET must|NOUN for|ADP our|PRON nation|NOUN .|PUNCT 
    ...
    ...
```
I followed the following tutorial(how to use source word features) given [here](https://opennmt.net/OpenNMT-py/FAQ.html#how-can-i-use-source-word-features). I get that I need to select the  `word_vec_size`,  `feat_merge` and `feat_vec_size`. 

Can you explain how do we need to set these(I can't find any mathematical or programattical explanation). Any help in this regard would be really great !! Other information : 

`data.yml` 

``` ... 

data:
    corpus_1:
        # path etc.
        transforms: [onmt_tokenize, inferfeats, filtertoolong]

    valid:
        # path etc.
        transforms: [onmt_tokenize, inferfeats]

reversible_tokenization: "joiner"

n_src_feats: 2
src_feats_defaults: "0￨1"
feat_merge: "concat"

... 
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 3
dec_layers: 3
heads: 2
hidden_size: 64
word_vec_size: 64
transformer_ff: 128
```

**Comment by vince62s** [comment]
if you use "sum" then you don't need to change the hidden_size/word_vec_size
if you use concat the sum of hidden_size and feat_merge_size need to match the "theoric" size of hidden_size
for instance, if wanted hidden_size is 512 then use something like 480 and then 32 for feat size if you use concat.

**Comment by yash-srivastava19** [comment]
Ok. That makes sense. I tried that, the problem was in the way I was applying the transforms. On removing the tokenization transform, it worked(which, I see going through the documentation shouldn't matter - if you have tokenized or pretokenized input)

**Comment by yash-srivastava19** [comment]
I believe this issue is resolved.
