### ISSUE TITLE
Integration of OpenNMT-py with Adapter-Transformers ?

### ISSUE THREAD

**Issue by yash-srivastava19** [OpenNMT/OpenNMT-py#2415]
Hi !!

I would like to add a feature request if there were a way to integrate [adapter-transformers](https://docs.adapterhub.ml/index.html) with OpenNMT-py ? I know it might not be too difficult, but even if I were to do it, I need some good enough place to start.

Having adapters with OpenNMT-py would actually be really awesome, both of them will compliment each other really good !!

Any pointers(or better, some people) would be really awesome !!

**Comment by vince62s** [comment]
what exactly are you trying to achieve ?

**Comment by yash-srivastava19** [comment]
I'm trying to make a seq to seq model of Transformer on some parallel corpus that I have.

OpenNMT allows me to incorporate linguistic features, and a much more freedom in terms of transformer architecture

Having task adapters will allow me to use the same architecture, and get comparable performance as fine tuning.

**Comment by yash-srivastava19** [comment]
Even if that's a big task, if there are ways to port OpenNMT-py models to HuggingFace, as adapters-transformers provide support for them out of box...

**Comment by vince62s** [comment]
I don't know about what HF does or not but, IMO:
- incorporating linguistic features is already possible with the current OpenNMT-py architecture, dig in the doc, forum and code / options
- we do support LoRA adapter already but it won't help for linguitic features, just finetuning
- In general OpenNMT-py is very modular but indded you need to read the code if you want to modify stuff. we jsut commited a PR to support custom encoders / decoders so you could just copy paste the codes of transformers encoder/decoder and modify on demand.


closing for now, open a more specific issue or question on the forum for these.

Cheers.
