### ISSUE TITLE
build_vocab

### ISSUE THREAD

**Issue by xxiutong** [OpenNMT/OpenNMT-py#2433]
Hello，
I'm having a problem running the command onmt_build_vocab 
Traceback (most recent call last):
  File "build_vocab.py", line 7, in <module>
    from onmt.inputters.corpus import build_vocab
ImportError: cannot import name 'build_vocab' from 'onmt.inputters.corpus' (/home/tsmc/.conda/envs/py37/lib/python3.7/site-packages/onmt/inputters/corpus.py
Any ideas how to overcome the issue?
2.0.0rc1

**Comment by vince62s** [comment]
sorry we don't support that old beta version.
