### ISSUE TITLE
anyone knows the reference for copy attention and coverage attention?

### ISSUE THREAD

**Issue by cosmmb** [OpenNMT/OpenNMT-py#245]
hi there,

anyone knows the references for copy attention and coverage attention options? Is the transformer option from the "attention is all you need" ?

Thanks!

**Comment by srush** [comment]
Our implementation is from Abigail See's paper "Get to the Point"

Yes that is the transformer from AIAYN

**Comment by cosmmb** [comment]
Thanks!
