### ISSUE TITLE
some problem about "-world-size" and "gpu_ranks"

### ISSUE THREAD

**Issue by fdggdfgg** [OpenNMT/OpenNMT-py#2450]
If running a single GPU, only the 0th card can be run

**Comment by vince62s** [comment]
is this on current master?

**Comment by maxiek0071** [comment]
Hi, I can confirm that I cannot start a training on 3 out of my 4 GPUs with the config:

```
world_size: 4
gpu_ranks: [1, 2, 3]
```

I would like to use indices 1, 2, and 3 of GPUs. On index 0 there is a different job running.

I use OpenNMT-py v3.0.4.

**Comment by vince62s** [comment]
Obviously this is not new. Not sure if it was possible in the past.
In any case, you can just set CUDA_VISIBLE_DEVICES=1,2,3
then you need to set gou_ranks: [0, 1, 2]

**Comment by maxiek0071** [comment]
Hi, I tried your solution, and it doesn't work. OpenNMT training is still exectued on GPU with index 0, despite the fact it is supposed to be not visible.
I executed in bash:
```
CUDA_VISIBLE_DEVICES=1,2,3 ; echo $CUDA_VISIBLE_DEVICES
```
And in train config:
```
world_size: 3
gpu_ranks: [0, 1, 2]
```
Would you have any ideas?

Here is a screenshot of `nvidia-smi` before it crashes:
![image](https://github.com/OpenNMT/OpenNMT-py/assets/45405419/c60d048a-0c3f-4e84-8788-68a3243fa6fa)
We still OpenNMT training is still executed on GPU/0. (venv-comet is the other job).

**Comment by vince62s** [comment]
I think you need to use "export CUDA_VISIBLE_DEVICES=1, 2, 3"

**Comment by maxiek0071** [comment]
Ok, thanks, it works!

**Comment by vince62s** [comment]
And I confirm this has always been the case, so closing.

**Comment by fdggdfgg** [comment]
On a server with multiple graphics cards on one machine
Your code is as follows：

> if opt.gpuid:
>     raise AssertionError(
>           "gpuid is deprecated see world_size and gpu_ranks")
> if torch.cuda.is_available() and not opt.gpu_ranks:
>     logger.warn("You have a CUDA device, should run with -gpu_ranks")
> if opt.world_size < len(opt.gpu_ranks):
>     raise AssertionError(
>           "parameter counts of -gpu_ranks must be less or equal "
>           "than -world_size.")
> if opt.world_size == len(opt.gpu_ranks) and \
>         min(opt.gpu_ranks) > 0:
>     raise AssertionError(
>           "-gpu_ranks should have master(=0) rank "
>           "unless -world_size is greater than len(gpu_ranks).")

If running a single GPU，the main function(train_single) can only run when "world_size"=1 and "gpu_rank" = [0]

**Comment by fdggdfgg** [comment]
> 

On a server with multiple graphics cards on one machine
Your code is as follows：

_

> if opt.gpuid:
> raise AssertionError(
> "gpuid is deprecated see world_size and gpu_ranks")
> if torch.cuda.is_available() and not opt.gpu_ranks:
> logger.warn("You have a CUDA device, should run with -gpu_ranks")
> if opt.world_size < len(opt.gpu_ranks):
> raise AssertionError(
> "parameter counts of -gpu_ranks must be less or equal "
> "than -world_size.")
> if opt.world_size == len(opt.gpu_ranks) and
> min(opt.gpu_ranks) > 0:
> raise AssertionError(
> "-gpu_ranks should have master(=0) rank "
> "unless -world_size is greater than len(gpu_ranks).")

_

If running a single GPU，the main function(train_single) can only run when "world_size"=1 and "gpu_rank" = [0]

**Comment by fdggdfgg** [comment]
I use  OpenNMT-py v2.3.0
