### ISSUE TITLE
cuda out of memeory

### ISSUE THREAD

**Issue by Mamooshe** [OpenNMT/OpenNMT-py#2456]
training process faces with cuda out of memory for 1660 super gpu(6 GIG) for English persian language.
Do you know minimum gpu memory do we need for training?
or which paprameters can I set to overcome this problem?

**Comment by ILG2021** [comment]
1.3b needs 24G GPU, 3.3B maybe 40G, I haven't tried.

**Comment by vince62s** [comment]
Indeed with 6GB you'll be able to train only very small models.
