### ISSUE TITLE
translate only one sentence input by user.

### ISSUE THREAD

**Issue by 13633491388** [OpenNMT/OpenNMT-py#2461]
Is there any demo that supports translating one sentence once (or detailed pipeline, i.e., preprocess,forward and postprocess )? It seems that the repository only supports translating a source file one time (i.e., 'translate.py'), but it's not so convenient for one sentence only as I need first to write it into file and then run 'translate.py' (load model,build dataloader...), finally read results from translate.py.

**Comment by vince62s** [comment]
You can have a look here https://github.com/OpenNMT/OpenNMT-py/blob/master/eval_llm/MMLU/run_mmlu_opennmt.py

I will document this later but in a nutshell:

```
from onmt.inference_engine import InferenceEngine
engine = InferenceEngine(opt) # where opt defines the inference options
scores, preds = engine.infer_list(src) # where src is a list of sentence to translate / complete
engine.terminate()
```

**Comment by 13633491388** [comment]
Thank you. I will take a look

**Comment by 13633491388** [comment]
solved
