### ISSUE TITLE
Any plan to support "mps" backend?

### ISSUE THREAD

**Issue by everdark** [OpenNMT/OpenNMT-py#2474]
It's been quite a while that `pytorch` supports Apple silicon for MacBook to accelerate the computing.
The current `OpenNMT-py` code base still hard code the gpu backend to be `cuda`. Is there any plan to add support for `mps`? :)

I'm playing around with the [quickstart example](https://opennmt.net/OpenNMT-py/quickstart.html) and by replacing certain lines of code I manage to run the `onmt_train` script with MPS as the backend. The performance gain is around only 25% faster though.

**Comment by vince62s** [comment]
no plan for this, sorry.
