### ISSUE TITLE
[help] onmt.inputters.text_dataset

### ISSUE THREAD

**Issue by timon49** [OpenNMT/OpenNMT-py#2482]
How to fix this error ? 
I have tried many times to reinstall python3.8,3.9,3.10, did everything according to the instructions. Tried to install the onmt.inputters.text_dataset module separately - all without success!

**Comment by vince62s** [comment]
you are not giving the error

**Comment by timon49** [comment]
![1-29-09-2023 16_19_15](https://github.com/OpenNMT/OpenNMT-py/assets/40638391/30a23228-1b34-40d7-b5b6-a5c8e7c31256)

**Comment by vince62s** [comment]
not familiar with usage on Windows. But it seems you cloned and did not actually install the package. So maybe it is just a question of env variable like PYTHONPATH on linux.
May another windows user can help better.

**Comment by timon49** [comment]
Ubuntu20 - same error!
![23](https://github.com/OpenNMT/OpenNMT-py/assets/40638391/aa944706-2822-4165-ad3d-d4648977c740)

**Comment by vince62s** [comment]
did you install OpenNMT-py ?
if not show the PYTHONPATH variable by typing "echo $PYTHONPATH"
it needs to include the path to OpenNMT-py folder
