### ISSUE TITLE
The result of opennmt-py translate different from CTranslate2.Translator (beamsearch10)

### ISSUE THREAD

**Issue by medicine-wave** [OpenNMT/OpenNMT-py#2483]
I trained a model by opennmt-py, and evaluate the inference result by ```onmt_translate (beamsearch 10)```, the top-1 accuracy on my task achieved 55%

Then, I convert it into CTranslate2 Model by ```ct2-opennmt-py-converter --model_path  --output_dir ```, 
and evaluate the inference result by ```translator.translate_batch(input_tokens, beam_size = 10, num_hypotheses = 10, max_batch_size = 512)```, the top-1 accuracy on my task achieved 50%. 

Is it reasonable to expect excessive performance degradation?

**Comment by vince62s** [comment]
don't multi post your questions.
if someone does not answer on the forum then maybe they have other stuff to do / no time to answer rigth away.
