### ISSUE TITLE
OpenNMT confusion use of `Optim.updateLearningRate`: `valid_loss` used as `ppl` arg

### ISSUE THREAD

**Issue by EmbraceLife** [OpenNMT/OpenNMT-py#25]
In `train.py` [line 246](https://github.com/OpenNMT/OpenNMT-py/blob/master/train.py#L246), we have 

```
#  (3) update the learning rate
optim.updateLearningRate(valid_loss, epoch)
```

However, in `onmt/Optim.py`, inside function `updateLearningRate()` at [line 37](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Optim.py#L37), we have: 

```
def updateLearningRate(self, ppl, epoch):
...
    self.last_ppl = ppl
```

Why use `valid_loss` in the place of `ppl` for `updateLearningRate()`? 
Are `valid_loss` and `ppl` different measures?

Could anyone help me here, Thanks!

**Comment by bmccann** [comment]
Either should work since ppl is just an exponentiated loss: https://github.com/OpenNMT/OpenNMT-py/blob/6b4cb9d60eb662a736b09c69457375939cff5dc6/train.py#L241.
