### ISSUE TITLE
transforms: filtertoolong failed in translating

### ISSUE THREAD

**Issue by ares89** [OpenNMT/OpenNMT-py#2501]
https://github.com/OpenNMT/OpenNMT-py/blob/3aeba3ea4028d9d0c7216bd7f4520a41e3b89f4b/onmt/transforms/misc.py#L56

transforms: filtertoolong failed in translating, because of no tgt.

**Comment by vince62s** [comment]
Indeed this transform is supposed to be used only for training.
if you intend to use it for inference it requires a test.
Do you want to send a PR to fix this ?
