### ISSUE TITLE
bash: scripts/onmt/train.sh: No such file or directory

### ISSUE THREAD

**Issue by Armilius** [OpenNMT/OpenNMT-py#2502]
Thank you for sharing OpenNMT with us!
However, during reproducing the translation results on WMT17 en-de dataset following the guidline in [https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/examples/wmt17/Translation.md](url), i found an error when i ran this command:
`(OpenNMT) ubuntu@ubun:~/ubuntu/Translation/docs/source/examples$ bash scripts/onmt/train.sh`.
The terminal showed: 
`bash: scripts/onmt/train.sh: No such file or directory`.
I cannot find any file called `train.sh` in this project. Can you tell me how to solve this problem?

**Comment by PC91** [comment]
Hello @Armilius,
From what I understand, in `doc\source\examples\wmt17\Translation.md`, the 2 following lines are already good to run the training and to reproduce the translation results on WMT17 en-de dataset:

- To build the vocabulary: `python3 ../../../onmt/bin/build_vocab.py --config wmt17/wmt17_ende.yaml --n_sample -1`
- To run the training: `python3 ../../../onmt/bin/train.py --config wmt17/wmt17_ende.yaml`

About `train.sh`, this is a bash file and I think it is supposed to contain the 2 above command lines to automate the process. But you can either create this file or run the 2 commands one by one.

Hope that helps you.

**Comment by Armilius** [comment]
> Hello @Armilius, From what I understand, in `doc\source\examples\wmt17\Translation.md`, the 2 following lines are already good to run the training and to reproduce the translation results on WMT17 en-de dataset:
> 
> * To build the vocabulary: `python3 ../../../onmt/bin/build_vocab.py --config wmt17/wmt17_ende.yaml --n_sample -1`
> * To run the training: `python3 ../../../onmt/bin/train.py --config wmt17/wmt17_ende.yaml`
> 
> About `train.sh`, this is a bash file and I think it is supposed to contain the 2 above command lines to automate the process. But you can either create this file or run the 2 commands one by one.
> 
> Hope that helps you.

Thank you very much for your help. I have ran Transformer on WMT17 successfully!

**Comment by vince62s** [comment]
Guys can one of the two of you send a PR to correct the tuto? it's a stupid leftover from a copy/paste thing
thanks.

**Comment by PC91** [comment]
Ok I will have a check with other files too and open a PR.
