### ISSUE TITLE
Add support for "Training RNNs as fast as CNNs"

### ISSUE THREAD

**Issue by srush** [OpenNMT/OpenNMT-py#251]
@taolei87 just put out this nice paper that uses opennmt. Would be nice to support directly. 

- [ ] Support SRU as an option for RNN type
- [ ] Add documentation for how to install the SRU module from https://github.com/taolei87/sru

**Comment by JianyuZhan** [comment]
Awesome!  I am interested in the idea in this paper, would like to chew it over.  If I have time, I would also like to implement it.   Anyone interested in embodying it in OpenNMT-py also please go ahead :-)

**Comment by taolei87** [comment]
Thanks @srush @JianyuZhan ! 

The SRU implementation is the [single file](https://github.com/taolei87/sru/blob/master/cuda_functional.py#L422-L539) in my repo.

Unfortunately it doesn't support `PackedSequence` yet. Need to study how this is handled in pytorch source code and include it in `SRU`.

**Comment by srush** [comment]
okay, makes sense! @JianyuZhan adding one more data point to your Encoder design. 

- [ ] A simple RNN encoder that does not use packed sequence.

This will make it easier for others to experiment with new RNN designs.

**Comment by JianyuZhan** [comment]
Hello, @taolei87 . Interesting idea in that paper, I would like to chew it over first.  I misunderstood sursh at first,  since you have it already,  if you like, I would like to help it be incorporated into the project.

@srush, okay.  I will

**Comment by taolei87** [comment]
@JianyuZhan That would be awesome. Thank you!

It should work if we change `Encoder` and `StdRNNDecoder` to create an instance of SRU for `self.rnn`.

**Comment by taolei87** [comment]
In the future, I plan to try SRU combined with multi-head attention. From google's paper, attention already works well with FFN. I'm curious to see if there's an improvement when using RNN to capture more context.

**Comment by srush** [comment]
Cool pr is merged. To let us know if that's okay, looks like the PR  just includes the cuda code directly, not sure what the license is.

I will make another pr for an option to use multiheaded attention with rnn models. (We have all the code already).

**Comment by taolei87** [comment]
@srush @JianyuZhan Hi, thanks a lot for adding support for SRU. I'm busy recently and will test it once as soon as I can.

It may be worth to add SRU as a separate dependency in the future, since I'm planning to experiment a few variants and the code will be changed.
