### ISSUE TITLE
Support datasets with blank lines

### ISSUE THREAD

**Issue by mzeidhassan** [OpenNMT/OpenNMT-py#252]
Hi all,

I am using the translate command to translate a text file into Arabic using command:

`python translate.py -model demo-model_acc_71.72_ppl_3.20_e2.pt -src data/Preparing_To_Implement.txt -output Preparing_To_Implement_out.txt -replace_unk -verbose`

but I got the following error:

`RuntimeError: dimension 0 out of range of 0D tensor at d:\pytorch-master-1\torch\lib\th\generic/THTensor.c:24`

Here is the full error text, just in case.

> python translate.py -model demo-model_acc_71.72_ppl_3.20_e2.pt -src data/Preparing_To_Implement.txt -output data/Preparing_To_Implement_out.txt -replace_unk -verbose
Traceback (most recent call last):
  File "translate.py", line 176, in <module>
    main()
  File "translate.py", line 110, in main
    = translator.translate(srcBatch, tgtBatch)
  File "C:\Users\OpenNMT-py-master\onmt\Translator.py", line 249, in translate
    batch = dataset[0]
  File "C:\Users\OpenNMT-py-master\onmt\Dataset.py", line 107, in __getitem__
    dtype=self._type)
  File "C:\Users\OpenNMT-py-master\onmt\Dataset.py", line 55, in _batchify
    lengths = [x.size(0) for x in data]
  File "C:\Users\OpenNMT-py-master\onmt\Dataset.py", line 55, in <listcomp>
    lengths = [x.size(0) for x in data]
RuntimeError: dimension 0 out of range of 0D tensor at d:\downloads\pytorch-master-1\torch\lib\th\generic/THTensor.c:24

Can you please let me know how this can be fixed?

Thanks

**Comment by srush** [comment]
Do you have a blank line in your source file? I think this is the cause. We should throw a better error message.

**Comment by mzeidhassan** [comment]
Hi Alexander,

Thanks for getting back to me. The file to translate has some blank lines in it. Does this mean that I need to strip all blank lines from the file before I translate it.  Blank lines are useful sometimes for formatting. 

One more thing:
Is there a way to translate xliff files using OpenNMT? 

Thanks again for your support!

**Comment by srush** [comment]
Yeah, sorry about that. What behavior would you like? You want it to output a blank when it gets a blank in? 

No, unfortunately we don't support xliff.

**Comment by mzeidhassan** [comment]
Yes, I would like to retain all spaces, blank lines as the original. 

What about HTML files? Can OpenNMT translate HTML files and retain formatting? 

Thanks again for your support!

**Comment by srush** [comment]
We only handle single lines of a space separated inputs. Everything else
you do as pre- and post- processing.

**Comment by mzeidhassan** [comment]
@srush any guides or instructions on how to do this? Thanks in advance!

**Comment by srush** [comment]
Unfortunately this is low priority for us. Can you just write a script that puts the word "blank" in all those lines, and then removes the translation of "blank" on the output?

**Comment by mzeidhassan** [comment]
@srush Yes, I think this is a good idea. Thanks Alex!

**Comment by dadashkarimi** [comment]
you can add the following lines at onmt/io/TextDataset.py:


    ```
@staticmethod
    def read_text_file(path, truncate, side):
        """
        Args:
            path (str): location of a src or tgt file.
            truncate (int): maximum sequence length (0 for unlimited).
            side (str): "src" or "tgt".

        Yields:
            (word, features, nfeat) triples for each line.
        """
        with codecs.open(path, "r", "utf-8") as corpus_file:
            for i, line in enumerate(corpus_file):
                line = line.strip().split()
                if not line :
                    continue
```
