### ISSUE TITLE
AttributeError: 'NMTModel' object has no attribute 'named_parameters'

### ISSUE THREAD

**Issue by Karamya** [OpenNMT/OpenNMT-py#254]
I get the above error when training a dataset as given in the instructions

**Comment by JianyuZhan** [comment]
Could you post the whole backtrace, so we can locate the culprit code .

**Comment by Karamya** [comment]
Here is the full output, when I start the train using the command
python train.py -data data/demo -save_model demo-model -gpuid 0

`Loading data from 'data/demo'
 * vocabulary size. source = 50002; target = 50004
 * number of training sentences. 14007671
 * maximum batch size. 64
Building model...
NMTModel (
  (encoder): RNNEncoder (
    (embeddings): Embeddings (
      (make_embedding): Sequential (
        (emb_luts): Elementwise (
          (0): Embedding(50002, 500, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(500, 500, num_layers=2, dropout=0.3)
  )
  (decoder): InputFeedRNNDecoder (
    (embeddings): Embeddings (
      (make_embedding): Sequential (
        (emb_luts): Elementwise (
          (0): Embedding(50004, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout (p = 0.3)
    (rnn): StackedLSTM (
      (dropout): Dropout (p = 0.3)
      (layers): ModuleList (
        (0): LSTMCell(1000, 500)
        (1): LSTMCell(500, 500)
      )
    )
    (attn): GlobalAttention (
      (linear_in): Linear (500 -> 500)
      (linear_out): Linear (1000 -> 500)
      (sm): Softmax ()
      (tanh): Tanh ()
    )
  )
  (generator): Sequential (
    (0): Linear (500 -> 50004)
    (1): LogSoftmax ()
  )
)
Intializing params
* number of parameters: 84821004
Traceback (most recent call last):
  File "train.py", line 313, in <module>
    main()
  File "train.py", line 297, in main
    for name, param in model.named_parameters():
  File "/home/ramya/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 235, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'NMTModel' object has no attribute 'named_parameters'
`

**Comment by JianyuZhan** [comment]
It is weird that `named_parameters()`  is a method while reported as an `attribute`.  A google search told me that this may be due to the wrong indention of the `named_parameters()` in the pytorch code. See this example:
https://stackoverflow.com/questions/11685936/python-attributeerror-object-has-no-attribute

I didn't find the reported code in pytorch . Would you please update the pytorch and give it another try?

**Comment by Karamya** [comment]
Thanks, updating pytorch solved the problem.
