### ISSUE TITLE
Supported SentencePiece parameters 

### ISSUE THREAD

**Issue by PC91** [OpenNMT/OpenNMT-py#2546]
Hello,

I would like to use some SentencePiece parameters to construct the vocabulary set. In the current OpenNMT version, it seems that in the function call of `pyonmttok.SentencePieceLearner`, there are only a few common parameters. And other SP params in https://github.com/google/sentencepiece/blob/master/doc/options.md (such as `train_extremely_large_corpus`, `user_defined_symbols`,...) do not appear by default.
```python
learner = pyonmttok.SentencePieceLearner(
        vocab_size=symbols, character_coverage=0.98
)
```

I found a way to work around this issue, which is to use `pyonmttok.SentencePieceLearner` separately. For example,
```python
learner = pyonmttok.SentencePieceLearner(
    vocab_size=40000,
    model_type="bpe",
    shuffle_input_sentence=True,
    keep_vocab=True,
    user_defined_symbols="a,b,c,d,e,f",
    split_by_unicode_script=False,
    split_by_number=False,
    split_by_whitespace=True,
    split_digits=False,
    treat_whitespace_as_suffix=True,
    character_coverage=1.0,
)

learner.ingest_file("data.en")
learner.ingest_file("data.vi")
tokenizer = learner.learn("model/spm.model", verbose=True)
```

Is there a proper solution to use these SP parameters (`train_extremely_large_corpus`, `user_defined_symbols`,...) integrally in OpenNMT ?

Thank you very much.

**Comment by vince62s** [comment]
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/bin/build_vocab.py#L189-L198
just basic options obviously
you took the right approach to do it separately.
