### ISSUE TITLE
Speech to Text Toy Data Could Not Be Downloaded

### ISSUE THREAD

**Issue by Keram-Yasin** [OpenNMT/OpenNMT-py#2554]
I was evaluating the speech-to-text feature of OpenNMT with this getting started example: https://opennmt.net/OpenNMT-py/legacy/speech2text.html However, the toy training data could not be downloaded with this command given in the example:
`wget -O data/speech.tgz http://lstm.seas.harvard.edu/latex/speech.tgz;`

The response of the above command is:
 $ wget -O ./speech.tgz http://lstm.seas.harvard.edu/latex/speech.tgz;
--2024-01-20 11:45:53--  http://lstm.seas.harvard.edu/latex/speech.tgz
Resolving lstm.seas.harvard.edu (lstm.seas.harvard.edu)... 54.172.197.41
Connecting to lstm.seas.harvard.edu (lstm.seas.harvard.edu)|54.172.197.41|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://lstmvis.vizhub.ai/ [following]
--2024-01-20 11:45:57--  https://lstmvis.vizhub.ai/
Resolving lstmvis.vizhub.ai (lstmvis.vizhub.ai)... 169.63.55.253
Connecting to lstmvis.vizhub.ai (lstmvis.vizhub.ai)|169.63.55.253|:443... failed: Connection timed out.
Retrying.

--2024-01-20 11:48:10--  (try: 2)  https://lstmvis.vizhub.ai/
Connecting to lstmvis.vizhub.ai (lstmvis.vizhub.ai)|169.63.55.253|:443... failed: Connection timed out.
Retrying.

--2024-01-20 11:50:22--  (try: 3)  https://lstmvis.vizhub.ai/
Connecting to lstmvis.vizhub.ai (lstmvis.vizhub.ai)|169.63.55.253|:443...

**Comment by Keram-Yasin** [comment]
Now It worked.

**Comment by vince62s** [comment]
Just bear in mind we do not support speech since v2.Not sure what you want to do but maybe this is not the best toolkit to use for you.

**Comment by Keram-Yasin** [comment]
The Issue still exist. The command downloaded the html page of https://lstmvis.vizhub.ai/ as .tgz file. The file can not be extracted.

@vince62s I had no idea about that. I thought the OpenNMT-py is also good at translating speech-to-text. Any replacement for the absence since v2 from OpenNMT?

**Comment by vince62s** [comment]
for speech to text, search for "faster whisper"
