### ISSUE TITLE
Support for torch 2.2

### ISSUE THREAD

**Issue by jakeBass** [OpenNMT/OpenNMT-py#2560]
Pytorch 2.2 [was released on January 30th](https://github.com/pytorch/pytorch/releases/tag/v2.2.0). Currently, `OpenNMT-py` [does not support torch 2.2](https://github.com/OpenNMT/OpenNMT-py/blob/v3.4.3/setup.py#L24). 

Are there plans to support it? And what's the timeline for support? 

If it's actually compatible and all that's needed is an update to `setup.py`, I would hope that it could be released quickly.

Thanks!

**Comment by jakeBass** [comment]
Is this a change you could make?

**Comment by jakeBass** [comment]
Hi @vince62s, I just wanted to check back on this. Can you or another maintainer make this change?

It'd be great to be able to use both torch 2.2 and OpenNMT-py off the shelf. Thanks!

**Comment by vince62s** [comment]
v3.5.0 released

**Comment by jakeBass** [comment]
Thank you!
