### ISSUE TITLE
Rest Server issue: source text is sent but no translation is returned

### ISSUE THREAD

**Issue by mzeidhassan** [OpenNMT/OpenNMT-py#257]
Hi Alexander,

It took me a while to figure out how to run the Rest server and I used your Flask server http://github.com/OpenNMT/Server/

As you can see in the screen shot, it seems that the source text is sent, but no translation is returned either in the terminal or the web page. Any idea why?

I tested it first with source 'word', then the sentence "You can print all files directly.', but nothing is returned.

Here is a screen shot

https://www.dropbox.com/s/1b3k9a3nri6oj9w/opennmt.PNG?dl=0

Thanks in advance for your support.

Kind regards,
Mohamed

**Comment by srush** [comment]
Oh this is actually a server for the Lua Torch opennmt. We don't have one yet for this version of the codebase.

**Comment by srush** [comment]
Try https://github.com/OpenNMT/OpenNMT
