### ISSUE TITLE
Supported languages

### ISSUE THREAD

**Issue by Mayyarkmp** [OpenNMT/OpenNMT-py#2584]
I want to know which languages this model can translate, I looked around a lot and didn't find the answer, hope someone has the answer here

**Comment by ymoslem** [comment]
[OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py) is not a model. It is a framework to train machine translation models. If you are looking for pre-trained models, have a look at [these](https://huggingface.co/models?pipeline_tag=translation&sort=trending).
