### ISSUE TITLE
Turn the attention based seq2seq model into a vanilla seq2seq one

### ISSUE THREAD

**Issue by AngusGLChen** [OpenNMT/OpenNMT-py#259]
https://github.com/OpenNMT/OpenNMT-py/blob/0de9c039367b9f8ff3adf30f9e07196d1e2c6016/onmt/Models.py#L237

Can we slightly change the code (the input option -input_feed as well) to transform the attention based seq2seq model into a vanilla seq2seq one?

**Comment by JianyuZhan** [comment]
Will take a look at it.

**Comment by luffycodes** [comment]
Just wondering if opennmt supports training and testing without using attention ?@AngusGLChen : Please let me know if you were able to do it ?

Thanks !

**Comment by vince62s** [comment]
Closing this for now. If someone erally needs this, open a PR, should not be tough to implement.
