### ISSUE TITLE
use gpu 1 

### ISSUE THREAD

**Issue by prigioni** [OpenNMT/OpenNMT-py#2598]
<img width="999" alt="image" src="https://github.com/user-attachments/assets/2baa94f7-b917-408d-8f99-0a6d2679e8df">

use gpu 1
set:
world_size: 2
gpu_ranks: [1]
but, this is a problem
thanks

**Comment by prigioni** [comment]
<img width="1134" alt="image" src="https://github.com/user-attachments/assets/b214f43f-74d0-4901-bc5e-a70d316a64cf">

**Comment by prigioni** [comment]
export CUDA_VISIBLE_DEVICES=1,2,3

world_size: 1
gpu_ranks: [0]

it works

**Comment by vince62s** [comment]
FYI: https://forum.opennmt.net/t/opennmt-py-is-now-in-maintenance-mode-use-eole-instead/5792
