### ISSUE TITLE
Add tests for models that use features

### ISSUE THREAD

**Issue by bpopeters** [OpenNMT/OpenNMT-py#261]
PR #255 breaks completely on models that use features. This is obviously an undesirable situation, and it is one that we would be less likely to face in the future if we tested pull requests on a model that uses features. I have the data for such a model lying around and I would love to donate it to the cause.

In the meantime, I'm working on a small PR right now to fix the changes that have happened to `Embeddings.py` since the last time I touched it without breaking any of @JianyuZhan 's recent work refactoring the encoder and the decoder.

**Comment by JianyuZhan** [comment]
Oops, sorry! What behavior does it break?

**Comment by bpopeters** [comment]
Dimensions are mismatched in various places if there are any features at all. The exact nature of the problem varies slightly depending on which `-feat_merge` option is taken. The bug in the `mlp` case appears to have been present before PR #255 and I didn't notice because I never use that option for anything (I'm not actually sure what the justification is for it; I only maintain it because it was the only existing merging operation before I started working on it; I don't think it exists in the lua version).

Part of the problem was the `embedding_dim` attribute you defined for the `Embeddings`. That is the correct final size of the embeddings if there are no features, but in general it does not correspond to the output of the class. The `embedding_size` attribute that occurs farther down in the constructor is correct in all cases. I'm working on restoring it to `Models.py`, which will probably also make the various `_input_size` decorator-attributes unnecessary.

I have it basically fixed already, I just need to take one last look at it.

**Comment by JianyuZhan** [comment]
Oh, understood. Thanks! Just wonder why this problem doesn't surface prior to #255. I just looked at that change, it seems it doesn't alter the `embedding_dim` related behaviors? Maybe I missed some points.

**Comment by bpopeters** [comment]
Well, the input size of the encoder and decoder rnns used to be self.embedding_size. You created a new attribute called self.embedding_dim and used that instead, and they're not the same thing. The dimensions in the Embeddings module were (mostly) correct, it's how these were getting communicating to the outside world that got broken. It could have been one of the refactoring pull requests before, I pulled them all at about the same time.

I think my approach to refactoring the encoder is better for debugging this -- I'm having to hunt down several places in the code where newly-incorrect information about the size of the embeddings is used. I regret I won't have much time to work on it this week.

**Comment by srush** [comment]
Yeah, ideally we would have unit tests in the code, but in the meanwhile having pretrained models with features would be a great help.

**Comment by srush** [comment]
Although, maybe I'm wrong. Maybe we can just have like 50 very small models checked in, and make sure that don't get broken...
