### ISSUE TITLE
What is dynamic dictionary?

### ISSUE THREAD

**Issue by wuhaixutab** [OpenNMT/OpenNMT-py#265]
In the preproces_opts(), there is an option -dynamic_dict, what is dynamic dictionary?

**Comment by srush** [comment]
It creates a dictionary for each source sentence of all the words it uses. This allows the target to "copy" source words that may not be in the target dictionary

**Comment by wuhaixutab** [comment]
Thank you! So, why the performance improves when I add -dynamic_dict on the basis of -share_vocab? In other words, is -dynamic_dict redundent after sharing the vocabularies?

**Comment by wuhaixutab** [comment]
Experiment shows -dynamic_dict is not redundent after sharing the vocabularies, why?

**Comment by srush** [comment]
The two options should be orthogonal. Share vocab just aligns the two dictionaries so they have the same numbering. This is needed if you want to share source and target embeddings.

**Comment by aj7tesh** [comment]
Can any one give more elaborate answer on what is the use of dynamic_dict and when to use it or share vocab ?

**Comment by aj7tesh** [comment]
@srush @ghost

**Comment by thethiny** [comment]
I believe, as in GPT-2, it is to clone a word from input into output.
Example "The man did this" is in the vocab. But "Arx514sa on Reddit did this" is not in the dictionary, so it will copy Arx514sa as is, and output it. I may be wrong so correct me if I am.
