### ISSUE TITLE
How to use a different MT dataset like WMT'15

### ISSUE THREAD

**Issue by loretoparisi** [OpenNMT/OpenNMT-py#27]
Tensorflow tutorial Seq2Seq is using the [WMT 2015 datasets](http://www.statmt.org/wmt15/translation-task.html) Following the step by step guide in the OpenNMT readme, will it work switching to those new datasets like one of parallel corpus there?

Thanks.

**Comment by bmccann** [comment]
You'll have to download that data and do any kind of preprocessing required, but as long as you get it into the right format, OpenNMT-py should work. I'm planning on adding IWSLT and WMT tutorials some time soon as I have successfully used OpenNMT-py to train good models for both on the de-en pair.

**Comment by loretoparisi** [comment]
@bmccann thanks that would be awesome! I agree to reach a good accuracy before implementing new parallel corpus. Regarding this and considering this WMT task, which bidirectional RNN is implemented among the ones depicted here?

<img width="899" alt="schermata 2017-04-04 alle 12 11 05" src="https://cloud.githubusercontent.com/assets/163333/24651893/cf6de150-192f-11e7-8819-59dcfa0cd134.png">


Thanks a lot!

**Comment by loretoparisi** [comment]
@bmccann Just adding here another Parallel Corpus to support: http://www.statmt.org/europarl/
