### ISSUE TITLE
Quickstart typo

### ISSUE THREAD

**Issue by urialon** [OpenNMT/OpenNMT-py#274]
Hi,
The [quickstart](http://opennmt.net/OpenNMT-py/quickstart/) training command line is:
`python train.py -data data/demo`**.train.pt**`  -save_model demo-model `

but it should be:
`python train.py -data data/demo -save_model demo-model `
(without ".train.pt", the code seems to concatenate this suffix by itself)

Thanks

**Comment by JianyuZhan** [comment]
Good catch. Thanks for reporting. It was fixed in f5ae3e8a,  please update your code :-)
