### ISSUE TITLE
Feature: ensemble decoding or averaging different models 

### ISSUE THREAD

**Issue by surawinfo** [OpenNMT/OpenNMT-py#275]

**Comment by srush** [comment]
Yes, we will add this. Probably in the medium term though.

**Comment by srush** [comment]
Rough plan for this if anyone wants to work on it:

[] - Implement a special `DecoderState` that is really a list of n-decoder states. 
[] - Implement a mock decoder that takes this state and pass it to n-different decoders and sums 
[] - Implement a mock generator that takes in n states and sums the scores. 
[] - Implement an code to read in n-models and ensemble them this way.

**Comment by vince62s** [comment]
Averaging is available in tools.
Ensembling is on its way, PR #732
