### ISSUE TITLE
hidden state shapes returned by SRU and LSTM are not consistent

### ISSUE THREAD

**Issue by jingxil** [OpenNMT/OpenNMT-py#277]
The hidden state returned by LSTM has the shape [layers\*directions x batch x dim], while the one returned by SRU has the shape [layers, batch, dim\*directions]. Current version seems to ignore this inconsistency. I think possible solution could be A) modify the shape of hidden state returned by SRU  or  B) make a special case for SRU in `init_decoder_state` function.

**Comment by jingxil** [comment]
I suggest to override `init_decoder_state` function in `SRURNNDecoder` which is inherited from `StdRNNDecoder`. If this solution sounds all right, I would like to propose a PR.

**Comment by JianyuZhan** [comment]
This approach is better, please also refer to `TransformerDecoderState` and `CNNDecoderState` as well,  to make their interface consistent.
