### ISSUE TITLE
MultiGPU issues

### ISSUE THREAD

**Issue by dasguptar** [OpenNMT/OpenNMT-py#28]
Hi,
This might be already known to you guys (since the README does mention at the end that multi-GPU is not supported), but I encountered this just now so thought I might give a heads up!
The code is supposed to support multiGPU via `nn.DataParallel`, however, it is breaking due to usage of `nn.utils.pack_padded_sequence` in the encoder. Basically, when the input data of padded sequences is sent to a `DataParallel`, it is split along the batch dimension, but the list containing the lengths is not split, resulting in a size mismatch error as follows:
```
File "/somepath/torch/nn/parallel/parallel_apply.py", line 45, in parallel_apply
    raise output
ValueError: lengths array has incorrect size
```
If the input was a tuple of a `B*L*D` Variable and a `B` length list of lengths, where `B` is the batchsize, `L` is the padded length, and `D` is the feature size, the `nn.DataParallel` scatters the `B*L*D` into `B/K*L*D`, where `K` is the number of GPUs, while the `B` length list is shallow copied. This causes `nn.utils.pack_padded_sequence` to raise an error.

**Comment by guillaumekln** [comment]
Thanks for the description. It should be fixed on master now.
