### ISSUE TITLE
Blank lines in preprocess.

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT-py#284]
EDIT: maybe just the fact that target shouldn't have case feature in the py version ....

Hi,
I took a dataset tokenized (with case feature) by the Lua version.

I got this error:
Preparing training ...
Building Training...
Traceback (most recent call last):
  File "preprocess.py", line 78, in <module>
    main()
  File "preprocess.py", line 60, in main
    train = onmt.IO.ONMTDataset(opt.train_src, opt.train_tgt, fields, opt)
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/IO.py", line 132, in __init__
    src_data = self._read_corpus_file(src_path, src_truncate)
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/IO.py", line 203, in _read_corpus_file
    return [extract_features(line) for line in lines]
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/IO.py", line 35, in extract_features
    token_size = len(split_tokens[0])
IndexError: list index out of range

is it the number of token in a line or the number of lines the culprit ?

**Comment by srush** [comment]
@bpopeters think you were looking at this at one point. Any ideas?

**Comment by vince62s** [comment]
Actually I did it again with datasets that have no features and I get the exact same error.

**Comment by vince62s** [comment]
yes like in most public datasets ....
I think we need to allow this.

**Comment by srush** [comment]
Okay, let's do it 

Matches this one too https://github.com/OpenNMT/OpenNMT-py/issues/252
