### ISSUE TITLE
Change loading behavior of models

### ISSUE THREAD

**Issue by srush** [OpenNMT/OpenNMT-py#288]
@bpopeters  @JianyuZhan let me know what you think of this. 

Instead of reloading models with opts, we should just save all the extra params and stuff in the state dict. It is silly that when we change an Opt, it breaks old models.

**Comment by srush** [comment]
So we basically wouldn't re __init__ all the classes at test time.

**Comment by JianyuZhan** [comment]
Yeah, I realized this point during the `Trainer` work, so for the `train_from` logic,  I use `model_opt` to build the model(`model_opt` is from checkpoint),  the the current environment `opt` only has effect in the gpu behavior(i.e.,  we can resume training using gpu, while the previous one didn't,  vice versa).  See :https://github.com/OpenNMT/OpenNMT-py/blob/master/train.py#L214.

I do the same for the optimizer work too, I think I need to add some explanation to help users get aware of this fact.

**Comment by srush** [comment]
Yeah I can't decide what is best here. I am leaning towards not saving model opt at all, and just have internal modules save their config.

**Comment by JianyuZhan** [comment]
Could do so, but we need to be careful with the gpu behavior.

We now actually have the correct semantics with saving the `NMTModel` and `load_state_dict()` in resume phase, I think we can be aggressive to just reuse the saved model(not rebuild the model from scratch using old `model_opt`). Would like to give it a try.
