### ISSUE TITLE
Strange decoding mask in _get_attn_subsequent_mask of Transformer

### ISSUE THREAD

**Issue by zhangxiangnick** [OpenNMT/OpenNMT-py#294]
[_get_attn_subsequent_mask](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/Transformer.py#L170) generates the decoding mask to avoid attentions on subsequent positions. However this mask seems strange to me.

For example, `self._get_attn_subsequent_mask(4)` generates a mask of 1x4x4:

### Expected
     [[[0, 1, 1, 1],
        [0, 0, 1, 1],
        [0, 0, 0, 1],
        [0, 0, 0, 0]]]

### Actual Behavior
     [[[0, 1, 1, 1],
        [0, 1, 1, 1],
        [0, 1, 1, 1],
        [0, 1, 1, 1]]]

**Comment by srush** [comment]
Oh that does look worrisome, something must have broken it. Would you by any chance be able to make a test and send us an PR?

**Comment by zhangxiangnick** [comment]
Never mind. I find this is only for my old numpy version. After upgrading numpy to 0.13.1 the behavior is correct. Close this.
