### ISSUE TITLE
Mask for attention

### ISSUE THREAD

**Issue by Chanrom** [OpenNMT/OpenNMT-py#30]
I wonder why we didn't apply mask in GlobalAttention since we paded zeros on the right. I find there actually have a `applyMask` function but not used.
Thank you.

**Comment by pcyin** [comment]
I believe this is an issue but is acceptable. Since examples are sorted by the length of the source sentence, during training the length of all source sentences within a batch should be the same for most of the time. Also note that `applyMask` is indeed used in decoding.
