### ISSUE TITLE
Cuda memory error during training

### ISSUE THREAD

**Issue by antspy** [OpenNMT/OpenNMT-py#301]
Hello, 

I have downloaded the openNMT integration testing dataset; https://github.com/OpenNMT/IntegrationTesting/tree/master/data

I then run a model with rnn_size = 1000, batch_size = 256, and layers=2. 
The model runs for one epoch, and after the end of the first epoch a "Cuda runtime error" is raised:

`RuntimeError: cuda runtime error (2) : out of memory at /py/conda-bld/pytorch_1493681908901/work/torch/lib/THC/generic/THCStorage.cu:66
`
I am running on a GPU with 12 GB of memory. During the training of the first epoch, it occupies about 7GB of GPU memory. It could be that the model is duplicated somewhere, causing it to request more than the 12 GB that are available. 

Do you know where the problem could be?

**Edit**

Interestingly, if I change the batch size to 128, it does not crash after one epoch, and it was able to finish training in 50 epochs. Memory usage, though, went from 7 GB during the first epoch to 9.5 GB after that.

**Comment by JianyuZhan** [comment]
Could you post the whole command line for me to try reproducing?

**Comment by antspy** [comment]
@JianyuZhan Hi, I am using onmt as a library, so I don't call it from command line. But I used those options to train it, and it crashed. With batch_size of 128, though, I am able to finish training (with a resulting perplexity of 102 though :/)

**Comment by mbforbes** [comment]
I am also having this issue.

It looks like it crashes trying to compute the perplexity on the validation set:

```
...
Epoch  1, 15400/15625; acc:  31.77; ppl:  35.95; 1678 src tok/s; 3401 tgt tok/s;  45393 s elapsed
Epoch  1, 15450/15625; acc:  31.46; ppl:  36.97; 1766 src tok/s; 3395 tgt tok/s;  45542 s elapsed
Epoch  1, 15500/15625; acc:  31.73; ppl:  36.06; 1654 src tok/s; 3287 tgt tok/s;  45689 s elapsed
Epoch  1, 15550/15625; acc:  31.54; ppl:  36.67; 1887 src tok/s; 3704 tgt tok/s;  45829 s elapsed
Epoch  1, 15600/15625; acc:  31.85; ppl:  35.99; 1808 src tok/s; 3615 tgt tok/s;  45961 s elapsed
Train perplexity: 52.6252
Train accuracy: 28.6506
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 347, in <module>
    main()
  File "train.py", line 343, in main
    train_model(model, train_dataset, valid_dataset, fields, optim, model_opt)
  File "train.py", line 173, in train_model
    valid_stats = trainer.validate()
  File "/home/max/repos/OpenNMT-py/onmt/Trainer.py", line 200, in validate
    batch, outputs, attns)
  File "/home/max/repos/OpenNMT-py/onmt/Loss.py", line 83, in monolithic_compute_loss
    _, batch_stats = self._compute_loss(batch, **shard_state)
  File "/home/max/repos/OpenNMT-py/onmt/Loss.py", line 183, in _compute_loss
    scores = self.generator(self._bottle(output))
  File "/home/max/.pyenv/versions/opennmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/max/.pyenv/versions/opennmt/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/max/.pyenv/versions/opennmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/max/.pyenv/versions/opennmt/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 720, in forward
    return F.log_softmax(input)
  File "/home/max/.pyenv/versions/opennmt/lib/python3.6/site-packages/torch/nn/functional.py", line 537, in log_softmax
    return _functions.thnn.LogSoftmax.apply(input)
  File "/home/max/.pyenv/versions/opennmt/lib/python3.6/site-packages/torch/nn/_functions/thnn/auto.py", line 174, in forward
    getattr(ctx._backend, update_output.name)(ctx._backend.library_state, input, output, *args)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:66
```

Here's how I ran from the command line (with `[dataset]` substituded for the specifics I used):

```
python train.py \
  -data data/[dataset] \
  -save_model [dataset] \
  -gpuid 1 \
  -pre_word_vecs_enc data/[dataset].glove.enc.pt \
  -pre_word_vecs_dec data/[dataset].glove.dec.pt \
  -epochs 20 \
  -word_vec_size 300 \
  -share_embeddings
```

This is a bummer because after almost 13 hours of training, it crashes and no model is saved :-( 

Many thanks for any insights / help!

**Comment by srush** [comment]
We'll look into it. Maybe we should have it run a round of validation first just to avoid any possibility of crashing after one epoch.

**Comment by helson73** [comment]
@antspy @mbforbes 
#476 this may help.

**Comment by mbforbes** [comment]
https://github.com/OpenNMT/OpenNMT-py/pull/481 seems to alleviate the issue for me (on a smaller test run) — thanks!

**Comment by abaheti95** [comment]
Hi all,
For me the model throws memory error in between training after certain time. I have a small dataset with large vocabulary. Following are the exact sizes of the data
 * number of train sentences: 2269605
 * number of valid sentences: 283548
 * maximum batch size: 256
 * vocabulary size. source = 44387; target = 44387
and I use the following parameters while training
`-encoder_type brnn -param_init 0.08 -batch_size 256 -learning_rate 0.1 -optim adadelta -max_grad_norm 1 -word_vec_size 300 -layers 4 -rnn_size 300 -epochs 10 -copy_attn`
I had tried with word_vec_size 500 and rnn_size 500 and then my training stopped at 150th batch in the 1st epoch. While with the 300 configuration it stopped at the 3rd epoch 
```
...
Epoch  3,  6200/ 8866; acc:  33.16; ppl:  68.86; 4075 src tok/s; 5121 tgt tok/s;   2942 s elapsed
Epoch  3,  6250/ 8866; acc:  33.20; ppl:  68.07; 4053 src tok/s; 5079 tgt tok/s;   2966 s elapsed
Epoch  3,  6300/ 8866; acc:  33.21; ppl:  67.80; 4139 src tok/s; 5115 tgt tok/s;   2989 s elapsed
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
```

Does the model allocate more memory after every epoch? Even if that is the case why did it stop the training in between an epoch? BTW my gpu memory is 12GB and I have successfully finished training for vocabulary size of 24k and vector size 1000 for the same code.

**Comment by sebastianGehrmann** [comment]
Hey @abaheti95 - I have seen this issue happen when I accidentally started a second job or process that allocated VRAM. Could that have happened to you?

A second reason could be that you squeeze your VRAM very tightly (>95% used) and then a slightly longer batch comes along that makes it go over 100%. If that is the case, the issue should never occur with a slightly smaller batch size of ~230-240?

**Comment by abaheti95** [comment]
@sebastianGehrmann - Thank you for the suggestion. Turns out you are right! 3 processes were killed due to memory error. I have halved my batch size and restarted the processes.
