### ISSUE TITLE
Add possibility to use config files

### ISSUE THREAD

**Issue by maxdel** [OpenNMT/OpenNMT-py#308]
We should allow {preprocess,train,translate}.py files to take options from configs.

**Comment by JianyuZhan** [comment]
Well, we would support `-save-config` and `-config` like the lua verion later, but I thought it is not a high priority thus it gets pending on my todo list.  I will promote it a bit .

**Comment by srush** [comment]
Yeah, I think this is a good idea. Possibly a nice user contribution if you have time. 

I would like not to do this ourselves, possibly use something like ConfigArgParse 
https://pypi.python.org/pypi/ConfigArgParse

**Comment by jerinphilip** [comment]
Hey, I'd like to try - can we discuss what all is required to be parametrized and passed inside to the functions?

**Comment by JianyuZhan** [comment]
Hi, @jerinphilip ,  

The three driver `preprocess.py`, 'train.py` and `translate.py` takes lots of command line options, see the `opts.py` source file for a overview.

Basically we want the same as the lua verion: 

- a `-save_config` option to save the current option to a file.
- a `-config` option to use a pre-saved config file.

You can refer to lua's implementation: https://github.com/OpenNMT/OpenNMT/blob/master/onmt/utils/ExtendedCmdLine.lua#L54

And you can leverage the ConfigArgParse as sruch recommended for most work I think.

**Comment by srush** [comment]
Thanks @jerinphilip. I think @JianyuZhan gives the idea. 

I think that ConfigArgParse is MIT licensed. So maybe the best thing to do is just include that file directly in our codebase.

**Comment by jerinphilip** [comment]
Is [this](https://ptpb.pw/DQmK/diff) along the lines of what is required? Rough summary of the above diff is:

- create a `config_opts` similar to `model_opts` in `opts.py`, with both `-save_config` and `-config` and reuse it across `{preprocess,train,translate}.py`

Haven't tested any of this yet, will do that and finishing touches and send in a PR, following a review.

**Comment by jerinphilip** [comment]
@JianyuZhan you seem to be working on something - I had a rough thing tested and ready today but found major conflicts. Where do I proceed now?

This is how I did it: https://github.com/jerinphilip/OpenNMT-py/commit/cc642a5f1758e45cdeca63ac913d9c24ee30eec9

**Comment by JianyuZhan** [comment]
@jerinphilip, please update the latest master branch, and then on your development branch,  `git rebase` to master branch, fix the errors as indicated, and `git push` again,  the pull request will update the code.

Then we can review and give feedback. Thanks for your work!

**Comment by JianyuZhan** [comment]
And I found your PR has some errors to be fixed, you can run `test/pull_request_chk.sh` and fix any errors before you push again.
