### ISSUE TITLE
Bug in translate.py with -tgt argument when using model with -copy_attn

### ISSUE THREAD

**Issue by sebastianGehrmann** [OpenNMT/OpenNMT-py#310]
I just noticed that when trying to decode from a model trained with copy attention, it blows up here: 

https://github.com/OpenNMT/OpenNMT-py/blob/819448dd470e398ad84e64b3d66030c84691b4ac/onmt/Translator.py#L81-L83

The generator without copy is initialized as a simple `nn.sequential` here:

https://github.com/OpenNMT/OpenNMT-py/blob/819448dd470e398ad84e64b3d66030c84691b4ac/onmt/ModelConstructor.py#L149-L157

However, this makes the forward signature different from the `CopyGenerator` one: 

https://github.com/OpenNMT/OpenNMT-py/blob/819448dd470e398ad84e64b3d66030c84691b4ac/onmt/modules/CopyGenerator.py#L22

Should we fix this by adding a copy attention option to `translate.py` that changes the call or should we change the generator to have the same signature?

**Comment by srush** [comment]
Oh I think this was fixed. Someone must have changed it. I'll look into the history.

**Comment by srush** [comment]
Can you check what it looks like in falcon's torchtext branch? Think it is special cased for copy.
