### ISSUE TITLE
technical problem 

### ISSUE THREAD

**Issue by sondos90** [OpenNMT/OpenNMT-py#311]
hi every one
at step 3: at command :python translate.py -model demo-model_epochX_PPL.pt -src data/src-test.txt -output pred.txt -replace_unk -verbose

why it keeps telling me that "IOError: [Errno 2] No such file or directory: 'demo-model_epochX_PPL.pt'
"
what does that mean ?
plz advise me thx

**Comment by srush** [comment]
oh, sorry, that is poor documentation. You should put in the file name that the model produced. You'll see a file output every epoch in the directory.
