### ISSUE TITLE
possible future issue with vocab sizes in share_vocab option

### ISSUE THREAD

**Issue by Henry-E** [OpenNMT/OpenNMT-py#312]
https://github.com/OpenNMT/OpenNMT-py/blob/a8b280dc8fad5e91154141e7551d4fd9a51a3a1d/onmt/IO.py#L353-L358

Just noting this could be an issue if the target vocab size is ever bigger than the source vocab size. But fortunately it works fine for now because the default value for `opt.src_vocab_size` is 50,000

**Comment by srush** [comment]
Ah good point. Maybe we should just make this more clear in the debug logs of preprocess.
