### ISSUE TITLE
Translation quality worsen with big batch size

### ISSUE THREAD

**Issue by antspy** [OpenNMT/OpenNMT-py#318]
Hi, 

When translating long texts, you want to increase batch size. If you do, the sentences will be padded with trailing dots to the length of the longest sentence in the batch. The bigger the batch size, the more trailing dots there are.  This completely destroy the translation quality for many sentences :/ 

For example, with batch size 256, I get 9 BLEU. With batch size 32, I got 24 BLEU on the same dataset and with the same model.

**Comment by srush** [comment]
Yes, this is a known bug. We have been slow to fix. I will prioritize it. 

In the mean time, please use batch_size 1 for translation.

**Comment by srush** [comment]
Should be fixed now.
