### ISSUE TITLE
batchify in class Dataset ignores last batch in input

### ISSUE THREAD

**Issue by amrsharaf** [OpenNMT/OpenNMT-py#32]
I have a training dataset with 1950 sentences, when I set the batch size to 64, and create a new dataset instance, I observed that the created dataset has only 30 batches, rather than 31, by inspection, I found out that the last 30 sentences has been ignored. The correct behavior will be to create 31 batches rather than 30, and the size of the last batch will be smaller than 64, but that should be fine!

**Comment by guillaumekln** [comment]
If you update to latest, this should be fixed.
