### ISSUE TITLE
If -tgt_seq_length is not set, preprocess will create empty dictionary, train will crash.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [OpenNMT/OpenNMT-py#320]
If -tgt_seq_length is not set, and the target sentences are >50 words long in general, preprocess.py will create empty output, and train.py will crash.

preprocess.py should refuse to create output with empty dictionary, and should print the number of lines that were removed.

**Comment by srush** [comment]
Agreed. We should print much nicer logs for preprocess. Once https://github.com/OpenNMT/OpenNMT-py/pull/300 is checked in, we would love a PR.
