### ISSUE TITLE
Embedding dropout

### ISSUE THREAD

**Issue by mataney** [OpenNMT/OpenNMT-py#321]
Hey guys, awesome work!
Easily one of the best projects in PyTorch.

When creating a new Embedding object we pass dropout probability but it looks like we don't use it (except for the `PositionalEncoding`)
Is this a mistake? should I create a PR for this or am I missing something?

Cheers.

**Comment by srush** [comment]
Thanks. We still have a lot of work to do, but it is getting there.

Oh yeah, so most models don't use drop-out on embeddings. It just so happened that transformer uses it and position encoding, so they got commingled. If you want maybe you can add another option "-embedding_dropout"  that controls that parameter?

**Comment by vince62s** [comment]
I think it would be clearer, if you do so.
Similarly, you may find useful to specify attention_dropout for the droout value of the mulithead attention.
Otherwise you use the same value.
Also, even when you use dropout=0 you define a nn.dropout layer which not very usefull.
Might be good to make it conditional to save memory.

**Comment by srush** [comment]
Good idea for separate `attention_dropout` will add. 

PyTorch now defines dropout as just a function, so it shouldn't take any mem. We include it there mostly as documentation and for backwards compat.

**Comment by vince62s** [comment]
If the dropout function brings memory saving and maybe also SPEED, it could be good to move to this even though it breaks backward compat.

**Comment by srush** [comment]
So we can skip the *using* unit without breaking backwards compat. Are there transformer models where you want to use 0 dropout though? I don't want to prematurely optimize, this is at most a 5% type of speedup.

**Comment by vince62s** [comment]
oh no, we need dropout, but I understood they changed from "dropout layer" to a function thinking adding a layer would be significantly slower (there are 3 dropouts) but if only 5% gain don't worry.
