### ISSUE TITLE
AttributeError: 'DataParallel' object has no attribute 'generator'

### ISSUE THREAD

**Issue by mataney** [OpenNMT/OpenNMT-py#323]
Hey guys, it looks like the model having problem when passing more than one gpu id.
It crashes after trying to fetch the model's generator, as the `DataParallel` object doesn't have one (It only has the `module` object)
It looks like this breaks training not only in this specific line.

Any advice?
(In order to reproduce the problem I'm facing just pass `-guid 0 1`)

**Comment by KelleyYin** [comment]
how to solve this question?

**Comment by XiangZhu0718** [comment]
the same problem...

**Comment by JianyuZhan** [comment]
Could you post the trackback ? Is it the newest code?

**Comment by srush** [comment]
Yeah. Sorry, multigpu is actually not supported at the moment. We are waiting on some work from the pytorch team. Currently even if you get it to run, it is not much faster.
