### ISSUE TITLE
What does init_decoder_state do?

### ISSUE THREAD

**Issue by ijauregiCMCRC** [OpenNMT/OpenNMT-py#325]
Hi!

I am trying to understand the code of the NMT model.  More precisely, I am trying to understand what the **init_decoder_state** method does after the encoder.  Does it initialize the decoder's hidden parameters with the same values as the encoder? I am new in the topic of NMT, but my understanding is that the parameters of the encoder and the decoder are different, so the answer to the previous question would be no in my opinion. However, I look to the code and it seems it is doing that. I would appreciate if someone could briefly clarify what's going on there.
Thanks,

**Comment by sriniiyer** [comment]
Not the parameters, but the initial hidden state of the decoder i.e. the previous state (h_0) that is input to the first RNN module of the decoder, which is normally set to be the hidden state of the last encoder RNN module.

**Comment by srush** [comment]
Good answer.
