### ISSUE TITLE
How to add "bridge" option like torch version of OpenNMT?

### ISSUE THREAD

**Issue by weilheim** [OpenNMT/OpenNMT-py#326]
I would like to forward the encoder states through a dense layer and use the output of the dense layer as the initial decoder state.  This is done by specify an option called "bridge" in the torch version of OpenNMT.
Does anyone have ideas about how to implement this in the framework of OpenNMT-py? 
I know I have to modify the source code, but I don't know how.
Thanks!

**Comment by srush** [comment]
Hey there. Great question!

We don't have this yet, but it should be easy to add.

Can you remind me again how the bridge is used? It's an extra layer after the attention? 

First off, add a new "bridge" module to this directory: https://github.com/OpenNMT/OpenNMT-py/tree/master/onmt/modules . It should be a standard torch module. 

Then you can modify the decoder to call the bridge layer after attention. for instance here https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L254

**Comment by srush** [comment]
@JianyuZhan you might consider adding this with the attention refactor.

**Comment by weilheim** [comment]
@srush It's not an extra layer after the attention. 
The bridge is used to initialize the hidden state of the decoder. 
RNN decoder accepts at least 2 arguments: the hidden state of the previous time step and the current input. What is the hidden state of the previous time step when you want the decoder to generate the first word (the first time step)? Of course the initial hidden state could be initialize to zero or simply copy the encoder hidden state but this hurts the performance. The bridge is used to create the decoder hidden state when it has just been created and nothing has been forward through. 
You could reference the following link: http://opennmt.net/OpenNMT/training/models/#bridges

**Comment by weilheim** [comment]
@srush @JianyuZhan OpenNMT-py initialize the decoder hidden state using the following piece of code.
https://github.com/OpenNMT/OpenNMT-py/blob/771b741163bf343365b2641fc361cc27056fefb0/onmt/Models.py#L190-L206
Basically, it just copies (with some operations to make sure that the dimension between encoder state and decoder state matches) the encoder state. It will be great if some more complicated operation could be done (like forward the encoder states through a dense layer). I have tested on other tasks (image captioning) that this could improve the performance (not much, but it does improve the performance).

**Comment by srush** [comment]
Oh I see. So `self._fix_enc_hidden(enc_hidden)` returns the last layer from the encoder. You could literally just add a `nn.Linear` and a `nn.TanH` around that to implement the bridge.

**Comment by srush** [comment]
We just added this. Option is -bridge
