### ISSUE TITLE
report_stats is being reset after every batch (ignoring report_every)

### ISSUE THREAD

**Issue by sriniiyer** [OpenNMT/OpenNMT-py#331]
After every batch, report_stats = Statistics() is executed in Trainer.py, so its not aggregating the stats anymore. That line should be moved into report_func or something.

**Comment by srush** [comment]
@JianyuZhan can you check this.

**Comment by JianyuZhan** [comment]
I checked the old code and it is the old behavior:

```
          if i % opt.report_every == -1 % opt.report_every:
                report_stats.output(epoch, i+1, len(train),
                                    total_stats.start_time)
                if opt.exp_host:
                    report_stats.log("progress", experiment, optim)
                report_stats = onmt.Loss.Statistics()
```

It seems we did want to log a new stats data for every report, not aggregating them.

Yes, it is weird, is it this on purpose?

**Comment by sriniiyer** [comment]
The old code has report_stats = onmt.Loss.Statistics() inside the if condition. The new code has it outside.

**Comment by JianyuZhan** [comment]
Oh, right. I misunderstood what you mean by "aggregate" - it is aggregating every report, the new code doesn't.  I will fix it.
