### ISSUE TITLE
Calling an external validation script and printing example translations during training

### ISSUE THREAD

**Issue by Henry-E** [OpenNMT/OpenNMT-py#336]
This is just a nice to have kind of thing that I'm mentioning. It was available in [Nematus](https://github.com/EdinburghNLP/nematus). Rather than waiting till the end it allowed the option to call an external validation script at the end of every Epoch or set number of batches. Similarly it would print out sample translations during training which was useful as well.

**Comment by vince62s** [comment]
discussed in #813
