### ISSUE TITLE
#layers for encoder equals #layers for decoder

### ISSUE THREAD

**Issue by LMescheder** [OpenNMT/OpenNMT-py#341]
I just noticed that for the default RNN encoder, the `enc_layers` parameter is ignored and the number of layers of the encoder is equal to the number of layers of the decoder (see [this line](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/ModelConstructor.py#L70)).

Is there some reasoning behind this or is it an error?

**Comment by JianyuZhan** [comment]
Oops, I believe this is a bug, due to typo or somehow, it is written as `dec_layers`.  Thanks for reporting.

Maybe in most cases people just set it the same as `dec_layers`, so it hasn't been noticed. Will fix it.
