### ISSUE TITLE
Options for embedding dimensions are a little off

### ISSUE THREAD

**Issue by bpopeters** [OpenNMT/OpenNMT-py#344]
In #267, I changed around the logic for figuring out feature embedding sizes so that it was possible to manually specify the embedding sizes when using `-feat_merge concat`. I think, though, that I should have done it a different way. In the lua version, you can manually specify all embeddings sizes with `-src_word_vec_size` and `-tgt_word_vec_size`, which can each take arbitrarily many integers, not just one, and the logic for whether to determine the feature sizes with an exponent or a fixed size was the same as it was in OpenNMT-py prior to #267. I propose to update the options so they're in line with what's in lua. This has two benefits over the status quo:

1. It brings OpenNMT-py's options closer to OpenNMT-lua's.
2. It allows a user to specify different dimensions for different layers of features. The current options in OpenNMT-py offer no way to do this.

**Comment by vince62s** [comment]
@bpopeters  was this ever implemented ?

**Comment by bpopeters** [comment]
@vince62s Yes, but it never merged because it failed some tests and I was too busy with other stuff to look into it. It probably wouldn't take more than a couple minutes to fix it.

**Comment by noe** [comment]
@bpopeters @vince62s are there any plans to continue with this?
