### ISSUE TITLE
Different attention-networks

### ISSUE THREAD

**Issue by ijauregiCMCRC** [OpenNMT/OpenNMT-py#357]
Hi!

In the [OpenNMT paper](https://pdfs.semanticscholar.org/2e52/8fefe8b547cce65e318818c00d774760d8c8.pdf?_ga=2.97834717.33726117.1508817321-315157909.1508392513) it is said:

> Attention Networks The use of
attention over the encoder at each step of translation
is crucial for the model to perform well. The
default method is to utilize the global attention
mechanism. However there are many other types
of attention that have recently proposed including
local attention (Luong et al., 2015), sparse-max attention
(Martins and Astudillo, 2016), hierarchical
attention (Yang et al., 2016) among others. As
this is simply a module in OpenNMT it can easily
be substituted. Recently the Harvard group developed
a structured attention approach, that utilizes
graphical model inference to compute this attention.
The method is quite computationally complex;
however as it is modularized by the Torch
interface, it can be used in OpenNMT to substitute
for standard attention.

Are these different attention networks implemented in OpenNMT-py? If there are implemented, how can I use them instead of the global_attention? I do not see any argument for those in the opt.py file.

Thanks,
Inigo

**Comment by JianyuZhan** [comment]
The local attention and hierarchical attention haven't been implemented.

Sparse-Max Attention is in `onmt/modules/StructuredAttention.py`.

There are MultiHeaded Attention for `transformer` in `onmt/modules/MultiHeadedAttn.py`;  MultiStep Attention for `cnn` model in `onmt/modules/ConvMultiStepAttention.py`.

Basically you can use them by just import that specific file, with some boilerplate code. Later we will refactor these a little bit, and hopefully users can use by just importing and creating that specific class.

**Comment by ijauregiCMCRC** [comment]
Ok. Thank you!

**Comment by srush** [comment]
Yeah, sorry this was for the lua version. We do hope to get to this quite soon though.
