### ISSUE TITLE
GRU in StdRNNDecoder

### ISSUE THREAD

**Issue by abhiskk** [OpenNMT/OpenNMT-py#358]
The current version of OpenNMT crashes when using `GRU` in `StdRNNDecoder`. This is happening because the input to forward are different for [GRU](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py#L399-L405) as compared to [LSTM](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py#L322-L330). 

I have opened a PR #353 to try and fix this. 

Below is the command for which the code crashes:

```
python train.py \
-data data/demo \
-save_model demo-model \
-enc_layers 1 \
-dec_layers 1 \
-epochs 4 \
-rnn_type GRU \
-input_feed 0 \
-batch_size 4
```

**Comment by srush** [comment]
Okay, I merged this. If you have a chance to add a unittest that would be awesome as well. It should only be one line in the tests/ directory.
