### ISSUE TITLE
Math of CopyGenerator?

### ISSUE THREAD

**Issue by moonlightlane** [OpenNMT/OpenNMT-py#361]
Hi,

I was reading the `CopyGenerator.py` file and had the following confusions. Some clarifications would be greatly appreciated!!

1. Is there a paper according to which the forward pass in `CopyGenerator` implements? I took a look at the [CopyNet paper](https://arxiv.org/pdf/1603.06393v3.pdf) but the CopyGenerator implementation does not appear to resemble the math in CopyNet paper (specifically, equation 5 and 6). For example, the paper uses a normalization term shared by both the copy probability and the original probability, whereas in the code the copy and original probability are calculated separately and then concatenated together. I will keep tracing the variables used in the forward pass and try to figure out what the matrix multiplications are doing there, but if someone can point out the math that would be great :)

2. In `__call__ ` in `CopyGeneratorCriterion` class, how is the loss calculated? In particular, what happens if a token is in both the target vocabulary and the source sequence, and how is `force_copy` used? From what I understand so far, when the above situation happens, there will be 2 indices in the output probability vector from the CopyGenerator for that token, and loss in both 2 indices are accumulated. As for `force_copy`, only the loss from the copy portion of the probability vector is accumulated. Is my understanding correct?

Also I think there is a tiny tiny typo in the comment in line 24: the variable `z` in the copy probability should be 1 instead of 0, e.g. `p_{copy}(w|z=1)` instead of `p_{copy}(w|z=0)`? 

Thanks in advance!

**Comment by srush** [comment]
- Our copy generator is based on "Get To The Point: Summarization with Pointer-Generator Networks" https://nlp.stanford.edu/pubs/see2017get.pdf. There are many different versions of this idea. If you want to try another one, we are happy help out. 

- Your understanding about force_copy is correct. 

Can you send us a PR with the math fix?
