### ISSUE TITLE
How to enable tensorboard visualization ?

### ISSUE THREAD

**Issue by laubonghaudoi** [OpenNMT/OpenNMT-py#363]
Is there an argument to toggle on/off tensorboard logging ? Or I have to manually add the SummaryWriter in the training codes.?

**Comment by srush** [comment]
We use `Crayon` for tensorboard visualizations. It is a tensorboard server that you send log data to. 

Set these arguments to point to your crayon server.
```
    parser.add_argument('-exp_host', type=str, default="",
                        help="Send logs to this crayon server.")
    parser.add_argument('-exp', type=str, default="",
                        help="Name of the experiment for logging.")
```
