### ISSUE TITLE
No module named 'onmt.Dict' when running translate.py

### ISSUE THREAD

**Issue by zhang23** [OpenNMT/OpenNMT-py#364]
When I trying to run the translate.py using the summarization modle, it comes the error that no module named onmt.Dict
![default](https://user-images.githubusercontent.com/19945329/32091317-33632678-bb26-11e7-8565-9ce388e0553d.JPEG)

python: 3.5，GPU
The command is : $ python3.5 translate.py -model textsum_acc_51.38_ppl_12.59_e13.pt -src ./input2.txt -gpu 0

**Comment by JianyuZhan** [comment]
Hmm, did you train and translate using the same code?  Update to latest master branch, and do a fresh train and translate see if it still pops up?

**Comment by srush** [comment]
Yeah, it looks like this model was trained with an old version of the system. Unfortunately we removed onmt.Dict this summer.
