### ISSUE TITLE
out-of-date Quickstart instructions?

### ISSUE THREAD

**Issue by emilypx** [OpenNMT/OpenNMT-py#365]
The instructions in the Quickstart section, along with those in the README in the repo, seem to be out of date, e.g.:

1. No *.dict files are generated by preprocess.py, as described in Step 1. It seems that preprocess.py now creates a single .pt binary for the vocabulary.

2. There is no -gpus option available in train.py, as mentioned in Step 2. It seems that there is now a -gpuid option instead.

**Comment by JianyuZhan** [comment]
You are right! Would fix it,  feel free to send a fix pull request if you like :-)

**Comment by srush** [comment]
Okay, think I fixed these now.
