### ISSUE TITLE
how are words converted into indices during training???

### ISSUE THREAD

**Issue by moonlightlane** [OpenNMT/OpenNMT-py#367]
I feel there's some magic happening here...

Once you constructed an `OrderedIterator` object from the data (`train.py` line 136, 137), you only need to do `for i, batch in enumerate(train_iter)` to start training in these batches (`Trainer.py`, line 100), where `train_iter` is an `OrderedIterator` object. Then, inexplicitly, the `src` and `tgt` in dataset (can be access by `batch.dataset.examples[idx].src` or `batch.dataset.examples[idx].tgt`) are magically converted to `(seq_len x batch_size)` matrix where each entry is the corresponding index of that word in the source or target sequence!! In the `OrderedIterator`, however, I didn't find anywhere such a conversion happens. `OrderedIterator.dataset.examples` contain the original `src` and `tgt` that are still words.

Someone knows what is happening here?? Much appreciated!!

**Comment by JianyuZhan** [comment]
The correspondence between words and indexes happen in preprocess stage, check `preprocess.py` please.

**Comment by moonlightlane** [comment]
Hi @JianyuZhan , perhaps I didn't articulate my question well... I know that the preprocess creates a vocab so you can do `vocab.stoi` or `vocab.itos` to find correspondence between words and indices. 

I was wondering how this conversion is done during the training process, for a complete sequence. For example, after line 262 in `train.py` you will have a `train` variable which is an `ONMTDataset` object, and you can access the original, token separated source or target sequence by `train.examples[idx].src` or `train.examples[idx].tgt`. The sequence you get is like this: 

`(u'stephen', u'jay', u'gould', u'proposed', u'an', u'approach', u'dividing', u'the', u'world', u'of', u'philosophy', u'into', u'what', u'he', u'called', u'"', u'non-overlapping', u'magisteria', u'"', u'(', u'noma', u')', u'.', u'non-overlapping', u'magisteria')
`

However, after you create the iterators in line 136 and 137 in `train.py`, the above sequence is suddenly converted into indices by simply iterating through the iterator in batches (line 100 in `Trainer.py`). The converted sequence for the above sentence, which can be access by `batch.tgt` or `batch.src[0]`, might be the following `torch.FloatTensor` object:

`1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ...` just for an example.

So, I think something must have happened somewhere that converts a batch of sequences that are still in the form of lists of tokens, into a matrix of indices. Or rather, the conversion is done during preprocess step and is stored somewhere. In either case, I fail to find where such conversion is done, or where the converted matrix is stored.....

**Comment by JianyuZhan** [comment]
Hi, @moonlightlane, I am not sure if you are concerning where the token sequence get transformed into `torch.FloatTensor`.  If yes, then the answer is the `torchtext` code: https://github.com/pytorch/text

The `torchtext.data.Iterator`(the super class of `OrderedIterator`) implements its own special method `__iter__`, see https://github.com/pytorch/text/blob/master/torchtext/data/iterator.py#L160.

This `__iter__` method will be called when we do `for i, batch in enumerate(self.train_iter)`, thus it will call `Iterator.init_epoch`, which in turn calls `OrderedIterator.create_batches()` to create batches. Then
this magic transform happens in the batch creation code in `torchtext.data.Batch`, where a `Batch` object is created, and the `setattr` method is used to set batch's attributes, including `src` and `tgt`. And it is exactly here the preprocess code transforms the token sequence into `Tensor`, see https://github.com/pytorch/text/blob/master/torchtext/data/batch.py#L22

**Comment by moonlightlane** [comment]
@JianyuZhan yes, I think I also figured this out yesterday. Thanks so much for your patience and the detailed answer!!
