### ISSUE TITLE
OSError:No space left on device raised when running train.py.

### ISSUE THREAD

**Issue by caozhen-alex** [OpenNMT/OpenNMT-py#373]
train with gpu.
<img width="1280" alt="screenshot 2017-11-03 13 25 45" src="https://user-images.githubusercontent.com/26409810/32361357-8324605e-c09a-11e7-8cc9-b8fa2e00e56d.png">

**Comment by JianyuZhan** [comment]
This is because the device where you save your model(`*.pt`) has no space, it is not a program error.
