### ISSUE TITLE
translate on single sentence instead of text

### ISSUE THREAD

**Issue by XiangZhu0718** [OpenNMT/OpenNMT-py#381]
When conduct translate, how can I use the sentences from commed line, instead of in the form of text,  to be as the `-src`?

**Comment by JianyuZhan** [comment]
No support now.

But could be easy done with a little trick:

```
<some process generating sentences> |
while  read sent; do
    echo $sent > /tmp/sent.txt && python translate.py ...  -src /tmp/sent.txt
done
```

**Comment by srush** [comment]
yeah, I don't think we will support this. Easy to do with bash.
