### ISSUE TITLE
Support  input reversing in luong 2015

### ISSUE THREAD

**Issue by IdiosyncraticDragon** [OpenNMT/OpenNMT-py#391]
I wan to run the results in _Thang Luong, Hieu Pham, Christopher D. Manning: Effective Approaches to Attention-based Neural Machine Translation. EMNLP 2015: 1412-1421_ . However, it is seems like there is no such choice in OpenNMT-py, is that right or I missed some selections?

**Comment by JianyuZhan** [comment]
We have implemented the global attention, the input feed, but yet no local attention, in this paper.

Please see the options `-global_attention`, `-input_feed` in `opts.py`.

**Comment by IdiosyncraticDragon** [comment]
I see there has implemented some features of the mentioned paper. My concern is, to luong 2015, the network accepts the input in reverse. I want to know if there is such an choice implemeted.

**Comment by JianyuZhan** [comment]
If I am not mistaken, `reverse input` is not supported yet.

**Comment by srush** [comment]
I don't think we will support this directly. If you want to reverse input, just write a python script to reverse your input files directly: 

Something like: 

> for l in sys.stdin:
>    print(" ".join(reversed(l.strip().split())))
