### ISSUE TITLE
Image-to-text

### ISSUE THREAD

**Issue by mtensor** [OpenNMT/OpenNMT-py#393]
Is image to text implemented, and if so, how should the image data be formatted for preprocessing? Would following the formatting given at https://github.com/OpenNMT/Im2Text work?

**Comment by JianyuZhan** [comment]
Not yet.  But pull request https://github.com/OpenNMT/OpenNMT-py/pull/380 is under review.

**Comment by srush** [comment]
Now merged with a readme
