### ISSUE TITLE
Translator error

### ISSUE THREAD

**Issue by xjtu-zeng** [OpenNMT/OpenNMT-py#396]
![image](https://user-images.githubusercontent.com/15373554/33324859-c112aeca-d48b-11e7-9ee5-ef68f5486117.png)

**Comment by JianyuZhan** [comment]
Seems same as https://github.com/OpenNMT/OpenNMT-py/issues/354.  Please downgrade your torchtext to 0.1.1 to temporally fix the problem. We will upgrade to new version of torchtext when the issue is fixed.

**Comment by xjtu-zeng** [comment]
yes, the method works for me.
