### ISSUE TITLE
Performance of OpenNMT versus OpenNMT-py

### ISSUE THREAD

**Issue by KenyaAA** [OpenNMT/OpenNMT-py#399]
Hi, I'm working on english-chinese translation with OpenNMT-py.
When I run english to chinese translation model, I have very low BLEU score.
Training dataset is as follow:
 - training set: UM News Corpus (370k) + WMT 17 TED Corpus (130k)
At epoch 13, model's training ppl is 108.99 and BLEU- News: 11.22, TED: 2.80

To check problem, I trained model with same model paramertes and dataset on OpenNMT, and I have different results.
At epoch 13, models' training ppl is 32.43 and BLEU- News: 24.88, TED: 18.68

I don't know why the results are different. Does OpenNMT and OpenNMT-py behave differently?

**Comment by JianyuZhan** [comment]
Both projects have close relationship, but neither one is the exact mirror of the other one, and the implementation detail might differ. The OpenNMT is older and has more features, OpenNMT-py is still in its early stage. Besides, there might be different default parameters between two projects. So you shall compare the printed model parameters to do an exact comparison.

**Comment by KenyaAA** [comment]
Okay. I'll check parameters. Thanks.

**Comment by Runingtime** [comment]
@KenyaAA Did you get similar results after checking parameters?

**Comment by KenyaAA** [comment]
> @KenyaAA Did you get similar results after checking parameters?

Yes,I found that the data processing was problem.
I don't know the details, the 'Carriage return' character caused this problem on OpenNMT-py only.
So, if you have same problem, I recommend checking the data.
