### ISSUE TITLE
Translator replace_unk exception when max attention is on EOS

### ISSUE THREAD

**Issue by ylhsieh** [OpenNMT/OpenNMT-py#40]
[Translator.py#61](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Translator.py#L61)
uses attention to replace unknowns in decoded tokens, but sometimes the max attention is on EOS, which causes an exception.

> File "/home/user/pytorch-seq2seq/onmt/Translator.py", line 65, in buildTargetTokens
>     tokens[i] = src[maxIndex[0]]
> IndexError: list index out of range

Should we guard against this case? Or maybe exclude specials when finding the max attention token?

**Comment by srush** [comment]
I think we did this now.
