### ISSUE TITLE
Preprocessing is slow

### ISSUE THREAD

**Issue by playma** [OpenNMT/OpenNMT-py#407]
It spent a lot of time to preprocessing big data (LCSTS dataset)
LCSTS(A Large Scale Chinese Short Text Summarization Dataset) is about 2,400,000 pair of short text and summarization 

I use "time" to calculate the process time and get
**482.88s user 60.32s system 5% cpu 2:49:00.97 total**

**Is it a bug? Or It could have been an operational mistake.**

This my command
```
    python3 preprocess.py \
      -train_src $ORIGIN_DIR/train.source \
      -train_tgt $ORIGIN_DIR/train.target \
      -valid_src $ORIGIN_DIR/valid.source \
      -valid_tgt $ORIGIN_DIR/valid.target \
      -src_vocab_size 8000 \
      -tgt_vocab_size 8000 \
      -src_seq_length 10000 \
      -tgt_seq_length 10000 \
      -src_seq_length_trunc 400 \
      -tgt_seq_length_trunc 100 \
      -save_data $DATA_DIR/processed
```

file is generated
```
-rw-rw-r-- 1 playma playma 2.6G Dec  3 11:45 processed.train.pt
-rw-rw-r-- 1 playma playma 1.1M Dec  3 14:14 processed.valid.pt
-rw-rw-r-- 1 playma playma  19M Dec  3 11:40 processed.vocab.pt
```

**Comment by JianyuZhan** [comment]
I am a bit confused with your figure. The `user` mode time and the `system` mode time look normal, but  `total` time looks insane?!   `user` + `system` is far less the total. This doesn't make sense. I suggest you test it again, and post the figure with more nice format.

**Comment by playma** [comment]
I test it again and get the similar result.
I found that it has saved file at the very early time but the process doesn't finish, so it get this result.
I have no idea what happened.

**Comment by playma** [comment]
I use the script to run the preprocess.py, maybe it is the reason

**Comment by playma** [comment]
I read the data from other HDD disks and save the file to the same disk and it is slow.
Finally, I change the path to save the data to the disk which I execute the program, and the problem solved.

**Comment by playma** [comment]
I have checked the ``iotop``.
It seems that bottleneck is ``onmt.IO.ONMTDataset``
When the program executes ``torch.save(train, open(opt.save_data + '.train.pt', 'wb'))``
It spends a lot of time to process ``onmt.IO.ONMTDataset``, but save file is only a few time.

<img width="953" alt="screen shot 2017-12-05 at 8 48 30 pm" src="https://user-images.githubusercontent.com/7677470/33607955-b7573b90-d9fd-11e7-860f-d88cbd81682c.png">

**Comment by JianyuZhan** [comment]
Thanks, can you share the measurement result or elaborate on how you pinpoint the bottleneck at `onmt.IO.ONMTDataset`?

**Comment by playma** [comment]
Someone give the test code below
```
x = torch.zeros(3500000000//4)
torch.save(x, “tmp.txt”)
```
And It spends only 4mins to save the file.
And It spends most of the time in disk_write not disk_read.

You can see details here.
https://discuss.pytorch.org/t/using-torch-save-to-save-big-file-is-very-slow/10749/8

**Comment by JianyuZhan** [comment]
Sorry, I don't get your point, could you be more specific?

**Comment by playma** [comment]
I don't know why it spends most of the time in disk_read not disk_write when the program executes ``torch.save(train, open(opt.save_data + '.train.pt', 'wb'))``
so I guess when it  executes this line, it wiil call train = onmt.IO.ONMTDataset(...)

**Comment by playma** [comment]
It seems that when I update the pytorch to 0.3.0, the problem solved.

**Comment by playma** [comment]
@JianyuZhan This problem is the same as issue #283
