### ISSUE TITLE
Elapsed Time grows in training. 

### ISSUE THREAD

**Issue by playma** [OpenNMT/OpenNMT-py#410]
It is very slow when I run the training process.

`
    python3 train.py 
      -data_char $DATA1_DIR/processed 
      -data_word $DATA2_DIR/processed 
      -word_vec_size 300 
      -encoder_type brnn 
      -epochs 20 
      -enc_layers 1 
      -dec_layers 1 
      -rnn_size 300 
      -gpuid 0 
      -save_model $MODEL_DIR/model
`

The elapsed is growth, and from 653 to 1191. Now is 1434, Why?
Can I have some trick to speed up?

<img width="1279" alt="screen shot 2017-12-05 at 9 44 08 am" src="https://user-images.githubusercontent.com/7677470/33585838-61016f42-d9a1-11e7-8972-929aa36b8873.png">

**Comment by playma** [comment]
And it will grow to 107046s at epoch 13

<img width="1276" alt="screen shot 2017-12-05 at 10 05 51 am" src="https://user-images.githubusercontent.com/7677470/33586339-e9ff5956-d9a3-11e7-8cdb-86c88080be9a.png">

**Comment by JianyuZhan** [comment]
Note in the first figure the two rows that are separated by blank lines,  there is a conspicuous throughput drop, thus slowing down the training, then it recovered to normal, and the overall processing speed is reasonable.

So there might be some outside factor affecting the weird slow down. Can't judge based on these number only.  If you can replicate this problem, please report again, I might need to ask you to provide
the system cpu/memory usage information during the training to aid in diagnosis.

**Comment by playma** [comment]
Actually, the first and second picture is different training process, word_vec embedding 8000 in the first picture, 4000 in the second. It is too slow in training embedding size 8000, so I cut it.

I can provide the second one's training log
[training_log.txt](https://github.com/OpenNMT/OpenNMT-py/files/1530094/training_log.txt)

The elapsed seconds will grow to very large gradually?

**Comment by playma** [comment]
@JianyuZhan Is there any solution?

**Comment by srush** [comment]
Not sure I understand the issue. Elapsed always grows. It is the time since start of training.
