### ISSUE TITLE
ValueError: lengths array has to be sorted in decreasing order

### ISSUE THREAD

**Issue by Star-in-Sky** [OpenNMT/OpenNMT-py#412]
When I train model in ubuntu17.10 by python3.6, there is the problem:
>Traceback (most recent call last):
  File "train.py", line 304, in <module>
    main()
  File "train.py", line 300, in main
    train_model(model, train, valid, fields, optim)
  File "train.py", line 165, in train_model
    valid_stats = trainer.validate()
  File "/data/rsong/OpenNMT-py/onmt/Trainer.py", line 155, in validate
    outputs, attns, _ = self.model(src, tgt, src_lengths)
  File "/usr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/rsong/OpenNMT-py/onmt/Models.py", line 420, in forward
    enc_hidden, context = self.encoder(src, lengths)
  File "/usr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/rsong/OpenNMT-py/onmt/Models.py", line 94, in forward
    packed_emb = pack(emb, lengths)
  File "/usr/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 79, in pack_padded_sequence
    raise ValueError("lengths array has to be sorted in decreasing order")
ValueError: lengths array has to be sorted in decreasing order

So, I tracked the code, find that **onmt/modules/IO.py**
>class OrderedIterator(torchtext.data.Iterator):
    def create_batches(self):
        if self.train:
            self.batches = torchtext.data.pool(
                self.data(), self.batch_size,
                self.sort_key, self.batch_size_fn,
                random_shuffler=self.random_shuffler)
        else:
            self.batches = []
            for b in torchtext.data.batch(self.data(), self.batch_size,
                                          self.batch_size_fn):
                **self.batches.append(_sorted(b, key=self.sort_key)_)**

I find the code marked in the above that it uses a "sorted()" by default parameter to be a ascending order.  So , I just change it by adding "reverse=True"
>self.batches.append(sorted(b, key=self.sort_key,reverse=True))

Finally , the error just be removed. However, I can't understand why it need valid data in descending order.

**Comment by JianyuZhan** [comment]
See https://github.com/OpenNMT/OpenNMT-py/issues/345.

Current temporary fix is to downgrade your `torchtext` to `0.1.1`, and when it has fixed the issue and available on PyPI, we will fix accordingly.
