### ISSUE TITLE
Question about attn_output in code

### ISSUE THREAD

**Issue by playma** [OpenNMT/OpenNMT-py#417]
I would like to ask what is `attn_output` here

https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L341

Actually, I am implementing the dual-attention seq2seq like the architecture below.
I have no idea how to  work with `attn_output` in the original code.
<img width="978" alt="screen shot 2017-12-06 at 4 12 00 pm" src="https://user-images.githubusercontent.com/7677470/33651296-3f73cb36-daa0-11e7-946b-e973a620df1a.png">

**Comment by JianyuZhan** [comment]
At a given time step `t`, the decoder's output **h_t** concatenates with context vector **c_t**,  then pass through a **linear layer**,  then the output is `attn_output` in our code, in which,

**h_t** is the RNN's hidden state at time t ,
**c_t** is the weighted decoder hidden states,  a.k.a "the source side info are encoded into a fixed size 
context vector".

If you find this obscure to understand, check Luong 2015 paper Figure 2:
https://arxiv.org/pdf/1508.04025.pdf

**Comment by playma** [comment]
Can I ask a simple question?
What is the different between `attn` and `attn_output` ?
`attn_output, attn = self.attn(rnn_output, context.transpose(0, 1))`

**Comment by JianyuZhan** [comment]
`attn` is attention, that is, you use the decoder hidden state **h_t** to calculate the encoder hidden states to get the attention scores, then normalize the scores to get the attention.

`attn_output` is as explained as my previous comment, it is combined information of attention and decoder hidden state.

**Comment by srush** [comment]
We should probably change the name of `attn_output` variable. The correct name for it in the literature is the `context` vector.

**Comment by playma** [comment]
I am still confused.

GlobalAttention is the same as below?
<img width="499" alt="screen shot 2017-12-07 at 3 15 10 pm" src="https://user-images.githubusercontent.com/7677470/33703080-746e2978-db61-11e7-924f-79a35ca428bf.png">

How to map each variable to the symbol here?

**Comment by playma** [comment]
I found that it is a little different between the (5) and OpenNMT document.
![screen shot 2017-12-07 at 3 37 40 pm](https://user-images.githubusercontent.com/7677470/33703794-9cd12b60-db64-11e7-80f3-b6757fcc5299.png)

**Comment by srush** [comment]
attn_output is always `c` in the above equations. attn is always `a`. Score may be computed differently depending of the model.
