### ISSUE TITLE
Unused argument in make_shard_state()

### ISSUE THREAD

**Issue by playma** [OpenNMT/OpenNMT-py#422]
It is confused that attn pass to `argument in make_shard_state()` and never use.
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Loss.py#L112

`attn` pass from model `to argument in make_shard_state()`
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L189
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Trainer.py#L118
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Trainer.py#L122
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Loss.py#L63
It seems unnecessary, Is it important?

**Comment by JianyuZhan** [comment]
`make_shard_state()` is a superclass method, and it has another implementation in `CopyGeneratorLossCompute` in `onmt/modules/CopyGenerator.py`, which uses `attn`.

Actually we can use `make_shard_state(*args, **kwargs)` to avoid listing arguments that might be not needed by subclasses. But for documentation consideration, I don't do like this.

**Comment by playma** [comment]
Got it.
Maybe separate  `attns` to `attn_std` and `attn_copy` is a better method.
Because `CopyGeneratorLossCompute` only use `attns['copy']`
