### ISSUE TITLE
Translating Chinese to English, get some Chinese words in translation.

### ISSUE THREAD

**Issue by Jeqen** [OpenNMT/OpenNMT-py#423]
I trained a Chinese-to-English model following the Tutorial, when I used this model to translate Chinese sentences, I get some Chinese words in English result:

_**SENT 1071: 巴林 公主 <unk> 美 大兵 <unk> 婚姻 五 年 宣告 破裂
PRED 1071: 婚姻 marriage between bahrain princess <unk>

SENT 1079: 不过 , 强生 表示 , 由于 被 称为 「 罪恶 之 城 」 的 拉斯维加斯 有 不少 诱惑 , 他 和 <unk> <unk> 势 大 的 <unk> 又 一直 关系 紧张 , 加以 <unk> 有 暗杀 他 的 阴谋 , 这 桩 历尽 波折 的 婚姻 终于 撑 不 下去 。
PRED 1079: however , 强生 said that there were quite a few 诱惑 that had been called " a city of 城 , " and that he had always been in a tense situation with <unk> , and the 暗杀 of the 暗杀 had been tense .**_

I checked the training data, there was no Chinese words in English corpus.
So I am very confused.....

**Comment by JianyuZhan** [comment]
See `replace_unk` option, which is by default `True`: https://github.com/OpenNMT/OpenNMT-py/blob/master/opts.py#L269

**Comment by Jeqen** [comment]
Thanks for your reply.
I should do more work on the original code...

**Comment by weizhenzhao** [comment]
@Jeqen 
Hi Jeqen I used opennmt-py to train the translator of English to Chinese
after I finish trainning process
when I execute python translate.py -gpu 0 ........
some thing wrong happened 
if I sent a English scentence to the translator , the pred result is also an English one
can you teach me how to solve this issue?

Thanks
weizhen
