### ISSUE TITLE
Greedy Decoder available ?

### ISSUE THREAD

**Issue by rajarsheem** [OpenNMT/OpenNMT-py#424]
Is greedy decoder, which feed current step's prediction as next decoder time step's input, available ?

**Comment by JianyuZhan** [comment]
No, could you point me to the paper?

**Comment by rajarsheem** [comment]
Greedy Decoder is basically the standard decoder that don't use teacher forcing.
It will take the start token and will predict, at each step, use previous step's prediction as current time step's decoder input. It should be there in this repo because that's how you do inference but I could not possibly find it.

**Comment by JianyuZhan** [comment]
Ah, okay.   This is hidden in the `RNNDecoderState`: https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L459.

And it is passed from previous step to current step here:https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Translator.py#L152

Is this what you are looking for?

**Comment by rajarsheem** [comment]
Yeah, got it. Thanks!

**Comment by rajarsheem** [comment]
Do you what [this](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Translator.py#L66) function runTarget() is doing ?
