### ISSUE TITLE
Can I turn off the attention?

### ISSUE THREAD

**Issue by cloudygoose** [OpenNMT/OpenNMT-py#426]
Hi, is there a simple way to just turn off the attention structure in the model, and have a vanilla LSTM seq2seq model?

**Comment by srush** [comment]
Strangely we don't actually have this built in yet! We should just have a NULL attention mode though. 

If you want, you can probably just modify this line to do it (https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L259) and use -input_feed 0
