### ISSUE TITLE
How to visualize the word embedding and word alignment?

### ISSUE THREAD

**Issue by NLPpupil** [OpenNMT/OpenNMT-py#428]
How to visualize the word embedding and word alignment? Are there any automatic methods?

**Comment by srush** [comment]
Yeah, we have a script `extract_embeddings.py` in tools that let's you pull out the embeddings. There should be code in the forum to convert that to tensorboard format. 

We don't have an alignment visualizer yet, but you can modify translation to print out the alignments. 

I'll make it a request to document these two.

**Comment by vince62s** [comment]
This http://nlp.seas.harvard.edu/2018/04/03/attention.html is a great resource too.
