### ISSUE TITLE
StackedLSTM vs nn.LSTM

### ISSUE THREAD

**Issue by aosokin** [OpenNMT/OpenNMT-py#43]
Hi, is there any difference between StackedLSTM and pytorch LSTM?
Specifically, it looks like the effect of 
```
nn.LSTM(input_size, hidden_size,
                        num_layers=layers,
                        dropout=dropout)
```
and 
```
StackedLSTM(layers, input_size, hidden_size, dropout)
```
is largely the same.

Is there any reason why StackedLSTM was used?

**Comment by jekbradbury** [comment]
Input feeding for attention is impossible with nn.LSTM.

**Comment by aosokin** [comment]
@jekbradbury But nn.LSTM also returns (h_n, c_n) meaning that it can be used in unrolled mode.
I mean that literally doing
```
self.rnn = nn.LSTM(input_size, opt.rnn_size, num_layers=opt.layers, dropout=opt.dropout)
```
in the constructor and 
```
emb_t = emb_t.unsqueeze(0)
output, hidden = self.rnn(emb_t, hidden)
output = output.squeeze(0)
```
works fine

**Comment by jekbradbury** [comment]
Turns out that for now that uses way more memory because of how PyTorch wraps the cuDNN LSTM. Hopefully it’ll be fixed soon.

**Comment by aosokin** [comment]
@jekbradbury Interesting observation about memory. Thanks!
