### ISSUE TITLE
Sudden Drop in Accuracy

### ISSUE THREAD

**Issue by caleblu** [OpenNMT/OpenNMT-py#431]
Can someone explain why there is a sudden drop in accuracy/increase in perplexity? 
Epoch  2, 52600/733817; acc:  42.20; ppl:  22.37; 998 src tok/s; 1132 tgt tok/s;   6234 s elapsed
Epoch  2, 52650/733817; acc:  43.40; ppl:  21.06; 998 src tok/s; 1132 tgt tok/s;   6239 s elapsed
Epoch  2, 52700/733817; acc:  40.87; ppl:  25.50; 1006 src tok/s; 1126 tgt tok/s;   6245 s elapsed
Epoch  2, 52750/733817; acc:  42.53; ppl:  22.06; 1016 src tok/s; 1121 tgt tok/s;   6251 s elapsed
Epoch  2, 52800/733817; acc:  42.20; ppl:  22.94; 991 src tok/s; 1170 tgt tok/s;   6257 s elapsed
Epoch  2, 52850/733817; acc:  43.25; ppl:  21.30; 993 src tok/s; 1162 tgt tok/s;   6263 s elapsed
Epoch  2, 52900/733817; acc:  42.14; ppl:  24.27; 732 src tok/s; 849 tgt tok/s;   6270 s elapsed
Epoch  2, 52950/733817; acc:  44.76; ppl:  19.35; 952 src tok/s; 1124 tgt tok/s;   6275 s elapsed
Epoch  2, 53000/733817; acc:  41.96; ppl:  24.42; 959 src tok/s; 1134 tgt tok/s;   6281 s elapsed
Epoch  2, 53050/733817; acc:  43.39; ppl:  21.48; 961 src tok/s; 1130 tgt tok/s;   6286 s elapsed
Epoch  2, 53100/733817; acc:  41.35; ppl:  24.57; 925 src tok/s; 1092 tgt tok/s;   6292 s elapsed
Epoch  2, 53150/733817; acc:  41.94; ppl:  24.31; 1006 src tok/s; 1161 tgt tok/s;   6298 s elapsed
Epoch  2, 53200/733817; acc:  42.59; ppl:  28.78; 989 src tok/s; 1146 tgt tok/s;   6304 s elapsed
Epoch  2, 53250/733817; acc:   9.15; ppl: 87931023.35; 753 src tok/s; 859 tgt tok/s;   6311 s elapsed
Epoch  2, 53300/733817; acc:   3.59; ppl: 240790327.35; 991 src tok/s; 1148 tgt tok/s;   6317 s elapsed
Epoch  2, 53350/733817; acc:   3.73; ppl: 1069121391.78; 1021 src tok/s; 1183 tgt tok/s;   6323 s elapsed
Epoch  2, 53400/733817; acc:   2.78; ppl: 3619363937.85; 1017 src tok/s; 1164 tgt tok/s;   6328 s elapsed
Epoch  2, 53450/733817; acc:   3.11; ppl: 516391446.86; 1008 src tok/s; 1175 tgt tok/s;   6334 s elapsed
Epoch  2, 53500/733817; acc:   0.66; ppl: 1027872386264.20; 961 src tok/s; 1121 tgt tok/s;   6339 s elapsed
Epoch  2, 53550/733817; acc:   0.28; ppl: 1108833956864644.00; 1000 src tok/s; 1173 tgt tok/s;   6345 s elapsed
Epoch  2, 53600/733817; acc:   0.26; ppl: 74638493001768560.00; 771 src tok/s; 892 tgt tok/s;   6352 s elapsed
Epoch  2, 53650/733817; acc:   0.26; ppl: 12168771858211136.00; 990 src tok/s; 1138 tgt tok/s;   6357 s elapsed
Epoch  2, 53700/733817; acc:   0.26; ppl: 42228779712064216.00; 1024 src tok/s; 1161 tgt tok/s;   6363 s elapsed
Epoch  2, 53750/733817; acc:   0.56; ppl: 13249564130222130.00; 978 src tok/s; 1160 tgt tok/s;   6369 s elapsed

**Comment by yoonkim** [comment]
Yeah these things happen from time to time. Try making the max_grad_norm smaller (e.g. try 1)
