### ISSUE TITLE
Dump the last encoder hidden state

### ISSUE THREAD

**Issue by NewGate0001** [OpenNMT/OpenNMT-py#438]
In torch OpenNMT there is an option "dump_input_encoding" that allows dumping the last hidden state of the encoder at translation time to a given file, is there a similar option for OpenNMT-py, if not how to access that last encoder hidden state at translation time?

**Comment by srush** [comment]
we don't have this yet. We'll add it.

**Comment by vince62s** [comment]
closing, reopen if needed.

**Comment by tanmayb123** [comment]
@srush Any updates on this?

**Comment by peps0791** [comment]
Hi,

I am also looking to migrate my project from OpenNMT-lua to OpenNMT-py.
@srush, are there any updates on this? Is this in plans for the near future?
