### ISSUE TITLE
Source word not in tgt dict in collapse_copy_scores?

### ISSUE THREAD

**Issue by sriniiyer** [OpenNMT/OpenNMT-py#439]
https://github.com/OpenNMT/OpenNMT-py/blob/45d92297e40775d46c66df60c69060e63bfa4417/onmt/IO.py#L402

Was getting an issue here were sw is not in the target vocab. Can this happen? Is there anything to ensure that all source words are in the target vocab?

**Comment by JianyuZhan** [comment]
Use `-share_dict`
