### ISSUE TITLE
"Convolutional Sequence to Sequence Learning" implementation

### ISSUE THREAD

**Issue by ethancaballero** [OpenNMT/OpenNMT-py#44]
Are there plans to add a PyTorch implementation of "Convolutional Sequence to Sequence Learning" to this repo?
Paper: https://s3.amazonaws.com/fairseq/papers/convolutional-sequence-to-sequence-learning.pdf
LuaTorch implementation: https://github.com/facebookresearch/fairseq/blob/master/fairseq/models/fconv_model.lua

**Comment by srush** [comment]
I don't think we will add this soon.

**Comment by srush** [comment]
Let's use forum.opennmt.net if you want to discuss more.

**Comment by StephenKyung** [comment]
@ethancaballero  
decoder part of Convolutional Sequence to Sequence Learning is implemented in \onmt\decoders\cnn_decoder.py
and encoder part is similiar with ResNet-18
