### ISSUE TITLE
torch.autograd.backward(inputs, grads)

### ISSUE THREAD

**Issue by KelleyYin** [OpenNMT/OpenNMT-py#443]
I can't completely understand its means of the backward in line 185 . I do some changes when calculating the loss , changing the loss function . However, it will arise a error: there are no graph nodes that require computing gradients. I convince the backward in line 185 lead to generate the bug . Therefore ,I want to completely understand the function.

**Comment by srush** [comment]
Here "inputs" are the end of a graph, and grads are the gradients we want to send back through that graph. For efficiency we calculate these gradients separately and send them back through the given inputs.

**Comment by KelleyYin** [comment]
@srush Yes , I see . Thanks a lot .
