### ISSUE TITLE
Need an `-output_vec_size` to allow different generator size and rnn size. 

### ISSUE THREAD

**Issue by howardyclo** [OpenNMT/OpenNMT-py#444]
Repost from the closed issue #115 .

The size mismatch problem is encountered when I attempted to run summarization-related task:

Preprocess command:
```
python preprocess.py -train_src ../dataset/efcamdat/sample_train_src.txt \                                                                                                1 ↵
-train_tgt ../dataset/efcamdat/sample_train_tgt.txt \
-valid_src ../dataset/jfleg/dev/dev.src \
-valid_tgt ../dataset/jfleg/dev/dev.ref0 \
-save_data ./data/sample \
-dynamic_dict -share_vocab
```
Train command:
```
python train.py -data data/sample \                                                                                                                                       1 ↵
-save_model sample-baseline-model \
-gpuid 0 \
-seed 1 \
-batch_size 64 \
-max_generator_batches 32 \
-epochs 5 \
-optim 'adam' \
-learning_rate 0.001 \
-max_grad_norm 2 \
-word_vec_size 128 \
-encoder_type 'brnn' \
-decoder_type 'rnn' \
-layers 2 \
-rnn_size 256 \
-rnn_type 'LSTM' \
-input_feed 0 \
-global_attention 'general' \
-share_decoder_embeddings -share_embeddings
```
Logs:
```
Loading train and validate data from 'data/sample'
 * number of training sentences: 99490
 * maximum batch size: 64
 * vocabulary size. source = 43625; target = 43625
Building model...
Intializing model parameters.
NMTModel (
  (encoder): RNNEncoder (
    (embeddings): Embeddings (
      (make_embedding): Sequential (
        (emb_luts): Elementwise (
          (0): Embedding(43625, 128, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(128, 128, num_layers=2, dropout=0.3, bidirectional=True)
  )
  (decoder): StdRNNDecoder (
    (embeddings): Embeddings (
      (make_embedding): Sequential (
        (emb_luts): Elementwise (
          (0): Embedding(43625, 128, padding_idx=1)
        )
      )
    )
    (dropout): Dropout (p = 0.3)
    (rnn): LSTM(128, 256, num_layers=2, dropout=0.3)
    (attn): GlobalAttention (
      (linear_in): Linear (256 -> 256)
      (linear_out): Linear (512 -> 256)
      (sm): Softmax ()
      (tanh): Tanh ()
    )
  )
  (generator): Sequential (
    (0): Linear (256 -> 43625)
    (1): LogSoftmax ()
  )
)
* number of parameters: 7405289
encoder:  6243456
decoder:  1161833

Traceback (most recent call last):
  File "train.py", line 306, in <module>
    main()
  File "train.py", line 302, in main
    train_model(model, train, valid, fields, optim)
  File "train.py", line 159, in train_model
    train_stats = trainer.train(epoch, report_func)
  File "/home/howard/research/OpenNMT-py/onmt/Trainer.py", line 125, in train
    trunc_size, self.shard_size)
  File "/home/howard/research/OpenNMT-py/onmt/Loss.py", line 73, in sharded_compute_loss
    loss, stats = self.compute_loss(batch, **shard)
  File "/home/howard/research/OpenNMT-py/onmt/Loss.py", line 121, in compute_loss
    scores = self.generator(self.bottle(output))
  File "/home/howard/.conda/envs/cedl2017/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/howard/.conda/envs/cedl2017/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/howard/.conda/envs/cedl2017/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/howard/.conda/envs/cedl2017/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 53, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/howard/.conda/envs/cedl2017/lib/python3.6/site-packages/torch/nn/functional.py", line 553, in linear
    return torch.addmm(bias, input, weight.t())
  File "/home/howard/.conda/envs/cedl2017/lib/python3.6/site-packages/torch/autograd/variable.py", line 924, in addmm
    return cls._blas(Addmm, args, False)
  File "/home/howard/.conda/envs/cedl2017/lib/python3.6/site-packages/torch/autograd/variable.py", line 920, in _blas
    return cls.apply(*(tensors + (alpha, beta, inplace)))
  File "/home/howard/.conda/envs/cedl2017/lib/python3.6/site-packages/torch/autograd/_functions/blas.py", line 26, in forward
    matrix1, matrix2, out=output)
RuntimeError: size mismatch at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/THC/generic/THCTensorMathBlas.cu:243
```

And I found the problem: 

Since I enabled `-share_decoder_embeddings`, this makes the input feature size in the weight matrix of the linear layer in the generator be equal to the `tgt_word_vec_size`, and causes the matrix size mismatch to the decoder's outputs' `rnn_size`. 

To put it briefly, if I did not enable `-share_decoder_embeddings`, the data flow will be:
decoder's outputs `(sent_length, batch_size, rnn_size)` --input to generator to project the hidden state to word ids-->  `(sent_length, batch_size, rnn_size)` x linear layer in generator `(in_features, out_features)`. And here, `in_features` should be the same as `rnn_size` when performing batch matrix-matrix product. But if we enable `-share_decoder_embeddings`, the `in_features` will become `tgt_word_vec_size`, and if `tgt_word_vec_size` != `rnn_size`, this will cause size mismatch error!

So I'm wondering:
1. Is this a bug?
2. In what scenario case would we enable `-share_decoder_embeddings`?
3. If this is not a bug, and what is the correct way to use?

Thanks.

**Comment by srush** [comment]
I think maybe you mean to use `share_embeddings`? 

`share_decoder_embeddings` will try to make the input and output embeddings on the decoder the same. In your case, your input embeddings are 128, but your output embeddings are 256 (same as RNN size). This is why you see the error.

**Comment by YuChunLOL** [comment]
@srush Hello:

1. No. it is not related to `share_embeddings`. 

2. Ok, I know the use case `share_decoder_embeddings `. 

3. The output embeddings is actually **128**, not 256. 
The problem is, when I enable the `share_decoder_embeddings`, it will execute the code [here](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/ModelConstructor.py#L166): `generator[0].weight = decoder.embeddings.word_lut.weight`. This makes the generator output  embeddings are the same as **`word_vec_size `** instead of **`rnn size`**.  

After executing the code I mentioned above, the model log info doesn't change from:
```
(generator): Sequential (
    (0): Linear (256 -> 43625)
    (1): LogSoftmax ()
  )
```
to:
```
(generator): Sequential (
    (0): Linear (300 -> 43625)
    (1): LogSoftmax ()
  )
```
Unless I change my `rnn_size` as same as my `target word embeddings size`, otherwise it will cause error.

So, does this mean to be like this? In order to use `share_decoder_embeddings`, should we usually make the `rnn_size` as same as `word_vec_size `?

**Comment by srush** [comment]
I think there is a misunderstanding. How can you share embeddings if they are different sizes? Your input is 128, your output is 256.

**Comment by srush** [comment]
I guess there could be a projection layer that maps form 256 -> 128 -> vocab size. We don't currently have that built in, but we could add it if that is what you would like?

**Comment by YuChunLOL** [comment]
@srush Yes! We need projection layer! That's what I mean, haha! And probably this is the core of the problem, since if we don't have projection layer, we can only set our `rnn_size` equal to the `word_vec_size`. Am I right?

**Comment by srush** [comment]
Yes, that is the issue. I think the solution will be to add a `-output_vec_size` with a linear projection. You are welcome to submit a PR.

**Comment by YuChunLOL** [comment]
Sure. 😉 Thanks for such efficient replies !

**Comment by howardyclo** [comment]
@srush, Hello, I think we can just modify the code from: https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/ModelConstructor.py#L190-L199
to:
```
if not model_opt.copy_attn:
        if model_opt.rnn_size == decoder.embeddings.embedding_size:
            generator = nn.Sequential(
            nn.Linear(model_opt.rnn_size, len(fields["tgt"].vocab)),
            nn.LogSoftmax())
        else:
            generator = nn.Sequential(
                nn.Linear(model_opt.rnn_size, decoder.embeddings.embedding_size),
                nn.Linear(decoder.embeddings.embedding_size, len(fields["tgt"].vocab)),
                nn.LogSoftmax()
            )
        if model_opt.share_decoder_embeddings:
            generator[-2].weight = decoder.embeddings.word_lut.weight
    else:
        generator = CopyGenerator(model_opt.rnn_size,
                                  fields["tgt"].vocab)
```

If it's okay, I'll send a pull request here :-)

**Comment by srush** [comment]
Hmm, I think you have to be a bit more careful. This will break current models. 

What if there is an argument -decoder_word_vec_size which defaults to -1, but if you set it to something else changes this behavior.
