### ISSUE TITLE
Explicit check when training with share_embeddings and not share_vocab

### ISSUE THREAD

**Issue by mataney** [OpenNMT/OpenNMT-py#453]
Hey, Whenever I run training with share_embedding flat I get the following error:

```RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1502009910772/work/torch/lib/THC/THCCachingHostAllocator.cpp:258```

Any idea what can cause this? how can fix this!

Thank.

**Comment by pltrdy** [comment]
Did you used `share_vocab` during preprocessing? I think it's mandatory and I remember of this error.

Still, I encountered this kind of device-side assert error on several occasion for various reasons (on experimental code)

**Comment by srush** [comment]
Oh yeah, need this at preprocessing. We should have an explicit check.

**Comment by JianyuZhan** [comment]
Will do this check in my current work on prerpocess.

**Comment by JianyuZhan** [comment]
Just wonder currently both options are by default `True`, if not explicitly assigning a `False` value, how would @mataney encounter this problem?

**Comment by mataney** [comment]
@pltrdy and @srush thanks! will run preprocessing again now.
@JianyuZhan they are both with `store_true`, doesn't it mean that only when you are passing `--share_vocab` it is assigned as True?!

**Comment by JianyuZhan** [comment]
@mataney, that means it is the default value if you don't explicitly specify a value for it.

**Comment by mataney** [comment]
@JianyuZhan 

![image](https://user-images.githubusercontent.com/11559198/34255455-714f992c-e659-11e7-88b4-8f0313859043.png)
It looks like when `action='store_true'` the default is False.

So I think you have to pass `share_vocab`

**Comment by JianyuZhan** [comment]
@mataney, ah,  right, sorry I mess up with the `default` arg... Yep, you are right.
