### ISSUE TITLE
Diagnostic error messages in preprocess.

### ISSUE THREAD

**Issue by notnami** [OpenNMT/OpenNMT-py#458]
Hi!

I'm working on something conceptually similar to text summarisation. I have tried to follow the guidelines for training a summarisation model, and I have observed something odd.

My source corpus has ~130k unique tokens. My target corpus contains about 4.5k tokens. I want to limit the source vocab to ~50k, and keep everything from the target corpus. When I run `preprocess.py` without `share_vocab`, this is exactly what happens. However, when I try to use `share_vocab`, I get a shared vocabulary with a strange size of 20843 tokens.

I believe this is too small for my task (the model fails to make useful predictions), and at any rate I don't understand where this vocabulary size comes from. The default for `preprocess` is supposed to be 50k, and even when I pass 50000 manually, it still creates a vocab of those ~20k tokens. Clearly, something happens behind the scenes, that either shouldn't happen, or should be explained better.

I've cursorily looked through the code, but haven't yet found the source of this behaviour. If someone more familiar with the code base knows where it comes from, I would appreciate their help. In the meantime, I'll keep looking myself.

**Comment by notnami** [comment]
Okay, I figured it out. Turns out I failed to increase the limit for truncating sequences. The example for summarisation actually specified it, so it's my fault for missing that. But perhaps, to reduce user error, there can be more diagnostic output in `preprocess.py` specifying that. If needed, I can try to add that.

**Comment by srush** [comment]
Yes, I agree we need these diagnostics. If you send a PR we would happily accept.

**Comment by srush** [comment]
Think we have these now.
