### ISSUE TITLE
AttributeError: 'module' object has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by ljy296566** [OpenNMT/OpenNMT-py#46]
when I try to train the model, 
`python train.py -data data/multi30k.atok.low.train.pt -save_model multi30k_model -gpus 0`
An error occurs.  What should I do ?
`Namespace(batch_size=64, brnn=False, brnn_merge='concat', curriculum=False, data='data/multi30k.atok.low.train.pt', dropout=0.3, epochs=13, extra_shuffle=False, gpus=[0], input_feed=1, layers=2, learning_rate=1.0, learning_rate_decay=0.5, log_interval=50, max_generator_batches=32, max_grad_norm=5, optim='sgd', param_init=0.1, pre_word_vecs_dec=None, pre_word_vecs_enc=None, rnn_size=500, save_model='multi30k_model', start_decay_at=8, start_epoch=1, train_from='', train_from_state_dict='', word_vec_size=500)
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    cuda.set_device(opt.gpus[0])
  File "/home/ljy/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 161, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: 'module' object has no attribute '_cuda_setDevice''
`

**Comment by ShivaliGoel** [comment]
You'll understand once you refer line 121 of train.py (  print("WARNING: You have a CUDA device, should run with -gpus 0") ) 

Try running the following instead:
python train.py -data data/multi30k.atok.low.train.pt -save_model multi30k_model

**Comment by FalconLK** [comment]
Is this issue already fixed?? Still seems like a problem with CUDA.

**Comment by RakhimBek** [comment]
Hi! I get this problem while running:

`onmt_train -config toy_en_de.yaml`

Is there a solution for this?
