### ISSUE TITLE
How to fix the source vocabulary

### ISSUE THREAD

**Issue by lianrzh** [OpenNMT/OpenNMT-py#475]
The argument `-src_vocab` doesn't work when preprocessing the data.  Is it not to be supported now?

**Comment by srush** [comment]
Oh, shoot. We stopped support this when we switched to torchtext. Need to mark deprecated. 

If you are interested, we would be happy to take a PR to add it back. 

The change would be at this line. 
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/io/IO.py#L237

Have an option to instead create a Counter from a file and call this constructor
https://github.com/pytorch/text/blob/master/torchtext/vocab.py#L30

And use this to set `fields["tgt"].vocab` directly.

**Comment by siddsach** [comment]
@srush Seems simple enough! As I understand it, the counter would be constructed from a text file, the path of which would be given an extra argument? If this is the case, should I use the parser from this [script](https://github.com/OpenNMT/OpenNMT-py/blob/b7be116f59ef6074526e1408e141e90dceaab61d/tools/tokenizer.perl) in onmt or from some field object's tokenize attribute?
