### ISSUE TITLE
Question about setting -max_shard_size

### ISSUE THREAD

**Issue by playma** [OpenNMT/OpenNMT-py#483]
@JianyuZhan 

I set `-max_shard_size` to 10485760(1024*1024*10), I expected to get 10M per shard, but I got 39 MB. Why?

Thank you for add this argument to avoid taking up too much memory.

<img width="737" alt="screen shot 2017-12-27 at 8 48 50 am" src="https://user-images.githubusercontent.com/7677470/34367223-ccce8b18-eae2-11e7-9235-9ab9f7bba810.png">

**Comment by JianyuZhan** [comment]
@playma, 

The `max_shard_size` is actually the size of a shard of the corpus file, not the size of the eventually-generated `*pt` file.  We don't have a reliable way to control the generated pt file size. 

The `*pt` file is actually serialized `torchtext.data.Dataset`, which contains list of `torchtext.data.Example` (which consists of processed corpus ) and list of 
`tuple(str, torchtext.data.Field)`.  So this explains why the shard size is 10M, but you eventually got a 39M pt file.

**Comment by playma** [comment]
I am glad to provide the result.
Can I ask how to measure the ratio of saved memory?

**Comment by JianyuZhan** [comment]
We care the really occupied physical memory, thus we measure the RSS(Resident Set Size) metirc.

You can compare with this script.  Fire this script first in one terminal:

```
./rss.sh  1 
```

The argument is the sampling internal  (unit: seconds).

And run the `preprocess.py`, collect the result.

`rss.sh`:
```
 #!/bin/bash

while true; do
    ps aux | grep "python preprocess.py" | grep -v grep | awk '{sum=sum+$6}; END {print sum/1024 " MB"}'
    sleep $1
done
```
