### ISSUE TITLE
Torchtext v0.2

### ISSUE THREAD

**Issue by srush** [OpenNMT/OpenNMT-py#488]
Combining all the torchtext v0.2 issues into one for organization. 

[] https://github.com/OpenNMT/OpenNMT-py/issues/368
[] https://github.com/OpenNMT/OpenNMT-py/issues/354
[] https://github.com/OpenNMT/OpenNMT-py/issues/345

**Comment by jekbradbury** [comment]
I just pushed 0.2.1 to PyPI; release notes are [here](https://github.com/pytorch/text/releases/tag/v0.2.1).
