### ISSUE TITLE
Large memory is needed after one epoch.

### ISSUE THREAD

**Issue by cswhjiang** [OpenNMT/OpenNMT-py#492]
The memory occupied increases after one epoch. It seems that it is a bug. 

I used ``RNNEncoder `` and ``InputFeedRNNDecoder``. Batch size was 32 and the memory increased from 17G to 23G.

**Comment by srush** [comment]
Yes, we think this has to do with the validation set being too large. Try setting `valid_batch_size` to be lower. (This is not a long term solution)
