### ISSUE TITLE
Question of advance each beam in Translator.py

### ISSUE THREAD

**Issue by playma** [OpenNMT/OpenNMT-py#500]
I can not understand it. Can I ask how it works? 

```
            # (c) Advance each beam.
            for j, b in enumerate(beam):
                b.advance(
                    out[:, j],
                    unbottle(attn["std"]).data[:, j, :context_lengths[j]])
                dec_states.beam_update(j, b.get_current_origin(), beam_size)
```

https://github.com/OpenNMT/OpenNMT-py/blob/56ef91f3371a01b7f1437b0c2dbdb7a4431fc1fb/onmt/translate/Translator.py#L153

**Comment by srush** [comment]
Good question. Probably worth looking at Beam.py

https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/Beam.py#L64

We'll add more documentation to that file. It works on each batch individually, takes the score of all the next words (and the attentions) and stores the k-best.

**Comment by playma** [comment]
@srush 

Thank you for your answering. I am still confused. Why do we need to pass attention to beam search?  I thought that Beam search just compute the k-best score of next words and not need to use attention.

**Comment by pltrdy** [comment]
It's indeed use in copy mechanisms, and to replace <unk> tokens, so we keep attention scores during the beam search and only uses it if related options are set (see  https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/Translation.py#L41)

**Comment by playma** [comment]
@pltrdy 

It's very weird. 

1.
I remove argument `-replace_unk`, and get the same result as use `-replace_unk`

2.
I remove argument `-replace_unk`, and replace Models.py#L474 below:

```
tmp = Variable(torch.FloatTensor(attn_char.size()).zero_())
attns["std"] += [tmp]

```

And I got the different result.
It represents that the program still use `attn`  some where

**Comment by playma** [comment]
This is related to #518
