### ISSUE TITLE
Warn users not to use special symbols. 

### ISSUE THREAD

**Issue by abaheti95** [OpenNMT/OpenNMT-py#503]
Hi all,
I have used the following format in my data
```
BOS = '<s>'
EOS = '</s>'
UNK = '<unk>'
```
All of my data is in the following format
`<s> w w w <unk> w <unk> </s>`
where w represents various words. But now when I try to translate the decoder prints </s> multiple times. For example
```
PRED 15: <s> le </s> </s> </s> </s> T30
PRED SCORE: -10.3222
```

How do I explicitly specify these in the parameters? Or if I cannot specify them how should I organize my data in OpenNMT?

https://github.com/OpenNMT/OpenNMT-py/blob/af24c9b58417ce154c86496d37d46e5872b52179/onmt/translate/Beam.py#L18

**Comment by helson73** [comment]
Eos and bos are automatically added to data, you dont need to add them manually.

**Comment by helson73** [comment]
See onmt.io.TextDataset.get_fields and torchtext.data.fields.Fields for detail.

**Comment by abaheti95** [comment]
So why do some predictions have more than one eos symbol?? Is it because of the replace_unk flag??

**Comment by helson73** [comment]
Your symbols are identical to default special symbols used in OPENNMT.
It happened because of following reasons. 
1) torchtext 0.3 adds preprocessing step which decodes all corpus to UNICODE format. 
2) special symbols in OpenNMT are directly passed to field opjects, so they are decoded into UNICODE format.
3) that means, default symbols are not unicode, your special symbols in corpus are unicode. So the system recognize them as distinct symbols. 

Just remove them from corpus, and it will be solved.

**Comment by abaheti95** [comment]
So what should be the format of my data?
No start and end symbol in the data?
For example
`<s> Hi , I am <unk> </s>` to `Hi , I am <unk>` in the data file?

**Comment by helson73** [comment]
You don't need to convert them to any format, tokenized plain text would be fine. Words with frequency rank lower than max_vocab_size will be automatically replaced with <unk>, you don't needed to convert them manually.

**Comment by abaheti95** [comment]
But what if I have preprocessed data from some other application? When I have <unk> marked in my corpus already. How do I specify those <unk> to OpenNMT?

**Comment by helson73** [comment]
They are declared in onmt/io/DatasetBase.py. 
You can change them to uncode format.
But still, your translation result will contains start symbols. 
I suggest do pre-processing again.

**Comment by abaheti95** [comment]
The problem with that is that the data I have is collected by a totally different project so all I have is the preprocessed data. So do I have to change the preprocessing code to enforce OpenNMT to recognize the <unk>s?

**Comment by helson73** [comment]
You can remove start and end symbols from your file by additional pre-processing, and modify the default \<unk> symbol to unicode format, that would be fine.
I think that's quite simple to do.

**Comment by srush** [comment]
Yeah, you should not use <s>, </s>, <unk> in your code. 

We should throw an error when we see them. I will add that to our preprocessing code.
