### ISSUE TITLE
Undefined behavior when  min_length > max_length

### ISSUE THREAD

**Issue by gabrielStanovsky** [OpenNMT/OpenNMT-py#510]
It seems that ```max_length``` takes precedence when conflicting:  ```min_length``` > ```max_length``` (I think that ```min_length```  was recently introduced in #496).
Is that the desired behavior?

I think that this can be confusing when setting ```min_length``` explicitly, while leaving ```max_length``` implicit. For example, setting the ```min_length``` to 150 would result in predictions of length 100, since that's the default ```max_length```.

I think this happens in [this loop](https://github.com/OpenNMT/OpenNMT-py/blob/66e3c180556a5d25dd25824e794879af2ebcdc37/onmt/translate/Translator.py#L114) where ```max_length``` overrides the new #496.

Would you want to raise an exception in such cases?
I could go ahead and submit a PR, if that's the case.

Thanks!

**Comment by srush** [comment]
Interesting. Sure you can send a PR to throw an error. 

`min_length` was meant to prevent a corner case of really short sentence. use at your own risk with forcing long ones (they might be bad).
