### ISSUE TITLE
What kind of python classes can be saved by using torch.save method?

### ISSUE THREAD

**Issue by ZiJianZhao** [OpenNMT/OpenNMT-py#519]
The onmt.io.TextDataset can be saved with torch.save and be loaded with torch.load.
However, the following defined class can be saved but can not be loaded succesfully.
```
import torch
class TT(object):
    def __init__(self):
        self.name = 'tt.txt'
    def __iter__(self):
        with open('tt.txt', 'r') as f:
            line = f.realine()
            yield line
if __name__ == '__main__':
    t = TT()
    torch.save(t, 't.pt')    
```
The error information is as follows:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-610d3b55c8fd> in <module>()
----> 1 torch.load('t.pt')

/home/zjz17/anaconda2/lib/python2.7/site-packages/torch/serialization.pyc in load(f, map_location, pickle_module)
    229         f = open(f, 'rb')
    230     try:
--> 231         return _load(f, map_location, pickle_module)
    232     finally:
    233         if new_fd:

/home/zjz17/anaconda2/lib/python2.7/site-packages/torch/serialization.pyc in _load(f, map_location, pickle_module)
    377     unpickler = pickle_module.Unpickler(f)
    378     unpickler.persistent_load = persistent_load
--> 379     result = unpickler.load()
    380 
    381     deserialized_storage_keys = pickle_module.load(f)

AttributeError: 'module' object has no attribute 'TT'

```
So, what is the mechanism of torch.save and torch.load? What kind of python classes can be processed by the methods.

**Comment by SsnL** [comment]
These methods are pickle based. With pickle, you need to have definitions before loading the data. So you would need the `TT` class def here before loading `t.pt`.

**Comment by ZiJianZhao** [comment]
Thanks for your reply. So why the dataset saved using torch.save method in this project can be loaded without predefining the class. 
https://github.com/OpenNMT/OpenNMT-py/blob/master/train.py#L279

**Comment by SsnL** [comment]
How do you know that it is not defined? When this function is called, the
definition code is likely already executed, either somewhere in this repo
if it’s a custom dataset or in importing if it is defined in a module like
torchtext.

**Comment by srush** [comment]
Not sure I understand this issue. Going to close for now, reopen if it is still a problem.
