### ISSUE TITLE
Special symbols in merged vocab 

### ISSUE THREAD

**Issue by helson73** [OpenNMT/OpenNMT-py#520]
[Source Code](https://github.com/OpenNMT/OpenNMT-py/blob/81d94563870d0b65c8414b576a4e7a44ce5b63b2/onmt/io/IO.py#L90)

\<unk> is missing in the special symbols, 
After merged, itos looks like ['\<blank>', '\<s>', '\</s>' ... ], which has wrong index.

**Comment by srush** [comment]
This is a bug. I think this may have changed in torchtext 0.2.1.
