### ISSUE TITLE
[question] Shards sorting / shuffling

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT-py#522]
@srush @JianyuZhan @helson73 
Guys,
I have a question for both the sharding preprocessing and the batching at training time.

I observed that during an epoch the PPL starts quite high, keeps decreasing and after it's finished it starts again very high.
I think it is due to the fact that the dataset may be sorted in some ways both during preprocess sharding, and also before batching in buckets.

I think buckets of the same length must be shuffled between them so that we do not see this phenomenon of ppl starting high at the beg of each epoch.

**Comment by srush** [comment]
Yes, I agree. We should also be much more explicit about lengths in the debug output as well.

**Comment by helson73** [comment]
I am not familiar with data loading process.
But how it comes to consume so huge memory(dozens of GBs) while the original data size is quite small(~3GB)?

**Comment by JianyuZhan** [comment]
@helson73 the generated `pt` files are actually `torchtext.data.dataset`, which contains `Example`, which consists of the original data, among other things, like loaded library, etc.

**Comment by srush** [comment]
Hmm, having a bit of trouble understanding this issue. Within a shard buckets of the same length are randomly shuffled. i.e. batches will alternate between long and short sentences. 

I guess we don't shuffle before sharding, so if the original data is sorted we don't mix that up. Is that the phenomenon you are describing?

**Comment by vince62s** [comment]
Yes I think this is it.
My Dataset is not sorted but it is the concat of 3 datasets (for WMT14) so they may be each in a similar domain (especially europarl)
So shuffling before sharding should do the job.

**Comment by vince62s** [comment]
@srush 
I have a question regarding the way we fill the token batches.
In T2T/opennmt-tf we first use this bucket_width to sort the data and when we fill the batch we make sure that all sentences are about the same length (at bucket_width max difference).
If we don't do so, maybe the token batch is made of various length sentences and if there is too m uch padding it does take too much memory.
not sure I am clear.

**Comment by vince62s** [comment]
closing this for now:
Sharding is done.
Shuffling needs to be done offline before preprocessing.
Bucketing is now fixed and no more memory issue.
