### ISSUE TITLE
Where are the logs generated?

### ISSUE THREAD

**Issue by hiteshvaidya** [OpenNMT/OpenNMT-py#524]
I am running the PyTorch code for machine translation. I tried the -exp [] command mentioned in [Logging](http://opennmt.net/OpenNMT-py/options/train.html#logging). However, I didn't find any log file being generated anywhere. For your understanding, I entered the following command to run the experiment.
```python train.py -data data/demo -gpuid 2 -word_vec_size 1000 -layers 3 -exp 'exp2' -save_model demo-model```

There is neither any log file named as 'exp2' or any other name including 'log' as a keyword. Could you please tell me where does the log file get stored? and what is the proper way to customize its filename?

**Comment by srush** [comment]
Currently we just output logs to std out. `Exp` is a feature for connecting to an external Crayon/tensorboard server. Happy to add additional logging support if you want to send a PR.

**Comment by srush** [comment]
You can now log to a tensorboardx directory which I recommend.
