### ISSUE TITLE
TypeError collapse_copy_scores() when using 'copy_attn' option

### ISSUE THREAD

**Issue by okayu9** [OpenNMT/OpenNMT-py#525]
When using -copy_attn to train.py, TypeError occurs at translation.

> Traceback (most recent call last):
>   File "translate.py", line 141, in <module>
>     main()
>   File "translate.py", line 105, in main
>     batch_data = translator.translate_batch(batch, data)
>   File "/path/to/OpenNMT-py/onmt/translate/Translator.py", line 151, in translate_batch
>     batch, self.fields["tgt"].vocab)
> TypeError: collapse_copy_scores() missing 1 required positional argument: 'src_vocabs'

The number of arguments do not match.
https://github.com/OpenNMT/OpenNMT-py/blob/7ce758614a92f38af88e00cc987e4690e3f9485a/onmt/io/TextDataset.py#L91-L92
https://github.com/OpenNMT/OpenNMT-py/blob/66e3c180556a5d25dd25824e794879af2ebcdc37/onmt/translate/Translator.py#L149-L151

**Comment by JianyuZhan** [comment]
Please confirm if this patch fixes your problem:

```
diff --git a/onmt/translate/Translator.py b/onmt/translate/Translator.py
index 9516393..92db36f 100644
--- a/onmt/translate/Translator.py
+++ b/onmt/translate/Translator.py
@@ -148,7 +148,8 @@ class Translator(object):
                 # beam x (tgt_vocab + extra_vocab)
                 out = data.collapse_copy_scores(
                     unbottle(out.data),
-                    batch, self.fields["tgt"].vocab)
+                    batch, self.fields["tgt"].vocab,
+                    self.cur_dataset.src_vocabs)
                 # beam x tgt_vocab
                 out = out.log()
 
```

Save it to a file, say `foo.diff`,  put it in the root directory of the project, then `patch -p1 < foo.diff`.

**Comment by srush** [comment]
think this got pushed now.
