### ISSUE TITLE
Pre-trained model throws error during inference.

### ISSUE THREAD

**Issue by LeenaShekhar** [OpenNMT/OpenNMT-py#531]
Hello,

I am using the pre-trained model mentioned in the README file with the current code, but that results in the following error:

python translate.py -model ../demo.rnn__acc_47.64_ppl_20.48_e13.pt -src data/src-test.txt -output pred.txt -replace_unk -verbose

```
Loading model parameters.
Traceback (most recent call last):
  File "translate.py", line 141, in <module>
    main()
  File "translate.py", line 62, in main
    onmt.ModelConstructor.load_test_model(opt, dummy_opt.__dict__)
  File "/home/leena/Downloads/NMT/OpenNMT-py-master/onmt/ModelConstructor.py", line 124, in load_test_model
    use_gpu(opt), checkpoint)
  File "/home/leena/Downloads/NMT/OpenNMT-py-master/onmt/ModelConstructor.py", line 199, in make_base_model
    model.load_state_dict(checkpoint['model'])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 490, in load_state_dict
    .format(name))
```

Could you please provide the latest model? If not, then point me to the correct version?

**Comment by LeenaShekhar** [comment]
After some debugging I figured that the key names in the loaded  checkpoint and the NMT model constructed in the code were different, but the value types were all the same. 

model_params with type: [('decoder.attn.linear_in.weight', <class 'torch.FloatTensor'>), ('decoder.attn.linear_out.weight', <class 'torch.FloatTensor'>), ('decoder.embeddings.make_embedding.emb_luts.0.weight', <class 'torch.FloatTensor'>), ('decoder.rnn.layers.0.bias_hh', <class 'torch.FloatTensor'>), ('decoder.rnn.layers.0.bias_ih', <class 'torch.FloatTensor'>), ('decoder.rnn.layers.0.weight_hh', <class 'torch.FloatTensor'>), ('decoder.rnn.layers.0.weight_ih', <class 'torch.FloatTensor'>), ('decoder.rnn.layers.1.bias_hh', <class 'torch.FloatTensor'>), ('decoder.rnn.layers.1.bias_ih', <class 'torch.FloatTensor'>), ('decoder.rnn.layers.1.weight_hh', <class 'torch.FloatTensor'>), ('decoder.rnn.layers.1.weight_ih', <class 'torch.FloatTensor'>), ('encoder.embeddings.make_embedding.emb_luts.0.weight', <class 'torch.FloatTensor'>), ('encoder.rnn.bias_hh_l0', <class 'torch.FloatTensor'>), ('encoder.rnn.bias_hh_l1', <class 'torch.FloatTensor'>), ('encoder.rnn.bias_ih_l0', <class 'torch.FloatTensor'>), ('encoder.rnn.bias_ih_l1', <class 'torch.FloatTensor'>), ('encoder.rnn.weight_hh_l0', <class 'torch.FloatTensor'>), ('encoder.rnn.weight_hh_l1', <class 'torch.FloatTensor'>), ('encoder.rnn.weight_ih_l0', <class 'torch.FloatTensor'>), ('encoder.rnn.weight_ih_l1', <class 'torch.FloatTensor'>)]
Loading model parameters.


ckpt_paramas with type before: [(u'decoder.attn.linear_in.weight', <class 'torch.FloatTensor'>), (u'decoder.attn.linear_out.weight', <class 'torch.FloatTensor'>), (u'decoder.embeddings.emb_luts.0.weight', <class 'torch.FloatTensor'>), (u'decoder.rnn.layers.0.bias_hh', <class 'torch.FloatTensor'>), (u'decoder.rnn.layers.0.bias_ih', <class 'torch.FloatTensor'>), (u'decoder.rnn.layers.0.weight_hh', <class 'torch.FloatTensor'>), (u'decoder.rnn.layers.0.weight_ih', <class 'torch.FloatTensor'>), (u'decoder.rnn.layers.1.bias_hh', <class 'torch.FloatTensor'>), (u'decoder.rnn.layers.1.bias_ih', <class 'torch.FloatTensor'>), (u'decoder.rnn.layers.1.weight_hh', <class 'torch.FloatTensor'>), (u'decoder.rnn.layers.1.weight_ih', <class 'torch.FloatTensor'>), (u'encoder.embeddings.emb_luts.0.weight', <class 'torch.FloatTensor'>), (u'encoder.rnn.bias_hh_l0', <class 'torch.FloatTensor'>), (u'encoder.rnn.bias_hh_l1', <class 'torch.FloatTensor'>), (u'encoder.rnn.bias_ih_l0', <class 'torch.FloatTensor'>), (u'encoder.rnn.bias_ih_l1', <class 'torch.FloatTensor'>), (u'encoder.rnn.weight_hh_l0', <class 'torch.FloatTensor'>), (u'encoder.rnn.weight_hh_l1', <class 'torch.FloatTensor'>), (u'encoder.rnn.weight_ih_l0', <class 'torch.FloatTensor'>), (u'encoder.rnn.weight_ih_l1', <class 'torch.FloatTensor'>)]

I then just replaced the mis-matched checkpoint key names with the one in the model. After that I Am able to decode the test dataset.

**Comment by srush** [comment]
Thanks. We'll retrain and update.
