### ISSUE TITLE
Support pytorch TensorboardX 

### ISSUE THREAD

**Issue by srush** [OpenNMT/OpenNMT-py#533]
It seems like Crayon is no longer supported. We should switch to using tensorboardX for log viewing. 

https://github.com/lanpa/tensorboard-pytorch

**Comment by Halfish** [comment]
I may be a little confused. Do you mean the project "Crayon" is no longer updated? Or just this project, OpenNMT-py, is favor of another new visualization tool?

**Comment by srush** [comment]
It looks to me like the tool crayon may not be supported going forward. But this new effort to directly support the tensorboard API looks really promising. Potentially will allow us to visualize many aspects of the model, e.g. embeddings/attention as well.

**Comment by srush** [comment]
This works now.
