### ISSUE TITLE
Implement dump beam

### ISSUE THREAD

**Issue by sharonzhou** [OpenNMT/OpenNMT-py#538]
The  `-dump_beam` flag currently outputs a skeletal json object that the translator (Translator.py) was initialized with, instead of the full history (as in the Torch/Lua implementation).

Specifically, this is initialized and stored as `beam_accum` in Translator.py.

This functionality would be very helpful for implementing more complex beam search decoding functions. Thank you!

**Comment by vince62s** [comment]
closing, discussion in #719
