### ISSUE TITLE
Is the program loads all the training data into memory before training? 

### ISSUE THREAD

**Issue by SuperHan777** [OpenNMT/OpenNMT-py#543]
My computer has only 8G memory, but my training data (the train.pt file) is 8.7G. When I ran the train commands (like python train.py -model_type img -data data/im2text/demo -save_model demo-model -gpuid 0 -batch_size 20 -max_grad_norm 20 -learning_rate 0.1) my computer crashed, how can I solve this problem? Thank you

**Comment by JianyuZhan** [comment]
So the generated `train.pt` is too big.  Then you can set `-max_shard_size`(unit: bytes) parameter during `preprocess` stage, which will create multiple smaller `train.pt`s.  

Recommended `-max_shard_size` is multiple of `1MB ( 1024 * 1024 bytes)`.  You can set to `2MB`, or even `4MB`, depending on your corpus size and your quota for memory .

**Comment by SuperHan777** [comment]
My data_type is 'img', it seems like the code does not support to create multiple smaller 'train.pt's when the data_type is 'img' or 'audio', should I write a similar function like 'build_save_text_dataset_in_shards'?

**Comment by SuperHan777** [comment]
Can I just split my 'src-train.txt' and 'tgt-train.txt' files to multiple smaller files like 'src-train_1.txt', 'src-train_2.txt', 'tgt-train_1.txt' and 'tgt-train_2.txt' and then generate train datasets?

**Comment by JianyuZhan** [comment]
@SuperHan777 , well, it is not that simple just implementing a `build_save_img_dataset_in_shards` function.  You can slice the corpus yourself, and generate the train datasets, and make sure they have names in forms of `xxx.train.<digit>.pt`, where <digit> should start from 1.

**Comment by srush** [comment]
oh, I didn't realize we did that for images. @da03 any ideas?

**Comment by da03** [comment]
Hmm I'm afraid we do not support that now. @JianyuZhan's solution might work if we can fix the target vocabulary, otherwise multiple runs of preprocessing might generate different vocabularies.
