### ISSUE TITLE
Wordnet Synets Annotations

### ISSUE THREAD

**Issue by thecortex** [OpenNMT/OpenNMT-py#545]
I have a dataset from wordnet definitions annotated like that:
```
x= precisely_r_01 at this moment_n_01 or the moment_n_01 identify_v_05 ;
y= just_r_06
```
Does OpenNMT correctly parse the annotations or should I do a preprocessing to trim?

**Comment by srush** [comment]
Sorry, I think this is outside the score of OpenNMT. 

We take in tokens of any form and out put tokens of any form. The model doesn't know anything about wordnet or other external resources.
