### ISSUE TITLE
machine crashed down when running the the example of translation using gpu at the 10th epoch

### ISSUE THREAD

**Issue by fayexu** [OpenNMT/OpenNMT-py#561]
RT, when i running the translation example using gpu, when it comes to the 10th or 11th epoch, it always caused my machine crashed down, and my gpu is NVIDIA-SMI P40 with 20 GB of memory .  But when i checked the system logs of the machine, i could not find anything wrong or any clues.  I can not figure out. One reason i guess may be the cooling problem of gpu caused the situation.  Did anybody meets the same problem as above, Is there a way of solving this issue?

**Comment by srush** [comment]
Can you post the full error?
