### ISSUE TITLE
Anybody use multi-gpu for this systerm ?

### ISSUE THREAD

**Issue by KelleyYin** [OpenNMT/OpenNMT-py#562]
This systerm is very faster in only one gpu . However , we want to train the corpus of WMT which will cost too much times. Futhermore , we seek to spend less time for waiting experimental result .

**Comment by srush** [comment]
It's the next thing we plan on working on. We were waiting for some pytorch features.

**Comment by alphadl** [comment]
maybe you can utilize nn.DataParallel function in pytorch v0.3, usage like this torch.nn.DataParallel(net, device_ids=[0, 1, 2]).cuda()

**Comment by srush** [comment]
Yeah, we had that originally, but it didn't give speed improvements. We are coming back to it now.

**Comment by mcjoshi** [comment]
Multi GPU still not working

**Comment by vince62s** [comment]
if you're in a hurry, try this fork:
https://github.com/Ubiqus/OpenNMT-py

**Comment by sbmaruf** [comment]
@vince62s : thank you for the link.
