### ISSUE TITLE
[Query] Regarding acoustic architectures

### ISSUE THREAD

**Issue by saurabhvyas** [OpenNMT/OpenNMT-py#565]
I would like to ask the following questions 

1.) Can I use OpenNMT to train a speech recognition model , based on transformer architecture ?

2.) If my dataset is for a different language say Japanese, How do I generate tokens for my vocabulary?

Can anyone please provide pointers ?

Thanks

**Comment by da03** [comment]
Sorry the current version doesn't support speech recognition with transformer decoder. I'm not sure how to deal with Japanese though.

**Comment by saurabhvyas** [comment]
Oh , well thanks for your reply, I guess Ill close this then.
