### ISSUE TITLE
How to compute GPU memory required from number of parameters

### ISSUE THREAD

**Issue by playma** [OpenNMT/OpenNMT-py#570]
I have the number of parameters information below:

* number of parameters: 494125252
encoder:  482111000
decoder:  12014252

How can I compute GPU memory required based on this information?

**Comment by playma** [comment]
I use `nvidia-smi` to check the memory usage is 8.3 GB.
But how to compute?

**Comment by srush** [comment]
It is actually not the size of the model that impacts memory usage. It is the batch_size and number of layers of the model. You can do a rough back of the envelope calculation by batch_size x max_length x num_layers x layer_size x 8 . You can also reduce `max_generator_batches` to get some more memory.

**Comment by playma** [comment]
@srush 

Is the memory usage related to `src_vocab_size` or `tgt_vocab_size`?
I found that different `src_vocab_size` or `tgt_vocab_size` cause out of memory.
(large `src_vocab_size` or large `tgt_vocab_size`)

Thank you
