### ISSUE TITLE
How to use another model in the Global Scorer in the Beam

### ISSUE THREAD

**Issue by abaheti95** [OpenNMT/OpenNMT-py#572]
Hello all,
I am using OpenNMT-py for reimplementing [this paper](https://arxiv.org/abs/1510.03055). Essentially this work rescores the final N-best list of Beam with a model which is trained on Source given Targets (S|T). I have trained 2 models (T|S) and (S|T) separately and I can get the N-best list from the beam search of (T|S). So my question is how can I use the model (S|T) to get the prediction score of souce|beam_candidates with the Global Scorer provision provided in the beam search.
In that global scorer I want full teacher enforcing and calculate the average softmax scores of the word predictions.

**Comment by srush** [comment]
Awesome idea! 

So I would recommend doing this outside of OpenNMT. Just create an n-best list, and then rerun the other model with -src and -tgt set appropriately. Then parse that file to do your own rescoring. 

Alternatively you could build a new GlobalScorer object, but that would require getting into the python code. I'll post an example ipython notebook that shows how to get started with that.

**Comment by srush** [comment]
Great. Here's the minimal example: 

`import onmt
import onmt.io
import onmt.translate
import onmt.ModelConstructor
from collections import namedtuple

# Load the model.
Opt = namedtuple('Opt', ['model', 'data_type', 'reuse_copy_attn', "gpu"])

opt = Opt("/home/srush/Downloads/model_acc_51.33_ppl_12.74_e20.pt", "text",False, 0)
fields, model, model_opt =         onmt.ModelConstructor.load_test_model(opt,{"reuse_copy_attn":False})

# Test data
data = onmt.io.build_dataset(fields, "text", "/home/srush/data/sum3/valid.article.filter.txt", None, use_filter_pred=False)
data_iter = onmt.io.OrderedIterator(
        dataset=data, device=0,
        batch_size=1, train=False, sort=False,
        sort_within_batch=True, shuffle=False)
# Translator
translator = onmt.translate.Translator(model, fields,
                                           beam_size=5,
                                           n_best=1,
                                           global_scorer=None,
                                           cuda=True)

builder = onmt.translate.TranslationBuilder(
        data, translator.fields,
        1, False, None)

for j, batch in enumerate(data_iter):
        batch_data = translator.translate_batch(batch, data)
        translations = builder.from_batch(batch_data)
        print("src:", " ".join(translations[0].src_raw))
        print()
        print("tgt:", " ".join(translations[0].pred_sents[0]))
`

**Comment by abaheti95** [comment]
Hey @srush ,
I just realized that the "gold_score" calculation is very similar to what I am trying to do, just that the model is different and the src and tgt are swapped. What I really want is the gold score of src given beam output on the (S|T) model. I am guessing a function similar to the one below should be sufficient to solve my problem.
https://github.com/OpenNMT/OpenNMT-py/blob/338b3b1c0103b773c52e47175fe2ce39735705aa/onmt/translate/Translator.py#L187

Kindly correct me if I'm thinking incorrectly.

**Comment by srush** [comment]
Yup! That's what we are calling. You can add that to the code above.

**Comment by srush** [comment]
Let us know how this goes, we could add it as an option later.

**Comment by abaheti95** [comment]
Hello everyone,

I have been trying to replicate a function similar to https://github.com/OpenNMT/OpenNMT-py/blob/338b3b1c0103b773c52e47175fe2ce39735705aa/onmt/translate/Translator.py#L187 for the MMI rescoring (essentially rescoring the beam candidates with another model which is trained on Source given Targets (S|T))

So far I have created a new class as follows
```
class MMIGlobalScorer(object):
    """
    Global scorer which rescores the candidates in beam using the (S|T) model
    ref: http://www.aclweb.org/anthology/N16-1014
    """
    def __init__(self, model, fields, cuda=False):
        self.model = model
        self.fields = fields
        self.src_vocab = self.fields["src"].vocab
        self.tgt_vocab = self.fields["tgt"].vocab
        self.tt = torch.cuda if cuda else torch

    def make_features(self, data):
        levels = [data]
        return torch.cat([level.unsqueeze(2) for level in levels], 2)


    def _run_target(self, tgt_data, src_data, tgt_lengths):
        tgt = self.make_features(tgt_data)
        src_in = self.make_features(src_data)[:-1]
        print "tgt"
        print tgt
        print "tgt_lengths"
        print tgt_lengths
        #  (1) run the encoder on the tgt
        enc_states, memory_bank = self.model.encoder(tgt, tgt_lengths)
        dec_states = \
            self.model.decoder.init_decoder_state(tgt, memory_bank, enc_states)

        #  (2) Compute the 'goldScore'
        #  (i.e. log likelihood) of the source given target under the model (S|T)
        gold_scores = self.tt.FloatTensor(1).fill_(0)
        dec_out, dec_states, attn = self.model.decoder(
            tgt_in, memory_bank, dec_states, memory_lengths=tgt_lengths)

        tgt_pad = self.fields["tgt"].vocab.stoi[onmt.io.PAD_WORD]
        for dec, src in zip(dec_out, src_data[1:]):         # src data is src + bos and eos
            # Log prob of each word.
            out = self.model.generator.forward(dec)
            src = src.unsqueeze(1)
            scores = out.data.gather(1, src)
            scores.masked_fill_(src.eq(tgt_pad), 0)
            gold_scores += scores
        return gold_scores

    def tgt_to_index(self, tgt):
        return [self.tgt_vocab.stoi[word] for word in tgt]

    def src_to_index(self, src):
        return [self.src_vocab.stoi[word] for word in src]
    
    def mmi_score(self, beam, hyp_word):
        # Get the source
        src_list = self.tgt_to_index(beam.source) # beam's source is target here
        print hyp_word
        hyp_list = self.src_to_index(hyp_word)
        # Src list to torch LongTensor 
        src_list.insert(0, beam._bos)
        src_list.append(beam._eos)
        src_data = self.tt.LongTensor(src_list)
        hyp_lengths = self.tt.LongTensor([len(hyp_list) - 1])
        

        hyp = self.tt.LongTensor(hyp_list[:-1])         # Remove EOS from the hyp which is the src to the MMI model
        src_data.unsqueeze_(1)
        hyp.unsqueeze_(1)
        print hyp
        score = self._run_target(hyp, src_data, hyp_lengths)
        print score
        return score
```
Notice I have simply copied the code of `_run_target()` and made some adjustment to fit in my framework. However, I am getting some kind of internal error which I am not able to decipher. The first hypothesis for which the mmi_score is being calculated is `[u'i', u'don', u"'t", u'want', u'to', u'eat', '</s>']` which is saved as as LongTensor in the tgt_data parameter of my `_run_target` function of the `MMIGlobalScorer` class. As you can see from the sample output the arguments to the `enc_states, memory_bank = self.model.encoder(tgt, tgt_lengths)` are as expected yet I am seeing the following error.

```
[u'i', u'don', u"'t", u'want', u'to', u'eat', '</s>']

   4
  33
  13
  63
   7
 404
[torch.LongTensor of size 6x1]

tgt

(0 ,.,.) = 
    4

(1 ,.,.) = 
   33

(2 ,.,.) = 
   13

(3 ,.,.) = 
   63

(4 ,.,.) = 
    7

(5 ,.,.) = 
  404
[torch.LongTensor of size 6x1x1]

tgt_lengths

 6
[torch.LongTensor of size 1]

Traceback (most recent call last):
  File "translate.py", line 153, in <module>
    main()
  File "translate.py", line 113, in main
    batch_data = translator.translate_batch(batch, data)
  File "/home/baheti/OpenNMT-py/onmt/translate/Translator.py", line 186, in translate_batch
    unbottle(attn["std"]).data[:, j, :memory_lengths[j]])
  File "/home/baheti/OpenNMT-py/onmt/translate/Beam.py", line 125, in advance
    global_score = self.global_scorer.mmi_score(self, word_hyp)
  File "/home/baheti/OpenNMT-py/onmt/translate/Beam.py", line 234, in mmi_score
    score = self._run_target(hyp, src_data, hyp_lengths)
  File "/home/baheti/OpenNMT-py/onmt/translate/Beam.py", line 192, in _run_target
    enc_states, memory_bank = self.model.encoder(tgt, tgt_lengths)
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baheti/OpenNMT-py/onmt/Models.py", line 139, in forward
    emb = self.embeddings(src)
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baheti/OpenNMT-py/onmt/modules/Embeddings.py", line 181, in forward
    emb = self.make_embedding(input)
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baheti/OpenNMT-py/onmt/modules/UtilClass.py", line 80, in forward
    outputs = [f(x) for f, x in zip(self, inputs)]
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baheti/.local/lib/python2.7/site-packages/torch/nn/modules/sparse.py", line 103, in forward
    self.scale_grad_by_freq, self.sparse
RuntimeError: save_for_backward can only save input or output tensors, but argument 0 doesn't satisfy this condition
```

Kindly point out my mistake. Am I not noticing something obvious here?

**Comment by srush** [comment]
Is your model a copy_attn model by any chance?

**Comment by srush** [comment]
Short story is the `copy_attn` takes in the attention as well, and the correct alignment. Unfortunately that makes it harder to do tgt scoring. You'll need to implement a few more pieces of code.

**Comment by abaheti95** [comment]
Yes!! @srush The other model was using `copy_attn`. I don't really know what benefit does it give but I have started training another model without it. Thanks for the help :)

**Comment by srush** [comment]
yeah, I would drop that for now. But let's make a separate issue to support it.

**Comment by zhongpeixiang** [comment]
Have you tried to implement the MMI-antilm model? 

`objective function = logp(T|S) − λlogU(T) `, where `U(T)` is a weighted target probability.

**Comment by abaheti95** [comment]
@zhongpeixiang No, I have implemented MMI-bidi model. Even in the paper he mentioned bidi performed better than anti so I chose to implement that. However, I think you can implement anti by using an external Language modeling library.

**Comment by zhongpeixiang** [comment]
@abaheti95 I thought about using an external language model as well, but I'm worried that the language patterns in OpenSubtitles dataset, which I use, may be different from that external language model, and as a result, the probabilities of a given target sentence may be different. 

In this [antilm tf implementation](https://github.com/Marsan-Ma/tf_chatbot_seq2seq_antilm/blob/145e78903b245050c3c31e9a162db8a54e1e91fe/lib/seq2seq_model_utils.py#L130), the author essentially uses the same seq2seq model and feed in empty input sentence (all PAD tokens) and get the probability of target sentence. In this case, he assumes P(T) = P(T|S), where S is all PAD tokens. 

Do you think it's a good idea?

**Comment by srush** [comment]
Yes I think that should be fine to do.

**Comment by rtygbwwwerr** [comment]
@zhongpeixiang I think it might make sense. Using PAD as the initial input of the encoder results in the same initial state of the decoder corresponding different p(T|S). Naturally, the first several output words of the decoder are more influenced by p(T|S) rather than U(T), that is consistent with the original thought of JiweiLi's paper. Commonly, the decoder is considered as a language model, and I think input empty is a simple way to implement anti-MMI without external Model. I hope it could be explicated by the author.

**Comment by vince62s** [comment]
closing this.
@abaheti95 feel free to open a PR either with some code or a Notebook to add in the Library.
