### ISSUE TITLE
Massive CPU memory usage during training

### ISSUE THREAD

**Issue by xforceco** [OpenNMT/OpenNMT-py#573]
I do training on WMT16 task using standard procedure, on GPU.
When I execute `train.py`, the memory usage however for CPU remains  around 37.6GB through out the training process.

Is this normal? If not, how to reduce this?

**Comment by srush** [comment]
This is our fault, we need better documentation. 

You need to run `preprocess.py` with `-max_shard_size`. Otherwise it loads all the data into memory.

**Comment by xforceco** [comment]
I misunderstood that `-max_shard_size` in `preprocess.py` only affects memory usage in preprocess stage.
Now it is great, `train.py` works in reasonable amount of memory now
