### ISSUE TITLE
Dual encoder - Sentence Level features appended in the context with attention.

### ISSUE THREAD

**Issue by abaheti95** [OpenNMT/OpenNMT-py#586]
Dear all,

I am trying to implement a baseline model of ["Topic Aware Neural Response Generation"](https://arxiv.org/pdf/1606.08340.pdf) TA-Seq2Seq-attention. 
Essentially this model feeds a bad of topic words which are similar to the source sentence along with the source sentence which is concatenated in the context along with the RNN attention. For exact details look at the Fig (2) in the paper.
OpenNMT supports word level features at the moment. I was wondering if there is way to add sentence level features with attention? I could then give a one hot vector of topic words as input to the model using which the model will be able to predict the word.

I guess this application is pretty specific to the paper. If this is not possible trivially in OpenNMT can someone direct me to the segment of codes that I would require to update to add such a feature?

**Comment by srush** [comment]
Can you describe a bit more what this would look like as a feature?

**Comment by abaheti95** [comment]
Kindly look at the model image below from the paper: 
![alt text](https://i.imgur.com/ri7jYQY.png "Logo Title Text 1")
Essentially the Encoder Attention is appended with Sentence Level Topic words features. However I think this exact specific model won't be available in OpenNMT.

Can I get do the following instead:
1. Encode the source sentence in encoder 1
2. Encode the topic words (as a sentence) in encoder 2
3. Append both context vectors and send it for decoding?

I saw the feature of multiple Source in the README. If this is possible how to do it?
Worst case scenario I was hoping to give this as the source input
<source-sentence> <special_token> <topic_words> <special_token>
instead of
<source-sentence>

**Comment by srush** [comment]
So unfortunately we don't yet support multiple source encoders. We may in future versions, but for now it would be hard to do this.

**Comment by vince62s** [comment]
@lordeddard 
This is not as easy as in onmt-tf because implementation is not as modualr os onmt-tf.
In a Nutshell you need to build another model with 2 encoders and to have an extra module for the joint attention where you will concat the 2 attention layers.
Again you would really need to understand how it is structured right now to fully see what it encompasses.
If @guillaumekln has a better idea, welcome.

**Comment by Bachstelze** [comment]
In openNMT-tf you can set [parallel](https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/models/multi_source_transformer.py) inputs like the [Dual-Source Transformer for Automatic Post-Editing](https://arxiv.org/pdf/1809.00188.pdf). The architecture seems to be straight forward, but I don't know how the training works.
