### ISSUE TITLE
AttributeError: 'NMTModel' object has no attribute 'items'

### ISSUE THREAD

**Issue by zxybazh** [OpenNMT/OpenNMT-py#59]
When I tried to use the pre-trained model onmt_model_en_de_200k, by
`python translate.py -gpu 0 -model onmt_model_en_de_200k-4783d9c3.pt -src data/multi30k/test.en.atok -tgt data/multi30k/test.de.atok -replace_u
nk -verbose -output multi30k.test.pred.atok`
got the following message:

> Traceback (most recent call last):
  File "translate.py", line 135, in <module>
    main()
  File "translate.py", line 62, in main
    translator = onmt.Translator(opt)
  File "\~/OpenNMT-py/onmt/Translator.py", line 26, in __init__
    model.load_state_dict(checkpoint['model'])
  File "\~/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 328, in load_state_dict
    for name, param in state_dict.items():
  File "\~/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 238, in \__getattr\__
    type(self).\__name\__, name))
AttributeError: 'NMTModel' object has no attribute 'items'

I tried to modify the source code as some warnings appeared:

> SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout' has changed. you can retrieve the original source code by accessing the object's source attribute or set`torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.

but I got same error plus the following message:

> SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout' has changed. Tried to save a patch, but couldn't create a writable file Dropout.patch. Make sure it doesn't exist and your working directory is writable.

**Comment by jongsae** [comment]
I am not using anaconda but I am experiencing the same problem. 
AttributeError: 'NMTModel' object has no attribute 'items'

**Comment by guillaumekln** [comment]
Pre-trained models may not be compatible with the latest version. It is recommended to retrain them.
