### ISSUE TITLE
Plan for minibatching with bucketing

### ISSUE THREAD

**Issue by xforceco** [OpenNMT/OpenNMT-py#590]
I would like to know whether there is a plan for bucketing support in dataset iteration. (Or it has already had?)
Speedup from bucketing is significant and well-known.
And this feature is already supported in torchtext.

Refs:
https://github.com/pytorch/text
https://github.com/pytorch/text/blob/master/torchtext/data/iterator.py

**Comment by srush** [comment]
Yup, we do this. We bucket by length on source. 

We think we can make it better though, there are some changes in the works to bucket better on the target side without breaking CUDNN. We should have that in the code shortly.

**Comment by xforceco** [comment]
I see. I ask since I saw the matrices on target side having many paddings.
