### ISSUE TITLE
Any other way to tackle data input?

### ISSUE THREAD

**Issue by getao** [OpenNMT/OpenNMT-py#596]
Hello.

I wonder if there is another way for data input if the input is not just a source and a target sentence. I know that token-level features can be added as extra information. But what if sentence-level features? Is there any way to add sentence-level features?

**Comment by srush** [comment]
Could you just add the sentence feature as a feature to each source? Or alternatively have it be a special token append or prepended.

**Comment by getao** [comment]
Thanks.
