### ISSUE TITLE
beam search outputs the same result many times

### ISSUE THREAD

**Issue by ryeak47** [OpenNMT/OpenNMT-py#60]
Here, I use beam search, and set beam_size and n_best both to 50, but the result shows that the same result outputs many times. I don't know why. Is it because of beam search itself or I do something wrong ?

**Comment by ryeak47** [comment]
It seems that beam search not always ends with 'EOS' symbol, but when output the translated sentence, beam search remove the last item as taken it 'EOS'.

**Comment by guillaumekln** [comment]
Most likely there is an issue with beam search which allows equal hypotheses.

For the `EOS` this could indeed be an issue when using `n_best`. Otherwise, `EOS` is the end condition for the beam search.

**Comment by bowenliu16** [comment]
I was wondering if there was a fix to this issue? I'm trying to compare the beam search with that of the google seq2seq model. However with OpenNMT-py, the majority of the n-best hypotheses are the same, although with different scores
