### ISSUE TITLE
Question: Beam search during training

### ISSUE THREAD

**Issue by xforceco** [OpenNMT/OpenNMT-py#601]
I would like to do a beam search similar to https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/Beam.py during training.

Therefore, I implement a beam search on `scores` in `_compute_loss` in `Loss.py`.
However, my version of beam search produces very poor quality translation, even using checkpoint on running on testset, when compared to the usual translations from `translate.py`

Any ideas?

My `_compute_loss` looks like this

```python
def _compute_loss(self, batch, output, target):
  scores = self.generator(self._bottle(output))
  loss=0.0
  base=0
  beam=10
  temp=target.t()
  for s in temp:
    q=[(1.0,[-1])]
    print(s)
    for i,t in enumerate(s):
      if t.data[0]==1:
        break
      else:
        q2=[]
        tk,ti=torch.topk(scores[base+i],beam)
        for j in q:
          for t1,t2 in zip(tk,ti):
            if j[1][-1]!=3:
              q2.append((j[0]+t1,j[1]+[t2.data[0]]))
          if j[1][-1]==3:
            q2.append(j)
        q=sorted(q2,reverse=True,key=lambda x: x[0].data[0])[:beam]
    print(q)
    base+=temp.shape[1]
       ....
```

I use `-max_generator_batch 999` to bypass the shard processing.

**Comment by xforceco** [comment]
My silly mistake, I have wrong understanding on `scores`

**Comment by srush** [comment]
Hi, 

You shouldn't have to write your own beam search. If you want to do this you can use the onmt.Translator object directly.

Or are you backpropagating through beam search? In which case, cool :)

**Comment by xforceco** [comment]
Yes, I shall make a PR after I have tested and confirmed everything working.
