### ISSUE TITLE
Need repeatable perplexity values during training

### ISSUE THREAD

**Issue by ratishsp** [OpenNMT/OpenNMT-py#605]
Hi,  
I am on the latest commit of OpenNMT-py.
I executed the below commands for training a demo model:
```
python preprocess.py -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo
python train.py -data data/demo -save_model demo-model -gpuid 2
```

The first run shows trace as:
Epoch  1,    50/  157; acc:   3.72; ppl: 201523.01; xent:  12.21; 8886 src tok/s; 8769 tgt tok/s;      9 s elapsed
Epoch  1,   100/  157; acc:   4.34; ppl: 11935.47; xent:   9.39; 9443 src tok/s; 9443 tgt tok/s;     16 s elapsed
Epoch  1,   150/  157; acc:   4.67; ppl: 4262.92; xent:   8.36; 8174 src tok/s; 8218 tgt tok/s;     24 s elapsed

I reran and now the trace is:
Epoch  1,    50/  157; acc:   4.02; ppl: 277314.92; xent:  12.53; 9379 src tok/s; 9325 tgt tok/s;      8 s elapsed
Epoch  1,   100/  157; acc:   3.68; ppl: 39765.60; xent:  10.59; 11140 src tok/s; 11076 tgt tok/s;     14 s elapsed
Epoch  1,   150/  157; acc:   4.73; ppl: 7326.26; xent:   8.90; 10071 src tok/s; 9991 tgt tok/s;     21 s elapsed

I haven't changed the default seed.
Ideally, the runs should show repeatable perplexity values. 

Thanks,
Ratish

**Comment by sebastianGehrmann** [comment]
You can run the training with a fixed seed with the `-seed` option.

**Comment by ratishsp** [comment]
Thanks @sebastianGehrmann 
`-seed` option works. 
Incidentally, I had earlier tried the `-seed` option with value as 0. And now I saw the code: 
```
if opt.seed > 0:
    random.seed(opt.seed)
    torch.manual_seed(opt.seed)
```
You may close the issue.
