### ISSUE TITLE
[Bug] embeddings_to_torch encounters error when reading glove.840B.300d.txt file

### ISSUE THREAD

**Issue by howardyclo** [OpenNMT/OpenNMT-py#608]
Hello, I suggest that at line: https://github.com/OpenNMT/OpenNMT-py/blob/master/tools/embeddings_to_torch.py#L47-L48

should be fixed to something like this (add try-except):
```
def get_embeddings(file):
    embs = dict()
    missing_count = 0
    
    for l in open(file, 'rb').readlines():
        l_split = l.decode('utf8').strip().split()
        if len(l_split) == 2:
            continue
        try:
            embs[l_split[0]] = [float(em) for em in l_split[1:]]
        except: missing_count += 1
            
    print("Got {} embeddings from {} (missing: {})".format(len(embs), file, missing_count))
    
    return embs
```

Since some elements in l_split[1:] are probably strings (maybe it's a bug for the original embedding file) instead of floating numbers.

If it's okay, I'll send a pull request for this.

**Comment by vince62s** [comment]
@pltrdy is this ok ?

**Comment by pltrdy** [comment]
I cannot reproduce this issue. We should not not ignore any exception like this. 

Please try to get insight on the problem e.g. count lines while iterating and print the erroneous one.
This issue may be closed until we have more information.
