### ISSUE TITLE
'invalid device ordinal' error when gpuid is 1

### ISSUE THREAD

**Issue by Henry-E** [OpenNMT/OpenNMT-py#609]
Has anyone else run into this error before 

```THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=87 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "/home/henrye/downloads/OpenNMT-py/train.py", line 54, in <module>
    cuda.set_device(opt.gpuid[0])
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/cuda/__init__.py", line 162, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:87
```

This happens when running a command with `-gpuid 1`. The same command with `-gpuid 0` causes no issues. Maybe it's something to do with how OpenNMT is doing multiple gpu training but I haven't been able to figure it. I've tried on different nodes and the same error appears.

![screen shot 2018-03-17 at 11 10 13](https://user-images.githubusercontent.com/12613144/37554696-5533860e-29d4-11e8-8f76-44d1de37664d.png)

**Comment by srush** [comment]
The issue might be the CUDA_VISIBLE_DEVICES on your machine.

**Comment by Henry-E** [comment]
After a bit more investigation it is something to do with CUDA_VISIBLE_DEVICES. 

When `CUDA_VISIBLE_DEVICES=0,1` and `-gpuid 1` it runs fine. But when `CUDA_VISIBLE_DEVICES=1` and `-gpuid 1` it breaks.

Our cluster has the option to assign a single GPU in a node and we use CUDA_VISIBLE_DEVICES to know which GPU has been assigned. 

Is this a problem with the cluster or OpenNMT?

**Comment by srush** [comment]
This is not a problem it is the expected behavior. When CUDA_VISIBLE_DEVICES=1 then gpuid 0 is a pointer to GPU=1.

**Comment by Henry-E** [comment]
Great, I can see the logic behind that but definitely not totally obvious

**Comment by Henry-E** [comment]
@srush 

https://github.com/OpenNMT/OpenNMT-py/blob/3bd519070ad3b092dc081d2e72d0cd129bd085c7/opts.py#L462-L463

This is an option for the translate command.

Since this variable is called `gpu` and not `gpuid` I'm guessing I would be correct in using the gpu number that CUDA_VISIBLE_DEVICES returns, rather than the gpuid of 0?

-----

I was going to ask this but I had a look through the code and the same code is used in both. So the gpu option still works the same as gpuid.
