### ISSUE TITLE
[Bug] AttributeError occurs when asserting torchtext's Vocab object with None in embeddings_to_torch.py 

### ISSUE THREAD

**Issue by howardyclo** [OpenNMT/OpenNMT-py#610]
When I execute this script, the error occurs:
```
Traceback (most recent call last):
  File "tools/embeddings_to_torch.py", line 129, in <module>
    main()
  File "tools/embeddings_to_torch.py", line 92, in main
    enc_vocab, dec_vocab = get_vocabs(opt.dict_file)
  File "tools/embeddings_to_torch.py", line 24, in get_vocabs
    assert None not in [enc_vocab, dec_vocab]
  File "/home/nlplab/howard/.conda/envs/cedl2017/lib/python3.6/site-packages/torchtext/vocab.py", line 78, in __eq__
    if self.freqs != other.freqs:
AttributeError: 'NoneType' object has no attribute 'freqs'
```

The error is come from this line: https://github.com/OpenNMT/OpenNMT-py/blob/master/tools/embeddings_to_torch.py#L24
where `torchtext.vocab.Vocab` has defined a `==` operation in it, which assumes the comparing variable is also the type of  `torchtext.vocab.Vocab`, but we are comparing the `torchtext.vocab.Vocab` with `None` here.

So, I think we should modify this line into:
```
assert type(None) not in [type(enc_vocab), type(dec_vocab)]
```

If it's acceptable, I'll happy to send PR here.

**Comment by halflkaka** [comment]
I met the same problem! How do you resolve it?

**Comment by vince62s** [comment]
@pltrdy can I close this ?
