### ISSUE TITLE
Dynamic Feature Loading

### ISSUE THREAD

**Issue by xiadingZ** [OpenNMT/OpenNMT-py#618]
I have a large dataset, features file produced by preprocess.py is larger than 100G. It takes too large to load, can I load feature from disk when it should be used, instead of loading them all in memory first?

**Comment by JianyuZhan** [comment]
You can set `-max_shard_size` during preprocssing, which will avoid the big file issue.  You can set it to 1MB, 2MB, or other optimal values you are satisfied with.  And we now do load them on demand during training.

**Comment by xiadingZ** [comment]
my data_type is not text. It seems I have to write this function by my self

**Comment by srush** [comment]
Unfortunately we do not have this yet. We are hoping that this issue in torchtext will get us there 

https://github.com/pytorch/text/issues/140

**Comment by haquynh1505** [comment]
Hi guys,
I don't know if any progress is being made here so far? 
I have the same problem while my data type is not text. I am doing a demo on a subset of the dataset which is pretty large already:
train.pt - 23G
valid.pt - 885M

I monitor the memory usage, but I am not quite sure what is happening. If you have the idea, please enlighten me!
At the first epoch, I see that the memory occupation is first added up by 25G after loading the first dataset (first_dataset = next(lazily_load_dataset("train"))) I understand that from here the whole train.pt file is loaded into the memory. And it stays there constantly? But then I see that when make_dataset_iter is called, DatasetLazyIter added 23G more to the memory usage. Here I get confused, it seems like it generates all the batches, and stores them all in the memory? I thought that it yields the each batch on the fly? 
And the weirdest thing I see is while generating batches at epoch 2, DatasetLazyIter added 22G more to the memory usage. At epoch 3, 4, and so on, DatasetLazyIter still added some amount to the memory usage, but it's so much lighter. 

I am not quite sure what I am describing is clear enough to you guys. If it is, please give me some explanation of what is going on at the first and the second epoch, that make the memory occupation grows horribly? 

Thanks so much in advanced!
