### ISSUE TITLE
Save Attention Scores

### ISSUE THREAD

**Issue by nikhilweee** [OpenNMT/OpenNMT-py#623]
Similar to https://github.com/OpenNMT/OpenNMT/pull/363, how can I visualize attention scores?

**Comment by nikhilweee** [comment]
https://github.com/OpenNMT/OpenNMT-py/blob/068b1636344f5ac2972013e96761e18f1147aff4/translate.py#L132

After digging up a bit, I found out that `trans.attns` has the attention scores. Anyway, is this a good feature to implement considering it's already present in the Lua version?

**Comment by srush** [comment]
Yes, great idea. I am meaning to post a notebook that you can use to get all this information out.
