### ISSUE TITLE
Query regarding difference in copy attention implementation from See et al

### ISSUE THREAD

**Issue by ratishsp** [OpenNMT/OpenNMT-py#627]
Hi,
The current copy attention implementation in OpenNMT-py has `p_copy = F.sigmoid(self.linear_copy(hidden))`
But in See et al, `p_copy = sigmoid(W_1^T hidden +W_2^T source_context +..)`
Did we experiment with having source context in `p_copy` definition of OpenNMT-py?
Thanks.

**Comment by sebastianGehrmann** [comment]
Yes, I experimented with it. The more complex computation slows down the training quite a bit for only a little gain. if you want to try, check out my branch `pgen_calc`.
