### ISSUE TITLE
Feature splitting with "￨" or "|" ?

### ISSUE THREAD

**Issue by ratishsp** [OpenNMT/OpenNMT-py#634]
Hi,
The current pipe delimiter used in https://github.com/OpenNMT/OpenNMT-py/blob/5cd11faf2eb9dfa617d8e065dedcaf061b36b0a3/onmt/io/DatasetBase.py#L61 seems to be incorrect. And it doesn't split the fields for me. I am not sure if it is issue specifically with my input. But when I use the pipe symbol on my machine, it works fine.
Thanks.

**Comment by srush** [comment]
Sorry what's the question? We use the unicode symbol "￨" not the standard pipe "|".

**Comment by ratishsp** [comment]
Thanks @srush for the detail. I thought it was the pipe symbol to be used. You may reject the corresponding pull request too.

**Comment by arvidzt** [comment]
Can somebody tell me what does the feature here mean？
can i use some numerical feature here divided by  "|" ?

**Comment by eduamf** [comment]
You can use letter, number etc. 

For instance, if you use tools/tokenize.lua, from OpenNMT project, or the pyonmttok library (https://github.com/OpenNMT/Tokenizer/tree/master/bindings/python), you'll be able to use the "case_feature" option. The word "Capital" will become "capital|C", while "capital" will become "CAPITAL|U".
