### ISSUE TITLE
Export model to ONNX 

### ISSUE THREAD

**Issue by Fred-Erik** [OpenNMT/OpenNMT-py#638]
Is it possible to export a model trained in OpenNMT-py to a ONNX-protobuf file? I tried [following this  Pytorch tutorial](http://pytorch.org/docs/master/onnx.html), and after reading about [some issues](https://github.com/pytorch/pytorch/issues/5234) with ONNX and RNNs I compiled Pytorch master from source. I now get this error:

`ValueError: Auto nesting doesn't know how to process an input object of type onmt.Models.RNNDecoderState. Accepted types: Variables, or lists/tuples of them`

I first load a trained model using
`fields, model, model_opt = onmt.ModelConstructor.load_test_model(opt, dummy_opt.__dict__)`
then create a dummy input using the `get_batch_image` function from test_models.py

```
def get_batch_image(tgt_l=3, bsize=1, h=15, w=17):
        test_src = Variable(torch.ones(bsize, 3, h, w)).float()
        test_tgt = Variable(torch.ones(tgt_l, bsize, 1)).long()
        test_length = torch.ones(bsize).fill_(136).long() # default None value gave error
        return test_src, test_tgt, test_length
```
and run the exporter with
`torch.onnx.export(loaded_model, (test_src, test_tgt, test_length), "im2text_kenteken.proto", verbose=True)`

**Comment by srush** [comment]
Unfortunately I do not think that ONNX support RNNs at all yet :(

Let us know when they get that functionality.

**Comment by Fred-Erik** [comment]
Good news! The [release log for pytorch 0.4](https://github.com/pytorch/pytorch/releases/tag/v0.4.0) states:
ONNX Improvements: RNN support

[Operater specification](https://github.com/onnx/onnx/blob/master/docs/Operators.md#RNN) on ONNX github

**Comment by vince62s** [comment]
see #1023 
Onnx export compatibility requires some preliminary work:
- remove "object" like DecoderState which is done by this PR
- change the way attentions flow, currently a dictionary but this does not work, requires list or tuple
- some other changes for unsupported operators

**Comment by vince62s** [comment]
As of now, just to export the transformer encoder, we need pytorch to support following operators:
expand_as
masked_fill
Then we need to change the way attention is returned from the decoder:
onnx does not accept a dict, we'll need to use a tuple or simply tensors.
to be continued.

**Comment by 520jefferson** [comment]
@vince62s 
i want to export pytorch model to onnx model like this (MT task using transformer):
def main(opt):
    dummy_parser = configargparse.ArgumentParser(description='train.py')
    opts.model_opts(dummy_parser)
    dummy_opt = dummy_parser.parse_known_args([])[0]
    load_test_model = onmt.decoders.ensemble.load_test_model \
        if len(opt.models) > 1 else onmt.model_builder.load_test_model
    fields, model, model_opt = load_test_model(opt, dummy_opt.__dict__)
    m = torch.load("model-transformer_step_120000.pt")
    x = Variable(torch.from_numpy(numpy.random((9,1,1))))
    y = Variable(torch.random(9,1,1))
    torch.onnx._export(model,(x,y,None), "Trans", export_params=True)
 
after i run the codes ,then  i got this:
TypeError: 'module' object is not callable

it seems the  encoder and decoder  are not one and the same.

**Comment by vince62s** [comment]
with the current code it won't work.
also if you want to try some preliminary steps, you need to export separately the encoder, the decoder and the generator.
but again given some code structure and onnx requirements it won't work with the attention being a tuple.

**Comment by 520jefferson** [comment]
@vince62s 
you said change the way attentions flow, currently a dictionary but this does not work, requires list or tuple
(https://github.com/OpenNMT/OpenNMT-py/issues/638#issuecomment-434765232), 
but now you said but again given some code structure and onnx requirements it won't work with the attention being a tuple.
i'm a little confused after contrasting the two statements above.

**Comment by vince62s** [comment]
I mixed up my comment sorry.

**Comment by 520jefferson** [comment]
@vince62s 
ONNX itself is native to pytorch 1.0 as the model output format, may the output be the format of ONNX ?

**Comment by vince62s** [comment]
it is not as simple as this. there are several levels of complexity:
1) we need to use only operations that are onnx compatible. Until recently some operations like expand_as, masked_fill were not exportable.
2) there might be some requirements to add in the code to activate the onnx trace. I have not tested this, but it might require some changes.
3) the transformer architecture work on a time step basis which would require to still code some stuff so that tensorrt can work with it. (it being the decoder export and the encoder export)
There might be some workaround (cf what fairseq did) but I have not tested it.

**Comment by gvskalyan** [comment]
@vince62s Any update on this?

**Comment by guillaumekln** [comment]
Maybe this needs to be reviewed again, as several PyTorch (and ONNX) versions were released in the meantime.

If it is still difficult to represent the full graph in ONNX, we could export the encoder and one decoder step separately. Then I will be interested in gluing everything together in CTranslate2. https://github.com/OpenNMT/CTranslate2/issues/5

**Comment by vince62s** [comment]
less and less trendy. Pytorch 2.0 might help to get a compiled and speedy version.
