### ISSUE TITLE
Question: transfer learning

### ISSUE THREAD

**Issue by yapingzhao** [OpenNMT/OpenNMT-py#644]
Dear developer,

I am newbie of openmnt-py. The library is very helpful for me. And I have some questions.
I want to apply a transfer learning strategy in neural machine translation.
1. First, translate models using large-scale parallel corpus training. but, How can I get model parameter weight?
2. Then, how do I transfer the weights of the parameters to the new translation framework (openmnt-py)?

Looking forward to your advice or answers.
Best regards,

yapingzhao

**Comment by yapingzhao** [comment]
Thank you for your quick response! 
I appreciate your kind help!

**Comment by Zhw098** [comment]
> Dear developer,
> 
> I am newbie of openmnt-py. The library is very helpful for me. And I have some questions. I want to apply a transfer learning strategy in neural machine translation.
> 
> 1. First, translate models using large-scale parallel corpus training. but, How can I get model parameter weight?
> 2. Then, how do I transfer the weights of the parameters to the new translation framework (openmnt-py)?
> 
> Looking forward to your advice or answers. Best regards,
> 
> yapingzhao

Hi，I also encountered the same problem, what method did you choose at that time？Thank you!
