### ISSUE TITLE
Loss stats incorrect in case of copy attention with copy_loss_by_seqlength?

### ISSUE THREAD

**Issue by ratishsp** [OpenNMT/OpenNMT-py#645]
Hi,
I was going through the code in CopyGenerator.py
https://github.com/OpenNMT/OpenNMT-py/blob/3bd519070ad3b092dc081d2e72d0cd129bd085c7/onmt/modules/CopyGenerator.py#L204-L216

The stats is computed and later the loss is further normalized by seqlength for the option `-copy_loss_by_seqlength`. I think the stats should be computed after the loss normalization.
Thanks.

**Comment by srush** [comment]
@sebastianGehrmann Is this you?

**Comment by sebastianGehrmann** [comment]
Yes, I kept stats as before to not break the computation of Perplexity in the stats module.
