### ISSUE TITLE
copy_loss_by_seqlength option handles truncated bptt?

### ISSUE THREAD

**Issue by ratishsp** [OpenNMT/OpenNMT-py#648]
Hi,
I was going through the code in CopyGenerator.py. I see that with copy_loss_by_seqlength option, the loss is normalized by the length of the target sequence.
https://github.com/OpenNMT/OpenNMT-py/blob/3bd519070ad3b092dc081d2e72d0cd129bd085c7/onmt/modules/CopyGenerator.py#L210-L214
In this, the length is the total length of the target. In case of truncated bptt, should the length be the truncated length?
Thanks.

**Comment by ratishsp** [comment]
I think you should compute length of `target` and not `batch.tgt` and `target` is 
https://github.com/OpenNMT/OpenNMT-py/blob/3bd519070ad3b092dc081d2e72d0cd129bd085c7/onmt/modules/CopyGenerator.py#L167

**Comment by vince62s** [comment]
clsoing, lack of activity. reopen if needed.
