### ISSUE TITLE
Error during decoding in Summarization

### ISSUE THREAD

**Issue by LeenaShekhar** [OpenNMT/OpenNMT-py#651]
I encountered the following error while decoding using a pre-trained model. I am trying to debug it so an help is appreciated. 

Command for decoding:

<code>
python translate.py -batch_size 1 \
                    -beam_size 5 \
                    -model ../model/ada6_bridge_oldcopy_tagged_acc_54.17_ppl_11.17_e20.pt \
                    -src ../cnndm/train.txt.src. \
                    -output ../testout/cnndm.train.output.txt \
                    -min_length 35 \
                    -stepwise_penalty \
                    -coverage_penalty summary \
                    -beta 5 \
                    -length_penalty wu \
                    -alpha 0.9 \
                    -ignore_when_blocking "." "</t>" "<t>" \
                    -n_best 5 
</code>

Traceback (most recent call last):
  File "translate.py", line 167, in <module>
    main()
  File "translate.py", line 116, in main
    for batch in data_iter:
  File "/usr/local/lib/python2.7/dist-packages/torchtext/data/iterator.py", line 180, in __iter__
    self.train)
  File "/usr/local/lib/python2.7/dist-packages/torchtext/data/batch.py", line 22, in __init__
    setattr(self, name, field.process(batch, device=device, train=train))
  File "/usr/local/lib/python2.7/dist-packages/torchtext/data/field.py", line 187, in process
    tensor = self.numericalize(padded, device=device, train=train)
  File "/usr/local/lib/python2.7/dist-packages/torchtext/data/field.py", line 309, in numericalize
    arr = self.tensor_type(arr)

P.S: The line numbers will not match the latest source code as I have a few extra print statements added to my local code. There is no other changes though.

**Comment by LeenaShekhar** [comment]
This seems to be fixed after I removed a newline from the train file. Not sure if it was introduced by mistake by me or was present already. I hope it helps others if they encounter a similar issue.

**Comment by LeenaShekhar** [comment]
Actually there are more than 1 sample in the training dataset. I am wondering if during training such empty articles were removed or not? 

Ideally they should be. During decoding these are not neglected, but i Am yet to check the training pipeline.

**Comment by sebastianGehrmann** [comment]
During training, empty samples are not removed.

**Comment by LeenaShekhar** [comment]
I do not think this should be a problem as such, but might be better to remove them. There are 114 in total just FYI. Feel free to close this issue if you want to.

**Comment by LeenaShekhar** [comment]
Makes sense though I thought see et, all 2017 do get rid of these samples, but I might be wrong. 
Thank you for the clarification.
