### ISSUE TITLE
ambiguous documentation: -share_embeddings option of train.py require shared dictionary

### ISSUE THREAD

**Issue by ttpro1995** [OpenNMT/OpenNMT-py#652]
In documentation [train.py](http://opennmt.net/OpenNMT-py/options/train.html), it said 

`
-share_embeddings [] Share the word embeddings between encoder and decoder. Need to use shared dictionary for this option.`

What is  "shared dictionary" ? Did you mean `-share_vocab` in [preprocess.py](http://opennmt.net/OpenNMT-py/options/preprocess.html)

**Comment by ratishsp** [comment]
Yes, `-share_embeddings` requires `-share_vocab` during preprocess. Agree that the documentation need to be updated to reflect it more clearly. 
Though the error message is helpful: https://github.com/OpenNMT/OpenNMT-py/blob/3bd519070ad3b092dc081d2e72d0cd129bd085c7/onmt/ModelConstructor.py#L179-L180
