### ISSUE TITLE
How to feed a single sentence (str) into model to get single output at runtime? 

### ISSUE THREAD

**Issue by ttpro1995** [OpenNMT/OpenNMT-py#653]
I would like to make application that use pretrained model. However, how can I load the model and feed single string (not whole file) to get single output ?

**Comment by ProHanziiee** [comment]
You can create a txt file under data directory with the sentence which you want to translate. 
For example, you typed "How to translate my sentence." in example.txt. 
Afterwards, execute follow command like in tutorial:
$ python translate.py -model demo-model_acc_XX.XX_ppl_XXX.XX_eX.pt -src data/**sample.txt** -output pred.txt -replace_unk -verbose

**Comment by aleSuglia** [comment]
Is it not possible to create a wrapper that easily allows to complete this task?

**Comment by yashkumaratri** [comment]
> You can create a txt file under data directory with the sentence which you want to translate.
> For example, you typed "How to translate my sentence." in example.txt.
> Afterwards, execute follow command like in tutorial:
> $ python translate.py -model demo-model_acc_XX.XX_ppl_XXX.XX_eX.pt -src data/**sample.txt** -output pred.txt -replace_unk -verbose

This is giving me 

RuntimeError: invalid argument 1: cannot perform reduction function max on tensor with no elements because the operation does not have an identity at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:370

both on cpu as well as gpu.

**Comment by kobzaond** [comment]
> 
> 
> @aleSuglia you can use my wrapper
> 
> ```
> from util import zopts
> import argparse
> import torch
> import onmt
> import onmt.ModelConstructor
> import time
> import uuid
> import os
> 
> from util import preprocess, postprocess
> 
> 
> 
> parser = argparse.ArgumentParser(
>     description='translator.py',
>     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
> # zopts.add_md_help_argument(parser)
> zopts.translator_opts(parser)
> 
> opt = parser.parse_args()
> 
> 
> 
> class Translator:
>     def __init__(self, model_dir=None):
>         """
>         load opts and model
>         :param model_dir director to .pt model
>         """
> 
>         if model_dir:
>             opt.model = model_dir
>         dummy_parser = argparse.ArgumentParser(description='translator.py')
>         zopts.model_opts(dummy_parser)
>         dummy_opt = dummy_parser.parse_known_args([])[0]
> 
>         opt.cuda = opt.gpu > -1
>         if opt.cuda:
>             torch.cuda.set_device(opt.gpu)
> 
>         # Load the model.
>         fields, model, model_opt = \
>             onmt.ModelConstructor.load_test_model(opt, dummy_opt.__dict__)
>         self.fields = fields
>         self.model = model
> 
>     def _create_tmp_file(self, text):
>         """create temp file"""
>         fname = str(uuid.uuid1())+".txt"
>         mfile = open(fname, 'w')
>         mfile.write(text)
>         mfile.close()
>         return fname
> 
>     def _delete_tmp_file(self, fname):
>         """
>         remove temp file create by _create_tmp_file
>         :param fname: file path
>         :return:
>         """
>         try:
>             os.remove(fname)
>         except OSError as e:
>             print("cannot remove tmp file")
>             print(e)
>             pass
> 
>     def _translate(self, text):
>         """
>         Take input
>         Forward to model
>         Return output
>         :param text: string
>         :return: string of result from model
>         """
>         model = self.model
>         fields = self.fields
> 
>         # set number of thread -> reduce CPU load (on shared server)
>         if opt.gpu == -1:
>             torch.set_num_threads(2)
>             print("num threads ", torch.get_num_threads())
> 
>         try:
> 
>             # create tmp file contained text
>             src_file = self._create_tmp_file(text)
> 
>             # Test data
>             data = onmt.io.build_dataset(fields, opt.data_type,
>                                          src_file, None,
>                                          use_filter_pred=False)
> 
>             # Sort batch by decreasing lengths of sentence required by pytorch.
>             # sort=False means "Use dataset's sortkey instead of iterator's".
>             data_iter = onmt.io.OrderedIterator(
>                 dataset=data, device=opt.gpu,
>                 batch_size=opt.batch_size, train=False, sort=False,
>                 sort_within_batch=True, shuffle=False)
> 
>             scorer = onmt.translate.GNMTGlobalScorer(opt.alpha,
>                                                      opt.beta,
>                                                      opt.coverage_penalty,
>                                                      opt.length_penalty)
> 
>             onmt_translator = onmt.translate.Translator(
>                 model, fields,
>                 beam_size=opt.beam_size,
>                 n_best=opt.n_best,
>                 max_length=opt.max_length,
>                 cuda=opt.cuda,
>                 global_scorer=scorer,
>                 beam_trace=opt.dump_beam != "",
>                 min_length=opt.min_length,
>                 stepwise_penalty=opt.stepwise_penalty,
>                 block_ngram_repeat=opt.block_ngram_repeat,
>                 ignore_when_blocking=opt.ignore_when_blocking)
> 
>             builder = onmt.translate.TranslationBuilder(
>                 data, onmt_translator.fields,
>                 opt.n_best, opt.replace_unk, None)
>             output_pred = []
>             for batch in data_iter:
>                 batch_data = onmt_translator.translate_batch(batch, data)
>                 translations = builder.from_batch(batch_data)
> 
>                 for trans in translations:
>                     n_best_preds = [" ".join(pred)
>                                     for pred in trans.pred_sents[:opt.n_best]]
>             output_pred.append(n_best_preds)
> 
>             # delete tmp file
>             self._delete_tmp_file(src_file)
> 
>         except Exception as e:
> 
>             # delete tmp file
>             self._delete_tmp_file(src_file)
>             return str(e)
> 
> 
>         return output_pred[0][0]
> 
>     def process(self, text):
>         """
>         replace number, url with _num_, _url_
>         forward through OpenNMT-py
>         replace _num_, _url_ with original
>         :param text:
>         :return:
>         """
>         if len(text.strip()) == 0:
>             return ""
>         text, _num_list, _url_list = preprocess(text)
>         # replace number, url with _num_, _url_
>         text = self._translate(text)
>         text = postprocess(text, _num_list, _url_list)
>         return text
> ```

Where to get the "util" package? - I'm getting error:     from util import zopts
ModuleNotFoundError: No module named 'util'

**Comment by elyase** [comment]
Try this:
```
from onmt.translate.translator import build_translator
from argparse import Namespace
import sentencepiece as spm

tokenizer = spm.SentencePieceProcessor()
tokenizer.Load('openmnt/sentencepiece.model')
opt = Namespace(models=['openmnt/averaged-10-epoch.pt'], n_best=1, alpha=0.0, batch_type='sents', beam_size=5, beta=-0.0, block_ngram_repeat=0, coverage_penalty='none', data_type='text', dump_beam='', fp32=False, gpu=-1, ignore_when_blocking=[], length_penalty='none', max_length=100, max_sent_length=None, min_length=0, output='/dev/null', phrase_table='', random_sampling_temp=1.0, random_sampling_topk=1, ratio=-0.0, replace_unk=False, report_align=False, report_time=False, seed=829, stepwise_penalty=False, tgt=None, verbose=False)
translator = build_translator(opt, report_score=False)

sentence = 'it works!'
tokens = tokenizer.EncodeAsPieces(sentence)
sentence = " ".join(tokens)
translated = translator.translate([sentence], batch_size=1)
detokenized = translated[1][0][0].replace('▁', '')
print(detokenized)
```
