### ISSUE TITLE
what different between -share_decoder_embeddings  vs share_embeddings ?

### ISSUE THREAD

**Issue by ttpro1995** [OpenNMT/OpenNMT-py#664]
What is the different between `-share_embeddings` and -share_decoder `_embeddings ` in `train.py`

As I understand, `-share_embedding` use same embedding matrix for both input and output language. It is helpful if you translate same language (ENG to ENG) with same vocabulary list. 

But what `-share_decoder_embeddings` does ?

**Comment by pltrdy** [comment]
Your understanding of `-share_embedding` is correct.

`-share_decoder_embeddings` is meant to use the output embedding matrix into the generator. The idea is to use semantic information from the embedding in the output projection that is used for the prediction.
source: https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/ModelConstructor.py#L195

**Comment by srush** [comment]
Looks like the docs are fixed now. Closing.

**Comment by eduamf** [comment]
The link https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/ModelConstructor.py doesn't exist.

**Comment by vince62s** [comment]
it's https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/model_builder.py
now
