### ISSUE TITLE
Does StdRNNDecoder  really reproduce "Neural Machine Translation By Jointly Learning To Align and Translate"[Bahdanau2015]

### ISSUE THREAD

**Issue by ZiJianZhao** [OpenNMT/OpenNMT-py#668]
In https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L354 ,
it says that the StdRNNDecoder class implements the structure of  "Neural Machine Translation By Jointly Learning To Align and Translate"[Bahdanau2015].
However, the decoder in that paper calculates the attention inside the gru operation at each time step. But in the implementation https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L388-L406,
it first runs the forward pass of the RNN and then calculates the attention. I think that it is incompatible with the structure of the original paper.

Thanks for your reply in advance.

**Comment by da03** [comment]
Hmm I think the implementation is based on a variant of the attention mechanism by Luong et all, "Effective Approaches to Attention-based Neural Machine Translation".

**Comment by ZiJianZhao** [comment]
I think so. So I think that the comment is misleading.

**Comment by SkyAndCloud** [comment]
Well, I agree with you @ZiJianZhao . I think it may need some fix or we may provide a standard rnnsearch implement @srush

**Comment by sebastianGehrmann** [comment]
The way attention is computed is similar to the cited paper. The order in which we implement the operations performs better, therefore we did exactly replicate the paper.

**Comment by da03** [comment]
Luong's formulation looks more clear to me, and with input feeding on (which is the default option) the attended context vector is also fed to RNN cells. I'm not sure if we currently have a plan to implement Bahdanau attention, but pull requests are welcome (Different decoder types can be added in onmt/Models.py).

**Comment by srush** [comment]
Our default model is based on Luoung and is the Input Feeding model. We will provide the parameter settings to replicate Bahdanau exactly (although this is often worse).

**Comment by ZiJianZhao** [comment]
OK! Thank you.

**Comment by SkyAndCloud** [comment]
Is there a vanilla groundhog(from [Neural Machine Translation By Jointly Learning To Align and Translate"[Bahdanau2015]](https://arxiv.org/abs/1409.0473)) pytorch implementation on github?

**Comment by ZiJianZhao** [comment]
Sorry, I dont't know. @SkyAndCloud 

And I have a question for @srush and @sebastianGehrmann , could tell the reference paper or research showing that the implemented structure performs better than that in the original paper.

**Comment by arijitx** [comment]
StdRNNDecoder basically never uses the attention for RNN computation, basically it computes the attention after the RNN forward so what is the point of calculating attention ?? It is just an encoder decoder without attention. Is my thinking correct?
