### ISSUE TITLE
30GB+ of RAM usage training Transformer model

### ISSUE THREAD

**Issue by Rabrg** [OpenNMT/OpenNMT-py#669]
When training a Transformer model with [these parameters](http://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-the-transformer-model) and the pretrained embeddings from the [downloadable pretrained transformer model](http://opennmt.net/Models-py/), training utilizes 11GB/12GB memory on my Titan X, and 36GB/64GB of my RAM.

Is this intended? The GPU memory is expectable, but the RAM usage seems abnormal to me.

**Comment by sebastianGehrmann** [comment]
You can use sharding during preprocessing to reduce the RAM usage. (set `max_shard_size` to 10,000,000 for example for ~10MB shards).

**Comment by Rabrg** [comment]
Thanks, setting -max_shard_size to 10485760 makes my training use twenty times less RAM.
