### ISSUE TITLE
limit number of cpu core in translate.py

### ISSUE THREAD

**Issue by ttpro1995** [OpenNMT/OpenNMT-py#673]
How to limit the number of cpu (not GPU but CPU) core to use in translate.py 
it would be helpful when I deploy OpenNMT-py as service on shared server.

**Comment by srush** [comment]
There is an option `torch.set_num_threads(n)` Can you send a pull request where you adding that as an option to translate.py?

**Comment by guillaumekln** [comment]
You can set the environment variable `OMP_NUM_THREADS`, e.g.:

```bash
OMP_NUM_THREADS=2 python translate.py [...]
```

to only translate using 2 threads.
