### ISSUE TITLE
Where to find large data-set for training?

### ISSUE THREAD

**Issue by ProHanziiee** [OpenNMT/OpenNMT-py#675]
Hi, everybody:
  I've test the translation model(English to German). Because the official data-set is too small, so the translation is terrible! I want to download a large scale data-set, maybe hundreds GB, it's any free data-set?

**Comment by srush** [comment]
This is a good starting place https://nlp.stanford.edu/projects/nmt/

**Comment by Sothan** [comment]
Could you provide me a link to download these data due to I can't download in https://nlp.stanford.edu/projects/nmt/

**Comment by he1ght** [comment]
You can download wmt download set...
In translate task
