### ISSUE TITLE
MAC OSX issue: sed: 1: "tokenizer.perl": undefined label 'okenizer.perl'

### ISSUE THREAD

**Issue by ShivaliGoel** [OpenNMT/OpenNMT-py#68]
When running sed -i "s/$RealBin\/..\/share\/nonbreaking_prefixes//" tokenizer.perl mac users might get an error sed: 1: "tokenizer.perl": undefined label 'okenizer.perl'

Resolved it by:

sed -i '.bak' "s/$RealBin\/..\/share\/nonbreaking_prefixes//" tokenizer.perl

**Comment by Deepblue129** [comment]
Updating this answer:
`sed -i '.bak' "s/$RealBin\/..\/share\/nonbreaking_prefixes//" tokenizer.perl`

Need to escape the / otherwise you get `sed: 1: "s//../share/nonbreaking ...": bad flag in substitute command: 's'`

**Comment by Deepblue129** [comment]
Adding a reference to why you may need to use '.bak': https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux

**Comment by eeric** [comment]
make OpenNMT project audio list and sentences text list, as following:
https://github.com/eeric/OpenNMT-py-make-tgt-train.txt/blob/master/openNMT_make_label.py
