### ISSUE TITLE
No attribute _input_size.

### ISSUE THREAD

**Issue by jerinphilip** [OpenNMT/OpenNMT-py#681]
```
  File "/home/jerin/code/machine-translation/ilmt/scripts/onmt/dataset.py", line 44, in <module>
    hidden_size=100, dropout=0)
  File "/home/jerin/.local/lib/python3.5/site-packages/OpenNMT_py-0.1-py3.5.egg/onmt/Models.py", line 255, in __init__
    input_size=self._input_size,
  File "/home/jerin/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 398, in __getattr__
    type(self).__name__, name))
AttributeError: 'InputFeedRNNDecoder' object has no attribute '_input_size'
```

I checked in source as well. self._input_size is getting called without defining.

Relevant section:
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L238L265

**Comment by jerinphilip** [comment]
Never mind, found `@property` later. Can you place an assert like how it's done in EncoderBase just to ensure this raises?

**Comment by addisonklinke** [comment]
@jerinphilip Can you explain how the `@property` tag is supposed to work here? I am getting the same error when trying to initialize a decoder

```
from onmt.decoders.decoder import StdRNNDecoder
decoder = StdRNNDecoder(rnn_type='LSTM', bidirectional_encoder=True, num_layers=1, hidden_size=64)
```

The above code results in 

```
AttributeError: 'StdRNNDecoder' object has no attribute '_input_size'
```

Which is raised from the [`__init__`](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/decoder.py#L102) of `RNNDecoderBase`. If I remove the `@property` tag of the subclass and use a callable at line 102 (i.e. `self._input_size()`), then it works

**Comment by sangwook236** [comment]
I got a similar error : 

> AttributeError: 'InputFeedRNNDecoder' object has no attribute '_input_size'

At this time, I created a decoder as shown below.
`decoder = onmt.decoders.InputFeedRNNDecoder(
	rnn_type=decoder_rnn_type, bidirectional_encoder=bidirectional_encoder, num_layers=decoder_num_layers,
	hidden_size=decoder_hidden_size, attn_type='general', attn_func='softmax',
	coverage_attn=False, context_gate=None,
	copy_attn=False, dropout=decoder_dropout, embeddings=None,
	reuse_copy_attn=False, copy_attn_type='general'
)
`

I couldn't know why the error occurred for a few hours.
And I happened to find a situation where no errors occurred.

At this time, I just added embeddings to create the decoder.
`decoder = onmt.decoders.InputFeedRNNDecoder(
	rnn_type=decoder_rnn_type, bidirectional_encoder=bidirectional_encoder, num_layers=decoder_num_layers,
	hidden_size=decoder_hidden_size, attn_type='general', attn_func='softmax',
	coverage_attn=False, context_gate=None,
	copy_attn=False, dropout=decoder_dropout, embeddings=embeddings,
	reuse_copy_attn=False, copy_attn_type='general'
)
`

So far, I still haven't found the cause, but the problem has been solved.
