### ISSUE TITLE
How to disable word embedding features?

### ISSUE THREAD

**Issue by SkyAndCloud** [OpenNMT/OpenNMT-py#689]
Hi, I noticed that there was word embedding features introduced in `onmt/modules/Embeddings.py`(see [doc](http://opennmt.net/OpenNMT-py/options/train.html)), which was proposed in `Linguistic Input Features Improve Neural Machine Translation`, but I dont't want to use these features not shown in luong's paper, how could I disable these features?
Thanks!

**Comment by SkyAndCloud** [comment]
@srush Please give me some advice, thanks!

**Comment by srush** [comment]
These are not on by default. You have to explicitly give them in your training data (e.g. "word|feat1 ... "). If you don't have them everything is just normal.

**Comment by SkyAndCloud** [comment]
Thanks!
