### ISSUE TITLE
Need a confirmation on the result with default dataset

### ISSUE THREAD

**Issue by FalconLK** [OpenNMT/OpenNMT-py#695]
I have a question as a beginner :)

I've tried the preprocessing, training, and translation with default dataset.

It seems like the result file (pred.txt) repeat "Es ist nicht ." or "Das ist sich in den Kommission ." almost all the time if I use the latest model. When I use some other models, I get some sentences that makes no sense after comparison with the "src-text.txt".

1. How to decide the best model that I have to use to translate among 13 results (in this case epoch was 13)? 
2. Could you please let me know how to improve the performance (to get better result) ?

Thank you very much in advance.

**Comment by srush** [comment]
This dataset is much too small to actually get real numbers. If you are looking for a small dataset we recommend IWSLT.
