### ISSUE TITLE
How to provide additional dense vector features to each token in source?

### ISSUE THREAD

**Issue by frankxu2004** [OpenNMT/OpenNMT-py#697]
One of the greatest features in this framework is that one can provide additional features to each token. However, I am wondering if I have real-valued vectors of some dimension associated with each token, how could it be incorporated? One quick but inelegant method is to create a large lookup table using embedding module, and assign an id to each vector, and follow the route of processing discrete features. But that would take a large amount of memory. Any pointer to which part of the framework should I incorporate this into?

**Comment by vince62s** [comment]
@jsenellart didn't you do something similar in the Lua framework for Audio ? I might be mistaken though.

**Comment by guillaumekln** [comment]
This feature is implemented in both the Torch and TensorFlow version.
