### ISSUE TITLE
Is there any early stopping module or options?

### ISSUE THREAD

**Issue by FalconLK** [OpenNMT/OpenNMT-py#698]
For my training, after like 10 epochs it just produces the same scores for acc and ppl. I've been finding early stop but haven't found yet.

**Comment by antoniovilarinholopes** [comment]
I made a pull request to support early stopping after each epoch and a specific number of batches, it's under review currently.

**Comment by FalconLK** [comment]
Great to hear that! :) Have a peaceful weekend.

**Comment by srush** [comment]
Sorry, I've had a busy couple weeks. We will get this in soon.

**Comment by vince62s** [comment]
discussion to be continued in #813
