### ISSUE TITLE
Save model on iter (i.e: multiple save per epoch)

### ISSUE THREAD

**Issue by ttpro1995** [OpenNMT/OpenNMT-py#708]
Currently, train.py save 1 model per epoch.

However, as I have a lot of data, one epoch may take long time to train. The training process may failed before it finish 1 epoch (accidentally pull off the power cog)  
Thus, I want to have multiple save per epoch. (after x% dataset, or after n iter)

**Comment by vince62s** [comment]
check -save_checkpoint_steps option
