### ISSUE TITLE
Could someone please explain me the idea behind using sharding while computing the loss?

### ISSUE THREAD

**Issue by LeenaShekhar** [OpenNMT/OpenNMT-py#710]
I have read the code, but idea of sharding while computing is not very clear to me. Could someone please explain it to me or point me to some document? Is it related to multi-GPU or for a single GPU as well?

Reason: I have written a model by myself and keep getting the following error when I run it on the GPU. I was wondering if I could use sharding to fix it (lowering the batch size to 16 works but not for 32 or 64 for my model and max_seq_len is 50). I want to run my model only on 1 GPU. 

RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/generic/THCStorage.cu:58

Thank you. 

Update:

I think I sort of get the idea: Even when batch_size is say 16, shard loss is basically there to calculate loss for say 32 tokens in parallel rather than 16 * max_len_tokens. This is to reduce memory footprint. Am I correct?

**Comment by ibulu** [comment]
I would also appreciate an explanation of or a reference for the method

**Comment by da03** [comment]
Hmm in my understanding, sharding is breaking total loss (which is a sum over individual target token losses) into multiple chunks of max_shard_size (say if the target length is 16, and max_shard_size is 8, then we have 2 chunks of size 8). Setting it would help reduce the memory footprint. In addition to that, I think you can also consider using -accum_count to a larger value lambda and set batch size to batch_size_desired/lambda, which means we accumulate gradients until lambda batches and update parameters, which is equivalent to using a larger batch size, but at a slower speed. (e.g., if we have -accum_count to be 2 and -batch_size to be 6, then the effective batch size is 2*6=12.)

**Comment by LeenaShekhar** [comment]
Thank you @da03. That's what I thought. I am wondering it this would solve my GPU OOM issue.

**Comment by LeenaShekhar** [comment]
It seems like it helps in getting rid of OOM issue. I will close this thread. Thank you all.
