### ISSUE TITLE
Transformer runs out of memory when reducing number of layers

### ISSUE THREAD

**Issue by nelson-liu** [OpenNMT/OpenNMT-py#715]
Seems similar to https://github.com/OpenNMT/OpenNMT-py/issues/241 .

I'm trying to train the transformer exactly as specified in the [FAQ](http://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-the-transformer-model), but I want to reduce the number of layers to 4. However, doing so gives me a GPU out of memory error (despite 6 working just fine). This is on the latest master, and I've tried running the code on a GTX 1080Ti, a Titan X (Pascal), and a Tesla V100 --- each gives me an out of memory error.

Any idea what could be going on? Thanks in advance!

**Comment by Embedding** [comment]
I have the same problem. I use the default setting recommended in FAQ, but encounter the following RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58
My GPU is 1080ti.

**Comment by vince62s** [comment]
if you reproduce, open a new issue based on master.
