### ISSUE TITLE
More pre-trained data

### ISSUE THREAD

**Issue by djKooks** [OpenNMT/OpenNMT-py#72]
Hope this is not a dumb question.
Is there some way to get pre-trained data for other language? I'm interested in contributing on other language(such as Korean or Japanese), but cannot find it. Do I need to make it myself, or there is some way to create it?

Thanks.

**Comment by shuoyangd** [comment]
[This](https://sites.google.com/site/rmyeid/projects/polyglot) might be a good place to start with.

**Comment by djKooks** [comment]
@shuoyangd Thanks! I'll look on it.

**Comment by eeric** [comment]
make OpenNMT project audio list and sentences text list, as following:
https://github.com/eeric/OpenNMT-py-make-tgt-train.txt/blob/master/openNMT_make_label.py
