### ISSUE TITLE
Program crashes if there is an empty line in the vocabulary

### ISSUE THREAD

**Issue by ziorufus** [OpenNMT/OpenNMT-py#723]
When preprocessing, the program crashes if the vocabulary file contains an empty line (or a line containing only one space, as happened to me).

The error is:

```
Traceback (most recent call last):
  File "preprocess.py", line 195, in <module>
    main()
  File "preprocess.py", line 188, in main
    build_save_vocab(train_dataset_files, fields, opt)
  File "preprocess.py", line 165, in build_save_vocab
    opt.tgt_words_min_frequency)
  File "/kore-ns-groups/dh/aprosio/simp/OpenNMT-py-master/onmt/io/IO.py", line 265, in build_vocab
    word = line.strip().split()[0]
```

The problem can be solved with a minor code insertion.
In both lines 262 and 273 in [IO.py](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/io/IO.py) this code should be added:

```
if not line.strip():
    continue
```

I think that this can be included in the next version.

**Comment by devinbostIL** [comment]
Perhaps there's a way that this problem can be solved in a way that also resolves issues with empty lines during the translation step, as I mentioned here: https://github.com/OpenNMT/OpenNMT-py/issues/743

**Comment by da03** [comment]
Thanks for reporting! Will fix.
