### ISSUE TITLE
translate.py fails on pytorch 0.4 on models trained with bug 403 patching

### ISSUE THREAD

**Issue by David-Levinthal** [OpenNMT/OpenNMT-py#725]
The patching discussed in 403 may not be adequate and this bug report irrelevant but making the 3 sets of changes in 403 produces a code base that does successfully run models with hidden size = embedding size =1024 to completion (13 epochs), producing *.pt files and validation accuracy ~ 60%
python train.py -data data/deen -save_model deen_model/deen-model -report_every 100 -batch_size 128 -layers 4 -rnn_size 1024 -word_vec_size 1024 -encoder_type brnn -gpuid 0 > wmt_deen_V100_brnn_1024.log 2>&1

but when I try to run translate.py using the resulting model
python translate.py -gpu 0 -model deen_model/deen-model_acc_65.80_ppl_5.49_e13.pt -src data/src-val.txt -tgt data/tgt-val.txt -replace_unk -verbose -output deen_model/val_test.txt >  translate_1024_brnn.log 2>&1
the run fails with the following error
tail -f translate_1024_brnn.log
/usr/local/lib/python2.7/dist-packages/torchtext/data/field.py:322: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  return Variable(arr, volatile=not train)
/usr/local/lib/python2.7/dist-packages/torchtext/data/field.py:321: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  return Variable(arr, volatile=not train), lengths
Loading model parameters.
('average src size', 26, 2167)
/home/levinth/OpenNMT-py/onmt/translate/Translator.py:254: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  def var(a): return Variable(a, volatile=True)
/home/levinth/OpenNMT-py/onmt/Models.py:665: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  for e in self._all]
Traceback (most recent call last):
  File "translate.py", line 29, in <module>
    main(opt)
  File "translate.py", line 18, in main
    opt.batch_size, opt.attn_debug)
  File "/home/levinth/OpenNMT-py/onmt/translate/Translator.py", line 159, in translate
    batch_data = self.translate_batch(batch, data)
  File "/home/levinth/OpenNMT-py/onmt/translate/Translator.py", line 339, in translate_batch
    ret["gold_score"] = self._run_target(batch, data)
  File "/home/levinth/OpenNMT-py/onmt/translate/Translator.py", line 388, in _run_target
    gold_scores += scores
RuntimeError: expand(torch.cuda.FloatTensor{[30, 1]}, size=[30]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

**Comment by da03** [comment]
Hi David, sorry for the delay. We just updated our code to work with PyTorch 0.4. Can you pull and try again?

**Comment by David-Levinthal** [comment]
Does this include fixes for both training and inference?
and yes I will make a new pull once I am in the office tomorrow

d

**Comment by da03** [comment]
Yep both training and inference shall work now. Please let us know if there are any issues, thanks!

**Comment by David-Levinthal** [comment]
I am wondering if there is an issue running with python3
I built pytorch (from source) with python3
if I invoke the demo preprocessor with python 3 then I get
mlperf@zt-gpu-lin2:~/OpenNMT-py$ python3 preprocess.py -train_src
data/src-train.txt -train_tgt data/tgt-train.txt -valid_src
data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip._internal import main
ImportError: No module named _internal
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip._internal import main
ImportError: No module named _internal

does this come from here?
~/OpenNMT-py$ grep pip onmt/*/*.py
onmt/modules/SRU.py:            subprocess.check_output('pip freeze |
findstr cupy', shell=True)
onmt/modules/SRU.py:            subprocess.check_output('pip freeze |
findstr pynvrtc',
onmt/modules/SRU.py:            subprocess.check_output('pip freeze | grep
-w cupy', shell=True)
onmt/modules/SRU.py:            subprocess.check_output('pip freeze | grep
-w pynvrtc',
Same pip business shows up in training...
~/OpenNMT-py$ python3 train.py -data data/demo -save_model demo-model
-gpuid 1 > demo.log 2>&1
but the demo does seem to run fine on a gpu
[2018-06-13 15:00:14,998 INFO] Epoch  4,    50/  157; acc:  10.74; ppl:
1188.08; xent:   7.08;  9249 src tok/s; 8836 tgt tok/s;      8 s elapsed
[2018-06-13 15:00:23,519 INFO] Epoch  4,   100/  157; acc:  12.24; ppl:
1030.65; xent:   6.94;  8738 src tok/s; 8236 tgt tok/s;     17 s elapsed
P100 with Cuda9.1 Cudnn7.1.2 and nccl 2.1.2

**Comment by da03** [comment]
@David-Levinthal Hmm I think the problem is about `pip`: can you try `pip -V` and see if there's the same error message? And indeed this is an issue of OpenNMT that it calls pip no matter if SRU is being used or not, which we'll fix, but a simple workaround would be just commenting all `subprocess.check_output` lines in `onmt/modules/SRU.py`

**Comment by David-Levinthal** [comment]
the python3 env on this machine requires one to use pip3 or things get a
bit odd
the python env can use pip.
if that check is desired it might be good to do it another way
