### ISSUE TITLE
coverage summary

### ISSUE THREAD

**Issue by mataney** [OpenNMT/OpenNMT-py#729]
Hey guys, how are you?

I noticed this penalty a few days ago. 
https://github.com/OpenNMT/OpenNMT-py/blob/0ecec8b4c16fdec7d8ce2646a0ea47ab6535d308/onmt/translate/Penalties.py#L45

It's very cool.. I'm not familiar with this penalty.
Is this a new idea, who should one cite in case of using this?

Matan.

**Comment by rbommasanimozilla** [comment]
If I recall correctly, the coverage penalty is taken from here: https://arxiv.org/abs/1609.08144
This is distinct but related to the coverage loss + coverage input used here: https://arxiv.org/abs/1704.04368
