### ISSUE TITLE
[interesting] repeating phrases in the output

### ISSUE THREAD

**Issue by pinzhenliao** [OpenNMT/OpenNMT-py#734]
Hi, I meet some very interesting errors:  repeating phrases in the output.  

I wonder if anyone gets any clue why we have this kind of error, and whether we have any ways to avoid such issue, please. My guessing is that it's a prediction loop? (it seems that is usually followed by it, then it is usually followed by seems that, then we get a loop?) 

Many thanks

-----
Here is an example (the weir part is highlighted).
In grammatical error correction task:

Input: However I feel that at the moment there should emerge more grups to control this development because the industrial polution that it has been created and it seems that its very little what has been done at the moment in relation to our embiroment .

Output: However I feel that at the moment there should spend more necessary to control this development because the industrial pollution that it has been created and **_it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems that it seems_**

Ground Truth: However , I feel that at the moment there should emerge more groups to control this development because of the industrial pollution that  has been created and it seems that it 's very little , what is being done at the moment in relation to our environment .

**Comment by da03** [comment]
Hmm that seems to be a common issue of neural machine translation, maybe attention coverage penalty (try `-beta 5` during inference?) will alleviate this, but adding more data would most likely to help.
