### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by rahular** [OpenNMT/OpenNMT-py#735]
I am trying to build a simple network and train it by following this tutorial: http://opennmt.net/OpenNMT-py/Library.html

But I am getting this error:
```
ValueError                                Traceback (most recent call last)
<ipython-input-4-513b7ee0d962> in <module>()
      1 optim = onmt.Optim(method="sgd", lr=1, max_grad_norm=2)
----> 2 optim.set_parameters(model.parameters())

/Users/rahul/code/OpenNMT-py/onmt/Optim.py in set_parameters(self, params)
     70         self.params = []
     71         self.sparse_params = []
---> 72         for k, p in params:
     73             if p.requires_grad:
     74                 if self.method != 'sparseadam' or "embed" not in k:

ValueError: too many values to unpack (expected 2)
```

when I execute `optim.set_parameters(model.parameters())`

**Comment by pltrdy** [comment]
Indeed.

Use instead: `optim.set_parameters(model.named_parameters())`.

**Comment by rahular** [comment]
@pltrdy thanks for your quick reply. That solved the problem, but I ran into couple of others.

Running `data = torch.load("../../data/data.train.pt")` gave me an error saying `FileNotFoundError: [Errno 2] No such file or directory: '../../data/data.train.pt'`. When I went into the data directory, I saw that the pre-processed file is named `data.train.1.pt` and not `data.train.pt`. A simple fix.

But, I was not able to solve the below problem.
Running `trainer.train(epoch, report_func)` gives me the following error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-10-2a4f8612446d> in <module>()
      7 
      8 for epoch in range(2):
----> 9     trainer.train(epoch, report_func)
     10     val_stats = trainer.validate()
     11 

/Users/rahul/code/OpenNMT-py/onmt/Trainer.py in train(self, train_iter, epoch, report_func)
    153         try:
    154             add_on = 0
--> 155             if len(train_iter) % self.grad_accum_count > 0:
    156                 add_on += 1
    157             num_batches = len(train_iter) / self.grad_accum_count + add_on

TypeError: object of type 'int' has no len()
```

**Comment by pltrdy** [comment]
It seems that you are passing `epoch` as the first parameter when it should be `train_iter`.

**Comment by rahular** [comment]
Then it says this:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-14-2a4f8612446d> in <module>()
      7 
      8 for epoch in range(2):
----> 9     trainer.train(epoch, report_func)
     10     val_stats = trainer.validate()
     11 

/Users/rahul/code/OpenNMT-py/onmt/Trainer.py in train(self, train_iter, epoch, report_func)
    153         try:
    154             add_on = 0
--> 155             if len(train_iter) % self.grad_accum_count > 0:
    156                 add_on += 1
    157             num_batches = len(train_iter) / self.grad_accum_count + add_on

TypeError: object of type 'int' has no len()
```

Therefore, I changed the arguments to adhere to [this](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Trainer.py#L137) function.

**Comment by pltrdy** [comment]
Your code is still `trainer.train(epoch, report_func)`, it should be `train(train_iter, epoch, report_func)` where `train_iter` is an iterator over the training batches.
