### ISSUE TITLE
About the performance of conv2conv

### ISSUE THREAD

**Issue by zhezhaoa** [OpenNMT/OpenNMT-py#739]
First of all, thank you for this great project. 
I conduct a series of seq2seq experiments using conv2conv. The results are pretty low. Could you provide recommended hyper-parameter settings for conv2conv? 
I also suspect something important goes wrong in the implementation of conv2conv. Conv2conv is even slower than rnn2rnn in this implementation. While in facebook's paper, conv2conv is 9X faster than rnn2rnn

**Comment by vince62s** [comment]
I think that @wjbianjason was the initial contributor of this code, but it was originally for speech.

I have worked on a multi-gpu / pytorch 0.4 version and tried a bit conv2conv.

I agree results are not good out of the box but when looking at the fairseq config it seems that you need a huge network (20 layers for encoder and same for decoder)
trying this right now. (but yes, it is not as fast as fairseq)

**Comment by vince62s** [comment]
closing this, I leave open #845
