### ISSUE TITLE
the example in Quickstart failed on pytorch 0.4

### ISSUE THREAD

**Issue by liangbright** [OpenNMT/OpenNMT-py#740]
train.py -data data/demo -save_model demo-model

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

**Comment by tulongthienvu** [comment]
To run on pytorch 0.4, you must fix some errors because the lib hasn't been migrated to pytorch 0.4. I think if you are new, you should use pytorch 0.3.1 first.

**Comment by da03** [comment]
Hi all, sorry for the delay, but we just updated our code to support pytorch 0.4.

**Comment by da03** [comment]
Closing this for now, please let us know if the current code doesn't work.
