### ISSUE TITLE
How does beam_update work, and what is it doing? 

### ISSUE THREAD

**Issue by paninifrancesco** [OpenNMT/OpenNMT-py#742]
Hi I'm currently working on my Master Thesis, and in particular I'm using this model to improve the beam search process. I'm new in Machine-Learning and even more so in RNN, so sorry for the silly questions...

1. How many dec_states do we have for iteration? I've got that we use the "repeat_beam_size_times" function to expand them times the beam width, but since we have batches of 30 sentences, will we have dec_state x beam_width x bath_size?

2. At the end of 
```python
# (c) Advance each beam.
            for j, b in enumerate(beam):
                b.advance(out[:, j],
                          beam_attn.data[:, j, :memory_lengths[j]])
                dec_states.beam_update(j, b.get_current_origin(), beam_size)
```
what is dec_states.beam_update actually doing? I'm not getting what we are updating, how we are doing so, and what sent_states (definition of beam_update function in Model.py) are.

Thank you all.

**Comment by vince62s** [comment]
duplicate #500
