### ISSUE TITLE
Support ParallelEncoder

### ISSUE THREAD

**Issue by Embedding** [OpenNMT/OpenNMT-py#744]
It could be great if opennmt-py supports ParallelEncoder. For examaple,  we use two encoder upon two separate sequences, and then concatenate them as the input of the decoder. 
This function is pretty useful and has been implemented in opennmt-tf.
Thank you very much.

**Comment by vince62s** [comment]
same as #586

**Comment by lordeddard** [comment]
Is the Mutli Encoder feature still not implemented? If not I would like to work on this. @vince62s , can you give me some starting points on this? 
To start, I went through the `ParallelEncoder` in **Open-NMT-tf**.

Thanks in advance!

**Comment by vince62s** [comment]
see thread in #586

**Comment by lordeddard** [comment]
So, implementing multiple source encoders is currently hard to achieve? Or has anything changed?
