### ISSUE TITLE
Block ngram repeats explanation

### ISSUE THREAD

**Issue by alireza202** [OpenNMT/OpenNMT-py#745]
Hi,

Can you explain what does the "Block ngram repeats" code does in beam search? It's difficult to understand the logic as it is written. For example, why does it set the `beam_scores[j] = -10e20` for the all the words in that beam?

One more question: How can you force the beam search to not produce the same sentences repeatedly?

**Comment by sebastianGehrmann** [comment]
Setting the ngram repeat to `3` blocks the beam search from ever generating a repeated trigram. It does so by setting the probability of the third word of the trigram to something super small. 
If you want to prevent endless repeats, set this to a reasonable number. However, if you experience endless repeats, it is often a sign that you need more training data.

**Comment by alireza202** [comment]
Thanks for the quick reply. What if all values of `beam_scores` are set to `-10e20`? Then where you are doing the `topk`, you will get a random index back. Wouldn't that be a problem?

**Comment by sebastianGehrmann** [comment]
You are correct that this can theoretically happen and would lead to repeated trigrams. In practice, I almost never saw this happen, unless I ran with a super small beam size.
