### ISSUE TITLE
out of memory error during inference using transformer for summarization

### ISSUE THREAD

**Issue by wasiahmad** [OpenNMT/OpenNMT-py#747]
During [summarization inference](http://opennmt.net/OpenNMT-py/Summarization.html#inference) based on the pre-trained transformer model provided by OpenNMT is giving out of memory error with a batch size of 16 and beam size of 4. 

I wonder why inference requires so much memory. I am using GeForce GTX 1080 GPU.

**Comment by devinbostIL** [comment]
I wonder if this is related to the out of memory error I experienced when trying to run translate.py on a large data file, as I mentioned in here: https://github.com/OpenNMT/OpenNMT-py/issues/743

**Comment by sebastianGehrmann** [comment]
Do you have this problem with a smaller batch size @wasiahmad? A normal 1080 only has 8GB of VRAM and the Transformer model is quite large, so it could easily exceed your memory. 
Our translate commands in the documentation all assume 12GB VRAM or more.

**Comment by wasiahmad** [comment]
The problem didn't appear when I set the batch size to 8 but it became very slow.
