### ISSUE TITLE
Where is multi-bleu.perl?

### ISSUE THREAD

**Issue by wuhaixutab** [OpenNMT/OpenNMT-py#75]
haixu@my-machine:~/Desktop/OpenNMT-cls-mdn$ perl multi-bleu.perl data/test.de.atok < cls2mdn.test.pred.atok
Can't open perl script "multi-bleu.perl": No such file or directory

**Comment by guillaumekln** [comment]
You can get it here:

https://raw.githubusercontent.com/moses-smt/mosesdecoder/master/scripts/generic/multi-bleu.perl
