### ISSUE TITLE
GRU is using v1 version, rather than v3 final version

### ISSUE THREAD

**Issue by hughperkins** [OpenNMT/OpenNMT-py#750]
Not sure if this will affect performance at all. I got as far as running lstm vs gru v1 in opennmt, using the demo data, and the gru v1 performance was pretty terrible, so I'm not sure if GRU is used much in OpenNMT? I put some more details on gru v1 vs gru v3 at https://github.com/pytorch/pytorch/issues/8153

**Comment by srush** [comment]
Huh, yeah, people have not really been using GRU. I will update.
