### ISSUE TITLE
Summarization Tutorial Results

### ISSUE THREAD

**Issue by rbommasanimozilla** [OpenNMT/OpenNMT-py#754]
Wasn't sure where to mention this, but it looks like there is an error in the computation of results for the summarization tutorial. In particular, the results given don't make sense assuming F-scores are computed as 2RP/(R+P) since notably the F score given doesn't match the expected value. More explicitly, the F-scores given are not in the interval [min(R,P), max(R,P)] which makes less sense. I tried to see if the columns were mislabeled (i.e. F was where R was or something) but this also does not appear to be the case.

**Comment by pltrdy** [comment]
Hi,

Sorry for late reply. 

I guess the thing is that the score you are getting is an average. the F-score being in an interval `[min(R,P), max(R,P)]` is true for a single measure. 

The results you talk about are averages over multiple measures, i.e. `avg(F)`, `avg(R)` and `avg(P)`. 
You find that it's strange that:
``` 
avg(F) is not in [avg(R), avg(P)] 
```
but in fact, all we can say is that: 
```
avg(F) is in [avg(min(R,P)), avg(max(R, P))]
```

The difference is that there will be measures with:
- `min(R, P) = P, max(R, P) = R`
- `min(R, P) = P, max(R, P)= R`
then their is no order between `avg(F)`, `avg(R)` and `avg(P)`
