### ISSUE TITLE
Inplace op error (post update)

### ISSUE THREAD

**Issue by fermat97** [OpenNMT/OpenNMT-py#755]
I use python 3.5.5 and pytorch 0.4.0, I just run to train a model with transformer and I get this run time error 

RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #2 'other'

in onmt/Loss.py:line 124, in sharded_compute_loss 
loss.div(normalization).backward() 

Thanks

**Comment by fermat97** [comment]
I have tried, and still have the got the same error.

**Comment by da03** [comment]
@fermat97 We just updated our code to support pytorch 0.4, can you pull the latest version and try again? (The Ubiqus fork also supports pytorch 0.4, but they also did some other stuff)

**Comment by fermat97** [comment]
I got this error
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
in onmt/Loss.py
line 276, in shards torch.autograd.backward(inputs, grads)
in 
torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag

**Comment by da03** [comment]
Hmm can you post the command you used such that we can reproduce this error? And did you use pytorch 0.4? (import torch; torch.__version__)

**Comment by fermat97** [comment]
python --version
python -c 'import torch;print("Pytorch version is "+torch.__version__)'
python -u train.py -data /data/ \
                   -save_model /models/models \
                   -gpuid 0 \
                   -layers 6 \
                   -rnn_size 512 \
                   -word_vec_size 512 \
                   -encoder_type transformer \
                   -decoder_type transformer \
                   -position_encoding \
                   -epochs 50 \
                   -max_generator_batches 32 \
                   -dropout 0.1 \
                   -batch_size 4096 \
                   -batch_type tokens \
                   -normalization tokens \
                   -accum_count 4 \
                   -optim adam \
                   -adam_beta2 0.998 \
                   -decay_method noam \
                   -warmup_steps 8000 \
                   -learning_rate 2 \
                   -max_grad_norm 0 \
                   -param_init 0 \
                   -param_init_glorot \
                   -label_smoothing 0.1
