### ISSUE TITLE
embedding training

### ISSUE THREAD

**Issue by arvidzt** [OpenNMT/OpenNMT-py#763]
if use pretrained embeddings, we can set fix_word_vecs_enc = False to train embeddings, but if we don't use pretrained embeddings, how to set embeddings trainable, is it defaultly trainable=True?

**Comment by bpopeters** [comment]
Yes, by default embeddings are learned.

**Comment by Huijun-Cui** [comment]
@srush  I have a question ,If i wanna fix the pretrainend embeddings in the first few epoches , when it comes to near convergence , I wanna make the word embeddings learnable ,  did the Open - nmt support this ?
