### ISSUE TITLE
BPE decreases the performance on FR - EN 

### ISSUE THREAD

**Issue by tayciryahmed** [OpenNMT/OpenNMT-py#765]
Hi,

I have been running multiple experiments on BPE, but is seems it always decreases the performance on French to English translation. I have calculated both tokenized ad detokenized scores, but either way I get less BLEU than a baseline.

The pipeline I am using is the following :

Tokenize the data using the script `tools/tokenizer.perl`
Learn bpe codes (I tried both shared codes and seperate codes): `OpenNMT-py-master/tools/learn_bpe.py –s 32000 < data.txt.tok> bpe-codes`
Apply BPE codes: `OpenNMT-py-master/tools/apply_bpe.py -c bpe-codes < src-train.txt.tok> train.src.bpe`
Then, openNMT-py preprocess and train
I am using 2.5M sentences, 2 layers dec/enc and 32k merge operations. 

Any explanations?

**Comment by da03** [comment]
Hmm can you post a few translated examples? And during preprocessing, did you set `-src_seq_length` to a larger number (default 50) since BPE sentences are longer?

**Comment by tayciryahmed** [comment]
Translated example: 

> Wh@@ enever I or my family need the N@@ H@@ S , we need to qu@@ eue up behind the chron@@ ically chronic intoler@@ ants who believe that everything is due .

I didn't use `-src_seq_length`. When checking the training logs, I fond 1825741 for bpe examples and 1891847 for the baseline (typical OpenNMT-py tokenization), however, I lose 2.85 BLEU ! 

I calculate detokenized BLEU using SacreBLEU. For detokenization, I replace "@@ " with "" and I apply the detoknization script that comes with OpenNMT.

**Comment by hpulfc** [comment]
think about to add layers ,such as 8 layers ,also layers units, batch_size. i think bpe means that 'use less words for more sentences_words`. just have a try !

**Comment by vince62s** [comment]
@tayciryahmed  the right answer is probably @da03 's one. with BPE you need to increase a lot the sequence length (about 100-120 is fine).
Closing, reopen if needed.
