### ISSUE TITLE
Confusion about the `LayerNorm`s in `TransformerEncoder`

### ISSUE THREAD

**Issue by anoidgit** [OpenNMT/OpenNMT-py#770]
According to [line 69](https://github.com/OpenNMT/OpenNMT-py/blob/e74814a397c7a09c77ecafb0f7be650bbf0fd55b/onmt/modules/Transformer.py#L69), the input to the `TransformerEncoderLayer` will be normalized, but when I see [line 120](https://github.com/OpenNMT/OpenNMT-py/blob/e74814a397c7a09c77ecafb0f7be650bbf0fd55b/onmt/modules/Transformer.py#L120) and [line 135](https://github.com/OpenNMT/OpenNMT-py/blob/e74814a397c7a09c77ecafb0f7be650bbf0fd55b/onmt/modules/Transformer.py#L135), I found that the embedding to the first `TransformerEncoderLayer` will also be normalized. I am not sure whether this is right, since [the original paper](https://arxiv.org/abs/1706.03762) says nothing about this in section 5.4.

**Comment by guillaumekln** [comment]
This is an improvement coming from the reference implementation and used as default in their Transformer configuration. See:

https://github.com/tensorflow/tensor2tensor/blob/v1.6.5/tensor2tensor/layers/common_hparams.py#L110-L112

https://github.com/tensorflow/tensor2tensor/blob/v1.6.5/tensor2tensor/models/transformer.py#L1133-L1134

**Comment by anoidgit** [comment]
Thank you. It really helps. @guillaumekln

**Comment by Tristan-J** [comment]
> This is an improvement coming from the reference implementation and used as default in their Transformer configuration. See:
> 
> https://github.com/tensorflow/tensor2tensor/blob/v1.6.5/tensor2tensor/layers/common_hparams.py#L110-L112
> 
> https://github.com/tensorflow/tensor2tensor/blob/v1.6.5/tensor2tensor/models/transformer.py#L1133-L1134

Hi Guillaumekln, still what to know why it's better... is there any mathematical explanation? Or it's according to the experimental results? Thanks!

**Comment by guillaumekln** [comment]
I believe it is according to experimental results from the original authors of the paper.
