### ISSUE TITLE
Can -max_shard_size reduce performance?

### ISSUE THREAD

**Issue by Gldkslfmsd** [OpenNMT/OpenNMT-py#773]
Hello,

I've already asked on gitter, but this is probably better place.

I noticed that if set to -max_shard_size in preprocessing to 5242880, which is 0.5MB, then I have several hundreds of shards, and the lazy data iterator takes them in alphabetical order: 1, 10, 11, 12, 13, ... 2, 20, 21, ...

On the other hand, if I set it to 100 MB, then there are only cca 5 shards, so the order of examples in training differs. I observed big difference in performance, the small shard run is much worse, and the big shard run has strange 3 BLEU high waves corresponding to epochs in BLEU curve. 

I'm wondering whether the shard size can influence this difference in performance? How are the training examples shuffled? Inside the shard or across? Does the order matter?

**Comment by vince62s** [comment]
If you shuffle upfront the dataset before sharding, you should not see any big difference.But I don't see the point of too small shards. 100MB (ie about 1Mio sentences) seems good to go.
