### ISSUE TITLE
Memory Issue:: taking around 16 GB memory with default parameters

### ISSUE THREAD

**Issue by sbmaruf** [OpenNMT/OpenNMT-py#774]
I am new to NMT research. Is it usual to take the default parameter to consume around 16GB of memory while I am also using a GTX 1080ti with 11GB memory? It is surprising to see that GPU is only using 4GB of memory while memory(RAM) is taking around 16 GB data. 

If it is normal, is there any way to stabilize it? 

from the `train.py` it's clear that we are using `*.cuda()` (GPU service) for only `optimizer` and `loss` calculation. Can't we use GPU for the variable to calculate forward pass so that we can do the training faster. 

I was able to test both codes in NVIDIA GTX `1080ti` and `P100`. Both of them process tokens around `4000-6000` tok/s. There's no significant difference.

**Comment by da03** [comment]
Did you pass flag `-gpuid 0` during training?

**Comment by sbmaruf** [comment]
Hi @da03 .. !
I passed `-gpuid 2` as I was using third gpu in the server. I guess that is ok.
