### ISSUE TITLE
tensorboard instead of tensorboardX

### ISSUE THREAD

**Issue by pschwllr** [OpenNMT/OpenNMT-py#780]
@pltrdy In the master branch in `onmt/utils/report_manager.py` (line 11), with the recent code refactoring you've changed from 
`from tensorboardX import SummaryWriter` 
to 
`from tensorboard import SummaryWriter`. 

I don't think a tensorflow/tensorboard dependencies should be introduced there, line 11 should probably be changed back to: `from tensorboardX import SummaryWriter`

Cheers

**Comment by pltrdy** [comment]
Oh indeed. Good point. 

Thanks for pointing this out
