### ISSUE TITLE
Query regarding code in translation.py

### ISSUE THREAD

**Issue by ratishsp** [OpenNMT/OpenNMT-py#782]
Hi,
I was going through the translation process and am unsure why we need the below lines in translation.py:
https://github.com/OpenNMT/OpenNMT-py/blob/f512ea5929d812418cb300d9dde84716c9d42e8d/onmt/translate/translation.py#L39-L40

My understanding is that ``collapse_copy_scores`` would copy probability mass to tgt_vocab. So the above lines in translation.py are redundant.
Please confirm.

-Ratish

**Comment by vince62s** [comment]
Not sure to understand your point / question.

Also, bear in mind collapse_copy_scores in called only when copy_attn is tirned on.
