### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 7267: invalid continuation byte

### ISSUE THREAD

**Issue by negacy** [OpenNMT/OpenNMT-py#784]
I am testing OpenNMT for my dataset. I have a parallel corpus, but when I run the `preprocess.py`, I have the following error message. Any thoughts? Thanks.

`OpenNMT-py$ python preprocess.py -train_src data/de-news-v0.91/src_train_de.al -train_tgt data/de-news-v0.91/tgt_train_en.al -valid_src data/de-news-v0.91/src_val_de.al -valid_tgt data/de-news-v0.91/tgt_val_en.al -save_data data/de-news-v0.91/de-news

[2018-06-28 14:15:30,884 INFO] Extracting features...
[2018-06-28 14:15:30,885 INFO]  * number of source features: 0.
[2018-06-28 14:15:30,885 INFO]  * number of target features: 0.
[2018-06-28 14:15:30,885 INFO] Building `Fields` object...
[2018-06-28 14:15:30,885 INFO] Building & saving training data...

Traceback (most recent call last):
 .....
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 7267: invalid continuation byte`

**Comment by vince62s** [comment]
are you on master ?

**Comment by negacy** [comment]
Yes, I am on master branch.

**Comment by YuanTingHsieh** [comment]
Is the dataset provided by them?
Or it is your own?

If it is your own dataset,
you might want to check the encoding of it.

**Comment by vince62s** [comment]
use python3, it should work.

**Comment by masonreznov** [comment]
Hello @vince62s  I'am also facing the same problem.
I tried to preprocess and came into the same problem.
platform: google colab
python: 3.6.8
source language: Manipuri (a rare Indian Language), which is in utf-8 format
target language: English
