### ISSUE TITLE
ModuleNotFoundError: No module named 'onmt.Utils'

### ISSUE THREAD

**Issue by WenTsai** [OpenNMT/OpenNMT-py#788]
Hi, I'm using `tools/embeddings_to_torch.py` to convert my pre-trained embeddings. However, there seems to lack some files.

Here goes the erros:
> Traceback (most recent call last):
  File "embeddings_to_torch.py", line 10, in <module>
    from onmt.Utils import get_logger
ModuleNotFoundError: No module named 'onmt.Utils'

I could use this function before in a older version, but I just cloned this project several days ago in a new environment.

Also, I noticed that the `embeddings_to_torch.py` can input two embeddings for encoder and decoder now. Should I just keep these two fields being the same pre-traind file if I want to do some summarization (both enc and dec are in the same language)?

**Comment by vince62s** [comment]
can you change this line https://github.com/OpenNMT/OpenNMT-py/blob/master/tools/embeddings_to_torch.py#L10
to 
from onmt.utils.misc import get_logger 

if this is enough to work, can you PR please ?
thanks

**Comment by WenTsai** [comment]
I can't import directly inside the tools folder, so I moved the file to the parent folder temporarily and it could be processed.

It seems to work well, however, there are still some logging error like:

> Filtered embeddings:
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "embeddings_to_torch.py", line 144, in <module>
    main()
  File "embeddings_to_torch.py", line 130, in main
    logger.info("\t* enc: ", filtered_enc_embeddings.size())
Message: '\t* enc: '
Arguments: (torch.Size([50004, 128]),) 

There are some files output without other errors anyway, so I thought the function work normally.

**Comment by vince62s** [comment]
to be able to run in like python tools/embeddings_totorch.py
you need to setup.py OR to export PYTHONPATH=.:$PYTHONPATH
the other error seems to be unrelated.

**Comment by WenTsai** [comment]
Thanks for your assistance. I'll try to submit a PR hours later!

**Comment by sajastu** [comment]
Have the same problem. Any thoughts? Could you get it past? @WenTsai

**Comment by zrlhk** [comment]
> to be able to run in like python tools/embeddings_totorch.py
> you need to setup.py OR to export PYTHONPATH=.:$PYTHONPATH
> the other error seems to be unrelated.

Thanks, it's done.  But I can not understand where I should do this. I use miniconda.
