### ISSUE TITLE
BLEU score is going to 0

### ISSUE THREAD

**Issue by shantanu778** [OpenNMT/OpenNMT-py#789]
after running the following command it seems something like that:

perl tools/multi-bleu.perl data/Tanzil_bnVal.txt < pred.txt
Use of uninitialized value in division (/) at tools/multi-bleu.perl line 139, <STDIN> line 12.
BLEU = 0.00, 32.2/2.9/0.8/0.0 (BP=0.005, ratio=0.159, hyp_len=149, ref_len=935)

Tanzil_bnVal.txt(bengali language dataset) is my valid dataset and pred.txt is the file that was generated after running translate.py

**Comment by sbmaruf** [comment]
can you share the dataset here so that we can reproduce the error and debug.
usually the first obvious case to check if there is any empty line causing this problem or not.

**Comment by vince62s** [comment]
closing for now, reopen if needed

**Comment by paulkp** [comment]
I get the same error!

**Comment by francoishernandez** [comment]
There must be something wrong with your inputs to the script: m
- check the ref and hyp;
- if the hyp seems broken you have an issue with the way you either train or translate.
Either way, you'll need to give more details if you want some help.

**Comment by Nanamumuhan** [comment]
@shantanu778 do you solve this problem ?

**Comment by lovodkin93** [comment]
I actually have the same problem. But what's weird is that when I run it from pycharm it works normally, but when I run it from the shell, this error occurs (in both cases I use the same virtual environment).
Has anyone had a similar situation?
