### ISSUE TITLE
some feature request

### ISSUE THREAD

**Issue by sbmaruf** [OpenNMT/OpenNMT-py#795]
These are some of the suggestion that came to my mind while working on the opennmt-py. 

1. after each of the epoch an evaluation of the bleu score on validation set(also if given any test set). bleu score could be a great help as most of the people judge the system by bleu score. start this evaluation only after a certain number of eppch or steps.
in this way most of the data will be in a single log file and it will be easy to generate some graph on tensorboard also.
2. retrain a model with new dataset.
3. include the moses and BPE pre-processing(it's bit confusing for new comers) inside the preprocess.py  if there is no LICENCE problem.
4. include the BPE post processing inside translate.py if there is no LICENCE problem. also the bpe processing should be decided automatically based on the checkpoint file.
5. visualization of the attention for a single sentence inference.
6. apart from text file, sentence inference from  single line for a model.
7. make a configuration (yaml/bash or others) file to provide the parameters of the model so that it becomes easier to reproduce the experiments. (this feature is in opennmt-tf)

I know all the feature right now we could implement by additional scripts and it makes the code more modular. but wouldn't it be cool if all of these are under the same hood.

**Comment by vince62s** [comment]
All what you mention here is more a workflow suggestion which is unlikely to be implemented in the core repo. However you can check the tools folder where there is a BPE pipeline example.
