### ISSUE TITLE
Memory Issues - Summarization

### ISSUE THREAD

**Issue by rbommasanimozilla** [OpenNMT/OpenNMT-py#796]
I am currently trying to set up summarization using pointer-generator networks with cov. penalty (i.e. the baseline suggested in the summarization tutorial) using the new Newsroom dataset from Cornell (https://arxiv.org/abs/1804.11283) that was published at NAACL 2018. 
I have been running into problems with memory despite using a Titan X Pascal.
Newsroom is 4GB (compared to CNN/DM which is 1.5 GB), so I began by assuming the problem was the size and therefore am trying to just use 10% (400MB) to see if that helps. In addition, I am naturally trying smaller batches, but even at a batch size of 2 I cannot seem to run an epoch to completition. In addition, I have to tried to see if sharding helps, and while super small shards (1MB) almost get me to the end of an epoch, this is a 500x decrease from the 500MB shards recommended for CNN/DM in the tutorial and still cannot complete an epoch. Additionally, I have tried decreasing the RNN size and embedding dimension, but this leads to marked declines in performance (obviously within the first epoch, so these differences may not exhibit in the final models similar to observations found by Britz et al regarding embedding dimension for NMT in https://arxiv.org/abs/1703.03906) and also wasn't sufficient unless I set the embedding dimension to a paltry 8 or so which obviously is unreasonable. 
Any ideas on what could be going wrong? All of the above refers to memory problems during training, I have yet to attempt to inference due to this problem.  

Also, with the current work on Multi-GPU, are there any early suspicions on whether this will either help/exacerbate memory performance?

**Comment by rbommasanimozilla** [comment]
![image](https://user-images.githubusercontent.com/39746714/42252926-0c66d226-7ef4-11e8-88b2-dfbad4278810.png)
If it helps, above is one of the logs I have gotten.

**Comment by vince62s** [comment]
If this is solved close the issue or post your command line.

**Comment by rbommasanimozilla** [comment]
Resolved

**Comment by evasharma** [comment]
Could you @rbommasanimozilla  @vince62s  share how this was resolved? I am facing the same issue when running the same model as specified on summarization.md on the cnn daily mail dataset. I am getting cuda out of memory error.

**Comment by ankit201** [comment]
@vince62s  @rbommasanimozilla  Please share what all changes have to be made to avoid memory error or training getting killed
