### ISSUE TITLE
README.md out of date?

### ISSUE THREAD

**Issue by epwalsh** [OpenNMT/OpenNMT-py#80]
At the end of the README under "Not yet implemented", it says "Multi-GPU". However it seems multi-gpu support was added: https://github.com/OpenNMT/OpenNMT-py/blob/master/train.py#L368

Is this correct?

**Comment by guillaumekln** [comment]
Yes it was implemented by @bmccann a while back. Thanks!

**Comment by jekbradbury** [comment]
It was implemented, but the PyTorch `nn.DataParallel` module that it uses is not very efficient for complicated RNN-heavy networks, so it didn't provide very good scaling. Soon, `nn.DistributedDataParallel` will be available (I think it's in master already) and could be a better choice (even for one machine).
