### ISSUE TITLE
torchtext Field don't support dtype 

### ISSUE THREAD

**Issue by GaoQ1** [OpenNMT/OpenNMT-py#806]
Hello, I find torchtext.data.Field don't support dtype paramters. It should be tensor_type. Is that right?
Thanks!

**Comment by zhezhaoa** [comment]
Maybe your torchtext is out-of-date. Try this  git+https://github.com/pytorch/text (see requirements.txt). 
Use tensor_type instead of dtype can also solve the problem.

**Comment by GaoQ1** [comment]
@zhezhaoa  Thanks, you're right.My torchtext version0.2.3. And this project is supported version 0.3.0.

**Comment by alphadl** [comment]
if you use the latest version ,you can remove the parameter "data_type"
