### ISSUE TITLE
when i  use preprocess.py  to process data, there was a memory leak

### ISSUE THREAD

**Issue by hpulfc** [OpenNMT/OpenNMT-py#811]
## there was a memory leak

my data set is 501M and it has 9741761 lines .
when i use this params:

`
 -src_seq_length 128 
 -tgt_seq_length 128 
 -dynamic_dict   
 -share_vocab 
`

There was a **memory leak**.
The os env as follows:
`
$free -h
`

                      total        used        free      shared  buff/cache   available

      Mem:            54G        455M         50G        656K        4.0G         53G
      Swap:            0B          0B          0B

I really appreciate you can help me!

**Comment by vince62s** [comment]
you need to shard the data, look at the options of preprocess.py

**Comment by hpulfc** [comment]
yes , it does work . 

I set the max_shard_size = 64 * 1024 * 1024 and the memory just use 15 ~ 20 G. 

Thank you ! :)  @vince62s
