### ISSUE TITLE
Word Features

### ISSUE THREAD

**Issue by Lawhy** [OpenNMT/OpenNMT-py#815]
May I ask if I want to annotate my data with some clusters number, so for example,
On the src side, Amy becomes A-0 m-1 y-2;
on the tgt side, 艾米 becomes 艾-3 米-1.
How could I incorporate this information using openNMT-py? I know that in the Lua version you have word features, so maybe A|0 m|1 y|2.

**Comment by vince62s** [comment]
same as in Lua, except that openNMT-py supports only src features, not target features.
