### ISSUE TITLE
translation_server.py may be have a flaw with opt

### ISSUE THREAD

**Issue by hpulfc** [OpenNMT/OpenNMT-py#819]
https://github.com/OpenNMT/OpenNMT-py/blob/e084cf3ff717c1edea080f1046eaeb97cb5391bb/onmt/translate/translation_server.py#L178

this may be `self.opt.log_file`  :)

**Comment by Embedding** [comment]
I met this too. A simple method is to replace opt.log_file with "./log.txt"

**Comment by ab3nd** [comment]
I just ran into this myself. Making it self.opt.log_file works, assuming you put a "log_file" entry in the conf.json file.

**Comment by pltrdy** [comment]
@hpulfc Thanks for pointing this out, this solution looks fine. 

@ab3nd I guess it's also working (i.e. not raising exception nor unwanted behavior) if there's no `log_file` entry, right? (since `parse_opt` would've set a default value (an empty string `''`) that should be ok).

**Comment by hpulfc** [comment]
well, close it !
