### ISSUE TITLE
Python server tokenizer loading checks a bad path for the tokenizer model

### ISSUE THREAD

**Issue by ab3nd** [OpenNMT/OpenNMT-py#825]
Lines 235-237 of the load method of ServerModel in translation_server.py attempt to load the tokenizer model specified in conf.json. 
``model_path = os.path.join(self.model_root, self.tokenizer_opt['model'])``
``sp.Load(model_path)``

I'm using the example.conf.json from OpenNMT-py/available_models, edited to include my model and to include a log_file entry so translation_server.py doesn't fail:

`{`
`    "models_root": "/home/ams/Projects/StupidDeep/data_for_OpenNMT",`
`    "models": [`
`        {`
`            "id": 100,`
`            "model": "chat-model_step_100000.pt",`
`            "timeout": 600,`
`            "on_timeout": "to_cpu",`
`            "load": true,`
`            "opt": {`
`                "gpu": 0,`
`                "beam_size": 10,`
`                "log_file": "/tmp/open_nmt.log"`
`            },`
`            "tokenizer": {`
`                "type": "sentencepiece",`
`                "model": "wmtenfr.model"`
`            }`
`        }`
`    ]`
`}`

I've installed sentencepiece, but there doesn't seem to be a file called wmtenfr.model anywhere on my computer, and certainly not in the model directory for my translation model. 

The full error is 
ams@gluttony:~/Projects/StupidDeep/OpenNMT-py$ ./server.py --config ../data_for_OpenNMT/conf.json
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Pre-loading model 100
[2018-07-11 22:05:25,286 INFO] Loading model 100
[2018-07-11 22:05:35,375 INFO] Loading tokenizer
Traceback (most recent call last):
  File "./server.py", line 115, in <module>
    debug=args.debug)
  File "./server.py", line 24, in start
    translation_server.start(config_file)
  File "/home/ams/Projects/StupidDeep/OpenNMT-py/onmt/translate/translation_server.py", line 75, in start
    self.preload_model(opt, model_id=model_id, **kwargs)
  File "/home/ams/Projects/StupidDeep/OpenNMT-py/onmt/translate/translation_server.py", line 111, in preload_model
    model = ServerModel(opt, model_id, **model_kwargs)
  File "/home/ams/Projects/StupidDeep/OpenNMT-py/onmt/translate/translation_server.py", line 181, in __init__
    self.load()
  File "/home/ams/Projects/StupidDeep/OpenNMT-py/onmt/translate/translation_server.py", line 237, in load
    sp.Load(model_path)
  File "/usr/local/lib/python2.7/dist-packages/sentencepiece.py", line 118, in Load
    return _sentencepiece.SentencePieceProcessor_Load(self, filename)
IOError: Not found: "/home/ams/Projects/StupidDeep/data_for_OpenNMT/wmtenfr.model": No such file or directory Error #2

**Comment by vince62s** [comment]
You need to build your own sentencepiece model (equivalent to BPE model)
