### ISSUE TITLE
didn't create saved model file

### ISSUE THREAD

**Issue by morningmorningwind** [OpenNMT/OpenNMT-py#827]
Hi, 

I just tested the latest version on my Mac. Here is the command used for training:

python train.py -data data/demo -save_model saves/demo_model -rnn_size 100 -word_vec_size 50 -layers 1 -train_steps 100 -optim adam -learning_rate 0.001

However, I can't see any saved file under the folder saves/ (it is empty after training). 
Could anyone help figure out this problem.

Thanks.

Best

**Comment by morningmorningwind** [comment]
oops... solved. I need to change -save_checkpoint_steps, because its default value is 5000...

**Comment by cocaer** [comment]
hi...how to load checkpoint?
