### ISSUE TITLE
_build_rnn() function is not found

### ISSUE THREAD

**Issue by susht3** [OpenNMT/OpenNMT-py#828]
onmt/decoders/decoder.py

class RNNDecoderBase(nn.Module):
it build rnn by : self.rnn = self._build_rnn(...)
but RNNDecoderBase has no this function, and the class Module also has no this function

but i find that class InputFeedRNNDecoder(RNNDecoderBase) has this function.

So where is _build_rnn function ？？

**Comment by vince62s** [comment]
RNNDecoderBase is instanciated by StdRNNDecoder parent class.
this one has _build_rnn

**Comment by vince62s** [comment]
What I mean is that only StsRNNDecoder and InputFeedRNNDecoder call RNNDecoderBase, and buil_rnn is defined in both.

**Comment by hpulfc** [comment]
@susht3 
may be you should know the relationship between the parent class and the subclass.
