### ISSUE TITLE
Summarization Results

### ISSUE THREAD

**Issue by rbommasanimozilla** [OpenNMT/OpenNMT-py#832]
Are there any available perplexity/accuracy results (i.e. non ROUGE) scores computed for validation for summarization (mostly those related to CNN/DM)? Having these results might be helpful for people trying to debug/build new models in addition to the recorded ROUGE results on the summarization tutorial. In addition, have the results presented in the tutorial been replicated on a recent commit/current master? 
From most of the discussions on summarization scattered accross multiple issues, I have seen references to ROUGE L-1 scores around 36, 37, and peaking at 38 in all of these discussions, which is significantly different from the 39.53 reported in the original Pointer-Generator Networks paper and is even farther from the best results reported in the tutorial of more than 40. It would be good to have these confirmed, since as far as I am aware this would reflect the best performance of an abstractive and openly-available summarization system (at least to my knowledge). 
Remark: All of the above is in the context of pointer-generator/copying based seq2seq models on CNN/DM.

**Comment by vince62s** [comment]
closing this, maybe go to the forum http://forum.opennmt.net/ where there are some discussion about results.
