### ISSUE TITLE
How can I select best model?

### ISSUE THREAD

**Issue by wonkeelee** [OpenNMT/OpenNMT-py#835]
Hi, 
I recently updated to the newly committed version (Jul 10, 2018)
in case of previous version, The file name of checkpoint made it easy to check the model performance.
(e.g. demo-model_acc_11.19_ppl_978.36_e7.pt), But for the newer version, I have no idea to check performance of checkpoint through the name of file (e.g: demo-model_step_10000.pt)

Is there any way to check model performance during the training  process?

thank you.

**Comment by rbommasanimozilla** [comment]
You can explictily setting how frequently it logs (in opts), alternatively you could just append these quantities to the checkpoint (i.e. basically reintroduce the old way checkpoints were labeled), in particular this might be helpful if you are on an external server and cannot see the logging.

**Comment by vince62s** [comment]
This is something that we will definitely address.
We are thinking of keeping sort of a result.yml file which will keep the best N checkpoint in a list.
Then we can use this to average.
see #813

**Comment by sajastu** [comment]
@vince62s Hi Vincent, wondering whether this option is addressed back then in OpenNMT? Thanks!

**Comment by vince62s** [comment]
no, but there is a moving average feature that can help.
