### ISSUE TITLE
I want to use BPE to prepare the data, how should i do in stap1?

### ISSUE THREAD

**Issue by Julisa-test** [OpenNMT/OpenNMT-py#837]
![1](https://user-images.githubusercontent.com/38872215/42793670-c513043e-89ad-11e8-8fce-fac516dfecec.png)

Thank you

**Comment by rbommasanimozilla** [comment]
looks like there are spaces in your paths which breaks the argument parser, as it interprets something like "train119w.bpe.mn" as an argument (which is what the error is describing)

**Comment by Julisa-test** [comment]
@rbommasanimozilla You are right. Thank you!
