### ISSUE TITLE
Option -gpuid not working as it should

### ISSUE THREAD

**Issue by goncalomcorreia** [OpenNMT/OpenNMT-py#840]
When I use `-gpuid` option in current master of OpenNMT, regardless of what gpu I choose, the training script always chooses gpu 0.
If I use multigpu, for example, `-gpuid 2 3`, the training goes to gpus 0 and 1.

Is this a known issue?

**Comment by goncalomcorreia** [comment]
For anyone who's having this problem, if you want to train on gpus that are not gpu 0, you can change the visible devices with `CUDA_VISIBLE_DEVICES`. For example, `$CUDA_VISIBLE_DEVICES=1,2` will make your experiments go to gpu 1 and then gpu 2 in the current master.

**Comment by vince62s** [comment]
AFAIK, this has always been the behavior of OpenNMT-py.

**Comment by rbommasanimozilla** [comment]
As far as I understand, this is really a pytorch+CUDA "inconsistency"

**Comment by goncalomcorreia** [comment]
@vince62s, I'm pretty sure this was not the behavior of OpenNMT-py as I used that option all the time to train on gpus other than 0, without changing the CUDA_VISIBLE_DEVICES

**Comment by vince62s** [comment]
ok here is the thing.
BEFORE I introduced multi-gpu, the behavior was to take the GPU id of the command line.
But it worked only **with single gpu**.

WHEN I introduced the multi-gpu, I replicated the behavior of Fairseq, which clearly says we need to specify the CUDA_VISIBLE_DEVICES env var.

The main reason is that, it is ultimately capable of multi node training, and it is way easier to handle it this way.

Nevertheless, I take the point into account, but a PR would be welcome.
Cheers.

**Comment by goncalomcorreia** [comment]
Yes, I know multigpu wasn't working before and I was very excited to know that it was working now - it was actually the main reason I pulled the latest changes.

I think that since, as you said, it may be hard to have the previous behavior with multi gpu, the -gpuid option may be a bit misleading in that regard. Some possible solutions:

1) Not sure if this is possible, but we could change the CUDA_VISIBLE_DEVICES after parsing the gpuid option (not a fan of this one since it changes an env var without the user knowing)

2) Another possibility is to have something like -n_gpus instead, where you choose the number of gpus you want to use and then specify in the documentation that you need to change your CUDA_VISIBLE_DEVICES with the gpu ids that you are able to use in that moment

3) Or OpenNMT could just replicate Fairseq in that regard and just use all the gpus available as default and, as in the option above, specifying in the documentation that the env var CUDA_VISIBLE_DEVICES needs to be changed with the gpus the user wants to train on

Not sure which of these options is the better one. Personally, I would go for number 2.

I would be happy to do a pull request with the preferred behavior for this.

**Comment by vince62s** [comment]
2. would work in the short term, BUT not if we want to support multi node, it may require a bit more work (see gpu_rank option)

**Comment by goncalomcorreia** [comment]
Maybe just a heads up in the README then (in step 2's description)?

**Comment by alphadl** [comment]
although I have assigned the gpuid by using the CUDA_VISIBLE_DEVICES , the gpu 0 still be automatically used as a priority....

**Comment by sbmaruf** [comment]
@goncalomcorreia What is the problem of Solution number 1. we can do it by `os.environ['CUDA_VISIBLE_DEVICES']`. When you change the `env var`, you could put that into the log that you are changing the environment variable, and also the env change is only going to effect in that python run. According to me it's the easiest way to solve this issue. 

Regarding the current solution, I also think it's a good way if this is properly documented in the documentation. Currently, it is written as,

`-gpuid [] Use CUDA on the listed devices.`

I think this is not that so clear at the first sight.

**Comment by vince62s** [comment]
guys,
a PR would be welcome, in the meantime I updated the FAQ to be clearer.

https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md

**Comment by vince62s** [comment]
can you guys have a look at #962 and tell me if you're comfortable with these new options ?

**Comment by goncalomcorreia** [comment]
Just to be sure I got it right, does the model run in all gpus available by default so you can then choose which gpus you want to use with CUDA_VISIBLE_DEVICES?

**Comment by vince62s** [comment]
Not exactly.
First you need to set which GPU you want to use with CUDA_VISIBLE_DEVICES

Then case (1) on a single node, you need to set:
world_size = 3 (if you want to run an 3 GPU, given you need to have made 3 visible at least)
gpu_ranks = 0 1 2
I know, this looks a little cumbersome because you need to set 2 parameters.

But you will get it when looking at case (2), on 2 nodes:
Node 1:
master_ip=ip_address_node1
master_port=portnumber_node1
world_size = 7
gpu_ranks = 0 1 2
Node2:
masterip=ipaddress_node1
master_port=portnumber_node1
world_size = 7
gpuranks = 3 4 5 6

for node 1 you need to have set at least 3 cuda visible devices
for node 2 at least 4

**Comment by Henry-E** [comment]
I would recommend adding this to the opts section since it's not super clear the first time around what to do

**Comment by noe** [comment]
On a single node, when trying to use nodes other than the first ones, I am getting an error. My node has 8 GPUs and I want to use GPUs 2 and 3. I am setting `--world_size 8 --gpu_ranks 2 3` and it gets stuck indefinitely. Setting `--world_size 2` is of no use either. `CUDA_VISIBLE_DEVICES` is properly set to `2,3`.

**Comment by vince62s** [comment]
Single node you need
gpu_ranks 0 1
world_size 2
And set cuda visible device as you need

**Comment by vince62s** [comment]
@Henry-E can you PR a doc / opts amendment ?

**Comment by Henry-E** [comment]
Sure

**Comment by vince62s** [comment]
"At that time, GPUs 0 and 1 were taken by other processes."

by a another onmt-py run or something else ?
monitor what you're doing with watch nvidia-smi

**Comment by noe** [comment]
GPUs 0 and 1 were taken by other non-onmt-py processes owned by other users of the machine. Target GPUs were 2 and 3, which were free, yet OpenNMT-py said "Address already in use". Consistently reproducible in my environment.

**Comment by noe** [comment]
My bad. On a different node this is no longer reproducible and works perfect with `-world_size 2 -gpu_ranks 0 1`. Given that the troublesome node is no longer accessible (it is part of a slurm cluster over which I have no admin control), I assume the node was in an unstable condition when the problems were happening. If I find the problem again, I will provide with the requested info. Sorry for the annoyance.

**Comment by noe** [comment]
The process never appears in `nvidia-smi` . The exception happens just after starting OpenNMT-py, so I ran OpenNMT-py several times (in a loop) while I was watching `nvidia-smi` and OpenNMT-py never appeared in the output.

However, I was mistaken: the problem is **not** 100% reproducible. In 2 different nodes I can reproduce it but in a third node I can not reproduce it, so there are other factors going on here. I am running in a [slurm](https://slurm.schedmd.com/) cluster; in theory it should not affect how stuff works, but I am no expert in slurm, so not totally sure.

**Comment by noe** [comment]
Nope. I still think this is a problem related to OpenNMT-py, as I have never got anything alike with tensor2tensor or fairseq in the same environment, but I can't provide further info to properly diagnose it.
