### ISSUE TITLE
Attribute typo in inputter.py

### ISSUE THREAD

**Issue by Evan-Gao** [OpenNMT/OpenNMT-py#843]
In [inputter.py Line 79](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/inputters/inputter.py#L79):

```
def save_fields_to_vocab(fields):
    """
    Save Vocab objects in Field objects to `vocab.pt` file.
    """
    vocab = []
    for k, f in fields.items():
        if f is not None and 'vocab' in f.__dict__:
            f.vocab.stoi = f.vocab.stoi
            vocab.append((k, f.vocab))
    return vocab
```

It does not make any sense to me for using ` f.vocab.stoi = f.vocab.stoi`.

**Comment by vince62s** [comment]
no it does not make sense but I left it here because previously it was = dict() and I had to remove it to avoid a bug even though it did make sense to have dict().
I did not inquire further.
