### ISSUE TITLE
OpenNMT loading data twice before Training?

### ISSUE THREAD

**Issue by abaheti95** [OpenNMT/OpenNMT-py#844]
Hi all,

I have successfully used an older version of OpenNMT-py (with pytroch 0.3). I recently saw that all the dependencies have been upgraded and I now I'm facing out of memory issues with the same previous configuration. However, that's not my main concern.

The train.py first loads the data and takes a LOT of time doing that. Once the mode in built it again loads the data for another hour before starting the training? Why is this done?
<img width="1154" alt="screen shot 2018-07-20 at 12 39 39 pm" src="https://user-images.githubusercontent.com/9119028/43014386-075f0202-8c1a-11e8-8a55-becc0c0e094f.png">

<img width="1165" alt="screen shot 2018-07-20 at 12 34 52 pm" src="https://user-images.githubusercontent.com/9119028/43014349-e7965dc6-8c19-11e8-9268-9afddae633cc.png">

**Comment by rbommasanimozilla** [comment]
1. I too recently have started having this bug, but
2. I am under the impression that this is just logging twice and not running everything twice (notice how every duplicate has the same timestampe and is exactly the same in terms of performance). 
This may be related to 3. A previously seen issue (I assume you are using a single GPU and that is why this happening)

**Comment by abaheti95** [comment]
I didn't notice the logging twice thing.

But, it is indeed loading the data again. I am currently running the same code again with a smaller batch size(128) and I was at 48% MEM when it logged `"Start training..."`. Now it is killed as it started accumulating another 48% on the server.
```
[1873031.362219] Out of memory: Kill process 19577 (python2) score 502 or sacrifice child
[1873031.362231] Killed process 19577 (python2) total-vm:449309268kB, anon-rss:398061500kB, file-rss:89088kB
```

**Comment by abaheti95** [comment]
@rbommasanimozilla Also, is OpenNMT loading the entire training and validation data into the memory? If yes how can I control? Is there any option to tell it to read it in batches? If No, why is it taking up so much memory and time?

**Comment by vince62s** [comment]
no just logging twice when using 1 GPU
there is a PR to fix it but not merged yet.

**Comment by abaheti95** [comment]
Why is there a 1 hour long wait between the 2 loggings then? (referring to the snapshot in the initial question)
Start training... [10:24:49]
Loading dataset.. [11:28:39]
Step 50... [11:30:06]

**Comment by rbommasanimozilla** [comment]
one thing I have observed is you don't incur much of penalty for havign many shards, so erring on the side of smaller shards seems to work fine in practice (I currently use 10mb shards, the recommended from elsewhere may be 131mb shards)

**Comment by vince62s** [comment]
as long as you shuffle before hand it should be fine, but working with 131mb shrad gives you about 1M sgements per shard which works fine too.

**Comment by eeric** [comment]
make OpenNMT project audio list and sentences text list, as following:
https://github.com/eeric/OpenNMT-py-make-tgt-train.txt/blob/master/openNMT_make_label.py
