### ISSUE TITLE
copy_attn and coverage_attn is not supported in StdRNNDecoder

### ISSUE THREAD

**Issue by wasiahmad** [OpenNMT/OpenNMT-py#847]
Since currently copy_attn and coverage_attn is not supported in StdRNNDecoder,  will it be fine if I follow the copy_attn and coverage_attn implementation from the InputFeedRNNDecoder? In my work, I want to avoid input-feeding but want to use copy_attn and coverage_attn. Any suggestion will be appreciated.

**Comment by vince62s** [comment]
Yes it should be fine.
