### ISSUE TITLE
Option -gpu or CUDA_VISIBLE_DEVICES not working in the decoding as it should

### ISSUE THREAD

**Issue by chenkehai** [OpenNMT/OpenNMT-py#852]
When I use "-gpu option" or "CUDA_VISIBLE_DEVICES=gpuid" to decode the test set in the current master of OpenNMT-py, regardless of what GPU I choose, the decoding always runs on the CPU instead of GPU.
Is this a known issue?

**Comment by vince62s** [comment]
no it works fine.
provide all command lines you used.

**Comment by chenkehai** [comment]
Thanks for your help!
I check it again.
The reason is that when I run the decoding on the GPU which is training, there is not enough memory to decode the test set on the same GPU.
Therefore, this decoding process selects the CPU by default to complete the decoding.
