### ISSUE TITLE
an error happened in tools/average_models.py 

### ISSUE THREAD

**Issue by alphadl** [OpenNMT/OpenNMT-py#859]
Traceback (most recent call last):
  File "average_models.py", line 46, in <module>
    main()
  File "average_models.py", line 41, in main
    final = average_models(opt.models)
  File "average_models.py", line 13, in average_models
    m = torch.load(model_file)
  File "/Users/alphadl/.pyenv/versions/2.7.13/lib/python2.7/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/Users/alphadl/.pyenv/versions/2.7.13/lib/python2.7/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
ImportError: No module named utils.optimizers

I met this error , but can not figure out where the bug from , also ,there are no documents describe this average_models.py

**Comment by alphadl** [comment]
btw , my local environment are as followed: python 2.7.13 / pytorch 0.4.0

**Comment by alphadl** [comment]
I am sure that I have done setup.py and run it in a right way ~

**Comment by vince62s** [comment]
module utils.optimizers exists, so provide your command line, it runs fine for me.

**Comment by alphadl** [comment]
I know the reason why the problem happens , I named the model with space, so that script regard one filepath to several files.

**Comment by alphadl** [comment]
however ,when I average a transformer model and a seq2seq model , I met a new problem ~   it shows:
-------
tools/average_models.py", line 23, in average_models
    avg_model[k].mul_(i).add_(model_weights[k]).div_(i + 1)
KeyError: 'encoder.rnn.bias_hh_l0'
------

**Comment by vince62s** [comment]
you just can't average models that do not have the same structure / parameters ...

**Comment by alphadl** [comment]
I see ... Appreciate your kind responses ~ but If I want to resemble models in different structures , how can I achieve it...

**Comment by vince62s** [comment]
you can't average. if you want to ensemble, you'll have to wait for the ensemble PR, but obviously it is not going to be merged right away.
or you can distillate your transformer model into a rnn that has the same structure as your rnn, and then average your rnns.

**Comment by alphadl** [comment]
BTW, if there are any papers or tutorials about ensembling Transformer and seq2seq
