### ISSUE TITLE
English -> German pretrained model that does not require sentencepiece

### ISSUE THREAD

**Issue by silent-vim** [OpenNMT/OpenNMT-py#861]
Hi, I am trying out some experiments with opennmt-py and was wondering if there is a pretrained model for english to german that does not require pretokenization with sentencepiece. 

- Thanks

**Comment by vince62s** [comment]
Sorry there is no such pretrained model.
Be aware that for German, BPE or SentencePiece (or any other subword tokenization) is required to get decent results.
