### ISSUE TITLE
Accuracy dropped when using -train_from

### ISSUE THREAD

**Issue by raymondhs** [OpenNMT/OpenNMT-py#864]
Hi, I have trained a transformer model for 100000 steps and stopped it. I wanted to continue training for 200K more steps by specifying `-train_from model_step_100000.pt -train_steps 300000`, the rest of the parameters are identical. I compared the perplexity and accuracy logged during training at step 100,000 (i.e. end of my first run) and 100,050. However it seems the accuracy has dropped a lot (it became 48 from 76). Is this an expected behaviour when using -train_from?

**Comment by vince62s** [comment]
no, not expected, I use it a lot and it works fine.
provide both command line (initial one and with train_from)

**Comment by vince62s** [comment]
How big is your dataset ? did you shuffle it before preprocessing ?
The only thing I can imagine is that when you train_from it starts over from the begining of the dataset and the data are very different from where it stands at step 100k

**Comment by raymondhs** [comment]
The dataset is about 25 million sentence pairs, I did not shuffle before but I thought preprocess.py would do the shuffling by default? By the way, the dataset is also sharded into several parts.

**Comment by vince62s** [comment]
Then it must be your issue.
If you don't want to retrain 100k steps and check if this is your issue, move the first shard into another place and check if when loading the second one (then do this again with the second one) you get another accuracy.
I think the order of shard is not numerical but alphabetical (1 then 11, ... then 2)

**Comment by vince62s** [comment]
this is only a Lua version argument.
you need to look at the train_from option and various settings of reset_optim is necessary.
