### ISSUE TITLE
Coverage in Global Attention

### ISSUE THREAD

**Issue by wasiahmad** [OpenNMT/OpenNMT-py#867]
Currently, it looks like coverage attention is not supported in Global Attention as mentioned in the [docstring](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/global_attention.py#L142). Can anyone confirm or am I missing anything?

If it is implemented, then what is expected to pass in the parameter, `coverage`? Docstring says it should be a float tensor but it looks like `coverage` needs to be a 2d tensor of shape, `batch x source_len`. 

```
if coverage is not None:
    batch_, source_l_ = coverage.size()
    aeq(batch, batch_)
    aeq(source_l, source_l_)
```

In case, if the whole decoded sequence (not one step) is provided to the global attention, then what is the role of `coverage` parameter?

Finally, it looks like the following code has issues. It doesn't look like what is suggested in the [Get to the Point](https://arxiv.org/pdf/1704.04368.pdf) paper.

```
if coverage is not None:
    cover = coverage.view(-1).unsqueeze(1)
    memory_bank += self.linear_cover(cover).view_as(memory_bank)
    memory_bank = self.tanh(memory_bank)
```

**Comment by andre-martins** [comment]
I found the same issue some time ago. In case it helps, I have an implementation of coverage which is closer to the paper: https://github.com/Unbabel/OpenNMT-py/blob/dev/onmt/modules/GlobalAttention.py#L198 (wrapped inside the "score" function).

**Comment by vince62s** [comment]
closing, lack of activity. feel free to reopen.
