### ISSUE TITLE
The Transformer is not the same as the paper

### ISSUE THREAD

**Issue by tanaka-jp** [OpenNMT/OpenNMT-py#868]
https://github.com/OpenNMT/OpenNMT-py/blob/fd1ec04758855008dbbf7ce1d56d16570544e616/onmt/encoders/transformer.py#L48-L52

Maybe I am wrong, but the order of each step does not seem to be in accordance with the paper.
I think it should be like this.
        context, _ = self.self_attn(inputs, inputs, inputs, mask=mask)
        out = self.dropout(context) + inputs
        out = self.layer_norm(out)
        return self.feed_forward(out)

https://github.com/OpenNMT/OpenNMT-py/blob/fd1ec04758855008dbbf7ce1d56d16570544e616/onmt/modules/position_ffn.py#L40-L42

And the order of each step in PositionwiseFeedForward is also different. 
I think it should be like this.
        inter = self.dropout_1(self.relu(self.w_1(x)))
        output = self.dropout_2(self.w_2(inter))
        output = self.layer_norm(output + x)
        return output

![aaa](https://user-images.githubusercontent.com/29939758/43496554-e911f9e0-9578-11e8-9763-0ea43e710466.png)

But in my examination, current transformer is working well.
I will try my change and report here.

**Comment by tanaka-jp** [comment]
I tried the Japanese text generation task and there is no clear change in validation accuracy.

**Comment by tanaka-jp** [comment]
Perhaps it may be different in other data sets and tasks.

**Comment by vince62s** [comment]
already discussed here #770

**Comment by tanaka-jp** [comment]
Thank you very much
