### ISSUE TITLE
GPU rank & transformer

### ISSUE THREAD

**Issue by Citronelol** [OpenNMT/OpenNMT-py#871]
Dear all, 

I have seen the GPU rank option (and device id) in the opts file : what is its goal exactly?

Also gave a try to the « big » transformer setup (heads 16, dff 4096...) but am facing an Out of Memory error even with very small maximum shard sizes. Do you have idea why ? 

Thanks a lot in advance for your help.

**Comment by vince62s** [comment]
Rank and device_id are dereived from the Fairseq implementation.
The purpose is for distributed training on several nodes.
Rank would be the overall process rank (eg from 0 to 127)
Device_id is the id within a node (eg from 0 to 7)

Anyway the code is not ready for multinode training, so just use -gpuid 0 1 2 3 ... for multi gpu.

Big:
I guess your OOM error comes from the GPU OOM not the RAM.
try to reduce the batch_size (sentence or token)

**Comment by Citronelol** [comment]
Thanks a lot Vince, indeed it is now training !
