### ISSUE TITLE
A (potential) bug of batch.indices

### ISSUE THREAD

**Issue by rylanchiu** [OpenNMT/OpenNMT-py#872]
I am trying to print the original target and source sequene out during training. I just follow the [implementation](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translation.py#L66-L83) in `translation.py`: 

    for b in batch.batch_size:
        print(batch.dataset.examples[batch.indices.data[b]].src)

But I got the error of `IndexError: list index out of range`. I print `batch.indices` and found there are some values larger than `len(batch.dataset.examples)`, which is problematic. And then I found there is a [filter_out](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/inputters/text_dataset.py#L85) that filter the examples. But after that, the indices is not re-arange to 0~len(examples). Is it a bug or I misunderstood it? Otherwise, how can I extract the correspoding original source and target of the current `batch`. Thanks a lot!

**Comment by vince62s** [comment]
closing this here since you asked the question on the forum.

**Comment by rylanchiu** [comment]
@vince62s But isn't it more suitable to put it here cause it is a (potential) issue ?
