### ISSUE TITLE
Words are getting skipped while doing the Translation

### ISSUE THREAD

**Issue by Manoharakadiri** [OpenNMT/OpenNMT-py#874]
I have trained a model with 10Lakh lines of(finnish - English) parallel corpus data to OpenNMT Model.Once the training is done i have tried to translate the small text file.
INPUT TEXT FILE DATA;
portal variables
Record producer name: Häiriöilmoitus
Käyttäjä: Messala Hanna Leena
Järjestelmä: Henki-jaeläkevakuutusjärjestelmä
Palvelu: Säästämis- ja sijoituspalvelut (sis. Henkivakuutus)
Asiakas/yritys: 102-46593
Henkilötunnus: secret
Vaikutus: 2 ? Normaali
Kiireellisyys: 2 ? Normaali
Prioriteetti: 3 - Normaali
Attachements:: Ei valittua tiedostoa
[incident_description]

The output which i got after translation.
OUTPUT:
portal
The Record name: Häiriöilmoitus
The Käyttäjä: Hanna Leena
Järjestelmä:
The Palvelu: and sijoituspalvelut (sis. Henkivakuutus)
Asiakas/yritys:
Henkilötunnus:
Are they supposed to be Vaikutus:
Are they supposed to be Kiireellisyys:
Prioriteetti: - Normaali
It was not a tiedostoa
[incident_description]

If you notice in the output most of the words are getting skipped but as per the process it has to replace the unknown as it is if the respective doesn't find in the trained model.

Would you please help me with this.

One more thing like do we need format the input data before sending for translation?
if that is the case could you please share the code for formatting the input data before sending for translation.

**Comment by alphadl** [comment]
could you give us more details like: what's your command line ? the size of your training corpus?...

first of all , you have to preprocess your text (both of training/valid text and test text) by a same processing method, like BPE / character etc.

secondly, you must aware that "missing translation" and “over translation” are inevitable in spite of the state-of-art translation method.

however , if you feed the model enough training data (finnish - English) and process the data and train the model appropriately , the translation results will perform better than you have got.

**Comment by Manoharakadiri** [comment]
hi alphadl,
thanks for your response,
i am not sure how to process furthur.
i have already used the preprocessing for the trained and valid text using the command which is there in the openNMT.
but we didn't preprocess the input translation data(finnish), so why maybe the words are not replacing if not found in the vocabulory.

so please help me how to go further, to get the best results and how to preprocess the input finnish text using BPE. please send me how to use and implement this BPE algorithm to openNMT translation.

**Comment by vince62s** [comment]
If you are new to NMT, don't try to play with the code, it works fine.
go through this pipeline here: https://github.com/OpenNMT/OpenNMT-py/blob/master/tools/bpe_pipeline.sh
to understant how it works, and ask your question on the forum:
http://forum.opennmt.net/
where you may find some answers already.
thanks.
