### ISSUE TITLE
Problem in hosting the server

### ISSUE THREAD

**Issue by satty18** [OpenNMT/OpenNMT-py#878]
Traceback (most recent call last):
  File "server.py", line 115, in <module>
    debug=args.debug)
  File "server.py", line 24, in start
    translation_server.start(config_file)
  File "/Users/newomhandloom/OpenNMT-py/onmt/translate/translation_server.py", line 61, in start
    for i, conf in enumerate(self.confs["models"]):
KeyError: 'models'

**Comment by satty18** [comment]
my config file:
{
    "models_root":  #"./available_models",
    "models": [
        {
            "id": 100,
            "model": "demo-model_step_23000.pt",
            "timeout": 600,
            "on_timeout": "to_cpu",
            "load": true,
            "opt": {
                "gpu": 0,
                "beam_size": 5
            },
           
        }
    ]
}

**Comment by satty18** [comment]
server.py file:
#
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="OpenNMT-py REST Server")
    parser.add_argument("--ip", type=str, default="0.0.0.0")
    parser.add_argument("--port", type=int, default="5000")
    parser.add_argument("--url_root", type=str, default="/translator")
    parser.add_argument("--debug", "-d", action="store_true")
    parser.add_argument("--config", "-c", type=str,
                        default="./available_models/conf.json")
    args = parser.parse_args()
    start(args.config, url_root=args.url_root, host=args.ip, port=args.port,
          debug=args.debug)

**Comment by vince62s** [comment]
looks like you have an extra comma line after beam_size
