### ISSUE TITLE
Translating on the host server

### ISSUE THREAD

**Issue by satty18** [OpenNMT/OpenNMT-py#879]
#878 
I am not able to get the translation to the host server , I am getting this error when I run server.py:
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by vince62s** [comment]
post again theconfig file and command lines you used.

**Comment by satty18** [comment]
config file:
{
    "models_root": "./available_models",
    "models": [
        {
            "id": 100,
            "model": "demo-model_step_23000.pt",
            "timeout": 600,
            "on_timeout": "to_cpu",
            "load": true,
            "opt": {
                "gpu": 0,
                "beam_size": 5
            },
        },{
            "model": "demo-model_step_23000.pt",
            "timeout": -1,
            "on_timeout": "unload",
            "model_root": "../available_models",
            "opt": {
                "batch_size": 1,
                "beam_size": 10
            }
        }
    ]
}

**Comment by satty18** [comment]
and i have simply used the commands:
python server.py

**Comment by vince62s** [comment]
If you don't really understand the json format, please try a simple config, with only one model.
you are mixing up things in your file.

**Comment by satty18** [comment]
I have tried with only one model and end up getting the same result.
Please help me with the commands or if there is any mistake in my files.
Cause I am getting the 'Url not found ' error

**Comment by vince62s** [comment]
is your model in this folder "models_root": "./available_models" ?
why do you put 2 "." here: "model_root": "../available_models"
did you change server.py ?
post the output with copy paste of "python3 server.py"

**Comment by satty18** [comment]
Yeah, my model is in the same directory, also I have removed the second model. 
I have changed the server.py file in order to make it run on the host.

$ python3 server.py
 * Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [05/Aug/2018 14:56:54] "GET /models HTTP/1.1" 404 -
127.0.0.1 - - [05/Aug/2018 14:56:57] "GET /index HTTP/1.1" 200 -
127.0.0.1 - - [05/Aug/2018 14:57:09] "GET /model HTTP/1.1" 404 -
127.0.0.1 - - [05/Aug/2018 14:57:13] "GET /models HTTP/1.1" 404 -

**Comment by satty18** [comment]
here is my server.py file:
#!/usr/bin/env python
import argparse

from flask import Flask, jsonify, request
from onmt.translate import TranslationServer, ServerModelError
from flask import render_template


STATUS_OK = "ok"
STATUS_ERROR = "error"
app = Flask(__name__)

@app.route('/index')
def index():
    return render_template ('form.html')


def start(config_file,
          url_root="./translator",
          host="128.0.0.1",
          port=5000,
          debug=True):
    def prefix_route(route_function, prefix='', mask='{0}{1}'):
        def newroute(route, *args, **kwargs):
            return route_function(mask.format(prefix, route), *args, **kwargs)
        return newroute

    app.route = prefix_route(app.route, url_root)
    translation_server = TranslationServer()
    translation_server.start(config_file)

    @app.route('/models', methods=['GET'])
    def get_models():
        out = translation_server.list_models()
        return jsonify(out)

    @app.route('/clone_model/<int:model_id>', methods=['POST'])
    def clone_model(model_id):
        out = {}
        data = request.get_json(force=True)
        timeout = -1
        if 'timeout' in data:
            timeout = data['timeout']
            del data['timeout']

        opt = data.get('opt', None)
        try:
            model_id, load_time = translation_server.clone_model(
                model_id, opt, timeout)
        except ServerModelError as e:
            out['status'] = STATUS_ERROR
            out['error'] = str(e)
        else:
            out['status'] = STATUS_OK
            out['model_id'] = model_id
            out['load_time'] = load_time

        return jsonify(out)

    @app.route('/unload_model/<int:model_id>', methods=['GET'])
    def unload_model(model_id):
        out = {"model_id": model_id}

        try:
            translation_server.unload_model(model_id)
            out['status'] = STATUS_OK
        except Exception as e:
            out['status'] = STATUS_ERROR
            out['error'] = str(e)

        return jsonify(out)

    @app.route('/translate', methods=['POST'])
    def translate():
        inputs = request.get_json(force=True)
        out = {}
        try:
            translation, scores, n_best, times = translation_server.run(inputs)
            assert len(translation) == len(inputs)
            assert len(scores) == len(inputs)

            out = [[{"src": inputs[i]['src'], "tgt": translation[i],
                     "n_best": n_best,
                     "pred_score": scores[i]}
                    for i in range(len(translation))]]
        except ServerModelError as e:
            out['error'] = str(e)
            out['status'] = STATUS_ERROR

        return jsonify(out)

    @app.route('/to_cpu/<int:model_id>', methods=['GET'])
    def to_cpu(model_id):
        out = {'model_id': model_id}
        translation_server.models[model_id].to_cpu()

        out['status'] = STATUS_OK
        return jsonify(out)

    @app.route('/to_gpu/<int:model_id>', methods=['GET'])
    def to_gpu(model_id):
        out = {'model_id': model_id}
        translation_server.models[model_id].to_gpu()

        out['status'] = STATUS_OK
        return jsonify(out)



if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="OpenNMT-py REST Server")
    parser.add_argument("--ip", type=str, default="0.0.0.0")
    parser.add_argument("--port", type=int, default="5000")
    parser.add_argument("--url_root", type=str, default="/translator")
    parser.add_argument("--debug", "-d", action="store_true")
    parser.add_argument("--config", "-c", type=str,
                        default="./available_models/conf.json")
    args = parser.parse_args()
    # start(args.config, url_root=args.url_root, host=args.ip, port=args.port,
    #       debug=args.debug)
    app.run(debug=args.debug, host=args.ip, port=args.port, use_reloader=False)

**Comment by vince62s** [comment]
don't change server.py

**Comment by satty18** [comment]
here is the code, you can see if there is any error.

**Comment by vince62s** [comment]
okay I don't have to time to help you further, ask on the forum. http://forum.opennmt.net
server.py works fine, it is not an "issue".

**Comment by satty18** [comment]
Thank you for the help.
I am looking into it.
