### ISSUE TITLE
Why the training process just quit when I restarted training from the checkpoint ?

### ISSUE THREAD

**Issue by 1130310223** [OpenNMT/OpenNMT-py#886]
I got a pre-trained model named `opensubtitles_step_200000.pt`, and I want to restart training from this checkpoint by using
`python train.py -data data/opensubs_data -gpuid 0 -train_steps 100000  -save_model ./opensubtitles_new  -train_from ./models/opensubtitles/opensubtitles_step_200000.pt` .
However, the program suddenly terminated after loading the data,
`[2018-08-08 19:08:49,037 INFO] Start training...`
`[2018-08-08 19:08:51,225 INFO] Loading train dataset from data/opensubs_data.train.1.pt, number of examples: 1224870`
I had tried several times on different GPUs but I ran into the same situation. Now I don't know what the problem is.

**Comment by vince62s** [comment]
you need to set train_steps to 300000.

**Comment by 1130310223** [comment]
thank you ：）
