### ISSUE TITLE
Zero gradients within truncated BPTT

### ISSUE THREAD

**Issue by aswinsuresh** [OpenNMT/OpenNMT-py#891]
https://github.com/OpenNMT/OpenNMT-py/blob/6b93582884a6df6417e5b9cda4e5cd3445fe1a91/onmt/trainer.py#L279

The gradients are being set to zero within the inner loop for truncated BPTT. Shouldn't this be done in the outer loop instead ?

**Comment by vince62s** [comment]
no it's fine but we should make it clearer that BPTT and accum_count > 1 are not compatible.

**Comment by aswinsuresh** [comment]
Do you mean truncated BPTT and accum_count == 1 ? Right now, if accum_count == 1 and there is truncated BPTT, the gradients are being set to zero before forward propagating for each trunc. This does not seem right to me. Kindly correct me if I am wrong.

**Comment by vince62s** [comment]
There is a bug, it has been introduced by my refactoring from June.
I'll try to fix it.
It is good to zero the gradients before each trunc, but we need to update the parameters also.
I mixed up when implementing the multi-gpu part.

**Comment by vince62s** [comment]
@aswinsuresh Can you test #926 and let me know if it works for you ?
