### ISSUE TITLE
Wrong implementation of Bahdanau Attention

### ISSUE THREAD

**Issue by Luolc** [OpenNMT/OpenNMT-py#892]
Hi there.

I find that there might be a mistake of the implementation of Bahdanau Attention at https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/global_attention.py#L80

As the [comment](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/global_attention.py#L58) shows, there should be no bias term in line 80.

We can also confirm the equation in the [original paper (page 12)](https://arxiv.org/pdf/1409.0473.pdf), as well as the [implementation in tensorflow](https://github.com/tensorflow/tensorflow/blob/r1.10/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py#L550-L551).

Please correct me if I was wrong. :-) thx

**Comment by rbommasanimozilla** [comment]
This has been pointed out previously. The difference is minor, and clearly an affine map which learns a bias of zero simplifies to the linear map given in the paper. We see that even the more significant discrepancy between additive and multiplicative attention has a marginal impact on model performance, and this is significantly more minor and probably isn't worth changing (and it can easily be changed on a per user basis if desired).

**Comment by Luolc** [comment]
Okay, I see.

I agree that this is minor and likely to make no difference to the performance. It is ok for me to change it by myself or just ignore it.

But well, I think it is always good to be faithful to the original paper when coding. :-)

I can make a PR if others don't want to waste time on it. :D

And I am just fine to keep it if most maintainers think it isn't worth changing.
