### ISSUE TITLE
contribute a debug for -log_file

### ISSUE THREAD

**Issue by ColainCYY** [OpenNMT/OpenNMT-py#893]
Hi! I have found that the `-log_file` in command line didn't work. OPEN-NMT always print logs to stdout, not my file. I read the onmt/utils/logging.py. There is a missing `else`:
```
def init_logger(log_file=None):
    log_format = logging.Formatter("[%(asctime)s %(levelname)s] %(message)s")
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)

    if log_file and log_file != '':
        file_handler = logging.FileHandler(log_file)
        file_handler.setFormatter(log_format)
        logger.addHandler(file_handler)
    # else: the below three lines of code should be under a "else"
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(log_format)
    logger.handlers = [console_handler]

    return logger
```

Please help check my code. I have test it but wonder whether it is proper. Thanks!

**Comment by pltrdy** [comment]
Hi! Thanks for pointing the problem and suggesting solution. 
I suggest fixing it by moving the "if" statement at the end of the function. It allows logging to both console and file at the same time.
