### ISSUE TITLE
Why -epochs in train.py is deprecated?

### ISSUE THREAD

**Issue by tagucci** [OpenNMT/OpenNMT-py#894]
When starting to train the summarization model following [Summarization.md](https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/Summarization.md), the code raises an assertion:  `-epochs is deprecated please use -train_steps`. 
Why did train.py remove -epochs? And are there any ways to select concrete number of epochs not -train_steps.

**Comment by pltrdy** [comment]
There's no direct way, but you can approximate: given that a step basically trains `n_batch x n_gpu` sequences at a time, calculate how many steps corresponds to an epoch.

**Comment by vince62s** [comment]
same as #866
