### ISSUE TITLE
PositionalEncoding Formulation

### ISSUE THREAD

**Issue by PetrochukM** [OpenNMT/OpenNMT-py#896]
@srush Hey! Looking back through the commits, I noticed you edited the positional encoding formula to be ``torch.exp(-2i * log(10000) / d_model)`` instead of`` torch.pow(10000, 2i / d_model)``. The equations are equivalent but I cannot find justification for why you did that.

**Comment by PetrochukM** [comment]
Please reopen this, this is still a legitimate question. It's not obvious or clear why this was done.

**Comment by vince62s** [comment]
I'm pretty sure there is no specific reason, it was just a few lines refactor in a block.
I'll leave it open for @srush ....

**Comment by PetrochukM** [comment]
Thanks! It's a non-obvious reformulation that is not aligned with the paper. I am thinking there may be numerical stability reasons for rewriting it, but I cannot find any.

**Comment by guillaumekln** [comment]
This formulation is coming directly from the reference implementation over at [Tensor2Tensor](https://github.com/tensorflow/tensor2tensor/blob/v1.8.0/tensor2tensor/layers/common_layers.py#L1350-L1353). I did not verify myself but I think it is a more efficient formulation, at least in TensorFlow graphs.

**Comment by PetrochukM** [comment]
Gotcha, Thanks!
