### ISSUE TITLE
Is there any way to visualize attention?

### ISSUE THREAD

**Issue by wonkeelee** [OpenNMT/OpenNMT-py#897]
Hi, I'm now experimenting with NMT model based on transformers.

I wonder how there is a way to visualize the results of attention (self attention) like the appendix of the 'Attention is All you need' below. 

Thanks! 👍 

<img width="512" alt="attn_example" src="https://user-images.githubusercontent.com/33458788/44013691-06e83532-9f02-11e8-81b8-1dc0d789b23f.PNG">

**Comment by rbommasanimozilla** [comment]
I believe you can obtain attention weights with the attention debug flag and then use those for visualization as you wish, but I have not tried this

**Comment by ColainCYY** [comment]
I have tried -atten_debug. I found it is for global-attention between source words and target words, not for self-attention within source words.

**Comment by vince62s** [comment]
Also you may read this: http://nlp.seas.harvard.edu/2018/04/03/attention.html
