### ISSUE TITLE
Out of Memory in Translation

### ISSUE THREAD

**Issue by rbommasanimozilla** [OpenNMT/OpenNMT-py#899]
I am currently running inference for summarization models (seq2seq attention + copying) and even with a batch size of 1 (beam size of 5 or 10) I run out of memory using a single Titan X Pascal (11GB memory) in translation (roughly 30k examples into my 100k test test, never in the same spot so I doubt it is one particularly long example). I have played with the batch size and obviously a batch size of 1 holds of the problem as long as possible, but I am not sure if there any other suggestions (cannot currently use the -fast flag as I am using copy_attention). Any advice? Would specifying a tighter set of upper and lower bounds on summarization be needed?
My inference command: (training command is default command from summarization tutorial up to converting epochs to steps)

python translate.py -model /newsroom_step_250000.pt -output /newsroom_step_250000.out -gpu 0 -batch_size 1 -beam_size 10 -src /newsroom-tagged/val.txt.srcp -min_length 5 -stepwise_penalty -coverage_penalty summary -beta 5 -length_penalty wu -alpha 0.9 -block_ngram_repeat 3 -ignore_when_blocking "." "</t>" "<t>"

Model Hyperparams:
1024 dim word embeddings (Not shared)
BRNN encoder, RNN decoder, 512 dimensional
2 encoder layers, 1 decoder layer
138M params

**Comment by alphadl** [comment]
trying to reduce your batch_size /  word_emb_size  / rnn_size

**Comment by rbommasanimozilla** [comment]
1. i assume you mean inference batch size, which i have to 1
2. currently running models, but i have had this problem for even smaller models (256,256 for word embedding/rnn size respectively)

**Comment by alphadl** [comment]
Have you observed your "GPU memory usage" through the command "nvidia-smi -l" ？

**Comment by vince62s** [comment]
try beam 4 or 5, it should not degrade too much the performance.

**Comment by rbommasanimozilla** [comment]
Without the fast flag, do batches not get parallelized properly on GPU? Currently, translating for a fix length (10 hours), the number of translated sentences is monotonically decreasing rather than increasing for me in the batch size (going from batch sizes of 1 to 16, scaling up by a factor of 2 with beam sizes of 5 and 10)

**Comment by rbommasanimozilla** [comment]
Here is the explicit results I get (after 10 hours for each inference setting, each on a separate Titan X Pascal):
Batch Size, Beam Size: MB of translation output
1,5:
2,5:
4,5:
8,5:
16,5:
1,10:
2,10:
4,10:
8,10:
16,10:

**Comment by guillaumekln** [comment]
Your out of memory issue is related to [PyTorch's caching allocator](https://pytorch.org/docs/stable/notes/cuda.html#cuda-memory-management) that I think is sometimes too optimistic about available memory. To constrain the memory usage, you can try calling `torch.cuda.empty_cache()` from the code, e.g. after each decoding loop:

```diff
diff --git a/onmt/translate/translator.py b/onmt/translate/translator.py
index b893f12..fe5d861 100644
--- a/onmt/translate/translator.py
+++ b/onmt/translate/translator.py
@@ -587,6 +587,8 @@ class Translator(object):
                           beam_attn.data[:, j, :memory_lengths[j]])
                 dec_states.beam_update(j, b.get_current_origin(), beam_size)
 
+            torch.cuda.empty_cache()
+
         # (4) Extract sentences from beam.
         ret = self._from_beam(beam)
         ret["gold_score"] = [0] * batch_size
```

> Without the fast flag, do batches not get parallelized properly on GPU?

They are parallelized when forwarded in the model but not during the beam search.

**Comment by rbommasanimozilla** [comment]
Shouldn't parallelism across the forward passes over the  model lead to a significant time-saving per example by batching (i.e. the opposite of what I am seeing), especially for a large model?

**Comment by guillaumekln** [comment]
Sure, but I think recent measurements showed that when the batch size increase you loose more time in beam search that you gain in the forward pass. This is the motivation for providing a revamped beam search with the `-fast` flag.
