### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'float32'

### ISSUE THREAD

**Issue by SimlaBurcu** [OpenNMT/OpenNMT-py#900]
I run the command `python translate.py -model averaged-10-epoch.pt -src data/test.txt -output pred.txt -replace_unk -verbose` 
I have pytorch 0.4.0 and torchtext 0.3.0 installed, but I am getting the following error:
```bash
Traceback (most recent call last):
  File "translate.py", line 7, in <module>
    from onmt.utils.logging import init_logger
  File "/home/simla/nmt/OpenNMT-py/onmt/__init__.py", line 4, in <module>
    import onmt.inputters
  File "/home/simla/nmt/OpenNMT-py/onmt/inputters/__init__.py", line 6, in <module>
    from onmt.inputters.inputter import collect_feature_vocabs, make_features, \
  File "/home/simla/nmt/OpenNMT-py/onmt/inputters/inputter.py", line 11, in <module>
    import torchtext.data
  File "/home/simla/venv/lib/python3.6/site-packages/torchtext/__init__.py", line 1, in <module>
    from . import data
  File "/home/simla/venv/lib/python3.6/site-packages/torchtext/data/__init__.py", line 4, in <module>
    from .field import RawField, Field, ReversibleField, SubwordField, NestedField, LabelField
  File "/home/simla/venv/lib/python3.6/site-packages/torchtext/data/field.py", line 61, in <module>
    class Field(RawField):
  File "/home/simla/venv/lib/python3.6/site-packages/torchtext/data/field.py", line 115, in Field
    torch.float32: float,
AttributeError: module 'torch' has no attribute 'float32'
```

**Comment by rbommasanimozilla** [comment]
What command did you run/how was the error produced?

**Comment by SimlaBurcu** [comment]
Oh sorry, I forgot to write that! I have just edited my question.

**Comment by vince62s** [comment]
4.0.4 is not a pytorch version, do you mean 0.4.0 or 0.4.1 ?
also what if you use gpu to translate ?

**Comment by SimlaBurcu** [comment]
I meant 0.4.0, sorry about that. I tried to run with gpu as well, same error again.

**Comment by SimlaBurcu** [comment]
I did, it gives the same error again.

**Comment by vince62s** [comment]
are you having the issue onmy with the translate command ? remove the replace_unk
but I think your issue is an installation issue.

**Comment by SimlaBurcu** [comment]
I tried removing it, again the same. I think you're right but I couldn't find how to fix it.
I first cloned the OpenNMT project 2.5 months ago and I still have that version and it works fine (but with pytorch=0.2.0 and torchtext==0.2.3). Recently, I cloned the latest version of OpenNMT and reinstalled pytorch and torchtext with the proper versions (pytorch 0.4.0 and torchtext 0.3.0), and I am getting this error.

**Comment by vince62s** [comment]
Did you try in a clean install with anaconda ?

**Comment by vince62s** [comment]
closing, reopne if needed.

**Comment by tangxiangru** [comment]
i need it. same bug

**Comment by vince62s** [comment]
post your full config (pytorch, torchtext, python versions) and commandl ines

**Comment by navneetkrc** [comment]
torchtext is the offending …?module?..(not sure what to call it) that causes this error. The authors released torchtext 0.3.1 earlier today (2018-10-11). Installing the previous version restores full functionality:
!{sys.executable} -m pip install torchtext==0.2.3

**Comment by SINDHUKUMARIP** [comment]
i got the same issue.
pip install torchtext==0.2.3
you need to change version of torchtext

**Comment by Hunterhuan** [comment]
> i got the same issue.
> pip install torchtext==0.2.3
> you need to change version of torchtext

Thanks! It solve my problem!

**Comment by louielu1027** [comment]
Same issue.
pip install torchtext==0.2.3, but not work!
I use pytorch 0.3.1+python2.7.
