### ISSUE TITLE
Details of the pre-trained models

### ISSUE THREAD

**Issue by adrianjav** [OpenNMT/OpenNMT-py#901]
Hello,
do you guys have the exact parameters that were used to train the models that you provide on the wiki? For example, [the model in the im2text page](http://opennmt.net/OpenNMT-py/im2text.html).

I'm writing a paper comparing different encoders with a new one I propose and it would be handy to have that information (to actually comparing others' models rather than others models I've trained myself).

Thank you in advance

**Comment by da03** [comment]
Sure, it's just the training command in that page.

**Comment by da03** [comment]
Oh sorry just noticed that epochs is deprecated in favor of training_steps now. But I generally train for 20 epochs.

**Comment by adrianjav** [comment]
I see, I was afraid that the model could've been trained with different hyperparameters to make it work better.
I'll close the issue. Thank you again.
