### ISSUE TITLE
the attention of transformer decoder used by beam search

### ISSUE THREAD

**Issue by tanaka-jp** [OpenNMT/OpenNMT-py#903]
https://github.com/OpenNMT/OpenNMT-py/blob/6b93582884a6df6417e5b9cda4e5cd3445fe1a91/onmt/modules/multi_headed_attn.py#L184-L201

I am investigating the source code of beam search in transformer.
I found that the attention used by beam search is the attention of the top head in the last decoder layer .

I can not understand the source code of this part.
Why not use other head's attn?
Is it mentioned in a paper somewhere.

I think maybe it should be like this.

idx = the best one of the attn
top_attn = attn.view(batch_size, head_count, query_len, key_len)[:, idx, :, :].contiguous()

**Comment by guillaumekln** [comment]
> idx = the best one of the attn

How would you compute that?

No attention heads are constrained to produce alignments so the code arbitrarily select the first one.

**Comment by tanaka-jp** [comment]
> How would you compute that?

Yes, that is a problem.

It looks like that the attn is used only when attn_debug and replace_unk are specified.
So , if I don't use this two parameters, attn is not necessary.
Am i right ?

**Comment by guillaumekln** [comment]
> So , if I don't use this two parameters, attn is not necessary.

Yes, it's only to comply with the decoder interface that should return attention as alignment information.

**Comment by tanaka-jp** [comment]
I got it. 
Thank you very much
