### ISSUE TITLE
Do you have any future plan to support ELMo ?

### ISSUE THREAD

**Issue by 1130310223** [OpenNMT/OpenNMT-py#905]
ELMo calculates word embeddings based on sentences, so there are some difficulties when directly using the pre-trained embedding APIs from OpenNMT-py . Can you give me any advice on how to use ELMo under current OpenNMT ?

**Comment by goncalomcorreia** [comment]
Yes, I am currently implementing this, along with a trainable language model that you can train to get ELMo embeddings in any language! I will do a Pull Request soon.

**Comment by 1130310223** [comment]
That's great 👍

**Comment by Ovis85** [comment]
Hi All,

any word on this project?

**Comment by eduamf** [comment]
> Hi All,
> 
> any word on this project?

Good question. The ELMo entry uses char in a CNN. OpenNMT-py accept bidirectional LSTM. I must review the changes on OpenNMT-py since 2018!
