### ISSUE TITLE
validation_metric not supported

### ISSUE THREAD

**Issue by AmitMY** [OpenNMT/OpenNMT-py#907]
I want to see BLEU scores while training. For that, I saw a parameter called "validation_metric" which can get "bleu" as a value, and calculate the bleu score in training time for validation.
http://opennmt.net/OpenNMT/options/train/#trainer-options

Is this not implemented in the python version? I know how to calculate BLEU after the fact, but I am interested to know the rate of improvement (and maybe graph it out)

**Comment by vince62s** [comment]
What you saw in implemented in the LUA version of OpenNMT.
PR are welcome for this request.

**Comment by vince62s** [comment]
I'll close this and add it in Projects in case someone is interested in picking it up.
