### ISSUE TITLE
what is the optimal way(param) for decoding with transformer?

### ISSUE THREAD

**Issue by wonkeelee** [OpenNMT/OpenNMT-py#908]
I wonder what hyper parameter set is best for the Transformer NMT.
can you recommend it something like an example below? Thanks!!

`python translate.py -model ... -src ... -length_penalty .. -coverage_penalty .. -alpha .. -beta ..`

**Comment by vince62s** [comment]
There is no magic rule, it depends on the task (translation, summarization, audio, image, ...) and also on the dataset.

**Comment by wonkeelee** [comment]
@vince62s 

Thank you for your response. Then, let me ask you another way.. 
Can I ask which hyperparameter was used to decode the pretrained model?

thanks!

**Comment by vince62s** [comment]
Just default values.
