### ISSUE TITLE
Out of memory in Summarization example

### ISSUE THREAD

**Issue by ailurus1991** [OpenNMT/OpenNMT-py#915]
Hey guys,

I was trying to run an summarization example with Giga dataset in documentation. I found it was killed cuz out of memory (64GB). I tried to reduce the rnn_size to 128 and batch_size to 4, still oom.

any suggestion?

**Comment by da03** [comment]
Did you mean out of RAM but not GPU memory? Maybe consider using -max_shard_size during preprocessing, to split files into multiple chunks in order to avoid loading them to memory all at once.
