### ISSUE TITLE
Different number of layers in encoder and decoder

### ISSUE THREAD

**Issue by pluiez** [OpenNMT/OpenNMT-py#917]
Hi, I'm trying to specify "-rnn_type GRU -enc_type brnn -enc_layers 1 -dec_layers 2", which defines a bidirectional GRU encoder along with 2-layer decoder, leaving the rest as default.

Then an IndexError is raised:
`IndexError: index 1 is out of bounds for dimension 0 with size 1`

Although the decoder is defined as a 2-layer stacked RNN, its initial state is derived from the encoder. In this case, the decoder's initial state is only one single hidden state wrapped in a list. Then an IndexError would raise during decoder rnn forward while trying to access the "second" hidden state in the decoder's initial state . 

I'm not sure is this a bug or design intention that expecting the same number of layers in both encoder and decoder? 

By the way, I'm recently running comparative experiments against different number of layers in the encoder and leave the decoder unchanged. However both my own implementations and nematus converge to a poor performance in the multi-layer encoder and one-layer decoder scenario. 

I'm not sure what's wrong and thus turn to openNMT for the same experiments. Is multi-layer encoder plus one-layer decoder a bad idea itself?

Any suggestions would be really appreciated!

**Comment by rbommasanimozilla** [comment]
You are correct that you cannot have the encoder-decoder design you have. However, I am not sure if I understood the second part of what you said correctly. It is possible to have a configuration of encoder-decoder layers of the form:
n encoder layers
k decoder layers
as long as n is at least k. While other ways of initializing the decoder can be amenable to having combinations of n encoder layers and k decoder layers where k exceeds n, this is currently not possible (though there are some papers that find such configurations are optimal for NMT in particular).

**Comment by vince62s** [comment]
Right by design this is not possible right now.
I'm wondering if onmt-tf offers this in some aspect, @guillaumekln  ?

**Comment by guillaumekln** [comment]
Isn't it already supported with the `-bridge` flag?

**Comment by vince62s** [comment]
Well no I don't think so, as is, it seems to be a simple copy bridge, not the same as in onmt-tf.

**Comment by S09P** [comment]
can any of you provide a yaml file for a multilayer lstm model or for n encoder k decoder model.
currently i am using this yaml file 
## Where the samples will be written
save_data:  Data1/run/example
## Where the vocab(s) will be written
src_vocab: Data1/run/example.vocab.src
tgt_vocab:  Data1/run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src:  Data1/trainen.en
        path_tgt:  Data1/trainhi.hi
    valid:
        path_src:  Data1/dev.en
        path_tgt:  Data1/dev.hi

# Vocabulary files that were just created
src_vocab:  Data1/run/example.vocab.src
tgt_vocab:  Data1/run/example.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: Data1/run/model
save_checkpoint_steps: 500
train_steps: 1000
valid_steps: 500
@guillaumekln @rbommasanimozilla @pluiez @vince62s @smartkiwi
