### ISSUE TITLE
cannot load the whole dataset when executing train.py; early termination

### ISSUE THREAD

**Issue by yuxin1210** [OpenNMT/OpenNMT-py#918]
Hi, I am trying to train a model by executing the train.py script but ran into this problem. This line

> Loading train dataset from ../sumdata/giga/syntax_model.train.1.pt, number of examples: 466246

> 
appears three times while the other train.pt did not get to be loaded. And the process terminates before training starts. Can anyone tell me what is happening here?

> [2018-08-24 06:20:37,847 INFO] Loading train dataset from ../sumdata/giga/syntax_model.train.1.pt, number of examples: 466246
[2018-08-24 06:20:38,193 INFO]  * vocabulary size. source = 110004; target = 110004
[2018-08-24 06:20:38,193 INFO] Building model…
[2018-08-24 06:21:07,713 INFO] NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(110004, 128, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(128, 256, bidirectional=True)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(110004, 128, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.0)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.0)
      (layers): ModuleList(
        (0): LSTMCell(640, 512)
      )
    )
    (attn): GlobalAttention(
      (linear_context): Linear(in_features=512, out_features=512, bias=False)
      (linear_query): Linear(in_features=512, out_features=512, bias=True)
      (v): Linear(in_features=512, out_features=1, bias=False)
      (linear_out): Linear(in_features=1024, out_features=512, bias=True)
      (softmax): Softmax()
      (tanh): Tanh()
    )
  )
  (generator): CopyGenerator(
    (linear): Linear(in_features=512, out_features=110004, bias=True)
    (linear_copy): Linear(in_features=512, out_features=1, bias=True)
    (softmax): Softmax()
    (sigmoid): Sigmoid()
  )
)
[2018-08-24 06:21:07,714 INFO] encoder: 14871040
[2018-08-24 06:21:07,714 INFO] decoder: 59846069
[2018-08-24 06:21:07,714 INFO] * number of parameters: 74717109
[2018-08-24 06:21:07,728 INFO] Start training…
[2018-08-24 06:22:16,305 INFO] Loading train dataset from ../sumdata/giga/syntax_model.train.1.pt, number of examples: 466246
[2018-08-24 06:23:51,152 INFO] Loading train dataset from ../sumdata/giga/syntax_model.train.1.pt, number of examples: 466246

**Comment by da03** [comment]
Weird, can you send the command used for preprocessing and training?

**Comment by vince62s** [comment]
are you on master ?

**Comment by yuxin1210** [comment]
> are you on master ?

I just checked that the current branch is the master...if that is what you are asking?

**Comment by vince62s** [comment]
A previous bug was logging things several times, but unrelated.
why are you training only 20 steps ? it's only 20 "iterations", for sure you're not going very far :)

**Comment by yuxin1210** [comment]
> why are you training only 20 steps ? it's only 20 "iterations"
Thanks for pointing that out! I change it to 120000 steps and can observe that it starts training, but I still don't see the logs of loading other parts of the dataset...I wonder if it is training using all the samples???

**Comment by vince62s** [comment]
use the training option -report_every 100
you will see a log each 100 steps and you can monitor.

**Comment by yuxin1210** [comment]
I guess I did not make it clear. So far I have seen this log

> [2018-08-24 11:27:15,553 INFO] Loading train dataset from ../sumdata/giga/syntax_model.train.1.pt

only for the first shard, but there is no such log for loading train.2.pt, train.3.pt etc. Therefore, I am not sure whether it has loaded all the data.

During training it is reporting every 50 steps (by default) like this:

> [2018-08-24 11:52:43,241 INFO] Step 1150/120000; acc:  69.57; ppl:  4.19; xent: 1.43; lr: 0.10000; 1274/2066 tok/s;   1528 sec

which does not tell  how many samples in total are used for training as well...

**Comment by vince62s** [comment]
You are using the default sentence batch, ie batch 64 = 64 sentences (examples).
Your first shard says 466246 examples, which means it requires 7285 steps to complete.
so after Step 7285/120000 you will see loading of shard 2.

**Comment by yuxin1210** [comment]
> so after Step 7285/120000 you will see loading of shard 2.

Thanks for the explanation!  My first shard should complete at step 14210, but then my process was killed by the kernel just before it loads the second shard due to "out of memory".

**Comment by fermat97** [comment]
I have almost similar problem, I have 5 shards, each of which almost 5 million sentences. And I set train steps 1000, and I use two GPUs. But the training is over after almost half an hour and it only shows loading the first shard. And I dont receive any error for out-of-memory issues. I use bachsize of 8. I assumed each iteration should be run on whole 5 shards, is that true?

**Comment by amansharma00a** [comment]
I am facing the same issue , 
[2019-03-01 22:08:57,750 INFO]  * src vocab size = 24997
[2019-03-01 22:08:57,750 INFO]  * tgt vocab size = 35820
[2019-03-01 22:08:57,750 INFO] Building model...
[2019-03-01 22:11:51,932 INFO] NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(24997, 500, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(500, 500, num_layers=2, dropout=0.3)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(35820, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.3)
      (layers): ModuleList(
        (0): LSTMCell(1000, 500)
        (1): LSTMCell(500, 500)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=500, out_features=500, bias=False)
      (linear_out): Linear(in_features=1000, out_features=500, bias=False)
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=500, out_features=35820, bias=True)
    (1): Cast()
    (2): LogSoftmax()
  )
)
[2019-03-01 22:11:51,933 INFO] encoder: 16506500
[2019-03-01 22:11:51,933 INFO] decoder: 41613820
[2019-03-01 22:11:51,933 INFO] * number of parameters: 58120320
[2019-03-01 22:11:51,938 INFO] Starting training on GPU: [0, 1, 2, 3, 4]
[2019-03-01 22:11:51,938 INFO] Start training loop and validate every 10000 steps...
[2019-03-01 22:11:52,183 INFO] Loading dataset from data/200k/demo.train.0.pt, number of examples: 10000

CUDA_VISIBLE_DEVICES=4,5,6,7 python train.py -data data/200k/demo -save_model data/200k/demo-model -save_checkpoint_steps 100 -world_size 4 -batch_size 64 -gpu_ranks 0 1 2 3 -report_every 20

**Comment by ladyhodhod** [comment]
I have the same issue. The training process gets killed right after trying to load the second shard.
It first gets stuck at this point: [2020-09-03 13:05:22,211 INFO] Loading dataset from data/cnndm/CNNDM.train.1.pt
then the whole process crashes with no visible errors, not even an out of memory error.

What is the problem? 

Thank you
