### ISSUE TITLE
BUG: while initializing the beams

### ISSUE THREAD

**Issue by wasiahmad** [OpenNMT/OpenNMT-py#920]
Isn't the [line](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/beam.py#L41) wrong? 
```
# The outputs at each time-step.
self.next_ys = [self.tt.LongTensor(size).fill_(pad)]
self.next_ys[0][0] = bos
```

We should initialize all the beams with 'bos'. Why do we only initialize one beam with 'bos' and leave the other beam initialized to 'pad'?

**Comment by guillaumekln** [comment]
For the first step, only the result of the first beam is considered. The rest is ignored and this initialization reflect that.
