### ISSUE TITLE
beam

### ISSUE THREAD

**Issue by weiwancheng** [OpenNMT/OpenNMT-py#924]

**Comment by weiwancheng** [comment]
It seems that beam search not always ends with 'EOS' symbol.so, i got many same result. can you tell me how beam search ends with 'EOS' ?

**Comment by vince62s** [comment]
are you using the -fast flag in translate.py ?

**Comment by weiwancheng** [comment]
Thank you for your reply. In my code have no -fast flag. I use the API as follow:

inference_decoder = BeamSearchDecoder( cell=self.decoder_cell, embedding=embed_and_input_proj, start_tokens=start_tokens, end_token=end_token, initial_state=self.decoder_initial_state, beam_width=self.beam_width, output_layer=self.decoder_output_projection, )
...
(self.decoder_outputs_decode,self.final_state,_ )= (seq2seq.dynamic_decode( decoder=inference_decoder, output_time_major=self.time_major, occurs maximum_iterations=max_decode_step, swap_memory=True, scope=decoder_scope ))

**Comment by guillaumekln** [comment]
This has nothing to do with PyTorch.
