### ISSUE TITLE
Hi , I have 130k train src tgt pairs, but the log info  of training process shows that there are only 22k train pairs after we preprocess the data 

### ISSUE THREAD

**Issue by zhaoguangxiang** [OpenNMT/OpenNMT-py#925]
Loading train dataset from data/***.train.1.pt, number of examples: 22307

the train  src and tgt  sentences are written to src-train.txt and tgt-train.txt respectively.

**Comment by zhaoguangxiang** [comment]
the train  src and tgt  sentences are written to src-train.txt and tgt-train.txt respectively.

**Comment by vince62s** [comment]
please use http://forum.opennmt.net/
