### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by TB-SeChaJia** [OpenNMT/OpenNMT-py#929]

**Comment by vince62s** [comment]
Please provide your pytorch + torchtext version and the command line you used

**Comment by TB-SeChaJia** [comment]
torchtext version=="0.2.3"
python3 train.py -data ./output/pre-data/demo

**Comment by bpopeters** [comment]
That version of torchtext is out of date. Try running

```
pip install -r requirements.txt
```

and see if things get better (this will also ensure that you're running an up-to-date version of pytorch).

**Comment by vince62s** [comment]
duplicate of #930
