### ISSUE TITLE
src_vocab and tgt_vocab tokens are ignored if token does not appear in corpus during preprocessing

### ISSUE THREAD

**Issue by Henry-E** [OpenNMT/OpenNMT-py#945]
I haven't looked yet into the code of why this happens but worth mentioning here.

If you specify a src or tgt vocab file when preprocessing a dataset, words which do not appear in the data / corpus but do appear in the vocab file are effectively ignored. This is not exactly expected. The correct behaviour would mean that there are empty / non-updating vectors in the vocab but this is useful to have for when doing post-training on different corpuses.

**Comment by murthyrudra** [comment]
Hi, I had faced a similar issue. The problem arises due to code in line 310 to 314 in file onmt/inputters/inputter.py.

        for path in train_dataset_files:

               dataset = torch.load(path)
               logger.info(" * reloading %s." % path)
               for ex in dataset.examples:
                   for k in fields:
                       val = getattr(ex, k, None)
                       if val is not None and not fields[k].sequential:
                           val = [val]
                       elif k == 'src' and src_vocab:
                           val = [item for item in val if item in src_vocab]
                       elif k == 'tgt' and tgt_vocab:
                           val = [item for item in val if item in tgt_vocab]
                       counter[k].update(val)

        _build_field_vocab(fields["tgt"], counter["tgt"], max_size=tgt_vocab_size,
                       min_freq=tgt_words_min_frequency)
        logger.info(" * tgt vocab size: %d." % len(fields["tgt"].vocab))

The `counter` variable is used to build the vocabularies. I manually updated the `counter` variable after the code to include all words from the `src_vocab` and `tgt_vocab` lists.

**Comment by vince62s** [comment]
Can one of the two of you submit a PR ? or we'll just close this.
thanks.
