### ISSUE TITLE
"-fix_word_vecs_enc" triggers an error when reloading an existing model

### ISSUE THREAD

**Issue by murthyrudra** [OpenNMT/OpenNMT-py#950]
Hi, I was training the Transformer model with the options as specified in [http://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-the-transformer-model](link). The training works fine, but the problem arises when i stop the training and resume the training using the option `train_from`. I get the following error:

        Traceback (most recent call last):
          File "train.py", line 40, in <module>
            main(opt)
          File "train.py", line 27, in main
            single_main(opt)
          File "/home/rudra/OpenNMT-py/onmt/train_single.py", line 113, in main
            optim = build_optim(model, opt, checkpoint)
          File "/home/rudra/OpenNMT-py/onmt/utils/optimizers.py", line 62, in build_optim
            optim.optimizer.load_state_dict(saved_optimizer_state_dict)
          File "/home/rudra/miniconda3/envs/py36/lib/python3.6/site-packages/torch/optim/optimizer.py", line         107, in load_state_dict
            raise ValueError("loaded state dict contains a parameter group "
        ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

The error occurs when the model tries to load the optimizer state in the File utils/optimizers.py line 62. Could anyone please help me in debugging this error?

**Comment by vince62s** [comment]
Give your command lines, both the first initial training and the train_from

**Comment by murthyrudra** [comment]
Hi, the initial command I ran was

    CUDA_VISIBLE_DEVICES=1 python train.py -data data/demo -save_model model-transformer-baseline 
    -pre_word_vecs_enc data/embeddings.enc.pt -word_vec_size 300 -gpuid 1 -encoder_type transformer 
    -decoder_type transformer -layers 5 -rnn_size 300 -transformer_ff 500 -heads 5 -fix_word_vecs_enc 
    -max_generator_batches 2 -dropout 0.1 -batch_size 4096 -batch_type tokens -normalization tokens 
    -accum_count 2 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 
    -learning_rate 1 -max_grad_norm 0 -param_init 0  -param_init_glorot -label_smoothing 0.1 
    -valid_steps 5000 -save_checkpoint_steps 5000

I stopped the training after 5000 steps and ran the following command

    CUDA_VISIBLE_DEVICES=1 python train.py -data data/demo -save_model model-transformer-baseline 
    -pre_word_vecs_enc data/embeddings.enc.pt -word_vec_size 300 -gpuid 1 -encoder_type transformer 
    -decoder_type transformer -layers 5 -rnn_size 300 -transformer_ff 500 -heads 5 -fix_word_vecs_enc 
    -max_generator_batches 2 -dropout 0.1 -batch_size 4096 -batch_type tokens -normalization tokens 
    -accum_count 2 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 
    -learning_rate 1 -max_grad_norm 0 -param_init 0  -param_init_glorot -label_smoothing 0.1 
    -valid_steps 5000 -save_checkpoint_steps 5000 -train_from model-transformer-baseline_step_5000.pt

**Comment by vince62s** [comment]
it might not be theproblem but you are not on master. line 62 of optimizer.py is not the same.
git pull and repost the error.

**Comment by murthyrudra** [comment]
Hi, I cloned the master branch and ran the model using the same command as earlier. I am getting the same error. I am using PyTorch 0.4.0 and Cuda 9.0

**Comment by vince62s** [comment]
I need the error trace to see the lines number

**Comment by murthyrudra** [comment]
Hi, the error occurs when the optimizer tries to load the saved state, specifically in the code optim/optimizer.py in https://github.com/pytorch/pytorch/blob/master/torch/optim/optimizer.py line 107. I tried printing the contents of `groups` and `saved_groups` and the `groups` has length of 218 whereas `saved_groups` has length of 217 and the individual contents are in the attached file
[error.txt](https://github.com/OpenNMT/OpenNMT-py/files/2359639/error.txt)

**Comment by murthyrudra** [comment]
Hi, Please find the error traceback:
    
    traceback (most recent call last):
      File "train.py", line 40, in <module>
        main(opt)
      File "train.py", line 27, in main
        single_main(opt)
      File "/home/rudra/NMT/OpenNMT/OpenNMT-py/onmt/train_single.py", line 112, in main
        optim = build_optim(model, opt, checkpoint)
      File "/home/rudra/NMT/OpenNMT/OpenNMT-py/onmt/utils/optimizers.py", line 51, in build_optim
        optim.optimizer.load_state_dict(saved_optimizer_state_dict)
      File "/home/rudra/miniconda3/envs/py36/lib/python3.6/site-packages/torch/optim/optimizer.py", line 107, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
    ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

**Comment by vince62s** [comment]
can  you remove this -pre_word_vecs_enc data/embeddings.enc.pt (and maybe the -fix_word_vecs_enc) from the second command line ?

**Comment by murthyrudra** [comment]
Hi, I am getting the same error. The error occurs when it tries to load the previously stored Optimizer's state. I did try bypassing the loading of Optimizer's state, but that results in perplexity being Nan values.

**Comment by vince62s** [comment]
Just as a sanity check can you please retrain from scratch without -pre_word_vecs_enc -fix_word_vecs_enc
save after afew steps, and then do a train_from ?
thanks

**Comment by murthyrudra** [comment]
Hi, If I train without specifying pre-trained word embeddings using `pre_word_vecs_enc` and the `-fix_word_vecs_enc` option and retraining using `-train_from`, the model works well. There is no error and the perplexity values seems good.

Now, I tried specifying only pre-trained word embeddings using `pre_word_vecs_enc` and retraining after some steps, the model works well, with no error. The problem arises only when I specify the argument `fix_word_vecs_enc`. 
Thanks

**Comment by fuzhenxin** [comment]
The problem has beed solved by pull request #1211
