### ISSUE TITLE
torchtext.data.Field doesn't have keyword argument "dtype"

### ISSUE THREAD

**Issue by HualeiZhuu** [OpenNMT/OpenNMT-py#951]
When I run the prerogress.py, a type error occurred as follows：
File "preprocess.py", line 211, in <module>
    main()
  File "preprocess.py", line 198, in main
    fields = inputters.get_fields(opt.data_type, src_nfeats, tgt_nfeats)
  File "/home/team308/notespace/zhuhualei/OpenNMT-py-master/onmt/inputters/inputter.py", line 48, in get_fields
    return TextDataset.get_fields(n_src_features, n_tgt_features)
  File "/home/team308/notespace/zhuhualei/OpenNMT-py-master/onmt/inputters/text_dataset.py", line 244, in get_fields
    postprocessing=make_src, sequential=False)
TypeError: __init__() got an unexpected keyword argument 'dtype'

I use PyTorch 0.4.1, python3.6, I tried torchtext 0.3.0 and torchtext0.2.3, the error is same.

I do not know which torchtext version has the parameter "dtype".

**Comment by vince62s** [comment]
with torchtext 0.3.0 / pytorch >=0.4.0 you should not have this issue.

**Comment by HualeiZhuu** [comment]
My pytorch version is 0.4.1 without GPU, torchtext is 0.3.0, python is 3.6.
The error did not change.

**Comment by vince62s** [comment]
cuda version ? postyour command line and your "pip list | grep torch"

also maybe try to replicate the command line in the travis file to check if this is working with the test dataset.

**Comment by HualeiZhuu** [comment]
Thanks!
Problem was resolved!
After I uninstalled torchtext 0.2.3, my torchtext became 0.3.0. And the error has gone.
