### ISSUE TITLE
[Bug] tools/test_rouge.py doesn't work

### ISSUE THREAD

**Issue by magician-david** [OpenNMT/OpenNMT-py#953]
The bug seems to be caused by this commit:
[Refactoring Translator and introducing make_translator](https://github.com/OpenNMT/OpenNMT-py/commit/b8d8072fa4d8b9a72cca5c352efa224a407e9214#diff-0a9225e89d70f9dac721c782cbf8bcdb)

In the function test_rouge(cand, ref), cand and ref should be file objects, rather than file path strings. 

Issue #776 also report this problem.

**Comment by vince62s** [comment]
@pltrdy if you can have a look , thanks.

**Comment by magician-david** [comment]
@pltrdy It would be better if the files are opened with the "utf-8" encoding, thanks!

**Comment by pltrdy** [comment]
@magician-david updated.
