### ISSUE TITLE
Error while trying to run server.py

### ISSUE THREAD

**Issue by starnleymbote** [OpenNMT/OpenNMT-py#956]
i get an error message that say: AttributeError: 'dict' object has no attribute 'log_file'

below is the whole error log whenever i run the server.py file

Pre-loading model 1230
Traceback (most recent call last):
  File "server.py", line 115, in <module>
    debug=args.debug)
  File "server.py", line 24, in start
    translation_server.start(config_file)
  File "/home/stano/OpenNMT-py/onmt/translate/translation_server.py", line 75, in start
    self.preload_model(opt, model_id=model_id, **kwargs)
  File "/home/stano/OpenNMT-py/onmt/translate/translation_server.py", line 111, in preload_model
    model = ServerModel(opt, model_id, **model_kwargs)
  File "/home/stano/OpenNMT-py/onmt/translate/translation_server.py", line 178, in __init__
    self.logger = init_logger(opt.log_file)
AttributeError: 'dict' object has no attribute 'log_file'

Any idea on how i can resolve this

**Comment by pltrdy** [comment]
Hi,

It seems like you are not running current version of the code. Pulling master is likely to solve your problem.

Paul

**Comment by Henry-E** [comment]
Is there a more up-to-date set of instructions for running the server than http://forum.opennmt.net/t/simple-opennmt-py-rest-server/1392 ?

**Comment by vince62s** [comment]
no, it's pretty straight forward, but we need to update some doc because we included the possibility to use the pyonmt tokenizer, which changed a bit the syntax of the config json.

**Comment by pltrdy** [comment]
@Henry-E 

I just wrote an update, do not hesitate to try and tell me what you think of it.
http://forum.opennmt.net/t/simple-opennmt-py-rest-server/1392/4?u=pltrdy

**Comment by starnleymbote** [comment]
Thanks. I'll try it then give you a feedback

**Comment by starnleymbote** [comment]
I will appreciate it.
