### ISSUE TITLE
How to solve training when the memory is relatively large

### ISSUE THREAD

**Issue by lijun20** [OpenNMT/OpenNMT-py#963]
4.0G nmt.train.1.pt
2.9M nmt.valid.1.pt
47M  nmt.vocab.pt

The system has 64G of memory, and the training is that the memory is filled up and killed by the system，How should I solve it ?

**Comment by ruidongtd** [comment]
change `batch_size`

**Comment by vince62s** [comment]
read this
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/opts.py#L160
bear in mind we may change this option according to #957
