### ISSUE TITLE
Vocab.pt file and preprocessing options missing for pre-trained OpenSubtitles

### ISSUE THREAD

**Issue by kstats** [OpenNMT/OpenNMT-py#974]
I'm trying to fine-tune the pre-trained OpenSubtitles model (http://opennmt.net/Models-py/) on my own dataset, but the OpenSubtitles dataset does not contain the vocab.pt file or the preprocessing command line options.  Is there a place that I'm missing to look for this?  Thanks!

**Comment by vince62s** [comment]
you'd better retrain from scratch because master has changed a lot since.
