### ISSUE TITLE
Query regarding monolithic_compute_loss

### ISSUE THREAD

**Issue by ratishsp** [OpenNMT/OpenNMT-py#975]
Hi,
I was facing memory issues while running validation monolithic_compute_loss. It is similar to #476. I am able to get around the issue by using a smaller valid_batch_size. I wanted to know why monolithic_compute_loss doesn't compute loss in shards as is done during training.
https://github.com/OpenNMT/OpenNMT-py/blob/fea19ef103bfdae10a268c7c1b3f63a9e1a3701f/onmt/utils/loss.py#L107
That should resolve the memory issue.

**Comment by vince62s** [comment]
No specific reason. Before the token mode, we had to restrict to shorter sentences, hence the valid batch size was not an issue.
We did not switch the validation to token mode (tricky) so yes, at atimes if you did not filter long sequences, you may have a memory issue. I don't think it is a problem to reduce the valid batch size. it's ot so much time consuming.
