### ISSUE TITLE
Sharding and the meaning of -shard_size

### ISSUE THREAD

**Issue by gchrupala** [OpenNMT/OpenNMT-py#979]
I am very confused about what the -shard_size option means. How do I disable sharing and just create a single file with all the examples? I am specifically trying to work with an audio model. 

For example, using the commands from http://opennmt.net/OpenNMT-py/speech2text.html

The input file with training data has 948 examples:
```
(OPENNMT) gchrupal@green:/roaming/gchrupal/OPENNMT/OpenNMT-py$ wc -l data/speech/tgt-train.txt
948 data/speech/tgt-train.txt

```
Using shard_size=300 as on the webpage, creates 4 .pt files, with total 943 examples:

```
(OPENNMT) gchrupal@green:/roaming/gchrupal/OPENNMT/OpenNMT-py$ python preprocess.py -data_type audio -src_dir data/speech/an4_dataset -train_src data/speech/src-train.txt -train_tgt data/speech/tgt-train.txt -valid_src data/speech/src-val.txt -valid_tgt data/speech/tgt-val.txt -shard_size 300 -save_data data/speech/demo
```
```
(OPENNMT) gchrupal@green:/roaming/gchrupal/OPENNMT/OpenNMT-py$ python -c 'import torch; print(sum(len(torch.load("data/speech/demo.train.{}.pt".format(i))) for i in range(4)))'
943
```

Setting shard_size=0 creates a single .pt file with 943 examples. Omitting the shard_size option altogether creates 4 .pt files with a total of 1586 examples. What is going on? How can I get a single .pt file with all and only the original 948 examples?

**Comment by vince62s** [comment]
-shard_size is the number of examples per shard, except for the last one.
But maybe there is a another option https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/opts.py#L210-L219
filtering some examples.
can you check ?

**Comment by gchrupala** [comment]
The option -tgt_seq_length was filtering some examples out: setting it to a large number, and -shard_size=0 generates a single file with all the examples. Thanks for the pointer.

But there is still something strange happening with when omitting the shard_size option altogether creates multiple .pt files with a total number of examples exceeding the actual number of examples in the input file.

**Comment by vince62s** [comment]
ok thanks, I'll check.

**Comment by vince62s** [comment]
the reason is that some intermediary txt files are not cleaned up, so it aggregates them during the .pt files generation.

**Comment by vince62s** [comment]
fixed.
