### ISSUE TITLE
Initialize models before loading data

### ISSUE THREAD

**Issue by shuoyangd** [OpenNMT/OpenNMT-py#98]
I noticed that it takes almost 3 minutes for me for a training job to run from the beginning to call `model.cuda()`. This causes problems for people running their jobs on a multi-gpu shared host, because first one finds a free gpu, pass it through option `-gpus x`, and in these 3 minutes, someone else could have taken this free gpu. So by the time `model.cuda()` is called, this gpu is no longer available.

I looked at the code in the main method of `train.py` and conjecture the mass of time is spent on loading data. So I assume this problem will be worse when I use even larger dataset (FYI my current dataset is only 2M sentences). 

I wonder if it is possible to re-organize the code in the main method so we can load data after `model.cuda()`? It seems to me that the only dependency is the following line:

```
assert("type" not in dataset or dataset["type"] == "img")
```

But is this really necessary?

Thanks!

**Comment by srush** [comment]
Sure, want to send a PR?

**Comment by shuoyangd** [comment]
@srush I tried what I proposed but ended up with a little bit messy code. So I explored another solution and it seems to be cleaner.

The idea is that we still load the data before `model.cuda()`, but if we are using gpu, we should load the data directly to whatever gpu we'll be using.

The code for the solution is in PR #102 . FYI I only tested this on CPU and single GPU and it seems to work for me -- GPU device seems to be occupied as long as data loading has started. I cannot reserve multiple device on the same machine for the moment so multi-GPU case is not tested.

**Comment by srush** [comment]
Hmm, I don't think I like this solution. The whole idea of dataset is not to load the data onto the gpu, but instead each batch individually.

**Comment by shuoyangd** [comment]
So the problem I had for the first proposal is that `onmt.Models.Encoder` and `onmt.Models.Decoder` both depends on `dicts`, which is part of `dataset`. But if you look closer only their size is actually used. So I wonder if it'll be nice to change this to a integer argument so we can decouple model initialization from data loading. But it affects some interface design so maybe you should decide whether this is more desirable.

**Comment by srush** [comment]
Okay. I think the best option is to load the dicts first. Then the models, and then the data. Let me know if you want to try this, or I can add it.

**Comment by srush** [comment]
The idea would be to change the dataset constructor to just load dicts, and then have a separate load data. Or maybe even easier have the load data be called lazily on first access.

**Comment by shuoyangd** [comment]
@srush Sounds good. I can give it a try.

**Comment by srush** [comment]
Oh actually, I see what you mean now. This is harder than I thought. Let me see if there is something else I can do.

**Comment by shuoyangd** [comment]
Right now when one runs `preprocess.py`, there is actually source and target dictionaries generated in text format. These dictionaries seem to be ignored when we load the serialized data (because serialized data have dictionaries as well). If we are to load dictionaries separately, we could load from text files.

I'm not yet sure what these text dictionaries generated for and whether they are the same as the binary serialized version. Maybe you could give me an answer?

**Comment by guillaumekln** [comment]
> I'm not yet sure what these text dictionaries generated for and whether they are the same as the binary serialized version.

They are generated so that they can be reused for another training. They are the same as the vocabularies serialized within the data package.

**Comment by shuoyangd** [comment]
Thanks @guillaumekln! That's very helpful.

**Comment by srush** [comment]
Think this should be fixed in the new code. We now can load dicts separately from data.

**Comment by eeric** [comment]
make OpenNMT project audio list and sentences text list, as following:
https://github.com/eeric/OpenNMT-py-make-tgt-train.txt/blob/master/openNMT_make_label.py
