### ISSUE TITLE
#759 breaks ensembling

### ISSUE THREAD

**Issue by bpopeters** [OpenNMT/OpenNMT-py#992]
RNN encoders used to return a 2-tuple in the forward pass consisting of the rnn output and the memory bank. Now it returns a 3-tuple consisting of those two things and the lengths argument passed to the function. But the ensemble encoder still expects the individual encoder output tuples to be of size 2 and consequently breaks. What is the rationale for this new encoder behavior? In my experiments the memory bank and the lenghts have the same value.

**Comment by vince62s** [comment]
That was my request in #759 to eliminate a specific case  and therefore to make all interfaces the same.
@da03 we forgot the impact on the ensemble.py script,if you have time.
Thanks.

**Comment by bpopeters** [comment]
#993
